/**
 * entityTypeRegistry.ts
 *
 * Centralized registry of all document types, their frontmatter fields,
 * folder conventions, and grouping. This is the source of truth for
 * auto-generating the Data Dictionary reference document.
 *
 * Adding a new document type? Add it here and it will appear in the
 * generated Data Dictionary on next build.
 */

export interface FieldMeta {
	name: string;
	type: string;
	required: boolean;
	description: string;
}

export interface EntityTypeMeta {
	typeName: string;
	group: "catalog" | "data-exchange" | "special";
	tab: string;
	folder: string;
	nameField: string;
	filePattern: string;
	description: string;
	fields: FieldMeta[];
}

export const ENTITY_TYPE_REGISTRY: EntityTypeMeta[] = [
	// ── Event Catalog Entity Types ──────────────────
	{
		typeName: "EventDoc",
		group: "catalog",
		tab: "Events",
		folder: "Events/",
		nameField: "event",
		filePattern: "{docsRoot}/Events/{eventType}.md",
		description: "Event documentation with payload shape, usage guidance, and operational notes",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "event", type: "string", required: true, description: "Event type identifier (e.g., user.created)" },
			{ name: "description", type: "string", required: false, description: "Brief description of the event" },
			{ name: "category", type: "string", required: false, description: "Event category" },
			{ name: "direction", type: "string", required: false, description: "Data flow direction" },
			{ name: "domain", type: "string", required: false, description: "Domain that owns this event" },
			{ name: "services", type: "string", required: false, description: "Service(s) that emit or handle this event" },
			{ name: "stability", type: "string", required: false, description: "Contract stability level" },
			{ name: "visibility", type: "string", required: false, description: "Intended audience" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "DomainDoc",
		group: "catalog",
		tab: "Domains",
		folder: "Domains/",
		nameField: "domain",
		filePattern: "{docsRoot}/Domains/{domainName}.md",
		description: "Business domain overview with related services, categories, and events",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "domain", type: "string", required: true, description: "Domain name" },
			{ name: "eventCount", type: "number", required: false, description: "Number of events in this domain" },
			{ name: "categories", type: "string[]", required: false, description: "Event categories covered" },
			{ name: "services", type: "string[]", required: false, description: "Services in this domain" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ArchitectureDoc",
		group: "catalog",
		tab: "Domains",
		folder: "Domains/",
		nameField: "domain",
		filePattern: "{docsRoot}/Domains/{domainName}.architecture.md",
		description: "Arc42 + C4 architecture document for a domain",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "domain", type: "string", required: true, description: "Domain name" },
			{ name: "eventCount", type: "number", required: false, description: "Number of events" },
			{ name: "categories", type: "string[]", required: false, description: "Event categories" },
			{ name: "services", type: "string[]", required: false, description: "Related services" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ServiceDoc",
		group: "catalog",
		tab: "Services",
		folder: "Services/",
		nameField: "service",
		filePattern: "{docsRoot}/Services/{serviceName}.md",
		description: "Service overview with related domains and events",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "service", type: "string", required: true, description: "Service name" },
			{ name: "eventCount", type: "number", required: false, description: "Number of events handled" },
			{ name: "domains", type: "string[]", required: false, description: "Domains this service belongs to" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ServiceBlueprintDoc",
		group: "catalog",
		tab: "Services",
		folder: "Services/",
		nameField: "service",
		filePattern: "{docsRoot}/Services/{serviceName}.blueprint.md",
		description: "Detailed service blueprint with user interactions and data flows",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "service", type: "string", required: true, description: "Service name" },
			{ name: "eventCount", type: "number", required: false, description: "Number of events" },
			{ name: "domains", type: "string[]", required: false, description: "Related domains" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "CategoryDoc",
		group: "catalog",
		tab: "Events",
		folder: "Categories/",
		nameField: "category",
		filePattern: "{docsRoot}/Categories/{categoryName}.md",
		description: "Event category grouping with related domains and services",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "category", type: "string", required: true, description: "Category name" },
			{ name: "eventCount", type: "number", required: false, description: "Number of events" },
			{ name: "domains", type: "string[]", required: false, description: "Related domains" },
			{ name: "services", type: "string[]", required: false, description: "Related services" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "FlowDoc",
		group: "catalog",
		tab: "Flows",
		folder: "Flows/",
		nameField: "flow",
		filePattern: "{docsRoot}/Flows/{flowName}.md",
		description: "Business flow with ordered event sequence, domains, and services",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "flow", type: "string", required: true, description: "Flow name" },
			{ name: "description", type: "string", required: false, description: "Brief flow description" },
			{ name: "events", type: "string[]", required: false, description: "Ordered event types" },
			{ name: "domains", type: "string[]", required: false, description: "Domains involved" },
			{ name: "services", type: "string[]", required: false, description: "Services participating" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "SystemDoc",
		group: "catalog",
		tab: "Systems",
		folder: "Systems/",
		nameField: "system",
		filePattern: "{docsRoot}/Systems/{systemName}.md",
		description: "External system documentation with linked domains and services",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "system", type: "string", required: true, description: "System name" },
			{ name: "description", type: "string", required: false, description: "Brief system description" },
			{ name: "domains", type: "string[]", required: false, description: "Related domains" },
			{ name: "services", type: "string[]", required: false, description: "Related services" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ActorDoc",
		group: "catalog",
		tab: "Actors",
		folder: "Actors/",
		nameField: "actor",
		filePattern: "{docsRoot}/Actors/{actorName}.md",
		description: "User persona documentation with goals, key events, and interactions",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "actor", type: "string", required: true, description: "Actor/persona name" },
			{ name: "description", type: "string", required: false, description: "Brief actor description" },
			{ name: "events", type: "string[]", required: false, description: "Key events" },
			{ name: "domains", type: "string[]", required: false, description: "Domains interacted with" },
			{ name: "services", type: "string[]", required: false, description: "Services relied on" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ProductDoc",
		group: "catalog",
		tab: "Products",
		folder: "Products/",
		nameField: "product",
		filePattern: "{docsRoot}/Products/{productName}.md",
		description: "Product documentation with linked events, domains, and services",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "product", type: "string", required: true, description: "Product name" },
			{ name: "description", type: "string", required: false, description: "Brief product description" },
			{ name: "events", type: "string[]", required: false, description: "Key product events" },
			{ name: "domains", type: "string[]", required: false, description: "Domains spanned" },
			{ name: "services", type: "string[]", required: false, description: "Services relied on" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	// ── Data Exchange Types ──────────────────────────
	{
		typeName: "CsvDoc",
		group: "data-exchange",
		tab: "Reports",
		folder: "Reports/",
		nameField: "name",
		filePattern: "{docsRoot}/Reports/CSV - {csvName}.md",
		description: "CSV file documentation with column headers, row count, and delimiter",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "csvFile", type: "string", required: true, description: "Wikilink to CSV file" },
			{ name: "filePath", type: "string", required: true, description: "Full vault path" },
			{ name: "name", type: "string", required: true, description: "Filename" },
			{ name: "description", type: "string", required: false, description: "User-provided description" },
			{ name: "columns", type: "number", required: false, description: "Number of columns" },
			{ name: "rows", type: "number", required: false, description: "Number of data rows" },
			{ name: "delimiter", type: "string", required: false, description: "Column delimiter" },
			{ name: "headers", type: "string[]", required: false, description: "Column header names" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "PropertyDoc",
		group: "data-exchange",
		tab: "Properties",
		folder: "Properties/",
		nameField: "property",
		filePattern: "{docsRoot}/Properties/Property - {propertyName}.md",
		description: "Frontmatter property documentation with CSV column mappings",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "property", type: "string", required: true, description: "Frontmatter property name" },
			{ name: "description", type: "string", required: false, description: "Property description" },
			{ name: "csvColumns", type: "string[]", required: false, description: "CSV columns that map to this property" },
			{ name: "configs", type: "string[]", required: false, description: "Config names using this property" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "TypeDoc",
		group: "data-exchange",
		tab: "Types",
		folder: "Types/",
		nameField: "name",
		filePattern: "{docsRoot}/Types/Type - {typeName}.md",
		description: "Note type definition with expected properties and lifecycle events",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "name", type: "string", required: true, description: "Note type name" },
			{ name: "description", type: "string", required: false, description: "Type description" },
			{ name: "properties", type: "string[]", required: false, description: "Expected frontmatter properties" },
			{ name: "pipelines", type: "number", required: false, description: "Configs referencing this type" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ImportConfigDoc",
		group: "data-exchange",
		tab: "Imports",
		folder: "Configs/",
		nameField: "name",
		filePattern: "{docsRoot}/Configs/Import - {configName}.md",
		description: "Import configuration with column mappings and settings",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "configId", type: "string", required: true, description: "UUID of the saved config" },
			{ name: "name", type: "string", required: true, description: "Config display name" },
			{ name: "targetFolder", type: "string", required: false, description: "Vault path for created notes" },
			{ name: "nameColumn", type: "string", required: false, description: "CSV column for note filenames" },
			{ name: "namePrefix", type: "string", required: false, description: "Filename prefix" },
			{ name: "nameSuffix", type: "string", required: false, description: "Filename suffix" },
			{ name: "conflictStrategy", type: "string", required: false, description: "How to handle existing files" },
			{ name: "columns", type: "number", required: false, description: "Total column mappings" },
			{ name: "includedColumns", type: "number", required: false, description: "Enabled column mappings" },
			{ name: "noteType", type: "string", required: false, description: "Note type assignment" },
			{ name: "sourcePath", type: "string", required: false, description: "Path to source CSV" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "ExportConfigDoc",
		group: "data-exchange",
		tab: "Exports",
		folder: "Configs/",
		nameField: "name",
		filePattern: "{docsRoot}/Configs/Export - {configName}.md",
		description: "Export configuration with columns and output settings",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "configId", type: "string", required: true, description: "UUID of the saved config" },
			{ name: "name", type: "string", required: true, description: "Config display name" },
			{ name: "sourcePath", type: "string", required: false, description: "Folder or .base file path" },
			{ name: "sourceType", type: "string", required: false, description: "Source type: folder or base" },
			{ name: "format", type: "string", required: false, description: "Output format: csv or tab" },
			{ name: "outputPath", type: "string", required: false, description: "Output file path" },
			{ name: "columns", type: "number", required: false, description: "Frontmatter columns exported" },
			{ name: "fileProperties", type: "number", required: false, description: "File metadata properties exported" },
			{ name: "conflictStrategy", type: "string", required: false, description: "How to handle existing output" },
			{ name: "isExternal", type: "boolean", required: false, description: "Output is outside the vault" },
			{ name: "noteType", type: "string", required: false, description: "Note type filter" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
		],
	},
	{
		typeName: "PipelineConfigDoc",
		group: "data-exchange",
		tab: "Pipelines",
		folder: "Configs/",
		nameField: "name",
		filePattern: "{docsRoot}/Configs/Pipeline - {pipelineName}.md",
		description: "Multi-import pipeline with sources and export steps",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "configId", type: "string", required: true, description: "UUID of the pipeline" },
			{ name: "name", type: "string", required: true, description: "Pipeline display name" },
			{ name: "description", type: "string", required: false, description: "Pipeline description" },
			{ name: "targetFolder", type: "string", required: false, description: "Vault path for merged notes" },
			{ name: "mergeKey", type: "string", required: false, description: "Frontmatter key for merge" },
			{ name: "noteType", type: "string", required: false, description: "Note type" },
			{ name: "namePrefix", type: "string", required: false, description: "Filename prefix" },
			{ name: "nameSuffix", type: "string", required: false, description: "Filename suffix" },
			{ name: "exportConfigIds", type: "string[]", required: false, description: "Export config UUIDs for post-import" },
			{ name: "sources", type: "number", required: false, description: "Number of CSV sources" },
			{ name: "created", type: "ISO timestamp", required: false, description: "Creation date" },
			{ name: "lastExecuted", type: "ISO timestamp", required: false, description: "Last execution time" },
		],
	},
	// ── Special Types ────────────────────────────────
	{
		typeName: "AreaDoc",
		group: "special",
		tab: "N/A",
		folder: "02 - Areas/",
		nameField: "area",
		filePattern: "02 - Areas/{areaName}/{areaName}.md",
		description: "PARA area document created from Mark as Area on a domain",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "area", type: "string", required: true, description: "Area name" },
			{ name: "domain", type: "string", required: false, description: "Parent domain name" },
			{ name: "description", type: "string", required: false, description: "Area description" },
		],
	},
	{
		typeName: "ProjectBrief",
		group: "special",
		tab: "N/A",
		folder: "01 - Projects/",
		nameField: "project",
		filePattern: "01 - Projects/{projectName}/{projectName}.md",
		description: "Project brief document with goals, timeline, and status",
		fields: [
			{ name: "type", type: "string", required: true, description: "Document type discriminator" },
			{ name: "project", type: "string", required: false, description: "Project name" },
			{ name: "goal", type: "string", required: false, description: "Primary project goal" },
			{ name: "description", type: "string", required: false, description: "Project description" },
			{ name: "status", type: "string", required: false, description: "Current project status" },
			{ name: "start", type: "string", required: false, description: "Start date" },
			{ name: "end", type: "string", required: false, description: "End date" },
		],
	},
	{
		typeName: "Event",
		group: "special",
		tab: "N/A",
		folder: "Anywhere",
		nameField: "name",
		filePattern: "Anywhere in vault",
		description: "User-defined custom event file discovered by EventBridge",
		fields: [
			{ name: "type", type: "string", required: true, description: 'Must be exactly "Event"' },
			{ name: "name", type: "string", required: false, description: "Explicit event name (defaults to filename-derived)" },
		],
	},
];
