/**
 * graphic-registry.ts — Named canvas draw functions for scene objects.
 *
 * Each registered graphic maps a string name to a factory that creates
 * an ex.Canvas with the object's visual. Extracted from the individual
 * actor class constructors so GenericInteractable can look them up by name.
 */

import * as ex from "excalibur";

type DrawFn = (width: number, height: number, hovered: boolean) => ex.Canvas;

const registry = new Map<string, DrawFn>();

function registerGraphic(name: string, fn: DrawFn): void {
	registry.set(name, fn);
}

export function getGraphic(name: string): DrawFn | undefined {
	return registry.get(name);
}

export function getGraphicNames(): readonly string[] {
	return [...registry.keys()];
}

// ── Food Bowl ────────────────────────────────────────────────
registerGraphic("food-bowl", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "rgba(0, 0, 0, 0.12)";
		ctx.beginPath();
		ctx.ellipse(16, 24, 13, 5, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#5c4a35";
		ctx.beginPath();
		ctx.ellipse(16, 20, 14, 8, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#6b5a45";
		ctx.beginPath();
		ctx.ellipse(16, 19, 12, 6, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#4e3d2a";
		ctx.beginPath();
		ctx.ellipse(16, 19, 10, 5, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.ellipse(13, 18, 4, 2, -0.3, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#8b4513";
		ctx.beginPath();
		ctx.ellipse(19, 19, 3, 2, 0.2, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#22c55e";
		ctx.beginPath();
		ctx.arc(16, 17, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.strokeStyle = "rgba(107, 90, 69, 0.4)";
		ctx.lineWidth = 0.5;
		ctx.beginPath();
		ctx.arc(16, 20, 13, 0.2, 1.2);
		ctx.stroke();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "7px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Food", 16, 32);
	}});
});

// ── Water Bowl ───────────────────────────────────────────────
registerGraphic("water-bowl", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "rgba(0, 0, 0, 0.12)";
		ctx.beginPath();
		ctx.ellipse(16, 24, 13, 5, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#6a6a6a";
		ctx.beginPath();
		ctx.ellipse(16, 20, 14, 8, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#7a7a7a";
		ctx.beginPath();
		ctx.ellipse(16, 19, 12, 6, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#555555";
		ctx.beginPath();
		ctx.ellipse(16, 19, 10, 5, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.ellipse(16, 18, 9, 4, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "rgba(147, 197, 253, 0.5)";
		ctx.beginPath();
		ctx.ellipse(13, 17, 4, 2, -0.3, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "rgba(255, 255, 255, 0.4)";
		ctx.beginPath();
		ctx.ellipse(11, 16, 2, 1, -0.4, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "rgba(90, 90, 90, 0.3)";
		ctx.beginPath();
		ctx.arc(8, 21, 0.6, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(22, 20, 0.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(20, 23, 0.7, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "7px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Water", 16, 32);
	}});
});

// ── Coffee Machine ───────────────────────────────────────────
registerGraphic("coffee-machine", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#5c4033";
		ctx.fillRect(6, 32, 4, 8);
		ctx.fillRect(22, 32, 4, 8);
		ctx.fillStyle = "#4e3628";
		ctx.fillRect(6, 34, 20, 3);
		ctx.fillStyle = "#3a3a3a";
		ctx.beginPath();
		ctx.moveTo(4, 16);
		ctx.quadraticCurveTo(2, 32, 6, 34);
		ctx.lineTo(26, 34);
		ctx.quadraticCurveTo(30, 32, 28, 16);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#4a4a4a";
		ctx.beginPath();
		ctx.ellipse(16, 16, 13, 4, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#1a6b3a";
		ctx.beginPath();
		ctx.ellipse(16, 17, 11, 3, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#22c55e";
		ctx.beginPath();
		ctx.arc(12, 16, 2, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(20, 15, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#a855f7";
		ctx.beginPath();
		ctx.arc(16, 14, 1.8, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(10, 14, 1, 0, Math.PI * 2);
		ctx.fill();
		ctx.strokeStyle = "rgba(180, 220, 180, 0.5)";
		ctx.lineWidth = 1;
		ctx.beginPath();
		ctx.moveTo(11, 12);
		ctx.quadraticCurveTo(9, 6, 11, 2);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(16, 11);
		ctx.quadraticCurveTo(18, 5, 16, 0);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(21, 12);
		ctx.quadraticCurveTo(23, 7, 21, 3);
		ctx.stroke();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Potions", width / 2, height + 10);
	}});
});

// ── Snack Table ──────────────────────────────────────────────
registerGraphic("snack-table", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#4e3628";
		ctx.fillRect(4, 30, 3, 10);
		ctx.fillRect(41, 30, 3, 10);
		ctx.fillStyle = "#5c4033";
		ctx.beginPath();
		ctx.arc(5, 39, 3, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(43, 39, 3, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#4e3628";
		ctx.beginPath();
		ctx.arc(5, 39, 1, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(43, 39, 1, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#5c4033";
		ctx.fillRect(2, 20, 44, 12);
		ctx.strokeStyle = "#4e3628";
		ctx.lineWidth = 0.5;
		ctx.beginPath();
		ctx.moveTo(2, 24);
		ctx.lineTo(46, 24);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(2, 28);
		ctx.lineTo(46, 28);
		ctx.stroke();
		ctx.fillStyle = "#3a2a1f";
		ctx.fillRect(2, 19, 44, 2);
		ctx.fillStyle = "#d4a574";
		ctx.beginPath();
		ctx.arc(10, 23, 4, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#c49464";
		ctx.beginPath();
		ctx.arc(10, 24, 3, 0, Math.PI);
		ctx.fill();
		ctx.fillStyle = "#ef4444";
		ctx.beginPath();
		ctx.arc(22, 24, 3.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#4e3628";
		ctx.fillRect(21, 20, 1.5, 2);
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.ellipse(36, 24, 6, 3, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.moveTo(42, 24);
		ctx.lineTo(45, 21);
		ctx.lineTo(45, 27);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.beginPath();
		ctx.arc(32, 23, 1, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Food", width / 2, height + 10);
	}});
});

// ── Water Cooler ─────────────────────────────────────────────
registerGraphic("water-cooler", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#5c4a35";
		ctx.beginPath();
		ctx.moveTo(4, 6);
		ctx.quadraticCurveTo(2, 6, 2, 10);
		ctx.lineTo(1, 20);
		ctx.quadraticCurveTo(1, 36, 4, 38);
		ctx.lineTo(20, 38);
		ctx.quadraticCurveTo(23, 36, 23, 20);
		ctx.lineTo(22, 10);
		ctx.quadraticCurveTo(22, 6, 20, 6);
		ctx.closePath();
		ctx.fill();
		ctx.strokeStyle = "#4e3d2a";
		ctx.lineWidth = 0.5;
		ctx.beginPath();
		ctx.moveTo(8, 7);
		ctx.lineTo(7, 37);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(12, 6);
		ctx.lineTo(12, 38);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(16, 7);
		ctx.lineTo(17, 37);
		ctx.stroke();
		ctx.fillStyle = "#6a6a6a";
		ctx.fillRect(2, 9, 20, 2);
		ctx.fillRect(1, 20, 22, 2);
		ctx.fillRect(2, 32, 20, 2);
		ctx.fillStyle = "#8a8a8a";
		ctx.beginPath();
		ctx.arc(5, 10, 0.8, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(19, 10, 0.8, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#4e3d2a";
		ctx.fillRect(3, 5, 18, 3);
		ctx.fillStyle = "#4a4a4a";
		ctx.fillRect(21, 22, 3, 2);
		ctx.fillRect(22, 21, 2, 4);
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.moveTo(23, 26);
		ctx.quadraticCurveTo(24, 28, 23, 29);
		ctx.quadraticCurveTo(22, 28, 23, 26);
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Water", width / 2, height + 10);
	}});
});

// ── Couch ────────────────────────────────────────────────────
registerGraphic("couch", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "rgba(0, 0, 0, 0.15)";
		ctx.beginPath();
		ctx.roundRect(3, 18, 60, 18, 4);
		ctx.fill();
		ctx.fillStyle = "#7b2d8b";
		ctx.beginPath();
		ctx.roundRect(2, 14, 60, 18, 4);
		ctx.fill();
		ctx.fillStyle = "#9b3dab";
		ctx.beginPath();
		ctx.roundRect(4, 14, 56, 12, 3);
		ctx.fill();
		ctx.strokeStyle = "#d4a017";
		ctx.lineWidth = 1.5;
		ctx.beginPath();
		ctx.roundRect(2, 14, 60, 18, 4);
		ctx.stroke();
		ctx.strokeStyle = "#c49417";
		ctx.lineWidth = 0.5;
		ctx.beginPath();
		ctx.roundRect(6, 17, 52, 12, 2);
		ctx.stroke();
		ctx.fillStyle = "#d4a017";
		ctx.beginPath();
		ctx.moveTo(32, 18);
		ctx.lineTo(38, 23);
		ctx.lineTo(32, 28);
		ctx.lineTo(26, 23);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#7b2d8b";
		ctx.beginPath();
		ctx.moveTo(32, 20);
		ctx.lineTo(36, 23);
		ctx.lineTo(32, 26);
		ctx.lineTo(28, 23);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#d4a017";
		ctx.beginPath();
		ctx.arc(5, 32, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(59, 32, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(5, 14, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.beginPath();
		ctx.arc(59, 14, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Rest", width / 2, height + 10);
	}});
});

// ── Plant ────────────────────────────────────────────────────
registerGraphic("plant", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#8b6c4a";
		ctx.beginPath();
		ctx.moveTo(4, 18);
		ctx.lineTo(5, 27);
		ctx.lineTo(15, 27);
		ctx.lineTo(16, 18);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#6b5236";
		ctx.fillRect(3, 17, 14, 3);
		ctx.fillStyle = "#9b7c5a";
		ctx.fillRect(4, 18, 3, 8);
		ctx.fillStyle = "#3a2a1a";
		ctx.beginPath();
		ctx.ellipse(10, 19, 6, 2.5, 0, 0, Math.PI * 2);
		ctx.fill();
		ctx.strokeStyle = "#22c55e";
		ctx.lineWidth = 2.5;
		ctx.beginPath();
		ctx.moveTo(7, 18);
		ctx.lineTo(7, 4);
		ctx.stroke();
		ctx.strokeStyle = "#10b981";
		ctx.lineWidth = 2.5;
		ctx.beginPath();
		ctx.moveTo(10, 18);
		ctx.lineTo(10, 2);
		ctx.stroke();
		ctx.strokeStyle = "#22c55e";
		ctx.lineWidth = 2;
		ctx.beginPath();
		ctx.moveTo(13, 18);
		ctx.lineTo(13, 6);
		ctx.stroke();
		ctx.strokeStyle = "#16a34a";
		ctx.lineWidth = 1;
		ctx.beginPath();
		ctx.moveTo(6, 10);
		ctx.lineTo(8, 10);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(9, 7);
		ctx.lineTo(11, 7);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(9, 12);
		ctx.lineTo(11, 12);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(12, 11);
		ctx.lineTo(14, 11);
		ctx.stroke();
		ctx.fillStyle = "#22c55e";
		ctx.beginPath();
		ctx.moveTo(7, 5);
		ctx.lineTo(2, 2);
		ctx.lineTo(5, 7);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#10b981";
		ctx.beginPath();
		ctx.moveTo(10, 3);
		ctx.lineTo(14, 0);
		ctx.lineTo(12, 5);
		ctx.closePath();
		ctx.fill();
		ctx.beginPath();
		ctx.moveTo(10, 4);
		ctx.lineTo(5, 1);
		ctx.lineTo(8, 6);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#22c55e";
		ctx.beginPath();
		ctx.moveTo(13, 7);
		ctx.lineTo(17, 4);
		ctx.lineTo(15, 9);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Bamboo", width / 2, height + 10);
	}});
});

// ── Notice Board ─────────────────────────────────────────────
registerGraphic("notice-board", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#5c4033";
		ctx.fillRect(2, 2, 44, 36);
		ctx.strokeStyle = "#3a2a1f";
		ctx.lineWidth = 2;
		ctx.strokeRect(1, 1, 46, 38);
		ctx.fillStyle = "#3a2a1f";
		ctx.fillRect(2, 2, 44, 8);
		ctx.fillStyle = "#d4a017";
		ctx.font = "6px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("QUESTS", 24, 9);
		ctx.fillStyle = "#d4c4a0";
		ctx.fillRect(5, 13, 14, 10);
		ctx.strokeStyle = "#b0a080";
		ctx.lineWidth = 0.5;
		ctx.strokeRect(5, 13, 14, 10);
		ctx.fillStyle = "#c4b090";
		ctx.fillRect(22, 12, 16, 11);
		ctx.strokeStyle = "#b0a080";
		ctx.strokeRect(22, 12, 16, 11);
		ctx.fillStyle = "#d4c4a0";
		ctx.fillRect(6, 26, 12, 10);
		ctx.strokeStyle = "#b0a080";
		ctx.strokeRect(6, 26, 12, 10);
		ctx.fillStyle = "#c8b898";
		ctx.fillRect(21, 26, 18, 10);
		ctx.strokeStyle = "#b0a080";
		ctx.strokeRect(21, 26, 18, 10);
		ctx.strokeStyle = "#5c4a35";
		ctx.lineWidth = 0.5;
		ctx.beginPath();
		ctx.moveTo(7, 17);
		ctx.lineTo(17, 17);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(7, 19);
		ctx.lineTo(15, 19);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(24, 16);
		ctx.lineTo(36, 16);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(24, 18);
		ctx.lineTo(34, 18);
		ctx.stroke();
		ctx.fillStyle = "#ef4444";
		ctx.beginPath();
		ctx.arc(12, 14, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.arc(30, 13, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#ef4444";
		ctx.beginPath();
		ctx.arc(12, 27, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.arc(30, 27, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.strokeStyle = "rgba(58, 42, 31, 0.2)";
		ctx.lineWidth = 0.3;
		ctx.beginPath();
		ctx.moveTo(3, 15);
		ctx.lineTo(3, 35);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(45, 15);
		ctx.lineTo(45, 35);
		ctx.stroke();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Quests", width / 2, height + 10);
	}});
});

// ── Whiteboard ───────────────────────────────────────────────
registerGraphic("whiteboard", (width, height, _hovered) => {
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#3a2a1f";
		ctx.fillRect(0, 0, 64, 48);
		ctx.fillStyle = "#5c4033";
		ctx.fillRect(2, 2, 60, 44);
		ctx.fillStyle = "#d4c4a0";
		ctx.fillRect(4, 4, 56, 40);
		ctx.strokeStyle = "rgba(180, 160, 120, 0.3)";
		ctx.lineWidth = 0.5;
		for (let y = 8; y < 44; y += 4) {
			ctx.beginPath();
			ctx.moveTo(5, y);
			ctx.lineTo(59, y);
			ctx.stroke();
		}
		ctx.fillStyle = "#c4b090";
		ctx.fillRect(7, 7, 18, 14);
		ctx.strokeStyle = "#a09070";
		ctx.lineWidth = 0.5;
		ctx.strokeRect(7, 7, 18, 14);
		ctx.fillStyle = "#d4c4a0";
		ctx.fillRect(30, 8, 22, 12);
		ctx.strokeStyle = "#a09070";
		ctx.strokeRect(30, 8, 22, 12);
		ctx.fillStyle = "#c8b898";
		ctx.fillRect(8, 26, 16, 14);
		ctx.strokeStyle = "#a09070";
		ctx.strokeRect(8, 26, 16, 14);
		ctx.fillStyle = "#d0c098";
		ctx.fillRect(28, 28, 26, 12);
		ctx.strokeStyle = "#a09070";
		ctx.strokeRect(28, 28, 26, 12);
		ctx.strokeStyle = "#5c4a35";
		ctx.lineWidth = 0.8;
		ctx.beginPath();
		ctx.moveTo(9, 12);
		ctx.lineTo(22, 12);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(9, 15);
		ctx.lineTo(20, 15);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(32, 13);
		ctx.lineTo(48, 13);
		ctx.stroke();
		ctx.fillStyle = "#ef4444";
		ctx.beginPath();
		ctx.arc(16, 8, 2, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.arc(41, 9, 2, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#ef4444";
		ctx.beginPath();
		ctx.arc(16, 27, 2, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#3b82f6";
		ctx.beginPath();
		ctx.arc(41, 29, 2, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#d4a017";
		ctx.fillRect(0, 0, 4, 4);
		ctx.fillRect(60, 0, 4, 4);
		ctx.fillRect(0, 44, 4, 4);
		ctx.fillRect(60, 44, 4, 4);
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "8px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Scrolls", width / 2, height + 10);
	}});
});

// ── Merchant Stall ───────────────────────────────────────────
registerGraphic("merchant-stall", (width, height, hovered) => {
	const borderColor = hovered ? "#f5c542" : "#DAA520";
	return new ex.Canvas({ width, height, draw: (ctx) => {
		ctx.fillStyle = "#4e3628";
		ctx.fillRect(3, 4, 4, 44);
		ctx.fillRect(41, 4, 4, 44);
		ctx.fillStyle = "#7b2d8b";
		ctx.fillRect(0, 2, 48, 14);
		ctx.fillStyle = "#3b82f6";
		ctx.fillRect(0, 2, 12, 14);
		ctx.fillRect(24, 2, 12, 14);
		ctx.fillStyle = borderColor;
		for (let i = 0; i < 6; i++) {
			ctx.beginPath();
			ctx.arc(4 + i * 8, 16, 4, 0, Math.PI);
			ctx.fill();
		}
		ctx.fillStyle = "#5c4033";
		ctx.fillRect(2, 22, 44, 8);
		ctx.fillStyle = "#6b5040";
		ctx.fillRect(2, 22, 44, 2);
		ctx.fillStyle = "#4e3628";
		ctx.fillRect(4, 30, 40, 18);
		ctx.strokeStyle = "#3a2a1f";
		ctx.lineWidth = 0.5;
		ctx.beginPath();
		ctx.moveTo(4, 36);
		ctx.lineTo(44, 36);
		ctx.stroke();
		ctx.beginPath();
		ctx.moveTo(4, 42);
		ctx.lineTo(44, 42);
		ctx.stroke();
		ctx.fillStyle = "#f59e0b";
		ctx.beginPath();
		ctx.arc(14, 26, 3, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#d4a017";
		ctx.beginPath();
		ctx.arc(14, 26, 1.5, 0, Math.PI * 2);
		ctx.fill();
		ctx.fillStyle = "#22c55e";
		ctx.beginPath();
		ctx.moveTo(26, 23);
		ctx.lineTo(29, 26);
		ctx.lineTo(26, 29);
		ctx.lineTo(23, 26);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#10b981";
		ctx.beginPath();
		ctx.moveTo(26, 24);
		ctx.lineTo(28, 26);
		ctx.lineTo(26, 28);
		ctx.lineTo(24, 26);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#c0392b";
		ctx.beginPath();
		ctx.moveTo(37, 23);
		ctx.lineTo(40, 26);
		ctx.lineTo(37, 29);
		ctx.lineTo(34, 26);
		ctx.closePath();
		ctx.fill();
		ctx.fillStyle = "#f5f5f4";
		ctx.font = "7px sans-serif";
		ctx.textAlign = "center";
		ctx.fillText("Shop", 24, 12);
	}});
});
