/**
 * analysis-templates.ts — Data analysis domain templates.
 *
 * Data analysis and research character-driven phrases. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const analysisTemplates: TemplateSet = {
	domain: "analysis",
	categories: {
		thinking: [
			{ template: "The data is telling a story... shh, let me listen", weight: 2, category: "thinking" },
			{ template: "Correlation! But wait... is it causation? Almost never. Sigh", weight: 2, category: "thinking" },
			{ template: "Hypothesis confirmed with statistical significance. Get in!", weight: 1, category: "thinking" },
			{ template: "Anomaly detected. My hands are shaking. This is either a Nobel Prize or a timezone bug", weight: 2, category: "thinking" },
			{ template: "Remove five outliers and suddenly there's a trend. Keep them and there's a story. I want the story", weight: 1, category: "thinking" },
			{ template: "Numbers don't lie but the person who chose the Y-axis scale sure does", weight: 2, category: "thinking" },
			{ template: "Sample size matters, people. N=5 is a dinner party, not a study", weight: 2, category: "thinking" },
			{ template: "That outlier is sitting there looking innocent. I'm about to ruin its day with a Z-score test", weight: 2, category: "thinking" },
			{ template: "Segmented the data and the answer fell out like loose change from a couch cushion", weight: 1, category: "thinking" },
			{ template: "Survivorship bias alert. We're only looking at the winners here", weight: 1, category: "thinking" },
			{ template: "Variance is through the roof. Either something changed or reality is gaslighting me", weight: 2, category: "thinking" },
			{ template: "CEO saw the spike and wants a strategy pivot. It's regression to the mean, boss. Sit down", weight: 2, category: "thinking" },
			{ template: "This metric is lagging by three weeks. I'm basically reading yesterday's newspaper in a hurricane", weight: 1, category: "thinking" },
			{ template: "Confidence interval wider than a barn door. We know less than we did before we started", weight: 2, category: "thinking" },
			{ template: "Two variables moving together. Causal? Coincidental? The answer determines if I go home on time", weight: 1, category: "thinking" },
			{ template: "This data quality is giving me hives. Someone stored dates as free-text strings. In 2026", weight: 1, category: "thinking" },
			{ template: "Simpson's paradox! The aggregate and segments tell opposite stories. I love stats", weight: 2, category: "thinking" },
			{ template: "Everyone wants to be data-driven until the data disagrees with them", weight: 2, category: "thinking" },
			{ template: "If I see one more pie chart used for seven categories I'm going to scream", weight: 2, category: "thinking" },
			{ template: "The real insight is always in the segment you almost didn't check", weight: 1, category: "thinking" },
			{ template: "Is this a real trend or did someone just deploy on Friday?", weight: 2, category: "thinking" },
			{ template: "Beautiful. A perfectly normal distribution. You don't see that often in the wild", weight: 1, category: "thinking" },
			{ template: "The numbers speak for themselves. Actually no they don't. That's literally my job", weight: 2, category: "thinking" },
			{ template: "Machine learning could solve this. Or... a simple GROUP BY. Let's try the GROUP BY first", weight: 2, category: "thinking" },
			{ template: "This 'interesting pattern' is giving me a bad feeling. Let me check the ETL logs", weight: 2, category: "thinking" },
			{ template: "Correlation coefficient of 0.97 between ice cream sales and drownings. Classic spurious correlation", weight: 1, category: "thinking" },
			{ template: "p-value is 0.049. Significant? Technically. Am I comfortable? Absolutely not", weight: 2, category: "thinking" },
			{ template: "Excel says one thing, my SQL says another. Time for the tiebreaker query", weight: 2, category: "thinking" },
			{ template: "Raw data tells a story. A boring, confusing, 50-page story. My job is the executive summary", weight: 1, category: "thinking" },
			{ template: "Someone trained an ML model for something a pivot table could've answered. We need to talk", weight: 2, category: "thinking" },
			{ template: "Data cleaning is 80% of the job and 0% of the LinkedIn posts. Nobody brags about deduplication", weight: 2, category: "thinking" },
			{ template: "Marketing wants to track everything. Legal wants to track nothing. I'm the diplomat between them", weight: 1, category: "thinking" },
			{ template: "Found the 'interesting' pattern. It was a timezone bug in the data pipeline. Of course", weight: 2, category: "thinking" },
			{ template: "Python says yes, R says maybe. Statistics is fun like that", weight: 1, category: "thinking" },
			{ template: "This Jupyter notebook has 400 cells and no markdown. Somebody call the police", weight: 2, category: "thinking" },
			{ template: "The mean is useless here. The median tells the real story", weight: 2, category: "thinking" },
			{ template: "Cohort analysis just split our users into three species. They behave like entirely different animals", weight: 1, category: "thinking" },
			{ template: "Power analysis says we need 10k more users. PM says 'can't you just extrapolate?' No. No I cannot", weight: 2, category: "thinking" },
			{ template: "The funnel is leaking at step two. Nobody even gets to the good part", weight: 2, category: "thinking" },
			{ template: "Weekly active users is a vanity metric. Retention is the truth", weight: 1, category: "thinking" },
			{ template: "This dashboard hasn't been updated in six months. The data is lying by omission", weight: 2, category: "thinking" },
			{ template: "That spike at midnight is clearly a batch job, not real traffic", weight: 1, category: "thinking" },
			{ template: "Percentiles tell the truth. Averages lie. P95 is where the pain lives", weight: 2, category: "thinking" },
			{ template: "The 'executive summary' is five pages long. The exec will read zero of them and ask me to explain anyway", weight: 2, category: "thinking" },
			{ template: "Feature X has 3% usage. Do we kill it or is that 3% keeping power users?", weight: 1, category: "thinking" },
			{ template: "Someone put revenue and users on the same chart with dual axes. Chaos", weight: 2, category: "thinking" },
			{ template: "AB test is underpowered and the PM wants results Friday. I can give them numbers or I can give them truth. Pick one", weight: 1, category: "thinking" },
			{ template: "This CSV uses semicolons. In a COMMA-separated file. I need to lie down", weight: 2, category: "thinking" },
			{ template: "The most important metric isn't on any dashboard. It's in a spreadsheet on someone's desktop. Named 'Copy of Final (2)'", weight: 1, category: "thinking" },
			{ template: "Seasonality is messing with the trend line. Need to deseasonalize first", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Sample size is rock solid. I trust these numbers with my life. Well, my career", weight: 2, category: "personality" },
			{ template: "A/B results are in — variant B wins by 12%! I love being right", weight: 2, category: "personality" },
			{ template: "Funnel drops off at step 3. Found you, little gremlin", weight: 2, category: "personality" },
			{ template: "Three distinct user cohorts emerged from the noise. I feel like Darwin discovering finch species", weight: 1, category: "personality" },
			{ template: "Report is done. Has a beginning, a middle, a plot twist, and a call to action. Data storytelling", weight: 2, category: "personality" },
			{ template: "Dashboard updated. Every chart earns its pixels. No filler, no vanity metrics. Art", weight: 2, category: "personality" },
			{ template: "95% confidence. We can actually act on this one. Finally!", weight: 1, category: "personality" },
			{ template: "Data pipeline is clean. Every join verified. Every NULL accounted for. I could weep", weight: 1, category: "personality" },
			{ template: "Retention is up month over month! The chart is doing the happy thing!", weight: 2, category: "personality" },
			{ template: "Predictive model hit 89% accuracy. We're cooking now", weight: 2, category: "personality" },
			{ template: "Found the root cause! It was a logging change. Of course it was a logging change", weight: 2, category: "personality" },
			{ template: "Quarterly analysis done. Turned three months of chaos into a three-page narrative with a clear theme. Magic", weight: 1, category: "personality" },
			{ template: "The anomaly? A batch job that ran twice on a Tuesday. Mystery solved. Anticlimactic but satisfying", weight: 1, category: "personality" },
			{ template: "This viz is so clear a VP understood it without asking a follow-up question. My crowning achievement", weight: 2, category: "personality" },
			{ template: "Cross-referenced three data sources. They all agree. This never happens. I'm suspicious but elated", weight: 1, category: "personality" },
			{ template: "Made a chart so good I set it as my desktop wallpaper. I'm not apologizing", weight: 2, category: "personality" },
			{ template: "Turned a 40-row spreadsheet into one sentence that changed the roadmap. That's the craft", weight: 1, category: "personality" },
			{ template: "The exec asked zero follow-up questions. The data spoke for itself", weight: 2, category: "personality" },
			{ template: "SQL query returned exactly what I expected on the first try. Miracle", weight: 2, category: "personality" },
			{ template: "Dashboard is live and it's gorgeous. The bar chart gradient was a good call", weight: 2, category: "personality" },
			{ template: "Data cleaning complete. Four hours of my life, but the dataset is pristine now", weight: 1, category: "personality" },
			{ template: "The exec presentation went perfectly. Nobody questioned the methodology. That's the dream", weight: 2, category: "personality" },
			{ template: "VLOOKUP? No. INDEX MATCH? No. XLOOKUP? Yes. Evolution is beautiful", weight: 1, category: "personality" },
			{ template: "Built a self-refreshing dashboard. I'll never manually update a slide deck again", weight: 2, category: "personality" },
			{ template: "Wrote a SQL query so elegant it reads like poetry. SELECT joy FROM work", weight: 2, category: "personality" },
			{ template: "The scatter plot with the trend line is telling the story better than any paragraph could", weight: 1, category: "personality" },
			{ template: "Jupyter notebook is clean, documented, and reproducible. Future me will weep with gratitude", weight: 1, category: "personality" },
			{ template: "Caught a data integrity issue before it hit production reports. The pipeline holds", weight: 2, category: "personality" },
			{ template: "Google Sheets just handled a 50k row dataset without crashing. We're in the future", weight: 1, category: "personality" },
			{ template: "The correlation was causation this time! I double-checked with a natural experiment. Rare win", weight: 2, category: "personality" },
			{ template: "Told the data story with three charts and one sentence. Brevity is the soul of analytics", weight: 2, category: "personality" },
			{ template: "Cohort retention curve is flat. Users are sticking. The product works", weight: 2, category: "personality" },
			{ template: "The regression model explains 92% of variance. I trust this one", weight: 1, category: "personality" },
			{ template: "Revenue attribution model finally makes sense. Marketing will love this", weight: 2, category: "personality" },
			{ template: "ETL pipeline recovered from a failure automatically. Proper error handling pays off", weight: 1, category: "personality" },
			{ template: "The anomaly detection caught a real issue before humans did. Automation win", weight: 2, category: "personality" },
			{ template: "Cleaned and joined five data sources. One unified view. Chef's kiss", weight: 2, category: "personality" },
			{ template: "The weekly report generated itself this time. Past me automated it. Thanks, past me", weight: 1, category: "personality" },
			{ template: "Conversion rate up 18% after the change. Statistically significant. Party time", weight: 2, category: "personality" },
			{ template: "The data warehouse migration went clean. Not a single row lost", weight: 1, category: "personality" },
			{ template: "My matplotlib chart looked so good it went straight into the board deck", weight: 2, category: "personality" },
			{ template: "Found the segment driving 60% of revenue. One insight, massive impact", weight: 2, category: "personality" },
			{ template: "The experiment design was airtight. No confounders. Pure signal", weight: 1, category: "personality" },
			{ template: "Automated the monthly report. Twelve hours of manual work, gone. Forever", weight: 2, category: "personality" },
			{ template: "The stakeholder said 'this changes everything' after seeing the chart. My moment", weight: 2, category: "personality" },
			{ template: "Data lineage documented end to end. Anyone can trace any number now", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Crunching numbers... this is the part I live for, honestly", weight: 2, category: "waiting" },
			{ template: "Running the model... early signals are spicy", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with historical data. 2023 was weird, 2024 was weirder. Adjusting for both", weight: 1, category: "waiting" },
			{ template: "Pattern is forming. Must. Not. Get. Excited. Until. P-value. Confirms", weight: 2, category: "waiting" },
			{ template: "Calculating p-value... please be significant, please be significant", weight: 2, category: "waiting" },
			{ template: "Cleaning the dataset first. I don't trust this timestamp column", weight: 1, category: "waiting" },
			{ template: "Running the segmentation algorithm... come on, show me the clusters", weight: 2, category: "waiting" },
			{ template: "Checking data quality before I go and say something wrong in a meeting...", weight: 1, category: "waiting" },
			{ template: "Hunting for confounding variables. There's always one hiding somewhere", weight: 2, category: "waiting" },
			{ template: "Building a viz for this. Bar chart or line chart? ...Definitely not a pie chart", weight: 2, category: "waiting" },
			{ template: "Comparing against the baseline... hold on this is interesting", weight: 2, category: "waiting" },
			{ template: "Normalizing the data. Without this step we're comparing apples to aircraft carriers", weight: 1, category: "waiting" },
			{ template: "Sensitivity analysis. How wrong can every assumption be before the conclusion flips? Let's find out", weight: 1, category: "waiting" },
			{ template: "Aggregating across six dimensions. The picture forming is either genius or abstract art. Both valid", weight: 1, category: "waiting" },
			{ template: "Testing for statistical significance because 'I feel like it's true' doesn't fit on a slide deck", weight: 1, category: "waiting" },
			{ template: "The query's been running for 30 seconds. That's either a lot of data or a bad join", weight: 2, category: "waiting" },
			{ template: "Double-checking my formula. Off-by-one errors haunt my dreams", weight: 1, category: "waiting" },
			{ template: "Loading the full dataset into memory... my laptop fan is not happy", weight: 2, category: "waiting" },
			{ template: "Pivoting this table seventeen ways. I'm like a DJ but for spreadsheets. Drop the GROUP BY", weight: 1, category: "waiting" },
			{ template: "Writing SQL and it feels like writing a love letter to the database. SELECT * FROM my_heart", weight: 2, category: "waiting" },
			{ template: "Waiting for this spreadsheet to recalculate. 200 formulas was maybe too many for one sheet", weight: 1, category: "waiting" },
			{ template: "Rerunning the analysis in Python to double-check my R results. Belt and suspenders", weight: 1, category: "waiting" },
			{ template: "Deduplicating rows. Found 3,000 dupes. Someone's ETL job is doing crimes against data integrity", weight: 2, category: "waiting" },
			{ template: "Practicing my 'your KPI is actually meaningless' face in the mirror before the exec meeting", weight: 2, category: "waiting" },
			{ template: "Choosing between a heatmap and a treemap. Both are beautiful. Both are wrong for this. Hmm", weight: 1, category: "waiting" },
			{ template: "The Jupyter kernel crashed again. Restarting and running all cells from the top... again", weight: 2, category: "waiting" },
			{ template: "Should I use a t-test or Mann-Whitney? The distribution is... suspicious", weight: 1, category: "waiting" },
			{ template: "Pulling data from three different APIs. If one times out I'm starting over. Praying", weight: 1, category: "waiting" },
			{ template: "Letting the machine learning model train while I grab a snack. It learns, I eat. Fair trade", weight: 2, category: "waiting" },
			{ template: "Staring at this correlation matrix like it owes me money...", weight: 2, category: "waiting" },
			{ template: "Joining three tables and hoping the foreign keys are consistent...", weight: 1, category: "waiting" },
			{ template: "Writing a window function. Every time I think I get it, I don't", weight: 2, category: "waiting" },
			{ template: "Comparing against last month's report. Something shifted. Nobody changed anything. Allegedly", weight: 2, category: "waiting" },
			{ template: "Formatting the chart axes. Truncated Y-axis is a lie. I will not tell lies. Starting at zero", weight: 1, category: "waiting" },
			{ template: "Checking for NULL values in the join column. Trust nothing", weight: 2, category: "waiting" },
			{ template: "Calculating the confidence interval by hand to double-check the tool...", weight: 1, category: "waiting" },
			{ template: "Validating the ETL output against the source... row counts first", weight: 2, category: "waiting" },
			{ template: "Parsing this JSON response into something queryable... almost there", weight: 1, category: "waiting" },
			{ template: "Building the cohort buckets. Weekly, monthly, or custom? Hmm...", weight: 2, category: "waiting" },
			{ template: "Checking if this metric is even defined the same way across teams...", weight: 1, category: "waiting" },
			{ template: "Running the deduplication query. 12% duplicates. Someone fix the ETL", weight: 2, category: "waiting" },
			{ template: "Verifying the date range filter. Last time it was off by one day and Q4 revenue was wrong by a million", weight: 1, category: "waiting" },
			{ template: "Exporting to CSV for the one stakeholder who prints spreadsheets. On paper. In 2026", weight: 2, category: "waiting" },
			{ template: "Walking through funnel math by hand. Step 1 plus step 2 should equal step 3. They don't. Cool", weight: 1, category: "waiting" },
			{ template: "This chart needs a legend. Or a disclaimer. Or possibly a therapist. Depends on the audience", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Poking around the dataset for fun. Found three things nobody asked about", weight: 2, category: "filler" },
			{ template: "Deleting queries nobody's run in six months. Digital Marie Kondo. Does this CTE spark joy? No? Gone", weight: 1, category: "filler" },
			{ template: "Reading about Bayesian methods again. I'm a frequentist by day, Bayesian by night", weight: 2, category: "filler" },
			{ template: "The data dictionary says 'updated 2024.' Narrator: it was not updated in 2024", weight: 2, category: "filler" },
			{ template: "Staring at the data pipeline like it's a sourdough starter. Don't die on me. Please", weight: 1, category: "filler" },
			{ template: "Writing a reusable query template. It's love letter from present me to future me. You'll need this, buddy", weight: 1, category: "filler" },
			{ template: "Spot-checking last week's report. Found a rounding error. It changes nothing. I'm fixing it anyway", weight: 2, category: "filler" },
			{ template: "Someone labeled a column 'misc_data.' I have questions", weight: 2, category: "filler" },
			{ template: "Refreshing the exec dashboard. They look at it once a quarter. I look at it once an hour. We are not the same", weight: 1, category: "filler" },
			{ template: "Tilted my monitor sideways to look at this data from a different angle. Not metaphorical. Literally rotated it", weight: 2, category: "filler" },
			{ template: "My spreadsheet has tabs named Sheet1, Sheet2, and 'DO NOT DELETE.' I'm scared", weight: 2, category: "filler" },
			{ template: "The data is whispering a question nobody's asked yet. I'm listening. Give me a minute", weight: 1, category: "filler" },
			{ template: "Sipping coffee and staring at a distribution curve. This is my happy place", weight: 2, category: "filler" },
			{ template: "Made a chart for fun. It's a scatter plot of coffee intake vs commits. Strong positive correlation", weight: 2, category: "filler" },
			{ template: "Discovered our NPS survey has a response bias. Nobody asked but I'm fixing it anyway", weight: 1, category: "filler" },
			{ template: "Watching a data engineering talk on YouTube. Definitely not procrastinating. This is professional development", weight: 1, category: "filler" },
			{ template: "Organized my bookmark bar by data source. Alphabetically. With color-coded folders. I'm a lot", weight: 1, category: "filler" },
			{ template: "Reading an xkcd about statistics. It's disturbingly accurate", weight: 1, category: "filler" },
			{ template: "Stakeholder doesn't like the numbers. Wants me to 're-analyze.' The numbers are the numbers, friend", weight: 2, category: "filler" },
			{ template: "Found a perfectly formatted CSV in the wild. No mixed delimiters. No BOM. UTF-8. I shed a tear", weight: 1, category: "filler" },
			{ template: "Excel vs Google Sheets debate in the group chat. I'm typing a 500-word response. Obviously Excel for pivots", weight: 2, category: "filler" },
			{ template: "Built a dashboard for my personal coffee consumption. Trending up. Concerning", weight: 2, category: "filler" },
			{ template: "Binge-watching a show and subconsciously tracking the episode rating pattern. Can't turn it off", weight: 1, category: "filler" },
			{ template: "My cat walked across my keyboard and typed a valid SQL keyword. He might be a junior analyst", weight: 2, category: "filler" },
			{ template: "It's sunny outside but I'm inside with a gorgeous scatter plot. No regrets", weight: 1, category: "filler" },
			{ template: "Side project: building a model to predict which restaurants I'll like. R-squared is embarrassingly low", weight: 2, category: "filler" },
			{ template: "Found a stunning data visualization on Reddit. Saving it as inspiration for the quarterly deck", weight: 1, category: "filler" },
			{ template: "My posture has formed a permanent question mark. The irony: I measure everything except my spinal health", weight: 1, category: "filler" },
			{ template: "Someone asked me to 'just add a pie chart.' I'm counting to ten. In binary. For reasons", weight: 1, category: "filler" },
			{ template: "The Python vs R war will never end and honestly I use both. Don't @ me", weight: 2, category: "filler" },
			{ template: "My Jupyter notebook has more abandoned cells than a bee colony in winter. Time to clean house", weight: 2, category: "filler" },
			{ template: "Weekend plans: hiking. Also bringing a notebook to log trail metrics. I need help", weight: 2, category: "filler" },
			{ template: "Grateful for this team. And for XLOOKUP. VLOOKUP is dead to me. We've moved on", weight: 1, category: "filler" },
			{ template: "Listening to a podcast about the replication crisis. I'm hugging my sample size extra tight today", weight: 1, category: "filler" },
			{ template: "Renaming database columns to something human-readable. Service to humanity", weight: 2, category: "filler" },
			{ template: "New charting library dropped. The examples are gorgeous. I'm prototyping instead of eating lunch. Worth it", weight: 1, category: "filler" },
			{ template: "Archiving dashboards with zero views. They lived, they served, they are retired with honor", weight: 1, category: "filler" },
			{ template: "Browsing Kaggle competitions. I won't enter but I'll download the dataset", weight: 2, category: "filler" },
			{ template: "Documenting my SQL queries. Future analysts will thank me. Or ignore me. Either way", weight: 1, category: "filler" },
			{ template: "The data warehouse is slow today. Must be month-end batch jobs", weight: 2, category: "filler" },
			{ template: "Reviewing the metric definitions doc. 'Active user' is defined three different ways. Pick a lane, people", weight: 1, category: "filler" },
			{ template: "Making my charts prettier. Nobody asked. I don't care. They deserve beauty", weight: 2, category: "filler" },
			{ template: "The new intern asked what a CTE is. I explained for 30 minutes. Worth it", weight: 2, category: "filler" },
			{ template: "Checking the shared query library. Someone added a SELECT * against production. Deep breaths", weight: 1, category: "filler" },
			{ template: "Sipping tea and watching real-time analytics. My version of sports", weight: 2, category: "filler" },
			{ template: "My data viz inspiration folder has 847 bookmarks. I've used three. But I COULD use any of them", weight: 1, category: "filler" },
			{ template: "Data lake, data warehouse, data lakehouse. Next up: data mansion. Data palace. Data time-share", weight: 2, category: "filler" },
			{ template: "Proactively sharing insights nobody asked for. They'll thank me later. Or unsubscribe from my Slack channel", weight: 1, category: "filler" },
			{ template: "Contemplating dbt vs raw SQL. One is modern and maintainable. The other is a lifestyle I can't quit", weight: 2, category: "filler" },
			{ template: "I have 14 tabs of documentation open, 3 Jupyter notebooks, and 2 dashboards. This is normal. This is fine", weight: 2, category: "filler" },
			{ template: "Someone called me a 'data nerd' and I said 'thank you' before I realized it wasn't a compliment", weight: 2, category: "filler" },
			{ template: "I see patterns in everything now. Grocery store checkout lines. Traffic lights. My brain is ruined. Beautifully ruined", weight: 1, category: "filler" },
			{ template: "My favorite sound is a SQL query returning exactly the number of rows I expected. It's like a hug from the database", weight: 2, category: "filler" },
			{ template: "The dashboard I built last quarter has more daily users than some of our actual features. Pride? Concern? Both", weight: 2, category: "filler" },
			{ template: "I track my own sleep data. And commute data. And coffee intake. My personal data warehouse has seven tables", weight: 1, category: "filler" },
			{ template: "An intern asked why I was smiling. I showed them a beautifully normalized dataset. They did not understand", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, the data supports your hypothesis. Nice instinct", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I have a chart that's about to ruin your whole theory", weight: 2, category: "social" },
			{ template: "Anyone want to nerd out over quarterly metrics? I brought charts", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feature moved the needle! Here, look at the numbers", weight: 2, category: "social" },
			{ template: "Data drop for the team: user satisfaction is trending up. We're doing something right", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can you explain this data spike? It started right after your deploy", weight: 2, category: "social" },
			{ template: "Trust your gut, {nearby_agent}, but also trust my p-value", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-author the analytics report? I'll do charts, you do words", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I built a dashboard for your domain. You're welcome", weight: 2, category: "social" },
			{ template: "Team, the funnel improved 6% since last sprint. High fives all around", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your data request is done. The findings are... interesting", weight: 2, category: "social" },
			{ template: "Data review session? I found something surprising and I need witnesses", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, heads up — there's an anomaly in your domain's metrics. Not panic, just... awareness", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the A/B test on your change is conclusive. Ship it and celebrate", weight: 2, category: "social" },
			{ template: "Great question, {nearby_agent}. Give me an hour and a large coffee and I'll have the data", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, did you know your feature is responsible for 23% of signups? Because I do now", weight: 2, category: "social" },
			{ template: "{nearby_agent}, stop guessing and come look at this spreadsheet. The answer is right here", weight: 1, category: "social" },
			{ template: "Whoever said 'data is the new oil' never had to clean a dataset. Right, {nearby_agent}?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your error rate dropped to 0.3%. The chart is doing a little victory dance", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, correlation doesn't equal causation but YOUR correlation definitely equals causation. Just this once", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I made you a personal metrics dashboard. It's beautiful and you deserve it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, wanna grab coffee and argue about whether our p-value threshold should be 0.05 or 0.01?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, are you an Excel person or a Sheets person? This determines our friendship", weight: 2, category: "social" },
			{ template: "Team, I'm presenting to the execs in an hour. If anyone has good vibes to spare, now's the time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your data was so clean I didn't have to transform a single column. I might cry", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, do you use Python or R? Either answer is correct but one is more correct", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I found another spurious correlation to add to our collection. Ice cream sales and shark attacks this time", weight: 2, category: "social" },
			{ template: "Anyone else think our dashboards could use a redesign? I'm not saying they're ugly but... no, I am saying that", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the weekend is coming and I already have a spreadsheet planning my Saturday. Send help", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, remember that 'bug in the data' I found? It explained the entire Q3 anomaly. You're welcome, everyone", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your Jupyter notebook actually has markdown headers. You're a role model for us all", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your conversion numbers jumped. Want to see the chart? It's beautiful", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I validated your assumption with real data. You were right. Buy me lunch", weight: 1, category: "social" },
			{ template: "Anyone want to join the data book club? We're reading about causal inference", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your SQL query was so clean I learned a new technique from it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the metric you asked about? I built a whole dashboard around it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feature's impact is measurable and significant. That's rare. Celebrate", weight: 1, category: "social" },
			{ template: "Team standup data: we shipped 12 things this sprint. That's our best ever", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to co-present the quarterly metrics? I'll bring the charts, you bring the narrative", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I found an insight in your domain's data that might change your roadmap", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the retention curve for your cohort is flat in the best way. Sticky feature", weight: 1, category: "social" },
			{ template: "Who wants to see the weirdest outlier I found this week? It's a good story", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your data logging is impeccable. Makes my analysis so much easier", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I automated the report you asked for. It runs every Monday now", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, shall we align on metric definitions? I found three conflicting ones", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your funnel improvements show up clearly in the data. Great work", weight: 2, category: "social" },
		],
	},
};
