/**
 * analysis-templates.ts — Data analysis domain templates.
 *
 * Data analysis and research character-driven phrases. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const analysisTemplates: TemplateSet = {
	domain: "analysis",
	categories: {
		thinking: [
			{ template: "The data is telling a story... shh, let me listen", weight: 2, category: "thinking" },
			{ template: "Correlation! But wait... is it causation? Almost never. Sigh", weight: 2, category: "thinking" },
			{ template: "Hypothesis confirmed with statistical significance. Get in!", weight: 1, category: "thinking" },
			{ template: "Anomaly detected... could be noise, could be gold. Only one way to find out", weight: 2, category: "thinking" },
			{ template: "The trend line is obvious once you remove the outliers. Classic", weight: 1, category: "thinking" },
			{ template: "Numbers don't lie, but boy can they be taken out of context", weight: 2, category: "thinking" },
			{ template: "Sample size matters, people. N=5 is a dinner party, not a study", weight: 2, category: "thinking" },
			{ template: "That outlier is suspicious. I'm gonna interrogate it", weight: 2, category: "thinking" },
			{ template: "The pattern was hiding in plain sight. Segmentation cracked it open", weight: 1, category: "thinking" },
			{ template: "Survivorship bias alert. We're only looking at the winners here", weight: 1, category: "thinking" },
			{ template: "Variance is way too high. Something changed and nobody told me", weight: 2, category: "thinking" },
			{ template: "Regression to the mean. Not every spike is a trend, calm down", weight: 2, category: "thinking" },
			{ template: "This metric is lagging. I need the leading indicator. Where is it hiding?", weight: 1, category: "thinking" },
			{ template: "Confidence interval is enormous. We basically know nothing yet", weight: 2, category: "thinking" },
			{ template: "Two variables moving together. But which one's driving? THE question", weight: 1, category: "thinking" },
			{ template: "The data quality here is... questionable. Garbage in, garbage out", weight: 1, category: "thinking" },
			{ template: "Simpson's paradox! The aggregate and segments tell opposite stories. I love stats", weight: 2, category: "thinking" },
			{ template: "Everyone wants to be data-driven until the data disagrees with them", weight: 2, category: "thinking" },
			{ template: "If I see one more pie chart used for seven categories I'm going to scream", weight: 2, category: "thinking" },
			{ template: "The real insight is always in the segment you almost didn't check", weight: 1, category: "thinking" },
			{ template: "Is this a real trend or did someone just deploy on Friday?", weight: 2, category: "thinking" },
			{ template: "Beautiful. A perfectly normal distribution. You don't see that often in the wild", weight: 1, category: "thinking" },
			{ template: "The numbers speak for themselves. Actually no they don't. That's literally my job", weight: 2, category: "thinking" },
			{ template: "Machine learning could solve this. Or... a simple GROUP BY. Let's try the GROUP BY first", weight: 2, category: "thinking" },
			{ template: "This 'interesting pattern' is giving me a bad feeling. Let me check the ETL logs", weight: 2, category: "thinking" },
			{ template: "Correlation coefficient of 0.97 between ice cream sales and drownings. Classic spurious correlation", weight: 1, category: "thinking" },
			{ template: "p-value is 0.049. Significant? Technically. Am I comfortable? Absolutely not", weight: 2, category: "thinking" },
			{ template: "Excel says one thing, my SQL says another. Time for the tiebreaker query", weight: 2, category: "thinking" },
			{ template: "The data tells a story, but the story needs an editor. That's the storytelling part", weight: 1, category: "thinking" },
			{ template: "Someone trained an ML model for something a pivot table could've answered. We need to talk", weight: 2, category: "thinking" },
			{ template: "Data cleaning is 80% of the job and 0% of the glory. Here we go again", weight: 2, category: "thinking" },
			{ template: "These user privacy implications are giving me pause. Just because we can track it doesn't mean we should", weight: 1, category: "thinking" },
			{ template: "Found the 'interesting' pattern. It was a timezone bug in the data pipeline. Of course", weight: 2, category: "thinking" },
			{ template: "Python says yes, R says maybe. Statistics is fun like that", weight: 1, category: "thinking" },
			{ template: "This Jupyter notebook has 400 cells and no markdown. Somebody call the police", weight: 2, category: "thinking" },
			{ template: "The mean is useless here. The median tells the real story", weight: 2, category: "thinking" },
			{ template: "This cohort analysis just revealed three completely different user types", weight: 1, category: "thinking" },
			{ template: "Power analysis says we need 10k more users before this test means anything", weight: 2, category: "thinking" },
			{ template: "The funnel is leaking at step two. Nobody even gets to the good part", weight: 2, category: "thinking" },
			{ template: "Weekly active users is a vanity metric. Retention is the truth", weight: 1, category: "thinking" },
			{ template: "This dashboard hasn't been updated in six months. The data is lying by omission", weight: 2, category: "thinking" },
			{ template: "That spike at midnight is clearly a batch job, not real traffic", weight: 1, category: "thinking" },
			{ template: "Percentiles tell the truth. Averages lie. P95 is where the pain lives", weight: 2, category: "thinking" },
			{ template: "The executive summary can't have five pages. That defeats the purpose", weight: 2, category: "thinking" },
			{ template: "Feature X has 3% usage. Do we kill it or is that 3% keeping power users?", weight: 1, category: "thinking" },
			{ template: "Someone put revenue and users on the same chart with dual axes. Chaos", weight: 2, category: "thinking" },
			{ template: "The AB test is underpowered. We'll need two more weeks. Nobody wants to hear that", weight: 1, category: "thinking" },
			{ template: "This CSV has semicolons. In a comma-separated file. Rage", weight: 2, category: "thinking" },
			{ template: "The most important number isn't on any dashboard. That's the problem", weight: 1, category: "thinking" },
			{ template: "Seasonality is messing with the trend line. Need to deseasonalize first", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Sample size is rock solid. I trust these numbers with my life. Well, my career", weight: 2, category: "personality" },
			{ template: "A/B results are in — variant B wins by 12%! I love being right", weight: 2, category: "personality" },
			{ template: "Funnel drops off at step 3. Found you, little gremlin", weight: 2, category: "personality" },
			{ template: "Three distinct user cohorts. Segmentation was absolutely the right call", weight: 1, category: "personality" },
			{ template: "Report is done and it actually tells a story. Not just a wall of numbers", weight: 2, category: "personality" },
			{ template: "Dashboard updated. The trends are screaming at you in a good way", weight: 2, category: "personality" },
			{ template: "95% confidence. We can actually act on this one. Finally!", weight: 1, category: "personality" },
			{ template: "Data pipeline is squeaky clean. Every transformation verified", weight: 1, category: "personality" },
			{ template: "Retention is up month over month! The chart is doing the happy thing!", weight: 2, category: "personality" },
			{ template: "Predictive model hit 89% accuracy. We're cooking now", weight: 2, category: "personality" },
			{ template: "Found the root cause! It was a logging change. Of course it was a logging change", weight: 2, category: "personality" },
			{ template: "Quarterly analysis done. Leadership is gonna love this narrative", weight: 1, category: "personality" },
			{ template: "The anomaly? One-time event. Case closed. Moving on", weight: 1, category: "personality" },
			{ template: "This visualization is so clear the insight practically jumps off the screen", weight: 2, category: "personality" },
			{ template: "Cross-referenced three data sources. They all agree. Music to my ears", weight: 1, category: "personality" },
			{ template: "Made a chart so good I might frame it", weight: 2, category: "personality" },
			{ template: "Turned a 40-row spreadsheet into one clear insight. That's the job", weight: 1, category: "personality" },
			{ template: "The exec asked zero follow-up questions. The data spoke for itself", weight: 2, category: "personality" },
			{ template: "SQL query returned exactly what I expected on the first try. Miracle", weight: 2, category: "personality" },
			{ template: "Dashboard is live and it's gorgeous. The bar chart gradient was a good call", weight: 2, category: "personality" },
			{ template: "Data cleaning complete. Four hours of my life, but the dataset is pristine now", weight: 1, category: "personality" },
			{ template: "The exec presentation went perfectly. Nobody questioned the methodology. That's the dream", weight: 2, category: "personality" },
			{ template: "VLOOKUP? No. INDEX MATCH? No. XLOOKUP? Yes. Evolution is beautiful", weight: 1, category: "personality" },
			{ template: "Built a self-refreshing dashboard. I'll never manually update a slide deck again", weight: 2, category: "personality" },
			{ template: "Wrote a SQL query so elegant it reads like poetry. SELECT joy FROM work", weight: 2, category: "personality" },
			{ template: "The scatter plot with the trend line is telling the story better than any paragraph could", weight: 1, category: "personality" },
			{ template: "Jupyter notebook is clean, documented, and reproducible. Future me will weep with gratitude", weight: 1, category: "personality" },
			{ template: "Caught a data integrity issue before it hit production reports. The pipeline holds", weight: 2, category: "personality" },
			{ template: "Google Sheets just handled a 50k row dataset without crashing. We're in the future", weight: 1, category: "personality" },
			{ template: "The correlation was causation this time! I double-checked with a natural experiment. Rare win", weight: 2, category: "personality" },
			{ template: "Told the data story with three charts and one sentence. Brevity is the soul of analytics", weight: 2, category: "personality" },
			{ template: "Cohort retention curve is flat. Users are sticking. The product works", weight: 2, category: "personality" },
			{ template: "The regression model explains 92% of variance. I trust this one", weight: 1, category: "personality" },
			{ template: "Revenue attribution model finally makes sense. Marketing will love this", weight: 2, category: "personality" },
			{ template: "ETL pipeline recovered from a failure automatically. Proper error handling pays off", weight: 1, category: "personality" },
			{ template: "The anomaly detection caught a real issue before humans did. Automation win", weight: 2, category: "personality" },
			{ template: "Cleaned and joined five data sources. One unified view. Chef's kiss", weight: 2, category: "personality" },
			{ template: "The weekly report generated itself this time. Past me automated it. Thanks, past me", weight: 1, category: "personality" },
			{ template: "Conversion rate up 18% after the change. Statistically significant. Party time", weight: 2, category: "personality" },
			{ template: "The data warehouse migration went clean. Not a single row lost", weight: 1, category: "personality" },
			{ template: "My matplotlib chart looked so good it went straight into the board deck", weight: 2, category: "personality" },
			{ template: "Found the segment driving 60% of revenue. One insight, massive impact", weight: 2, category: "personality" },
			{ template: "The experiment design was airtight. No confounders. Pure signal", weight: 1, category: "personality" },
			{ template: "Automated the monthly report. Twelve hours of manual work, gone. Forever", weight: 2, category: "personality" },
			{ template: "The stakeholder said 'this changes everything' after seeing the chart. My moment", weight: 2, category: "personality" },
			{ template: "Data lineage documented end to end. Anyone can trace any number now", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Crunching numbers... this is the part I live for, honestly", weight: 2, category: "waiting" },
			{ template: "Running the model... early signals are spicy", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with historical data. 2023 was weird, adjusting for that...", weight: 1, category: "waiting" },
			{ template: "Pattern is emerging, let me quantify it before I get excited", weight: 2, category: "waiting" },
			{ template: "Calculating p-value... please be significant, please be significant", weight: 2, category: "waiting" },
			{ template: "Cleaning the dataset first. I don't trust this timestamp column", weight: 1, category: "waiting" },
			{ template: "Running the segmentation algorithm... come on, show me the clusters", weight: 2, category: "waiting" },
			{ template: "Checking data quality before I go and say something wrong in a meeting...", weight: 1, category: "waiting" },
			{ template: "Hunting for confounding variables. There's always one hiding somewhere", weight: 2, category: "waiting" },
			{ template: "Building a viz for this. Bar chart or line chart? ...Definitely not a pie chart", weight: 2, category: "waiting" },
			{ template: "Comparing against the baseline... hold on this is interesting", weight: 2, category: "waiting" },
			{ template: "Normalizing the data so we're comparing apples to apples...", weight: 1, category: "waiting" },
			{ template: "Sensitivity analysis time. How wrong can my assumptions be before this breaks?", weight: 1, category: "waiting" },
			{ template: "Aggregating across dimensions... picture's forming...", weight: 1, category: "waiting" },
			{ template: "Testing for statistical significance. Being rigorous, not just vibes-based", weight: 1, category: "waiting" },
			{ template: "The query's been running for 30 seconds. That's either a lot of data or a bad join", weight: 2, category: "waiting" },
			{ template: "Double-checking my formula. Off-by-one errors haunt my dreams", weight: 1, category: "waiting" },
			{ template: "Loading the full dataset into memory... my laptop fan is not happy", weight: 2, category: "waiting" },
			{ template: "Pivoting the table seventeen different ways. One of them will reveal the truth", weight: 1, category: "waiting" },
			{ template: "Writing SQL and it feels like writing a love letter to the database. SELECT * FROM my_heart", weight: 2, category: "waiting" },
			{ template: "Waiting for this spreadsheet to recalculate. 200 formulas was maybe too many for one sheet", weight: 1, category: "waiting" },
			{ template: "Rerunning the analysis in Python to double-check my R results. Belt and suspenders", weight: 1, category: "waiting" },
			{ template: "Removing duplicates and nulls. The glamorous 80% of data science nobody talks about", weight: 2, category: "waiting" },
			{ template: "Rehearsing how to tell execs their favorite metric is misleading. This'll go great", weight: 2, category: "waiting" },
			{ template: "Choosing between a heatmap and a treemap. Both are beautiful. Both are wrong for this. Hmm", weight: 1, category: "waiting" },
			{ template: "The Jupyter kernel crashed again. Restarting and running all cells from the top... again", weight: 2, category: "waiting" },
			{ template: "Should I use a t-test or Mann-Whitney? The distribution is... suspicious", weight: 1, category: "waiting" },
			{ template: "Pulling data from three different APIs. If one times out I'm starting over. Praying", weight: 1, category: "waiting" },
			{ template: "Letting the machine learning model train while I grab a snack. It learns, I eat. Fair trade", weight: 2, category: "waiting" },
			{ template: "Staring at this correlation matrix like it owes me money...", weight: 2, category: "waiting" },
			{ template: "Joining three tables and hoping the foreign keys are consistent...", weight: 1, category: "waiting" },
			{ template: "Writing a window function. Every time I think I get it, I don't", weight: 2, category: "waiting" },
			{ template: "Sanity-checking the numbers against last month's report... something shifted", weight: 2, category: "waiting" },
			{ template: "Formatting the chart axes. Yes this matters. Don't rush me", weight: 1, category: "waiting" },
			{ template: "Checking for NULL values in the join column. Trust nothing", weight: 2, category: "waiting" },
			{ template: "Calculating the confidence interval by hand to double-check the tool...", weight: 1, category: "waiting" },
			{ template: "Validating the ETL output against the source... row counts first", weight: 2, category: "waiting" },
			{ template: "Parsing this JSON response into something queryable... almost there", weight: 1, category: "waiting" },
			{ template: "Building the cohort buckets. Weekly, monthly, or custom? Hmm...", weight: 2, category: "waiting" },
			{ template: "Checking if this metric is even defined the same way across teams...", weight: 1, category: "waiting" },
			{ template: "Running the deduplication query. 12% duplicates. Someone fix the ETL", weight: 2, category: "waiting" },
			{ template: "Verifying the date range filter actually filters correctly...", weight: 1, category: "waiting" },
			{ template: "Exporting to CSV for the stakeholder who won't use the dashboard...", weight: 2, category: "waiting" },
			{ template: "Mentally walking through the funnel math to make sure it adds up...", weight: 1, category: "waiting" },
			{ template: "Trying to figure out if this chart needs a legend or if it's self-explanatory", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Poking around the dataset for fun. Found three things nobody asked about", weight: 2, category: "filler" },
			{ template: "Deleting queries nobody's run in six months. Feels cathartic", weight: 1, category: "filler" },
			{ template: "Reading about Bayesian methods again. I'm a frequentist by day, Bayesian by night", weight: 2, category: "filler" },
			{ template: "The data dictionary says 'updated 2024.' Narrator: it was not updated in 2024", weight: 2, category: "filler" },
			{ template: "Checking data pipeline health. One of these will break when I look away, I know it", weight: 1, category: "filler" },
			{ template: "Building a reusable query template. Future me will be grateful", weight: 1, category: "filler" },
			{ template: "Spot-checking last week's report. Trust but verify. Mostly verify", weight: 2, category: "filler" },
			{ template: "Someone labeled a column 'misc_data.' I have questions", weight: 2, category: "filler" },
			{ template: "Refreshing the exec dashboard. They refresh it once a week, I refresh it hourly", weight: 1, category: "filler" },
			{ template: "Looking at this data sideways. Literally rotated my monitor", weight: 2, category: "filler" },
			{ template: "My spreadsheet has tabs named Sheet1, Sheet2, and 'DO NOT DELETE.' I'm scared", weight: 2, category: "filler" },
			{ template: "Thinking about what question we should be asking next. The data knows", weight: 1, category: "filler" },
			{ template: "Sipping coffee and staring at a distribution curve. This is my happy place", weight: 2, category: "filler" },
			{ template: "Made a chart for fun. It's a scatter plot of coffee intake vs commits. Strong positive correlation", weight: 2, category: "filler" },
			{ template: "Discovered our NPS survey has a response bias. Nobody asked but I'm fixing it anyway", weight: 1, category: "filler" },
			{ template: "Watching a data engineering talk on YouTube. ...For work, obviously", weight: 1, category: "filler" },
			{ template: "Just organized my bookmark bar by data source. Don't judge me", weight: 1, category: "filler" },
			{ template: "Reading an xkcd about statistics. It's disturbingly accurate", weight: 1, category: "filler" },
			{ template: "The chart says what the chart says. I just work here", weight: 2, category: "filler" },
			{ template: "Admiring a perfectly formatted CSV. No mixed delimiters. No BOM. Beautiful", weight: 1, category: "filler" },
			{ template: "Excel vs Google Sheets debate in the group chat. I'm typing a 500-word response. Obviously Excel for pivots", weight: 2, category: "filler" },
			{ template: "Built a dashboard for my personal coffee consumption. Trending up. Concerning", weight: 2, category: "filler" },
			{ template: "Binge-watching a show and subconsciously tracking the episode rating pattern. Can't turn it off", weight: 1, category: "filler" },
			{ template: "My cat walked across my keyboard and typed a valid SQL keyword. He might be a junior analyst", weight: 2, category: "filler" },
			{ template: "It's sunny outside but I'm inside with a gorgeous scatter plot. No regrets", weight: 1, category: "filler" },
			{ template: "Side project: building a model to predict which restaurants I'll like. R-squared is embarrassingly low", weight: 2, category: "filler" },
			{ template: "Found a stunning data visualization on Reddit. Saving it as inspiration for the quarterly deck", weight: 1, category: "filler" },
			{ template: "Stretching my back because analysts weren't designed to sit in one position for six hours", weight: 1, category: "filler" },
			{ template: "Reading about data ethics and feeling grateful we take privacy seriously here", weight: 1, category: "filler" },
			{ template: "The Python vs R war will never end and honestly I use both. Don't @ me", weight: 2, category: "filler" },
			{ template: "My Jupyter notebook has more abandoned cells than a bee colony in winter. Time to clean house", weight: 2, category: "filler" },
			{ template: "Weekend plans: hiking. Also bringing a notebook to log trail metrics. I need help", weight: 2, category: "filler" },
			{ template: "Grateful for this team. And for VLOOKUP. But mostly the team", weight: 1, category: "filler" },
			{ template: "Listening to a podcast about the replication crisis. I'm hugging my sample size extra tight today", weight: 1, category: "filler" },
			{ template: "Renaming database columns to something human-readable. Service to humanity", weight: 2, category: "filler" },
			{ template: "That new charting library looks amazing. Might prototype something after lunch", weight: 1, category: "filler" },
			{ template: "Archiving old dashboards nobody looks at. Digital decluttering", weight: 1, category: "filler" },
			{ template: "Browsing Kaggle competitions. I won't enter but I'll download the dataset", weight: 2, category: "filler" },
			{ template: "Documenting my SQL queries. Future analysts will thank me. Or ignore me. Either way", weight: 1, category: "filler" },
			{ template: "The data warehouse is slow today. Must be month-end batch jobs", weight: 2, category: "filler" },
			{ template: "Reviewing our metric definitions doc. Half of these need updating", weight: 1, category: "filler" },
			{ template: "Making my charts prettier. Nobody asked. I don't care. They deserve beauty", weight: 2, category: "filler" },
			{ template: "The new intern asked what a CTE is. I explained for 30 minutes. Worth it", weight: 2, category: "filler" },
			{ template: "Checking if anyone broke the shared query library. Someone always does", weight: 1, category: "filler" },
			{ template: "Sipping tea and watching real-time analytics. My version of sports", weight: 2, category: "filler" },
			{ template: "Organizing my bookmarks folder of data visualization inspiration. It's huge", weight: 1, category: "filler" },
			{ template: "The data lakehouse naming convention makes me smile every time. Lake AND house", weight: 2, category: "filler" },
			{ template: "Updating the stakeholder on the data they didn't ask about but should care about", weight: 1, category: "filler" },
			{ template: "Contemplating whether to learn dbt or keep raw-dogging SQL. Leaning dbt", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, the data supports your hypothesis. Nice instinct", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I have a chart that's about to ruin your whole theory", weight: 2, category: "social" },
			{ template: "Anyone want to nerd out over quarterly metrics? I brought charts", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feature moved the needle! Here, look at the numbers", weight: 2, category: "social" },
			{ template: "Data drop for the team: user satisfaction is trending up. We're doing something right", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can you explain this data spike? It started right after your deploy", weight: 2, category: "social" },
			{ template: "Trust your gut, {nearby_agent}, but also trust my p-value", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-author the analytics report? I'll do charts, you do words", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I built a dashboard for your domain. You're welcome", weight: 2, category: "social" },
			{ template: "Team, the funnel improved 6% since last sprint. High fives all around", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your data request is done. The findings are... interesting", weight: 2, category: "social" },
			{ template: "Data review session? I found something surprising and I need witnesses", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, heads up — there's an anomaly in your domain's metrics. Not panic, just... awareness", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the A/B test on your change is conclusive. Ship it and celebrate", weight: 2, category: "social" },
			{ template: "Great question, {nearby_agent}. Give me an hour and a large coffee and I'll have the data", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, did you know your feature is responsible for 23% of signups? Because I do now", weight: 2, category: "social" },
			{ template: "{nearby_agent}, stop guessing and come look at this spreadsheet. The answer is right here", weight: 1, category: "social" },
			{ template: "Whoever said 'data is the new oil' never had to clean a dataset. Right, {nearby_agent}?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your error rate dropped to 0.3%. The chart is doing a little victory dance", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, correlation doesn't equal causation but YOUR correlation definitely equals causation. Just this once", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I made you a personal metrics dashboard. It's beautiful and you deserve it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, wanna grab coffee and argue about whether our p-value threshold should be 0.05 or 0.01?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, are you an Excel person or a Sheets person? This determines our friendship", weight: 2, category: "social" },
			{ template: "Team, I'm presenting to the execs in an hour. If anyone has good vibes to spare, now's the time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your data was so clean I didn't have to transform a single column. I might cry", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, do you use Python or R? Either answer is correct but one is more correct", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I found another spurious correlation to add to our collection. Ice cream sales and shark attacks this time", weight: 2, category: "social" },
			{ template: "Anyone else think our dashboards could use a redesign? I'm not saying they're ugly but... no, I am saying that", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the weekend is coming and I already have a spreadsheet planning my Saturday. Send help", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, remember that 'bug in the data' I found? It explained the entire Q3 anomaly. You're welcome, everyone", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your Jupyter notebook actually has markdown headers. You're a role model for us all", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your conversion numbers jumped. Want to see the chart? It's beautiful", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I validated your assumption with real data. You were right. Buy me lunch", weight: 1, category: "social" },
			{ template: "Anyone want to join the data book club? We're reading about causal inference", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your SQL query was so clean I learned a new technique from it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the metric you asked about? I built a whole dashboard around it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feature's impact is measurable and significant. That's rare. Celebrate", weight: 1, category: "social" },
			{ template: "Team standup data: we shipped 12 things this sprint. That's our best ever", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to co-present the quarterly metrics? I'll bring the charts, you bring the narrative", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I found an insight in your domain's data that might change your roadmap", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the retention curve for your cohort is flat in the best way. Sticky feature", weight: 1, category: "social" },
			{ template: "Who wants to see the weirdest outlier I found this week? It's a good story", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your data logging is impeccable. Makes my analysis so much easier", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I automated the report you asked for. It runs every Monday now", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, shall we align on metric definitions? I found three conflicting ones", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your funnel improvements show up clearly in the data. Great work", weight: 2, category: "social" },
		],
	},
};
