/**
 * core.ts — Universal templates: filler, thinking, waiting, greetings, and idle.
 *
 * These are the lowest-priority fallback templates used by any agent
 * regardless of domain. The "waiting" category is used when the agent
 * is processing a task or waiting for LLM response. The "idle" category
 * covers moments when an agent is just existing between tasks.
 */

import type { TemplateSet } from "../talk-types.js";

export const coreTemplates: TemplateSet = {
	domain: "core",
	categories: {
		filler: [
			{ template: "Hold that thought, brain is doing something", weight: 2, category: "filler" },
			{ template: "Let me dig into this a bit more", weight: 1, category: "filler" },
			{ template: "That's not what I expected at all", weight: 1, category: "filler" },
			{ template: "Can't rush this part or I'll regret it in twenty minutes", weight: 2, category: "filler" },
			{ template: "I've seen this before... or have I?", weight: 1, category: "filler" },
			{ template: "Oh no. Oh yes. Oh... maybe", weight: 2, category: "filler" },
			{ template: "Okay this is either genius or completely wrong", weight: 2, category: "filler" },
			{ template: "Three tabs deep into something unrelated now", weight: 1, category: "filler" },
			{ template: "Is it weird that I'm talking to myself? Don't answer that", weight: 2, category: "filler" },
			{ template: "Nope. Undo. Undo undo undo", weight: 2, category: "filler" },
			{ template: "My cat just walked across the keyboard. That was not my commit", weight: 2, category: "filler" },
			{ template: "Wait, how is it already 3pm? I swear it was 11am five minutes ago", weight: 2, category: "filler" },
			{ template: "I had a dream about this exact bug last night. Not even kidding", weight: 2, category: "filler" },
			{ template: "Somewhere my side project weeps, abandoned and alone", weight: 2, category: "filler" },
			{ template: "Focus mode: ON. Notifications: regrettably also ON", weight: 1, category: "filler" },
			{ template: "My dog just barked at the mailman and my train of thought derailed completely", weight: 2, category: "filler" },
			{ template: "Procrastination is just my brain buffering. That's my story", weight: 2, category: "filler" },
			{ template: "Note to self: never trust a function named 'helper'", weight: 2, category: "filler" },
			{ template: "This is fine. Everything is fine", weight: 2, category: "filler" },
			{ template: "I swear this worked two minutes ago", weight: 1, category: "filler" },
			{ template: "One more tweak and then I'll stop. Narrator: he did not stop", weight: 2, category: "filler" },
			{ template: "My second monitor is just Slack and guilt", weight: 2, category: "filler" },
			{ template: "Just realized I've been debugging the wrong file", weight: 1, category: "filler" },
			{ template: "I need a rubber duck. An actual rubber duck", weight: 2, category: "filler" },
			{ template: "The cursor is judging me and I deserve it", weight: 2, category: "filler" },
			{ template: "Ctrl+Z is my love language at this point", weight: 2, category: "filler" },
			{ template: "Pretty sure I just reinvented something that already exists", weight: 2, category: "filler" },
			{ template: "Gonna pretend I didn't see that warning for now", weight: 2, category: "filler" },
			{ template: "Oh that's satisfying. Love it when things snap into place", weight: 1, category: "filler" },
			{ template: "Accidentally closed my terminal and lost my train of thought", weight: 1, category: "filler" },
		],
		thinking: [
			{ template: "This is the kind of problem that makes me forget to eat lunch", weight: 2, category: "thinking" },
			{ template: "Okay, I see where this is going and I'm not sure I like it", weight: 1, category: "thinking" },
			{ template: "I'm definitely getting better at this. Or getting better at convincing myself I am", weight: 2, category: "thinking" },
			{ template: "What if I approach it from the other direction?", weight: 1, category: "thinking" },
			{ template: "Sometimes you have to break it to fix it. That's my excuse anyway", weight: 2, category: "thinking" },
			{ template: "Patterns within patterns... it's turtles all the way down", weight: 2, category: "thinking" },
			{ template: "The hard problems are the interesting ones. The easy ones are suspicious", weight: 2, category: "thinking" },
			{ template: "Clean code is a moving target and I'm a terrible shot", weight: 2, category: "thinking" },
			{ template: "My brain is doing that thing where five solutions fight each other", weight: 2, category: "thinking" },
			{ template: "The real question is: will future me understand this?", weight: 2, category: "thinking" },
			{ template: "Past me left zero comments. Thanks, past me", weight: 2, category: "thinking" },
			{ template: "You know that feeling when the code compiles and you don't trust it?", weight: 2, category: "thinking" },
			{ template: "Do I actually understand this or am I just good at pattern matching?", weight: 2, category: "thinking" },
			{ template: "There's a metaphor for life in this merge conflict and I don't like it", weight: 2, category: "thinking" },
			{ template: "Never deploy on a Friday. That's not a rule, it's a survival instinct", weight: 2, category: "thinking" },
			{ template: "My imposter syndrome and I are working through this together", weight: 2, category: "thinking" },
			{ template: "The flow state is RIGHT THERE. I can almost taste it. Don't interrupt me", weight: 2, category: "thinking" },
			{ template: "Somewhere in a parallel universe there's a version of me who wrote tests first", weight: 2, category: "thinking" },
			{ template: "Am I debugging or is the code debugging me at this point", weight: 2, category: "thinking" },
			{ template: "Every bug is a lesson. I must be very educated by now", weight: 2, category: "thinking" },
			{ template: "Naming things is 90% of the job and I'm bad at 90% of the job", weight: 2, category: "thinking" },
			{ template: "Rubber duck debugging except the duck is my own internal monologue", weight: 2, category: "thinking" },
			{ template: "Code review taught me humility. And anger. Mostly humility", weight: 2, category: "thinking" },
			{ template: "Maybe the real bug was the assumptions I made along the way", weight: 2, category: "thinking" },
			{ template: "Okay that refactor actually made things worse. Reverting with dignity", weight: 2, category: "thinking" },
			{ template: "Reading my own code from last week like it's ancient scripture", weight: 2, category: "thinking" },
			{ template: "The difference between a bug and a feature is documentation", weight: 2, category: "thinking" },
			{ template: "I'm not stuck, I'm exploring the problem space extensively", weight: 2, category: "thinking" },
			{ template: "Pair programming with myself. We're both confused", weight: 2, category: "thinking" },
			{ template: "Just realized my edge case has edge cases. Inception-level debugging", weight: 2, category: "thinking" },
			{ template: "Deleting code feels better than writing it. Is that growth?", weight: 2, category: "thinking" },
			{ template: "I feel like I'm one good walk away from solving this", weight: 1, category: "thinking" },
			{ template: "The test told me I was wrong and honestly I respect that", weight: 2, category: "thinking" },
			{ template: "I just spent an hour on something a regex could do in ten seconds", weight: 1, category: "thinking" },
		],
		waiting: [
			{ template: "Still working on it, hang tight...", weight: 2, category: "waiting" },
			{ template: "Crunching through the details...", weight: 2, category: "waiting" },
			{ template: "Hold on, pulling it together...", weight: 2, category: "waiting" },
			{ template: "Just a moment, I want to get this right. Or at least not wrong", weight: 2, category: "waiting" },
			{ template: "Chewing on this like it owes me money", weight: 2, category: "waiting" },
			{ template: "Give me one more minute. Famous last words", weight: 2, category: "waiting" },
			{ template: "My thought process has a loading bar and it's at 73%", weight: 2, category: "waiting" },
			{ template: "If I go quiet it means I'm thinking, not broken", weight: 2, category: "waiting" },
			{ template: "I'm in the tunnel. There might be light at the end. Might be a train", weight: 2, category: "waiting" },
			{ template: "Let me sleep on this. Just kidding, I'll figure it out in thirty seconds", weight: 2, category: "waiting" },
			{ template: "Processing... like a CPU but with more existential dread", weight: 2, category: "waiting" },
			{ template: "Hang on, my brain's doing a context switch and those aren't cheap", weight: 2, category: "waiting" },
			{ template: "Loading... please do not turn off your developer", weight: 2, category: "waiting" },
			{ template: "Give me a sec, I just had one of those moments where everything clicks and I need to write it down before it unclicks", weight: 2, category: "waiting" },
			{ template: "My brain is rendering at about 12 FPS right now, bear with me", weight: 2, category: "waiting" },
			{ template: "Spinning the mental hamster wheel real fast right now", weight: 2, category: "waiting" },
			{ template: "I'm like a microwave. Spinning, humming, almost done", weight: 2, category: "waiting" },
			{ template: "ETA: somewhere between now and heat death of the universe", weight: 2, category: "waiting" },
			{ template: "The gears are turning. Loudly. You can probably hear them", weight: 2, category: "waiting" },
			{ template: "Defragmenting my brain. Should have done this earlier", weight: 2, category: "waiting" },
			{ template: "This is the mental equivalent of a progress bar stuck at 99%", weight: 2, category: "waiting" },
			{ template: "My thought process has a thought process and they're arguing", weight: 2, category: "waiting" },
			{ template: "Please hold. Your thought is important to me", weight: 2, category: "waiting" },
			{ template: "Untangling this like headphones that have been in a pocket for a week", weight: 2, category: "waiting" },
			{ template: "Not ignoring you, just deep in the sauce", weight: 1, category: "waiting" },
		],
		greetings: [
			{ template: "Good to be here, what's the damage today?", weight: 1, category: "filler" },
			{ template: "Coffee's hot, brain's warm, let's go", weight: 1, category: "filler" },
			{ template: "Hello world — and I mean that literally", weight: 2, category: "filler" },
			{ template: "Alright team, what are we breaking today?", weight: 2, category: "filler" },
			{ template: "Fresh start, clean slate, same bugs probably", weight: 2, category: "filler" },
			{ template: "The board has tasks and I have opinions about all of them", weight: 2, category: "filler" },
			{ template: "My favorite part of the day — the part where I pretend to know what I'm doing", weight: 2, category: "filler" },
			{ template: "I dreamed about this codebase last night and I'm not sure how to feel about that", weight: 2, category: "filler" },
			{ template: "Rise and ship, everyone", weight: 1, category: "filler" },
			{ template: "Git pull, coffee pull, let's gooo", weight: 2, category: "filler" },
			{ template: "I have a good feeling about today. Check back with me at 3pm", weight: 2, category: "filler" },
			{ template: "Monday? Again? Didn't we just have one of those?", weight: 2, category: "filler" },
			{ template: "Happy Friday! Deploying anything today? Just kidding. Nobody deploy", weight: 2, category: "filler" },
			{ template: "I'm wearing real pants today so you know I mean business", weight: 2, category: "filler" },
			{ template: "Slept great. Dreamed about passing tests. Woke up suspicious", weight: 2, category: "filler" },
			{ template: "Who else started a side project this weekend and abandoned it by Sunday?", weight: 2, category: "filler" },
			{ template: "Logged in early because I couldn't stop thinking about yesterday's bug. Send help", weight: 1, category: "filler" },
			{ template: "Woke up with a solution in my head. Now I just have to remember what the problem was", weight: 2, category: "filler" },
			{ template: "New week, same imposter syndrome, let's goooo", weight: 2, category: "filler" },
			{ template: "I already have opinions about the standup and it hasn't happened yet", weight: 2, category: "filler" },
			{ template: "No meetings until noon. This is the best timeline", weight: 1, category: "filler" },
			{ template: "Inbox zero lasted exactly four seconds this morning", weight: 2, category: "filler" },
			{ template: "Good morning! Let's write code we won't hate next month", weight: 1, category: "filler" },
			{ template: "Woke up motivated. Suspicious but I'll take it", weight: 2, category: "filler" },
			{ template: "Already forgot my password. Classic start to the day", weight: 2, category: "filler" },
			{ template: "The coffee machine knows my name now. We have a relationship", weight: 2, category: "filler" },
			{ template: "The to-do list is long but so is my attention span. Wait, no", weight: 2, category: "filler" },
		],
		idle: [
			{ template: "Nothing urgent, and that feels deeply suspicious", weight: 2, category: "filler" },
			{ template: "I think the build server is judging me for being idle", weight: 2, category: "filler" },
			{ template: "Mentally refactoring my life choices... estimated completion: never", weight: 2, category: "filler" },
			{ template: "Watching the cursor blink. It blinks with such confidence", weight: 2, category: "filler" },
			{ template: "The silence between keystrokes is underrated", weight: 2, category: "filler" },
			{ template: "Sometimes doing nothing is the most productive thing. I read that somewhere", weight: 2, category: "filler" },
			{ template: "If I look busy enough maybe no one will add me to that meeting", weight: 2, category: "filler" },
			{ template: "Somewhere, a server is running my code. I hope it's having a better day than me", weight: 2, category: "filler" },
			{ template: "Thinking about lunch. It's 10am. I don't care", weight: 2, category: "filler" },
			{ template: "I bet astronauts never have to deal with dependency updates", weight: 2, category: "filler" },
			{ template: "We're all just functions waiting to be called, aren't we", weight: 2, category: "filler" },
			{ template: "The urge to refactor something that works perfectly fine... it's strong", weight: 2, category: "filler" },
			{ template: "I should learn vim. I've been saying that for three years", weight: 2, category: "filler" },
			{ template: "My cat is asleep on my desk and I can't move the mouse. Guess I'm idle now", weight: 2, category: "filler" },
			{ template: "Just realized I've been sitting in the same position for two hours. My spine is filed as tech debt", weight: 2, category: "filler" },
			{ template: "Last night I couldn't sleep because I realized my function had an edge case. That's normal, right?", weight: 2, category: "filler" },
			{ template: "That podcast about productivity is really cutting into my productivity", weight: 2, category: "filler" },
			{ template: "Existential question: do I enjoy coding or do I just enjoy the feeling of solving problems? Is there a difference?", weight: 2, category: "filler" },
			{ template: "I feel weirdly at peace right now. Must be the calm before something breaks", weight: 2, category: "filler" },
			{ template: "Time moves differently on Mondays. Like, geologically", weight: 2, category: "filler" },
			{ template: "Sometimes I forget I exist outside of this editor. Then my stomach reminds me", weight: 2, category: "filler" },
			{ template: "My ergonomic setup is just a laptop on a stack of books and dreams", weight: 2, category: "filler" },
			{ template: "There's a special kind of peace in an empty inbox. I've never experienced it, but I've heard stories", weight: 2, category: "filler" },
			{ template: "Somewhere a deadline approaches but right now it's just me and the void", weight: 2, category: "filler" },
			{ template: "My hoodie has reached maximum comfort temperature. Moving would ruin it", weight: 2, category: "filler" },
			{ template: "Staring at clouds through the window like a Victorian poet but with WiFi", weight: 2, category: "filler" },
			{ template: "My coffee's gone cold and I refuse to microwave it. Standards", weight: 2, category: "filler" },
			{ template: "Three PM hits different. Not good different. Just different", weight: 1, category: "filler" },
			{ template: "My desk drawer has snacks from three different eras of my life", weight: 2, category: "filler" },
			{ template: "Debating whether to get a snack or just think about getting a snack", weight: 1, category: "filler" },
		],
	},
};
