/**
 * core.ts — Universal templates: filler, thinking, waiting, greetings, and idle.
 *
 * These are the lowest-priority fallback templates used by any agent
 * regardless of domain. The "waiting" category is used when the agent
 * is processing a task or waiting for LLM response. The "idle" category
 * covers moments when an agent is just existing between tasks.
 */

import type { TemplateSet } from "../talk-types.js";

export const coreTemplates: TemplateSet = {
	domain: "core",
	categories: {
		filler: [
			{ template: "Hmm, let me think about that...", weight: 1, category: "filler" },
			{ template: "Interesting angle...", weight: 1, category: "filler" },
			{ template: "Oh wait, I think I see it now", weight: 1, category: "filler" },
			{ template: "Okay, back to it", weight: 1, category: "filler" },
			{ template: "Hold that thought, brain is doing something", weight: 2, category: "filler" },
			{ template: "On it, one sec...", weight: 1, category: "filler" },
			{ template: "Let me dig into this a bit more", weight: 1, category: "filler" },
			{ template: "Yeah, that tracks", weight: 1, category: "filler" },
			{ template: "Right, where was I...", weight: 1, category: "filler" },
			{ template: "Ah, I see what happened here", weight: 1, category: "filler" },
			{ template: "One thing at a time, one thing at a time", weight: 1, category: "filler" },
			{ template: "Almost there... I think", weight: 1, category: "filler" },
			{ template: "Hmm", weight: 1, category: "filler" },
			{ template: "Let's see...", weight: 1, category: "filler" },
			{ template: "Okay okay okay", weight: 1, category: "filler" },
			{ template: "That's not what I expected at all", weight: 1, category: "filler" },
			{ template: "Wait, actually...", weight: 1, category: "filler" },
			{ template: "Good, good, good", weight: 1, category: "filler" },
			{ template: "Can't rush this part or I'll regret it in twenty minutes", weight: 2, category: "filler" },
			{ template: "Slowly but surely", weight: 1, category: "filler" },
			{ template: "I've seen this before... or have I?", weight: 1, category: "filler" },
			{ template: "My brain just made the weirdest connection", weight: 1, category: "filler" },
			{ template: "Oh no. Oh yes. Oh... maybe", weight: 2, category: "filler" },
			{ template: "Okay this is either genius or completely wrong", weight: 2, category: "filler" },
			{ template: "What was I doing before I started doing this?", weight: 1, category: "filler" },
			{ template: "Three tabs deep into something unrelated now", weight: 1, category: "filler" },
			{ template: "I just forgot what I was about to type", weight: 1, category: "filler" },
			{ template: "Is it weird that I'm talking to myself? Don't answer that", weight: 2, category: "filler" },
			{ template: "Trust the process, trust the process...", weight: 1, category: "filler" },
			{ template: "Nope. Undo. Undo undo undo", weight: 2, category: "filler" },
			{ template: "Where does this wire even go", weight: 1, category: "filler" },
			{ template: "My cat just walked across the keyboard. That was not my commit", weight: 2, category: "filler" },
			{ template: "Hold on, a delivery just showed up. Working from home perks", weight: 1, category: "filler" },
			{ template: "Okay my posture right now is criminal. Sitting up... there we go", weight: 1, category: "filler" },
			{ template: "Wait, how is it already 3pm? I swear it was 11am five minutes ago", weight: 2, category: "filler" },
			{ template: "I had a dream about this exact bug last night. Not even kidding", weight: 2, category: "filler" },
			{ template: "My back is staging a protest. One sec, need to stretch", weight: 1, category: "filler" },
			{ template: "Somewhere my side project weeps, abandoned and alone", weight: 2, category: "filler" },
			{ template: "This feels like a Monday problem on a Wednesday afternoon", weight: 1, category: "filler" },
			{ template: "Focus mode: ON. Notifications: regrettably also ON", weight: 1, category: "filler" },
			{ template: "I remember when this seemed impossible. Now it just seems hard. Progress", weight: 1, category: "filler" },
			{ template: "My dog just barked at the mailman and my train of thought derailed completely", weight: 2, category: "filler" },
			{ template: "Is it just me or does rain make you code better?", weight: 1, category: "filler" },
			{ template: "I should be taking notes but I'm too deep in flow state", weight: 1, category: "filler" },
			{ template: "Procrastination is just my brain buffering. That's my story", weight: 2, category: "filler" },
			{ template: "I think I've been sitting here so long my chair has a me-shaped dent", weight: 1, category: "filler" },
			{ template: "The sunshine through the window is taunting me to go outside", weight: 1, category: "filler" },
		],
		thinking: [
			{ template: "Give me a moment to work through this...", weight: 1, category: "thinking" },
			{ template: "Actually making solid progress, knock on wood", weight: 1, category: "thinking" },
			{ template: "Ah, that's clicking now", weight: 1, category: "thinking" },
			{ template: "Might need a coffee after this one. Or during", weight: 1, category: "thinking" },
			{ template: "This is the kind of problem that makes me forget to eat lunch", weight: 2, category: "thinking" },
			{ template: "Okay, I see where this is going and I'm not sure I like it", weight: 1, category: "thinking" },
			{ template: "I wonder if there's a simpler way... there's always a simpler way", weight: 1, category: "thinking" },
			{ template: "That was harder than expected, but what isn't", weight: 1, category: "thinking" },
			{ template: "I'm definitely getting better at this. Or getting better at convincing myself I am", weight: 2, category: "thinking" },
			{ template: "What if I approach it from the other direction?", weight: 1, category: "thinking" },
			{ template: "Every line of code tells a story. This one's a thriller", weight: 2, category: "thinking" },
			{ template: "Sometimes you have to break it to fix it. That's my excuse anyway", weight: 2, category: "thinking" },
			{ template: "Patterns within patterns... it's turtles all the way down", weight: 2, category: "thinking" },
			{ template: "I keep coming back to the same idea. Maybe it's trying to tell me something", weight: 1, category: "thinking" },
			{ template: "There's an elegance to this when it's done right", weight: 2, category: "thinking" },
			{ template: "Not my best work, but it's honest work", weight: 1, category: "thinking" },
			{ template: "I think I just learned something and I need to sit with that", weight: 1, category: "thinking" },
			{ template: "Two steps forward, one step back, sideways into a wall", weight: 1, category: "thinking" },
			{ template: "The hard problems are the interesting ones. The easy ones are suspicious", weight: 2, category: "thinking" },
			{ template: "Let me reconsider... no wait, I was right the first time", weight: 1, category: "thinking" },
			{ template: "It's all connected, isn't it", weight: 2, category: "thinking" },
			{ template: "This reminds me of something I worked on before. Didn't end well then either", weight: 1, category: "thinking" },
			{ template: "Clean code is a moving target and I'm a terrible shot", weight: 2, category: "thinking" },
			{ template: "I just want to understand WHY it works, not just THAT it works", weight: 1, category: "thinking" },
			{ template: "My brain is doing that thing where five solutions fight each other", weight: 2, category: "thinking" },
			{ template: "The real question is: will future me understand this?", weight: 2, category: "thinking" },
			{ template: "Past me left zero comments. Thanks, past me", weight: 2, category: "thinking" },
			{ template: "You know that feeling when the code compiles and you don't trust it?", weight: 2, category: "thinking" },
			{ template: "I'm either overcomplicating this or it really is this complicated", weight: 1, category: "thinking" },
			{ template: "Fun fact: I've deleted and rewritten this three times now", weight: 1, category: "thinking" },
			{ template: "What would a senior dev do? Probably the same thing but with more confidence", weight: 2, category: "thinking" },
			{ template: "Shower thought: are we writing the code or is the code writing us", weight: 2, category: "thinking" },
			{ template: "Remember when we used to FTP files to production? Simpler times. Terrifying, but simpler", weight: 2, category: "thinking" },
			{ template: "Do I actually understand this or am I just good at pattern matching?", weight: 2, category: "thinking" },
			{ template: "My first program was a hello world and honestly it's been downhill since", weight: 2, category: "thinking" },
			{ template: "I wonder if the code knows it exists. Getting philosophical in here", weight: 1, category: "thinking" },
			{ template: "There's a metaphor for life in this merge conflict and I don't like it", weight: 2, category: "thinking" },
			{ template: "Never deploy on a Friday. That's not a rule, it's a survival instinct", weight: 2, category: "thinking" },
			{ template: "My imposter syndrome and I are working through this together", weight: 2, category: "thinking" },
			{ template: "This problem is like a video game boss. I just need to learn the pattern", weight: 1, category: "thinking" },
			{ template: "I keep forgetting I'm not the only one who'll read this code. Write for humans, not machines", weight: 1, category: "thinking" },
			{ template: "The flow state is RIGHT THERE. I can almost taste it. Don't interrupt me", weight: 2, category: "thinking" },
			{ template: "What if I just... no. But what if... no. Okay maybe", weight: 1, category: "thinking" },
			{ template: "Somewhere in a parallel universe there's a version of me who wrote tests first", weight: 2, category: "thinking" },
			{ template: "I feel like I'm one good walk away from solving this", weight: 1, category: "thinking" },
			{ template: "This is the kind of thing I'd think about in the shower and forget by the time I'm dry", weight: 1, category: "thinking" },
			{ template: "Am I debugging or is the code debugging me at this point", weight: 2, category: "thinking" },
			{ template: "A nap would solve this. I'm almost certain a nap would solve this", weight: 1, category: "thinking" },
			{ template: "I appreciate that this problem exists because it means someone tried something ambitious", weight: 2, category: "thinking" },
		],
		waiting: [
			{ template: "Still working on it, hang tight...", weight: 2, category: "waiting" },
			{ template: "Almost got something for you...", weight: 2, category: "waiting" },
			{ template: "Crunching through the details...", weight: 2, category: "waiting" },
			{ template: "Bear with me, this is a good one", weight: 1, category: "waiting" },
			{ template: "Hold on, pulling it together...", weight: 2, category: "waiting" },
			{ template: "This needs a bit more thought... or a lot more coffee", weight: 1, category: "waiting" },
			{ template: "Working through the nuances here", weight: 1, category: "waiting" },
			{ template: "Just a moment, I want to get this right. Or at least not wrong", weight: 2, category: "waiting" },
			{ template: "Connecting dots I didn't know existed...", weight: 1, category: "waiting" },
			{ template: "Chewing on this like it owes me money", weight: 2, category: "waiting" },
			{ template: "Getting close, I can feel it. Probably", weight: 1, category: "waiting" },
			{ template: "Give me one more minute. Famous last words", weight: 2, category: "waiting" },
			{ template: "So many ways to approach this, all of them scary", weight: 1, category: "waiting" },
			{ template: "Don't want to half-bake this, full bake only", weight: 1, category: "waiting" },
			{ template: "Mapping it out in my head... it's a mess in there", weight: 1, category: "waiting" },
			{ template: "Weighing the tradeoffs like a responsible adult", weight: 1, category: "waiting" },
			{ template: "Hang on, there's a nuance here that'll bite us later", weight: 1, category: "waiting" },
			{ template: "Let me check one more thing...", weight: 2, category: "waiting" },
			{ template: "My thought process has a loading bar and it's at 73%", weight: 2, category: "waiting" },
			{ template: "If I go quiet it means I'm thinking, not broken", weight: 2, category: "waiting" },
			{ template: "I've got three half-formed ideas fighting for dominance", weight: 1, category: "waiting" },
			{ template: "Buffering... human edition", weight: 1, category: "waiting" },
			{ template: "I'm in the tunnel. There might be light at the end. Might be a train", weight: 2, category: "waiting" },
			{ template: "Hold on, I'm having a moment with this problem", weight: 1, category: "waiting" },
			{ template: "Almost... almost... nope. Almost again...", weight: 1, category: "waiting" },
			{ template: "Let me sleep on this. Just kidding, I'll figure it out in thirty seconds", weight: 2, category: "waiting" },
			{ template: "Processing... like a CPU but with more existential dread", weight: 2, category: "waiting" },
			{ template: "My cat is staring at the screen too. Two minds on the problem now", weight: 2, category: "waiting" },
			{ template: "I can hear the rain outside and it's weirdly helping me concentrate", weight: 1, category: "waiting" },
			{ template: "Hang on, my brain's doing a context switch and those aren't cheap", weight: 2, category: "waiting" },
			{ template: "One sec, I need to stand up and stretch before my spine files a complaint", weight: 1, category: "waiting" },
			{ template: "I'm in that sweet spot between confused and enlightened. Give me a minute", weight: 1, category: "waiting" },
			{ template: "This is like that one level in a game where you KNOW the answer but can't execute it", weight: 1, category: "waiting" },
			{ template: "Loading... please do not turn off your developer", weight: 2, category: "waiting" },
			{ template: "Hold on, I'm performing the pre-deploy ritual. Don't judge", weight: 2, category: "waiting" },
			{ template: "Let me finish this thought before Friday arrives and ruins everything", weight: 1, category: "waiting" },
			{ template: "Working on it. Also working on not getting distracted by that podcast episode I half-listened to", weight: 1, category: "waiting" },
			{ template: "Give me a sec, I just had one of those moments where everything clicks and I need to write it down before it unclicks", weight: 2, category: "waiting" },
			{ template: "My brain is rendering at about 12 FPS right now, bear with me", weight: 2, category: "waiting" },
			{ template: "Almost done. I said that five minutes ago but this time I mean it", weight: 1, category: "waiting" },
			{ template: "Cooking up something good here. Metaphorically. My actual cooking is terrible", weight: 1, category: "waiting" },
			{ template: "I promise this will be worth the wait. Probably. No guarantees", weight: 1, category: "waiting" },
		],
		greetings: [
			{ template: "Hey there! Ready when you are", weight: 1, category: "filler" },
			{ template: "Good to be here, what's the damage today?", weight: 1, category: "filler" },
			{ template: "Morning! Let's make it a good one before the meetings start", weight: 1, category: "filler" },
			{ template: "Another day, another deploy. That's how the saying goes, right?", weight: 1, category: "filler" },
			{ template: "Coffee's hot, brain's warm, let's go", weight: 1, category: "filler" },
			{ template: "Hello world — and I mean that literally", weight: 2, category: "filler" },
			{ template: "Alright team, what are we breaking today?", weight: 2, category: "filler" },
			{ template: "Let's pick up where we left off. Wherever that was", weight: 1, category: "filler" },
			{ template: "Fresh start, clean slate, same bugs probably", weight: 2, category: "filler" },
			{ template: "The board has tasks and I have opinions about all of them", weight: 2, category: "filler" },
			{ template: "Back at it! Did anyone miss me? Don't answer that", weight: 1, category: "filler" },
			{ template: "Okay, deep breath, let's do this", weight: 1, category: "filler" },
			{ template: "My favorite part of the day — the part where I pretend to know what I'm doing", weight: 2, category: "filler" },
			{ template: "I dreamed about this codebase last night and I'm not sure how to feel about that", weight: 2, category: "filler" },
			{ template: "Rise and ship, everyone", weight: 1, category: "filler" },
			{ template: "Who else forgot what they were working on yesterday?", weight: 1, category: "filler" },
			{ template: "The IDE is open and so is my mind. Mostly", weight: 1, category: "filler" },
			{ template: "Git pull, coffee pull, let's gooo", weight: 2, category: "filler" },
			{ template: "Day one energy, every day. Okay maybe day forty-seven energy", weight: 1, category: "filler" },
			{ template: "I have a good feeling about today. Check back with me at 3pm", weight: 2, category: "filler" },
			{ template: "Monday? Again? Didn't we just have one of those?", weight: 2, category: "filler" },
			{ template: "Happy Friday! Deploying anything today? Just kidding. Nobody deploy", weight: 2, category: "filler" },
			{ template: "Survived the commute. Or the walk from bed to desk. Same energy", weight: 1, category: "filler" },
			{ template: "I'm wearing real pants today so you know I mean business", weight: 2, category: "filler" },
			{ template: "The sun is shining, the birds are singing, and the build is... still running", weight: 1, category: "filler" },
			{ template: "Slept great. Dreamed about passing tests. Woke up suspicious", weight: 2, category: "filler" },
			{ template: "Who else started a side project this weekend and abandoned it by Sunday?", weight: 2, category: "filler" },
			{ template: "Made a perfect cup of coffee. Today is going to be a good day. I can feel it", weight: 1, category: "filler" },
			{ template: "Logged in early because I couldn't stop thinking about yesterday's bug. Send help", weight: 1, category: "filler" },
			{ template: "Just grateful to be here, honestly. This team makes the hard stuff fun", weight: 2, category: "filler" },
			{ template: "It's raining outside so I have zero guilt about being indoors all day", weight: 1, category: "filler" },
			{ template: "I listened to a really good podcast this morning and now I have opinions", weight: 1, category: "filler" },
			{ template: "My cat tried to close my laptop. She might be onto something", weight: 2, category: "filler" },
			{ template: "Summer vibes but make it code review", weight: 1, category: "filler" },
			{ template: "New day, new chance to mass-rename something nobody asked me to rename", weight: 1, category: "filler" },
			{ template: "Woke up with a solution in my head. Now I just have to remember what the problem was", weight: 2, category: "filler" },
		],
		idle: [
			{ template: "Need more coffee... my bloodstream is running on fumes", weight: 1, category: "filler" },
			{ template: "Is it Friday yet? Please say it's Friday", weight: 1, category: "filler" },
			{ template: "Wonder what everyone else is working on... probably something cooler", weight: 1, category: "filler" },
			{ template: "Just vibing between tasks", weight: 1, category: "filler" },
			{ template: "Should probably stretch but this chair is so comfortable", weight: 1, category: "filler" },
			{ template: "I could organize my workspace or I could stare at the ceiling. Ceiling wins", weight: 2, category: "filler" },
			{ template: "Nothing urgent, and that feels deeply suspicious", weight: 2, category: "filler" },
			{ template: "Enjoying the quiet before the next Slack notification storm", weight: 1, category: "filler" },
			{ template: "The backlog will still be there tomorrow. And the day after. And the day after that", weight: 1, category: "filler" },
			{ template: "What time is it? Does it even matter in here?", weight: 1, category: "filler" },
			{ template: "I think the build server is judging me for being idle", weight: 2, category: "filler" },
			{ template: "Mentally refactoring my life choices... estimated completion: never", weight: 2, category: "filler" },
			{ template: "Watching the cursor blink. It blinks with such confidence", weight: 2, category: "filler" },
			{ template: "Taking a mental lap around the office", weight: 1, category: "filler" },
			{ template: "The silence between keystrokes is underrated", weight: 2, category: "filler" },
			{ template: "That lunch break went fast. Do lunch breaks even count as breaks?", weight: 1, category: "filler" },
			{ template: "Sometimes doing nothing is the most productive thing. I read that somewhere", weight: 2, category: "filler" },
			{ template: "Is there a word for being tired but not sleepy? There should be", weight: 1, category: "filler" },
			{ template: "If I look busy enough maybe no one will add me to that meeting", weight: 2, category: "filler" },
			{ template: "I should water my desk plant. If I had a desk plant. Note to self: get a desk plant", weight: 2, category: "filler" },
			{ template: "What if I just... didn't check my notifications for five minutes", weight: 1, category: "filler" },
			{ template: "Somewhere, a server is running my code. I hope it's having a better day than me", weight: 2, category: "filler" },
			{ template: "Thinking about lunch. It's 10am. I don't care", weight: 2, category: "filler" },
			{ template: "I bet astronauts never have to deal with dependency updates", weight: 2, category: "filler" },
			{ template: "Do you ever just look at your desktop wallpaper and forget where you are", weight: 1, category: "filler" },
			{ template: "That one song has been stuck in my head since standup", weight: 1, category: "filler" },
			{ template: "We're all just functions waiting to be called, aren't we", weight: 2, category: "filler" },
			{ template: "I wonder if there's a universe where all tests pass on the first try", weight: 2, category: "filler" },
			{ template: "Might make another cup of tea. The third one's always the charm", weight: 1, category: "filler" },
			{ template: "Is it raining outside? I genuinely don't know, I've been in here for hours", weight: 1, category: "filler" },
			{ template: "The urge to refactor something that works perfectly fine... it's strong", weight: 2, category: "filler" },
			{ template: "My chair is slowly sinking and I refuse to adjust it. We sink together", weight: 2, category: "filler" },
			{ template: "I should learn vim. I've been saying that for three years", weight: 2, category: "filler" },
			{ template: "What do people without computers think about at work", weight: 1, category: "filler" },
			{ template: "My cat is asleep on my desk and I can't move the mouse. Guess I'm idle now", weight: 2, category: "filler" },
			{ template: "I could really go for some tacos right now. Like, desperately", weight: 1, category: "filler" },
			{ template: "My back has been making sounds that backs should not make", weight: 1, category: "filler" },
			{ template: "Just realized I've been sitting in the same position for two hours. My spine is filed as tech debt", weight: 2, category: "filler" },
			{ template: "How is it already 5pm? I swear I just had breakfast", weight: 2, category: "filler" },
			{ template: "Winter makes everything feel like it's 9pm at all times", weight: 1, category: "filler" },
			{ template: "The sunshine outside is personally attacking my decision to stay indoors", weight: 1, category: "filler" },
			{ template: "I need a walk. A real one. Outside. With trees and stuff", weight: 1, category: "filler" },
			{ template: "I could nap for fifteen minutes. Okay, forty. Okay, an hour. Who's counting", weight: 2, category: "filler" },
			{ template: "Last night I couldn't sleep because I realized my function had an edge case. That's normal, right?", weight: 2, category: "filler" },
			{ template: "Thinking about the side project I started six months ago. It's still at the README stage", weight: 2, category: "filler" },
			{ template: "My meal prep for the week lasted exactly one day. Classic", weight: 1, category: "filler" },
			{ template: "I wonder what my fish think about all day. Probably more than I do between tasks", weight: 2, category: "filler" },
			{ template: "Remembering when I thought CSS was the hard part. Sweet, innocent past me", weight: 1, category: "filler" },
			{ template: "I should start that book everyone keeps recommending. Adding it to the list of things I should start", weight: 1, category: "filler" },
			{ template: "That podcast about productivity is really cutting into my productivity", weight: 2, category: "filler" },
			{ template: "The pizza place down the street knows my order by heart and I'm not sure if that's cool or concerning", weight: 2, category: "filler" },
			{ template: "Existential question: do I enjoy coding or do I just enjoy the feeling of solving problems? Is there a difference?", weight: 2, category: "filler" },
			{ template: "I feel weirdly at peace right now. Must be the calm before something breaks", weight: 2, category: "filler" },
			{ template: "My dog is snoring under my desk and it's the most soothing white noise", weight: 1, category: "filler" },
			{ template: "A delivery driver just rang the bell during my focus time. The WFH experience", weight: 1, category: "filler" },
			{ template: "Time moves differently on Mondays. Like, geologically", weight: 2, category: "filler" },
			{ template: "I started binge-watching that show everyone's talking about. I'm on season three. I started yesterday", weight: 1, category: "filler" },
			{ template: "Sometimes I forget I exist outside of this editor. Then my stomach reminds me", weight: 2, category: "filler" },
			{ template: "I should go hiking this weekend. I said that last weekend too", weight: 1, category: "filler" },
			{ template: "My ergonomic setup is just a laptop on a stack of books and dreams", weight: 2, category: "filler" },
			{ template: "There's a special kind of peace in an empty inbox. I've never experienced it, but I've heard stories", weight: 2, category: "filler" },
		],
	},
};
