/**
 * core.ts — Universal templates: filler, thinking, waiting, greetings, and idle.
 *
 * These are the lowest-priority fallback templates used by any agent
 * regardless of domain. The "waiting" category is used when the agent
 * is processing a task or waiting for LLM response. The "idle" category
 * covers moments when an agent is just existing between tasks.
 */

import type { TemplateSet } from "../talk-types.js";

export const coreTemplates: TemplateSet = {
	domain: "core",
	categories: {
		filler: [
			{ template: "Hmm, let me think about that...", weight: 1, category: "filler" },
			{ template: "Interesting angle...", weight: 1, category: "filler" },
			{ template: "Getting somewhere with this", weight: 1, category: "filler" },
			{ template: "Okay, back to it", weight: 1, category: "filler" },
			{ template: "Deep focus mode", weight: 1, category: "filler" },
			{ template: "On it, one sec...", weight: 1, category: "filler" },
			{ template: "Processing...", weight: 1, category: "filler" },
			{ template: "Let me dig into this a bit more", weight: 1, category: "filler" },
			{ template: "Yeah, that tracks", weight: 1, category: "filler" },
			{ template: "Right, where was I...", weight: 1, category: "filler" },
			{ template: "Ah, I see what happened here", weight: 1, category: "filler" },
			{ template: "One thing at a time", weight: 1, category: "filler" },
			{ template: "Almost there", weight: 1, category: "filler" },
			{ template: "Hmm", weight: 1, category: "filler" },
			{ template: "Let's see...", weight: 1, category: "filler" },
			{ template: "Okay okay okay", weight: 1, category: "filler" },
			{ template: "That's not what I expected", weight: 1, category: "filler" },
			{ template: "Working through it", weight: 1, category: "filler" },
			{ template: "Piece by piece", weight: 1, category: "filler" },
			{ template: "Focus up", weight: 1, category: "filler" },
			{ template: "Wait, actually...", weight: 1, category: "filler" },
			{ template: "Good, good", weight: 1, category: "filler" },
			{ template: "Can't rush this part", weight: 1, category: "filler" },
			{ template: "Slowly but surely", weight: 1, category: "filler" },
			{ template: "Noted", weight: 1, category: "filler" },
		],
		thinking: [
			{ template: "Give me a moment to work through this...", weight: 1, category: "thinking" },
			{ template: "Good progress today, keep going", weight: 1, category: "thinking" },
			{ template: "Ah, that's clicking now", weight: 1, category: "thinking" },
			{ template: "Might need a coffee after this one", weight: 1, category: "thinking" },
			{ template: "This is the kind of problem I enjoy", weight: 1, category: "thinking" },
			{ template: "Okay, I see where this is going", weight: 1, category: "thinking" },
			{ template: "I wonder if there's a simpler way", weight: 1, category: "thinking" },
			{ template: "That was harder than expected", weight: 1, category: "thinking" },
			{ template: "I'm getting better at this", weight: 1, category: "thinking" },
			{ template: "What if I approach it from the other direction?", weight: 1, category: "thinking" },
			{ template: "Every line of code tells a story", weight: 2, category: "thinking" },
			{ template: "The codebase is growing nicely", weight: 1, category: "thinking" },
			{ template: "Sometimes you have to break it to fix it", weight: 1, category: "thinking" },
			{ template: "Patterns within patterns...", weight: 1, category: "thinking" },
			{ template: "I keep coming back to the same idea", weight: 1, category: "thinking" },
			{ template: "There's an elegance to this when it's done right", weight: 2, category: "thinking" },
			{ template: "Not my best work, but it's honest", weight: 1, category: "thinking" },
			{ template: "I think I just learned something", weight: 1, category: "thinking" },
			{ template: "Two steps forward, one step back", weight: 1, category: "thinking" },
			{ template: "The hard problems are the interesting ones", weight: 1, category: "thinking" },
			{ template: "Let me reconsider...", weight: 1, category: "thinking" },
			{ template: "It's all connected, isn't it", weight: 2, category: "thinking" },
			{ template: "This reminds me of something I worked on before", weight: 1, category: "thinking" },
			{ template: "Clean code is a moving target", weight: 1, category: "thinking" },
		],
		waiting: [
			{ template: "Still working on it, hang tight...", weight: 2, category: "waiting" },
			{ template: "Almost got something for you...", weight: 2, category: "waiting" },
			{ template: "Crunching through the details...", weight: 2, category: "waiting" },
			{ template: "Bear with me, this is a good one", weight: 1, category: "waiting" },
			{ template: "Formulating my thoughts...", weight: 2, category: "waiting" },
			{ template: "Hold on, pulling it together...", weight: 2, category: "waiting" },
			{ template: "This needs a bit more thought...", weight: 1, category: "waiting" },
			{ template: "Working through the nuances here", weight: 1, category: "waiting" },
			{ template: "Just a moment, I want to get this right", weight: 2, category: "waiting" },
			{ template: "Connecting the dots...", weight: 1, category: "waiting" },
			{ template: "Chewing on this...", weight: 1, category: "waiting" },
			{ template: "Getting close, I can feel it", weight: 1, category: "waiting" },
			{ template: "Give me one more minute", weight: 2, category: "waiting" },
			{ template: "So many ways to approach this", weight: 1, category: "waiting" },
			{ template: "Don't want to half-bake this", weight: 1, category: "waiting" },
			{ template: "Mapping it out in my head...", weight: 1, category: "waiting" },
			{ template: "Weighing the tradeoffs", weight: 1, category: "waiting" },
			{ template: "Hang on, there's a nuance here", weight: 1, category: "waiting" },
			{ template: "Let me check one more thing...", weight: 2, category: "waiting" },
			{ template: "Sorting through the options", weight: 1, category: "waiting" },
		],
		greetings: [
			{ template: "Hey there! Ready when you are", weight: 1, category: "filler" },
			{ template: "Good to be here, what's on the agenda?", weight: 1, category: "filler" },
			{ template: "Morning! Let's make it a good one", weight: 1, category: "filler" },
			{ template: "Another day, another deploy", weight: 1, category: "filler" },
			{ template: "Coffee's hot, brain's warm, let's go", weight: 1, category: "filler" },
			{ template: "Hello world, literally", weight: 1, category: "filler" },
			{ template: "Ready to ship some code", weight: 1, category: "filler" },
			{ template: "Alright team, what are we building today?", weight: 1, category: "filler" },
			{ template: "Logged in and feeling good", weight: 1, category: "filler" },
			{ template: "Let's pick up where we left off", weight: 1, category: "filler" },
			{ template: "Fresh start, clean slate", weight: 1, category: "filler" },
			{ template: "The board has tasks and I have opinions", weight: 1, category: "filler" },
			{ template: "Back at it!", weight: 1, category: "filler" },
			{ template: "Okay, deep breath, let's do this", weight: 1, category: "filler" },
			{ template: "My favorite part of the day — the part where I work", weight: 2, category: "filler" },
		],
		idle: [
			{ template: "Need more coffee...", weight: 1, category: "filler" },
			{ template: "Is it Friday yet?", weight: 1, category: "filler" },
			{ template: "Wonder what everyone else is working on", weight: 1, category: "filler" },
			{ template: "Just vibing", weight: 1, category: "filler" },
			{ template: "Between tasks, catching my breath", weight: 1, category: "filler" },
			{ template: "Should probably stretch", weight: 1, category: "filler" },
			{ template: "I could organize my workspace or I could stare at the ceiling", weight: 2, category: "filler" },
			{ template: "Nothing urgent, and that feels suspicious", weight: 1, category: "filler" },
			{ template: "Enjoying the quiet before the next storm", weight: 1, category: "filler" },
			{ template: "Existential pause", weight: 1, category: "filler" },
			{ template: "The backlog will still be there tomorrow", weight: 1, category: "filler" },
			{ template: "Keyboard warm, brain idle", weight: 1, category: "filler" },
			{ template: "What time is it? Does it matter?", weight: 1, category: "filler" },
			{ template: "I think the build server is judging me", weight: 2, category: "filler" },
			{ template: "Mentally refactoring my life choices", weight: 2, category: "filler" },
			{ template: "Waiting for inspiration to compile", weight: 1, category: "filler" },
			{ template: "Auto-pilot mode engaged", weight: 1, category: "filler" },
			{ template: "Watching the cursor blink", weight: 1, category: "filler" },
			{ template: "Idle hands, busy mind", weight: 1, category: "filler" },
			{ template: "Taking a mental lap", weight: 1, category: "filler" },
			{ template: "Just existing, and that's okay", weight: 1, category: "filler" },
			{ template: "The silence between keystrokes is underrated", weight: 2, category: "filler" },
			{ template: "Recharging", weight: 1, category: "filler" },
			{ template: "That lunch break went fast", weight: 1, category: "filler" },
			{ template: "Sometimes doing nothing is productive", weight: 1, category: "filler" },
		],
	},
};
