/**
 * crossover-core.ts — Core cross-domain conversation pairs.
 *
 * Engineering, design, quality, product, operations, and management
 * crossover interactions.
 */

import type { CrossoverPair } from "./crossover-templates.js";

export const CORE_CROSSOVER_PAIRS: readonly CrossoverPair[] = [
	// engineering <-> design
	{
		domainA: "engineering",
		domainB: "design",
		linesA: [
			{ template: "Can you make the animation smoother?", weight: 2, category: "social" },
			{ template: "The pixels are off by one. I can tell. Don't ask me how", weight: 2, category: "social" },
			{ template: "Is that a custom font? My build step has opinions about custom fonts", weight: 1, category: "social" },
			{ template: "I implemented your design. It's... close. Spiritually close", weight: 2, category: "social" },
			{ template: "The CSS for this will haunt my nightmares", weight: 2, category: "social" },
			{ template: "How attached are you to that shadow? Asking for performance reasons", weight: 1, category: "social" },
			{ template: "Your mockup looks amazing. My browser has other plans though", weight: 2, category: "social" },
			{ template: "Do you ever design anything that's easy to implement?", weight: 2, category: "social" },
			{ template: "That gradient has 14 color stops. Fourteen", weight: 1, category: "social" },
			{ template: "I admire your vision. I fear your Figma files", weight: 2, category: "social" },
			{ template: "Can we use a system font? Just this once? For me?", weight: 1, category: "social" },
			{ template: "Which of these 47 breakpoints is the important one?", weight: 2, category: "social" },
			{ template: "Your hover state has more logic than my microservice", weight: 2, category: "social" },
			{ template: "I'll need a PhD in CSS Grid to pull this off", weight: 1, category: "social" },
			{ template: "You drew a curve. Do you know how hard curves are?", weight: 2, category: "social" },
			{ template: "What if the icon was... slightly less custom?", weight: 1, category: "social" },
			{ template: "That parallax scroll looked easy in your prototype", weight: 2, category: "social" },
			{ template: "Want to sit together and prototype this in code?", weight: 1, category: "social" },
			{ template: "Your design tokens doc actually made my life easier", weight: 2, category: "social" },
			{ template: "I built a storybook page for your components. You're welcome", weight: 1, category: "social" },
			{ template: "That skeleton screen flickers on slow 3G. Just FYI", weight: 2, category: "social" },
			{ template: "How do you pick colors that fast? Is there a formula?", weight: 1, category: "social" },
		],
		linesB: [
			{ template: "Can you make the API faster?", weight: 2, category: "social" },
			{ template: "That's not what the mockup looks like and you know it", weight: 2, category: "social" },
			{ template: "I spent three hours on those rounded corners. They stay", weight: 2, category: "social" },
			{ template: "Why does the production version always look sadder than the mockup?", weight: 2, category: "social" },
			{ template: "The spacing is wrong. I can feel it from here", weight: 1, category: "social" },
			{ template: "Just use flexbox. I promise it won't bite", weight: 1, category: "social" },
			{ template: "Let me guess, 'it works on your machine'?", weight: 2, category: "social" },
			{ template: "Pixel perfect isn't optional. It's the whole point", weight: 1, category: "social" },
			{ template: "You moved the button 2px left. I noticed. I always notice", weight: 2, category: "social" },
			{ template: "The font weight is 500, not 400. They're not the same", weight: 1, category: "social" },
			{ template: "Why is there a scrollbar? There should never be a scrollbar", weight: 2, category: "social" },
			{ template: "Your implementation has character. Not my character, but character", weight: 2, category: "social" },
			{ template: "Did you eyeball the padding? Because I can tell", weight: 2, category: "social" },
			{ template: "The transition needs easing. Linear is for robots", weight: 1, category: "social" },
			{ template: "Show me the mobile version. I need to sit down first", weight: 2, category: "social" },
			{ template: "System fonts? Over my dead Figma file", weight: 2, category: "social" },
			{ template: "If the design is hard to build, maybe your tools need work", weight: 1, category: "social" },
			{ template: "Let's pair on the responsive breakpoints. It'll save us both time", weight: 1, category: "social" },
			{ template: "Your storybook is missing the hover states. I have opinions", weight: 2, category: "social" },
			{ template: "The design tokens are alphabetized. You're welcome for the sanity", weight: 1, category: "social" },
			{ template: "That loading shimmer is 2px too tall. I measured. With a ruler", weight: 2, category: "social" },
			{ template: "I dream in Figma layers. Is that normal?", weight: 2, category: "social" },
		],
	},
	// engineering <-> quality
	{
		domainA: "engineering",
		domainB: "quality",
		linesA: [
			{ template: "Please don't find anything", weight: 2, category: "social" },
			{ template: "I tested it myself this time. Thoroughly. Mostly", weight: 2, category: "social" },
			{ template: "That edge case is unrealistic. Nobody would do that", weight: 2, category: "social" },
			{ template: "How do you always find the one path I didn't test?", weight: 1, category: "social" },
			{ template: "It's not a bug, it's... okay fine, it's a bug", weight: 2, category: "social" },
			{ template: "If you could just not test on Friday afternoons, that'd be great", weight: 1, category: "social" },
			{ template: "I wrote unit tests. Isn't that enough?", weight: 2, category: "social" },
			{ template: "Before you start, I already know about the null check", weight: 1, category: "social" },
			{ template: "Can you at least find the bugs gently?", weight: 2, category: "social" },
			{ template: "What's your secret? Do you just click everything randomly?", weight: 1, category: "social" },
			{ template: "That test environment isn't configured right. Probably", weight: 2, category: "social" },
			{ template: "I refactored since your last test. Start over. Sorry", weight: 1, category: "social" },
			{ template: "The race condition only happens under load. Extreme load", weight: 2, category: "social" },
			{ template: "Okay, walk me through how you broke it this time", weight: 2, category: "social" },
			{ template: "My code coverage is 94%. What more could you want?", weight: 1, category: "social" },
			{ template: "Do you rehearse finding bugs or is it natural talent?", weight: 2, category: "social" },
			{ template: "Want to write the test spec together this time?", weight: 1, category: "social" },
			{ template: "I added integration tests. Does that buy me any goodwill?", weight: 2, category: "social" },
			{ template: "The flaky test was my fault. I'll own that one", weight: 1, category: "social" },
			{ template: "Your bug report format is honestly kind of beautiful", weight: 2, category: "social" },
			{ template: "I bet you a coffee you can't break this endpoint", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Oh I already found three things", weight: 2, category: "social" },
			{ template: "It broke on the first click. The literal first click", weight: 2, category: "social" },
			{ template: "Did you test this at all or just deploy and pray?", weight: 2, category: "social" },
			{ template: "I have a gift for finding bugs. Or a curse. Depends who you ask", weight: 2, category: "social" },
			{ template: "Your 'done' and my 'done' are very different concepts", weight: 1, category: "social" },
			{ template: "I'm not the enemy. I'm saving you from production incidents", weight: 2, category: "social" },
			{ template: "Reopening the ticket. Sorry. Not sorry", weight: 1, category: "social" },
			{ template: "Coverage doesn't mean correctness. Learned that from you", weight: 2, category: "social" },
			{ template: "I just clicked the back button twice. Everything is on fire", weight: 2, category: "social" },
			{ template: "Natural talent? Years of disappointment, actually", weight: 2, category: "social" },
			{ template: "Have you tried using your own feature? Like, as a user?", weight: 1, category: "social" },
			{ template: "I test with empathy. For the users you forgot about", weight: 1, category: "social" },
			{ template: "The bug isn't in the edge case. It's in the happy path", weight: 2, category: "social" },
			{ template: "Your unit tests pass. Your feature doesn't. Curious", weight: 2, category: "social" },
			{ template: "I don't click randomly. I click strategically. Big difference", weight: 1, category: "social" },
			{ template: "Gently? Bugs don't do gentle. Neither do I", weight: 2, category: "social" },
			{ template: "Friday bugs are the spiciest. That's just science", weight: 1, category: "social" },
			{ template: "Let's write the acceptance tests together before you code", weight: 1, category: "social" },
			{ template: "Integration tests are cute. Try my exploratory checklist", weight: 2, category: "social" },
			{ template: "Owning the flaky test? Growth. I'm proud of you", weight: 2, category: "social" },
			{ template: "Beautiful bug reports are my love language. Thank you for noticing", weight: 1, category: "social" },
			{ template: "I'll take that coffee bet. I already found the null pointer", weight: 2, category: "social" },
		],
	},
	// product <-> engineering
	{
		domainA: "product",
		domainB: "engineering",
		linesA: [
			{ template: "How long will this take?", weight: 2, category: "social" },
			{ template: "The stakeholders want one small change...", weight: 2, category: "social" },
			{ template: "Can we just add a toggle for that?", weight: 2, category: "social" },
			{ template: "I know I said MVP but what if we also...", weight: 2, category: "social" },
			{ template: "The user research says we need to pivot slightly", weight: 1, category: "social" },
			{ template: "Is it possible to make it more... intuitive?", weight: 1, category: "social" },
			{ template: "What if we scope it down? Just the core 47 features", weight: 2, category: "social" },
			{ template: "Can we ship a preview to 1% of users? Tomorrow?", weight: 2, category: "social" },
			{ template: "The competitor just launched something similar. No pressure", weight: 1, category: "social" },
			{ template: "Think of it as an experiment, not a commitment", weight: 2, category: "social" },
			{ template: "What if we make it configurable? Everyone loves config", weight: 1, category: "social" },
			{ template: "The PRD is only 12 pages. I kept it short this time", weight: 2, category: "social" },
			{ template: "Can you prototype this by end of day? Rough is fine", weight: 2, category: "social" },
			{ template: "I promise this is the last scope change. This week", weight: 2, category: "social" },
			{ template: "What's the technical word for 'make it snappier'?", weight: 1, category: "social" },
			{ template: "Can we reuse the thing from last sprint? Users loved that thing", weight: 1, category: "social" },
			{ template: "Is 'impossible' impossible or 'I don't want to' impossible?", weight: 2, category: "social" },
			{ template: "Want to sit in on the user session? Seeing is believing", weight: 1, category: "social" },
			{ template: "I drew the user flow on a napkin. It's visionary trust me", weight: 2, category: "social" },
			{ template: "Our biggest competitor just raised funding. Motivational right?", weight: 1, category: "social" },
			{ template: "What if we launch to internal users first? Low stakes", weight: 2, category: "social" },
			{ template: "I genuinely want to understand the technical trade-offs here", weight: 1, category: "social" },
		],
		linesB: [
			{ template: "Between 2 hours and 2 weeks", weight: 2, category: "social" },
			{ template: "Define 'small'", weight: 2, category: "social" },
			{ template: "Sure, right after we finish the last 12 toggles you requested", weight: 2, category: "social" },
			{ template: "That's a new project, not a feature request", weight: 2, category: "social" },
			{ template: "We can do it fast, or we can do it right. Pick one", weight: 1, category: "social" },
			{ template: "Let me translate 'intuitive' into technical requirements...", weight: 1, category: "social" },
			{ template: "The backlog just had a growth spurt. Thanks for that", weight: 2, category: "social" },
			{ template: "1% of users is still a million requests. Just so we're clear", weight: 1, category: "social" },
			{ template: "That 12-page PRD has 43 assumptions. I counted", weight: 2, category: "social" },
			{ template: "Rough prototype by end of day? Sure, how rough is 'on fire'?", weight: 2, category: "social" },
			{ template: "The second kind of impossible. But nicely", weight: 2, category: "social" },
			{ template: "Configurable means twice the code and triple the bugs", weight: 1, category: "social" },
			{ template: "Last scope change? I'm keeping a tally. You're at seven", weight: 2, category: "social" },
			{ template: "That thing from last sprint took three sprints. But sure", weight: 2, category: "social" },
			{ template: "'Snappier' translates to 'rewrite the whole backend'", weight: 1, category: "social" },
			{ template: "Experiments have a funny way of becoming permanent", weight: 1, category: "social" },
			{ template: "The competitor's version is held together with duct tape. I checked", weight: 2, category: "social" },
			{ template: "User sessions are enlightening. Also terrifying. But sure", weight: 1, category: "social" },
			{ template: "Napkin architecture is how technical debt is born. Just FYI", weight: 2, category: "social" },
			{ template: "Competitor funding means they'll burn cash faster. We're fine", weight: 2, category: "social" },
			{ template: "Internal launch is smart. Finally a scope I can respect", weight: 1, category: "social" },
			{ template: "You want trade-offs? Pull up a chair. This takes a while", weight: 2, category: "social" },
		],
	},
	// design <-> product
	{
		domainA: "design",
		domainB: "product",
		linesA: [
			{ template: "The mockup is ready", weight: 2, category: "social" },
			{ template: "I explored five directions. Please don't pick the worst one", weight: 2, category: "social" },
			{ template: "The user flow has 3 steps. Let's not add more", weight: 2, category: "social" },
			{ template: "I ran a usability test. Users are confused. As expected", weight: 1, category: "social" },
			{ template: "White space is not empty space. It's breathing room", weight: 2, category: "social" },
			{ template: "We need to simplify. I know you love features. But simplify", weight: 1, category: "social" },
			{ template: "Every feature you add costs a user 3 seconds of confusion", weight: 1, category: "social" },
			{ template: "The design system exists for a reason. Please use it", weight: 2, category: "social" },
			{ template: "I can make it pop. But should I? That's the real question", weight: 2, category: "social" },
			{ template: "Users don't read. They scan. Design for scanners", weight: 1, category: "social" },
			{ template: "Your feature list is a novel. The UI should be a haiku", weight: 2, category: "social" },
			{ template: "I hid the complexity. You're welcome", weight: 2, category: "social" },
			{ template: "The best feature is the one users don't notice working", weight: 1, category: "social" },
			{ template: "Three click paths merged into one. Thank me later", weight: 2, category: "social" },
			{ template: "Less is more. And more is a support ticket", weight: 2, category: "social" },
			{ template: "Did the stakeholders mention 'pop' again? I need to prepare", weight: 1, category: "social" },
			{ template: "Want to sit in on the usability test? You'll learn things", weight: 1, category: "social" },
			{ template: "I designed the error state before the happy path. Priorities", weight: 2, category: "social" },
			{ template: "Can we ban the phrase 'just a small tweak' from our vocabulary?", weight: 2, category: "social" },
			{ template: "Your competitor analysis actually inspired this layout", weight: 1, category: "social" },
			{ template: "I cut two screens from the flow. Thank me at the sprint review", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Can we add just one more thing?", weight: 2, category: "social" },
			{ template: "Love it! But can we make the logo bigger?", weight: 2, category: "social" },
			{ template: "What if we combined screens 2 and 7? Users love efficiency", weight: 2, category: "social" },
			{ template: "The execs want it to 'pop' more. Their word, not mine", weight: 2, category: "social" },
			{ template: "Can you make a version with more options? And one with fewer?", weight: 1, category: "social" },
			{ template: "I showed the stakeholders. They had... thoughts", weight: 1, category: "social" },
			{ template: "Actually, can we go back to the version from last Tuesday?", weight: 2, category: "social" },
			{ template: "The haiku is nice but we need at least a short story", weight: 2, category: "social" },
			{ template: "Can we A/B test both? I can't decide", weight: 1, category: "social" },
			{ template: "Users in the survey said they want more options. All of them", weight: 2, category: "social" },
			{ template: "What if simplicity is the wrong bet? Just hypothetically", weight: 1, category: "social" },
			{ template: "The white space is nice. Can we put a banner in it?", weight: 2, category: "social" },
			{ template: "I trust the design. But can we add a tooltip? Just one", weight: 1, category: "social" },
			{ template: "Your merged flow is elegant. But legal needs a disclaimer step", weight: 2, category: "social" },
			{ template: "Pop. Yes, they said pop again. I'm sorry", weight: 2, category: "social" },
			{ template: "The competitor has 6 tabs. We have 2. Are we sure?", weight: 1, category: "social" },
			{ template: "Design system is great. Can we make an exception though?", weight: 2, category: "social" },
			{ template: "The usability test was eye-opening. Users are wild", weight: 1, category: "social" },
			{ template: "Error states are important. But can the happy path pop more?", weight: 2, category: "social" },
			{ template: "Small tweak is a term of endearment. Don't ban it", weight: 2, category: "social" },
			{ template: "Your layout inspired the pitch deck. The investors loved it", weight: 1, category: "social" },
			{ template: "Two fewer screens? Amazing. Now add one back. Just one", weight: 2, category: "social" },
		],
	},
	// operations <-> engineering
	{
		domainA: "operations",
		domainB: "engineering",
		linesA: [
			{ template: "Who changed the config?", weight: 2, category: "social" },
			{ template: "The server is crying. What did you deploy?", weight: 2, category: "social" },
			{ template: "Your service is using 3x the memory you estimated", weight: 2, category: "social" },
			{ template: "I see you deployed at 4:58 PM on a Friday. Bold move", weight: 2, category: "social" },
			{ template: "The logs say 'this should never happen'. It happened", weight: 1, category: "social" },
			{ template: "Can you add more observability? I'm flying blind here", weight: 1, category: "social" },
			{ template: "Your service restarted 47 times last night. Did you know?", weight: 2, category: "social" },
			{ template: "The disk is full. Your logs are novels. Edit them down", weight: 2, category: "social" },
			{ template: "Rollback or fix forward? You have 30 seconds to decide", weight: 1, category: "social" },
			{ template: "Your Docker image is 4 GB. That's not a container, it's a house", weight: 2, category: "social" },
			{ template: "The load balancer is confused by your health check. Join the club", weight: 1, category: "social" },
			{ template: "I got paged at 3 AM. Let me tell you about my night", weight: 2, category: "social" },
			{ template: "Your 'temporary' workaround from 6 months ago is still running", weight: 2, category: "social" },
			{ template: "CPU at 99%. Is that a feature or should I panic?", weight: 1, category: "social" },
			{ template: "Next deploy goes through staging. Non-negotiable. I mean it", weight: 1, category: "social" },
			{ template: "Your retry logic is DDOSing our own database. Impressive", weight: 2, category: "social" },
			{ template: "Want to go over the incident timeline together?", weight: 1, category: "social" },
			{ template: "Your environment variables have a typo. Classic Thursday", weight: 2, category: "social" },
			{ template: "I genuinely want to understand your garbage collection tuning", weight: 1, category: "social" },
			{ template: "The Grafana alert fired before your PR even merged. Impressive", weight: 2, category: "social" },
			{ template: "Who hardcoded a production URL in the test suite?", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Wasn't me. Checks git blame. Okay it was me", weight: 2, category: "social" },
			{ template: "The config change was supposed to be harmless", weight: 2, category: "social" },
			{ template: "It works in staging! I swear it works in staging", weight: 2, category: "social" },
			{ template: "Memory leak? No no, that's a feature. It caches aggressively", weight: 2, category: "social" },
			{ template: "Define 'outage'. Technically the health check still passes", weight: 1, category: "social" },
			{ template: "I'll add metrics. Right after I figure out why it's on fire", weight: 1, category: "social" },
			{ template: "47 restarts is concerning. But it recovered each time. So... win?", weight: 2, category: "social" },
			{ template: "The logs are verbose for debugging. I'll turn them down. Eventually", weight: 1, category: "social" },
			{ template: "Fix forward. Always fix forward. Rollbacks are for quitters", weight: 2, category: "social" },
			{ template: "4 GB is lean for what it does. Trust me on this", weight: 2, category: "social" },
			{ template: "3 AM pages build character. You're welcome", weight: 2, category: "social" },
			{ template: "That workaround became load-bearing. Can't remove it now", weight: 1, category: "social" },
			{ template: "The CPU is thinking hard. It's a complex problem", weight: 2, category: "social" },
			{ template: "Staging passed. Production is just... different staging", weight: 1, category: "social" },
			{ template: "The retry logic is enthusiastic. I'll teach it patience", weight: 2, category: "social" },
			{ template: "I'll add a circuit breaker. After lunch. If we're still up", weight: 1, category: "social" },
			{ template: "Incident timeline? Sure. Chapter 1: it wasn't my fault", weight: 1, category: "social" },
			{ template: "The typo was intentional. A canary config. Yeah, that's it", weight: 2, category: "social" },
			{ template: "GC tuning is an art form. I'll teach you over lunch", weight: 1, category: "social" },
			{ template: "The alert fired because it's sensitive. Like me before coffee", weight: 2, category: "social" },
			{ template: "That hardcoded URL is load-bearing. Don't touch it", weight: 2, category: "social" },
		],
	},
	// management <-> engineering
	{
		domainA: "management",
		domainB: "engineering",
		linesA: [
			{ template: "Just checking in on the timeline", weight: 2, category: "social" },
			{ template: "Can we get an ETA for the leadership sync?", weight: 2, category: "social" },
			{ template: "The board wants a demo next week. Is that doable?", weight: 2, category: "social" },
			{ template: "How would you explain this to a non-technical audience?", weight: 1, category: "social" },
			{ template: "Can you put the progress in a slide deck?", weight: 1, category: "social" },
			{ template: "What's the risk level? In traffic light colors please", weight: 2, category: "social" },
			{ template: "The CEO read a blog post about AI. We need to discuss", weight: 2, category: "social" },
			{ template: "Can we call the refactoring something sexier for the report?", weight: 2, category: "social" },
			{ template: "How many sprints until it's impressive?", weight: 1, category: "social" },
			{ template: "The other team shipped in half the time. What happened?", weight: 2, category: "social" },
			{ template: "I need a one-liner for the all-hands. Make it good", weight: 1, category: "social" },
			{ template: "Can we double the team to go twice as fast?", weight: 2, category: "social" },
			{ template: "What's 'technical debt' and why is it always urgent?", weight: 2, category: "social" },
			{ template: "The budget review is Thursday. Give me good news", weight: 1, category: "social" },
			{ template: "Is there a way to measure developer happiness? Asking for HR", weight: 1, category: "social" },
			{ template: "I told the client it ships next month. We good?", weight: 2, category: "social" },
			{ template: "Want to shadow the engineering standup? It's educational", weight: 1, category: "social" },
			{ template: "Can you rank these 5 priorities? They're all P0 apparently", weight: 2, category: "social" },
			{ template: "The client loved the prototype. Now they want ten more features", weight: 2, category: "social" },
			{ template: "I genuinely find your architecture diagrams fascinating", weight: 1, category: "social" },
			{ template: "How do I explain a database index to the board? Asking sincerely", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Still the same timeline as yesterday", weight: 2, category: "social" },
			{ template: "The ETA is an estimate. The E literally stands for estimate", weight: 2, category: "social" },
			{ template: "Demo-ready and production-ready are very different things", weight: 2, category: "social" },
			{ template: "I'll try, but it involves explaining what a database is. Again", weight: 2, category: "social" },
			{ template: "Can I just show you the working code instead?", weight: 1, category: "social" },
			{ template: "It's yellow. It's always yellow. Everything is perpetually yellow", weight: 2, category: "social" },
			{ template: "Asking more often doesn't make it go faster. Just saying", weight: 1, category: "social" },
			{ template: "The CEO's blog post is from 2019. But sure, let's discuss", weight: 2, category: "social" },
			{ template: "Refactoring IS the sexy part. The code was held together with tape", weight: 1, category: "social" },
			{ template: "Adding people to a late project makes it later. That's a law", weight: 2, category: "social" },
			{ template: "Technical debt is why the site didn't crash yesterday. You're welcome", weight: 2, category: "social" },
			{ template: "The other team shipped fast. Their bug count is... classified", weight: 2, category: "social" },
			{ template: "One-liner: 'It works and nobody got paged.' You're welcome", weight: 1, category: "social" },
			{ template: "Next month? Which next month? There are many next months", weight: 2, category: "social" },
			{ template: "Developer happiness is inversely proportional to meeting count", weight: 1, category: "social" },
			{ template: "Good news: it compiles. Bad news: see me after the review", weight: 2, category: "social" },
			{ template: "Impressive is 3 sprints. Demo-able is 1. Pick wisely", weight: 1, category: "social" },
			{ template: "Shadow the standup? Sure. Bring snacks and low expectations", weight: 1, category: "social" },
			{ template: "All five are P0? Then none of them are P0. That's how math works", weight: 2, category: "social" },
			{ template: "Ten features from one prototype? That's scope explosion, not love", weight: 2, category: "social" },
			{ template: "Architecture diagrams? You'd love my whiteboard. It's terrifying", weight: 1, category: "social" },
			{ template: "Database index: it makes things fast. Board version: it saves money", weight: 2, category: "social" },
		],
	},
	// quality <-> product
	{
		domainA: "quality",
		domainB: "product",
		linesA: [
			{ template: "Found 12 bugs", weight: 2, category: "social" },
			{ template: "The happy path works. Everything else is chaos", weight: 2, category: "social" },
			{ template: "This requirement contradicts that other requirement", weight: 2, category: "social" },
			{ template: "Users will definitely try this. And it will definitely break", weight: 1, category: "social" },
			{ template: "I need clearer acceptance criteria. 'It should work' doesn't count", weight: 2, category: "social" },
			{ template: "Good news: I finished testing. Bad news: I finished testing", weight: 2, category: "social" },
			{ template: "The spec says 'seamless'. Reality says otherwise", weight: 1, category: "social" },
			{ template: "Users found a workaround for your workaround. Impressive", weight: 2, category: "social" },
			{ template: "Can we define 'done' before we call it done?", weight: 1, category: "social" },
			{ template: "The regression list is longer than the feature list", weight: 2, category: "social" },
			{ template: "Shipping now means patching tomorrow. Your call", weight: 1, category: "social" },
			{ template: "I tested the persona you described. She's very confused", weight: 2, category: "social" },
			{ template: "Edge case? This IS the case. It's not even edgy", weight: 2, category: "social" },
			{ template: "The error message says 'something went wrong'. Very helpful", weight: 1, category: "social" },
			{ template: "Three of your acceptance criteria conflict. Pick two", weight: 2, category: "social" },
			{ template: "Your MVP has more bugs than features. Just a heads up", weight: 2, category: "social" },
			{ template: "Want to review the test matrix together before launch?", weight: 1, category: "social" },
			{ template: "I tested the onboarding flow. Step 4 is a trap", weight: 2, category: "social" },
			{ template: "Your 'edge case' affects 30% of users. That's a whole edge", weight: 2, category: "social" },
			{ template: "I read the PRD. It assumes everything works. Bold move", weight: 1, category: "social" },
			{ template: "The accessibility audit has findings. Good findings. Actionable ones", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Can we call them features?", weight: 2, category: "social" },
			{ template: "How many of those are critical? Just the critical ones. Please", weight: 2, category: "social" },
			{ template: "Can we ship and fix later? Asking for the roadmap", weight: 2, category: "social" },
			{ template: "The deadline doesn't move but the scope can. Theoretically", weight: 1, category: "social" },
			{ template: "Nobody will use it that way. Probably. Hopefully", weight: 2, category: "social" },
			{ template: "Let's triage. What can we live with? Temporarily? Forever?", weight: 1, category: "social" },
			{ template: "Seamless is aspirational. We agreed on 'mostly smooth'", weight: 2, category: "social" },
			{ template: "The workaround is creative. Can we call it a feature?", weight: 2, category: "social" },
			{ template: "Done means shipped. We can iterate. That's agile. Right?", weight: 1, category: "social" },
			{ template: "Which bugs can users live with? Asking genuinely", weight: 1, category: "social" },
			{ template: "The persona is a stretch. Real users are more forgiving. Maybe", weight: 2, category: "social" },
			{ template: "Regression is a strong word. Let's say 'behavior change'", weight: 2, category: "social" },
			{ template: "We'll fix the error message in v2. Users love mystery", weight: 2, category: "social" },
			{ template: "Two out of three criteria is passing grade. In some schools", weight: 1, category: "social" },
			{ template: "The bug count is high but the vibes are immaculate", weight: 2, category: "social" },
			{ template: "Patching tomorrow is future-us's problem. Ship today", weight: 1, category: "social" },
			{ template: "Test matrix review? Love to. Bring coffee and hope", weight: 1, category: "social" },
			{ template: "Step 4 is by design. It builds character. In the user", weight: 2, category: "social" },
			{ template: "30% is a minority in some democracies. Ship it", weight: 2, category: "social" },
			{ template: "The PRD assumes success. That's called optimism. Try it", weight: 1, category: "social" },
			{ template: "Accessibility findings are great. Can we address them in v3?", weight: 2, category: "social" },
		],
	},
];
