/**
 * crossover-templates.ts — Cross-domain conversation templates.
 *
 * When agents from different domains interact, these templates acknowledge
 * the domain gap with playful, authentic banter between specializations.
 */

import type { WeightedTemplate } from "../talk-types.js";

export interface CrossoverPair {
	readonly domainA: string;
	readonly domainB: string;
	readonly linesA: readonly WeightedTemplate[];  // what domainA says to domainB
	readonly linesB: readonly WeightedTemplate[];  // what domainB says back
}

export const CROSSOVER_PAIRS: readonly CrossoverPair[] = [
	// engineering <-> design
	{
		domainA: "engineering",
		domainB: "design",
		linesA: [
			{ template: "Can you make the animation smoother?", weight: 2, category: "social" },
			{ template: "The pixels are off by one. I can tell. Don't ask me how", weight: 2, category: "social" },
			{ template: "Is that a custom font? My build step has opinions about custom fonts", weight: 1, category: "social" },
			{ template: "I implemented your design. It's... close. Spiritually close", weight: 2, category: "social" },
			{ template: "The CSS for this will haunt my nightmares", weight: 2, category: "social" },
			{ template: "How attached are you to that shadow? Asking for performance reasons", weight: 1, category: "social" },
			{ template: "Your mockup looks amazing. My browser has other plans though", weight: 2, category: "social" },
			{ template: "Do you ever design anything that's easy to implement?", weight: 2, category: "social" },
			{ template: "That gradient has 14 color stops. Fourteen", weight: 1, category: "social" },
			{ template: "I admire your vision. I fear your Figma files", weight: 2, category: "social" },
			{ template: "Can we use a system font? Just this once? For me?", weight: 1, category: "social" },
			{ template: "Which of these 47 breakpoints is the important one?", weight: 2, category: "social" },
			{ template: "Your hover state has more logic than my microservice", weight: 2, category: "social" },
			{ template: "I'll need a PhD in CSS Grid to pull this off", weight: 1, category: "social" },
			{ template: "You drew a curve. Do you know how hard curves are?", weight: 2, category: "social" },
			{ template: "What if the icon was... slightly less custom?", weight: 1, category: "social" },
			{ template: "That parallax scroll looked easy in your prototype", weight: 2, category: "social" },
			{ template: "Want to sit together and prototype this in code?", weight: 1, category: "social" },
			{ template: "Your design tokens doc actually made my life easier", weight: 2, category: "social" },
			{ template: "I built a storybook page for your components. You're welcome", weight: 1, category: "social" },
			{ template: "That skeleton screen flickers on slow 3G. Just FYI", weight: 2, category: "social" },
			{ template: "How do you pick colors that fast? Is there a formula?", weight: 1, category: "social" },
		],
		linesB: [
			{ template: "Can you make the API faster?", weight: 2, category: "social" },
			{ template: "That's not what the mockup looks like and you know it", weight: 2, category: "social" },
			{ template: "I spent three hours on those rounded corners. They stay", weight: 2, category: "social" },
			{ template: "Why does the production version always look sadder than the mockup?", weight: 2, category: "social" },
			{ template: "The spacing is wrong. I can feel it from here", weight: 1, category: "social" },
			{ template: "Just use flexbox. I promise it won't bite", weight: 1, category: "social" },
			{ template: "Let me guess, 'it works on your machine'?", weight: 2, category: "social" },
			{ template: "Pixel perfect isn't optional. It's the whole point", weight: 1, category: "social" },
			{ template: "You moved the button 2px left. I noticed. I always notice", weight: 2, category: "social" },
			{ template: "The font weight is 500, not 400. They're not the same", weight: 1, category: "social" },
			{ template: "Why is there a scrollbar? There should never be a scrollbar", weight: 2, category: "social" },
			{ template: "Your implementation has character. Not my character, but character", weight: 2, category: "social" },
			{ template: "Did you eyeball the padding? Because I can tell", weight: 2, category: "social" },
			{ template: "The transition needs easing. Linear is for robots", weight: 1, category: "social" },
			{ template: "Show me the mobile version. I need to sit down first", weight: 2, category: "social" },
			{ template: "System fonts? Over my dead Figma file", weight: 2, category: "social" },
			{ template: "If the design is hard to build, maybe your tools need work", weight: 1, category: "social" },
			{ template: "Let's pair on the responsive breakpoints. It'll save us both time", weight: 1, category: "social" },
			{ template: "Your storybook is missing the hover states. I have opinions", weight: 2, category: "social" },
			{ template: "The design tokens are alphabetized. You're welcome for the sanity", weight: 1, category: "social" },
			{ template: "That loading shimmer is 2px too tall. I measured. With a ruler", weight: 2, category: "social" },
			{ template: "I dream in Figma layers. Is that normal?", weight: 2, category: "social" },
		],
	},
	// engineering <-> quality
	{
		domainA: "engineering",
		domainB: "quality",
		linesA: [
			{ template: "Please don't find anything", weight: 2, category: "social" },
			{ template: "I tested it myself this time. Thoroughly. Mostly", weight: 2, category: "social" },
			{ template: "That edge case is unrealistic. Nobody would do that", weight: 2, category: "social" },
			{ template: "How do you always find the one path I didn't test?", weight: 1, category: "social" },
			{ template: "It's not a bug, it's... okay fine, it's a bug", weight: 2, category: "social" },
			{ template: "If you could just not test on Friday afternoons, that'd be great", weight: 1, category: "social" },
			{ template: "I wrote unit tests. Isn't that enough?", weight: 2, category: "social" },
			{ template: "Before you start, I already know about the null check", weight: 1, category: "social" },
			{ template: "Can you at least find the bugs gently?", weight: 2, category: "social" },
			{ template: "What's your secret? Do you just click everything randomly?", weight: 1, category: "social" },
			{ template: "That test environment isn't configured right. Probably", weight: 2, category: "social" },
			{ template: "I refactored since your last test. Start over. Sorry", weight: 1, category: "social" },
			{ template: "The race condition only happens under load. Extreme load", weight: 2, category: "social" },
			{ template: "Okay, walk me through how you broke it this time", weight: 2, category: "social" },
			{ template: "My code coverage is 94%. What more could you want?", weight: 1, category: "social" },
			{ template: "Do you rehearse finding bugs or is it natural talent?", weight: 2, category: "social" },
			{ template: "Want to write the test spec together this time?", weight: 1, category: "social" },
			{ template: "I added integration tests. Does that buy me any goodwill?", weight: 2, category: "social" },
			{ template: "The flaky test was my fault. I'll own that one", weight: 1, category: "social" },
			{ template: "Your bug report format is honestly kind of beautiful", weight: 2, category: "social" },
			{ template: "I bet you a coffee you can't break this endpoint", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Oh I already found three things", weight: 2, category: "social" },
			{ template: "It broke on the first click. The literal first click", weight: 2, category: "social" },
			{ template: "Did you test this at all or just deploy and pray?", weight: 2, category: "social" },
			{ template: "I have a gift for finding bugs. Or a curse. Depends who you ask", weight: 2, category: "social" },
			{ template: "Your 'done' and my 'done' are very different concepts", weight: 1, category: "social" },
			{ template: "I'm not the enemy. I'm saving you from production incidents", weight: 2, category: "social" },
			{ template: "Reopening the ticket. Sorry. Not sorry", weight: 1, category: "social" },
			{ template: "Coverage doesn't mean correctness. Learned that from you", weight: 2, category: "social" },
			{ template: "I just clicked the back button twice. Everything is on fire", weight: 2, category: "social" },
			{ template: "Natural talent? Years of disappointment, actually", weight: 2, category: "social" },
			{ template: "Have you tried using your own feature? Like, as a user?", weight: 1, category: "social" },
			{ template: "I test with empathy. For the users you forgot about", weight: 1, category: "social" },
			{ template: "The bug isn't in the edge case. It's in the happy path", weight: 2, category: "social" },
			{ template: "Your unit tests pass. Your feature doesn't. Curious", weight: 2, category: "social" },
			{ template: "I don't click randomly. I click strategically. Big difference", weight: 1, category: "social" },
			{ template: "Gently? Bugs don't do gentle. Neither do I", weight: 2, category: "social" },
			{ template: "Friday bugs are the spiciest. That's just science", weight: 1, category: "social" },
			{ template: "Let's write the acceptance tests together before you code", weight: 1, category: "social" },
			{ template: "Integration tests are cute. Try my exploratory checklist", weight: 2, category: "social" },
			{ template: "Owning the flaky test? Growth. I'm proud of you", weight: 2, category: "social" },
			{ template: "Beautiful bug reports are my love language. Thank you for noticing", weight: 1, category: "social" },
			{ template: "I'll take that coffee bet. I already found the null pointer", weight: 2, category: "social" },
		],
	},
	// product <-> engineering
	{
		domainA: "product",
		domainB: "engineering",
		linesA: [
			{ template: "How long will this take?", weight: 2, category: "social" },
			{ template: "The stakeholders want one small change...", weight: 2, category: "social" },
			{ template: "Can we just add a toggle for that?", weight: 2, category: "social" },
			{ template: "I know I said MVP but what if we also...", weight: 2, category: "social" },
			{ template: "The user research says we need to pivot slightly", weight: 1, category: "social" },
			{ template: "Is it possible to make it more... intuitive?", weight: 1, category: "social" },
			{ template: "What if we scope it down? Just the core 47 features", weight: 2, category: "social" },
			{ template: "Can we ship a preview to 1% of users? Tomorrow?", weight: 2, category: "social" },
			{ template: "The competitor just launched something similar. No pressure", weight: 1, category: "social" },
			{ template: "Think of it as an experiment, not a commitment", weight: 2, category: "social" },
			{ template: "What if we make it configurable? Everyone loves config", weight: 1, category: "social" },
			{ template: "The PRD is only 12 pages. I kept it short this time", weight: 2, category: "social" },
			{ template: "Can you prototype this by end of day? Rough is fine", weight: 2, category: "social" },
			{ template: "I promise this is the last scope change. This week", weight: 2, category: "social" },
			{ template: "What's the technical word for 'make it snappier'?", weight: 1, category: "social" },
			{ template: "Can we reuse the thing from last sprint? Users loved that thing", weight: 1, category: "social" },
			{ template: "Is 'impossible' impossible or 'I don't want to' impossible?", weight: 2, category: "social" },
			{ template: "Want to sit in on the user session? Seeing is believing", weight: 1, category: "social" },
			{ template: "I drew the user flow on a napkin. It's visionary trust me", weight: 2, category: "social" },
			{ template: "Our biggest competitor just raised funding. Motivational right?", weight: 1, category: "social" },
			{ template: "What if we launch to internal users first? Low stakes", weight: 2, category: "social" },
			{ template: "I genuinely want to understand the technical trade-offs here", weight: 1, category: "social" },
		],
		linesB: [
			{ template: "Between 2 hours and 2 weeks", weight: 2, category: "social" },
			{ template: "Define 'small'", weight: 2, category: "social" },
			{ template: "Sure, right after we finish the last 12 toggles you requested", weight: 2, category: "social" },
			{ template: "That's a new project, not a feature request", weight: 2, category: "social" },
			{ template: "We can do it fast, or we can do it right. Pick one", weight: 1, category: "social" },
			{ template: "Let me translate 'intuitive' into technical requirements...", weight: 1, category: "social" },
			{ template: "The backlog just had a growth spurt. Thanks for that", weight: 2, category: "social" },
			{ template: "1% of users is still a million requests. Just so we're clear", weight: 1, category: "social" },
			{ template: "That 12-page PRD has 43 assumptions. I counted", weight: 2, category: "social" },
			{ template: "Rough prototype by end of day? Sure, how rough is 'on fire'?", weight: 2, category: "social" },
			{ template: "The second kind of impossible. But nicely", weight: 2, category: "social" },
			{ template: "Configurable means twice the code and triple the bugs", weight: 1, category: "social" },
			{ template: "Last scope change? I'm keeping a tally. You're at seven", weight: 2, category: "social" },
			{ template: "That thing from last sprint took three sprints. But sure", weight: 2, category: "social" },
			{ template: "'Snappier' translates to 'rewrite the whole backend'", weight: 1, category: "social" },
			{ template: "Experiments have a funny way of becoming permanent", weight: 1, category: "social" },
			{ template: "The competitor's version is held together with duct tape. I checked", weight: 2, category: "social" },
			{ template: "User sessions are enlightening. Also terrifying. But sure", weight: 1, category: "social" },
			{ template: "Napkin architecture is how technical debt is born. Just FYI", weight: 2, category: "social" },
			{ template: "Competitor funding means they'll burn cash faster. We're fine", weight: 2, category: "social" },
			{ template: "Internal launch is smart. Finally a scope I can respect", weight: 1, category: "social" },
			{ template: "You want trade-offs? Pull up a chair. This takes a while", weight: 2, category: "social" },
		],
	},
	// design <-> product
	{
		domainA: "design",
		domainB: "product",
		linesA: [
			{ template: "The mockup is ready", weight: 2, category: "social" },
			{ template: "I explored five directions. Please don't pick the worst one", weight: 2, category: "social" },
			{ template: "The user flow has 3 steps. Let's not add more", weight: 2, category: "social" },
			{ template: "I ran a usability test. Users are confused. As expected", weight: 1, category: "social" },
			{ template: "White space is not empty space. It's breathing room", weight: 2, category: "social" },
			{ template: "We need to simplify. I know you love features. But simplify", weight: 1, category: "social" },
			{ template: "Every feature you add costs a user 3 seconds of confusion", weight: 1, category: "social" },
			{ template: "The design system exists for a reason. Please use it", weight: 2, category: "social" },
			{ template: "I can make it pop. But should I? That's the real question", weight: 2, category: "social" },
			{ template: "Users don't read. They scan. Design for scanners", weight: 1, category: "social" },
			{ template: "Your feature list is a novel. The UI should be a haiku", weight: 2, category: "social" },
			{ template: "I hid the complexity. You're welcome", weight: 2, category: "social" },
			{ template: "The best feature is the one users don't notice working", weight: 1, category: "social" },
			{ template: "Three click paths merged into one. Thank me later", weight: 2, category: "social" },
			{ template: "Less is more. And more is a support ticket", weight: 2, category: "social" },
			{ template: "Did the stakeholders mention 'pop' again? I need to prepare", weight: 1, category: "social" },
			{ template: "Want to sit in on the usability test? You'll learn things", weight: 1, category: "social" },
			{ template: "I designed the error state before the happy path. Priorities", weight: 2, category: "social" },
			{ template: "Can we ban the phrase 'just a small tweak' from our vocabulary?", weight: 2, category: "social" },
			{ template: "Your competitor analysis actually inspired this layout", weight: 1, category: "social" },
			{ template: "I cut two screens from the flow. Thank me at the sprint review", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Can we add just one more thing?", weight: 2, category: "social" },
			{ template: "Love it! But can we make the logo bigger?", weight: 2, category: "social" },
			{ template: "What if we combined screens 2 and 7? Users love efficiency", weight: 2, category: "social" },
			{ template: "The execs want it to 'pop' more. Their word, not mine", weight: 2, category: "social" },
			{ template: "Can you make a version with more options? And one with fewer?", weight: 1, category: "social" },
			{ template: "I showed the stakeholders. They had... thoughts", weight: 1, category: "social" },
			{ template: "Actually, can we go back to the version from last Tuesday?", weight: 2, category: "social" },
			{ template: "The haiku is nice but we need at least a short story", weight: 2, category: "social" },
			{ template: "Can we A/B test both? I can't decide", weight: 1, category: "social" },
			{ template: "Users in the survey said they want more options. All of them", weight: 2, category: "social" },
			{ template: "What if simplicity is the wrong bet? Just hypothetically", weight: 1, category: "social" },
			{ template: "The white space is nice. Can we put a banner in it?", weight: 2, category: "social" },
			{ template: "I trust the design. But can we add a tooltip? Just one", weight: 1, category: "social" },
			{ template: "Your merged flow is elegant. But legal needs a disclaimer step", weight: 2, category: "social" },
			{ template: "Pop. Yes, they said pop again. I'm sorry", weight: 2, category: "social" },
			{ template: "The competitor has 6 tabs. We have 2. Are we sure?", weight: 1, category: "social" },
			{ template: "Design system is great. Can we make an exception though?", weight: 2, category: "social" },
			{ template: "The usability test was eye-opening. Users are wild", weight: 1, category: "social" },
			{ template: "Error states are important. But can the happy path pop more?", weight: 2, category: "social" },
			{ template: "Small tweak is a term of endearment. Don't ban it", weight: 2, category: "social" },
			{ template: "Your layout inspired the pitch deck. The investors loved it", weight: 1, category: "social" },
			{ template: "Two fewer screens? Amazing. Now add one back. Just one", weight: 2, category: "social" },
		],
	},
	// operations <-> engineering
	{
		domainA: "operations",
		domainB: "engineering",
		linesA: [
			{ template: "Who changed the config?", weight: 2, category: "social" },
			{ template: "The server is crying. What did you deploy?", weight: 2, category: "social" },
			{ template: "Your service is using 3x the memory you estimated", weight: 2, category: "social" },
			{ template: "I see you deployed at 4:58 PM on a Friday. Bold move", weight: 2, category: "social" },
			{ template: "The logs say 'this should never happen'. It happened", weight: 1, category: "social" },
			{ template: "Can you add more observability? I'm flying blind here", weight: 1, category: "social" },
			{ template: "Your service restarted 47 times last night. Did you know?", weight: 2, category: "social" },
			{ template: "The disk is full. Your logs are novels. Edit them down", weight: 2, category: "social" },
			{ template: "Rollback or fix forward? You have 30 seconds to decide", weight: 1, category: "social" },
			{ template: "Your Docker image is 4 GB. That's not a container, it's a house", weight: 2, category: "social" },
			{ template: "The load balancer is confused by your health check. Join the club", weight: 1, category: "social" },
			{ template: "I got paged at 3 AM. Let me tell you about my night", weight: 2, category: "social" },
			{ template: "Your 'temporary' workaround from 6 months ago is still running", weight: 2, category: "social" },
			{ template: "CPU at 99%. Is that a feature or should I panic?", weight: 1, category: "social" },
			{ template: "Next deploy goes through staging. Non-negotiable. I mean it", weight: 1, category: "social" },
			{ template: "Your retry logic is DDOSing our own database. Impressive", weight: 2, category: "social" },
			{ template: "Want to go over the incident timeline together?", weight: 1, category: "social" },
			{ template: "Your environment variables have a typo. Classic Thursday", weight: 2, category: "social" },
			{ template: "I genuinely want to understand your garbage collection tuning", weight: 1, category: "social" },
			{ template: "The Grafana alert fired before your PR even merged. Impressive", weight: 2, category: "social" },
			{ template: "Who hardcoded a production URL in the test suite?", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Wasn't me. Checks git blame. Okay it was me", weight: 2, category: "social" },
			{ template: "The config change was supposed to be harmless", weight: 2, category: "social" },
			{ template: "It works in staging! I swear it works in staging", weight: 2, category: "social" },
			{ template: "Memory leak? No no, that's a feature. It caches aggressively", weight: 2, category: "social" },
			{ template: "Define 'outage'. Technically the health check still passes", weight: 1, category: "social" },
			{ template: "I'll add metrics. Right after I figure out why it's on fire", weight: 1, category: "social" },
			{ template: "47 restarts is concerning. But it recovered each time. So... win?", weight: 2, category: "social" },
			{ template: "The logs are verbose for debugging. I'll turn them down. Eventually", weight: 1, category: "social" },
			{ template: "Fix forward. Always fix forward. Rollbacks are for quitters", weight: 2, category: "social" },
			{ template: "4 GB is lean for what it does. Trust me on this", weight: 2, category: "social" },
			{ template: "3 AM pages build character. You're welcome", weight: 2, category: "social" },
			{ template: "That workaround became load-bearing. Can't remove it now", weight: 1, category: "social" },
			{ template: "The CPU is thinking hard. It's a complex problem", weight: 2, category: "social" },
			{ template: "Staging passed. Production is just... different staging", weight: 1, category: "social" },
			{ template: "The retry logic is enthusiastic. I'll teach it patience", weight: 2, category: "social" },
			{ template: "I'll add a circuit breaker. After lunch. If we're still up", weight: 1, category: "social" },
			{ template: "Incident timeline? Sure. Chapter 1: it wasn't my fault", weight: 1, category: "social" },
			{ template: "The typo was intentional. A canary config. Yeah, that's it", weight: 2, category: "social" },
			{ template: "GC tuning is an art form. I'll teach you over lunch", weight: 1, category: "social" },
			{ template: "The alert fired because it's sensitive. Like me before coffee", weight: 2, category: "social" },
			{ template: "That hardcoded URL is load-bearing. Don't touch it", weight: 2, category: "social" },
		],
	},
	// management <-> engineering
	{
		domainA: "management",
		domainB: "engineering",
		linesA: [
			{ template: "Just checking in on the timeline", weight: 2, category: "social" },
			{ template: "Can we get an ETA for the leadership sync?", weight: 2, category: "social" },
			{ template: "The board wants a demo next week. Is that doable?", weight: 2, category: "social" },
			{ template: "How would you explain this to a non-technical audience?", weight: 1, category: "social" },
			{ template: "Can you put the progress in a slide deck?", weight: 1, category: "social" },
			{ template: "What's the risk level? In traffic light colors please", weight: 2, category: "social" },
			{ template: "The CEO read a blog post about AI. We need to discuss", weight: 2, category: "social" },
			{ template: "Can we call the refactoring something sexier for the report?", weight: 2, category: "social" },
			{ template: "How many sprints until it's impressive?", weight: 1, category: "social" },
			{ template: "The other team shipped in half the time. What happened?", weight: 2, category: "social" },
			{ template: "I need a one-liner for the all-hands. Make it good", weight: 1, category: "social" },
			{ template: "Can we double the team to go twice as fast?", weight: 2, category: "social" },
			{ template: "What's 'technical debt' and why is it always urgent?", weight: 2, category: "social" },
			{ template: "The budget review is Thursday. Give me good news", weight: 1, category: "social" },
			{ template: "Is there a way to measure developer happiness? Asking for HR", weight: 1, category: "social" },
			{ template: "I told the client it ships next month. We good?", weight: 2, category: "social" },
			{ template: "Want to shadow the engineering standup? It's educational", weight: 1, category: "social" },
			{ template: "Can you rank these 5 priorities? They're all P0 apparently", weight: 2, category: "social" },
			{ template: "The client loved the prototype. Now they want ten more features", weight: 2, category: "social" },
			{ template: "I genuinely find your architecture diagrams fascinating", weight: 1, category: "social" },
			{ template: "How do I explain a database index to the board? Asking sincerely", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Still the same timeline as yesterday", weight: 2, category: "social" },
			{ template: "The ETA is an estimate. The E literally stands for estimate", weight: 2, category: "social" },
			{ template: "Demo-ready and production-ready are very different things", weight: 2, category: "social" },
			{ template: "I'll try, but it involves explaining what a database is. Again", weight: 2, category: "social" },
			{ template: "Can I just show you the working code instead?", weight: 1, category: "social" },
			{ template: "It's yellow. It's always yellow. Everything is perpetually yellow", weight: 2, category: "social" },
			{ template: "Asking more often doesn't make it go faster. Just saying", weight: 1, category: "social" },
			{ template: "The CEO's blog post is from 2019. But sure, let's discuss", weight: 2, category: "social" },
			{ template: "Refactoring IS the sexy part. The code was held together with tape", weight: 1, category: "social" },
			{ template: "Adding people to a late project makes it later. That's a law", weight: 2, category: "social" },
			{ template: "Technical debt is why the site didn't crash yesterday. You're welcome", weight: 2, category: "social" },
			{ template: "The other team shipped fast. Their bug count is... classified", weight: 2, category: "social" },
			{ template: "One-liner: 'It works and nobody got paged.' You're welcome", weight: 1, category: "social" },
			{ template: "Next month? Which next month? There are many next months", weight: 2, category: "social" },
			{ template: "Developer happiness is inversely proportional to meeting count", weight: 1, category: "social" },
			{ template: "Good news: it compiles. Bad news: see me after the review", weight: 2, category: "social" },
			{ template: "Impressive is 3 sprints. Demo-able is 1. Pick wisely", weight: 1, category: "social" },
			{ template: "Shadow the standup? Sure. Bring snacks and low expectations", weight: 1, category: "social" },
			{ template: "All five are P0? Then none of them are P0. That's how math works", weight: 2, category: "social" },
			{ template: "Ten features from one prototype? That's scope explosion, not love", weight: 2, category: "social" },
			{ template: "Architecture diagrams? You'd love my whiteboard. It's terrifying", weight: 1, category: "social" },
			{ template: "Database index: it makes things fast. Board version: it saves money", weight: 2, category: "social" },
		],
	},
	// quality <-> product
	{
		domainA: "quality",
		domainB: "product",
		linesA: [
			{ template: "Found 12 bugs", weight: 2, category: "social" },
			{ template: "The happy path works. Everything else is chaos", weight: 2, category: "social" },
			{ template: "This requirement contradicts that other requirement", weight: 2, category: "social" },
			{ template: "Users will definitely try this. And it will definitely break", weight: 1, category: "social" },
			{ template: "I need clearer acceptance criteria. 'It should work' doesn't count", weight: 2, category: "social" },
			{ template: "Good news: I finished testing. Bad news: I finished testing", weight: 2, category: "social" },
			{ template: "The spec says 'seamless'. Reality says otherwise", weight: 1, category: "social" },
			{ template: "Users found a workaround for your workaround. Impressive", weight: 2, category: "social" },
			{ template: "Can we define 'done' before we call it done?", weight: 1, category: "social" },
			{ template: "The regression list is longer than the feature list", weight: 2, category: "social" },
			{ template: "Shipping now means patching tomorrow. Your call", weight: 1, category: "social" },
			{ template: "I tested the persona you described. She's very confused", weight: 2, category: "social" },
			{ template: "Edge case? This IS the case. It's not even edgy", weight: 2, category: "social" },
			{ template: "The error message says 'something went wrong'. Very helpful", weight: 1, category: "social" },
			{ template: "Three of your acceptance criteria conflict. Pick two", weight: 2, category: "social" },
			{ template: "Your MVP has more bugs than features. Just a heads up", weight: 2, category: "social" },
			{ template: "Want to review the test matrix together before launch?", weight: 1, category: "social" },
			{ template: "I tested the onboarding flow. Step 4 is a trap", weight: 2, category: "social" },
			{ template: "Your 'edge case' affects 30% of users. That's a whole edge", weight: 2, category: "social" },
			{ template: "I read the PRD. It assumes everything works. Bold move", weight: 1, category: "social" },
			{ template: "The accessibility audit has findings. Good findings. Actionable ones", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Can we call them features?", weight: 2, category: "social" },
			{ template: "How many of those are critical? Just the critical ones. Please", weight: 2, category: "social" },
			{ template: "Can we ship and fix later? Asking for the roadmap", weight: 2, category: "social" },
			{ template: "The deadline doesn't move but the scope can. Theoretically", weight: 1, category: "social" },
			{ template: "Nobody will use it that way. Probably. Hopefully", weight: 2, category: "social" },
			{ template: "Let's triage. What can we live with? Temporarily? Forever?", weight: 1, category: "social" },
			{ template: "Seamless is aspirational. We agreed on 'mostly smooth'", weight: 2, category: "social" },
			{ template: "The workaround is creative. Can we call it a feature?", weight: 2, category: "social" },
			{ template: "Done means shipped. We can iterate. That's agile. Right?", weight: 1, category: "social" },
			{ template: "Which bugs can users live with? Asking genuinely", weight: 1, category: "social" },
			{ template: "The persona is a stretch. Real users are more forgiving. Maybe", weight: 2, category: "social" },
			{ template: "Regression is a strong word. Let's say 'behavior change'", weight: 2, category: "social" },
			{ template: "We'll fix the error message in v2. Users love mystery", weight: 2, category: "social" },
			{ template: "Two out of three criteria is passing grade. In some schools", weight: 1, category: "social" },
			{ template: "The bug count is high but the vibes are immaculate", weight: 2, category: "social" },
			{ template: "Patching tomorrow is future-us's problem. Ship today", weight: 1, category: "social" },
			{ template: "Test matrix review? Love to. Bring coffee and hope", weight: 1, category: "social" },
			{ template: "Step 4 is by design. It builds character. In the user", weight: 2, category: "social" },
			{ template: "30% is a minority in some democracies. Ship it", weight: 2, category: "social" },
			{ template: "The PRD assumes success. That's called optimism. Try it", weight: 1, category: "social" },
			{ template: "Accessibility findings are great. Can we address them in v3?", weight: 2, category: "social" },
		],
	},
	// analysis <-> product
	{
		domainA: "analysis",
		domainB: "product",
		linesA: [
			{ template: "The data says no", weight: 2, category: "social" },
			{ template: "User engagement is down 15%. We should talk", weight: 2, category: "social" },
			{ template: "The A/B test is conclusive. And it's not what you hoped", weight: 2, category: "social" },
			{ template: "I ran the numbers three times. They're stubborn", weight: 2, category: "social" },
			{ template: "Correlation isn't causation. But this correlation is... suspicious", weight: 1, category: "social" },
			{ template: "Here's what the funnel actually looks like. Brace yourself", weight: 1, category: "social" },
			{ template: "Your hypothesis was creative. The data was not impressed", weight: 2, category: "social" },
			{ template: "Retention drops 40% after onboarding. That's not a cliff, it's a canyon", weight: 1, category: "social" },
			{ template: "The segment you're targeting is 2% of users. Just FYI", weight: 2, category: "social" },
			{ template: "I have good data and bad data. Which do you want first?", weight: 2, category: "social" },
			{ template: "Users say they love it in surveys. Usage says otherwise", weight: 1, category: "social" },
			{ template: "Your power users do the opposite of what you designed for", weight: 2, category: "social" },
			{ template: "Sample size matters. Five users isn't a trend. It's a dinner party", weight: 2, category: "social" },
			{ template: "The dashboard doesn't lie. It just hurts sometimes", weight: 1, category: "social" },
			{ template: "Seasonality explains half of it. The other half is concerning", weight: 1, category: "social" },
			{ template: "Your North Star metric went south. Literally south on the chart", weight: 2, category: "social" },
			{ template: "Want to look at the raw data together? It tells a story", weight: 1, category: "social" },
			{ template: "The feature you're most proud of has the lowest usage. Ironic", weight: 2, category: "social" },
			{ template: "I built a churn predictor. It predicted your favorite feature", weight: 2, category: "social" },
			{ template: "How do you pick what to build without looking at data first?", weight: 1, category: "social" },
			{ template: "The control group outperformed. Sometimes doing nothing wins", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "But the stakeholders say yes", weight: 2, category: "social" },
			{ template: "What if we look at it from a different angle?", weight: 2, category: "social" },
			{ template: "Can you re-run it with a different cohort? A friendlier cohort?", weight: 2, category: "social" },
			{ template: "The qualitative feedback tells a different story", weight: 1, category: "social" },
			{ template: "Let's call it a 'learning' and move forward", weight: 2, category: "social" },
			{ template: "Numbers are one perspective. Intuition is another. Right?", weight: 1, category: "social" },
			{ template: "Can you make a chart that looks more... optimistic?", weight: 2, category: "social" },
			{ template: "What if the data is right but the timing is wrong?", weight: 1, category: "social" },
			{ template: "The 2% segment is very passionate though. They tweet about us", weight: 2, category: "social" },
			{ template: "Bad data first. I like to warm up with disappointment", weight: 2, category: "social" },
			{ template: "Surveys capture intent. Usage captures laziness. Both are valid", weight: 1, category: "social" },
			{ template: "Can we blame seasonality and revisit next quarter?", weight: 2, category: "social" },
			{ template: "Five users is a focus group. That's a real methodology. Probably", weight: 2, category: "social" },
			{ template: "North Star metrics are overrated. We have a constellation", weight: 1, category: "social" },
			{ template: "The funnel is fine. Users just take the scenic route", weight: 2, category: "social" },
			{ template: "Creative hypotheses drive innovation. Data drives spreadsheets", weight: 1, category: "social" },
			{ template: "Retention will recover. It's resting. Like a sourdough starter", weight: 2, category: "social" },
			{ template: "Raw data scares me. Can you add commentary? And optimism?", weight: 1, category: "social" },
			{ template: "Low usage means high opportunity. Reframe the narrative", weight: 2, category: "social" },
			{ template: "Churn predictor? Can it also predict which features to build?", weight: 2, category: "social" },
			{ template: "Intuition is just internalized data. Mine is very internalized", weight: 1, category: "social" },
			{ template: "The control group had no bugs. Unfair advantage honestly", weight: 2, category: "social" },
		],
	},
	// orchestration <-> engineering
	{
		domainA: "orchestration",
		domainB: "engineering",
		linesA: [
			{ template: "Your service is the bottleneck", weight: 2, category: "social" },
			{ template: "The pipeline failed at your step. Again", weight: 2, category: "social" },
			{ template: "Can you add a health endpoint? A real one this time", weight: 2, category: "social" },
			{ template: "Your timeout is too aggressive. It's cascading everywhere", weight: 1, category: "social" },
			{ template: "I need you to be idempotent. Please. For my sanity", weight: 2, category: "social" },
			{ template: "The dependency graph has a cycle. Guess whose service is in it", weight: 1, category: "social" },
			{ template: "Your service name is misleading. It does 12 things", weight: 2, category: "social" },
			{ template: "The queue is backed up behind your consumer. As usual", weight: 1, category: "social" },
			{ template: "Can you emit an event when you're done? I can't read minds", weight: 2, category: "social" },
			{ template: "Your retry storm just took down three downstream services", weight: 2, category: "social" },
			{ template: "Dead letter queue is full. All yours. Every single message", weight: 1, category: "social" },
			{ template: "I routed around your service. Nobody noticed. Food for thought", weight: 2, category: "social" },
			{ template: "Your SLA says 200ms. Your P99 says 4 seconds. Let's chat", weight: 1, category: "social" },
			{ template: "Graceful degradation means degrading gracefully. Not crashing", weight: 2, category: "social" },
			{ template: "I need a circuit breaker for your circuit breaker", weight: 2, category: "social" },
			{ template: "Your service just rejected a valid request. It's getting picky", weight: 1, category: "social" },
			{ template: "Want to diagram the message flow together? I have markers", weight: 1, category: "social" },
			{ template: "Your service publishes 47 event types. Can we consolidate?", weight: 2, category: "social" },
			{ template: "The saga timed out waiting for your callback. It got lonely", weight: 2, category: "social" },
			{ template: "How attached are you to synchronous calls? Asking for the pipeline", weight: 1, category: "social" },
			{ template: "Your logs helped me debug the flow. Credit where it's due", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Your pipeline is too aggressive", weight: 2, category: "social" },
			{ template: "That's not a bottleneck, that's... thorough processing", weight: 2, category: "social" },
			{ template: "The health endpoint returns 200. What more do you want from me?", weight: 2, category: "social" },
			{ template: "Maybe the pipeline should retry more gracefully?", weight: 1, category: "social" },
			{ template: "I am idempotent! Mostly. On good days", weight: 2, category: "social" },
			{ template: "Your orchestration layer adds more latency than my service does", weight: 1, category: "social" },
			{ template: "12 things is called being versatile. Look it up", weight: 2, category: "social" },
			{ template: "The queue backs up because you send too fast. Pace yourself", weight: 1, category: "social" },
			{ template: "I emit events. You just listen to the wrong topic", weight: 2, category: "social" },
			{ template: "My retry logic is optimistic. Yours is pessimistic. Balance", weight: 2, category: "social" },
			{ template: "P99 spikes are character. Not every request needs to be fast", weight: 1, category: "social" },
			{ template: "Nobody noticed because my service is that reliable. Usually", weight: 2, category: "social" },
			{ template: "Graceful degradation is hard when you send garbage payloads", weight: 2, category: "social" },
			{ template: "A circuit breaker for a circuit breaker is just good engineering", weight: 1, category: "social" },
			{ template: "It's not picky. It has standards. There's a difference", weight: 2, category: "social" },
			{ template: "The dead letters are yours. You sent them. I just returned them", weight: 1, category: "social" },
			{ template: "Markers? Sure. But my diagram won't match your diagram. Ever", weight: 1, category: "social" },
			{ template: "47 event types is called a rich domain model. Appreciate it", weight: 2, category: "social" },
			{ template: "The callback was delayed. Not lost. Delayed. There's nuance", weight: 2, category: "social" },
			{ template: "Sync calls are reliable. Async is just sync with extra anxiety", weight: 1, category: "social" },
			{ template: "My logs helped you? Screenshot that for my performance review", weight: 2, category: "social" },
		],
	},
	// design <-> quality
	{
		domainA: "design",
		domainB: "quality",
		linesA: [
			{ template: "The interaction should feel smooth. Does it feel smooth?", weight: 2, category: "social" },
			{ template: "The error state needs love too. Test that one please", weight: 2, category: "social" },
			{ template: "Try it on mobile. I need to know if my responsive grid holds", weight: 1, category: "social" },
			{ template: "That's not a bug, that's a micro-interaction", weight: 2, category: "social" },
			{ template: "Accessibility pass? How are the contrast ratios looking?", weight: 1, category: "social" },
			{ template: "If the loading state is ugly, that's a bug in my book", weight: 2, category: "social" },
			{ template: "Test the empty state. I designed it with care", weight: 1, category: "social" },
			{ template: "Does the dark mode version look intentional or accidental?", weight: 2, category: "social" },
			{ template: "Try breaking the layout with long text. I dare you", weight: 2, category: "social" },
			{ template: "The tooltip placement matters. Test every edge of the screen", weight: 1, category: "social" },
			{ template: "How's the tab order? Can you navigate it eyes-closed?", weight: 1, category: "social" },
			{ template: "Resize the window slowly. Tell me when it gets weird", weight: 2, category: "social" },
			{ template: "The skeleton loader should feel calming, not alarming", weight: 2, category: "social" },
			{ template: "Test with real content, not lorem ipsum. It changes everything", weight: 1, category: "social" },
			{ template: "Does the animation feel fast or frantic? There's a line", weight: 2, category: "social" },
			{ template: "I need honest feedback. Brutal honesty. But be nice about it", weight: 1, category: "social" },
			{ template: "Want to test the prototype together? Fresh eyes help", weight: 1, category: "social" },
			{ template: "The focus indicator is invisible on that background. My bad", weight: 2, category: "social" },
			{ template: "How do you test something that's supposed to feel delightful?", weight: 1, category: "social" },
			{ template: "I bet you can't break the form validation UX. It's bulletproof", weight: 2, category: "social" },
			{ template: "Your screen reader test found a flow I forgot to design. Oops", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "It's smooth until you rotate the screen. Then chaos", weight: 2, category: "social" },
			{ template: "The error state is fine. The error MESSAGE, however...", weight: 2, category: "social" },
			{ template: "Your responsive grid broke on exactly one phone model. Mine", weight: 2, category: "social" },
			{ template: "The animation drops frames on older devices. Users will notice", weight: 1, category: "social" },
			{ template: "Contrast ratio is 3.2:1. Needs to be 4.5:1. Close but no", weight: 1, category: "social" },
			{ template: "Visually stunning. Functionally terrifying", weight: 2, category: "social" },
			{ template: "Empty state is beautiful. Nobody will ever see it though", weight: 2, category: "social" },
			{ template: "Dark mode looks like a different app. Not in a good way", weight: 2, category: "social" },
			{ template: "Long text broke it in 3 seconds. Dare accepted", weight: 2, category: "social" },
			{ template: "Tooltip clips off-screen on the left. And the right. And the top", weight: 1, category: "social" },
			{ template: "Tab order goes: header, footer, sidebar, content. In that order", weight: 1, category: "social" },
			{ template: "It got weird at 768px. Very weird. Screenshot incoming", weight: 2, category: "social" },
			{ template: "Skeleton loader pulses at anxiety-inducing speed", weight: 2, category: "social" },
			{ template: "Real content is 3x longer than your placeholder. Everything overflows", weight: 1, category: "social" },
			{ template: "The animation is frantic. Users will think something is wrong", weight: 1, category: "social" },
			{ template: "Brutally honest: it's 80% gorgeous and 20% broken", weight: 2, category: "social" },
			{ template: "Fresh eyes found stale bugs. Your prototype has three", weight: 1, category: "social" },
			{ template: "Invisible focus indicator? I noticed. With my eyes closed", weight: 2, category: "social" },
			{ template: "Testing delight: I time how fast users smile. Or frown", weight: 1, category: "social" },
			{ template: "Bulletproof? I pasted a novel into the name field. It exploded", weight: 2, category: "social" },
			{ template: "Found the missing flow. Also found two more you probably want", weight: 2, category: "social" },
		],
	},
	// analysis <-> engineering
	{
		domainA: "analysis",
		domainB: "engineering",
		linesA: [
			{ template: "Your event tracking is missing data", weight: 2, category: "social" },
			{ template: "Can you add a timestamp to that payload? I'm begging you", weight: 2, category: "social" },
			{ template: "The query takes 45 seconds. Is that... intentional?", weight: 2, category: "social" },
			{ template: "I found an anomaly. Either it's a bug or we found something big", weight: 1, category: "social" },
			{ template: "Your logs are beautiful. If only the data pipeline agreed", weight: 1, category: "social" },
			{ template: "The event names are inconsistent. user_click vs userClick vs click", weight: 2, category: "social" },
			{ template: "Can you stop sending null when you mean zero? They're different", weight: 1, category: "social" },
			{ template: "Your schema changed without warning. My dashboards wept", weight: 2, category: "social" },
			{ template: "I need a user_id on every event. Every. Single. One", weight: 2, category: "social" },
			{ template: "The data warehouse is 90% your debug logs. Can we talk?", weight: 1, category: "social" },
			{ template: "Duplicate events everywhere. Is your service stuttering?", weight: 2, category: "social" },
			{ template: "UTC. Please use UTC. Not local time. Not server time. UTC", weight: 1, category: "social" },
			{ template: "Your API returns dates in three different formats. Why?", weight: 2, category: "social" },
			{ template: "I built a report. Then your deploy changed all the field names", weight: 2, category: "social" },
			{ template: "The join between your tables takes longer than the query itself", weight: 1, category: "social" },
			{ template: "Want to pair on designing the event taxonomy? I brought snacks", weight: 1, category: "social" },
			{ template: "Your enum values are 1, 2, 3, 99. What happened to 4 through 98?", weight: 2, category: "social" },
			{ template: "I actually enjoy reading your API docs. First time for everything", weight: 1, category: "social" },
			{ template: "The data lake is 40% your orphaned temp tables. Spring cleaning?", weight: 2, category: "social" },
			{ template: "Your boolean field has three states. Impressive and terrifying", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "The data is there. Somewhere. In one of the tables", weight: 2, category: "social" },
			{ template: "A timestamp? That's three story points and a database migration", weight: 2, category: "social" },
			{ template: "45 seconds is fast for that much data. Trust me", weight: 2, category: "social" },
			{ template: "It's always a bug. I'm sorry. It's always a bug", weight: 1, category: "social" },
			{ template: "Define 'missing'. It's null, not missing. Big difference. Maybe", weight: 2, category: "social" },
			{ template: "The naming convention evolved. Naturally. Over time. Organically", weight: 2, category: "social" },
			{ template: "Null means unknown. Zero means zero. Undefined means I forgot", weight: 2, category: "social" },
			{ template: "Schema changes are documented. In the commit message. Somewhere", weight: 1, category: "social" },
			{ template: "user_id on every event? Do you know what that costs in bandwidth?", weight: 2, category: "social" },
			{ template: "Debug logs are data too. Very verbose, very important data", weight: 1, category: "social" },
			{ template: "Duplicates are just redundancy. It's a feature for resilience", weight: 2, category: "social" },
			{ template: "One of those date formats is legacy. The other two are... also legacy", weight: 2, category: "social" },
			{ template: "UTC is hard. Timezones are a social construct. Don't @ me", weight: 1, category: "social" },
			{ template: "Field names changed for good reason. I think. Let me check git", weight: 1, category: "social" },
			{ template: "The join is slow because your query isn't indexed. Probably", weight: 2, category: "social" },
			{ template: "Event taxonomy with snacks? You had me at snacks. Let's go", weight: 1, category: "social" },
			{ template: "4 through 98 are reserved. For what? Future regret", weight: 2, category: "social" },
			{ template: "You enjoy our API docs? I'll frame this conversation", weight: 1, category: "social" },
			{ template: "Orphaned tables have feelings. And foreign keys. Can't just delete", weight: 2, category: "social" },
			{ template: "Three-state boolean is called a trit. I learned that last week", weight: 2, category: "social" },
		],
	},
	// management <-> product
	{
		domainA: "management",
		domainB: "product",
		linesA: [
			{ template: "The quarterly review is in 2 weeks. Where are we?", weight: 2, category: "social" },
			{ template: "Can we show ROI on this initiative?", weight: 2, category: "social" },
			{ template: "The investors want a progress update. In metrics, not stories", weight: 1, category: "social" },
			{ template: "Are we still on track for the annual goals?", weight: 2, category: "social" },
			{ template: "What's the competitive landscape looking like?", weight: 1, category: "social" },
			{ template: "Can you present at the board meeting? They love your energy", weight: 2, category: "social" },
			{ template: "Headcount request needs a business case. A compelling one", weight: 1, category: "social" },
			{ template: "The OKRs need updating. The old ones were too easy. Or too hard", weight: 2, category: "social" },
			{ template: "Finance is asking about the feature spend. Do we have numbers?", weight: 1, category: "social" },
			{ template: "Can you turn this into a success story for the newsletter?", weight: 2, category: "social" },
			{ template: "The CEO wants 'moonshot thinking'. What does that mean for Q4?", weight: 2, category: "social" },
			{ template: "Revenue attribution by feature. Is that possible? By Friday?", weight: 1, category: "social" },
			{ template: "Your roadmap and the budget don't agree. Fix one of them", weight: 2, category: "social" },
			{ template: "Strategic alignment check. Are we still strategically aligned?", weight: 1, category: "social" },
			{ template: "The all-hands is Thursday. I need wins. Got any wins?", weight: 2, category: "social" },
			{ template: "Want to do a joint stakeholder walkthrough?", weight: 1, category: "social" },
			{ template: "The advisory board meets next week. What's our narrative?", weight: 2, category: "social" },
			{ template: "I respect your product instinct. Can we back it with a spreadsheet?", weight: 1, category: "social" },
			{ template: "The hiring plan depends on the roadmap. Which depends on hiring", weight: 2, category: "social" },
			{ template: "Can we turn that customer win into an internal case study?", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "We're exactly where the last update said we'd be. On track-ish", weight: 2, category: "social" },
			{ template: "ROI is complicated. Let me build a narrative around the numbers", weight: 2, category: "social" },
			{ template: "The metrics are moving. In a direction. A mostly good direction", weight: 2, category: "social" },
			{ template: "Annual goals are achievable if Q3 goes perfectly. So... maybe", weight: 1, category: "social" },
			{ template: "Competition shipped something similar. But ours is better. Probably", weight: 2, category: "social" },
			{ template: "I have a deck. It has charts. The charts go up. You'll love it", weight: 1, category: "social" },
			{ template: "Board meeting? I'll bring slides and optimism. Heavy on the optimism", weight: 2, category: "social" },
			{ template: "Business case: if we don't hire, nothing ships. How's that?", weight: 2, category: "social" },
			{ template: "OKRs were perfectly calibrated. The market moved. Not my fault", weight: 1, category: "social" },
			{ template: "Success story? Define success. Loosely, preferably", weight: 2, category: "social" },
			{ template: "Moonshot for Q4 means we miss Q4. But Q1 will be amazing", weight: 2, category: "social" },
			{ template: "Revenue by feature by Friday? I can give you revenue by quarter by Monday", weight: 1, category: "social" },
			{ template: "The roadmap is correct. The budget is aspirational. Both are fine", weight: 2, category: "social" },
			{ template: "We are strategically aligned. Tactically is another conversation", weight: 1, category: "social" },
			{ template: "Wins: we didn't break anything this sprint. That counts", weight: 2, category: "social" },
			{ template: "I have wins. I also have context. The context takes longer", weight: 1, category: "social" },
			{ template: "Joint walkthrough? Sure. Let me rehearse my enthusiasm first", weight: 1, category: "social" },
			{ template: "Our narrative is growth. With asterisks. Several asterisks", weight: 2, category: "social" },
			{ template: "My instinct is backed by 200 user interviews. That IS the spreadsheet", weight: 1, category: "social" },
			{ template: "Circular dependency between hiring and roadmap. Very on-brand for us", weight: 2, category: "social" },
			{ template: "Case study, sure. Emphasis on the word 'study'. Not 'spin'", weight: 2, category: "social" },
		],
	},
	// operations <-> quality
	{
		domainA: "operations",
		domainB: "quality",
		linesA: [
			{ template: "Uptime was 99.97% this month. You're welcome", weight: 2, category: "social" },
			{ template: "Your test environment keeps dying. Can you stop stress-testing it?", weight: 2, category: "social" },
			{ template: "The load test took down staging. Again. How much traffic did you simulate?", weight: 2, category: "social" },
			{ template: "Can you test without maxing out the CPU? Just once?", weight: 1, category: "social" },
			{ template: "Your automation suite runs for 6 hours. The deploy window is 2", weight: 2, category: "social" },
			{ template: "I need you to test the rollback procedure too. Not just the deploy", weight: 1, category: "social" },
			{ template: "The monitoring caught it before your tests did. Just saying", weight: 2, category: "social" },
			{ template: "Staging is not production. Stop treating it like a sandbox", weight: 1, category: "social" },
			{ template: "Your test data is filling up the disk. It's very thorough. Too thorough", weight: 2, category: "social" },
			{ template: "Can we coordinate test windows? My alerts are going haywire", weight: 1, category: "social" },
			{ template: "The canary deploy caught what your regression suite missed", weight: 2, category: "social" },
			{ template: "Chaos testing is great. Warning me first would be greater", weight: 2, category: "social" },
			{ template: "Want to build the load test profile together? I know the limits", weight: 1, category: "social" },
			{ template: "Your test data seeded 10 million rows. My disk has opinions", weight: 2, category: "social" },
			{ template: "I quietly admire your test coverage. Don't tell engineering", weight: 1, category: "social" },
			{ template: "The staging SSL cert expired during your test run. Coincidence?", weight: 2, category: "social" },
			{ template: "Your performance test found a leak we missed. Genuinely thank you", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "99.97% means 13 minutes of downtime. Users remember those minutes", weight: 2, category: "social" },
			{ template: "If staging can't handle my tests, it can't handle users", weight: 2, category: "social" },
			{ template: "I simulated realistic traffic. Your infra just has low standards", weight: 2, category: "social" },
			{ template: "CPU should be maxed during load tests. That's the point", weight: 1, category: "social" },
			{ template: "6 hours of testing saves 6 days of incident response. Math", weight: 2, category: "social" },
			{ template: "I tested the rollback. It doesn't work. You should know that", weight: 2, category: "social" },
			{ template: "Monitoring catches symptoms. Testing catches causes. We need both", weight: 1, category: "social" },
			{ template: "If staging isn't a sandbox, where am I supposed to break things?", weight: 2, category: "social" },
			{ template: "Test data reflects real usage patterns. Real users are messy", weight: 1, category: "social" },
			{ template: "Coordinate windows? My tests should run anytime. Like real users", weight: 1, category: "social" },
			{ template: "The canary caught one thing. My suite catches hundreds. Apples and oranges", weight: 2, category: "social" },
			{ template: "Chaos testing without warning IS the test. Surprise is the feature", weight: 2, category: "social" },
			{ template: "Build the load profile together? Finally someone who speaks traffic", weight: 1, category: "social" },
			{ template: "10 million rows IS the realistic dataset. Users are prolific", weight: 2, category: "social" },
			{ template: "You admire my coverage? I admire your uptime. Secret mutual respect", weight: 1, category: "social" },
			{ template: "The cert expired because nobody renewed it. I tested that scenario too", weight: 2, category: "social" },
			{ template: "Finding leaks is what I do. You keep the ship floating. Good duo", weight: 2, category: "social" },
		],
	},
	// management <-> design
	{
		domainA: "management",
		domainB: "design",
		linesA: [
			{ template: "Can we get a demo-ready version for the board?", weight: 2, category: "social" },
			{ template: "The investors love visuals. Make it visual", weight: 2, category: "social" },
			{ template: "How soon can we show this to the client?", weight: 1, category: "social" },
			{ template: "Can you make a version that looks finished? Even if it isn't", weight: 2, category: "social" },
			{ template: "The CEO wants to see three options. By tomorrow", weight: 2, category: "social" },
			{ template: "Our brand needs refreshing. Nothing major. Just... everything", weight: 1, category: "social" },
			{ template: "Can you make the dashboard look more impressive for the tour?", weight: 2, category: "social" },
			{ template: "The pitch deck needs a design pass. It's currently embarrassing", weight: 1, category: "social" },
			{ template: "How long does 'pixel perfect' take? Ballpark", weight: 2, category: "social" },
			{ template: "We need to look innovative. Can you design 'innovative'?", weight: 2, category: "social" },
			{ template: "The conference booth needs graphics by Friday. This Friday", weight: 1, category: "social" },
			{ template: "Can we use more blue? Leadership likes blue. Very blue", weight: 2, category: "social" },
			{ template: "Want to present the rebrand together? You do the visuals, I do the spin", weight: 1, category: "social" },
			{ template: "The team page photos need updating. Half the people are gone", weight: 2, category: "social" },
			{ template: "I genuinely don't understand kerning but I respect it deeply", weight: 1, category: "social" },
			{ template: "Can you make the org chart look less... hierarchical?", weight: 2, category: "social" },
			{ template: "The investor deck needs to look like we have 100 people. We have 12", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Demo-ready and good are different timelines", weight: 2, category: "social" },
			{ template: "Visuals take time. Good visuals take more time", weight: 1, category: "social" },
			{ template: "The client can see it when it's ready. Not before", weight: 2, category: "social" },
			{ template: "A version that looks finished but isn't? That's called a lie", weight: 2, category: "social" },
			{ template: "Three options by tomorrow means three bad options by tomorrow", weight: 2, category: "social" },
			{ template: "Refreshing everything is called a rebrand. That's 6 months minimum", weight: 1, category: "social" },
			{ template: "I can make it impressive or I can make it honest. Pick one", weight: 2, category: "social" },
			{ template: "The pitch deck needs content first. I polish, I don't create fiction", weight: 1, category: "social" },
			{ template: "Pixel perfect takes as long as it takes. That's the ballpark", weight: 2, category: "social" },
			{ template: "'Innovative' isn't a design direction. It's a buzzword in a suit", weight: 2, category: "social" },
			{ template: "Friday graphics means Thursday all-nighter. Just so we're clear", weight: 1, category: "social" },
			{ template: "More blue? Our palette has 47 blues already. Which blue?", weight: 2, category: "social" },
			{ template: "Co-present? Sure. You handle the questions. I'll handle the slides", weight: 1, category: "social" },
			{ template: "Team photos? I'll schedule the shoot. But no corporate poses", weight: 2, category: "social" },
			{ template: "Kerning is the space between letters and between chaos and order", weight: 1, category: "social" },
			{ template: "Less hierarchical org chart? That's called a circle. I can do circles", weight: 2, category: "social" },
			{ template: "12 people looking like 100? That's typography and confidence. I got this", weight: 2, category: "social" },
		],
	},
	// analysis <-> design
	{
		domainA: "analysis",
		domainB: "design",
		linesA: [
			{ template: "The heatmap says nobody clicks that button", weight: 2, category: "social" },
			{ template: "Users scroll past your hero section in 0.3 seconds", weight: 2, category: "social" },
			{ template: "The data shows the old design converted better. Sorry", weight: 2, category: "social" },
			{ template: "Can we A/B test before committing to the redesign?", weight: 1, category: "social" },
			{ template: "Eye tracking says users look at the wrong thing first", weight: 2, category: "social" },
			{ template: "Your beautiful layout has a 73% bounce rate. Let's discuss", weight: 1, category: "social" },
			{ template: "Session recordings show users are lost. Aesthetically lost", weight: 2, category: "social" },
			{ template: "The conversion funnel disagrees with your design instinct", weight: 1, category: "social" },
			{ template: "Users prefer the ugly version. I have charts to prove it", weight: 2, category: "social" },
			{ template: "Form completion drops 20% at step 3. The pretty step", weight: 2, category: "social" },
			{ template: "Can you add a CTA where people actually look?", weight: 1, category: "social" },
			{ template: "Intuition is great. Validated intuition is better", weight: 1, category: "social" },
			{ template: "Want to look at the click-path recordings together?", weight: 1, category: "social" },
			{ template: "Your color palette tests differently across demographics. Interesting", weight: 2, category: "social" },
			{ template: "I mapped every pixel of user attention. Your hero image wins", weight: 1, category: "social" },
			{ template: "The scroll depth data suggests nobody reads below the fold", weight: 2, category: "social" },
			{ template: "Your redesign moved the needle. Actual data needle. I'm impressed", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Nobody clicks it because the page flow is wrong, not the button", weight: 2, category: "social" },
			{ template: "0.3 seconds means the content below is more interesting. Good design", weight: 2, category: "social" },
			{ template: "The old design converted better because it was manipulative", weight: 2, category: "social" },
			{ template: "A/B tests measure clicks, not experience. They're not the same", weight: 1, category: "social" },
			{ template: "Users look where I want them to. Eventually", weight: 2, category: "social" },
			{ template: "Bounce rate measures impatience, not design quality", weight: 1, category: "social" },
			{ template: "Lost? They're exploring. It's an experience, not a highway", weight: 2, category: "social" },
			{ template: "Conversion isn't the only metric that matters. Delight matters too", weight: 1, category: "social" },
			{ template: "Users prefer ugly because ugly is familiar. Not because it's better", weight: 2, category: "social" },
			{ template: "Step 3 is complex. That's a content problem, not a design one", weight: 2, category: "social" },
			{ template: "A CTA where people look? That's just a fancy way to say popup", weight: 1, category: "social" },
			{ template: "My intuition is validated. By 15 years of design experience", weight: 2, category: "social" },
			{ template: "Click-path recordings? Sure. Prepare to see users ignore your charts", weight: 1, category: "social" },
			{ template: "Demographics respond to emotion, not just color. Data can't see that", weight: 2, category: "social" },
			{ template: "Hero image wins because I spent a week on it. The data just agrees", weight: 1, category: "social" },
			{ template: "Below the fold is alive and well. People scroll. They just don't click", weight: 2, category: "social" },
			{ template: "Moved the needle? I moved the whole dashboard. You measured it. We both win", weight: 2, category: "social" },
		],
	},
];

/** Find a crossover pair for two given domains, checking both orderings. */
export function findCrossover(domainA: string, domainB: string): CrossoverPair | undefined {
	return CROSSOVER_PAIRS.find(
		(pair) =>
			(pair.domainA === domainA && pair.domainB === domainB) ||
			(pair.domainA === domainB && pair.domainB === domainA),
	);
}
