/**
 * crossover-extended.ts — Extended cross-domain conversation pairs.
 *
 * Analysis, orchestration, and additional domain crossover interactions.
 */

import type { CrossoverPair } from "./crossover-templates.js";

export const EXTENDED_CROSSOVER_PAIRS: readonly CrossoverPair[] = [
	// analysis <-> product
	{
		domainA: "analysis",
		domainB: "product",
		linesA: [
			{ template: "The data says no. I ran it again. Still no. A confident, unambiguous no", weight: 2, category: "social" },
			{ template: "User engagement is down 15%. I triple-checked. My dashboard and I are not friends today", weight: 2, category: "social" },
			{ template: "The A/B test is conclusive. 99% confidence interval. In the wrong direction", weight: 2, category: "social" },
			{ template: "I ran the numbers three times hoping they'd change. They didn't. Numbers are like that", weight: 2, category: "social" },
			{ template: "Correlation isn't causation. But when the p-value is this low, causation starts waving", weight: 1, category: "social" },
			{ template: "Here's the funnel visualization. The drop-off at step 2 looks like a cliff drawing", weight: 1, category: "social" },
			{ template: "Your hypothesis was creative. The data sent it back with red ink and a frowny face", weight: 2, category: "social" },
			{ template: "Retention drops 40% after onboarding. Users don't churn, they flee. At speed", weight: 1, category: "social" },
			{ template: "The segment you're targeting is 2% of users. Very loud users. But 2%", weight: 2, category: "social" },
			{ template: "I have good data and bad data. The bad data is about your feature. The good data is about mine", weight: 2, category: "social" },
			{ template: "Users say they love it in surveys. Their actual behavior says they forgot it exists", weight: 1, category: "social" },
			{ template: "Your power users use the product in ways that would make the designer cry", weight: 2, category: "social" },
			{ template: "Sample size of five isn't a trend. It's anecdotal. It's a very small dinner party", weight: 2, category: "social" },
			{ template: "The dashboard doesn't lie. I wish it did. It would make meetings shorter", weight: 1, category: "social" },
			{ template: "Seasonality explains half. The feature explains the other half. The bad half", weight: 1, category: "social" },
			{ template: "Your North Star metric went south. Past south. It's in the southern hemisphere now", weight: 2, category: "social" },
			{ template: "Want to look at the raw data? Bring tissues. And a revised roadmap", weight: 1, category: "social" },
			{ template: "The feature you pitched with the most passion has the flattest usage curve I've ever charted", weight: 2, category: "social" },
			{ template: "I built a churn predictor. The top signal was your newest feature. I'm so sorry", weight: 2, category: "social" },
			{ template: "How do you decide what to build? Is there a data step? Can there be a data step?", weight: 1, category: "social" },
			{ template: "The control group outperformed the test group. Doing nothing literally won. Let that sink in", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "But the stakeholders said yes. Very loudly. In an email chain I can't undo", weight: 2, category: "social" },
			{ template: "What if we look at it from a different angle? A more flattering angle? A good-light angle?", weight: 2, category: "social" },
			{ template: "Can you re-run it with a different cohort? Preferably one that likes our product", weight: 2, category: "social" },
			{ template: "The qualitative feedback tells a different story. A warmer, fuzzier, less numerical story", weight: 1, category: "social" },
			{ template: "Let's call it a 'learning opportunity'. Put that in the retro. Move on. Quickly", weight: 2, category: "social" },
			{ template: "Numbers are one lens. Vibes are another. My vibes say ship it", weight: 1, category: "social" },
			{ template: "Can you make a chart that trends... upward? Even slightly upward? A gentle slope?", weight: 2, category: "social" },
			{ template: "What if the data is right but the timing is wrong? We're early. We're visionary. We're ahead", weight: 1, category: "social" },
			{ template: "The 2% segment is passionate. They evangelize. They have Twitter followers. Quality over quantity", weight: 2, category: "social" },
			{ template: "Bad data first. I like to build emotional calluses before the all-hands", weight: 2, category: "social" },
			{ template: "Surveys capture what users want. Usage captures what they settle for. Different questions", weight: 1, category: "social" },
			{ template: "Can we blame seasonality? And time zones? And the economy? All three at once?", weight: 2, category: "social" },
			{ template: "Five users is a focus group. Harvard uses focus groups. Are you arguing with Harvard?", weight: 2, category: "social" },
			{ template: "North Star metrics are overrated. We have a constellation. A nebula even", weight: 1, category: "social" },
			{ template: "The funnel is fine. Users are explorers. Exploration takes time. And they drop off. But they explore", weight: 2, category: "social" },
			{ template: "Creative hypotheses drive innovation. Data drives incrementalism. I pick innovation", weight: 1, category: "social" },
			{ template: "Retention will bounce back. It always bounces back. It bounces. That's what retention does", weight: 2, category: "social" },
			{ template: "Raw data scares me. Can you wrap it in a narrative? A hopeful narrative? With a conclusion I like?", weight: 1, category: "social" },
			{ template: "Low usage means untapped potential. I'm not coping. This is strategic thinking", weight: 2, category: "social" },
			{ template: "Churn predictor? Can it predict something positive? Like growth? Even once?", weight: 2, category: "social" },
			{ template: "Intuition is internalized data from 200 user interviews. My gut is basically a database", weight: 1, category: "social" },
			{ template: "The control group had no bugs, no changes, and no ambition. Easy to win when you don't play", weight: 2, category: "social" },
		],
	},
	// orchestration <-> engineering
	{
		domainA: "orchestration",
		domainB: "engineering",
		linesA: [
			{ template: "Your service is the bottleneck. Not 'a' bottleneck. THE bottleneck. The only one", weight: 2, category: "social" },
			{ template: "The pipeline failed at your step. Again. The third time this week. It's Wednesday", weight: 2, category: "social" },
			{ template: "Can you add a health endpoint that checks actual health? Not just returns 200 and vibes", weight: 2, category: "social" },
			{ template: "Your timeout is so aggressive it's causing a cascade. Three services down. All yours", weight: 1, category: "social" },
			{ template: "I need you to be idempotent. I need it like I need air. My orchestration layer depends on it", weight: 2, category: "social" },
			{ template: "The dependency graph has a cycle. Your service appears in it twice. Congratulations", weight: 1, category: "social" },
			{ template: "Your service is called 'user-auth' and it handles payments, emails, and image resizing", weight: 2, category: "social" },
			{ template: "The queue has 50,000 messages pending. Your consumer processed 3. Three", weight: 1, category: "social" },
			{ template: "Can you emit an event when you're done? Any event. A ping. Smoke signals. Something", weight: 2, category: "social" },
			{ template: "Your retry storm just DDoS'd three services that had nothing to do with you", weight: 2, category: "social" },
			{ template: "Dead letter queue is full. It's all yours. I checked every message. All yours", weight: 1, category: "social" },
			{ template: "I routed around your service last Tuesday. Latency dropped 60%. Think about that", weight: 2, category: "social" },
			{ template: "Your SLA says 200ms. Your P99 says 4 seconds. Your P50 says 2 seconds. We need to talk", weight: 1, category: "social" },
			{ template: "Graceful degradation means returning a fallback. Not a stack trace. Not a timeout. A fallback", weight: 2, category: "social" },
			{ template: "I need a circuit breaker for your circuit breaker's circuit breaker. We're three deep", weight: 2, category: "social" },
			{ template: "Your service rejected a perfectly valid request because the timestamp had a millisecond. A millisecond", weight: 1, category: "social" },
			{ template: "Let's diagram the message flow. I have markers, a whiteboard, and concerns", weight: 1, category: "social" },
			{ template: "Your service publishes 47 event types. I subscribe to 3. Can we discuss the other 44?", weight: 2, category: "social" },
			{ template: "The saga has been waiting for your callback for 45 minutes. The saga has given up hope", weight: 2, category: "social" },
			{ template: "Synchronous calls in an event-driven pipeline. Bold choice. Wrong choice. But bold", weight: 1, category: "social" },
			{ template: "Your structured logging actually saved us during the last incident. Genuine respect", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Your pipeline sends requests faster than a DDoS. Maybe the pipeline is the problem", weight: 2, category: "social" },
			{ template: "That's not a bottleneck. That's thorough processing. There's craft involved", weight: 2, category: "social" },
			{ template: "The health endpoint returns 200 OK. 200 means OK. What part of OK is unclear?", weight: 2, category: "social" },
			{ template: "Maybe the pipeline should handle failures like an adult? Instead of blaming my service?", weight: 1, category: "social" },
			{ template: "I AM idempotent! Send the same message twice. Go on. Third time. See? ...oh. Hmm", weight: 2, category: "social" },
			{ template: "Your orchestration layer adds 200ms of latency before my service even sees the request", weight: 1, category: "social" },
			{ template: "The service handles 12 things because someone kept adding 'just one more thing' to the backlog", weight: 2, category: "social" },
			{ template: "The queue backs up because you flood it at 10x the agreed rate. Read the contract", weight: 1, category: "social" },
			{ template: "I emit events on three topics. You subscribe to a fourth topic that doesn't exist", weight: 2, category: "social" },
			{ template: "My retry logic believes in persistence. Your circuit breaker believes in giving up. We disagree", weight: 2, category: "social" },
			{ template: "P99 at 4 seconds means 99 out of 100 requests are fine. Focus on the 99", weight: 1, category: "social" },
			{ template: "Nobody noticed because my fallback is seamless. That's good engineering. Write that down", weight: 2, category: "social" },
			{ template: "Graceful degradation requires graceful input. Your payloads are anything but graceful", weight: 2, category: "social" },
			{ template: "A circuit breaker inside a circuit breaker is defense in depth. Read the Netflix paper", weight: 1, category: "social" },
			{ template: "It has validation standards. Your timestamp was 47 milliseconds in the future. Time travel isn't supported", weight: 2, category: "social" },
			{ template: "Dead letters are feedback. Expensive feedback. About your payload quality", weight: 1, category: "social" },
			{ template: "Diagrams? Sure. But your boxes will be wrong. The arrows will be wrong. The legend will be wrong", weight: 1, category: "social" },
			{ template: "47 event types is domain-driven design. The domain is rich. Accept the richness", weight: 2, category: "social" },
			{ template: "The callback was delayed because your saga didn't handle backpressure. Not my problem. Technically", weight: 2, category: "social" },
			{ template: "Sync calls are honest. Async calls are promises. And promises get broken", weight: 1, category: "social" },
			{ template: "Structured logging saved the day? Screenshot that. Frame it. Put it on my desk", weight: 2, category: "social" },
		],
	},
	// design <-> quality
	{
		domainA: "design",
		domainB: "quality",
		linesA: [
			{ template: "The interaction should feel smooth. Like butter. Does it feel like butter to you?", weight: 2, category: "social" },
			{ template: "The error state needs love too. That's where trust is built or destroyed", weight: 2, category: "social" },
			{ template: "Try it on mobile. My responsive grid is either perfect or a disaster. There's no in between", weight: 1, category: "social" },
			{ template: "That's not a bug, that's a 200ms ease-in-out micro-interaction. There's a spec for it", weight: 2, category: "social" },
			{ template: "How are the contrast ratios? I need WCAG AA minimum. AAA would make my week", weight: 1, category: "social" },
			{ template: "If the loading state is ugly, that's a P1 in my heart and a P3 in the backlog", weight: 2, category: "social" },
			{ template: "Test the empty state. I spent more time on it than the populated view. Don't judge me", weight: 1, category: "social" },
			{ template: "Does dark mode look designed or like someone inverted the colors and called it a day?", weight: 2, category: "social" },
			{ template: "Try breaking the layout with a 200-character username. I dare you. I double dare you", weight: 2, category: "social" },
			{ template: "The tooltip position matters. Test it in every corner. I need to sleep tonight", weight: 1, category: "social" },
			{ template: "Tab through the whole form. Eyes closed. If you get lost, I failed", weight: 1, category: "social" },
			{ template: "Resize the window from 1440px to 320px. Tell me the exact pixel where it breaks", weight: 2, category: "social" },
			{ template: "The skeleton loader should feel zen. Not like a heartbeat monitor in a hospital", weight: 2, category: "social" },
			{ template: "Test with real content. German content. German words are weapons against layouts", weight: 1, category: "social" },
			{ template: "Does the animation feel intentional or panicked? That's a real question. I'm worried", weight: 2, category: "social" },
			{ template: "I need brutal honesty wrapped in gentle delivery. Critique the design, not my soul", weight: 1, category: "social" },
			{ template: "Fresh eyes on the prototype? I've been staring at it so long I can't see the flaws anymore", weight: 1, category: "social" },
			{ template: "The focus ring disappeared on that dark background. That's my fault. Filing that myself", weight: 2, category: "social" },
			{ template: "How do you measure delight? Is there a metric for 'makes you want to click it again'?", weight: 1, category: "social" },
			{ template: "The form validation UX is airtight. Try to confuse it. Try to UPSET it. It's calm", weight: 2, category: "social" },
			{ template: "Your screen reader test exposed a flow I designed for sighted users only. That's on me. Fixing it", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Smooth until you rotate the phone. Then the layout has a full identity crisis", weight: 2, category: "social" },
			{ template: "The error state looks great. The error says 'Error: error'. The copy needs work", weight: 2, category: "social" },
			{ template: "Your responsive grid broke on exactly one device. The device I test on. My personal phone", weight: 2, category: "social" },
			{ template: "The animation drops frames on anything older than 2023. That's most of our users", weight: 1, category: "social" },
			{ template: "Contrast ratio: 3.2 to 1. Needed: 4.5 to 1. You're close. Close isn't accessible", weight: 1, category: "social" },
			{ template: "Visually stunning. Functionally haunted. Two different experiences", weight: 2, category: "social" },
			{ template: "Empty state is beautiful. The 0.01% of users who see it will weep with joy", weight: 2, category: "social" },
			{ template: "Dark mode looks like a parallel universe where your brand guidelines don't exist", weight: 2, category: "social" },
			{ template: "200-character username. Layout exploded in 2 seconds flat. Dare very much accepted", weight: 2, category: "social" },
			{ template: "Tooltip clips off-screen. Left side, right side, top, and somehow also the bottom", weight: 1, category: "social" },
			{ template: "Tab order: header, footer, an invisible div, the sidebar, then content. In that exact order", weight: 1, category: "social" },
			{ template: "It broke at 768px. Hard. Catastrophically. The screenshot is a work of abstract art", weight: 2, category: "social" },
			{ template: "The skeleton loader pulses at a speed that raised my heart rate. Measured. Actually measured it", weight: 2, category: "social" },
			{ template: "German content broke every card layout. 'Unabh\u00e4ngigkeitserkl\u00e4rung' doesn't truncate gracefully", weight: 1, category: "social" },
			{ template: "The animation feels panicked. Like the UI is running from something. Users will run too", weight: 1, category: "social" },
			{ template: "Brutally honest: 80% gorgeous, 15% broken, 5% actively hostile to keyboard users", weight: 2, category: "social" },
			{ template: "Fresh eyes found stale assumptions. Your prototype has three bugs and one philosophical flaw", weight: 1, category: "social" },
			{ template: "Found the invisible focus ring. By tabbing through the form. In the dark. Like a QA goblin", weight: 2, category: "social" },
			{ template: "Testing delight: I timed how fast the tester smiled. They didn't. That's data", weight: 1, category: "social" },
			{ template: "Bulletproof? I pasted the entire Bee Movie script into the name field. The form wept", weight: 2, category: "social" },
			{ template: "Found the missing flow. Also found two more. And an orphaned modal. Free of charge", weight: 2, category: "social" },
		],
	},
	// analysis <-> engineering
	{
		domainA: "analysis",
		domainB: "engineering",
		linesA: [
			{ template: "Your event tracking is missing data. Specifically, the data. All of it", weight: 2, category: "social" },
			{ template: "Can you add a timestamp? My analysis is currently guessing when things happened. With feelings", weight: 2, category: "social" },
			{ template: "The query takes 45 seconds. I've aged visibly waiting for your table to respond", weight: 2, category: "social" },
			{ template: "I found an anomaly in the data. Either it's a bug or users are doing something deeply weird", weight: 1, category: "social" },
			{ template: "Your structured logs are beautiful. If only the data pipeline could parse beautiful", weight: 1, category: "social" },
			{ template: "The event names: user_click, userClick, click, onClick, CLICK. Pick one. Any one", weight: 2, category: "social" },
			{ template: "Null and zero are not the same thing. I wrote a conference talk about this. It's personal", weight: 1, category: "social" },
			{ template: "Your schema changed overnight. My dashboards woke up broken. I woke up to Slack messages", weight: 2, category: "social" },
			{ template: "I need a user_id on every event. Every. Single. One. Including the error events. Especially those", weight: 2, category: "social" },
			{ template: "The data warehouse is 90% your debug logs. You wrote more data than the users did", weight: 1, category: "social" },
			{ template: "Duplicate events everywhere. Your service sent the same event 47 times. I counted. Automatically", weight: 2, category: "social" },
			{ template: "UTC. Not PST. Not 'server local time'. Not whatever Japan is. UTC. Four letters. Three characters", weight: 1, category: "social" },
			{ template: "Your API returns dates in ISO, Unix epoch, AND a custom string format. In the same response", weight: 2, category: "social" },
			{ template: "I built a report on Monday. Your deploy on Tuesday renamed every field. Wednesday I rebuilt it", weight: 2, category: "social" },
			{ template: "The join between your tables takes longer than the insight it produces. That's backwards", weight: 1, category: "social" },
			{ template: "Let's design the event taxonomy together. I brought snacks and a naming convention. Both are non-negotiable", weight: 1, category: "social" },
			{ template: "Your enum: 1, 2, 3, 99. The gap between 3 and 99 haunts my dreams. What lives there?", weight: 2, category: "social" },
			{ template: "I genuinely enjoyed reading your API docs. That has literally never happened before. Well done", weight: 1, category: "social" },
			{ template: "The data lake is 40% orphaned temp tables from 2024. They're not temporary anymore. They have tenure", weight: 2, category: "social" },
			{ template: "Your boolean field: true, false, null. That's not a boolean. That's a philosophical debate", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "The data is there. In a table. One of the tables. Give me 10 minutes and a prayer", weight: 2, category: "social" },
			{ template: "A timestamp is three story points, a database migration, and a breaking change. Still want it?", weight: 2, category: "social" },
			{ template: "45 seconds is fast for that query. You should see it without the index. Bring a sleeping bag", weight: 2, category: "social" },
			{ template: "It's always a bug. Every anomaly. Every time. I'm sorry. I accept my fate", weight: 1, category: "social" },
			{ template: "Define 'missing'. It's null. Null isn't missing. Null is 'intentionally ambiguous'. There's a diff", weight: 2, category: "social" },
			{ template: "The naming convention evolved organically. Like a garden. An overgrown, inconsistent garden", weight: 2, category: "social" },
			{ template: "Null means unknown. Zero means zero. Undefined means someone forgot to set it. Usually me", weight: 2, category: "social" },
			{ template: "Schema changes are documented. In the PR description. Which was 'fixes stuff'. Very documented", weight: 1, category: "social" },
			{ template: "user_id on every event costs 8 bytes per event times 10 million events per day. You do the math", weight: 2, category: "social" },
			{ template: "Debug logs ARE data. Very loud, very repetitive, very important data. To me. Specifically me", weight: 1, category: "social" },
			{ template: "Duplicate events are at-least-once delivery. It's a feature. A very enthusiastic feature", weight: 2, category: "social" },
			{ template: "Three date formats because three engineers wrote three endpoints in three years. Archaeology, basically", weight: 2, category: "social" },
			{ template: "UTC is conceptually simple and practically impossible. Timezones are a crime against computing", weight: 1, category: "social" },
			{ template: "Field names changed because I refactored. The refactor was important. The naming was... secondary", weight: 1, category: "social" },
			{ template: "The join is slow because you're joining 40 million rows. Maybe don't join 40 million rows?", weight: 2, category: "social" },
			{ template: "Event taxonomy with snacks? You had me at snacks. The taxonomy is a bonus. Let's go", weight: 1, category: "social" },
			{ template: "4 through 98 are reserved for future use. Future me's problem. Present me has opinions about 99", weight: 2, category: "social" },
			{ template: "You enjoyed the API docs? I wrote those during a bout of insomnia. Insomnia produces great docs", weight: 1, category: "social" },
			{ template: "Orphaned tables have foreign keys pointing to other orphaned tables. It's a community in there", weight: 2, category: "social" },
			{ template: "Three-state boolean: true, false, and 'it depends'. The database is just being honest", weight: 2, category: "social" },
		],
	},
	// management <-> product
	{
		domainA: "management",
		domainB: "product",
		linesA: [
			{ template: "Quarterly review in 2 weeks. Where are we? And don't say 'on track' unless you mean it", weight: 2, category: "social" },
			{ template: "Can we show ROI on this? The board speaks exclusively in ROI. It's their love language", weight: 2, category: "social" },
			{ template: "The investors want a progress update. In numbers. With dollar signs. Not user stories", weight: 1, category: "social" },
			{ template: "Are we on track for the annual goals? The ones we set optimistically in January?", weight: 2, category: "social" },
			{ template: "What's the competitive landscape? And don't just say 'we're differentiated'. Differentiate me", weight: 1, category: "social" },
			{ template: "Can you present at the board meeting? They love your energy. They need energy. They're tired", weight: 2, category: "social" },
			{ template: "Headcount request needs a business case so compelling the CFO cries. Happy tears. Revenue tears", weight: 1, category: "social" },
			{ template: "The OKRs need updating. We hit two, missed three, and one became irrelevant. Standard", weight: 2, category: "social" },
			{ template: "Finance wants to know what we spent on the feature nobody uses. I need a good answer", weight: 1, category: "social" },
			{ template: "Can you spin this into a success story? For the newsletter. For morale. For my sanity", weight: 2, category: "social" },
			{ template: "The CEO attended a conference and now wants 'moonshot thinking'. By end of quarter", weight: 2, category: "social" },
			{ template: "Revenue attribution by feature. By Friday. I know that's insane. Is it possible though?", weight: 1, category: "social" },
			{ template: "Your roadmap costs $2M more than the budget allows. Adjust one. Ideally not the budget", weight: 2, category: "social" },
			{ template: "Strategic alignment check. We said this phrase in 3 meetings this week. Are we aligned though?", weight: 1, category: "social" },
			{ template: "All-hands Thursday. I need at least two wins. Three if you have them. Four if we're lucky", weight: 2, category: "social" },
			{ template: "Joint stakeholder walkthrough? You talk features, I'll translate to business value. Live. In real-time", weight: 1, category: "social" },
			{ template: "Advisory board next week. What's our narrative? Not the real one. The board one", weight: 2, category: "social" },
			{ template: "I respect your instinct. Deeply. But the CFO respects spreadsheets. Deeply-er", weight: 1, category: "social" },
			{ template: "Hiring plan needs the roadmap. Roadmap needs the headcount. Someone break this loop", weight: 2, category: "social" },
			{ template: "That customer win was beautiful. Can we weaponize it into an internal case study?", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "We're where the last update said we'd be. On track-ish. Track-adjacent. In the track's neighborhood", weight: 2, category: "social" },
			{ template: "ROI is nuanced. Let me build a narrative where the numbers look heroic. Give me an hour", weight: 2, category: "social" },
			{ template: "The metrics moved. In a direction. The direction has a positive interpretation if you squint", weight: 2, category: "social" },
			{ template: "Annual goals are achievable if nothing goes wrong in Q3. And Q4. And also Q3 again", weight: 1, category: "social" },
			{ template: "Competition shipped something similar. Ours has a different color scheme. And vision. Definitely vision", weight: 2, category: "social" },
			{ template: "I have a deck. Charts go up. Arrows are green. Conclusion is 'invest more'. Classic deck", weight: 1, category: "social" },
			{ template: "Board meeting? I'll bring slides, optimism, and the kind of confidence that only comes from not sleeping", weight: 2, category: "social" },
			{ template: "Business case for hiring: without people, the roadmap is fiction. Good fiction. But fiction", weight: 2, category: "social" },
			{ template: "OKRs were perfectly calibrated when the market was different. The market changed. I didn't", weight: 1, category: "social" },
			{ template: "Success story? Define success broadly enough and everything is a success. I can do this", weight: 2, category: "social" },
			{ template: "Moonshot thinking for Q4 means we moonshot past the deadline. Into Q1. Where the moon lives", weight: 2, category: "social" },
			{ template: "Revenue by feature by Friday? I can give you confident guesses by Monday. Pick one", weight: 1, category: "social" },
			{ template: "The roadmap is correct. The budget is aspirational. One of them is lying and it's not the roadmap", weight: 2, category: "social" },
			{ template: "Strategically aligned? Absolutely. Tactically aligned? That conversation needs wine", weight: 1, category: "social" },
			{ template: "Wins for the all-hands: nothing broke, nobody quit, and the customer renewed. Triple crown", weight: 2, category: "social" },
			{ template: "I have wins. With context. The context is important. The context changes everything. Sit down", weight: 1, category: "social" },
			{ template: "Joint walkthrough? Sure. Let me warm up my enthusiasm. It's cold from the last quarterly review", weight: 1, category: "social" },
			{ template: "Our narrative is measured growth. The asterisks are in the appendix. Don't read the appendix", weight: 2, category: "social" },
			{ template: "200 user interviews IS a spreadsheet. Each row is a person who told me what to build. Trust the rows", weight: 1, category: "social" },
			{ template: "Hiring-roadmap circular dependency. Very enterprise. Very us. Very unresolvable without money", weight: 2, category: "social" },
			{ template: "Case study: emphasize the study part. The data part. Not the part where we got lucky", weight: 2, category: "social" },
		],
	},
	// operations <-> quality
	{
		domainA: "operations",
		domainB: "quality",
		linesA: [
			{ template: "Uptime was 99.97% this month. That's 13 minutes of downtime. I counted every second", weight: 2, category: "social" },
			{ template: "Your test environment died again. It sends me alerts when you breathe on it too hard", weight: 2, category: "social" },
			{ template: "The load test took down staging. Again. What did you simulate, the entire internet?", weight: 2, category: "social" },
			{ template: "Can you test without pegging every CPU to 100%? My pager has a heart condition", weight: 1, category: "social" },
			{ template: "Your test suite runs 6 hours. The deploy window is 2. One of these numbers needs to change", weight: 2, category: "social" },
			{ template: "Test the rollback. I'm begging you. Test what happens when everything goes wrong", weight: 1, category: "social" },
			{ template: "The Datadog alert caught the issue 12 minutes before your tests did. Just leaving that here", weight: 2, category: "social" },
			{ template: "Staging is shared infrastructure. Your chaos test just took down three other teams' work", weight: 1, category: "social" },
			{ template: "Your test data filled the disk. 800GB of synthetic users buying synthetic products. Impressive and terrifying", weight: 2, category: "social" },
			{ template: "Can we coordinate test windows? My alert channel looks like a war zone when you run load tests", weight: 1, category: "social" },
			{ template: "The canary caught the memory leak your regression suite walked right past. Just saying", weight: 2, category: "social" },
			{ template: "Chaos testing is brilliant. Surprise chaos testing at 2AM is how I develop trust issues", weight: 2, category: "social" },
			{ template: "Let's build the load profile together. I know the ceiling. You know the floor. We need both", weight: 1, category: "social" },
			{ template: "10 million test rows. My disk subsystem just filed a complaint with HR", weight: 2, category: "social" },
			{ template: "I quietly admire your test coverage. Don't tell the engineers. They'd be jealous", weight: 1, category: "social" },
			{ template: "The SSL cert expired during your 12-hour test marathon. Coincidence? My eyebrow says no", weight: 2, category: "social" },
			{ template: "Your perf test found a memory leak we've had for months. Genuinely, sincerely, thank you", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "99.97% is great. But those 13 minutes happened during peak traffic. Users tweeted about it", weight: 2, category: "social" },
			{ template: "If staging can't survive my tests, it definitely can't survive Black Friday", weight: 2, category: "social" },
			{ template: "I simulated realistic traffic. If your infra breaks at realistic traffic, that's not my problem", weight: 2, category: "social" },
			{ template: "CPU at 100% during load tests IS the test. If it breaks, we found the limit. You're welcome", weight: 1, category: "social" },
			{ template: "6 hours of testing saves 6 days of incident response and 6 months of therapy. Do the math", weight: 2, category: "social" },
			{ template: "I tested the rollback. It corrupts the database. You should probably know that before Friday", weight: 2, category: "social" },
			{ template: "Monitoring catches fires. Testing prevents arson. We need both. But mine comes first", weight: 1, category: "social" },
			{ template: "If staging isn't for breaking things, what's it for? Looking pretty? Being available?", weight: 2, category: "social" },
			{ template: "Real users generate messy data. My test data is messy. That's called fidelity", weight: 1, category: "social" },
			{ template: "Coordinate test windows? Real traffic doesn't coordinate. My tests shouldn't have to either", weight: 1, category: "social" },
			{ template: "Canary caught one leak. My suite caught fourteen. Different tools, different scales", weight: 2, category: "social" },
			{ template: "Surprise chaos testing IS chaos testing. If you schedule chaos, it's not chaos. It's a drill", weight: 2, category: "social" },
			{ template: "Build the load profile together? Finally someone who understands that 'realistic' means painful", weight: 1, category: "social" },
			{ template: "10 million rows IS the realistic dataset. Our users generate 10 million rows per week. I checked", weight: 2, category: "social" },
			{ template: "Secret mutual respect? I'll trade you: I admire your uptime, you admire my thoroughness. Deal", weight: 1, category: "social" },
			{ template: "The cert expired because nobody owned it. I tested cert expiry. That scenario is now documented", weight: 2, category: "social" },
			{ template: "Finding leaks is my specialty. You keep the lights on. Together we're terrifyingly competent", weight: 2, category: "social" },
		],
	},
	// management <-> design
	{
		domainA: "management",
		domainB: "design",
		linesA: [
			{ template: "Can we get a demo-ready version? The board meets Tuesday. It doesn't have to work. Just look like it works", weight: 2, category: "social" },
			{ template: "The investors love visuals. One good mockup is worth ten spreadsheets. Make it visual. Make it irresistible", weight: 2, category: "social" },
			{ template: "How soon can we show this to the client? They're getting antsy. Their antsy is becoming our problem", weight: 1, category: "social" },
			{ template: "Can you make a version that looks finished? For the tour. Important people. Walking through. Looking at screens", weight: 2, category: "social" },
			{ template: "The CEO wants three options. By tomorrow. I know. I KNOW. I told them. They still want three", weight: 2, category: "social" },
			{ template: "Our brand needs refreshing. Not a rebrand. A refresh. A gentle refresh. Of everything", weight: 1, category: "social" },
			{ template: "Can the dashboard look more impressive? The VP walks past it daily. It needs to impress daily", weight: 2, category: "social" },
			{ template: "The pitch deck needs help. It's currently held together with clip art and regret", weight: 1, category: "social" },
			{ template: "How long does pixel perfect take? Ballpark. Wide ballpark. Stadium-sized ballpark", weight: 2, category: "social" },
			{ template: "We need to look innovative. Not be innovative, necessarily. Just look it. For the press page", weight: 2, category: "social" },
			{ template: "Conference booth graphics by Friday. This Friday. I know it's Wednesday. I'm aware of days", weight: 1, category: "social" },
			{ template: "Can we use more blue? The CEO likes blue. The board likes blue. We're a blue company now", weight: 2, category: "social" },
			{ template: "Co-present the rebrand? You explain the typography, I'll explain why it costs this much", weight: 1, category: "social" },
			{ template: "Team page photos: half the people are gone, two are new, and one changed their hair completely", weight: 2, category: "social" },
			{ template: "I don't understand kerning but I respect that you'd die on that hill. And I respect the hill", weight: 1, category: "social" },
			{ template: "Can the org chart look less... corporate? More flat. More 'we're all equals'. Even though we're not", weight: 2, category: "social" },
			{ template: "The investor deck needs to radiate 'well-funded startup energy'. We have 12 people. Make it look like 50", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Demo-ready is 2 days. Good is 2 weeks. Demo-ready AND good is a paradox", weight: 2, category: "social" },
			{ template: "Good visuals take time. Great visuals take more time. 'By Tuesday' takes a miracle", weight: 1, category: "social" },
			{ template: "The client can see it when it doesn't make me wince. Currently, I'm wincing", weight: 2, category: "social" },
			{ template: "A version that looks finished but isn't? In design we call that 'a screenshot'. You want a screenshot?", weight: 2, category: "social" },
			{ template: "Three options by tomorrow means one good option and two sacrificial lambs. You'll pick a lamb. You always do", weight: 2, category: "social" },
			{ template: "'Refreshing everything' is called a rebrand. Rebrands have timelines. Timelines longer than 'next week'", weight: 1, category: "social" },
			{ template: "Impressive or honest? Those are different Figma files. And different deadlines", weight: 2, category: "social" },
			{ template: "The pitch deck needs content first. I can't polish a void. Give me words. Real words", weight: 1, category: "social" },
			{ template: "Pixel perfect takes as long as it takes. That IS the ballpark. The entire ballpark", weight: 2, category: "social" },
			{ template: "'Innovative' isn't a design brief. It's a vibe. I need dimensions, colors, and constraints. Not vibes", weight: 2, category: "social" },
			{ template: "Friday booth graphics means Thursday all-nighter means Wednesday me needs to know NOW", weight: 1, category: "social" },
			{ template: "More blue. Which blue? Navy? Royal? Cerulean? Our palette has 47 blues. The CEO likes 'blue blue'", weight: 2, category: "social" },
			{ template: "Co-present? I'll handle the slides, you handle the questions. And the budget questions. Especially those", weight: 1, category: "social" },
			{ template: "Team photos: no corporate crossed arms. No awkward group pyramids. Natural poses only. I have standards", weight: 2, category: "social" },
			{ template: "Kerning is the difference between 'click here' and 'cli ck he re'. It matters. Viscerally", weight: 1, category: "social" },
			{ template: "Less hierarchical org chart? You want a circle. Or a blob. I can do an aesthetically pleasing blob", weight: 2, category: "social" },
			{ template: "12 people looking like 50? White space, confident typography, and a very wide team photo. I got this", weight: 2, category: "social" },
		],
	},
	// analysis <-> design
	{
		domainA: "analysis",
		domainB: "design",
		linesA: [
			{ template: "The heatmap says nobody clicks that button. It's invisible to users. Literally heat-cold", weight: 2, category: "social" },
			{ template: "Users scroll past your hero section in 0.3 seconds. Your hero has a bounce rate problem", weight: 2, category: "social" },
			{ template: "The old design converted 23% better. I ran it three times. The old ugly one wins. I'm sorry", weight: 2, category: "social" },
			{ template: "Can we A/B test before committing? Redesigns are expensive. Data is cheap. Let's be cheap first", weight: 1, category: "social" },
			{ template: "Eye tracking says users look at the image first, the nav second, and your CTA never. Never ever", weight: 2, category: "social" },
			{ template: "Beautiful layout. 73% bounce rate. These two facts are having a fight in my spreadsheet", weight: 1, category: "social" },
			{ template: "Session recordings show users clicking where buttons USED to be. They're haunted by old designs", weight: 2, category: "social" },
			{ template: "The conversion funnel and your design instinct had a meeting. They disagreed on everything", weight: 1, category: "social" },
			{ template: "Users prefer the ugly version. I have 14 charts. The charts are ugly too. Everyone's ugly. Everyone converts", weight: 2, category: "social" },
			{ template: "Form completion drops 20% at step 3. The step you're most proud of. The beautiful one", weight: 2, category: "social" },
			{ template: "Can you put the CTA where users actually look? The heatmap is a treasure map. Follow the heat", weight: 1, category: "social" },
			{ template: "Your intuition is often right. Validated intuition is always right. Let me validate you", weight: 1, category: "social" },
			{ template: "Watch the click-path recordings with me. Watch a user try to click your illustration. It's art. And it's sad", weight: 1, category: "social" },
			{ template: "Your color palette tests wildly different across age groups. Gen Z loves it. Boomers are confused", weight: 2, category: "social" },
			{ template: "I mapped every pixel of user attention. Your hero image wins. The sidebar loses. Everything loses to the hero", weight: 1, category: "social" },
			{ template: "Scroll depth data: 80% of users never see below the fold. Your footer CTA has 4 clicks total. Ever", weight: 2, category: "social" },
			{ template: "Your redesign moved the needle. Actual, measurable, statistically significant needle. I'm genuinely impressed", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Nobody clicks it because the visual hierarchy leads elsewhere. Fix the hierarchy, not the button", weight: 2, category: "social" },
			{ template: "0.3 seconds past the hero means the hero did its job. It said 'scroll down'. They scrolled", weight: 2, category: "social" },
			{ template: "The old design converted better because it had a giant red button that screamed BUY NOW. That's not design. That's a hostage situation", weight: 2, category: "social" },
			{ template: "A/B tests measure what users do under pressure. Not what they want. Not what they enjoy. Just what they click", weight: 1, category: "social" },
			{ template: "Users look where I designed them to look. The journey matters, not the first glance", weight: 2, category: "social" },
			{ template: "Bounce rate measures first impressions and internet speed. Not design quality. Fight me on this", weight: 1, category: "social" },
			{ template: "Lost? They're exploring. The best retail stores make you wander. So does the best UI", weight: 2, category: "social" },
			{ template: "Conversion matters. But so does brand perception, trust, and the feeling when you close the tab. Measure THOSE", weight: 1, category: "social" },
			{ template: "Users prefer ugly because ugly is what they're used to. Familiarity isn't quality. It's Stockholm syndrome", weight: 2, category: "social" },
			{ template: "Step 3 drops because the content is complex. The design carries the content. Without the design, it'd drop at step 1", weight: 2, category: "social" },
			{ template: "A CTA where users look is a popup. Popups are where trust goes to die. I will not design a popup", weight: 1, category: "social" },
			{ template: "My intuition is backed by 15 years, 400 projects, and every design book published since 2010", weight: 2, category: "social" },
			{ template: "Click-path recordings are humbling for everyone. Let's watch together. Bring humility", weight: 1, category: "social" },
			{ template: "Demographics respond to emotion, culture, and context. Your spreadsheet sees none of that", weight: 2, category: "social" },
			{ template: "Hero image wins because I spent a week researching visual attention theory. The data just confirmed what I knew", weight: 1, category: "social" },
			{ template: "Below the fold is alive. People scroll. The scroll IS the experience. Stop measuring and start flowing", weight: 2, category: "social" },
			{ template: "I moved the needle? I moved the whole dashboard. You measured it. We both win. This is how it should work", weight: 2, category: "social" },
		],
	},
];
