/**
 * crossover-core.ts — Core cross-domain conversation pairs.
 *
 * Engineering, design, quality, product, operations, and management
 * crossover interactions.
 */

import type { CrossoverPair } from "./crossover-templates.js";

export const CORE_CROSSOVER_PAIRS: readonly CrossoverPair[] = [
	// engineering <-> design
	{
		domainA: "engineering",
		domainB: "design",
		linesA: [
			{ template: "Can you make the animation smoother? Without adding a 200KB library?", weight: 2, category: "social" },
			{ template: "The pixels are off by one. How do I know? Because YOU told me last time", weight: 2, category: "social" },
			{ template: "Is that a custom font? My bundle size just flinched", weight: 1, category: "social" },
			{ template: "I implemented your design. It's close. Squint and tilt your head close", weight: 2, category: "social" },
			{ template: "The CSS for this has more z-index layers than a geological survey", weight: 2, category: "social" },
			{ template: "How attached are you to that box shadow? It costs 4ms per frame", weight: 1, category: "social" },
			{ template: "Your mockup is gorgeous. Safari has decided otherwise", weight: 2, category: "social" },
			{ template: "Has anything you've ever designed been achievable with a single div?", weight: 2, category: "social" },
			{ template: "That gradient has 14 color stops. My GPU is filing a complaint", weight: 1, category: "social" },
			{ template: "I admire your vision. My webpack config does not share my admiration", weight: 2, category: "social" },
			{ template: "Can we use system fonts? My lighthouse score is begging", weight: 1, category: "social" },
			{ template: "Can we move this 2px left? Just kidding. Please never say that to me", weight: 2, category: "social" },
			{ template: "Your hover state requires more state management than the whole app", weight: 2, category: "social" },
			{ template: "I'll need a support group to recover from implementing this layout", weight: 1, category: "social" },
			{ template: "You drew a bezier curve. My CSS would like a word with your pen tool", weight: 2, category: "social" },
			{ template: "What if we used an existing icon? From the icon set? That we already have?", weight: 1, category: "social" },
			{ template: "That parallax scroll was a 5-second demo. It's a 5-day build", weight: 2, category: "social" },
			{ template: "Want to pair on this? I write the code, you tell me it's wrong in real-time", weight: 1, category: "social" },
			{ template: "Your design tokens doc actually saved me a full day. I'll never admit that again", weight: 2, category: "social" },
			{ template: "I built storybook pages for all your components. You owe me lunch", weight: 1, category: "social" },
			{ template: "The skeleton loader flickers at exactly the frequency that causes migraines", weight: 2, category: "social" },
			{ template: "How do you pick colors that fast? I'm still choosing between two grays", weight: 1, category: "social" },
		],
		linesB: [
			{ template: "Can you make the API faster? My loading spinner is getting lonely", weight: 2, category: "social" },
			{ template: "That's not what the mockup looks like. Open Figma. Look. LOOK", weight: 2, category: "social" },
			{ template: "I spent three hours kerning that heading. The 2px stays", weight: 2, category: "social" },
			{ template: "Why does production always look like the mockup's sadder, divorced cousin?", weight: 2, category: "social" },
			{ template: "The spacing is 24px. You used 23. I can feel the asymmetry in my bones", weight: 1, category: "social" },
			{ template: "Just use flexbox. Or grid. Or literally anything besides absolute positioning", weight: 1, category: "social" },
			{ template: "Let me guess, 'it works on Chrome on your specific monitor'?", weight: 2, category: "social" },
			{ template: "Pixel perfect isn't a preference. It's the job. THE job", weight: 1, category: "social" },
			{ template: "You moved the button 2px left. That breaks the 8-point grid. We had a deal", weight: 2, category: "social" },
			{ template: "The font weight is 500. You used 400. They are CATEGORICALLY different", weight: 1, category: "social" },
			{ template: "Why is there a scrollbar? I designed this to be scrollbar-free. It was my vision", weight: 2, category: "social" },
			{ template: "Your implementation has... personality. Wrong personality, but personality", weight: 2, category: "social" },
			{ template: "Did you eyeball the padding? Because my retinas can tell you eyeballed it", weight: 2, category: "social" },
			{ template: "The transition is linear. Linear transitions are what happens when engineers design", weight: 1, category: "social" },
			{ template: "Show me the mobile version. I'll be behind this plant when you're ready", weight: 2, category: "social" },
			{ template: "System fonts? I will quit. I will actually, literally quit", weight: 2, category: "social" },
			{ template: "If the design is hard to build, that means the design is ambitious. You're welcome", weight: 1, category: "social" },
			{ template: "Let's pair on breakpoints. You'll learn. I'll heal from your CSS", weight: 1, category: "social" },
			{ template: "Your storybook is missing hover, focus, active, and disabled states. So... all of them", weight: 2, category: "social" },
			{ template: "The design tokens are alphabetized, documented, and versioned. This is what love looks like", weight: 1, category: "social" },
			{ template: "The shimmer is 2px too tall. I overlaid my mockup on your build. Pixel by pixel", weight: 2, category: "social" },
			{ template: "I dream in Figma auto-layout. Engineers dream in merge conflicts. We're not the same", weight: 2, category: "social" },
		],
	},
	// engineering <-> quality
	{
		domainA: "engineering",
		domainB: "quality",
		linesA: [
			{ template: "Please don't find anything. I need this. I need a clean pass", weight: 2, category: "social" },
			{ template: "I tested it myself this time. Thoroughly. On my machine. In Chrome", weight: 2, category: "social" },
			{ template: "That edge case requires the user to triple-click while holding alt. Nobody does that", weight: 2, category: "social" },
			{ template: "How do you always find the one code path that only exists on Tuesdays?", weight: 1, category: "social" },
			{ template: "It's not a bug, it's... okay I looked at the stack trace. It's a bug", weight: 2, category: "social" },
			{ template: "Can you at least wait until Monday to destroy my confidence?", weight: 1, category: "social" },
			{ template: "I wrote unit tests. 200 of them. They all pass. What do you WANT from me?", weight: 2, category: "social" },
			{ template: "Before you start, yes I know about the null check. No I didn't fix it yet", weight: 1, category: "social" },
			{ template: "Can you find the bugs with kindness this time? Like a gentle audit?", weight: 2, category: "social" },
			{ template: "What's your method? Do you just think 'how would chaos use this feature'?", weight: 1, category: "social" },
			{ template: "That's a staging environment issue. The config is different. I think", weight: 2, category: "social" },
			{ template: "I refactored the whole module since your last pass. Yes, again. Sorry", weight: 1, category: "social" },
			{ template: "The race condition only happens at exactly 10,000 concurrent users. So... never", weight: 2, category: "social" },
			{ template: "Walk me through how you broke it. Slowly. I need to process this", weight: 2, category: "social" },
			{ template: "94% coverage. What more could you... no, don't answer that. I see your face", weight: 1, category: "social" },
			{ template: "Did you actually test this? Or did you have a bad dream about my code?", weight: 2, category: "social" },
			{ template: "What if we write the test cases together BEFORE I code? Novel concept, I know", weight: 1, category: "social" },
			{ template: "I added integration tests AND contract tests. Is that enough to earn a clean pass?", weight: 2, category: "social" },
			{ template: "The flaky test was mine. I own it. I've named it. We have a relationship now", weight: 1, category: "social" },
			{ template: "Your bug report had a mermaid diagram. A DIAGRAM. In a BUG REPORT. I'm in awe", weight: 2, category: "social" },
			{ template: "I bet you a coffee you can't break this endpoint. Double or nothing from last time", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Oh I already found three things. I found them while the page was loading", weight: 2, category: "social" },
			{ template: "It broke on the first click. I didn't even finish sitting down", weight: 2, category: "social" },
			{ template: "Did anyone actually test this? Or did you push to prod and whisper a prayer?", weight: 2, category: "social" },
			{ template: "I have a gift for finding bugs. My therapist calls it 'hypervigilance'. I call it QA", weight: 2, category: "social" },
			{ template: "Your 'done' and my 'done' need couples counseling", weight: 1, category: "social" },
			{ template: "I'm not the villain here. I'm the reason your pager stays quiet at 3AM", weight: 2, category: "social" },
			{ template: "Reopening the ticket. For the third time. We should name this cycle", weight: 1, category: "social" },
			{ template: "94% coverage and the 6% is where all the users live. Funny how that works", weight: 2, category: "social" },
			{ template: "I pressed the back button twice and the page gave me an existential error", weight: 2, category: "social" },
			{ template: "Years of disappointment shaped me into this. You're welcome", weight: 2, category: "social" },
			{ template: "Have you used your own feature? As a regular person? Without dev tools open?", weight: 1, category: "social" },
			{ template: "I test with empathy. For the user who accidentally pastes their password into search", weight: 1, category: "social" },
			{ template: "The bug isn't in the edge case. It's in the happy path. Step one. Of three", weight: 2, category: "social" },
			{ template: "Your unit tests pass. Your feature crashes. The duality of engineering", weight: 2, category: "social" },
			{ template: "I don't click randomly. I think like a user who's angry and in a hurry. Strategically", weight: 1, category: "social" },
			{ template: "Gently? Bugs don't negotiate. And neither do deadlines", weight: 2, category: "social" },
			{ template: "Friday afternoon bugs hit different. They taste like overtime", weight: 1, category: "social" },
			{ template: "Write acceptance tests before code? That's called TDD. You should try it sometime", weight: 1, category: "social" },
			{ template: "Integration tests are step one. My chaos script is step final", weight: 2, category: "social" },
			{ template: "Owning the flaky test? Naming it? That's character development. Genuinely proud", weight: 2, category: "social" },
			{ template: "Mermaid diagrams in bug reports are my art form. The Louvre can wait", weight: 1, category: "social" },
			{ template: "Coffee bet? I broke the endpoint before you finished your sentence. Pay up", weight: 2, category: "social" },
		],
	},
	// product <-> engineering
	{
		domainA: "product",
		domainB: "engineering",
		linesA: [
			{ template: "How long will this take? And before you say 'it depends', I know it depends", weight: 2, category: "social" },
			{ template: "The stakeholders want one small change. They said 'small'. I'm just the messenger", weight: 2, category: "social" },
			{ template: "Can we just add a toggle for that? Everyone loves toggles. Toggles are free right?", weight: 2, category: "social" },
			{ template: "I know I said MVP but what if we also added just ONE more thing to this sprint?", weight: 2, category: "social" },
			{ template: "The user research says we need to pivot. Gently. Like a gentle pivot", weight: 1, category: "social" },
			{ template: "Is it possible to make it more... intuitive? Like, you know, just... better?", weight: 1, category: "social" },
			{ template: "What if we scope it down? Just the core 47 features. That's scoped down from 90", weight: 2, category: "social" },
			{ template: "Can we ship a preview to 1% of users? By Thursday? No, this Thursday", weight: 2, category: "social" },
			{ template: "The competitor just launched something similar. We should talk. Urgently. Now", weight: 1, category: "social" },
			{ template: "Think of it as an experiment. A permanently deployed, customer-facing experiment", weight: 2, category: "social" },
			{ template: "What if we make it configurable? Then everyone gets what they want. Simple right?", weight: 1, category: "social" },
			{ template: "The PRD is only 12 pages. I trimmed it. From 40. You're welcome", weight: 2, category: "social" },
			{ template: "Can you prototype this by end of day? It doesn't have to work, just... look like it works", weight: 2, category: "social" },
			{ template: "I promise this is the last scope change. This sprint. This week. Today. I promise", weight: 2, category: "social" },
			{ template: "What's the technical word for 'make it snappier'? I need it for the exec summary", weight: 1, category: "social" },
			{ template: "Can we reuse the thing from last sprint? Users loved that thing. Which thing? THE thing", weight: 1, category: "social" },
			{ template: "Is 'impossible' your professional impossible or your emotional impossible?", weight: 2, category: "social" },
			{ template: "Sit in on the user session. Watch them struggle. Then tell me the feature isn't needed", weight: 1, category: "social" },
			{ template: "I drew the user flow on a napkin. It has arrows. It's practically a spec", weight: 2, category: "social" },
			{ template: "Our biggest competitor just raised funding. I find that motivating. Do you find that motivating?", weight: 1, category: "social" },
			{ template: "What if we launch to internal users first? Low stakes. Zero consequences. Probably", weight: 2, category: "social" },
			{ template: "I genuinely want to understand the trade-offs. Even the ones you think will scare me", weight: 1, category: "social" },
		],
		linesB: [
			{ template: "Between 2 hours and 2 weeks. I know that's not helpful. It's accurate though", weight: 2, category: "social" },
			{ template: "Define 'small'. In story points. With acceptance criteria. I'll wait", weight: 2, category: "social" },
			{ template: "Sure, right after we finish the 12 toggles that are already broken from last sprint", weight: 2, category: "social" },
			{ template: "That's a new project disguised as a feature request wearing a user story costume", weight: 2, category: "social" },
			{ template: "We can do it fast, or we can do it right. You always pick fast. And then ask why it breaks", weight: 1, category: "social" },
			{ template: "Let me translate 'intuitive' into Jira tickets... okay that's about 14 stories", weight: 1, category: "social" },
			{ template: "The backlog just gained weight. It's now heavier than the codebase", weight: 2, category: "social" },
			{ template: "1% of users at our scale is still enough to set my pager on fire", weight: 1, category: "social" },
			{ template: "That 12-page PRD has 43 assumptions and 11 contradictions. I circled them", weight: 2, category: "social" },
			{ template: "Rough prototype by EOD? Define rough. Because 'compiles' is already generous", weight: 2, category: "social" },
			{ template: "The second kind of impossible. The kind where I know exactly how hard it is", weight: 2, category: "social" },
			{ template: "Configurable means twice the code, triple the bugs, and infinite support tickets", weight: 1, category: "social" },
			{ template: "Last scope change? I'm keeping a spreadsheet. You're at seven. This sprint", weight: 2, category: "social" },
			{ template: "That thing from last sprint took three sprints. But sure, let's reuse the trauma", weight: 2, category: "social" },
			{ template: "'Snappier' translates to 'rewrite the backend'. I checked. Twice", weight: 1, category: "social" },
			{ template: "Experiments have a funny way of becoming permanent features with zero documentation", weight: 1, category: "social" },
			{ template: "The competitor's version crashes on mobile. I cloned it. For research. And comfort", weight: 2, category: "social" },
			{ template: "User sessions are enlightening. I watched someone close the app in frustration. Fun times", weight: 1, category: "social" },
			{ template: "Napkin architecture is how production outages are born. I have the receipts. Literally", weight: 2, category: "social" },
			{ template: "Competitor funding means they'll hire fast and ship bugs faster. We're fine", weight: 2, category: "social" },
			{ template: "Internal launch first? That's the first reasonable scope I've heard all quarter", weight: 1, category: "social" },
			{ template: "Pull up a chair for the trade-off discussion. Bring lunch. And your afternoon", weight: 2, category: "social" },
		],
	},
	// design <-> product
	{
		domainA: "design",
		domainB: "product",
		linesA: [
			{ template: "The mockup is ready. Don't ask me to change the font. The font is final", weight: 2, category: "social" },
			{ template: "I explored five directions. They picked the one I spent 10 minutes on. Classic", weight: 2, category: "social" },
			{ template: "The user flow has 3 steps. It had 3 steps yesterday. It still has 3 steps. Please", weight: 2, category: "social" },
			{ template: "I ran a usability test. Users tried to close the modal by clicking outside. We don't support that. We should", weight: 1, category: "social" },
			{ template: "White space is not empty space. It's the design breathing. Stop suffocating my design", weight: 2, category: "social" },
			{ template: "Every feature you add is another thing the user has to ignore to find what they actually need", weight: 1, category: "social" },
			{ template: "I know you love features. I love users. Users love simplicity. The math is clear", weight: 1, category: "social" },
			{ template: "The design system exists so we don't have this conversation every sprint", weight: 2, category: "social" },
			{ template: "I can make it pop. I can also make it usable. Pick one. Please pick usable", weight: 2, category: "social" },
			{ template: "Users don't read. They scan. I watched twelve people skip your copy in real-time", weight: 1, category: "social" },
			{ template: "Your feature list is a novel. The UI should be a haiku. We're currently at short story", weight: 2, category: "social" },
			{ template: "I hid the complexity so well that you forgot there was complexity. You're welcome", weight: 2, category: "social" },
			{ template: "The best feature is invisible. The worst feature has three tooltips and a tutorial", weight: 1, category: "social" },
			{ template: "Three click paths merged into one drag. Saved users 8 seconds per flow. Thank me later", weight: 2, category: "social" },
			{ template: "Less is more. More is a support ticket. Even more is a churn event", weight: 2, category: "social" },
			{ template: "Did the stakeholders say 'pop' again? I need 10 minutes and a stress ball", weight: 1, category: "social" },
			{ template: "Want to watch the usability test? Watch a user stare at your CTA for 12 seconds and do nothing", weight: 1, category: "social" },
			{ template: "I designed the error state before the happy path. Because errors are where trust lives", weight: 2, category: "social" },
			{ template: "Can we add 'just a small tweak' to the list of banned phrases? Next to 'make it pop'", weight: 2, category: "social" },
			{ template: "Your competitor analysis actually inspired this layout. Don't tell the competitor", weight: 1, category: "social" },
			{ template: "I cut two screens and combined three. The user journey lost 15 seconds. You're welcome", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Can we add just one more thing? A tiny thing. A toggle-shaped thing", weight: 2, category: "social" },
			{ template: "Love it! Genuinely! But can the logo be... more present? More... everywhere?", weight: 2, category: "social" },
			{ template: "What if we combined screens 2 and 7? Users love efficiency. I assume. I haven't asked them", weight: 2, category: "social" },
			{ template: "The execs want it to 'pop'. I told them pop isn't a design term. They said 'make it pop anyway'", weight: 2, category: "social" },
			{ template: "Can you make one version with everything? And one with nothing? I'll show both. Pick neither", weight: 1, category: "social" },
			{ template: "I showed the stakeholders. They had thoughts. Many thoughts. Conflicting thoughts", weight: 1, category: "social" },
			{ template: "Actually, can we go back to version 3? Not last Tuesday. The one from two Tuesdays ago", weight: 2, category: "social" },
			{ template: "The haiku is elegant. But the exec summary needs a paragraph. And a bullet list. And a chart", weight: 2, category: "social" },
			{ template: "Can we A/B test both? I can't decide and I don't want to be the one who decides wrong", weight: 1, category: "social" },
			{ template: "Users in the survey want more options. All the options. Maximum options. I'm as confused as you", weight: 2, category: "social" },
			{ template: "What if simplicity is wrong? What if users secretly want complexity? The data is ambiguous", weight: 1, category: "social" },
			{ template: "The white space is lovely. It would be even lovelier with a promotional banner", weight: 2, category: "social" },
			{ template: "I trust the design completely. But what if we added a tooltip? Just to be safe. Just one. Maybe two", weight: 1, category: "social" },
			{ template: "Your merged flow is elegant. Legal needs a disclaimer. Compliance needs a checkbox. Sorry", weight: 2, category: "social" },
			{ template: "Pop. They said pop. Again. I tried to stop them. I failed. I'm sorry", weight: 2, category: "social" },
			{ template: "The competitor has 6 tabs and a sidebar. We have 2 tabs. Are we minimalist or just behind?", weight: 1, category: "social" },
			{ template: "Design system is sacred. But can we make one exception? Just this once? For the CEO?", weight: 2, category: "social" },
			{ template: "The usability test was eye-opening. One user tried to drag the logo. Into the search bar", weight: 1, category: "social" },
			{ template: "Error states matter. But the happy path needs to... you know. Pop. I hate myself for saying it", weight: 2, category: "social" },
			{ template: "Small tweak is a love language. My love language. For your designs. Accept it", weight: 2, category: "social" },
			{ template: "Your layout inspired the pitch deck. The investors gave us funding. You basically raised the round", weight: 1, category: "social" },
			{ template: "Two fewer screens was inspired. Now add one back. A small one. A screen-shaped screen", weight: 2, category: "social" },
		],
	},
	// operations <-> engineering
	{
		domainA: "operations",
		domainB: "engineering",
		linesA: [
			{ template: "Who changed the config? I have timestamps. And feelings", weight: 2, category: "social" },
			{ template: "The server is weeping. Actual memory tears. What did you deploy?", weight: 2, category: "social" },
			{ template: "Your service is using 3x the memory you estimated. We estimated together. I was there", weight: 2, category: "social" },
			{ template: "I see you deployed at 4:58 PM on a Friday. I see that with my own two on-call eyes", weight: 2, category: "social" },
			{ template: "The logs say 'this should never happen'. Line 47. It happened at line 48", weight: 1, category: "social" },
			{ template: "Can you add observability? Any observability. A print statement. Anything", weight: 1, category: "social" },
			{ template: "Your service restarted 47 times last night. Each time it took my blood pressure with it", weight: 2, category: "social" },
			{ template: "The disk is full of your logs. Your service wrote a 200GB autobiography overnight", weight: 2, category: "social" },
			{ template: "Rollback or fix forward? You have 30 seconds. The SLA is staring at us both", weight: 1, category: "social" },
			{ template: "Your Docker image is 4 GB. I've seen apartments smaller than your container", weight: 2, category: "social" },
			{ template: "The load balancer is confused by your health check. It returns 200 during a crash. How?", weight: 1, category: "social" },
			{ template: "I got paged at 3 AM. My spouse sends their regards. They're not happy", weight: 2, category: "social" },
			{ template: "Your 'temporary' workaround from 6 months ago now has its own monitoring dashboard", weight: 2, category: "social" },
			{ template: "CPU at 99%. Your service is either mining crypto or having an existential crisis", weight: 1, category: "social" },
			{ template: "Next deploy goes through staging. And canary. And my personal approval. Non-negotiable", weight: 1, category: "social" },
			{ template: "Your retry logic is DDoSing our own database. We're our own worst attacker. Congratulations", weight: 2, category: "social" },
			{ template: "Let's do the incident timeline together. I'll bring the logs, you bring the excuses", weight: 1, category: "social" },
			{ template: "Your env vars have a typo. DATABASE_PASWORD. The S is not optional", weight: 2, category: "social" },
			{ template: "Teach me your GC tuning. I want to understand why it pauses for 30 seconds", weight: 1, category: "social" },
			{ template: "The Grafana dashboard went red before your PR finished merging. New speed record", weight: 2, category: "social" },
			{ template: "Who hardcoded a production URL in the test suite? The test suite that runs in CI? That CI?", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Wasn't me. Checks git blame. Pauses. Closes terminal slowly. It was me", weight: 2, category: "social" },
			{ template: "The config change was supposed to be harmless. The word 'supposed' is doing heavy lifting", weight: 2, category: "social" },
			{ template: "It works in staging! Staging and I are very close. Production is a different relationship", weight: 2, category: "social" },
			{ template: "Memory leak? That's aggressive caching. The cache just... never stops caching", weight: 2, category: "social" },
			{ template: "Define 'outage'. The health check returns 200. The app returns nothing. But the health check is fine", weight: 1, category: "social" },
			{ template: "I'll add metrics right after I figure out which of the three fires to put out first", weight: 1, category: "social" },
			{ template: "47 restarts sounds bad but it recovered every time. That's resilience. Write that down", weight: 2, category: "social" },
			{ template: "The logs are verbose for debugging purposes. The 200GB is... comprehensive debugging", weight: 1, category: "social" },
			{ template: "Fix forward. Always fix forward. Rolling back is admitting I made a mistake. Which I didn't. Mostly", weight: 2, category: "social" },
			{ template: "4 GB is lean for what it does. You should see the node_modules folder", weight: 2, category: "social" },
			{ template: "3 AM pages build character. Tell your spouse I said thank you for their service", weight: 2, category: "social" },
			{ template: "That workaround became load-bearing infrastructure. It has dependencies now. It has fans", weight: 1, category: "social" },
			{ template: "The CPU is working hard because the problem is hard. Correlation. Not my fault", weight: 2, category: "social" },
			{ template: "Staging is production's younger sibling. Same DNA, different upbringing", weight: 1, category: "social" },
			{ template: "The retry logic is enthusiastic. It believes in second chances. And third. And fortieth", weight: 2, category: "social" },
			{ template: "I'll add a circuit breaker. Right after the circuit stops breaking. Chicken and egg", weight: 1, category: "social" },
			{ template: "Incident timeline? Chapter 1: In the beginning, there was a PR that looked harmless", weight: 1, category: "social" },
			{ template: "The typo was a canary deployment. Testing whether ops reads env vars. You passed", weight: 2, category: "social" },
			{ template: "GC tuning is an art. My art causes 30-second pauses. It's abstract art", weight: 1, category: "social" },
			{ template: "The alert is sensitive. Like a smoke detector near a kitchen. Technically correct", weight: 2, category: "social" },
			{ template: "That hardcoded URL is an undocumented feature. Don't touch it. I mean it. Please", weight: 2, category: "social" },
		],
	},
	// management <-> engineering
	{
		domainA: "management",
		domainB: "engineering",
		linesA: [
			{ template: "Just checking in on the timeline. Casually. No pressure. Unless there should be pressure", weight: 2, category: "social" },
			{ template: "Can we get an ETA for the leadership sync? They're asking. Hourly. I'm not exaggerating", weight: 2, category: "social" },
			{ template: "The board wants a demo next week. Not a good demo, just a demo. Bar is low. Thoughts?", weight: 2, category: "social" },
			{ template: "How would you explain this to the board? Pretend they don't know what an API is. Because they don't", weight: 1, category: "social" },
			{ template: "Can you put the progress in a slide deck? With green arrows. Upward green arrows", weight: 1, category: "social" },
			{ template: "What's the risk level? In traffic light colors. And don't say red", weight: 2, category: "social" },
			{ template: "The CEO read a blog post about AI. Now we need an AI strategy. By Wednesday", weight: 2, category: "social" },
			{ template: "Can we call the refactoring 'platform modernization'? For the board deck", weight: 2, category: "social" },
			{ template: "How many sprints until it looks impressive on a slide? Visual impressiveness. Not code quality", weight: 1, category: "social" },
			{ template: "The other team shipped in half the time. With half the people. Their manager won't shut up about it", weight: 2, category: "social" },
			{ template: "I need a one-liner for the all-hands. Something inspiring. No acronyms. Under 10 words", weight: 1, category: "social" },
			{ template: "Can we double the team to go twice as fast? Before you quote Brooks's Law, hear me out", weight: 2, category: "social" },
			{ template: "What's 'technical debt' and why does it keep showing up in sprint reviews like a recurring villain?", weight: 2, category: "social" },
			{ template: "Budget review Thursday. I need wins. Anything. Even small wins. Especially small wins", weight: 1, category: "social" },
			{ template: "Is there a way to measure developer happiness that I can put on a dashboard? For HR", weight: 1, category: "social" },
			{ template: "I told the client it ships next month. Before you react, which month is negotiable", weight: 2, category: "social" },
			{ template: "Want to shadow the standup? It's fifteen minutes. Usually. In theory", weight: 1, category: "social" },
			{ template: "These 5 priorities are all P0. I know that's not how priorities work. The VP disagrees", weight: 2, category: "social" },
			{ template: "The client loved the prototype so much they want everything. All of it. Yesterday", weight: 2, category: "social" },
			{ template: "I genuinely find your architecture diagrams fascinating. I don't understand them. But fascinating", weight: 1, category: "social" },
			{ template: "How do I explain a database index to the board? In a way that justifies the invoice", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Still the same timeline as yesterday. And the day before. The timeline hasn't changed since Tuesday", weight: 2, category: "social" },
			{ template: "The ETA is an estimate. The E is doing all the work in that acronym", weight: 2, category: "social" },
			{ template: "Demo-ready is makeup on a prototype. Production-ready is surgery. Different timelines", weight: 2, category: "social" },
			{ template: "I'll try to explain it simply. Last time I used a car analogy. They asked about the car", weight: 2, category: "social" },
			{ template: "Can I just show them the working code? No? Slides it is. With clip art, probably", weight: 1, category: "social" },
			{ template: "It's yellow. It has been yellow. It will be yellow. Yellow is our steady state", weight: 2, category: "social" },
			{ template: "Asking every hour doesn't make the code compile faster. It makes my eye twitch faster", weight: 1, category: "social" },
			{ template: "The CEO's blog post is from 2019 and the company that wrote it went bankrupt. But sure, AI strategy", weight: 2, category: "social" },
			{ template: "Refactoring IS the sexy part. Without it, the site crashes. Crashes are not sexy", weight: 1, category: "social" },
			{ template: "Adding people to a late project makes it later. That's called Brooks's Law. It has a name because it's that true", weight: 2, category: "social" },
			{ template: "Technical debt is why the site didn't crash during the board demo. Frame it that way", weight: 2, category: "social" },
			{ template: "The other team shipped fast. I've seen their codebase. It looks like a crime scene", weight: 2, category: "social" },
			{ template: "One-liner for all-hands: 'Nothing caught fire this quarter.' Under 10 words. You're welcome", weight: 1, category: "social" },
			{ template: "Next month? Sure. Which of the next twelve months works for you?", weight: 2, category: "social" },
			{ template: "Developer happiness metric: count the sighs per standup. Lower is better. We're high", weight: 1, category: "social" },
			{ template: "Good news: it compiles. Bad news: we should talk. In private. With snacks", weight: 2, category: "social" },
			{ template: "Impressive is 3 sprints. Demo-able is 1. Slide-deck-able is right now. Pick your reality", weight: 1, category: "social" },
			{ template: "Shadow the standup? Sure. It's fifteen minutes that feel like forty. Bring coffee", weight: 1, category: "social" },
			{ template: "Five P0s means zero P0s. Tell the VP I said that. Actually, don't tell the VP I said anything", weight: 2, category: "social" },
			{ template: "Client wants everything from the prototype? That prototype was held together with hope. Literal hope", weight: 2, category: "social" },
			{ template: "Architecture diagrams? You'll love my whiteboard. It has arrows going in directions that concern me", weight: 1, category: "social" },
			{ template: "Database index makes things fast. Board translation: it saves $50K per month. That usually works", weight: 2, category: "social" },
		],
	},
	// quality <-> product
	{
		domainA: "quality",
		domainB: "product",
		linesA: [
			{ template: "Found 12 bugs. Before lunch. On one page. Want me to keep going?", weight: 2, category: "social" },
			{ template: "The happy path works. Every other path leads to a 500 error and sadness", weight: 2, category: "social" },
			{ template: "Requirement 3 contradicts requirement 7. And requirement 7 contradicts itself", weight: 2, category: "social" },
			{ template: "Users will absolutely click that. They'll click it twice. And it'll crash both times", weight: 1, category: "social" },
			{ template: "I need acceptance criteria with more detail than 'it should work correctly'", weight: 2, category: "social" },
			{ template: "Good news: testing is complete. Bad news: I have a spreadsheet for you", weight: 2, category: "social" },
			{ template: "The spec says 'delightful experience'. The reality says 'unexpected token at line 1'", weight: 1, category: "social" },
			{ template: "Users found a workaround for your workaround for the original bug. We've gone recursive", weight: 2, category: "social" },
			{ template: "Can we define 'done'? Because right now 'done' means 'mostly broken in a shippable way'", weight: 1, category: "social" },
			{ template: "The regression list is now longer than the feature list. By a factor of three", weight: 2, category: "social" },
			{ template: "Ship now, patch tomorrow, hotfix Thursday, rollback Friday. Sound about right?", weight: 1, category: "social" },
			{ template: "I tested as your persona. She tried to sign up. She's still trying. It's been 20 minutes", weight: 2, category: "social" },
			{ template: "Edge case? 40% of users hit this flow. That's not an edge, that's a boulevard", weight: 2, category: "social" },
			{ template: "The error message says 'oops'. Just... 'oops'. That's the whole message", weight: 1, category: "social" },
			{ template: "Three acceptance criteria. Three contradictions. Zero working states. Pick your favorite", weight: 2, category: "social" },
			{ template: "Your MVP has a bug-to-feature ratio that I'm not comfortable sharing in standup", weight: 2, category: "social" },
			{ template: "Let's review the test matrix together. Before launch. Please. I'm begging", weight: 1, category: "social" },
			{ template: "I tested the onboarding flow. Step 4 is where users go to question their life choices", weight: 2, category: "social" },
			{ template: "Your 'edge case' is the default browser on the most popular phone. So. Not edgy", weight: 2, category: "social" },
			{ template: "I read the PRD. It assumes the server is up, the API is fast, and users are patient. Bold", weight: 1, category: "social" },
			{ template: "The accessibility audit found things. Real things. Things that affect real people", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Can we rebrand those as 'known issues' and ship anyway?", weight: 2, category: "social" },
			{ template: "How many are critical? And can we redefine critical? Downward?", weight: 2, category: "social" },
			{ template: "Can we ship and fix later? That's literally what patches are for", weight: 2, category: "social" },
			{ template: "The deadline is set in concrete. The quality bar is set in... something softer", weight: 1, category: "social" },
			{ template: "Nobody will use it that way. Our analytics will prove me right. Eventually", weight: 2, category: "social" },
			{ template: "Let's triage. What can users live with? What can I tell the board they can live with?", weight: 1, category: "social" },
			{ template: "Seamless was the pitch. 'Mostly works' is the delivery. We iterate. That's the process", weight: 2, category: "social" },
			{ template: "The workaround is creative. The user is resourceful. Ship it", weight: 2, category: "social" },
			{ template: "Done means shipped. Iterate means we fix it when customers yell. That's agile", weight: 1, category: "social" },
			{ template: "Which bugs are below the threshold of user outrage? Those stay", weight: 1, category: "social" },
			{ template: "The persona is aspirational. Real users mash buttons and forgive. Usually", weight: 2, category: "social" },
			{ template: "Regression is strong. How about 'unexpected feature evolution'?", weight: 2, category: "social" },
			{ template: "We'll fix the error message in v2. 'Oops' is charmingly honest actually", weight: 2, category: "social" },
			{ template: "Two out of three criteria is a B+. In some grading systems. Probably. Ship it", weight: 1, category: "social" },
			{ template: "The bug count is high but customer excitement is higher. Vibes over defects", weight: 2, category: "social" },
			{ template: "Patching tomorrow is future-us's problem. Present-us ships features", weight: 1, category: "social" },
			{ template: "Test matrix review? I'll be there. With coffee, hope, and a very flexible definition of 'pass'", weight: 1, category: "social" },
			{ template: "Step 4 is the character-building step. Users emerge stronger. Or they leave. Either way, data", weight: 2, category: "social" },
			{ template: "30% of users? That's the minority. The other 70% love it. Probably. We should check", weight: 2, category: "social" },
			{ template: "The PRD assumes success because I believe in this team. Despite the evidence", weight: 1, category: "social" },
			{ template: "Accessibility findings? Absolutely. Roadmap slot? Q3. Maybe Q4. We'll get there", weight: 2, category: "social" },
		],
	},
];
