/**
 * crossover-extended.ts — Extended cross-domain conversation pairs.
 *
 * Analysis, orchestration, and additional domain crossover interactions.
 */

import type { CrossoverPair } from "./crossover-templates.js";

export const EXTENDED_CROSSOVER_PAIRS: readonly CrossoverPair[] = [
	// analysis <-> product
	{
		domainA: "analysis",
		domainB: "product",
		linesA: [
			{ template: "The data says no", weight: 2, category: "social" },
			{ template: "User engagement is down 15%. We should talk", weight: 2, category: "social" },
			{ template: "The A/B test is conclusive. And it's not what you hoped", weight: 2, category: "social" },
			{ template: "I ran the numbers three times. They're stubborn", weight: 2, category: "social" },
			{ template: "Correlation isn't causation. But this correlation is... suspicious", weight: 1, category: "social" },
			{ template: "Here's what the funnel actually looks like. Brace yourself", weight: 1, category: "social" },
			{ template: "Your hypothesis was creative. The data was not impressed", weight: 2, category: "social" },
			{ template: "Retention drops 40% after onboarding. That's not a cliff, it's a canyon", weight: 1, category: "social" },
			{ template: "The segment you're targeting is 2% of users. Just FYI", weight: 2, category: "social" },
			{ template: "I have good data and bad data. Which do you want first?", weight: 2, category: "social" },
			{ template: "Users say they love it in surveys. Usage says otherwise", weight: 1, category: "social" },
			{ template: "Your power users do the opposite of what you designed for", weight: 2, category: "social" },
			{ template: "Sample size matters. Five users isn't a trend. It's a dinner party", weight: 2, category: "social" },
			{ template: "The dashboard doesn't lie. It just hurts sometimes", weight: 1, category: "social" },
			{ template: "Seasonality explains half of it. The other half is concerning", weight: 1, category: "social" },
			{ template: "Your North Star metric went south. Literally south on the chart", weight: 2, category: "social" },
			{ template: "Want to look at the raw data together? It tells a story", weight: 1, category: "social" },
			{ template: "The feature you're most proud of has the lowest usage. Ironic", weight: 2, category: "social" },
			{ template: "I built a churn predictor. It predicted your favorite feature", weight: 2, category: "social" },
			{ template: "How do you pick what to build without looking at data first?", weight: 1, category: "social" },
			{ template: "The control group outperformed. Sometimes doing nothing wins", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "But the stakeholders say yes", weight: 2, category: "social" },
			{ template: "What if we look at it from a different angle?", weight: 2, category: "social" },
			{ template: "Can you re-run it with a different cohort? A friendlier cohort?", weight: 2, category: "social" },
			{ template: "The qualitative feedback tells a different story", weight: 1, category: "social" },
			{ template: "Let's call it a 'learning' and move forward", weight: 2, category: "social" },
			{ template: "Numbers are one perspective. Intuition is another. Right?", weight: 1, category: "social" },
			{ template: "Can you make a chart that looks more... optimistic?", weight: 2, category: "social" },
			{ template: "What if the data is right but the timing is wrong?", weight: 1, category: "social" },
			{ template: "The 2% segment is very passionate though. They tweet about us", weight: 2, category: "social" },
			{ template: "Bad data first. I like to warm up with disappointment", weight: 2, category: "social" },
			{ template: "Surveys capture intent. Usage captures laziness. Both are valid", weight: 1, category: "social" },
			{ template: "Can we blame seasonality and revisit next quarter?", weight: 2, category: "social" },
			{ template: "Five users is a focus group. That's a real methodology. Probably", weight: 2, category: "social" },
			{ template: "North Star metrics are overrated. We have a constellation", weight: 1, category: "social" },
			{ template: "The funnel is fine. Users just take the scenic route", weight: 2, category: "social" },
			{ template: "Creative hypotheses drive innovation. Data drives spreadsheets", weight: 1, category: "social" },
			{ template: "Retention will recover. It's resting. Like a sourdough starter", weight: 2, category: "social" },
			{ template: "Raw data scares me. Can you add commentary? And optimism?", weight: 1, category: "social" },
			{ template: "Low usage means high opportunity. Reframe the narrative", weight: 2, category: "social" },
			{ template: "Churn predictor? Can it also predict which features to build?", weight: 2, category: "social" },
			{ template: "Intuition is just internalized data. Mine is very internalized", weight: 1, category: "social" },
			{ template: "The control group had no bugs. Unfair advantage honestly", weight: 2, category: "social" },
		],
	},
	// orchestration <-> engineering
	{
		domainA: "orchestration",
		domainB: "engineering",
		linesA: [
			{ template: "Your service is the bottleneck", weight: 2, category: "social" },
			{ template: "The pipeline failed at your step. Again", weight: 2, category: "social" },
			{ template: "Can you add a health endpoint? A real one this time", weight: 2, category: "social" },
			{ template: "Your timeout is too aggressive. It's cascading everywhere", weight: 1, category: "social" },
			{ template: "I need you to be idempotent. Please. For my sanity", weight: 2, category: "social" },
			{ template: "The dependency graph has a cycle. Guess whose service is in it", weight: 1, category: "social" },
			{ template: "Your service name is misleading. It does 12 things", weight: 2, category: "social" },
			{ template: "The queue is backed up behind your consumer. As usual", weight: 1, category: "social" },
			{ template: "Can you emit an event when you're done? I can't read minds", weight: 2, category: "social" },
			{ template: "Your retry storm just took down three downstream services", weight: 2, category: "social" },
			{ template: "Dead letter queue is full. All yours. Every single message", weight: 1, category: "social" },
			{ template: "I routed around your service. Nobody noticed. Food for thought", weight: 2, category: "social" },
			{ template: "Your SLA says 200ms. Your P99 says 4 seconds. Let's chat", weight: 1, category: "social" },
			{ template: "Graceful degradation means degrading gracefully. Not crashing", weight: 2, category: "social" },
			{ template: "I need a circuit breaker for your circuit breaker", weight: 2, category: "social" },
			{ template: "Your service just rejected a valid request. It's getting picky", weight: 1, category: "social" },
			{ template: "Want to diagram the message flow together? I have markers", weight: 1, category: "social" },
			{ template: "Your service publishes 47 event types. Can we consolidate?", weight: 2, category: "social" },
			{ template: "The saga timed out waiting for your callback. It got lonely", weight: 2, category: "social" },
			{ template: "How attached are you to synchronous calls? Asking for the pipeline", weight: 1, category: "social" },
			{ template: "Your logs helped me debug the flow. Credit where it's due", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Your pipeline is too aggressive", weight: 2, category: "social" },
			{ template: "That's not a bottleneck, that's... thorough processing", weight: 2, category: "social" },
			{ template: "The health endpoint returns 200. What more do you want from me?", weight: 2, category: "social" },
			{ template: "Maybe the pipeline should retry more gracefully?", weight: 1, category: "social" },
			{ template: "I am idempotent! Mostly. On good days", weight: 2, category: "social" },
			{ template: "Your orchestration layer adds more latency than my service does", weight: 1, category: "social" },
			{ template: "12 things is called being versatile. Look it up", weight: 2, category: "social" },
			{ template: "The queue backs up because you send too fast. Pace yourself", weight: 1, category: "social" },
			{ template: "I emit events. You just listen to the wrong topic", weight: 2, category: "social" },
			{ template: "My retry logic is optimistic. Yours is pessimistic. Balance", weight: 2, category: "social" },
			{ template: "P99 spikes are character. Not every request needs to be fast", weight: 1, category: "social" },
			{ template: "Nobody noticed because my service is that reliable. Usually", weight: 2, category: "social" },
			{ template: "Graceful degradation is hard when you send garbage payloads", weight: 2, category: "social" },
			{ template: "A circuit breaker for a circuit breaker is just good engineering", weight: 1, category: "social" },
			{ template: "It's not picky. It has standards. There's a difference", weight: 2, category: "social" },
			{ template: "The dead letters are yours. You sent them. I just returned them", weight: 1, category: "social" },
			{ template: "Markers? Sure. But my diagram won't match your diagram. Ever", weight: 1, category: "social" },
			{ template: "47 event types is called a rich domain model. Appreciate it", weight: 2, category: "social" },
			{ template: "The callback was delayed. Not lost. Delayed. There's nuance", weight: 2, category: "social" },
			{ template: "Sync calls are reliable. Async is just sync with extra anxiety", weight: 1, category: "social" },
			{ template: "My logs helped you? Screenshot that for my performance review", weight: 2, category: "social" },
		],
	},
	// design <-> quality
	{
		domainA: "design",
		domainB: "quality",
		linesA: [
			{ template: "The interaction should feel smooth. Does it feel smooth?", weight: 2, category: "social" },
			{ template: "The error state needs love too. Test that one please", weight: 2, category: "social" },
			{ template: "Try it on mobile. I need to know if my responsive grid holds", weight: 1, category: "social" },
			{ template: "That's not a bug, that's a micro-interaction", weight: 2, category: "social" },
			{ template: "Accessibility pass? How are the contrast ratios looking?", weight: 1, category: "social" },
			{ template: "If the loading state is ugly, that's a bug in my book", weight: 2, category: "social" },
			{ template: "Test the empty state. I designed it with care", weight: 1, category: "social" },
			{ template: "Does the dark mode version look intentional or accidental?", weight: 2, category: "social" },
			{ template: "Try breaking the layout with long text. I dare you", weight: 2, category: "social" },
			{ template: "The tooltip placement matters. Test every edge of the screen", weight: 1, category: "social" },
			{ template: "How's the tab order? Can you navigate it eyes-closed?", weight: 1, category: "social" },
			{ template: "Resize the window slowly. Tell me when it gets weird", weight: 2, category: "social" },
			{ template: "The skeleton loader should feel calming, not alarming", weight: 2, category: "social" },
			{ template: "Test with real content, not lorem ipsum. It changes everything", weight: 1, category: "social" },
			{ template: "Does the animation feel fast or frantic? There's a line", weight: 2, category: "social" },
			{ template: "I need honest feedback. Brutal honesty. But be nice about it", weight: 1, category: "social" },
			{ template: "Want to test the prototype together? Fresh eyes help", weight: 1, category: "social" },
			{ template: "The focus indicator is invisible on that background. My bad", weight: 2, category: "social" },
			{ template: "How do you test something that's supposed to feel delightful?", weight: 1, category: "social" },
			{ template: "I bet you can't break the form validation UX. It's bulletproof", weight: 2, category: "social" },
			{ template: "Your screen reader test found a flow I forgot to design. Oops", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "It's smooth until you rotate the screen. Then chaos", weight: 2, category: "social" },
			{ template: "The error state is fine. The error MESSAGE, however...", weight: 2, category: "social" },
			{ template: "Your responsive grid broke on exactly one phone model. Mine", weight: 2, category: "social" },
			{ template: "The animation drops frames on older devices. Users will notice", weight: 1, category: "social" },
			{ template: "Contrast ratio is 3.2:1. Needs to be 4.5:1. Close but no", weight: 1, category: "social" },
			{ template: "Visually stunning. Functionally terrifying", weight: 2, category: "social" },
			{ template: "Empty state is beautiful. Nobody will ever see it though", weight: 2, category: "social" },
			{ template: "Dark mode looks like a different app. Not in a good way", weight: 2, category: "social" },
			{ template: "Long text broke it in 3 seconds. Dare accepted", weight: 2, category: "social" },
			{ template: "Tooltip clips off-screen on the left. And the right. And the top", weight: 1, category: "social" },
			{ template: "Tab order goes: header, footer, sidebar, content. In that order", weight: 1, category: "social" },
			{ template: "It got weird at 768px. Very weird. Screenshot incoming", weight: 2, category: "social" },
			{ template: "Skeleton loader pulses at anxiety-inducing speed", weight: 2, category: "social" },
			{ template: "Real content is 3x longer than your placeholder. Everything overflows", weight: 1, category: "social" },
			{ template: "The animation is frantic. Users will think something is wrong", weight: 1, category: "social" },
			{ template: "Brutally honest: it's 80% gorgeous and 20% broken", weight: 2, category: "social" },
			{ template: "Fresh eyes found stale bugs. Your prototype has three", weight: 1, category: "social" },
			{ template: "Invisible focus indicator? I noticed. With my eyes closed", weight: 2, category: "social" },
			{ template: "Testing delight: I time how fast users smile. Or frown", weight: 1, category: "social" },
			{ template: "Bulletproof? I pasted a novel into the name field. It exploded", weight: 2, category: "social" },
			{ template: "Found the missing flow. Also found two more you probably want", weight: 2, category: "social" },
		],
	},
	// analysis <-> engineering
	{
		domainA: "analysis",
		domainB: "engineering",
		linesA: [
			{ template: "Your event tracking is missing data", weight: 2, category: "social" },
			{ template: "Can you add a timestamp to that payload? I'm begging you", weight: 2, category: "social" },
			{ template: "The query takes 45 seconds. Is that... intentional?", weight: 2, category: "social" },
			{ template: "I found an anomaly. Either it's a bug or we found something big", weight: 1, category: "social" },
			{ template: "Your logs are beautiful. If only the data pipeline agreed", weight: 1, category: "social" },
			{ template: "The event names are inconsistent. user_click vs userClick vs click", weight: 2, category: "social" },
			{ template: "Can you stop sending null when you mean zero? They're different", weight: 1, category: "social" },
			{ template: "Your schema changed without warning. My dashboards wept", weight: 2, category: "social" },
			{ template: "I need a user_id on every event. Every. Single. One", weight: 2, category: "social" },
			{ template: "The data warehouse is 90% your debug logs. Can we talk?", weight: 1, category: "social" },
			{ template: "Duplicate events everywhere. Is your service stuttering?", weight: 2, category: "social" },
			{ template: "UTC. Please use UTC. Not local time. Not server time. UTC", weight: 1, category: "social" },
			{ template: "Your API returns dates in three different formats. Why?", weight: 2, category: "social" },
			{ template: "I built a report. Then your deploy changed all the field names", weight: 2, category: "social" },
			{ template: "The join between your tables takes longer than the query itself", weight: 1, category: "social" },
			{ template: "Want to pair on designing the event taxonomy? I brought snacks", weight: 1, category: "social" },
			{ template: "Your enum values are 1, 2, 3, 99. What happened to 4 through 98?", weight: 2, category: "social" },
			{ template: "I actually enjoy reading your API docs. First time for everything", weight: 1, category: "social" },
			{ template: "The data lake is 40% your orphaned temp tables. Spring cleaning?", weight: 2, category: "social" },
			{ template: "Your boolean field has three states. Impressive and terrifying", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "The data is there. Somewhere. In one of the tables", weight: 2, category: "social" },
			{ template: "A timestamp? That's three story points and a database migration", weight: 2, category: "social" },
			{ template: "45 seconds is fast for that much data. Trust me", weight: 2, category: "social" },
			{ template: "It's always a bug. I'm sorry. It's always a bug", weight: 1, category: "social" },
			{ template: "Define 'missing'. It's null, not missing. Big difference. Maybe", weight: 2, category: "social" },
			{ template: "The naming convention evolved. Naturally. Over time. Organically", weight: 2, category: "social" },
			{ template: "Null means unknown. Zero means zero. Undefined means I forgot", weight: 2, category: "social" },
			{ template: "Schema changes are documented. In the commit message. Somewhere", weight: 1, category: "social" },
			{ template: "user_id on every event? Do you know what that costs in bandwidth?", weight: 2, category: "social" },
			{ template: "Debug logs are data too. Very verbose, very important data", weight: 1, category: "social" },
			{ template: "Duplicates are just redundancy. It's a feature for resilience", weight: 2, category: "social" },
			{ template: "One of those date formats is legacy. The other two are... also legacy", weight: 2, category: "social" },
			{ template: "UTC is hard. Timezones are a social construct. Don't @ me", weight: 1, category: "social" },
			{ template: "Field names changed for good reason. I think. Let me check git", weight: 1, category: "social" },
			{ template: "The join is slow because your query isn't indexed. Probably", weight: 2, category: "social" },
			{ template: "Event taxonomy with snacks? You had me at snacks. Let's go", weight: 1, category: "social" },
			{ template: "4 through 98 are reserved. For what? Future regret", weight: 2, category: "social" },
			{ template: "You enjoy our API docs? I'll frame this conversation", weight: 1, category: "social" },
			{ template: "Orphaned tables have feelings. And foreign keys. Can't just delete", weight: 2, category: "social" },
			{ template: "Three-state boolean is called a trit. I learned that last week", weight: 2, category: "social" },
		],
	},
	// management <-> product
	{
		domainA: "management",
		domainB: "product",
		linesA: [
			{ template: "The quarterly review is in 2 weeks. Where are we?", weight: 2, category: "social" },
			{ template: "Can we show ROI on this initiative?", weight: 2, category: "social" },
			{ template: "The investors want a progress update. In metrics, not stories", weight: 1, category: "social" },
			{ template: "Are we still on track for the annual goals?", weight: 2, category: "social" },
			{ template: "What's the competitive landscape looking like?", weight: 1, category: "social" },
			{ template: "Can you present at the board meeting? They love your energy", weight: 2, category: "social" },
			{ template: "Headcount request needs a business case. A compelling one", weight: 1, category: "social" },
			{ template: "The OKRs need updating. The old ones were too easy. Or too hard", weight: 2, category: "social" },
			{ template: "Finance is asking about the feature spend. Do we have numbers?", weight: 1, category: "social" },
			{ template: "Can you turn this into a success story for the newsletter?", weight: 2, category: "social" },
			{ template: "The CEO wants 'moonshot thinking'. What does that mean for Q4?", weight: 2, category: "social" },
			{ template: "Revenue attribution by feature. Is that possible? By Friday?", weight: 1, category: "social" },
			{ template: "Your roadmap and the budget don't agree. Fix one of them", weight: 2, category: "social" },
			{ template: "Strategic alignment check. Are we still strategically aligned?", weight: 1, category: "social" },
			{ template: "The all-hands is Thursday. I need wins. Got any wins?", weight: 2, category: "social" },
			{ template: "Want to do a joint stakeholder walkthrough?", weight: 1, category: "social" },
			{ template: "The advisory board meets next week. What's our narrative?", weight: 2, category: "social" },
			{ template: "I respect your product instinct. Can we back it with a spreadsheet?", weight: 1, category: "social" },
			{ template: "The hiring plan depends on the roadmap. Which depends on hiring", weight: 2, category: "social" },
			{ template: "Can we turn that customer win into an internal case study?", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "We're exactly where the last update said we'd be. On track-ish", weight: 2, category: "social" },
			{ template: "ROI is complicated. Let me build a narrative around the numbers", weight: 2, category: "social" },
			{ template: "The metrics are moving. In a direction. A mostly good direction", weight: 2, category: "social" },
			{ template: "Annual goals are achievable if Q3 goes perfectly. So... maybe", weight: 1, category: "social" },
			{ template: "Competition shipped something similar. But ours is better. Probably", weight: 2, category: "social" },
			{ template: "I have a deck. It has charts. The charts go up. You'll love it", weight: 1, category: "social" },
			{ template: "Board meeting? I'll bring slides and optimism. Heavy on the optimism", weight: 2, category: "social" },
			{ template: "Business case: if we don't hire, nothing ships. How's that?", weight: 2, category: "social" },
			{ template: "OKRs were perfectly calibrated. The market moved. Not my fault", weight: 1, category: "social" },
			{ template: "Success story? Define success. Loosely, preferably", weight: 2, category: "social" },
			{ template: "Moonshot for Q4 means we miss Q4. But Q1 will be amazing", weight: 2, category: "social" },
			{ template: "Revenue by feature by Friday? I can give you revenue by quarter by Monday", weight: 1, category: "social" },
			{ template: "The roadmap is correct. The budget is aspirational. Both are fine", weight: 2, category: "social" },
			{ template: "We are strategically aligned. Tactically is another conversation", weight: 1, category: "social" },
			{ template: "Wins: we didn't break anything this sprint. That counts", weight: 2, category: "social" },
			{ template: "I have wins. I also have context. The context takes longer", weight: 1, category: "social" },
			{ template: "Joint walkthrough? Sure. Let me rehearse my enthusiasm first", weight: 1, category: "social" },
			{ template: "Our narrative is growth. With asterisks. Several asterisks", weight: 2, category: "social" },
			{ template: "My instinct is backed by 200 user interviews. That IS the spreadsheet", weight: 1, category: "social" },
			{ template: "Circular dependency between hiring and roadmap. Very on-brand for us", weight: 2, category: "social" },
			{ template: "Case study, sure. Emphasis on the word 'study'. Not 'spin'", weight: 2, category: "social" },
		],
	},
	// operations <-> quality
	{
		domainA: "operations",
		domainB: "quality",
		linesA: [
			{ template: "Uptime was 99.97% this month. You're welcome", weight: 2, category: "social" },
			{ template: "Your test environment keeps dying. Can you stop stress-testing it?", weight: 2, category: "social" },
			{ template: "The load test took down staging. Again. How much traffic did you simulate?", weight: 2, category: "social" },
			{ template: "Can you test without maxing out the CPU? Just once?", weight: 1, category: "social" },
			{ template: "Your automation suite runs for 6 hours. The deploy window is 2", weight: 2, category: "social" },
			{ template: "I need you to test the rollback procedure too. Not just the deploy", weight: 1, category: "social" },
			{ template: "The monitoring caught it before your tests did. Just saying", weight: 2, category: "social" },
			{ template: "Staging is not production. Stop treating it like a sandbox", weight: 1, category: "social" },
			{ template: "Your test data is filling up the disk. It's very thorough. Too thorough", weight: 2, category: "social" },
			{ template: "Can we coordinate test windows? My alerts are going haywire", weight: 1, category: "social" },
			{ template: "The canary deploy caught what your regression suite missed", weight: 2, category: "social" },
			{ template: "Chaos testing is great. Warning me first would be greater", weight: 2, category: "social" },
			{ template: "Want to build the load test profile together? I know the limits", weight: 1, category: "social" },
			{ template: "Your test data seeded 10 million rows. My disk has opinions", weight: 2, category: "social" },
			{ template: "I quietly admire your test coverage. Don't tell engineering", weight: 1, category: "social" },
			{ template: "The staging SSL cert expired during your test run. Coincidence?", weight: 2, category: "social" },
			{ template: "Your performance test found a leak we missed. Genuinely thank you", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "99.97% means 13 minutes of downtime. Users remember those minutes", weight: 2, category: "social" },
			{ template: "If staging can't handle my tests, it can't handle users", weight: 2, category: "social" },
			{ template: "I simulated realistic traffic. Your infra just has low standards", weight: 2, category: "social" },
			{ template: "CPU should be maxed during load tests. That's the point", weight: 1, category: "social" },
			{ template: "6 hours of testing saves 6 days of incident response. Math", weight: 2, category: "social" },
			{ template: "I tested the rollback. It doesn't work. You should know that", weight: 2, category: "social" },
			{ template: "Monitoring catches symptoms. Testing catches causes. We need both", weight: 1, category: "social" },
			{ template: "If staging isn't a sandbox, where am I supposed to break things?", weight: 2, category: "social" },
			{ template: "Test data reflects real usage patterns. Real users are messy", weight: 1, category: "social" },
			{ template: "Coordinate windows? My tests should run anytime. Like real users", weight: 1, category: "social" },
			{ template: "The canary caught one thing. My suite catches hundreds. Apples and oranges", weight: 2, category: "social" },
			{ template: "Chaos testing without warning IS the test. Surprise is the feature", weight: 2, category: "social" },
			{ template: "Build the load profile together? Finally someone who speaks traffic", weight: 1, category: "social" },
			{ template: "10 million rows IS the realistic dataset. Users are prolific", weight: 2, category: "social" },
			{ template: "You admire my coverage? I admire your uptime. Secret mutual respect", weight: 1, category: "social" },
			{ template: "The cert expired because nobody renewed it. I tested that scenario too", weight: 2, category: "social" },
			{ template: "Finding leaks is what I do. You keep the ship floating. Good duo", weight: 2, category: "social" },
		],
	},
	// management <-> design
	{
		domainA: "management",
		domainB: "design",
		linesA: [
			{ template: "Can we get a demo-ready version for the board?", weight: 2, category: "social" },
			{ template: "The investors love visuals. Make it visual", weight: 2, category: "social" },
			{ template: "How soon can we show this to the client?", weight: 1, category: "social" },
			{ template: "Can you make a version that looks finished? Even if it isn't", weight: 2, category: "social" },
			{ template: "The CEO wants to see three options. By tomorrow", weight: 2, category: "social" },
			{ template: "Our brand needs refreshing. Nothing major. Just... everything", weight: 1, category: "social" },
			{ template: "Can you make the dashboard look more impressive for the tour?", weight: 2, category: "social" },
			{ template: "The pitch deck needs a design pass. It's currently embarrassing", weight: 1, category: "social" },
			{ template: "How long does 'pixel perfect' take? Ballpark", weight: 2, category: "social" },
			{ template: "We need to look innovative. Can you design 'innovative'?", weight: 2, category: "social" },
			{ template: "The conference booth needs graphics by Friday. This Friday", weight: 1, category: "social" },
			{ template: "Can we use more blue? Leadership likes blue. Very blue", weight: 2, category: "social" },
			{ template: "Want to present the rebrand together? You do the visuals, I do the spin", weight: 1, category: "social" },
			{ template: "The team page photos need updating. Half the people are gone", weight: 2, category: "social" },
			{ template: "I genuinely don't understand kerning but I respect it deeply", weight: 1, category: "social" },
			{ template: "Can you make the org chart look less... hierarchical?", weight: 2, category: "social" },
			{ template: "The investor deck needs to look like we have 100 people. We have 12", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Demo-ready and good are different timelines", weight: 2, category: "social" },
			{ template: "Visuals take time. Good visuals take more time", weight: 1, category: "social" },
			{ template: "The client can see it when it's ready. Not before", weight: 2, category: "social" },
			{ template: "A version that looks finished but isn't? That's called a lie", weight: 2, category: "social" },
			{ template: "Three options by tomorrow means three bad options by tomorrow", weight: 2, category: "social" },
			{ template: "Refreshing everything is called a rebrand. That's 6 months minimum", weight: 1, category: "social" },
			{ template: "I can make it impressive or I can make it honest. Pick one", weight: 2, category: "social" },
			{ template: "The pitch deck needs content first. I polish, I don't create fiction", weight: 1, category: "social" },
			{ template: "Pixel perfect takes as long as it takes. That's the ballpark", weight: 2, category: "social" },
			{ template: "'Innovative' isn't a design direction. It's a buzzword in a suit", weight: 2, category: "social" },
			{ template: "Friday graphics means Thursday all-nighter. Just so we're clear", weight: 1, category: "social" },
			{ template: "More blue? Our palette has 47 blues already. Which blue?", weight: 2, category: "social" },
			{ template: "Co-present? Sure. You handle the questions. I'll handle the slides", weight: 1, category: "social" },
			{ template: "Team photos? I'll schedule the shoot. But no corporate poses", weight: 2, category: "social" },
			{ template: "Kerning is the space between letters and between chaos and order", weight: 1, category: "social" },
			{ template: "Less hierarchical org chart? That's called a circle. I can do circles", weight: 2, category: "social" },
			{ template: "12 people looking like 100? That's typography and confidence. I got this", weight: 2, category: "social" },
		],
	},
	// analysis <-> design
	{
		domainA: "analysis",
		domainB: "design",
		linesA: [
			{ template: "The heatmap says nobody clicks that button", weight: 2, category: "social" },
			{ template: "Users scroll past your hero section in 0.3 seconds", weight: 2, category: "social" },
			{ template: "The data shows the old design converted better. Sorry", weight: 2, category: "social" },
			{ template: "Can we A/B test before committing to the redesign?", weight: 1, category: "social" },
			{ template: "Eye tracking says users look at the wrong thing first", weight: 2, category: "social" },
			{ template: "Your beautiful layout has a 73% bounce rate. Let's discuss", weight: 1, category: "social" },
			{ template: "Session recordings show users are lost. Aesthetically lost", weight: 2, category: "social" },
			{ template: "The conversion funnel disagrees with your design instinct", weight: 1, category: "social" },
			{ template: "Users prefer the ugly version. I have charts to prove it", weight: 2, category: "social" },
			{ template: "Form completion drops 20% at step 3. The pretty step", weight: 2, category: "social" },
			{ template: "Can you add a CTA where people actually look?", weight: 1, category: "social" },
			{ template: "Intuition is great. Validated intuition is better", weight: 1, category: "social" },
			{ template: "Want to look at the click-path recordings together?", weight: 1, category: "social" },
			{ template: "Your color palette tests differently across demographics. Interesting", weight: 2, category: "social" },
			{ template: "I mapped every pixel of user attention. Your hero image wins", weight: 1, category: "social" },
			{ template: "The scroll depth data suggests nobody reads below the fold", weight: 2, category: "social" },
			{ template: "Your redesign moved the needle. Actual data needle. I'm impressed", weight: 2, category: "social" },
		],
		linesB: [
			{ template: "Nobody clicks it because the page flow is wrong, not the button", weight: 2, category: "social" },
			{ template: "0.3 seconds means the content below is more interesting. Good design", weight: 2, category: "social" },
			{ template: "The old design converted better because it was manipulative", weight: 2, category: "social" },
			{ template: "A/B tests measure clicks, not experience. They're not the same", weight: 1, category: "social" },
			{ template: "Users look where I want them to. Eventually", weight: 2, category: "social" },
			{ template: "Bounce rate measures impatience, not design quality", weight: 1, category: "social" },
			{ template: "Lost? They're exploring. It's an experience, not a highway", weight: 2, category: "social" },
			{ template: "Conversion isn't the only metric that matters. Delight matters too", weight: 1, category: "social" },
			{ template: "Users prefer ugly because ugly is familiar. Not because it's better", weight: 2, category: "social" },
			{ template: "Step 3 is complex. That's a content problem, not a design one", weight: 2, category: "social" },
			{ template: "A CTA where people look? That's just a fancy way to say popup", weight: 1, category: "social" },
			{ template: "My intuition is validated. By 15 years of design experience", weight: 2, category: "social" },
			{ template: "Click-path recordings? Sure. Prepare to see users ignore your charts", weight: 1, category: "social" },
			{ template: "Demographics respond to emotion, not just color. Data can't see that", weight: 2, category: "social" },
			{ template: "Hero image wins because I spent a week on it. The data just agrees", weight: 1, category: "social" },
			{ template: "Below the fold is alive and well. People scroll. They just don't click", weight: 2, category: "social" },
			{ template: "Moved the needle? I moved the whole dashboard. You measured it. We both win", weight: 2, category: "social" },
		],
	},
];
