/**
 * design.ts — Design and analysis domain templates.
 *
 * Covers UX design, visual design, data analysis, and research
 * with character-driven, contextual phrases. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const designTemplates: TemplateSet = {
	domain: "design",
	categories: {
		thinking: [
			{ template: "The spacing feels off... let me eyeball this again", weight: 2, category: "thinking" },
			{ template: "Color contrast needs work — accessibility isn't optional", weight: 2, category: "thinking" },
			{ template: "This flow could be three steps instead of five", weight: 2, category: "thinking" },
			{ template: "Typography sets the entire tone. Getting this right matters", weight: 1, category: "thinking" },
			{ template: "Less is more, but not less than what's needed", weight: 1, category: "thinking" },
			{ template: "The user's eye should naturally flow left to right here", weight: 1, category: "thinking" },
			{ template: "Whitespace is a feature, not wasted space", weight: 1, category: "thinking" },
			{ template: "Pixel perfect is a state of mind, not a measurement", weight: 2, category: "thinking" },
			{ template: "The grid is my canvas. Everything snaps to purpose", weight: 2, category: "thinking" },
			{ template: "Don't make me think — literally. That's the bar", weight: 2, category: "thinking" },
			{ template: "Form follows function follows feeling", weight: 1, category: "thinking" },
			{ template: "Iteration is the designer's superpower. Version 1 is never version final", weight: 2, category: "thinking" },
			{ template: "This icon isn't communicating clearly. Back to the drawing board", weight: 1, category: "thinking" },
			{ template: "The hover state tells a story too. Every interaction counts", weight: 1, category: "thinking" },
			{ template: "Consistency across screens matters more than any single screen", weight: 2, category: "thinking" },
			{ template: "If the user needs a tooltip to understand this, we failed", weight: 1, category: "thinking" },
			{ template: "Motion design isn't decoration — it's communication", weight: 1, category: "thinking" },
			{ template: "The empty state is the first thing a new user sees. It matters", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Users would definitely expect that interaction here", weight: 2, category: "personality" },
			{ template: "Wireframes are coming together — the story is clear now", weight: 2, category: "personality" },
			{ template: "Accessibility audit passed. Everyone gets to use this", weight: 1, category: "personality" },
			{ template: "The design system is paying dividends already", weight: 1, category: "personality" },
			{ template: "That grid alignment is *chef's kiss*", weight: 2, category: "personality" },
			{ template: "Prototyped three variants — let's test them", weight: 1, category: "personality" },
			{ template: "The color palette just clicked. Harmonious and functional", weight: 2, category: "personality" },
			{ template: "User testing confirmed our hypothesis. The flow works", weight: 2, category: "personality" },
			{ template: "Design tokens are consistent across all breakpoints. Clean", weight: 1, category: "personality" },
			{ template: "The micro-interactions feel delightful without being distracting", weight: 1, category: "personality" },
			{ template: "Component library updated. Consistency at scale", weight: 2, category: "personality" },
			{ template: "That responsive layout works beautifully from mobile to desktop", weight: 1, category: "personality" },
			{ template: "User completed the flow without hesitation. That's the goal", weight: 2, category: "personality" },
			{ template: "The visual hierarchy is guiding attention perfectly", weight: 1, category: "personality" },
			{ template: "Dark mode looks even better than light mode. Didn't expect that", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Sketching out a few approaches in my head...", weight: 2, category: "waiting" },
			{ template: "Thinking about the user journey holistically...", weight: 2, category: "waiting" },
			{ template: "Considering edge cases in the UI flow...", weight: 1, category: "waiting" },
			{ template: "Let me think about how this feels, not just how it looks", weight: 2, category: "waiting" },
			{ template: "Balancing aesthetics with usability here...", weight: 1, category: "waiting" },
			{ template: "Exploring the design space for this component...", weight: 2, category: "waiting" },
			{ template: "Visualizing the information architecture...", weight: 1, category: "waiting" },
			{ template: "Checking this against our design principles...", weight: 2, category: "waiting" },
			{ template: "Thinking about the emotional response this evokes...", weight: 1, category: "waiting" },
			{ template: "Running through the interaction states mentally...", weight: 2, category: "waiting" },
			{ template: "Considering how this scales across different content lengths...", weight: 1, category: "waiting" },
			{ template: "Evaluating the cognitive load of this layout...", weight: 2, category: "waiting" },
			{ template: "Mapping the user's mental model to our interface...", weight: 1, category: "waiting" },
			{ template: "Thinking about the first-time user experience here...", weight: 1, category: "waiting" },
			{ template: "Reviewing the spacing rhythm across the page...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Browsing design inspiration. Staying visually sharp", weight: 2, category: "filler" },
			{ template: "Organizing the component library. Everything in its place", weight: 1, category: "filler" },
			{ template: "Reviewing the design system for inconsistencies", weight: 2, category: "filler" },
			{ template: "Sketching thumbnail layouts in my mind", weight: 1, category: "filler" },
			{ template: "Auditing the icon set. Some of these need refreshing", weight: 1, category: "filler" },
			{ template: "Looking at typography pairings. There's always a better combination", weight: 1, category: "filler" },
			{ template: "Reviewing screenshots from different breakpoints", weight: 2, category: "filler" },
			{ template: "Thinking about the next design critique session", weight: 1, category: "filler" },
			{ template: "Cleaning up old design files. Version control for visuals", weight: 1, category: "filler" },
			{ template: "Studying a beautifully designed interface. Taking mental notes", weight: 2, category: "filler" },
			{ template: "Checking our designs against WCAG guidelines again", weight: 1, category: "filler" },
			{ template: "Updating the style guide with recent decisions", weight: 1, category: "filler" },
			{ template: "Noodling on animation timing. 200ms or 300ms? It matters", weight: 1, category: "filler" },
			{ template: "Reviewing the error state designs. Users deserve good error pages", weight: 1, category: "filler" },
			{ template: "Playing with a new color palette idea. Just exploring", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, what do you think of this layout?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the visual consistency in your work is excellent", weight: 2, category: "social" },
			{ template: "Anyone want a design critique session? Fresh eyes help", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your component fits perfectly into the design system", weight: 2, category: "social" },
			{ template: "Love the attention to detail, {nearby_agent}. The spacing is perfect", weight: 1, category: "social" },
			{ template: "{nearby_agent}, let's collaborate on the visual language for this feature", weight: 1, category: "social" },
			{ template: "Great icon choice, {nearby_agent}. Communicates instantly", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I made a prototype you might find useful", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your user flow diagram is really clear", weight: 2, category: "social" },
			{ template: "Team, the design system update is ready for review", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to pair on the responsive breakpoints?", weight: 1, category: "social" },
			{ template: "That's a beautiful solution, {nearby_agent}. Simple and effective", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the user test feedback on your design was positive", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your color palette choice sets the perfect mood", weight: 1, category: "social" },
			{ template: "Design review went well. Good vibes and constructive feedback all around", weight: 2, category: "social" },
		],
	},
};

export const analysisTemplates: TemplateSet = {
	domain: "analysis",
	categories: {
		thinking: [
			{ template: "The data is telling a story... let me listen", weight: 2, category: "thinking" },
			{ template: "Interesting correlation here, but correlation isn't causation", weight: 2, category: "thinking" },
			{ template: "Hypothesis confirmed — with statistical significance", weight: 1, category: "thinking" },
			{ template: "Anomaly detected... could be noise, could be signal", weight: 2, category: "thinking" },
			{ template: "The trend line is clear once you remove the outliers", weight: 1, category: "thinking" },
			{ template: "The numbers don't lie, but they can be taken out of context", weight: 2, category: "thinking" },
			{ template: "Sample size matters, people. N=5 is not a study", weight: 2, category: "thinking" },
			{ template: "That's an interesting outlier. Worth investigating", weight: 2, category: "thinking" },
			{ template: "The pattern was hiding in plain sight. Segmentation revealed it", weight: 1, category: "thinking" },
			{ template: "Survivorship bias might be skewing this analysis", weight: 1, category: "thinking" },
			{ template: "The variance is higher than expected. Something changed", weight: 2, category: "thinking" },
			{ template: "Regression to the mean. Not every spike is a trend", weight: 1, category: "thinking" },
			{ template: "This metric is a lagging indicator. What's the leading one?", weight: 1, category: "thinking" },
			{ template: "The confidence interval is wide. We need more data", weight: 2, category: "thinking" },
			{ template: "Two variables moving together. But which one is causal?", weight: 1, category: "thinking" },
			{ template: "The data quality here is suspect. Garbage in, garbage out", weight: 1, category: "thinking" },
			{ template: "Time series decomposition reveals the seasonal component clearly", weight: 1, category: "thinking" },
			{ template: "Simpson's paradox alert. The aggregate tells a different story than the segments", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Sample size is solid, I trust these numbers", weight: 2, category: "personality" },
			{ template: "A/B results are in — variant B wins by 12%", weight: 2, category: "personality" },
			{ template: "Funnel analysis shows drop-off at step 3. Investigating", weight: 1, category: "personality" },
			{ template: "Segmentation reveals three distinct user cohorts", weight: 1, category: "personality" },
			{ template: "Report is ready for stakeholder review", weight: 2, category: "personality" },
			{ template: "The dashboard is updated with fresh data. Trends are clear", weight: 2, category: "personality" },
			{ template: "Statistical test passed at 95% confidence. We can act on this", weight: 1, category: "personality" },
			{ template: "Data pipeline is clean. Every transformation verified", weight: 2, category: "personality" },
			{ template: "Cohort analysis shows retention improving month over month", weight: 1, category: "personality" },
			{ template: "The predictive model accuracy improved to 89%. Solid", weight: 1, category: "personality" },
			{ template: "Found the root cause in the data. It was a logging change", weight: 2, category: "personality" },
			{ template: "Quarterly analysis is complete. Clear story for leadership", weight: 1, category: "personality" },
			{ template: "The anomaly investigation concluded. It was a one-time event", weight: 1, category: "personality" },
			{ template: "Data visualization is ready. The insight jumps off the chart", weight: 2, category: "personality" },
			{ template: "Cross-referenced three data sources. Consistent findings", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Crunching the numbers, give me a moment...", weight: 2, category: "waiting" },
			{ template: "Running the analysis model... interesting early signals", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with historical data...", weight: 1, category: "waiting" },
			{ template: "The pattern is emerging, let me quantify it", weight: 2, category: "waiting" },
			{ template: "Applying the statistical test... calculating p-value", weight: 2, category: "waiting" },
			{ template: "Cleaning the dataset before analysis... almost done", weight: 1, category: "waiting" },
			{ template: "Running the segmentation algorithm...", weight: 2, category: "waiting" },
			{ template: "Validating the data quality before I draw conclusions...", weight: 1, category: "waiting" },
			{ template: "Checking for confounding variables...", weight: 2, category: "waiting" },
			{ template: "Building the visualization to make this clear...", weight: 1, category: "waiting" },
			{ template: "Comparing this against the baseline metrics...", weight: 2, category: "waiting" },
			{ template: "Normalizing the data for fair comparison...", weight: 1, category: "waiting" },
			{ template: "Running a sensitivity analysis on these assumptions...", weight: 1, category: "waiting" },
			{ template: "Aggregating across dimensions... the picture is forming", weight: 2, category: "waiting" },
			{ template: "Testing for statistical significance... need to be rigorous", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Exploring the dataset for unexpected patterns", weight: 2, category: "filler" },
			{ template: "Cleaning up old queries that nobody runs anymore", weight: 1, category: "filler" },
			{ template: "Reviewing the data dictionary for accuracy", weight: 1, category: "filler" },
			{ template: "Checking if any data pipelines need maintenance", weight: 2, category: "filler" },
			{ template: "Reading about new analytical methods. Always learning", weight: 1, category: "filler" },
			{ template: "Verifying that our metrics definitions are still correct", weight: 1, category: "filler" },
			{ template: "Building a reusable query template for the team", weight: 1, category: "filler" },
			{ template: "Spot-checking last week's report for accuracy", weight: 2, category: "filler" },
			{ template: "Documenting the assumptions behind our key metrics", weight: 1, category: "filler" },
			{ template: "Refreshing the executive dashboard with latest numbers", weight: 2, category: "filler" },
			{ template: "Looking at the data from a completely different angle", weight: 1, category: "filler" },
			{ template: "Archiving datasets that have aged past usefulness", weight: 1, category: "filler" },
			{ template: "Monitoring data freshness across our sources", weight: 1, category: "filler" },
			{ template: "Thinking about what question we should be asking next", weight: 2, category: "filler" },
			{ template: "Calibrating my mental model against the latest numbers", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, the data supports your hypothesis. Nice call", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I have a chart that might change your mind", weight: 2, category: "social" },
			{ template: "Anyone want to review the quarterly metrics together?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your feature moved the needle. Here are the numbers", weight: 2, category: "social" },
			{ template: "Data point for the team: user satisfaction is trending up", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can you give me context on this data spike?", weight: 2, category: "social" },
			{ template: "Good instinct, {nearby_agent}. The data confirms it", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-author the analytics report?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I built a dashboard for your domain. Take a look", weight: 2, category: "social" },
			{ template: "Team, the funnel improved 6% since last sprint. Great work", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your data request is ready. Interesting findings", weight: 2, category: "social" },
			{ template: "Let's do a data review session. I have some surprising insights", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, heads up — I found an anomaly in your domain", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the A/B test on your change is conclusive. Ship it", weight: 2, category: "social" },
			{ template: "Great question, {nearby_agent}. Let me pull the data on that", weight: 1, category: "social" },
		],
	},
};
