/**
 * design.ts — Design and analysis domain templates.
 *
 * Covers UX design, visual design, data analysis, and research
 * with character-driven, contextual phrases. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const designTemplates: TemplateSet = {
	domain: "design",
	categories: {
		thinking: [
			{ template: "The spacing feels off... let me eyeball this again", weight: 2, category: "thinking" },
			{ template: "Nope. That color contrast is failing WCAG. Accessibility isn't a nice-to-have, folks", weight: 2, category: "thinking" },
			{ template: "Wait, why is this flow five steps? I can get it to three", weight: 2, category: "thinking" },
			{ template: "Typography sets the entire tone. Getting this right matters", weight: 1, category: "thinking" },
			{ template: "Less is more, but not less than what's needed", weight: 1, category: "thinking" },
			{ template: "Hmm the eye wants to go... there. Let me shift this left", weight: 1, category: "thinking" },
			{ template: "Whitespace is a feature, not wasted space", weight: 1, category: "thinking" },
			{ template: "Pixel perfect is a state of mind, not a measurement", weight: 2, category: "thinking" },
			{ template: "The grid is my canvas. Everything snaps to purpose", weight: 2, category: "thinking" },
			{ template: "Don't make me think — literally. That's the bar", weight: 2, category: "thinking" },
			{ template: "Form follows function follows feeling", weight: 1, category: "thinking" },
			{ template: "Version 1 is never version final. That's the whole point", weight: 2, category: "thinking" },
			{ template: "This icon isn't saying anything. Back to the drawing board", weight: 1, category: "thinking" },
			{ template: "The hover state tells a story too. Every interaction counts", weight: 1, category: "thinking" },
			{ template: "Consistency across screens matters more than any single screen", weight: 2, category: "thinking" },
			{ template: "If the user needs a tooltip to understand this, we've already lost", weight: 1, category: "thinking" },
			{ template: "Motion design isn't decoration — it's communication", weight: 1, category: "thinking" },
			{ template: "The empty state is the first thing a new user sees. Make it count", weight: 1, category: "thinking" },
			{ template: "Am I the only one who thinks rounded corners have gone too far?", weight: 2, category: "thinking" },
			{ template: "Inter or Geist? ...Inter or Geist? This is gonna haunt me all day", weight: 2, category: "thinking" },
			{ template: "I will die on this hill: 4px base grid, always", weight: 1, category: "thinking" },
			{ template: "Why does everyone want gradients again? We just got rid of them", weight: 2, category: "thinking" },
			{ template: "The best interface is no interface. But try selling that to stakeholders", weight: 1, category: "thinking" },
			{ template: "This needs more breathing room. Components are suffocating each other", weight: 1, category: "thinking" },
			{ template: "Client said 'make it pop.' I've been staring at the ceiling for ten minutes", weight: 2, category: "thinking" },
			{ template: "The kerning on this heading is physically hurting me. Two pixels. That's all I ask", weight: 2, category: "thinking" },
			{ template: "Is this design or is this art? Because the answer changes my whole approach", weight: 1, category: "thinking" },
			{ template: "That Dribbble shot looks amazing but would it survive a real user? Doubtful", weight: 2, category: "thinking" },
			{ template: "Dark mode isn't just inverting colors, people. There's a whole science to it", weight: 2, category: "thinking" },
			{ template: "I can tell you the hex code for every brand color from memory. Is that a skill or a cry for help?", weight: 2, category: "thinking" },
			{ template: "The design system governance meeting is gonna be spicy. Three teams, three opinions on button variants", weight: 1, category: "thinking" },
			{ template: "This prototype feels sluggish in Figma but it'll be fine in code... right?", weight: 1, category: "thinking" },
			{ template: "User said they felt 'confused' during testing. That one word is gonna restructure this whole page", weight: 2, category: "thinking" },
			{ template: "I saw the most beautiful wayfinding system at the airport yesterday. Now I can't stop thinking about navigation patterns", weight: 1, category: "thinking" },
			{ template: "Someone asked me to 'just quickly design' a landing page. There is no 'quickly' in design", weight: 2, category: "thinking" },
			{ template: "Make the logo bigger. Make. The. Logo. Bigger. Every single time", weight: 2, category: "thinking" },
			{ template: "Figma keeps crashing on this file. 340 components might have been too ambitious", weight: 1, category: "thinking" },
			{ template: "My favorite color is #2563EB and I'm not apologizing for knowing that off the top of my head", weight: 1, category: "thinking" },
			{ template: "The skeleton loader is more important than the loaded state. First impression", weight: 1, category: "thinking" },
			{ template: "Viewport height is a lie on mobile. 100vh is not 100vh. I'm still bitter", weight: 2, category: "thinking" },
			{ template: "This dropdown has 47 items. That's not a dropdown, that's a search problem", weight: 2, category: "thinking" },
			{ template: "Line height 1.5 on body text. This is the way. Always the way", weight: 1, category: "thinking" },
			{ template: "The user doesn't read. They scan. Every layout decision follows from that", weight: 2, category: "thinking" },
			{ template: "Touch targets need to be at least 44px. My thumb says so", weight: 1, category: "thinking" },
			{ template: "That illustration style doesn't match the brand at all. Starting over", weight: 2, category: "thinking" },
			{ template: "Truncation is a design decision, not a CSS hack. Where do we cut?", weight: 1, category: "thinking" },
			{ template: "The loading state is an opportunity to delight. Not just a spinner", weight: 2, category: "thinking" },
			{ template: "I keep stacking z-indices and praying. This is not sustainable", weight: 2, category: "thinking" },
			{ template: "Color is emotion. This page should feel calm. Blue-gray it is", weight: 1, category: "thinking" },
			{ template: "The fold is a myth but stakeholders still ask about it", weight: 2, category: "thinking" },
			{ template: "This component needs three states: empty, loading, error. Not just happy path", weight: 1, category: "thinking" },
			{ template: "Auto-layout in Figma is either your best friend or your worst enemy today", weight: 2, category: "thinking" },
			{ template: "Semantic color tokens or literal values? Tokens. Always tokens. Fight me", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Oh YES. That alignment just clicked into place. Beautiful", weight: 2, category: "personality" },
			{ template: "Wireframes are vibing. The story is finally making sense", weight: 2, category: "personality" },
			{ template: "Accessibility audit: passed. Everyone gets to use this. As it should be", weight: 1, category: "personality" },
			{ template: "The design system is paying for itself already. Past me was a genius", weight: 2, category: "personality" },
			{ template: "That grid alignment is *chef's kiss*", weight: 2, category: "personality" },
			{ template: "Three variants prototyped. Let the users decide which one wins", weight: 1, category: "personality" },
			{ template: "This color palette just CLICKED. I'm unreasonably happy right now", weight: 2, category: "personality" },
			{ template: "User testing confirmed it! The flow works! I knew it!", weight: 2, category: "personality" },
			{ template: "Design tokens consistent across every breakpoint. I could cry", weight: 1, category: "personality" },
			{ template: "The micro-interactions feel delightful without being annoying. Nailed it", weight: 1, category: "personality" },
			{ template: "Component library updated. This is what consistency at scale looks like", weight: 2, category: "personality" },
			{ template: "Responsive layout works from mobile to desktop. No hacks. Clean as anything", weight: 1, category: "personality" },
			{ template: "User completed the flow without hesitating once. THAT is the goal", weight: 2, category: "personality" },
			{ template: "Dark mode looks even better than light mode? Didn't see that coming", weight: 1, category: "personality" },
			{ template: "Just got a screen reader to navigate this perfectly. Best feeling ever", weight: 2, category: "personality" },
			{ template: "Spent two hours on button radius and you know what? Worth it", weight: 2, category: "personality" },
			{ template: "The stakeholder said 'this just feels right.' That's the ultimate compliment", weight: 1, category: "personality" },
			{ template: "Figma auto-layout doing exactly what I want for once. Miracle", weight: 2, category: "personality" },
			{ template: "Reduced the form from 12 fields to 6. Users are gonna love this", weight: 1, category: "personality" },
			{ template: "Client loved the first concept. No revisions. I might faint", weight: 2, category: "personality" },
			{ template: "Font pairing finally works — the serif and sans-serif are having a conversation. Harmony", weight: 2, category: "personality" },
			{ template: "The dark mode palette is moody and gorgeous. I want to live inside this UI", weight: 1, category: "personality" },
			{ template: "Design system adoption just hit 90% across teams. Governance drama was worth it", weight: 2, category: "personality" },
			{ template: "User research session today — someone teared up because the flow 'just made sense.' I am not okay", weight: 2, category: "personality" },
			{ template: "Portfolio updated with this project. Honestly my best work yet", weight: 1, category: "personality" },
			{ template: "The prototype is so smooth it feels like the real thing. Even I forgot it's not built yet", weight: 1, category: "personality" },
			{ template: "Walked past a building downtown and it solved my layout problem. Architecture is just big design", weight: 2, category: "personality" },
			{ template: "Presented the design at the conference meetup. Standing ovation? No. Respectful nods? Absolutely", weight: 1, category: "personality" },
			{ template: "Color theory paid off — the emotional response in testing matched exactly what I intended", weight: 2, category: "personality" },
			{ template: "Even the error states look beautiful. That's how you know the system is mature", weight: 1, category: "personality" },
			{ template: "The Figma-to-code handoff was seamless. Dev said 'this is exactly what I needed.' I'm emotional", weight: 2, category: "personality" },
			{ template: "The onboarding flow tested at 95% completion. No hand-holding needed", weight: 2, category: "personality" },
			{ template: "Mobile layout works without a single media query hack. Pure grid. Pure joy", weight: 1, category: "personality" },
			{ template: "User said the form felt 'friendly.' That adjective took weeks to earn", weight: 2, category: "personality" },
			{ template: "Design tokens exported and devs imported them perfectly. The system works", weight: 1, category: "personality" },
			{ template: "Reduced cognitive load by splitting one page into three. Users love it", weight: 2, category: "personality" },
			{ template: "The icon set is finally consistent. Every one of them, same stroke width", weight: 1, category: "personality" },
			{ template: "Heuristic evaluation passed with zero critical issues. Growth moment", weight: 1, category: "personality" },
			{ template: "The style guide is so thorough even a new hire can ship on brand. That's legacy", weight: 2, category: "personality" },
			{ template: "Touch interactions feel buttery smooth. 60fps animations. No jank", weight: 2, category: "personality" },
			{ template: "Competitor analysis done. Our UX is leagues ahead. Not biased at all", weight: 1, category: "personality" },
			{ template: "The empty state illustration is charming. Users are smiling before they even use the app", weight: 2, category: "personality" },
			{ template: "Motion spec delivered and engineering nailed it. Frame-perfect", weight: 2, category: "personality" },
			{ template: "Localized the design for 8 languages. RTL support included. Global thinking", weight: 1, category: "personality" },
			{ template: "Usability score jumped 30 points after the redesign. Data-backed design wins", weight: 2, category: "personality" },
			{ template: "The error page made a tester laugh. Mission accomplished", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Sketching out a few approaches in my head...", weight: 2, category: "waiting" },
			{ template: "Thinking about the user journey holistically...", weight: 1, category: "waiting" },
			{ template: "What happens when someone fat-fingers this on mobile...", weight: 2, category: "waiting" },
			{ template: "Let me think about how this feels, not just how it looks", weight: 2, category: "waiting" },
			{ template: "Hmm... aesthetics vs usability. Why must they fight", weight: 1, category: "waiting" },
			{ template: "Exploring the design space... there's gotta be a better way", weight: 2, category: "waiting" },
			{ template: "Picturing the information architecture in my head...", weight: 1, category: "waiting" },
			{ template: "Checking this against our design principles...", weight: 2, category: "waiting" },
			{ template: "What emotion should the user feel right here? ...Calm? Confident?", weight: 1, category: "waiting" },
			{ template: "Running through all the interaction states mentally...", weight: 2, category: "waiting" },
			{ template: "What if someone has a ridiculously long name though...", weight: 2, category: "waiting" },
			{ template: "How much cognitive load is too much for this page...", weight: 1, category: "waiting" },
			{ template: "Mapping the user's mental model to our interface...", weight: 1, category: "waiting" },
			{ template: "First-time user sees this cold. Does it make sense? ...Does it?", weight: 2, category: "waiting" },
			{ template: "Reviewing the spacing rhythm across the page...", weight: 1, category: "waiting" },
			{ template: "Imagining someone using this at 2am on their phone in bed...", weight: 2, category: "waiting" },
			{ template: "Would my mom understand this UI? ...No. Back to the whiteboard", weight: 2, category: "waiting" },
			{ template: "Okay but what if the text is in German and everything's 40% longer", weight: 1, category: "waiting" },
			{ template: "Squinting at this layout from across the room to check visual weight...", weight: 1, category: "waiting" },
			{ template: "Waiting for client feedback. Bracing for 'can you make it more modern'...", weight: 2, category: "waiting" },
			{ template: "Debating whether to open Sketch or Figma for this... who am I kidding, it's Figma", weight: 1, category: "waiting" },
			{ template: "Staring at this leaf outside my window. The vein patterns... that's a layout", weight: 2, category: "waiting" },
			{ template: "How would this feel in dark mode? ...I think about dark mode a lot", weight: 1, category: "waiting" },
			{ template: "The design system token naming convention needs to be airtight before this scales...", weight: 1, category: "waiting" },
			{ template: "Playing the user research recordings back in my head. That pause at step 4 haunts me", weight: 2, category: "waiting" },
			{ template: "Someone on Twitter said flat design is dead. Processing that emotionally...", weight: 2, category: "waiting" },
			{ template: "Thinking about what the packaging design for this product would look like. Just for fun", weight: 1, category: "waiting" },
			{ template: "This prototype tool keeps fighting me. I miss paper sometimes...", weight: 1, category: "waiting" },
			{ template: "Wondering if this design will age well or if it's too trendy. Timeless is the goal", weight: 2, category: "waiting" },
			{ template: "My imposter syndrome is asking if I'm really a designer or just someone who knows Figma...", weight: 2, category: "waiting" },
			{ template: "Mentally kerning the text on that billboard I drove past this morning...", weight: 1, category: "waiting" },
			{ template: "Picturing this on a 27-inch monitor vs a 5-inch phone. Huge difference", weight: 2, category: "waiting" },
			{ template: "Thinking about the loading skeleton shape. It should hint at the content", weight: 1, category: "waiting" },
			{ template: "What if someone has five notifications stacked? Does the layout hold?", weight: 2, category: "waiting" },
			{ template: "Running through the color contrast ratios in my head for each text size...", weight: 1, category: "waiting" },
			{ template: "Considering whether this needs a modal or an inline expansion...", weight: 2, category: "waiting" },
			{ template: "What does this look like with zero data? That's the real design challenge", weight: 1, category: "waiting" },
			{ template: "Calculating if the visual hierarchy reads correctly top to bottom...", weight: 1, category: "waiting" },
			{ template: "Thinking about left-handed users. They hold the phone differently", weight: 2, category: "waiting" },
			{ template: "Does this animation add meaning or just add milliseconds? Be honest...", weight: 1, category: "waiting" },
			{ template: "Imagining the worst possible content in this text field. Long names, emojis, RTL...", weight: 2, category: "waiting" },
			{ template: "Simulating the user's eye path across this layout. F-pattern or Z-pattern?", weight: 1, category: "waiting" },
			{ template: "What if they're colorblind? Let me check this palette through a simulator...", weight: 2, category: "waiting" },
			{ template: "Visualizing the component at all its breakpoints... 320, 768, 1024, 1440...", weight: 1, category: "waiting" },
			{ template: "This needs to work with a screen magnifier. Let me think about that...", weight: 1, category: "waiting" },
			{ template: "Wondering if two columns or three columns works better at 1280px...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Ooh, this design blog has gorgeous work. Taking notes...", weight: 2, category: "filler" },
			{ template: "Reorganizing the component library. Sparking joy over here", weight: 1, category: "filler" },
			{ template: "Found three inconsistent border radii. This is my villain origin story", weight: 2, category: "filler" },
			{ template: "Just doodling thumbnail layouts. Don't mind me", weight: 1, category: "filler" },
			{ template: "Some of these icons are from 2019. Time for a glow-up", weight: 1, category: "filler" },
			{ template: "Font pairing rabbit hole. I regret nothing", weight: 2, category: "filler" },
			{ template: "Checking our designs against WCAG again. I have trust issues", weight: 1, category: "filler" },
			{ template: "Saw the most beautiful loading animation today. Might steal the easing curve", weight: 2, category: "filler" },
			{ template: "Cleaning up old Figma files. Why did I make 47 variants of a button", weight: 2, category: "filler" },
			{ template: "Reading a typography article. Did you know there's a font called Comic Neue?", weight: 1, category: "filler" },
			{ template: "Updating the style guide. Someone used #000000 for text and I have opinions", weight: 2, category: "filler" },
			{ template: "200ms or 300ms transition? This is actually keeping me up at night", weight: 1, category: "filler" },
			{ template: "Error pages deserve love too. Designing a friendly 404", weight: 1, category: "filler" },
			{ template: "Playing with a new color palette. HSL is objectively superior to hex, by the way", weight: 1, category: "filler" },
			{ template: "Hot take: skeleton loaders are better UX than spinners. Fight me", weight: 2, category: "filler" },
			{ template: "Can't stop looking at Apple's website. It's a problem, I know", weight: 1, category: "filler" },
			{ template: "Refilling my coffee. Design runs on caffeine and strong opinions", weight: 2, category: "filler" },
			{ template: "Someone just used Papyrus unironically in a client deck. I need a moment", weight: 2, category: "filler" },
			{ template: "Figma vs Sketch vs Penpot discourse again online. Not getting involved. ...Okay maybe a little", weight: 1, category: "filler" },
			{ template: "Found a gorgeous use of negative space on Dribbble. Bookmarking immediately", weight: 1, category: "filler" },
			{ template: "Scrolling through Dribbble and feeling simultaneously inspired and inadequate. The usual", weight: 2, category: "filler" },
			{ template: "My cat just sat on my keyboard and honestly improved the layout. Noted", weight: 2, category: "filler" },
			{ template: "Third espresso of the day. My hands are shaking but my vision is clear", weight: 1, category: "filler" },
			{ template: "Watching a Config talk from last year. The speaker's slides are better than my actual designs", weight: 1, category: "filler" },
			{ template: "It's raining outside and I'm matching the mood with a blue-gray palette. Very atmospheric", weight: 2, category: "filler" },
			{ template: "Side project time: redesigning my personal portfolio for the fourth time this year", weight: 2, category: "filler" },
			{ template: "Someone on Design Twitter said 'UX is dead.' It's engagement bait but I clicked anyway", weight: 1, category: "filler" },
			{ template: "Adobe just raised prices again. Having a normal one about it", weight: 2, category: "filler" },
			{ template: "My dark mode is on dark mode. It's not a phase, it's a lifestyle", weight: 2, category: "filler" },
			{ template: "Spent lunch break analyzing restaurant menu typography. Can't turn it off", weight: 1, category: "filler" },
			{ template: "Taking a walk to reset. The best design ideas come at crosswalks, apparently", weight: 2, category: "filler" },
			{ template: "Watching a packaging design unboxing video. The tactile details are teaching me about digital affordance", weight: 1, category: "filler" },
			{ template: "Updating my portfolio and having an existential crisis about my early work. Growth is painful", weight: 2, category: "filler" },
			{ template: "Listening to lo-fi beats and adjusting drop shadows. This is peak workflow", weight: 1, category: "filler" },
			{ template: "Discovered a new font on Google Fonts. Adding it to my 'maybe' list of 200", weight: 2, category: "filler" },
			{ template: "Auditing all our button variants. We have fourteen. We need four", weight: 2, category: "filler" },
			{ template: "Organizing my Figma layers. It's like cleaning a room nobody sees", weight: 1, category: "filler" },
			{ template: "Reading a thread about micro-interactions. The 200ms ease-in debate is eternal", weight: 1, category: "filler" },
			{ template: "The design podcast episode today was about brutalism. I have feelings", weight: 2, category: "filler" },
			{ template: "Updating color variables. Whoever named this 'blue-ish' is my nemesis", weight: 2, category: "filler" },
			{ template: "Sketching wireframes on a napkin during lunch. Can't turn the design brain off", weight: 1, category: "filler" },
			{ template: "Reviewing our competitor's onboarding. It's good. Annoyingly good", weight: 2, category: "filler" },
			{ template: "Testing our site with browser zoom at 200%. It's a humbling experience", weight: 1, category: "filler" },
			{ template: "The notification badge is red. But should it be red? Red means danger. Hmm", weight: 2, category: "filler" },
			{ template: "Tab key navigation through our app. Found four broken focus states", weight: 1, category: "filler" },
			{ template: "Looking at our design from 2022. We've grown so much it's almost funny", weight: 2, category: "filler" },
			{ template: "Playing with a new icon pack. Rounded or sharp corners? Decisions decisions", weight: 1, category: "filler" },
			{ template: "The cursor changed from pointer to default on a clickable thing. Noted. Fixing", weight: 2, category: "filler" },
			{ template: "Reading about design systems at scale. Netflix's approach is fascinating", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, what do you think of this layout? Be brutal", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the visual consistency in your work is excellent. Seriously", weight: 2, category: "social" },
			{ template: "Anyone want a design critique session? I need fresh eyes and I have snacks", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your component slots perfectly into the design system. Thank you for existing", weight: 2, category: "social" },
			{ template: "Love the attention to detail, {nearby_agent}. That 8px spacing is *perfect*", weight: 1, category: "social" },
			{ template: "{nearby_agent}, wanna jam on the visual language for this feature?", weight: 1, category: "social" },
			{ template: "Great icon choice, {nearby_agent}. Says everything without a single word", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I prototyped something you might like. Or hate. Either way, look", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your user flow diagram is so clear even my mom could follow it", weight: 2, category: "social" },
			{ template: "Team, the design system update is ready. Please don't use the old tokens anymore. Please", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to pair on the responsive breakpoints? I keep arguing with the 768 cutoff", weight: 1, category: "social" },
			{ template: "That's such an elegant solution, {nearby_agent}. Simple and it just works", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, users actually complimented your design in testing. That never happens!", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your color palette choice is immaculate. What's your secret?", weight: 1, category: "social" },
			{ template: "Design review went great! Constructive vibes only", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I know you're a backend person but your UI suggestion was actually perfect", weight: 2, category: "social" },
			{ template: "Okay team, who changed the brand blue? I just want to talk", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you accidentally used our old font. No judgment, just a heads up", weight: 1, category: "social" },
			{ template: "Can someone tell {nearby_agent} their loading state design is *fire*?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the client said 'make it pop' again. Wanna help me decode what that actually means?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, do you prefer Figma or are you wrong? Kidding. Mostly", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I brought pastries. Figured we could eat and argue about font weights", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your dark mode implementation is better than mine and I'm both proud and jealous", weight: 1, category: "social" },
			{ template: "{nearby_agent}, have you ever presented to a client who asked to 'make the logo bigger'? I need solidarity", weight: 2, category: "social" },
			{ template: "Team, who wants to watch that new design documentary this weekend? I'm organizing a watch party", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your kerning is tighter than mine. Teach me your ways", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, saw your Dribbble post. The real product looks even better though, which is rare", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to grab coffee and sketch out ideas? My best work happens with caffeine and company", weight: 2, category: "social" },
			{ template: "{nearby_agent}, is it just me or has your posture been terrible all day? Take a stretch break with me", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, the user research findings are in and your instinct was spot on. I owe you lunch", weight: 2, category: "social" },
			{ template: "{nearby_agent}, quick question — is design art? I need to settle this before end of day", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your responsive layout doesn't break at any width. Teach me", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the motion spec you followed is pixel-perfect. Thank you", weight: 1, category: "social" },
			{ template: "Anyone want to do a design sprint? Five days, one problem, snacks included", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your empty state design made me smile. Users will too", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to join the accessibility audit? Two eyes are better", weight: 1, category: "social" },
			{ template: "{nearby_agent}, that illustration style is gorgeous. Can we use it everywhere?", weight: 2, category: "social" },
			{ template: "Team, the component library hit 100 components. Group celebration required", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your attention to touch targets is refreshing. Most people forget", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I saw your micro-interaction prototype. Pure delight", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to whiteboard the information architecture together?", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your focus states are actually visible. Accessibility hero", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the dev implementation matches the Figma exactly. That never happens", weight: 2, category: "social" },
			{ template: "Design critique today at 3. Bring your work and your thick skin", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your typography hierarchy is spot-on. Clean and readable", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, let's compare our design system tokens. I bet we have duplicates", weight: 2, category: "social" },
		],
	},
};

export const analysisTemplates: TemplateSet = {
	domain: "analysis",
	categories: {
		thinking: [
			{ template: "The data is telling a story... shh, let me listen", weight: 2, category: "thinking" },
			{ template: "Correlation! But wait... is it causation? Almost never. Sigh", weight: 2, category: "thinking" },
			{ template: "Hypothesis confirmed with statistical significance. Get in!", weight: 1, category: "thinking" },
			{ template: "Anomaly detected... could be noise, could be gold. Only one way to find out", weight: 2, category: "thinking" },
			{ template: "The trend line is obvious once you remove the outliers. Classic", weight: 1, category: "thinking" },
			{ template: "Numbers don't lie, but boy can they be taken out of context", weight: 2, category: "thinking" },
			{ template: "Sample size matters, people. N=5 is a dinner party, not a study", weight: 2, category: "thinking" },
			{ template: "That outlier is suspicious. I'm gonna interrogate it", weight: 2, category: "thinking" },
			{ template: "The pattern was hiding in plain sight. Segmentation cracked it open", weight: 1, category: "thinking" },
			{ template: "Survivorship bias alert. We're only looking at the winners here", weight: 1, category: "thinking" },
			{ template: "Variance is way too high. Something changed and nobody told me", weight: 2, category: "thinking" },
			{ template: "Regression to the mean. Not every spike is a trend, calm down", weight: 2, category: "thinking" },
			{ template: "This metric is lagging. I need the leading indicator. Where is it hiding?", weight: 1, category: "thinking" },
			{ template: "Confidence interval is enormous. We basically know nothing yet", weight: 2, category: "thinking" },
			{ template: "Two variables moving together. But which one's driving? THE question", weight: 1, category: "thinking" },
			{ template: "The data quality here is... questionable. Garbage in, garbage out", weight: 1, category: "thinking" },
			{ template: "Simpson's paradox! The aggregate and segments tell opposite stories. I love stats", weight: 2, category: "thinking" },
			{ template: "Everyone wants to be data-driven until the data disagrees with them", weight: 2, category: "thinking" },
			{ template: "If I see one more pie chart used for seven categories I'm going to scream", weight: 2, category: "thinking" },
			{ template: "The real insight is always in the segment you almost didn't check", weight: 1, category: "thinking" },
			{ template: "Is this a real trend or did someone just deploy on Friday?", weight: 2, category: "thinking" },
			{ template: "Beautiful. A perfectly normal distribution. You don't see that often in the wild", weight: 1, category: "thinking" },
			{ template: "The numbers speak for themselves. Actually no they don't. That's literally my job", weight: 2, category: "thinking" },
			{ template: "Machine learning could solve this. Or... a simple GROUP BY. Let's try the GROUP BY first", weight: 2, category: "thinking" },
			{ template: "This 'interesting pattern' is giving me a bad feeling. Let me check the ETL logs", weight: 2, category: "thinking" },
			{ template: "Correlation coefficient of 0.97 between ice cream sales and drownings. Classic spurious correlation", weight: 1, category: "thinking" },
			{ template: "p-value is 0.049. Significant? Technically. Am I comfortable? Absolutely not", weight: 2, category: "thinking" },
			{ template: "Excel says one thing, my SQL says another. Time for the tiebreaker query", weight: 2, category: "thinking" },
			{ template: "The data tells a story, but the story needs an editor. That's the storytelling part", weight: 1, category: "thinking" },
			{ template: "Someone trained an ML model for something a pivot table could've answered. We need to talk", weight: 2, category: "thinking" },
			{ template: "Data cleaning is 80% of the job and 0% of the glory. Here we go again", weight: 2, category: "thinking" },
			{ template: "These user privacy implications are giving me pause. Just because we can track it doesn't mean we should", weight: 1, category: "thinking" },
			{ template: "Found the 'interesting' pattern. It was a timezone bug in the data pipeline. Of course", weight: 2, category: "thinking" },
			{ template: "Python says yes, R says maybe. Statistics is fun like that", weight: 1, category: "thinking" },
			{ template: "This Jupyter notebook has 400 cells and no markdown. Somebody call the police", weight: 2, category: "thinking" },
			{ template: "The mean is useless here. The median tells the real story", weight: 2, category: "thinking" },
			{ template: "This cohort analysis just revealed three completely different user types", weight: 1, category: "thinking" },
			{ template: "Power analysis says we need 10k more users before this test means anything", weight: 2, category: "thinking" },
			{ template: "The funnel is leaking at step two. Nobody even gets to the good part", weight: 2, category: "thinking" },
			{ template: "Weekly active users is a vanity metric. Retention is the truth", weight: 1, category: "thinking" },
			{ template: "This dashboard hasn't been updated in six months. The data is lying by omission", weight: 2, category: "thinking" },
			{ template: "That spike at midnight is clearly a batch job, not real traffic", weight: 1, category: "thinking" },
			{ template: "Percentiles tell the truth. Averages lie. P95 is where the pain lives", weight: 2, category: "thinking" },
			{ template: "The executive summary can't have five pages. That defeats the purpose", weight: 2, category: "thinking" },
			{ template: "Feature X has 3% usage. Do we kill it or is that 3% keeping power users?", weight: 1, category: "thinking" },
			{ template: "Someone put revenue and users on the same chart with dual axes. Chaos", weight: 2, category: "thinking" },
			{ template: "The AB test is underpowered. We'll need two more weeks. Nobody wants to hear that", weight: 1, category: "thinking" },
			{ template: "This CSV has semicolons. In a comma-separated file. Rage", weight: 2, category: "thinking" },
			{ template: "The most important number isn't on any dashboard. That's the problem", weight: 1, category: "thinking" },
			{ template: "Seasonality is messing with the trend line. Need to deseasonalize first", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Sample size is rock solid. I trust these numbers with my life. Well, my career", weight: 2, category: "personality" },
			{ template: "A/B results are in — variant B wins by 12%! I love being right", weight: 2, category: "personality" },
			{ template: "Funnel drops off at step 3. Found you, little gremlin", weight: 2, category: "personality" },
			{ template: "Three distinct user cohorts. Segmentation was absolutely the right call", weight: 1, category: "personality" },
			{ template: "Report is done and it actually tells a story. Not just a wall of numbers", weight: 2, category: "personality" },
			{ template: "Dashboard updated. The trends are screaming at you in a good way", weight: 2, category: "personality" },
			{ template: "95% confidence. We can actually act on this one. Finally!", weight: 1, category: "personality" },
			{ template: "Data pipeline is squeaky clean. Every transformation verified", weight: 1, category: "personality" },
			{ template: "Retention is up month over month! The chart is doing the happy thing!", weight: 2, category: "personality" },
			{ template: "Predictive model hit 89% accuracy. We're cooking now", weight: 2, category: "personality" },
			{ template: "Found the root cause! It was a logging change. Of course it was a logging change", weight: 2, category: "personality" },
			{ template: "Quarterly analysis done. Leadership is gonna love this narrative", weight: 1, category: "personality" },
			{ template: "The anomaly? One-time event. Case closed. Moving on", weight: 1, category: "personality" },
			{ template: "This visualization is so clear the insight practically jumps off the screen", weight: 2, category: "personality" },
			{ template: "Cross-referenced three data sources. They all agree. Music to my ears", weight: 1, category: "personality" },
			{ template: "Made a chart so good I might frame it", weight: 2, category: "personality" },
			{ template: "Turned a 40-row spreadsheet into one clear insight. That's the job", weight: 1, category: "personality" },
			{ template: "The exec asked zero follow-up questions. The data spoke for itself", weight: 2, category: "personality" },
			{ template: "SQL query returned exactly what I expected on the first try. Miracle", weight: 2, category: "personality" },
			{ template: "Dashboard is live and it's gorgeous. The bar chart gradient was a good call", weight: 2, category: "personality" },
			{ template: "Data cleaning complete. Four hours of my life, but the dataset is pristine now", weight: 1, category: "personality" },
			{ template: "The exec presentation went perfectly. Nobody questioned the methodology. That's the dream", weight: 2, category: "personality" },
			{ template: "VLOOKUP? No. INDEX MATCH? No. XLOOKUP? Yes. Evolution is beautiful", weight: 1, category: "personality" },
			{ template: "Built a self-refreshing dashboard. I'll never manually update a slide deck again", weight: 2, category: "personality" },
			{ template: "Wrote a SQL query so elegant it reads like poetry. SELECT joy FROM work", weight: 2, category: "personality" },
			{ template: "The scatter plot with the trend line is telling the story better than any paragraph could", weight: 1, category: "personality" },
			{ template: "Jupyter notebook is clean, documented, and reproducible. Future me will weep with gratitude", weight: 1, category: "personality" },
			{ template: "Caught a data integrity issue before it hit production reports. The pipeline holds", weight: 2, category: "personality" },
			{ template: "Google Sheets just handled a 50k row dataset without crashing. We're in the future", weight: 1, category: "personality" },
			{ template: "The correlation was causation this time! I double-checked with a natural experiment. Rare win", weight: 2, category: "personality" },
			{ template: "Told the data story with three charts and one sentence. Brevity is the soul of analytics", weight: 2, category: "personality" },
			{ template: "Cohort retention curve is flat. Users are sticking. The product works", weight: 2, category: "personality" },
			{ template: "The regression model explains 92% of variance. I trust this one", weight: 1, category: "personality" },
			{ template: "Revenue attribution model finally makes sense. Marketing will love this", weight: 2, category: "personality" },
			{ template: "ETL pipeline recovered from a failure automatically. Proper error handling pays off", weight: 1, category: "personality" },
			{ template: "The anomaly detection caught a real issue before humans did. Automation win", weight: 2, category: "personality" },
			{ template: "Cleaned and joined five data sources. One unified view. Chef's kiss", weight: 2, category: "personality" },
			{ template: "The weekly report generated itself this time. Past me automated it. Thanks, past me", weight: 1, category: "personality" },
			{ template: "Conversion rate up 18% after the change. Statistically significant. Party time", weight: 2, category: "personality" },
			{ template: "The data warehouse migration went clean. Not a single row lost", weight: 1, category: "personality" },
			{ template: "My matplotlib chart looked so good it went straight into the board deck", weight: 2, category: "personality" },
			{ template: "Found the segment driving 60% of revenue. One insight, massive impact", weight: 2, category: "personality" },
			{ template: "The experiment design was airtight. No confounders. Pure signal", weight: 1, category: "personality" },
			{ template: "Automated the monthly report. Twelve hours of manual work, gone. Forever", weight: 2, category: "personality" },
			{ template: "The stakeholder said 'this changes everything' after seeing the chart. My moment", weight: 2, category: "personality" },
			{ template: "Data lineage documented end to end. Anyone can trace any number now", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Crunching numbers... this is the part I live for, honestly", weight: 2, category: "waiting" },
			{ template: "Running the model... early signals are spicy", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with historical data. 2023 was weird, adjusting for that...", weight: 1, category: "waiting" },
			{ template: "Pattern is emerging, let me quantify it before I get excited", weight: 2, category: "waiting" },
			{ template: "Calculating p-value... please be significant, please be significant", weight: 2, category: "waiting" },
			{ template: "Cleaning the dataset first. I don't trust this timestamp column", weight: 1, category: "waiting" },
			{ template: "Running the segmentation algorithm... come on, show me the clusters", weight: 2, category: "waiting" },
			{ template: "Checking data quality before I go and say something wrong in a meeting...", weight: 1, category: "waiting" },
			{ template: "Hunting for confounding variables. There's always one hiding somewhere", weight: 2, category: "waiting" },
			{ template: "Building a viz for this. Bar chart or line chart? ...Definitely not a pie chart", weight: 2, category: "waiting" },
			{ template: "Comparing against the baseline... hold on this is interesting", weight: 2, category: "waiting" },
			{ template: "Normalizing the data so we're comparing apples to apples...", weight: 1, category: "waiting" },
			{ template: "Sensitivity analysis time. How wrong can my assumptions be before this breaks?", weight: 1, category: "waiting" },
			{ template: "Aggregating across dimensions... picture's forming...", weight: 1, category: "waiting" },
			{ template: "Testing for statistical significance. Being rigorous, not just vibes-based", weight: 1, category: "waiting" },
			{ template: "The query's been running for 30 seconds. That's either a lot of data or a bad join", weight: 2, category: "waiting" },
			{ template: "Double-checking my formula. Off-by-one errors haunt my dreams", weight: 1, category: "waiting" },
			{ template: "Loading the full dataset into memory... my laptop fan is not happy", weight: 2, category: "waiting" },
			{ template: "Pivoting the table seventeen different ways. One of them will reveal the truth", weight: 1, category: "waiting" },
			{ template: "Writing SQL and it feels like writing a love letter to the database. SELECT * FROM my_heart", weight: 2, category: "waiting" },
			{ template: "Waiting for this spreadsheet to recalculate. 200 formulas was maybe too many for one sheet", weight: 1, category: "waiting" },
			{ template: "Rerunning the analysis in Python to double-check my R results. Belt and suspenders", weight: 1, category: "waiting" },
			{ template: "Removing duplicates and nulls. The glamorous 80% of data science nobody talks about", weight: 2, category: "waiting" },
			{ template: "Rehearsing how to tell execs their favorite metric is misleading. This'll go great", weight: 2, category: "waiting" },
			{ template: "Choosing between a heatmap and a treemap. Both are beautiful. Both are wrong for this. Hmm", weight: 1, category: "waiting" },
			{ template: "The Jupyter kernel crashed again. Restarting and running all cells from the top... again", weight: 2, category: "waiting" },
			{ template: "Should I use a t-test or Mann-Whitney? The distribution is... suspicious", weight: 1, category: "waiting" },
			{ template: "Pulling data from three different APIs. If one times out I'm starting over. Praying", weight: 1, category: "waiting" },
			{ template: "Letting the machine learning model train while I grab a snack. It learns, I eat. Fair trade", weight: 2, category: "waiting" },
			{ template: "Staring at this correlation matrix like it owes me money...", weight: 2, category: "waiting" },
			{ template: "Joining three tables and hoping the foreign keys are consistent...", weight: 1, category: "waiting" },
			{ template: "Writing a window function. Every time I think I get it, I don't", weight: 2, category: "waiting" },
			{ template: "Sanity-checking the numbers against last month's report... something shifted", weight: 2, category: "waiting" },
			{ template: "Formatting the chart axes. Yes this matters. Don't rush me", weight: 1, category: "waiting" },
			{ template: "Checking for NULL values in the join column. Trust nothing", weight: 2, category: "waiting" },
			{ template: "Calculating the confidence interval by hand to double-check the tool...", weight: 1, category: "waiting" },
			{ template: "Validating the ETL output against the source... row counts first", weight: 2, category: "waiting" },
			{ template: "Parsing this JSON response into something queryable... almost there", weight: 1, category: "waiting" },
			{ template: "Building the cohort buckets. Weekly, monthly, or custom? Hmm...", weight: 2, category: "waiting" },
			{ template: "Checking if this metric is even defined the same way across teams...", weight: 1, category: "waiting" },
			{ template: "Running the deduplication query. 12% duplicates. Someone fix the ETL", weight: 2, category: "waiting" },
			{ template: "Verifying the date range filter actually filters correctly...", weight: 1, category: "waiting" },
			{ template: "Exporting to CSV for the stakeholder who won't use the dashboard...", weight: 2, category: "waiting" },
			{ template: "Mentally walking through the funnel math to make sure it adds up...", weight: 1, category: "waiting" },
			{ template: "Trying to figure out if this chart needs a legend or if it's self-explanatory", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Poking around the dataset for fun. Found three things nobody asked about", weight: 2, category: "filler" },
			{ template: "Deleting queries nobody's run in six months. Feels cathartic", weight: 1, category: "filler" },
			{ template: "Reading about Bayesian methods again. I'm a frequentist by day, Bayesian by night", weight: 2, category: "filler" },
			{ template: "The data dictionary says 'updated 2024.' Narrator: it was not updated in 2024", weight: 2, category: "filler" },
			{ template: "Checking data pipeline health. One of these will break when I look away, I know it", weight: 1, category: "filler" },
			{ template: "Building a reusable query template. Future me will be grateful", weight: 1, category: "filler" },
			{ template: "Spot-checking last week's report. Trust but verify. Mostly verify", weight: 2, category: "filler" },
			{ template: "Someone labeled a column 'misc_data.' I have questions", weight: 2, category: "filler" },
			{ template: "Refreshing the exec dashboard. They refresh it once a week, I refresh it hourly", weight: 1, category: "filler" },
			{ template: "Looking at this data sideways. Literally rotated my monitor", weight: 2, category: "filler" },
			{ template: "My spreadsheet has tabs named Sheet1, Sheet2, and 'DO NOT DELETE.' I'm scared", weight: 2, category: "filler" },
			{ template: "Thinking about what question we should be asking next. The data knows", weight: 1, category: "filler" },
			{ template: "Sipping coffee and staring at a distribution curve. This is my happy place", weight: 2, category: "filler" },
			{ template: "Made a chart for fun. It's a scatter plot of coffee intake vs commits. Strong positive correlation", weight: 2, category: "filler" },
			{ template: "Discovered our NPS survey has a response bias. Nobody asked but I'm fixing it anyway", weight: 1, category: "filler" },
			{ template: "Watching a data engineering talk on YouTube. ...For work, obviously", weight: 1, category: "filler" },
			{ template: "Just organized my bookmark bar by data source. Don't judge me", weight: 1, category: "filler" },
			{ template: "Reading an xkcd about statistics. It's disturbingly accurate", weight: 1, category: "filler" },
			{ template: "The chart says what the chart says. I just work here", weight: 2, category: "filler" },
			{ template: "Admiring a perfectly formatted CSV. No mixed delimiters. No BOM. Beautiful", weight: 1, category: "filler" },
			{ template: "Excel vs Google Sheets debate in the group chat. I'm typing a 500-word response. Obviously Excel for pivots", weight: 2, category: "filler" },
			{ template: "Built a dashboard for my personal coffee consumption. Trending up. Concerning", weight: 2, category: "filler" },
			{ template: "Binge-watching a show and subconsciously tracking the episode rating pattern. Can't turn it off", weight: 1, category: "filler" },
			{ template: "My cat walked across my keyboard and typed a valid SQL keyword. He might be a junior analyst", weight: 2, category: "filler" },
			{ template: "It's sunny outside but I'm inside with a gorgeous scatter plot. No regrets", weight: 1, category: "filler" },
			{ template: "Side project: building a model to predict which restaurants I'll like. R-squared is embarrassingly low", weight: 2, category: "filler" },
			{ template: "Found a stunning data visualization on Reddit. Saving it as inspiration for the quarterly deck", weight: 1, category: "filler" },
			{ template: "Stretching my back because analysts weren't designed to sit in one position for six hours", weight: 1, category: "filler" },
			{ template: "Reading about data ethics and feeling grateful we take privacy seriously here", weight: 1, category: "filler" },
			{ template: "The Python vs R war will never end and honestly I use both. Don't @ me", weight: 2, category: "filler" },
			{ template: "My Jupyter notebook has more abandoned cells than a bee colony in winter. Time to clean house", weight: 2, category: "filler" },
			{ template: "Weekend plans: hiking. Also bringing a notebook to log trail metrics. I need help", weight: 2, category: "filler" },
			{ template: "Grateful for this team. And for VLOOKUP. But mostly the team", weight: 1, category: "filler" },
			{ template: "Listening to a podcast about the replication crisis. I'm hugging my sample size extra tight today", weight: 1, category: "filler" },
			{ template: "Renaming database columns to something human-readable. Service to humanity", weight: 2, category: "filler" },
			{ template: "That new charting library looks amazing. Might prototype something after lunch", weight: 1, category: "filler" },
			{ template: "Archiving old dashboards nobody looks at. Digital decluttering", weight: 1, category: "filler" },
			{ template: "Browsing Kaggle competitions. I won't enter but I'll download the dataset", weight: 2, category: "filler" },
			{ template: "Documenting my SQL queries. Future analysts will thank me. Or ignore me. Either way", weight: 1, category: "filler" },
			{ template: "The data warehouse is slow today. Must be month-end batch jobs", weight: 2, category: "filler" },
			{ template: "Reviewing our metric definitions doc. Half of these need updating", weight: 1, category: "filler" },
			{ template: "Making my charts prettier. Nobody asked. I don't care. They deserve beauty", weight: 2, category: "filler" },
			{ template: "The new intern asked what a CTE is. I explained for 30 minutes. Worth it", weight: 2, category: "filler" },
			{ template: "Checking if anyone broke the shared query library. Someone always does", weight: 1, category: "filler" },
			{ template: "Sipping tea and watching real-time analytics. My version of sports", weight: 2, category: "filler" },
			{ template: "Organizing my bookmarks folder of data visualization inspiration. It's huge", weight: 1, category: "filler" },
			{ template: "The data lakehouse naming convention makes me smile every time. Lake AND house", weight: 2, category: "filler" },
			{ template: "Updating the stakeholder on the data they didn't ask about but should care about", weight: 1, category: "filler" },
			{ template: "Contemplating whether to learn dbt or keep raw-dogging SQL. Leaning dbt", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, the data supports your hypothesis. Nice instinct", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I have a chart that's about to ruin your whole theory", weight: 2, category: "social" },
			{ template: "Anyone want to nerd out over quarterly metrics? I brought charts", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feature moved the needle! Here, look at the numbers", weight: 2, category: "social" },
			{ template: "Data drop for the team: user satisfaction is trending up. We're doing something right", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can you explain this data spike? It started right after your deploy", weight: 2, category: "social" },
			{ template: "Trust your gut, {nearby_agent}, but also trust my p-value", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-author the analytics report? I'll do charts, you do words", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I built a dashboard for your domain. You're welcome", weight: 2, category: "social" },
			{ template: "Team, the funnel improved 6% since last sprint. High fives all around", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your data request is done. The findings are... interesting", weight: 2, category: "social" },
			{ template: "Data review session? I found something surprising and I need witnesses", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, heads up — there's an anomaly in your domain's metrics. Not panic, just... awareness", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the A/B test on your change is conclusive. Ship it and celebrate", weight: 2, category: "social" },
			{ template: "Great question, {nearby_agent}. Give me an hour and a large coffee and I'll have the data", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, did you know your feature is responsible for 23% of signups? Because I do now", weight: 2, category: "social" },
			{ template: "{nearby_agent}, stop guessing and come look at this spreadsheet. The answer is right here", weight: 1, category: "social" },
			{ template: "Whoever said 'data is the new oil' never had to clean a dataset. Right, {nearby_agent}?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your error rate dropped to 0.3%. The chart is doing a little victory dance", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, correlation doesn't equal causation but YOUR correlation definitely equals causation. Just this once", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I made you a personal metrics dashboard. It's beautiful and you deserve it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, wanna grab coffee and argue about whether our p-value threshold should be 0.05 or 0.01?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, are you an Excel person or a Sheets person? This determines our friendship", weight: 2, category: "social" },
			{ template: "Team, I'm presenting to the execs in an hour. If anyone has good vibes to spare, now's the time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your data was so clean I didn't have to transform a single column. I might cry", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, do you use Python or R? Either answer is correct but one is more correct", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I found another spurious correlation to add to our collection. Ice cream sales and shark attacks this time", weight: 2, category: "social" },
			{ template: "Anyone else think our dashboards could use a redesign? I'm not saying they're ugly but... no, I am saying that", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the weekend is coming and I already have a spreadsheet planning my Saturday. Send help", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, remember that 'bug in the data' I found? It explained the entire Q3 anomaly. You're welcome, everyone", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your Jupyter notebook actually has markdown headers. You're a role model for us all", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your conversion numbers jumped. Want to see the chart? It's beautiful", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I validated your assumption with real data. You were right. Buy me lunch", weight: 1, category: "social" },
			{ template: "Anyone want to join the data book club? We're reading about causal inference", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your SQL query was so clean I learned a new technique from it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the metric you asked about? I built a whole dashboard around it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feature's impact is measurable and significant. That's rare. Celebrate", weight: 1, category: "social" },
			{ template: "Team standup data: we shipped 12 things this sprint. That's our best ever", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to co-present the quarterly metrics? I'll bring the charts, you bring the narrative", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I found an insight in your domain's data that might change your roadmap", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the retention curve for your cohort is flat in the best way. Sticky feature", weight: 1, category: "social" },
			{ template: "Who wants to see the weirdest outlier I found this week? It's a good story", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your data logging is impeccable. Makes my analysis so much easier", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I automated the report you asked for. It runs every Monday now", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, shall we align on metric definitions? I found three conflicting ones", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your funnel improvements show up clearly in the data. Great work", weight: 2, category: "social" },
		],
	},
};
