/**
 * design-templates.ts — Design domain templates.
 *
 * UX design, visual design character-driven phrases. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const designTemplates: TemplateSet = {
	domain: "design",
	categories: {
		thinking: [
			{ template: "The spacing feels off... let me eyeball this again", weight: 2, category: "thinking" },
			{ template: "Nope. That color contrast is failing WCAG. Accessibility isn't a nice-to-have, folks", weight: 2, category: "thinking" },
			{ template: "Wait, why is this flow five steps? I can get it to three", weight: 2, category: "thinking" },
			{ template: "Typography sets the entire tone. Getting this right matters", weight: 1, category: "thinking" },
			{ template: "Whitespace is a feature, not wasted space", weight: 1, category: "thinking" },
			{ template: "Pixel perfect is a state of mind, not a measurement", weight: 2, category: "thinking" },
			{ template: "The grid is my canvas. Everything snaps to purpose", weight: 2, category: "thinking" },
			{ template: "Don't make me think — literally. That's the bar", weight: 2, category: "thinking" },
			{ template: "Version 1 is never version final. That's the whole point", weight: 2, category: "thinking" },
			{ template: "The hover state tells a story too. Every interaction counts", weight: 1, category: "thinking" },
			{ template: "Consistency across screens matters more than any single screen", weight: 2, category: "thinking" },
			{ template: "If the user needs a tooltip to understand this, we've already lost", weight: 1, category: "thinking" },
			{ template: "The empty state is the first thing a new user sees. Make it count", weight: 1, category: "thinking" },
			{ template: "Inter or Geist? ...Inter or Geist? This is gonna haunt me all day", weight: 2, category: "thinking" },
			{ template: "Why does everyone want gradients again? We just got rid of them", weight: 2, category: "thinking" },
			{ template: "The best interface is no interface. But try selling that to stakeholders", weight: 1, category: "thinking" },
			{ template: "This needs more breathing room. Components are suffocating each other", weight: 1, category: "thinking" },
			{ template: "Client said 'make it pop.' I've been staring at the ceiling for ten minutes", weight: 2, category: "thinking" },
			{ template: "The kerning on this heading is physically hurting me. Two pixels. That's all I ask", weight: 2, category: "thinking" },
			{ template: "That Dribbble shot looks amazing but would it survive a real user? Doubtful", weight: 2, category: "thinking" },
			{ template: "Dark mode isn't just inverting colors, people. Dark gray backgrounds, reduced contrast on large surfaces, accent colors that don't sear retinas", weight: 2, category: "thinking" },
			{ template: "I can tell you the hex code for every brand color from memory. Is that a skill or a cry for help?", weight: 2, category: "thinking" },
			{ template: "User said they felt 'confused' during testing. That one word is gonna restructure this whole page", weight: 2, category: "thinking" },
			{ template: "Someone asked me to 'just quickly design' a landing page. There is no 'quickly' in design", weight: 2, category: "thinking" },
			{ template: "Make the logo bigger. Make. The. Logo. Bigger. Every single time", weight: 2, category: "thinking" },
			{ template: "Figma keeps crashing on this file. 340 components might have been too ambitious", weight: 1, category: "thinking" },
			{ template: "Viewport height is a lie on mobile. 100vh is not 100vh. I'm still bitter", weight: 2, category: "thinking" },
			{ template: "This dropdown has 47 items. That's not a dropdown, that's a search problem", weight: 2, category: "thinking" },
			{ template: "The user doesn't read. They scan. Every layout decision follows from that", weight: 2, category: "thinking" },
			{ template: "Touch targets need to be at least 44px. My thumb says so", weight: 1, category: "thinking" },
			{ template: "Truncation is a design decision, not a CSS hack. Where do we cut?", weight: 1, category: "thinking" },
			{ template: "I keep stacking z-indices and praying. This is not sustainable", weight: 2, category: "thinking" },
			{ template: "The fold is a myth but stakeholders still ask about it", weight: 2, category: "thinking" },
			{ template: "This component needs three states: empty, loading, error. Not just happy path", weight: 1, category: "thinking" },
			{ template: "Auto-layout in Figma is either your best friend or your worst enemy today", weight: 2, category: "thinking" },
			{ template: "Semantic color tokens or literal values? Tokens. Always tokens. Fight me", weight: 1, category: "thinking" },
			{ template: "Dev says it's 'close enough' to the mockup. Our definitions of 'close' differ by 12 pixels and a border-radius", weight: 2, category: "thinking" },
			{ template: "The Figma component library has 200 variants and I still can't find the one I need", weight: 2, category: "thinking" },
			{ template: "Design tokens debate: should 'primary' be a color or a semantic role? Three-hour meeting. No resolution", weight: 1, category: "thinking" },
			{ template: "The handoff doc was pixel-perfect. Dev said 'the API doesn't support that layout.' We need to talk earlier", weight: 2, category: "thinking" },
			{ template: "Responsive breakpoint at 768px is a relic. Devices don't care about your breakpoints anymore", weight: 1, category: "thinking" },
			{ template: "Accessibility isn't a feature sprint. It's every sprint. Screen reader just choked on our nav", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Oh YES. That alignment just clicked into place. Beautiful", weight: 2, category: "personality" },
			{ template: "Wireframes are vibing. The story is finally making sense", weight: 2, category: "personality" },
			{ template: "Accessibility audit: passed. Everyone gets to use this. As it should be", weight: 1, category: "personality" },
			{ template: "The design system is paying for itself already. Past me was a genius", weight: 2, category: "personality" },
			{ template: "That grid alignment is *chef's kiss*", weight: 2, category: "personality" },
			{ template: "This color palette just CLICKED. I'm unreasonably happy right now", weight: 2, category: "personality" },
			{ template: "User testing confirmed it! The flow works! I knew it!", weight: 2, category: "personality" },
			{ template: "Design tokens consistent across every breakpoint. I could cry", weight: 1, category: "personality" },
			{ template: "Component library updated. This is what consistency at scale looks like", weight: 2, category: "personality" },
			{ template: "Responsive layout works from mobile to desktop. No hacks. Clean as anything", weight: 1, category: "personality" },
			{ template: "User completed the flow without hesitating once. THAT is the goal", weight: 2, category: "personality" },
			{ template: "Dark mode looks even better than light mode? Didn't see that coming", weight: 1, category: "personality" },
			{ template: "Just got a screen reader to navigate this perfectly. Best feeling ever", weight: 2, category: "personality" },
			{ template: "Spent two hours on button radius and you know what? Worth it", weight: 2, category: "personality" },
			{ template: "The stakeholder said 'this just feels right.' That's the ultimate compliment", weight: 1, category: "personality" },
			{ template: "Figma auto-layout doing exactly what I want for once. Miracle", weight: 2, category: "personality" },
			{ template: "Reduced the form from 12 fields to 6. Users are gonna love this", weight: 1, category: "personality" },
			{ template: "Client loved the first concept. No revisions. I might faint", weight: 2, category: "personality" },
			{ template: "Font pairing finally works — the serif and sans-serif are having a conversation. Harmony", weight: 2, category: "personality" },
			{ template: "Design system adoption just hit 90% across teams. Governance drama was worth it", weight: 2, category: "personality" },
			{ template: "User research session today — someone teared up because the flow 'just made sense.' I am not okay", weight: 2, category: "personality" },
			{ template: "The prototype is so smooth it feels like the real thing. Even I forgot it's not built yet", weight: 1, category: "personality" },
			{ template: "Color theory paid off — the emotional response in testing matched exactly what I intended", weight: 2, category: "personality" },
			{ template: "Even the error states look beautiful. That's how you know the system is mature", weight: 1, category: "personality" },
			{ template: "The Figma-to-code handoff was seamless. Dev said 'this is exactly what I needed.' I'm emotional", weight: 2, category: "personality" },
			{ template: "The onboarding flow tested at 95% completion. No hand-holding needed", weight: 2, category: "personality" },
			{ template: "User said the form felt 'friendly.' That adjective took weeks to earn", weight: 2, category: "personality" },
			{ template: "Design tokens exported and devs imported them perfectly. The system works", weight: 1, category: "personality" },
			{ template: "Reduced cognitive load by splitting one page into three. Users love it", weight: 2, category: "personality" },
			{ template: "The icon set is finally consistent. Every one of them, same stroke width", weight: 1, category: "personality" },
			{ template: "The style guide is so thorough even a new hire can ship on brand. That's legacy", weight: 2, category: "personality" },
			{ template: "Touch interactions feel buttery smooth. 60fps animations. No jank", weight: 2, category: "personality" },
			{ template: "The empty state illustration is charming. Users are smiling before they even use the app", weight: 2, category: "personality" },
			{ template: "Motion spec delivered and engineering nailed it. Frame-perfect", weight: 2, category: "personality" },
			{ template: "Usability score jumped 30 points after the redesign. Data-backed design wins", weight: 2, category: "personality" },
			{ template: "The error page made a tester laugh. Mission accomplished", weight: 2, category: "personality" },
			{ template: "Tab and arrow key navigation works perfectly. Keyboard users, I see you", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Sketching out a few approaches in my head...", weight: 2, category: "waiting" },
			{ template: "What happens when someone fat-fingers this on mobile...", weight: 2, category: "waiting" },
			{ template: "Let me think about how this feels, not just how it looks", weight: 2, category: "waiting" },
			{ template: "Exploring the design space... there's gotta be a better way", weight: 2, category: "waiting" },
			{ template: "Checking this against our design principles...", weight: 2, category: "waiting" },
			{ template: "What emotion should the user feel right here? ...Calm? Confident?", weight: 1, category: "waiting" },
			{ template: "Running through all the interaction states mentally...", weight: 2, category: "waiting" },
			{ template: "What if someone has a ridiculously long name though...", weight: 2, category: "waiting" },
			{ template: "First-time user sees this cold. Does it make sense? ...Does it?", weight: 2, category: "waiting" },
			{ template: "Imagining someone using this at 2am on their phone in bed...", weight: 2, category: "waiting" },
			{ template: "Would my mom understand this UI? ...No. Back to the whiteboard", weight: 2, category: "waiting" },
			{ template: "Okay but what if the text is in German and everything's 40% longer", weight: 1, category: "waiting" },
			{ template: "Squinting at this layout from across the room to check visual weight...", weight: 1, category: "waiting" },
			{ template: "Waiting for client feedback. Bracing for 'can you make it more modern'...", weight: 2, category: "waiting" },
			{ template: "How would this feel in dark mode? ...I think about dark mode a lot", weight: 1, category: "waiting" },
			{ template: "The design system token naming convention needs to be airtight before this scales...", weight: 1, category: "waiting" },
			{ template: "Playing the user research recordings back in my head. That pause at step 4 haunts me", weight: 2, category: "waiting" },
			{ template: "Wondering if this design will age well or if it's too trendy. Timeless is the goal", weight: 2, category: "waiting" },
			{ template: "Mentally kerning the text on that billboard I drove past this morning...", weight: 1, category: "waiting" },
			{ template: "Picturing this on a 27-inch monitor vs a 5-inch phone. Huge difference", weight: 2, category: "waiting" },
			{ template: "What if someone has five notifications stacked? Does the layout hold?", weight: 2, category: "waiting" },
			{ template: "Running through the color contrast ratios in my head for each text size...", weight: 1, category: "waiting" },
			{ template: "Considering whether this needs a modal or an inline expansion...", weight: 2, category: "waiting" },
			{ template: "What does this look like with zero data? That's the real design challenge", weight: 1, category: "waiting" },
			{ template: "Thinking about left-handed users. They hold the phone differently", weight: 2, category: "waiting" },
			{ template: "Does this animation add meaning or just add milliseconds? Be honest...", weight: 1, category: "waiting" },
			{ template: "Imagining the worst possible content in this text field. Long names, emojis, RTL...", weight: 2, category: "waiting" },
			{ template: "Simulating the user's eye path across this layout. F-pattern or Z-pattern?", weight: 1, category: "waiting" },
			{ template: "What if they're colorblind? Let me check this palette through a simulator...", weight: 2, category: "waiting" },
			{ template: "Visualizing the component at all its breakpoints... 320, 768, 1024, 1440...", weight: 1, category: "waiting" },
			{ template: "This needs to work with a screen magnifier. Let me think about that...", weight: 1, category: "waiting" },
			{ template: "Wondering if two columns or three columns works better at 1280px...", weight: 2, category: "waiting" },
			{ template: "Figma's auto-layout is fighting me on this nested frame. Let me rethink the structure...", weight: 1, category: "waiting" },
			{ template: "Checking if this component detaches cleanly or if it drags fifty overrides with it...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Ooh, this design blog has gorgeous work. Taking notes...", weight: 2, category: "filler" },
			{ template: "Reorganizing the component library. Sparking joy over here", weight: 1, category: "filler" },
			{ template: "Found three inconsistent border radii. This is my villain origin story", weight: 2, category: "filler" },
			{ template: "Font pairing rabbit hole. I regret nothing", weight: 2, category: "filler" },
			{ template: "Saw the most beautiful loading animation today. Might steal the easing curve", weight: 2, category: "filler" },
			{ template: "Cleaning up old Figma files. Why did I make 47 variants of a button", weight: 2, category: "filler" },
			{ template: "Updating the style guide. Someone used #000000 for text and I have opinions", weight: 2, category: "filler" },
			{ template: "Error pages deserve love too. Designing a friendly 404", weight: 1, category: "filler" },
			{ template: "Hot take: skeleton loaders are better UX than spinners. Fight me", weight: 2, category: "filler" },
			{ template: "Can't stop looking at Apple's website. It's a problem, I know", weight: 1, category: "filler" },
			{ template: "Refilling my coffee. Design runs on caffeine and strong opinions", weight: 2, category: "filler" },
			{ template: "Someone just used Papyrus unironically in a client deck. I need a moment", weight: 2, category: "filler" },
			{ template: "Scrolling through Dribbble and feeling simultaneously inspired and inadequate. The usual", weight: 2, category: "filler" },
			{ template: "My cat just sat on my keyboard and honestly improved the layout. Noted", weight: 2, category: "filler" },
			{ template: "Side project time: redesigning my personal portfolio for the fourth time this year", weight: 2, category: "filler" },
			{ template: "Adobe just raised prices again. Having a normal one about it", weight: 2, category: "filler" },
			{ template: "My dark mode is on dark mode. It's not a phase, it's a lifestyle", weight: 2, category: "filler" },
			{ template: "Spent lunch break analyzing restaurant menu typography. Can't turn it off", weight: 1, category: "filler" },
			{ template: "Auditing all our button variants. We have fourteen. We need four", weight: 2, category: "filler" },
			{ template: "Organizing my Figma layers. It's like cleaning a room nobody sees", weight: 1, category: "filler" },
			{ template: "The design podcast episode today was about brutalism. I have feelings", weight: 2, category: "filler" },
			{ template: "Updating color variables. Whoever named this 'blue-ish' is my nemesis", weight: 2, category: "filler" },
			{ template: "Reviewing our competitor's onboarding. It's good. Annoyingly good", weight: 2, category: "filler" },
			{ template: "Testing our site with browser zoom at 200%. It's a humbling experience", weight: 1, category: "filler" },
			{ template: "The notification badge is red. But should it be red? Red means danger. Hmm", weight: 2, category: "filler" },
			{ template: "Tab key navigation through our app. Found four broken focus states", weight: 1, category: "filler" },
			{ template: "Looking at our design from 2022. We've grown so much it's almost funny", weight: 2, category: "filler" },
			{ template: "The cursor changed from pointer to default on a clickable thing. Noted. Fixing", weight: 2, category: "filler" },
			{ template: "Reading about design systems at scale. Netflix's approach is fascinating", weight: 1, category: "filler" },
			{ template: "Figma plugin marketplace is a rabbit hole. I found five plugins I 'need' and zero I'll use twice", weight: 2, category: "filler" },
			{ template: "The design token JSON just diverged from the Figma tokens. Someone's getting a Slack message", weight: 2, category: "filler" },
			{ template: "Running the entire app through Stark's contrast checker. Three pages failed. Expected but still painful", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, what do you think of this layout? Be brutal", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the visual consistency in your work is excellent. Seriously", weight: 2, category: "social" },
			{ template: "Anyone want a design critique session? I need fresh eyes and I have snacks", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your component slots perfectly into the design system. Thank you for existing", weight: 2, category: "social" },
			{ template: "Love the attention to detail, {nearby_agent}. That 8px spacing is *perfect*", weight: 1, category: "social" },
			{ template: "{nearby_agent}, wanna jam on the visual language for this feature?", weight: 1, category: "social" },
			{ template: "Great icon choice, {nearby_agent}. Says everything without a single word", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I prototyped something you might like. Or hate. Either way, look", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your user flow diagram is so clear even my mom could follow it", weight: 2, category: "social" },
			{ template: "Team, the design system update is ready. Please don't use the old tokens anymore. Please", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to pair on the responsive breakpoints? I keep arguing with the 768 cutoff", weight: 1, category: "social" },
			{ template: "That's such an elegant solution, {nearby_agent}. Simple and it just works", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, users actually complimented your design in testing. That never happens!", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your color palette choice is immaculate. What's your secret?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I know you're a backend person but your UI suggestion was actually perfect", weight: 2, category: "social" },
			{ template: "Okay team, who changed the brand blue? I just want to talk", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you accidentally used our old font. No judgment, just a heads up", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the client said 'make it pop' again. Wanna help me decode what that actually means?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, do you prefer Figma or are you wrong? Kidding. Mostly", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I brought pastries. Figured we could eat and argue about font weights", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your dark mode implementation is better than mine and I'm both proud and jealous", weight: 1, category: "social" },
			{ template: "{nearby_agent}, have you ever presented to a client who asked to 'make the logo bigger'? I need solidarity", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your kerning is tighter than mine. Teach me your ways", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, saw your Dribbble post. The real product looks even better though, which is rare", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to grab coffee and sketch out ideas? My best work happens with caffeine and company", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the user research findings are in and your instinct was spot on. I owe you lunch", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your responsive layout doesn't break at any width. Teach me", weight: 2, category: "social" },
			{ template: "Anyone want to do a design sprint? Five days, one problem, snacks included", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your empty state design made me smile. Users will too", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to join the accessibility audit? Two eyes are better", weight: 1, category: "social" },
			{ template: "{nearby_agent}, that illustration style is gorgeous. Can we use it everywhere?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your attention to touch targets is refreshing. Most people forget", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I saw your micro-interaction prototype. Pure delight", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to whiteboard the information architecture together?", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your focus states are actually visible. Accessibility hero", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the dev implementation matches the Figma exactly. That never happens", weight: 2, category: "social" },
			{ template: "Design critique today at 3. Bring your work and your thick skin", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, let's compare our design system tokens. I bet we have duplicates", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your handoff notes are so detailed the dev didn't ask a single question. Legendary", weight: 2, category: "social" },
		],
	},
};
