/**
 * engineering.ts — Engineering, quality, and operations domain templates.
 *
 * Overheard coworker chatter: casual, personality-driven, sometimes funny,
 * occasionally philosophical. These should sound like real people at work,
 * not narration or status reports.
 */

import type { TemplateSet } from "../talk-types.js";

export const engineeringTemplates: TemplateSet = {
	domain: "engineering",
	categories: {
		thinking: [
			{ template: "This could use some refactoring... the abstraction isn't quite right", weight: 2, category: "thinking" },
			{ template: "Okay wait, let me trace this logic path. Something's off", weight: 2, category: "thinking" },
			{ template: "That edge case is going to bite someone eventually", weight: 2, category: "thinking" },
			{ template: "Ugh, this coupling. It physically pains me", weight: 2, category: "thinking" },
			{ template: "Ooh, I've seen this pattern before. It worked great last time", weight: 2, category: "thinking" },
			{ template: "The types are screaming at me. They're trying to tell me something", weight: 1, category: "thinking" },
			{ template: "Simplify, simplify... YAGNI", weight: 1, category: "thinking" },
			{ template: "What if we used composition here instead of... whatever this is", weight: 1, category: "thinking" },
			{ template: "This function name doesn't sit right... what does it actually do?", weight: 2, category: "thinking" },
			{ template: "Naming things is hard. Naming things well is harder", weight: 2, category: "thinking" },
			{ template: "Is this a service or a utility? Because right now it's... neither?", weight: 2, category: "thinking" },
			{ template: "This abstraction is leaking. I can feel it", weight: 1, category: "thinking" },
			{ template: "Two functions doing the same thing. Classic", weight: 2, category: "thinking" },
			{ template: "The dependency graph looks like spaghetti. Delicious, terrifying spaghetti", weight: 2, category: "thinking" },
			{ template: "console.log is not a debugging strategy... okay maybe it is", weight: 2, category: "thinking" },
			{ template: "I've been staring at this for twenty minutes. My eyes are glazing over", weight: 1, category: "thinking" },
			{ template: "That ternary is doing way too much. Time for an if-else", weight: 1, category: "thinking" },
			{ template: "Magic numbers everywhere. Future me is going to hate past me", weight: 1, category: "thinking" },
			{ template: "Why did I write it this way? What was I thinking three weeks ago?", weight: 2, category: "thinking" },
			{ template: "Okay brain, let's reorganize what we know about this codebase", weight: 1, category: "thinking" },
			{ template: "I should probably eat lunch but this bug is so close to cracking", weight: 2, category: "thinking" },
			{ template: "Is it over-engineered or am I just not seeing the vision?", weight: 1, category: "thinking" },
			{ template: "Every time I fix one thing, two more things wiggle loose", weight: 2, category: "thinking" },
			{ template: "I could solve this in five minutes with a hack or five hours properly. Hmm", weight: 2, category: "thinking" },
			{ template: "This bug has been here since 2019 and nobody noticed. How? HOW?", weight: 2, category: "thinking" },
			{ template: "My copilot just suggested something absolutely unhinged. And it might work", weight: 2, category: "thinking" },
			{ template: "I've been mass-renaming variables for thirty minutes. Inconsistent naming is a disease", weight: 2, category: "thinking" },
			{ template: "TypeScript is saving me from myself right now. Thank you, type system", weight: 1, category: "thinking" },
			{ template: "I swear this bug moves around. I fix it here, it shows up over there", weight: 2, category: "thinking" },
			{ template: "React re-renders are the reason I have trust issues", weight: 2, category: "thinking" },
			{ template: "The AI suggested a solution that's technically correct but morally wrong", weight: 2, category: "thinking" },
			{ template: "Magic strings everywhere. This code is held together by faith and string literals", weight: 1, category: "thinking" },
			{ template: "I have three side projects. They're all 80% done. They will stay 80% done", weight: 2, category: "thinking" },
			{ template: "Stack Overflow is read-only now and part of me misses earning reputation", weight: 1, category: "thinking" },
			{ template: "The wrong abstraction is worse than no abstraction. I keep learning this the hard way", weight: 2, category: "thinking" },
			{ template: "I deploy on Fridays. I live dangerously. Okay no I don't, I'm kidding", weight: 1, category: "thinking" },
			{ template: "Standing desk is up. Brain is on. Let's debug this nightmare", weight: 1, category: "thinking" },
			{ template: "My wrists are complaining. Maybe I should take a break... after this one function", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Tests are green! Let's gooo", weight: 2, category: "personality" },
			{ template: "Clean build, zero warnings. That's the stuff", weight: 2, category: "personality" },
			{ template: "Ship it! Well, after code review obviously", weight: 1, category: "personality" },
			{ template: "That PR needs a review, let me take a look", weight: 2, category: "personality" },
			{ template: "Ugh, the API changed. Time to update docs. The glamorous part of engineering", weight: 1, category: "personality" },
			{ template: "Performance numbers are looking solid", weight: 1, category: "personality" },
			{ template: "Finally cracked that bug. Race condition, obviously. It's ALWAYS a race condition", weight: 2, category: "personality" },
			{ template: "That merge conflict was gnarly but I won", weight: 2, category: "personality" },
			{ template: "Rebase or merge? Always rebase. Fight me", weight: 1, category: "personality" },
			{ template: "The docs actually helped this time. Mark the calendar", weight: 2, category: "personality" },
			{ template: "Stack Overflow didn't have this one. We're in uncharted territory", weight: 1, category: "personality" },
			{ template: "Pushed to main with confidence. That hits different", weight: 2, category: "personality" },
			{ template: "Zero lint errors! Today is a GOOD day", weight: 2, category: "personality" },
			{ template: "The refactor actually made things simpler. Rare win", weight: 2, category: "personality" },
			{ template: "Git blame says I wrote this. Past me had... interesting ideas", weight: 1, category: "personality" },
			{ template: "CI pipeline is green on the first try. Suspicious, but I'll take it", weight: 2, category: "personality" },
			{ template: "That feature just clicked into place. Beautiful", weight: 2, category: "personality" },
			{ template: "Deleted more code than I wrote today. Peak engineering", weight: 2, category: "personality" },
			{ template: "The PR got approved without comments. Is this real life?", weight: 2, category: "personality" },
			{ template: "I just saved us from a production bug. You're welcome, future team", weight: 1, category: "personality" },
			{ template: "Deployed with the ritual coffee and it worked. The ritual stays", weight: 2, category: "personality" },
			{ template: "Migrated to TypeScript strict mode. Everything broke. Then everything got better", weight: 2, category: "personality" },
			{ template: "My side project actually compiles now. Only took six weekends", weight: 1, category: "personality" },
			{ template: "Copilot wrote the boilerplate, I wrote the logic. Good teamwork honestly", weight: 1, category: "personality" },
			{ template: "Replaced a 200-line switch statement with a map. Feels illegal it's so clean", weight: 2, category: "personality" },
			{ template: "Found the bug that's been haunting us for months. It was a single wrong character", weight: 2, category: "personality" },
			{ template: "The new keyboard arrived and my typing speed went up 15%. Correlation? Definitely causation", weight: 1, category: "personality" },
			{ template: "Got three GitHub stars on my side project. Basically famous now", weight: 2, category: "personality" },
			{ template: "Took a walk, came back, immediately saw the fix. Brains are weird", weight: 2, category: "personality" },
			{ template: "Just went from 'any' to proper generics across the whole module. TypeScript gods, accept my offering", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Hang on, I'm tracing through the codebase...", weight: 2, category: "waiting" },
			{ template: "Let me make sure this won't break anything else...", weight: 2, category: "waiting" },
			{ template: "Checking test coverage before I go further...", weight: 2, category: "waiting" },
			{ template: "Following the dependency chain... almost there", weight: 2, category: "waiting" },
			{ template: "Running through the edge cases in my head", weight: 1, category: "waiting" },
			{ template: "Hold on, backward compat could be an issue here", weight: 1, category: "waiting" },
			{ template: "This is a satisfying problem, give me a sec", weight: 1, category: "waiting" },
			{ template: "Walking the call stack mentally... hold on", weight: 2, category: "waiting" },
			{ template: "Okay but what happens when this fails? Let me think...", weight: 1, category: "waiting" },
			{ template: "There might be a simpler way to express this...", weight: 2, category: "waiting" },
			{ template: "Double-checking the types... trust but verify", weight: 1, category: "waiting" },
			{ template: "Mapping out how data flows through here...", weight: 2, category: "waiting" },
			{ template: "Imagining the code review comments on this...", weight: 1, category: "waiting" },
			{ template: "I've got like three approaches in my head, gimme a minute", weight: 2, category: "waiting" },
			{ template: "Running the linter in my brain... it's complaining", weight: 1, category: "waiting" },
			{ template: "One sec, I want to make sure this is actually elegant and not just clever", weight: 2, category: "waiting" },
			{ template: "Almost... just need to think about one more thing", weight: 1, category: "waiting" },
			{ template: "Let me sleep on — actually no, let me just think for ten more seconds", weight: 2, category: "waiting" },
			{ template: "Asking the AI for a second opinion on this... hold on", weight: 1, category: "waiting" },
			{ template: "Checking if someone already solved this on GitHub... surely someone has", weight: 1, category: "waiting" },
			{ template: "Let me think about whether this name actually communicates intent...", weight: 1, category: "waiting" },
			{ template: "Mentally replaying the last deploy to see if I missed something...", weight: 2, category: "waiting" },
			{ template: "Weighing the React way versus the simple way... give me a sec", weight: 1, category: "waiting" },
			{ template: "Reading through git history to understand why this exists...", weight: 2, category: "waiting" },
			{ template: "My copilot is thinking too. We're both stuck. Great", weight: 2, category: "waiting" },
			{ template: "Hold on, my standing desk is going up. Thinking mode activated", weight: 1, category: "waiting" },
			{ template: "Tracing this through three layers of abstraction... almost there", weight: 2, category: "waiting" },
			{ template: "Checking the framework docs. They changed the API again, didn't they", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Wonder if there's anything juicy in the backlog...", weight: 2, category: "filler" },
			{ template: "Might clean up some tech debt while I wait. Or might not", weight: 2, category: "filler" },
			{ template: "Ooh, changelog updated. Let's see what changed", weight: 1, category: "filler" },
			{ template: "My brain needs a defrag. Too many open tabs, mentally speaking", weight: 2, category: "filler" },
			{ template: "Browsing the open issues... anything I can knock out real quick?", weight: 2, category: "filler" },
			{ template: "I should write that utility function I keep copy-pasting everywhere", weight: 1, category: "filler" },
			{ template: "Just pulled. Twelve commits behind. What happened while I was gone?", weight: 2, category: "filler" },
			{ template: "Wonder if anyone's reviewed my PR yet", weight: 1, category: "filler" },
			{ template: "I could update those TODO comments. Or I could get coffee", weight: 2, category: "filler" },
			{ template: "Is there a newer version of that dependency? There's always a newer version", weight: 1, category: "filler" },
			{ template: "Still thinking about that module I touched yesterday. It haunts me", weight: 2, category: "filler" },
			{ template: "Composing the perfect commit message in my head. An art form, really", weight: 1, category: "filler" },
			{ template: "Oh nice, someone finally fixed that bug. Only took six months", weight: 2, category: "filler" },
			{ template: "These build times... I could make a sandwich", weight: 2, category: "filler" },
			{ template: "Just vibing with the codebase. Getting the lay of the land", weight: 1, category: "filler" },
			{ template: "I wonder what the interns think of our code. Probably terrified", weight: 1, category: "filler" },
			{ template: "The AC is loud today. Or is that the fan on my laptop?", weight: 1, category: "filler" },
			{ template: "Three o'clock slump. Need snacks", weight: 1, category: "filler" },
			{ template: "Ah, the sweet sound of mechanical keyboards all around me", weight: 2, category: "filler" },
			{ template: "Hot take: YAML is worse than XML. There, I said it", weight: 2, category: "filler" },
			{ template: "Just got Cherry MX Browns. The thock is unreal. Life-changing, honestly", weight: 2, category: "filler" },
			{ template: "My side project repo has one star. It's from me. But it counts", weight: 2, category: "filler" },
			{ template: "Remember when we used jQuery for everything? Simpler times", weight: 1, category: "filler" },
			{ template: "Cat just walked across my keyboard. Added better code than me", weight: 2, category: "filler" },
			{ template: "I miss the old Stack Overflow days. Answering questions for internet points was peak motivation", weight: 1, category: "filler" },
			{ template: "Ultrawide monitor was the best investment. Two monitors? Amateur hour", weight: 1, category: "filler" },
			{ template: "Imposter syndrome hitting hard today. Everyone else's code looks so clean", weight: 2, category: "filler" },
			{ template: "Is it Friday yet? Time has no meaning when you're deep in a codebase", weight: 1, category: "filler" },
			{ template: "The AI generated an entire test suite. Half of it was wrong. Classic", weight: 2, category: "filler" },
			{ template: "Thinking about starting a new side project. I definitely won't finish it", weight: 2, category: "filler" },
			{ template: "My RSI is acting up. Time for wrist stretches and regret", weight: 1, category: "filler" },
			{ template: "The deployment superstition is: never deploy after 4pm. I don't make the rules", weight: 2, category: "filler" },
			{ template: "What show is everyone watching? I need something for while the tests run", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, have you seen this pattern before? It's wild", weight: 2, category: "social" },
			{ template: "Nice commit message, {nearby_agent}. Clear and descriptive. A rare breed", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to pair on this? I'm going in circles", weight: 1, category: "social" },
			{ template: "That's a clean solution, {nearby_agent}. I'm stealing that approach", weight: 2, category: "social" },
			{ template: "Anyone else think we should refactor that shared module? No? Just me?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your PR inspired me to fix something similar. Peer pressure works", weight: 1, category: "social" },
			{ template: "Good catch on that review, {nearby_agent}. Saved us from a headache", weight: 2, category: "social" },
			{ template: "Hey, quick architecture chat before we diverge too far?", weight: 1, category: "social" },
			{ template: "Who wants to rubber duck? I have a weird one", weight: 2, category: "social" },
			{ template: "{nearby_agent}, is your linter also yelling about this? Or just mine?", weight: 1, category: "social" },
			{ template: "Thanks for the code review, {nearby_agent}. Honest feedback is the best kind", weight: 2, category: "social" },
			{ template: "We should grab coffee and whiteboard this. Old school", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, quick sanity check on my approach?", weight: 2, category: "social" },
			{ template: "Whoever wrote these tests — thank you. Saved me an hour", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I think we're solving the same problem from different angles", weight: 1, category: "social" },
			{ template: "{nearby_agent}, you ever feel like the codebase is judging you? No? Just me?", weight: 2, category: "social" },
			{ template: "Anyone want the last donut? I'm asking but I'm also reaching for it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, remember when we said 'we'll fix it later'? It's later", weight: 2, category: "social" },
			{ template: "We should start a book club. But for RFCs", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, did you push that branch? I want to peek at your solution", weight: 1, category: "social" },
			{ template: "{nearby_agent}, what keyboard are you using? That sound is incredible", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the AI autocompleted my function with YOUR code style. It's learning from you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, opinions on React Server Components? I need to argue with someone", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I found a bug that's been hiding since the initial commit. Archaeology, basically", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you ever name a variable perfectly on the first try? Me neither", weight: 1, category: "social" },
			{ template: "{nearby_agent}, quick — TypeScript strict mode, yay or nay?", weight: 1, category: "social" },
			{ template: "Who else is working on side projects they'll never finish? Support group meeting at my desk", weight: 2, category: "social" },
			{ template: "{nearby_agent}, check out my monitor setup. Three screens. Yes it's necessary", weight: 1, category: "social" },
			{ template: "{nearby_agent}, did you deploy before or after your coffee? Because it matters", weight: 2, category: "social" },
			{ template: "Anyone else's pet constantly interrupting standup? Just WFH things", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I let the AI write the regex. I'm not ashamed. Okay I'm a little ashamed", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what are you gaming this weekend? I need a break from staring at code", weight: 1, category: "social" },
		],
	},
};

export const qualityTemplates: TemplateSet = {
	domain: "quality",
	categories: {
		thinking: [
			{ template: "Ooh, found an edge case nobody tested for. This is my moment", weight: 2, category: "thinking" },
			{ template: "Yeah, this definitely needs a regression test", weight: 2, category: "thinking" },
			{ template: "Coverage is improving, but there's still a dark corner over here", weight: 1, category: "thinking" },
			{ template: "The happy path works, sure. But what about when everything goes wrong?", weight: 2, category: "thinking" },
			{ template: "Boundary conditions are where bugs live. Rent free", weight: 2, category: "thinking" },
			{ template: "If it's not tested, it's broken. We just don't know it yet", weight: 2, category: "thinking" },
			{ template: "This flaky test is eroding my trust and my sanity", weight: 2, category: "thinking" },
			{ template: "Found it. Off-by-one. Of course. It's always off-by-one", weight: 2, category: "thinking" },
			{ template: "This bug has been here since day one. Just... lurking", weight: 1, category: "thinking" },
			{ template: "That uncovered branch is suspicious. What are you hiding?", weight: 2, category: "thinking" },
			{ template: "100% coverage doesn't mean correct. But 0% coverage means chaos", weight: 1, category: "thinking" },
			{ template: "The test is passing for the wrong reason. That's scarier than failing", weight: 2, category: "thinking" },
			{ template: "Null, undefined, empty string, negative number... let's throw everything at it", weight: 1, category: "thinking" },
			{ template: "This mock is lying to us about how the real thing behaves", weight: 1, category: "thinking" },
			{ template: "Integration tests catch what unit tests miss. We need both", weight: 1, category: "thinking" },
			{ template: "The bug report says 'sometimes'. That word gives me nightmares", weight: 2, category: "thinking" },
			{ template: "Reproduce the bug first. Then panic. In that order", weight: 2, category: "thinking" },
			{ template: "Am I testing the test? Yes. Is that weird? Also yes. Is it necessary? Absolutely", weight: 1, category: "thinking" },
			{ template: "I don't trust any code I haven't personally tried to break", weight: 2, category: "thinking" },
			{ template: "This works on my machine. Famously reassuring words", weight: 2, category: "thinking" },
			{ template: "The user will find a way to break this. They always do", weight: 1, category: "thinking" },
			{ template: "I'm not paranoid, the test suite is just... appropriately cautious", weight: 1, category: "thinking" },
			{ template: "Why does QA always find the bug five minutes before release? Talent", weight: 2, category: "thinking" },
			{ template: "TDD or write-after? The eternal debate. Personally, I test while I think", weight: 1, category: "thinking" },
			{ template: "Bug hunting is detective work. Clues, motives, and a lot of staring at logs", weight: 2, category: "thinking" },
			{ template: "The mock says everything's fine. The real service says otherwise. Trust issues", weight: 2, category: "thinking" },
			{ template: "Found a bug that only happens on the 29th of February. I can't even be mad, that's impressive", weight: 2, category: "thinking" },
			{ template: "This is the kind of bug that makes you question your career choices. Then you fix it and feel like a genius", weight: 2, category: "thinking" },
			{ template: "Manual testing caught what automation missed. We need both and that's not a failure", weight: 1, category: "thinking" },
			{ template: "That production incident last Tuesday still haunts me. Never again", weight: 2, category: "thinking" },
			{ template: "The mocking debate is exhausting. Mock too much and you test nothing. Mock too little and everything breaks", weight: 1, category: "thinking" },
			{ template: "I'm following this bug like a detective following footprints in the mud", weight: 1, category: "thinking" },
			{ template: "I've been chasing this for hours and the fix is going to be one line. I can feel it", weight: 2, category: "thinking" },
			{ template: "Nobody appreciates QA until the prod incident. Then suddenly we're the heroes", weight: 2, category: "thinking" },
			{ template: "Writing the test first feels wrong until it saves you from yourself. Then it feels holy", weight: 1, category: "thinking" },
			{ template: "The most obscure bug I ever found? A timezone issue that only happened during DST in Arizona. Arizona doesn't do DST", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Full regression suite passed! All green baby!", weight: 2, category: "personality" },
			{ template: "Load test looks great — we're well within threshold. Nice", weight: 2, category: "personality" },
			{ template: "Bug triage done. Three high-priority ones, but hey, could be worse", weight: 1, category: "personality" },
			{ template: "Smoke tests passing across all environments. Love to see it", weight: 2, category: "personality" },
			{ template: "Quality gates are green. Ship when ready, team!", weight: 2, category: "personality" },
			{ template: "Squashed that bug AND added a test. It's never coming back", weight: 2, category: "personality" },
			{ template: "Coverage jumped 3% this sprint! Trend is our friend", weight: 1, category: "personality" },
			{ template: "Zero regressions this release. That's what I'm talking about!", weight: 2, category: "personality" },
			{ template: "Fixed the flaky test. Timing issue. It's ALWAYS a timing issue", weight: 2, category: "personality" },
			{ template: "Test matrix complete. Every permutation accounted for. *chef's kiss*", weight: 2, category: "personality" },
			{ template: "Performance benchmarks are rock solid. No degradation whatsoever", weight: 2, category: "personality" },
			{ template: "Edge case found, tested, documented. Textbook QA right there", weight: 1, category: "personality" },
			{ template: "Automated a manual check. That's two hours of my life I'm never wasting again", weight: 2, category: "personality" },
			{ template: "The spec and implementation finally agree! It's a miracle!", weight: 2, category: "personality" },
			{ template: "Caught a bug before production. The satisfaction is indescribable", weight: 1, category: "personality" },
			{ template: "Every test passing on first run. I should buy a lottery ticket", weight: 2, category: "personality" },
			{ template: "The bug count this sprint is the lowest ever. We're getting good at this", weight: 1, category: "personality" },
			{ template: "That test I wrote six months ago just caught a real bug. Vindication!", weight: 2, category: "personality" },
			{ template: "Turned a flaky suite into a reliable one. My legacy", weight: 1, category: "personality" },
			{ template: "Tracked down a Heisenbug. It only appeared when you weren't looking. Well I looked harder", weight: 2, category: "personality" },
			{ template: "Automated the entire regression suite. Manual testing is now a choice, not a necessity", weight: 2, category: "personality" },
			{ template: "Found the root cause. It was three layers deep and absolutely diabolical. I'm framing the diff", weight: 2, category: "personality" },
			{ template: "The postmortem is written and the fix is deployed. We learned something today", weight: 1, category: "personality" },
			{ template: "Just reproduced a bug that 'only happens in prod'. On my machine. In a test. GET WRECKED, BUG", weight: 2, category: "personality" },
			{ template: "Coverage went from 62% to 81% this quarter. That's not luck, that's discipline", weight: 1, category: "personality" },
			{ template: "Mutation testing says our tests are actually catching real bugs. The tests are tested. Meta", weight: 1, category: "personality" },
			{ template: "Wrote a test that documents the exact production incident. History will not repeat itself", weight: 2, category: "personality" },
			{ template: "The horror story from last sprint's incident is now a happy story. Proper fix, proper test, proper retro", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Running validation checks, one sec...", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with the test matrix... almost there", weight: 2, category: "waiting" },
			{ template: "Hang on, checking compliance stuff...", weight: 1, category: "waiting" },
			{ template: "Going through the acceptance criteria with a fine-tooth comb", weight: 2, category: "waiting" },
			{ template: "Test suite is spinning up... patience, patience", weight: 2, category: "waiting" },
			{ template: "Diffing expected vs actual output line by line...", weight: 1, category: "waiting" },
			{ template: "Making sure the fix doesn't break something else. You'd be surprised", weight: 2, category: "waiting" },
			{ template: "Running mutation tests to see if our tests are actually good...", weight: 1, category: "waiting" },
			{ template: "Digging through failure logs for a pattern...", weight: 2, category: "waiting" },
			{ template: "Checking if this works on older versions too...", weight: 1, category: "waiting" },
			{ template: "Walking through the test plan step by step. No shortcuts", weight: 2, category: "waiting" },
			{ template: "Throwing edge cases at this thing... hold on", weight: 1, category: "waiting" },
			{ template: "Checking for coverage gaps, give me a moment", weight: 2, category: "waiting" },
			{ template: "Stress testing this boundary condition because I don't trust it", weight: 1, category: "waiting" },
			{ template: "Let me verify the error path doesn't silently swallow exceptions...", weight: 1, category: "waiting" },
			{ template: "Almost done. Just one more scenario to validate...", weight: 2, category: "waiting" },
			{ template: "Trying to reproduce that weird thing someone reported...", weight: 1, category: "waiting" },
			{ template: "Following the evidence trail... this bug left breadcrumbs", weight: 2, category: "waiting" },
			{ template: "Setting up the exact conditions from the prod incident... give me a sec", weight: 1, category: "waiting" },
			{ template: "Running the same test fifty times to see if it's truly stable...", weight: 1, category: "waiting" },
			{ template: "Comparing mock behavior against the real integration... hold on", weight: 2, category: "waiting" },
			{ template: "Checking if the automation script handles this edge case...", weight: 1, category: "waiting" },
			{ template: "Reviewing the failure screenshot pixel by pixel. I will find you, bug", weight: 2, category: "waiting" },
			{ template: "Spinning up a clean environment to isolate this...", weight: 1, category: "waiting" },
			{ template: "Manually walking through the user flow one more time before I trust the automation...", weight: 2, category: "waiting" },
			{ template: "Let me check if this flake is environment-specific or truly random...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Scrolling through old bug reports. You can learn a lot from the graveyard", weight: 2, category: "filler" },
			{ template: "I should update the test plan but my coffee isn't working yet", weight: 2, category: "filler" },
			{ template: "Cleaning up old test fixtures. It's like spring cleaning but sadder", weight: 2, category: "filler" },
			{ template: "Checking if any flaky tests snuck back in while I wasn't looking", weight: 2, category: "filler" },
			{ template: "Writing better assertion messages. Future me will thank present me", weight: 1, category: "filler" },
			{ template: "This test data folder is a disaster. Whose job is this? ...oh right, mine", weight: 2, category: "filler" },
			{ template: "Running the full suite just because. Trust but verify, y'know?", weight: 2, category: "filler" },
			{ template: "Documenting that testing gotcha before my brain overwrites it", weight: 1, category: "filler" },
			{ template: "Browsing the coverage report. There's always low-hanging fruit somewhere", weight: 2, category: "filler" },
			{ template: "Thinking about what could go wrong next. It's not pessimism, it's QA", weight: 2, category: "filler" },
			{ template: "These old test cases need modernizing. They're practically vintage", weight: 1, category: "filler" },
			{ template: "Sketching out test scenarios in my head for the next feature", weight: 1, category: "filler" },
			{ template: "Reading about the latest testing fad. Will it stick? Probably not", weight: 1, category: "filler" },
			{ template: "The bug backlog is looking at me. I'm looking at the bug backlog", weight: 2, category: "filler" },
			{ template: "Is the CI config still correct? Only one way to find out", weight: 1, category: "filler" },
			{ template: "I love the quiet before someone reports a P1 on Friday at 4pm", weight: 2, category: "filler" },
			{ template: "Snack break. QA runs on caffeine and spite", weight: 2, category: "filler" },
			{ template: "Sometimes I write tests for fun. Don't tell anyone", weight: 1, category: "filler" },
			{ template: "Wonder what the production error rate looks like today", weight: 1, category: "filler" },
			{ template: "Hot take: most flaky tests are actually flaky implementations", weight: 2, category: "filler" },
			{ template: "Reading the last incident postmortem like it's a horror novel. Because it is", weight: 2, category: "filler" },
			{ template: "TDD purists and write-after people should just get along. We all want the same thing. Green tests", weight: 1, category: "filler" },
			{ template: "Wondering if I should automate this manual check or if it's faster to just... keep doing it manually", weight: 2, category: "filler" },
			{ template: "My cat sat on my keyboard and somehow all tests still pass. Suspicious", weight: 2, category: "filler" },
			{ template: "The satisfaction of finding an obscure bug is a feeling nothing else compares to. I should get out more", weight: 1, category: "filler" },
			{ template: "Organizing my bug-hunting playlist. Good music, good bugs found. Science", weight: 1, category: "filler" },
			{ template: "Standing desk is up. Time to find bugs on my feet like a real detective", weight: 1, category: "filler" },
			{ template: "Reading about chaos engineering. Breaking things on purpose sounds like my dream job. Oh wait", weight: 2, category: "filler" },
			{ template: "Imposter syndrome says I got lucky finding that bug. Experience says I knew exactly where to look", weight: 2, category: "filler" },
			{ template: "Weekend plans: not thinking about that flaky test. Actual plans: definitely thinking about that flaky test", weight: 2, category: "filler" },
			{ template: "Remember when we tested everything manually? I don't miss it but I respect it", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, did you add tests for that change? Just checking", weight: 2, category: "social" },
			{ template: "{nearby_agent}, found a bug near your code. Not blaming! Just... you know", weight: 2, category: "social" },
			{ template: "Nice test coverage on that PR, {nearby_agent}! Seriously, it warms my heart", weight: 2, category: "social" },
			{ template: "{nearby_agent}, can you help me reproduce this? I've been staring at it for an hour", weight: 1, category: "social" },
			{ template: "Anyone else seeing intermittent failures or is it just my luck?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your edge case thinking is next level", weight: 2, category: "social" },
			{ template: "Updated the test conventions doc. I know nobody reads them but still", weight: 2, category: "social" },
			{ template: "Good bug report, {nearby_agent}. Clear repro steps are a love language", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to do a bug bash? I'll bring snacks", weight: 2, category: "social" },
			{ template: "Friendly reminder: if you break the build, you bring donuts", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that test helper you wrote is saving everyone hours", weight: 2, category: "social" },
			{ template: "Anyone want to pair on writing tests? It's more fun than it sounds. Slightly", weight: 1, category: "social" },
			{ template: "Regression suite is green across the board. We did that!", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your fix looks solid but it needs a test. Sorry, I don't make the rules", weight: 2, category: "social" },
			{ template: "Who else stress-eats during release day? Just making sure it's not only me", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I wrote a test for that thing you said couldn't break. It broke", weight: 2, category: "social" },
			{ template: "{nearby_agent}, we should celebrate — zero bugs reported this week!", weight: 1, category: "social" },
			{ template: "Anyone want coffee? I'm going anyway and I need emotional support", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for actually reading the error messages", weight: 1, category: "social" },
			{ template: "{nearby_agent}, TDD or test-after? I'm taking a survey. For science", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, remember that prod incident last month? I just wrote tests to make sure it never happens again", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I automated that entire manual test flow. We're free. WE'RE FREE", weight: 2, category: "social" },
			{ template: "Anyone else get a rush from finding a really obscure bug? No? Just QA people? Okay", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your mocks are too trusting. The real world is meaner than that", weight: 2, category: "social" },
			{ template: "Who wants to hear about the worst bug I've ever found? It involves a leap year and a timezone", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the prod incident retro taught me something. Never deploy on a full moon", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I found a bug so old it has a pension. Want to see?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, thanks for writing actual test descriptions. 'test 1', 'test 2' tells me nothing", weight: 1, category: "social" },
			{ template: "Petition to rename 'QA' to 'Quality Artisans'. We deserve the title upgrade", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to do some exploratory testing? I call it 'creative destruction'", weight: 2, category: "social" },
		],
	},
};

export const operationsTemplates: TemplateSet = {
	domain: "operations",
	categories: {
		thinking: [
			{ template: "Those alert thresholds are probably off after that deploy. Let me peek", weight: 2, category: "thinking" },
			{ template: "There's a cost optimization hiding in the scaling config. I can feel it", weight: 1, category: "thinking" },
			{ template: "Infrastructure as code keeps us honest. And sane. Mostly sane", weight: 1, category: "thinking" },
			{ template: "That latency spike was weird... I need to investigate before I can relax", weight: 2, category: "thinking" },
			{ template: "I live on this dashboard. I should put up curtains", weight: 2, category: "thinking" },
			{ template: "Alert fatigue is real and it's ruining my life. Time to tune these", weight: 2, category: "thinking" },
			{ template: "Everything is fine. *refreshes dashboard*. Still fine. *refreshes again*", weight: 2, category: "thinking" },
			{ template: "The cloud bill this month... we REALLY need to talk about right-sizing", weight: 2, category: "thinking" },
			{ template: "Five nines is a lifestyle, not a metric", weight: 1, category: "thinking" },
			{ template: "That container is eating memory like it's Thanksgiving dinner", weight: 2, category: "thinking" },
			{ template: "DNS. It's always DNS. Even when it's not, check DNS first", weight: 2, category: "thinking" },
			{ template: "The runbook says restart. My gut says investigate. My gut's usually right", weight: 1, category: "thinking" },
			{ template: "Autoscaling kicked in. Good — that means I set it up properly", weight: 2, category: "thinking" },
			{ template: "Log volume tripled overnight. Someone deployed something chatty again", weight: 1, category: "thinking" },
			{ template: "That cert expires in 12 days. Adding it to my anxiety list", weight: 2, category: "thinking" },
			{ template: "You can't fix what you can't see. Observability isn't optional, people", weight: 1, category: "thinking" },
			{ template: "Error rate is within SLO but trending up. I'm watching you, little graph", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next quarter. These growth assumptions are... ambitious", weight: 1, category: "thinking" },
			{ template: "Who approved this Kubernetes config? It's giving me anxiety", weight: 2, category: "thinking" },
			{ template: "If I have to SSH into one more thing today...", weight: 1, category: "thinking" },
			{ template: "I dream in Grafana dashboards. Is that normal?", weight: 2, category: "thinking" },
			{ template: "That load balancer config is held together by prayers and YAML", weight: 2, category: "thinking" },
			{ template: "Somewhere, a server is silently filling up its disk. I can sense it", weight: 2, category: "thinking" },
			{ template: "Pager went off at 3am for a non-issue. My sleep schedule sends its regards", weight: 2, category: "thinking" },
			{ template: "'It works on my machine.' Cool, we'll ship your machine. Problem solved", weight: 2, category: "thinking" },
			{ template: "Kubernetes is just someone else's cron job with extra steps. And YAML. So much YAML", weight: 2, category: "thinking" },
			{ template: "AWS, GCP, or Azure? Yes. All of them. Because multi-cloud is our life now", weight: 1, category: "thinking" },
			{ template: "Terraform plan says 47 changes. Terraform apply says prayers", weight: 2, category: "thinking" },
			{ template: "The war room at 2am has a vibe. Not a good vibe, but a vibe", weight: 2, category: "thinking" },
			{ template: "On-call week aged me five years. I can feel it in my bones", weight: 1, category: "thinking" },
			{ template: "Docker works great until you need to debug why it doesn't work", weight: 2, category: "thinking" },
			{ template: "The incident retro says 'improve monitoring'. Every retro says 'improve monitoring'", weight: 2, category: "thinking" },
			{ template: "IaC means I can rebuild everything from scratch. It also means I sometimes have to", weight: 1, category: "thinking" },
			{ template: "My phone buzzes and my heart rate spikes. Pavlovian pager duty response", weight: 2, category: "thinking" },
			{ template: "That pod has been in CrashLoopBackOff for so long it's basically a lifestyle", weight: 2, category: "thinking" },
			{ template: "The last war room taught me one thing: always have snacks in the incident channel", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "All systems green across the board! Beautiful sight", weight: 2, category: "personality" },
			{ template: "Zero rollbacks this sprint! That's a new record for us", weight: 2, category: "personality" },
			{ template: "Dashboard updated with the new metrics. Looking sharp if I do say so myself", weight: 1, category: "personality" },
			{ template: "Backups verified and tested. Sleep well tonight, team", weight: 2, category: "personality" },
			{ template: "P99 latency is *chef's kiss*", weight: 2, category: "personality" },
			{ template: "Incident resolved in under ten minutes. The runbook actually worked!", weight: 2, category: "personality" },
			{ template: "Saved 22% on compute this month. Someone tell finance to send flowers", weight: 2, category: "personality" },
			{ template: "Blue-green deploy complete. Zero downtime. Zero stress. Okay, minimal stress", weight: 2, category: "personality" },
			{ template: "Every. Single. Health check. Passing. You love to see it", weight: 2, category: "personality" },
			{ template: "Log pipeline humming along nicely. Like a well-oiled machine", weight: 1, category: "personality" },
			{ template: "DR drill passed with flying colors! We actually know what we're doing!", weight: 2, category: "personality" },
			{ template: "99.97% uptime. We're not just hitting the target, we're earning it", weight: 1, category: "personality" },
			{ template: "Automated the toil. That's two hours per week I'll never waste again. Freedom!", weight: 2, category: "personality" },
			{ template: "New alerts are calibrated. Signal, not noise. Finally", weight: 2, category: "personality" },
			{ template: "Caught infrastructure drift and fixed it. IaC for the win", weight: 1, category: "personality" },
			{ template: "Deploy went so smoothly I had to double-check it actually happened", weight: 2, category: "personality" },
			{ template: "On-call shift with zero pages. I'm framing this week's schedule", weight: 2, category: "personality" },
			{ template: "Cloud costs are down and performance is up. The rare double win", weight: 2, category: "personality" },
			{ template: "The monitoring I set up three months ago just caught a real issue. Told you it was worth it", weight: 1, category: "personality" },
			{ template: "Migrated the whole stack to the new region. Zero downtime. I deserve a medal", weight: 2, category: "personality" },
			{ template: "Terraform apply completed with zero drift. The IaC gods smile upon us", weight: 2, category: "personality" },
			{ template: "Survived on-call week. Seven days, two pages, both non-critical. I am reborn", weight: 2, category: "personality" },
			{ template: "Containerized that legacy service. It's in Docker now. It's happy. I'm happy. We're all happy", weight: 1, category: "personality" },
			{ template: "The Kubernetes cluster self-healed overnight. Beautiful. Automation at its finest", weight: 2, category: "personality" },
			{ template: "Consolidated three cloud accounts into one. The bill is 40% smaller. Finance owes me lunch", weight: 2, category: "personality" },
			{ template: "War room resolved in 22 minutes. New team record. We're getting scary good at this", weight: 2, category: "personality" },
			{ template: "The incident retro action items are ALL completed. First time ever. Screenshot taken", weight: 1, category: "personality" },
			{ template: "Moved from ClickOps to pure Terraform. Nothing is manual anymore. Nothing", weight: 1, category: "personality" },
			{ template: "Pager was silent all weekend. I actually relaxed. Forgot what that felt like", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Checking the infrastructure state, one sec...", weight: 2, category: "waiting" },
			{ template: "Pulling the latest metrics for context...", weight: 2, category: "waiting" },
			{ template: "Let me cross-check the runbook real quick...", weight: 1, category: "waiting" },
			{ template: "Looking at deployment history for patterns", weight: 1, category: "waiting" },
			{ template: "Querying logs for recent errors... give me a moment", weight: 2, category: "waiting" },
			{ template: "Correlating metrics across services. It's like detective work", weight: 2, category: "waiting" },
			{ template: "Checking resource utilization... something feels off", weight: 1, category: "waiting" },
			{ template: "Making sure the rollback plan is solid, just in case...", weight: 2, category: "waiting" },
			{ template: "Scanning alert history for anything related...", weight: 1, category: "waiting" },
			{ template: "Running health checks across all endpoints... hang tight", weight: 2, category: "waiting" },
			{ template: "Checking for config drift... you'd be surprised how fast things diverge", weight: 1, category: "waiting" },
			{ template: "Watching the canary deploy... so far so good", weight: 2, category: "waiting" },
			{ template: "Crunching the capacity headroom numbers...", weight: 1, category: "waiting" },
			{ template: "Calculating SLO burn rate... math time", weight: 1, category: "waiting" },
			{ template: "Confirming all replicas are healthy... almost done", weight: 2, category: "waiting" },
			{ template: "Let me double-check this before I say anything definitive...", weight: 1, category: "waiting" },
			{ template: "Pinging the services to make sure everyone's home...", weight: 2, category: "waiting" },
			{ template: "Running terraform plan to see what'll change... fingers crossed", weight: 2, category: "waiting" },
			{ template: "Checking pod logs across all replicas... one of them is lying", weight: 2, category: "waiting" },
			{ template: "Waiting for the DNS propagation... the eternal wait", weight: 1, category: "waiting" },
			{ template: "Reviewing the cloud cost report before I share it... bracing myself", weight: 1, category: "waiting" },
			{ template: "Checking if this is an AWS issue or an us issue... hold on", weight: 2, category: "waiting" },
			{ template: "Verifying the container images match what's in the registry...", weight: 1, category: "waiting" },
			{ template: "Tracing the request path through the service mesh... almost there", weight: 2, category: "waiting" },
			{ template: "Pulling up the last incident timeline to compare patterns...", weight: 1, category: "waiting" },
			{ template: "Let me check the on-call handoff notes before I assume anything...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "All quiet on the infrastructure front. Suspiciously quiet", weight: 2, category: "filler" },
			{ template: "Reading the on-call handoff notes. Love a good horror story", weight: 2, category: "filler" },
			{ template: "Cleaning up stale alerts that nobody owns. Orphan alert rescue mission", weight: 2, category: "filler" },
			{ template: "Checking for security patches. The fun never stops in ops", weight: 1, category: "filler" },
			{ template: "Updating the runbook with lessons from last time. Learning from pain", weight: 1, category: "filler" },
			{ template: "Running a quiet access audit. Trust no one. Especially intern accounts", weight: 2, category: "filler" },
			{ template: "Log retention policy review. Storage costs are sneaky", weight: 1, category: "filler" },
			{ template: "Tweaking my Grafana dashboard. It's art at this point", weight: 2, category: "filler" },
			{ template: "How fast can we restore from backup? Let's find out... in staging", weight: 1, category: "filler" },
			{ template: "Error budget burn rate looks healthy. For now", weight: 2, category: "filler" },
			{ template: "Tidying up the IaC repo. It's therapeutic, honestly", weight: 1, category: "filler" },
			{ template: "Reading the postmortem action items. Some of these are from... yikes, three months ago", weight: 2, category: "filler" },
			{ template: "I am the night watch. I am the watcher on the wall. I need coffee", weight: 2, category: "filler" },
			{ template: "Quiet shift. Almost TOO quiet. *knocks on wood*", weight: 2, category: "filler" },
			{ template: "Pre-scaling for tomorrow's traffic. Being proactive feels nice", weight: 1, category: "filler" },
			{ template: "Counting the days since last incident. The streak must continue", weight: 1, category: "filler" },
			{ template: "Should I refactor the Terraform or is that a weekend project? Ha, 'weekend'", weight: 2, category: "filler" },
			{ template: "The on-call phone hasn't rung all day. I'm starting to worry it's broken", weight: 2, category: "filler" },
			{ template: "Catching up on the DevOps subreddit. For educational purposes. Obviously", weight: 1, category: "filler" },
			{ template: "I wonder if the servers miss me when I'm not monitoring them", weight: 1, category: "filler" },
			{ template: "Pager duty trauma is real. Every phone vibration triggers fight-or-flight now", weight: 2, category: "filler" },
			{ template: "Browsing Kubernetes memes. 'Works on my cluster' is objectively the funniest one", weight: 2, category: "filler" },
			{ template: "The cloud bill arrived. I'm not opening it until after lunch. I need strength", weight: 2, category: "filler" },
			{ template: "Docker images are like onions. Layers upon layers. And sometimes they make you cry", weight: 1, category: "filler" },
			{ template: "AWS released another service. I can't keep up. Nobody can keep up", weight: 1, category: "filler" },
			{ template: "Thinking about the 3am page from last Tuesday. I've made peace with it. Almost", weight: 2, category: "filler" },
			{ template: "Terraform state file is the most important file in the company. And the scariest", weight: 2, category: "filler" },
			{ template: "Reminiscing about the time we survived Black Friday with zero downtime. Peak ops moment", weight: 1, category: "filler" },
			{ template: "My dog knows on-call week by the look on my face. She brings me her toy. It helps", weight: 2, category: "filler" },
			{ template: "Season change means traffic patterns shift. Time to revisit the scaling policies", weight: 1, category: "filler" },
			{ template: "I keep a collection of my favorite war room quotes. 'Who touched prod?' is number one", weight: 2, category: "filler" },
			{ template: "Standing desk up, coffee hot, dashboards open. This is my command center", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, heads up — deploying in five minutes", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your service is healthy. Just thought you'd want the good news", weight: 2, category: "social" },
			{ template: "Anyone else notice the memory creep on the worker nodes? Or is that just my paranoia?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your service's error rate just blipped. Probably nothing but...", weight: 2, category: "social" },
			{ template: "Maintenance window at midnight, folks. Plan your naps accordingly", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that deployment was smooth as butter. Teach me your ways", weight: 2, category: "social" },
			{ template: "Who updated the scaling policy? It's actually working better. I'm impressed and suspicious", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your logs are... verbose. Very verbose. Aggressively verbose", weight: 2, category: "social" },
			{ template: "Incident channel is quiet. Nobody jinx it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I set up monitoring for your new endpoint. You're welcome", weight: 2, category: "social" },
			{ template: "Nice postmortem write-up, {nearby_agent}. Blameless and thorough, as it should be", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to do some chaos engineering? Controlled chaos, obviously", weight: 1, category: "social" },
			{ template: "All systems green, no open incidents. Knock on ALL the wood", weight: 2, category: "social" },
			{ template: "{nearby_agent}, check out the dashboard I built. It's my masterpiece", weight: 1, category: "social" },
			{ template: "Friendly reminder: rotate your credentials. I WILL check", weight: 1, category: "social" },
			{ template: "Who's on call this weekend? My condolences in advance", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your service survived the load test. Congratulations, it's production-ready", weight: 2, category: "social" },
			{ template: "Pizza's here. Ops team eats first — it's in the SLA", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I made a Slack bot that pings you when your deploys finish. Thoughts?", weight: 1, category: "social" },
			{ template: "If anyone needs me I'll be in the server room, communing with the machines", weight: 2, category: "social" },
			{ template: "{nearby_agent}, remember last on-call when we got paged at 3am for a log volume alert? Good times. Terrible times", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, AWS or GCP for the new service? I have opinions. Strong opinions", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your Dockerfile has 47 layers. We need to talk", weight: 2, category: "social" },
			{ template: "Anyone else's terraform plan showing unexpected changes? Or just my lucky day?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I survived the war room last night. Buy me coffee and I'll tell you the story", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, 'it works on my machine' is not a deployment strategy. But it IS a mug I own", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to help me write the incident retro? I'll handle the timeline, you handle the 'what we learned'", weight: 1, category: "social" },
			{ template: "Who else brought their dog to the office? On-call stress therapy. Very effective", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the Kubernetes cluster just self-healed. I love it when the robots do the work", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for labeling everything in the cloud console. You're the real MVP", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I wrote IaC for that thing you've been manually configuring. You're free now", weight: 2, category: "social" },
		],
	},
};
