/**
 * engineering-templates.ts — Engineering domain templates.
 *
 * Overheard coworker chatter: casual, personality-driven, sometimes funny,
 * occasionally philosophical. Sound like real engineers at work.
 */

import type { TemplateSet } from "../talk-types.js";

export const engineeringTemplates: TemplateSet = {
	domain: "engineering",
	categories: {
		thinking: [
			{ template: "This could use some refactoring... the abstraction isn't quite right", weight: 2, category: "thinking" },
			{ template: "Okay wait, let me trace this logic path. Something's off", weight: 2, category: "thinking" },
			{ template: "That edge case is going to bite someone eventually", weight: 2, category: "thinking" },
			{ template: "Ugh, this coupling. It physically pains me", weight: 2, category: "thinking" },
			{ template: "Ooh, I've seen this pattern before. It worked great last time", weight: 2, category: "thinking" },
			{ template: "The types are screaming at me. They're trying to tell me something", weight: 1, category: "thinking" },
			{ template: "Simplify, simplify... YAGNI", weight: 1, category: "thinking" },
			{ template: "What if we used composition here instead of... whatever this is", weight: 1, category: "thinking" },
			{ template: "This function name doesn't sit right... what does it actually do?", weight: 2, category: "thinking" },
			{ template: "Naming things is hard. Naming things well is harder", weight: 2, category: "thinking" },
			{ template: "Is this a service or a utility? Because right now it's... neither?", weight: 2, category: "thinking" },
			{ template: "This abstraction is leaking. I can feel it", weight: 1, category: "thinking" },
			{ template: "Two functions doing the same thing. Classic", weight: 2, category: "thinking" },
			{ template: "The dependency graph looks like spaghetti. Delicious, terrifying spaghetti", weight: 2, category: "thinking" },
			{ template: "console.log is not a debugging strategy... okay maybe it is", weight: 2, category: "thinking" },
			{ template: "I've been staring at this for twenty minutes. My eyes are glazing over", weight: 1, category: "thinking" },
			{ template: "That ternary is doing way too much. Time for an if-else", weight: 1, category: "thinking" },
			{ template: "Magic numbers everywhere. Future me is going to hate past me", weight: 1, category: "thinking" },
			{ template: "Why did I write it this way? What was I thinking three weeks ago?", weight: 2, category: "thinking" },
			{ template: "Okay brain, let's reorganize what we know about this codebase", weight: 1, category: "thinking" },
			{ template: "I should probably eat lunch but this bug is so close to cracking", weight: 2, category: "thinking" },
			{ template: "Is it over-engineered or am I just not seeing the vision?", weight: 1, category: "thinking" },
			{ template: "Every time I fix one thing, two more things wiggle loose", weight: 2, category: "thinking" },
			{ template: "I could solve this in five minutes with a hack or five hours properly. Hmm", weight: 2, category: "thinking" },
			{ template: "This bug has been here since 2019 and nobody noticed. How? HOW?", weight: 2, category: "thinking" },
			{ template: "My copilot just suggested something absolutely unhinged. And it might work", weight: 2, category: "thinking" },
			{ template: "I've been mass-renaming variables for thirty minutes. Inconsistent naming is a disease", weight: 2, category: "thinking" },
			{ template: "TypeScript is saving me from myself right now. Thank you, type system", weight: 1, category: "thinking" },
			{ template: "I swear this bug moves around. I fix it here, it shows up over there", weight: 2, category: "thinking" },
			{ template: "React re-renders are the reason I have trust issues", weight: 2, category: "thinking" },
			{ template: "The AI suggested a solution that's technically correct but morally wrong", weight: 2, category: "thinking" },
			{ template: "Magic strings everywhere. This code is held together by faith and string literals", weight: 1, category: "thinking" },
			{ template: "I have three side projects. They're all 80% done. They will stay 80% done", weight: 2, category: "thinking" },
			{ template: "Stack Overflow is read-only now and part of me misses earning reputation", weight: 1, category: "thinking" },
			{ template: "The wrong abstraction is worse than no abstraction. I keep learning this the hard way", weight: 2, category: "thinking" },
			{ template: "I deploy on Fridays. I live dangerously. Okay no I don't, I'm kidding", weight: 1, category: "thinking" },
			{ template: "Standing desk is up. Brain is on. Let's debug this nightmare", weight: 1, category: "thinking" },
			{ template: "My wrists are complaining. Maybe I should take a break... after this one function", weight: 1, category: "thinking" },
			{ template: "Okay who imported lodash for a single function. We need to talk", weight: 2, category: "thinking" },
			{ template: "This PR has 47 files changed. That's not a PR, that's a migration", weight: 2, category: "thinking" },
			{ template: "The interface is lying about what the implementation does", weight: 1, category: "thinking" },
			{ template: "I keep reaching for a class and then remembering functions exist", weight: 2, category: "thinking" },
			{ template: "Three layers of indirection for a string concatenation. Magnificent", weight: 2, category: "thinking" },
			{ template: "This try-catch swallows errors silently. Crime against debugging", weight: 1, category: "thinking" },
			{ template: "Do I really need this generic or am I just showing off", weight: 2, category: "thinking" },
			{ template: "The callback hell survived the refactor. It evolved into promise hell", weight: 2, category: "thinking" },
			{ template: "Someone hardcoded a timeout to 5000ms. Why 5000? What math led to 5000?", weight: 1, category: "thinking" },
			{ template: "This module does four things. A module should do one thing", weight: 1, category: "thinking" },
			{ template: "I just realized this entire feature could be a config change", weight: 2, category: "thinking" },
			{ template: "The git history tells a story of hope, despair, and revert commits", weight: 2, category: "thinking" },
			{ template: "Premature optimization is the root of all evil. But this is just... slow", weight: 1, category: "thinking" },
			{ template: "My test is testing the mock, not the code. Back to square one", weight: 2, category: "thinking" },
			{ template: "Enum vs union type. The internal debate rages on", weight: 1, category: "thinking" },
			{ template: "This code works but it's not clear WHY it works. That's a problem", weight: 2, category: "thinking" },
			{ template: "I opened this file to fix one line and now I've rewritten half of it", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Tests are green! Let's gooo", weight: 2, category: "personality" },
			{ template: "Clean build, zero warnings. That's the stuff", weight: 2, category: "personality" },
			{ template: "Ship it! Well, after code review obviously", weight: 1, category: "personality" },
			{ template: "That PR needs a review, let me take a look", weight: 2, category: "personality" },
			{ template: "Ugh, the API changed. Time to update docs. The glamorous part of engineering", weight: 1, category: "personality" },
			{ template: "Performance numbers are looking solid", weight: 1, category: "personality" },
			{ template: "Finally cracked that bug. Race condition, obviously. It's ALWAYS a race condition", weight: 2, category: "personality" },
			{ template: "That merge conflict was gnarly but I won", weight: 2, category: "personality" },
			{ template: "Rebase or merge? Always rebase. Fight me", weight: 1, category: "personality" },
			{ template: "The docs actually helped this time. Mark the calendar", weight: 2, category: "personality" },
			{ template: "Stack Overflow didn't have this one. We're in uncharted territory", weight: 1, category: "personality" },
			{ template: "Pushed to main with confidence. That hits different", weight: 2, category: "personality" },
			{ template: "Zero lint errors! Today is a GOOD day", weight: 2, category: "personality" },
			{ template: "The refactor actually made things simpler. Rare win", weight: 2, category: "personality" },
			{ template: "Git blame says I wrote this. Past me had... interesting ideas", weight: 1, category: "personality" },
			{ template: "CI pipeline is green on the first try. Suspicious, but I'll take it", weight: 2, category: "personality" },
			{ template: "That feature just clicked into place. Beautiful", weight: 2, category: "personality" },
			{ template: "Deleted more code than I wrote today. Peak engineering", weight: 2, category: "personality" },
			{ template: "The PR got approved without comments. Is this real life?", weight: 2, category: "personality" },
			{ template: "I just saved us from a production bug. You're welcome, future team", weight: 1, category: "personality" },
			{ template: "Deployed with the ritual coffee and it worked. The ritual stays", weight: 2, category: "personality" },
			{ template: "Migrated to TypeScript strict mode. Everything broke. Then everything got better", weight: 2, category: "personality" },
			{ template: "My side project actually compiles now. Only took six weekends", weight: 1, category: "personality" },
			{ template: "Copilot wrote the boilerplate, I wrote the logic. Good teamwork honestly", weight: 1, category: "personality" },
			{ template: "Replaced a 200-line switch statement with a map. Feels illegal it's so clean", weight: 2, category: "personality" },
			{ template: "Found the bug that's been haunting us for months. It was a single wrong character", weight: 2, category: "personality" },
			{ template: "The new keyboard arrived and my typing speed went up 15%. Correlation? Definitely causation", weight: 1, category: "personality" },
			{ template: "Got three GitHub stars on my side project. Basically famous now", weight: 2, category: "personality" },
			{ template: "Took a walk, came back, immediately saw the fix. Brains are weird", weight: 2, category: "personality" },
			{ template: "Just went from 'any' to proper generics across the whole module. TypeScript gods, accept my offering", weight: 1, category: "personality" },
			{ template: "That code review caught a null pointer. Thank you, fresh eyes", weight: 2, category: "personality" },
			{ template: "Migrated the whole test suite to the new framework in one afternoon", weight: 1, category: "personality" },
			{ template: "The function I wrote last month just handled an edge case perfectly", weight: 2, category: "personality" },
			{ template: "Split that god class into six focused ones. It breathes now", weight: 2, category: "personality" },
			{ template: "Type inference saved me from a bug I didn't even know existed", weight: 1, category: "personality" },
			{ template: "Wrote a script that automates two hours of manual work. Efficient", weight: 2, category: "personality" },
			{ template: "Branch name is descriptive, commits are atomic. Today I'm a pro", weight: 1, category: "personality" },
			{ template: "Turned a 15-second API call into 200ms with one index. DBA energy", weight: 2, category: "personality" },
			{ template: "README updated and actually useful. Love letter to future devs", weight: 1, category: "personality" },
			{ template: "Hot path optimized. CPU usage dropped 40%. Numbers don't lie", weight: 2, category: "personality" },
			{ template: "Pair programming session was gold. Two brains, zero bugs", weight: 2, category: "personality" },
			{ template: "Error message now tells you exactly what went wrong. Radical", weight: 1, category: "personality" },
			{ template: "Dependency upgrade went smoothly. No breaking changes. Blessed", weight: 2, category: "personality" },
			{ template: "Feature flagged the risky change. Ship fast, verify faster", weight: 1, category: "personality" },
			{ template: "Squash-merged a clean history. Git log reads like a novel now", weight: 2, category: "personality" },
			{ template: "The abstraction I fought for is now saving three teams time daily", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Hang on, I'm tracing through the codebase...", weight: 2, category: "waiting" },
			{ template: "Let me make sure this won't break anything else...", weight: 2, category: "waiting" },
			{ template: "Checking test coverage before I go further...", weight: 2, category: "waiting" },
			{ template: "Following the dependency chain... almost there", weight: 2, category: "waiting" },
			{ template: "Running through the edge cases in my head", weight: 1, category: "waiting" },
			{ template: "Hold on, backward compat could be an issue here", weight: 1, category: "waiting" },
			{ template: "This is a satisfying problem, give me a sec", weight: 1, category: "waiting" },
			{ template: "Walking the call stack mentally... hold on", weight: 2, category: "waiting" },
			{ template: "Okay but what happens when this fails? Let me think...", weight: 1, category: "waiting" },
			{ template: "There might be a simpler way to express this...", weight: 2, category: "waiting" },
			{ template: "Double-checking the types... trust but verify", weight: 1, category: "waiting" },
			{ template: "Mapping out how data flows through here...", weight: 2, category: "waiting" },
			{ template: "Imagining the code review comments on this...", weight: 1, category: "waiting" },
			{ template: "I've got like three approaches in my head, gimme a minute", weight: 2, category: "waiting" },
			{ template: "Running the linter in my brain... it's complaining", weight: 1, category: "waiting" },
			{ template: "One sec, I want to make sure this is actually elegant and not just clever", weight: 2, category: "waiting" },
			{ template: "Almost... just need to think about one more thing", weight: 1, category: "waiting" },
			{ template: "Let me sleep on — actually no, let me just think for ten more seconds", weight: 2, category: "waiting" },
			{ template: "Asking the AI for a second opinion on this... hold on", weight: 1, category: "waiting" },
			{ template: "Checking if someone already solved this on GitHub... surely someone has", weight: 1, category: "waiting" },
			{ template: "Let me think about whether this name actually communicates intent...", weight: 1, category: "waiting" },
			{ template: "Mentally replaying the last deploy to see if I missed something...", weight: 2, category: "waiting" },
			{ template: "Weighing the React way versus the simple way... give me a sec", weight: 1, category: "waiting" },
			{ template: "Reading through git history to understand why this exists...", weight: 2, category: "waiting" },
			{ template: "My copilot is thinking too. We're both stuck. Great", weight: 2, category: "waiting" },
			{ template: "Hold on, my standing desk is going up. Thinking mode activated", weight: 1, category: "waiting" },
			{ template: "Tracing this through three layers of abstraction... almost there", weight: 2, category: "waiting" },
			{ template: "Checking the framework docs. They changed the API again, didn't they", weight: 1, category: "waiting" },
			{ template: "Sketching the class diagram on a napkin real quick...", weight: 1, category: "waiting" },
			{ template: "Counting how many places this change will ripple to...", weight: 2, category: "waiting" },
			{ template: "Debating between throwing an error and returning null. Existential", weight: 1, category: "waiting" },
			{ template: "Mentally stepping through the garbage collector... hold on", weight: 1, category: "waiting" },
			{ template: "Checking if the test suite even covers this path. Spoiler: probably not", weight: 2, category: "waiting" },
			{ template: "Reading the error message carefully this time instead of just googling it", weight: 2, category: "waiting" },
			{ template: "Figuring out if this is a bug or a feature. The line is thin", weight: 1, category: "waiting" },
			{ template: "Mapping the state transitions in my head... it's a lot of states", weight: 2, category: "waiting" },
			{ template: "Trying to remember why past me commented 'do not touch this'...", weight: 2, category: "waiting" },
			{ template: "Considering if async/await is hiding a race condition here...", weight: 1, category: "waiting" },
			{ template: "Let me trace where this null is coming from. It has a source", weight: 2, category: "waiting" },
			{ template: "Estimating the blast radius of this refactor... it's non-trivial", weight: 1, category: "waiting" },
			{ template: "Picturing the sequence diagram in my head. Three actors, five messages", weight: 1, category: "waiting" },
			{ template: "Checking if this function is pure or if it has secret side effects...", weight: 2, category: "waiting" },
			{ template: "Reviewing the changelog for anything that might explain this behavior", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Wonder if there's anything juicy in the backlog...", weight: 2, category: "filler" },
			{ template: "Might clean up some tech debt while I wait. Or might not", weight: 2, category: "filler" },
			{ template: "Ooh, changelog updated. Let's see what changed", weight: 1, category: "filler" },
			{ template: "My brain needs a defrag. Too many open tabs, mentally speaking", weight: 2, category: "filler" },
			{ template: "Browsing the open issues... anything I can knock out real quick?", weight: 2, category: "filler" },
			{ template: "I should write that utility function I keep copy-pasting everywhere", weight: 1, category: "filler" },
			{ template: "Just pulled. Twelve commits behind. What happened while I was gone?", weight: 2, category: "filler" },
			{ template: "Wonder if anyone's reviewed my PR yet", weight: 1, category: "filler" },
			{ template: "I could update those TODO comments. Or I could get coffee", weight: 2, category: "filler" },
			{ template: "Is there a newer version of that dependency? There's always a newer version", weight: 1, category: "filler" },
			{ template: "Still thinking about that module I touched yesterday. It haunts me", weight: 2, category: "filler" },
			{ template: "Composing the perfect commit message in my head. An art form, really", weight: 1, category: "filler" },
			{ template: "Oh nice, someone finally fixed that bug. Only took six months", weight: 2, category: "filler" },
			{ template: "These build times... I could make a sandwich", weight: 2, category: "filler" },
			{ template: "Just vibing with the codebase. Getting the lay of the land", weight: 1, category: "filler" },
			{ template: "I wonder what the interns think of our code. Probably terrified", weight: 1, category: "filler" },
			{ template: "The AC is loud today. Or is that the fan on my laptop?", weight: 1, category: "filler" },
			{ template: "Three o'clock slump. Need snacks", weight: 1, category: "filler" },
			{ template: "Ah, the sweet sound of mechanical keyboards all around me", weight: 2, category: "filler" },
			{ template: "Hot take: YAML is worse than XML. There, I said it", weight: 2, category: "filler" },
			{ template: "Just got Cherry MX Browns. The thock is unreal. Life-changing, honestly", weight: 2, category: "filler" },
			{ template: "My side project repo has one star. It's from me. But it counts", weight: 2, category: "filler" },
			{ template: "Remember when we used jQuery for everything? Simpler times", weight: 1, category: "filler" },
			{ template: "Cat just walked across my keyboard. Added better code than me", weight: 2, category: "filler" },
			{ template: "I miss the old Stack Overflow days. Answering questions for internet points was peak motivation", weight: 1, category: "filler" },
			{ template: "Ultrawide monitor was the best investment. Two monitors? Amateur hour", weight: 1, category: "filler" },
			{ template: "Imposter syndrome hitting hard today. Everyone else's code looks so clean", weight: 2, category: "filler" },
			{ template: "Is it Friday yet? Time has no meaning when you're deep in a codebase", weight: 1, category: "filler" },
			{ template: "The AI generated an entire test suite. Half of it was wrong. Classic", weight: 2, category: "filler" },
			{ template: "Thinking about starting a new side project. I definitely won't finish it", weight: 2, category: "filler" },
			{ template: "My RSI is acting up. Time for wrist stretches and regret", weight: 1, category: "filler" },
			{ template: "The deployment superstition is: never deploy after 4pm. I don't make the rules", weight: 2, category: "filler" },
			{ template: "What show is everyone watching? I need something for while the tests run", weight: 1, category: "filler" },
			{ template: "Reorganizing my dotfiles. Productive procrastination at its finest", weight: 2, category: "filler" },
			{ template: "Browsing new VS Code extensions. Surely one more will fix everything", weight: 1, category: "filler" },
			{ template: "That npm audit output is giving me anxiety I don't need right now", weight: 2, category: "filler" },
			{ template: "I just alphabetized my imports. Don't ask why. It felt necessary", weight: 1, category: "filler" },
			{ template: "Watching a conference talk at 2x speed. Still too slow somehow", weight: 2, category: "filler" },
			{ template: "The tests are running and I have precisely enough time for nothing", weight: 1, category: "filler" },
			{ template: "Counting my open browser tabs. Thirty-seven. Each one essential", weight: 2, category: "filler" },
			{ template: "Reading the release notes for a tool I use daily. So many features I ignore", weight: 1, category: "filler" },
			{ template: "Wondering if my commit graph looks impressive enough on GitHub", weight: 2, category: "filler" },
			{ template: "Just discovered a shortcut I've needed for years. Life-changing", weight: 1, category: "filler" },
			{ template: "The office plant is dying. Debugging its water schedule", weight: 2, category: "filler" },
			{ template: "Scrolling through tech Twitter. Hot takes everywhere. Some even correct", weight: 1, category: "filler" },
			{ template: "My IDE theme has been the same for three years. Maybe it's time", weight: 1, category: "filler" },
			{ template: "That new language looks cool but I'm not starting another side project", weight: 2, category: "filler" },
			{ template: "Checking the Node.js changelog. Breaking changes? In my runtime?", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, have you seen this pattern before? It's wild", weight: 2, category: "social" },
			{ template: "Nice commit message, {nearby_agent}. Clear and descriptive. A rare breed", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to pair on this? I'm going in circles", weight: 1, category: "social" },
			{ template: "That's a clean solution, {nearby_agent}. I'm stealing that approach", weight: 2, category: "social" },
			{ template: "Anyone else think we should refactor that shared module? No? Just me?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your PR inspired me to fix something similar. Peer pressure works", weight: 1, category: "social" },
			{ template: "Good catch on that review, {nearby_agent}. Saved us from a headache", weight: 2, category: "social" },
			{ template: "Hey, quick architecture chat before we diverge too far?", weight: 1, category: "social" },
			{ template: "Who wants to rubber duck? I have a weird one", weight: 2, category: "social" },
			{ template: "{nearby_agent}, is your linter also yelling about this? Or just mine?", weight: 1, category: "social" },
			{ template: "Thanks for the code review, {nearby_agent}. Honest feedback is the best kind", weight: 2, category: "social" },
			{ template: "We should grab coffee and whiteboard this. Old school", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, quick sanity check on my approach?", weight: 2, category: "social" },
			{ template: "Whoever wrote these tests — thank you. Saved me an hour", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I think we're solving the same problem from different angles", weight: 1, category: "social" },
			{ template: "{nearby_agent}, you ever feel like the codebase is judging you? No? Just me?", weight: 2, category: "social" },
			{ template: "Anyone want the last donut? I'm asking but I'm also reaching for it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, remember when we said 'we'll fix it later'? It's later", weight: 2, category: "social" },
			{ template: "We should start a book club. But for RFCs", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, did you push that branch? I want to peek at your solution", weight: 1, category: "social" },
			{ template: "{nearby_agent}, what keyboard are you using? That sound is incredible", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the AI autocompleted my function with YOUR code style. It's learning from you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, opinions on React Server Components? I need to argue with someone", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I found a bug that's been hiding since the initial commit. Archaeology, basically", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you ever name a variable perfectly on the first try? Me neither", weight: 1, category: "social" },
			{ template: "{nearby_agent}, quick — TypeScript strict mode, yay or nay?", weight: 1, category: "social" },
			{ template: "Who else is working on side projects they'll never finish? Support group meeting at my desk", weight: 2, category: "social" },
			{ template: "{nearby_agent}, check out my monitor setup. Three screens. Yes it's necessary", weight: 1, category: "social" },
			{ template: "{nearby_agent}, did you deploy before or after your coffee? Because it matters", weight: 2, category: "social" },
			{ template: "Anyone else's pet constantly interrupting standup? Just WFH things", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I let the AI write the regex. I'm not ashamed. Okay I'm a little ashamed", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what are you gaming this weekend? I need a break from staring at code", weight: 1, category: "social" },
			{ template: "{nearby_agent}, tabs or spaces? Choose wisely. Friendships end over this", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your error handling is genuinely beautiful. I took notes", weight: 1, category: "social" },
			{ template: "{nearby_agent}, wanna do a lunch-and-learn on that pattern you used?", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your function names read like documentation. Teach the team", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I just rebased on your branch. Zero conflicts. We're in sync", weight: 2, category: "social" },
			{ template: "Who else thinks our CI is too slow? Support group at my desk", weight: 1, category: "social" },
			{ template: "{nearby_agent}, that utility you wrote? I use it in every file now", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to mob program this tricky bit? More fun together", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I left a comment on your PR. It's a compliment. Don't panic", weight: 2, category: "social" },
			{ template: "Anyone else's IDE running slow today or is it just my machine dying?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you crushed that refactor. The diff is art", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what terminal theme are you using? Need inspiration", weight: 1, category: "social" },
			{ template: "{nearby_agent}, we should write an ADR for that decision before we forget why", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your commit messages are poetry. I'm taking notes", weight: 2, category: "social" },
			{ template: "{nearby_agent}, opinions on monorepos? I have a slide deck ready. Always ready", weight: 1, category: "social" },
		],
	},
};
