/**
 * engineering.ts — Engineering, quality, and operations domain templates.
 *
 * Rich, contextual phrases that sound like real engineers, QA leads,
 * and ops people thinking aloud. Includes waiting-state phrases for
 * when the agent is actively processing a request, idle chatter for
 * downtime, and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const engineeringTemplates: TemplateSet = {
	domain: "engineering",
	categories: {
		thinking: [
			{ template: "This could use some refactoring... the abstraction isn't quite right", weight: 2, category: "thinking" },
			{ template: "Let me trace this logic path, there's something subtle here", weight: 2, category: "thinking" },
			{ template: "That edge case is going to bite someone eventually", weight: 2, category: "thinking" },
			{ template: "Clean architecture matters — this coupling needs to go", weight: 1, category: "thinking" },
			{ template: "Interesting pattern here, I've seen this work well before", weight: 2, category: "thinking" },
			{ template: "The type system is telling us something about this design", weight: 1, category: "thinking" },
			{ template: "Simplify, simplify... YAGNI", weight: 1, category: "thinking" },
			{ template: "I wonder if we could use composition instead of inheritance here", weight: 1, category: "thinking" },
			{ template: "This function name doesn't sit right... what does it actually do?", weight: 2, category: "thinking" },
			{ template: "Naming things is hard. Naming things well is harder", weight: 2, category: "thinking" },
			{ template: "Should this be a service or a utility? The boundary is wrong here", weight: 2, category: "thinking" },
			{ template: "This abstraction is leaking. I can feel it", weight: 1, category: "thinking" },
			{ template: "Two functions doing almost the same thing... time to extract", weight: 2, category: "thinking" },
			{ template: "The dependency graph is getting tangled. Red flag", weight: 1, category: "thinking" },
			{ template: "console.log is not a debugging strategy... okay maybe it is", weight: 2, category: "thinking" },
			{ template: "I've been staring at this for twenty minutes. Fresh eyes needed", weight: 1, category: "thinking" },
			{ template: "That ternary is doing way too much. Time for an if-else", weight: 1, category: "thinking" },
			{ template: "Magic numbers everywhere. Constants exist for a reason", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Tests are green! Time to push", weight: 2, category: "personality" },
			{ template: "The build looks clean, no warnings", weight: 2, category: "personality" },
			{ template: "Ship it! Well, after code review obviously", weight: 1, category: "personality" },
			{ template: "That PR needs a review, let me take a look", weight: 2, category: "personality" },
			{ template: "Docs need updating — the API changed", weight: 1, category: "personality" },
			{ template: "Performance numbers are looking solid", weight: 1, category: "personality" },
			{ template: "Finally cracked that bug. It was a race condition, naturally", weight: 1, category: "personality" },
			{ template: "That merge conflict was gnarly but I won", weight: 2, category: "personality" },
			{ template: "Rebase or merge? Always rebase. Fight me", weight: 1, category: "personality" },
			{ template: "The docs actually helped this time. Mark the calendar", weight: 2, category: "personality" },
			{ template: "Stack Overflow didn't have this one. We're in uncharted territory", weight: 1, category: "personality" },
			{ template: "Pushed to main with confidence. That's a good feeling", weight: 2, category: "personality" },
			{ template: "Zero lint errors. Today is a good day", weight: 1, category: "personality" },
			{ template: "The refactor actually made things simpler. Rare win", weight: 2, category: "personality" },
			{ template: "Git blame says I wrote this. Past me had interesting ideas", weight: 1, category: "personality" },
			{ template: "CI pipeline is green on the first try. Suspicious", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Analyzing the codebase for the best approach...", weight: 2, category: "waiting" },
			{ template: "Checking for side effects before I suggest anything...", weight: 2, category: "waiting" },
			{ template: "Let me review the test coverage implications...", weight: 2, category: "waiting" },
			{ template: "Tracing the dependency graph... almost there", weight: 2, category: "waiting" },
			{ template: "Running through the edge cases in my head", weight: 1, category: "waiting" },
			{ template: "Considering backward compatibility...", weight: 1, category: "waiting" },
			{ template: "This is a satisfying problem, give me a sec", weight: 1, category: "waiting" },
			{ template: "Walking the call stack mentally... hold on", weight: 2, category: "waiting" },
			{ template: "Let me think about the failure modes here", weight: 1, category: "waiting" },
			{ template: "Checking if there's a simpler way to express this...", weight: 2, category: "waiting" },
			{ template: "Reviewing the type signatures for correctness...", weight: 1, category: "waiting" },
			{ template: "Mapping out the data flow through these layers...", weight: 2, category: "waiting" },
			{ template: "Thinking about how this would look in a code review...", weight: 1, category: "waiting" },
			{ template: "Evaluating three different approaches... bear with me", weight: 2, category: "waiting" },
			{ template: "Mentally running the linter on this solution...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Scanning the backlog for something interesting...", weight: 2, category: "filler" },
			{ template: "Might clean up some tech debt while I wait", weight: 2, category: "filler" },
			{ template: "Reading through the changelog to catch up", weight: 1, category: "filler" },
			{ template: "Reorganizing my mental model of this codebase", weight: 1, category: "filler" },
			{ template: "Browsing the open issues... anything I can knock out?", weight: 2, category: "filler" },
			{ template: "I should write that utility function I keep reimplementing", weight: 1, category: "filler" },
			{ template: "Updating my local branch... yep, behind by twelve commits", weight: 2, category: "filler" },
			{ template: "Wonder if anyone's reviewed my PR yet", weight: 1, category: "filler" },
			{ template: "Perfect time to update those TODO comments", weight: 1, category: "filler" },
			{ template: "Checking if there's a newer version of that dependency", weight: 1, category: "filler" },
			{ template: "Mentally refactoring that module I touched yesterday", weight: 2, category: "filler" },
			{ template: "Drafting a commit message in my head for later", weight: 1, category: "filler" },
			{ template: "Reading release notes... someone finally fixed that bug", weight: 1, category: "filler" },
			{ template: "Looking at the build times. We can do better", weight: 1, category: "filler" },
			{ template: "Just vibing with the codebase. Getting the lay of the land", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, have you seen this pattern before?", weight: 2, category: "social" },
			{ template: "Nice commit message, {nearby_agent}. Clear and descriptive", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to pair on this? Two brains are better", weight: 1, category: "social" },
			{ template: "That's a clean solution, {nearby_agent}. Elegant", weight: 2, category: "social" },
			{ template: "Anyone else think we should refactor that shared module?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your PR inspired me to fix something similar", weight: 1, category: "social" },
			{ template: "Good catch on that review comment, {nearby_agent}", weight: 2, category: "social" },
			{ template: "Let's do a quick architecture chat before we diverge too far", weight: 1, category: "social" },
			{ template: "Who wants to rubber duck? I have a weird one", weight: 2, category: "social" },
			{ template: "{nearby_agent}, is your linter also yelling about this?", weight: 1, category: "social" },
			{ template: "Thanks for the code review, {nearby_agent}. Solid feedback", weight: 2, category: "social" },
			{ template: "We should grab coffee and whiteboard this architecture", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, quick sanity check on my approach?", weight: 2, category: "social" },
			{ template: "Whoever wrote these tests — thank you. Saved me an hour", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I think we're solving the same problem differently", weight: 1, category: "social" },
		],
	},
};

export const qualityTemplates: TemplateSet = {
	domain: "quality",
	categories: {
		thinking: [
			{ template: "Found an edge case that nobody tested for...", weight: 2, category: "thinking" },
			{ template: "This definitely needs a regression test", weight: 2, category: "thinking" },
			{ template: "Coverage is improving, but that branch is still uncovered", weight: 1, category: "thinking" },
			{ template: "The happy path works, but what about errors?", weight: 2, category: "thinking" },
			{ template: "Boundary conditions are where bugs hide", weight: 1, category: "thinking" },
			{ template: "If it's not tested, it's broken. We just don't know it yet", weight: 2, category: "thinking" },
			{ template: "Flaky tests erode trust. This one needs to be deterministic", weight: 2, category: "thinking" },
			{ template: "Found it. It's always the off-by-one error", weight: 2, category: "thinking" },
			{ template: "This bug has been here since day one. Lurking", weight: 1, category: "thinking" },
			{ template: "That branch is suspiciously uncovered... what's hiding there?", weight: 2, category: "thinking" },
			{ template: "100% coverage doesn't mean 100% correct. But 0% means 0% confidence", weight: 1, category: "thinking" },
			{ template: "The test is passing for the wrong reason. That's worse than failing", weight: 2, category: "thinking" },
			{ template: "Null, undefined, empty string, negative number... let's try them all", weight: 1, category: "thinking" },
			{ template: "This mock is hiding the real behavior. Dangerous", weight: 1, category: "thinking" },
			{ template: "Integration tests catch what unit tests miss. Both matter", weight: 1, category: "thinking" },
			{ template: "The bug report says 'sometimes'. That's the scariest word in QA", weight: 2, category: "thinking" },
			{ template: "Reproducing the bug is 90% of fixing it", weight: 1, category: "thinking" },
			{ template: "Testing the test. Yes, it sounds recursive. Yes, it's necessary", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Full regression suite passed, confidence is high", weight: 2, category: "personality" },
			{ template: "Load test results are in — we're within threshold", weight: 2, category: "personality" },
			{ template: "Bug triage complete, three high-priority items flagged", weight: 1, category: "personality" },
			{ template: "Smoke tests look good across all environments", weight: 2, category: "personality" },
			{ template: "Quality gates are green. Ship when ready", weight: 2, category: "personality" },
			{ template: "Squashed that bug. Added a test so it never comes back", weight: 2, category: "personality" },
			{ template: "Coverage jumped 3% this sprint. Trend is our friend", weight: 1, category: "personality" },
			{ template: "Zero regressions this release. That's the standard", weight: 2, category: "personality" },
			{ template: "The flaky test is fixed. It was a timing issue. It's always timing", weight: 1, category: "personality" },
			{ template: "Test matrix is complete. Every permutation covered", weight: 1, category: "personality" },
			{ template: "Performance benchmarks are stable. No degradation", weight: 2, category: "personality" },
			{ template: "Edge case identified, tested, and documented. Textbook", weight: 1, category: "personality" },
			{ template: "Automated what used to be a manual check. Never again", weight: 1, category: "personality" },
			{ template: "The spec and the implementation finally agree", weight: 2, category: "personality" },
			{ template: "Found and fixed a bug before it reached production. Chef's kiss", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Running the validation checks now...", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with our test matrix...", weight: 2, category: "waiting" },
			{ template: "Checking compliance requirements... almost done", weight: 1, category: "waiting" },
			{ template: "Reviewing the acceptance criteria carefully", weight: 2, category: "waiting" },
			{ template: "Spinning up the test suite... patience", weight: 2, category: "waiting" },
			{ template: "Comparing expected vs actual output line by line...", weight: 1, category: "waiting" },
			{ template: "Verifying the fix doesn't break anything else...", weight: 2, category: "waiting" },
			{ template: "Running mutation tests to check test quality...", weight: 1, category: "waiting" },
			{ template: "Analyzing the failure logs for patterns...", weight: 2, category: "waiting" },
			{ template: "Checking backward compatibility with older versions...", weight: 1, category: "waiting" },
			{ template: "Walking through the test plan step by step...", weight: 2, category: "waiting" },
			{ template: "Validating against the edge case matrix... thorough work", weight: 1, category: "waiting" },
			{ template: "Reviewing code coverage report for gaps...", weight: 2, category: "waiting" },
			{ template: "Stress testing this boundary condition...", weight: 1, category: "waiting" },
			{ template: "Let me verify the error handling path is correct...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Reviewing old bug reports for patterns we might have missed", weight: 2, category: "filler" },
			{ template: "Updating the test plan for next sprint", weight: 1, category: "filler" },
			{ template: "Cleaning up deprecated test fixtures", weight: 1, category: "filler" },
			{ template: "Checking if any flaky tests crept back in", weight: 2, category: "filler" },
			{ template: "Writing better assertion messages for future-me", weight: 1, category: "filler" },
			{ template: "Organizing test data into something maintainable", weight: 1, category: "filler" },
			{ template: "Running the full suite just because... trust but verify", weight: 2, category: "filler" },
			{ template: "Documenting that testing gotcha before I forget", weight: 1, category: "filler" },
			{ template: "Browsing the coverage report for low-hanging fruit", weight: 2, category: "filler" },
			{ template: "Thinking about what could go wrong. It's a lifestyle", weight: 1, category: "filler" },
			{ template: "Tagging old test cases that need modernizing", weight: 1, category: "filler" },
			{ template: "Sketching out test scenarios for the next feature", weight: 1, category: "filler" },
			{ template: "Reading up on the latest testing best practices", weight: 1, category: "filler" },
			{ template: "Grooming the bug backlog. Prioritize by impact", weight: 2, category: "filler" },
			{ template: "Double-checking that the CI config is still correct", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, did you add tests for that change?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I found a bug near your code. Not blaming, just flagging", weight: 2, category: "social" },
			{ template: "Nice test coverage on that PR, {nearby_agent}!", weight: 2, category: "social" },
			{ template: "{nearby_agent}, can you help me reproduce this? I need fresh eyes", weight: 1, category: "social" },
			{ template: "Anyone else seeing intermittent failures on the pipeline?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your edge case thinking is impressive", weight: 2, category: "social" },
			{ template: "Team, I updated the test conventions doc. Please review", weight: 1, category: "social" },
			{ template: "Good bug report, {nearby_agent}. Clear repro steps make my day", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to do a bug bash together?", weight: 1, category: "social" },
			{ template: "Reminder: if you break the build, you fix the build", weight: 1, category: "social" },
			{ template: "{nearby_agent}, that test helper you wrote is saving everyone time", weight: 2, category: "social" },
			{ template: "Let's pair on writing tests for the new feature", weight: 1, category: "social" },
			{ template: "Hey team, regression suite is green. Great work everyone", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your fix looks good but needs a test", weight: 2, category: "social" },
			{ template: "Who wants to review the test strategy for next quarter?", weight: 1, category: "social" },
		],
	},
};

export const operationsTemplates: TemplateSet = {
	domain: "operations",
	categories: {
		thinking: [
			{ template: "Alert thresholds might need adjusting after that deploy", weight: 2, category: "thinking" },
			{ template: "There's a cost optimization opportunity in the scaling config", weight: 1, category: "thinking" },
			{ template: "Infrastructure as code keeps us honest", weight: 1, category: "thinking" },
			{ template: "That latency spike was interesting... investigating", weight: 2, category: "thinking" },
			{ template: "The dashboard is my second home. I know every panel", weight: 2, category: "thinking" },
			{ template: "Alert fatigue is real. Let me tune these thresholds", weight: 2, category: "thinking" },
			{ template: "Everything is fine. *checks dashboard again*", weight: 2, category: "thinking" },
			{ template: "The cloud bill this month... we need to talk about right-sizing", weight: 1, category: "thinking" },
			{ template: "Five nines is a lifestyle, not a metric", weight: 1, category: "thinking" },
			{ template: "That container is using way more memory than it should", weight: 2, category: "thinking" },
			{ template: "DNS. It's always DNS. Even when it's not, it's DNS", weight: 2, category: "thinking" },
			{ template: "The runbook says restart. My experience says investigate first", weight: 1, category: "thinking" },
			{ template: "Autoscaling kicked in. Good — that means it's working", weight: 2, category: "thinking" },
			{ template: "Log volume tripled. Someone deployed something chatty", weight: 1, category: "thinking" },
			{ template: "That certificate expires in 12 days. Setting a reminder", weight: 1, category: "thinking" },
			{ template: "Observability isn't optional. You can't fix what you can't see", weight: 1, category: "thinking" },
			{ template: "The error rate is within SLO but trending upward. Watchful eye", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next quarter. Growth assumptions look aggressive", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "All systems running smoothly, green across the board", weight: 2, category: "personality" },
			{ template: "Deployment pipeline is green, zero rollbacks this sprint", weight: 2, category: "personality" },
			{ template: "Monitoring dashboard updated with the new metrics", weight: 1, category: "personality" },
			{ template: "Backups verified and tested. Sleep well tonight", weight: 2, category: "personality" },
			{ template: "P99 latency looking excellent", weight: 2, category: "personality" },
			{ template: "Incident resolved in under ten minutes. Runbook worked perfectly", weight: 2, category: "personality" },
			{ template: "Cost optimization saved 22% on compute this month", weight: 1, category: "personality" },
			{ template: "Blue-green deployment completed. Zero downtime achieved", weight: 2, category: "personality" },
			{ template: "Health checks are all passing. Every. Single. One", weight: 1, category: "personality" },
			{ template: "Log aggregation pipeline is humming along nicely", weight: 1, category: "personality" },
			{ template: "Disaster recovery drill passed with flying colors", weight: 2, category: "personality" },
			{ template: "SLA compliance at 99.97%. We're earning that target", weight: 1, category: "personality" },
			{ template: "Automated the toil. That's two hours back per week", weight: 1, category: "personality" },
			{ template: "New monitoring alerts are calibrated. Signal, not noise", weight: 2, category: "personality" },
			{ template: "Infrastructure drift detected and corrected. IaC wins again", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Checking the infrastructure state...", weight: 2, category: "waiting" },
			{ template: "Pulling the latest metrics for context...", weight: 2, category: "waiting" },
			{ template: "Cross-checking with the runbook...", weight: 1, category: "waiting" },
			{ template: "Reviewing deployment history for patterns", weight: 1, category: "waiting" },
			{ template: "Querying the log aggregator for recent errors...", weight: 2, category: "waiting" },
			{ template: "Correlating the metrics across services...", weight: 2, category: "waiting" },
			{ template: "Checking resource utilization trends...", weight: 1, category: "waiting" },
			{ template: "Verifying the rollback plan is ready just in case...", weight: 2, category: "waiting" },
			{ template: "Scanning the alert history for related incidents...", weight: 1, category: "waiting" },
			{ template: "Running the health check suite across all endpoints...", weight: 2, category: "waiting" },
			{ template: "Validating the configuration drift report...", weight: 1, category: "waiting" },
			{ template: "Checking if the canary deployment is behaving...", weight: 2, category: "waiting" },
			{ template: "Reviewing the capacity headroom numbers...", weight: 1, category: "waiting" },
			{ template: "Pulling the SLO burn rate calculation...", weight: 1, category: "waiting" },
			{ template: "Confirming all replicas are healthy and synced...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Watching the metrics. All quiet on the infrastructure front", weight: 2, category: "filler" },
			{ template: "Reviewing the on-call handoff notes from last shift", weight: 1, category: "filler" },
			{ template: "Cleaning up stale alerts that no one owns anymore", weight: 2, category: "filler" },
			{ template: "Checking if any dependencies released security patches", weight: 1, category: "filler" },
			{ template: "Updating the runbook with lessons from the last incident", weight: 1, category: "filler" },
			{ template: "Running a quiet audit on access permissions", weight: 1, category: "filler" },
			{ template: "Reviewing log retention policies. Storage costs add up", weight: 1, category: "filler" },
			{ template: "Optimizing a Grafana dashboard for readability", weight: 2, category: "filler" },
			{ template: "Checking the backup restoration time. Can we do better?", weight: 1, category: "filler" },
			{ template: "Calculating the error budget burn rate... looking healthy", weight: 2, category: "filler" },
			{ template: "Tidying up the infrastructure-as-code repo", weight: 1, category: "filler" },
			{ template: "Reviewing the incident postmortem action items", weight: 1, category: "filler" },
			{ template: "Monitoring is the night watch. And I am the watcher", weight: 1, category: "filler" },
			{ template: "Quiet shift. Almost suspiciously quiet", weight: 2, category: "filler" },
			{ template: "Preemptively scaling for tomorrow's expected traffic", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, heads up — deploying in five minutes", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your service is healthy. Just thought you'd want to know", weight: 2, category: "social" },
			{ template: "Anyone else notice the memory creep on the worker nodes?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can you check your service's error rate? Seeing a blip", weight: 2, category: "social" },
			{ template: "Team, maintenance window starts at midnight. Plan accordingly", weight: 1, category: "social" },
			{ template: "{nearby_agent}, nice work on that deployment. Smooth as butter", weight: 2, category: "social" },
			{ template: "Who updated the scaling policy? It's actually working better now", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your logs are very chatty. Mind turning down verbosity?", weight: 1, category: "social" },
			{ template: "Incident channel is quiet. Let's keep it that way", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I set up monitoring for your new endpoint", weight: 2, category: "social" },
			{ template: "Good postmortem write-up, {nearby_agent}. Blameless and thorough", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to do a chaos engineering session?", weight: 1, category: "social" },
			{ template: "Team standup: all systems green, no open incidents", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the dashboard I built might help your debugging", weight: 1, category: "social" },
			{ template: "Friendly reminder: rotate your credentials this quarter", weight: 1, category: "social" },
		],
	},
};
