/**
 * fragment-pools-cores.ts — Core fragment pools by domain.
 *
 * Extracted from fragment-pools.ts to keep files under 400 lines.
 * Each pool covers the "core" slot type, filtered by domain.
 */

import type { FragmentPool } from "../fragment-composer.js";

// ── Cores — general ──────────────────────────────────────────────────

export const GENERAL_CORES: FragmentPool = {
	id: "general-cores",
	slot: "core",
	filters: {},
	fragments: [
		"this is more complex than I thought",
		"the tests are passing suspiciously well",
		"the documentation is lying to me",
		"I've been looking at this too long",
		"something smells off in this module",
		"there's a pattern here I'm not seeing",
		"this should be simpler",
		"the build is taking forever",
		"I just learned something new",
		"that error message is actively unhelpful",
		"I need to step back and think",
		"my gut says this is wrong",
		"this works but I don't know why",
		"I've context-switched too many times today",
		"the edge cases are multiplying",
		"I keep second-guessing this decision",
		"the scope just doubled",
		"someone already solved this problem somewhere",
		"I need a rubber duck",
		"the naming here is deeply confusing",
		"this comment hasn't aged well",
		"I should have written the tests first",
		"everything connects to everything else",
		"I've lost track of what I was originally doing",
		"this is either brilliant or terrible",
		"the deadline is quietly looming",
		"I deleted more code than I added today — good",
		"we keep having the same conversation",
		"something changed and I don't know what",
		"this broke in a way I didn't expect",
		"the happy path works; the sad paths do not",
		"nobody told me this was deprecated",
		"I'm blocking on someone else's PR",
		"the requirements are ambiguous again",
		"this function is doing three jobs",
		"whoever named this variable was brave",
		"the ticket says nothing useful",
		"I'm rediscovering how this all works",
		"the debug session is becoming the main event",
		"I have too many tabs open",
		"the diff is way bigger than expected",
	],
};

// ── Cores — engineering ──────────────────────────────────────────────

export const ENGINEERING_CORES: FragmentPool = {
	id: "engineering-cores",
	slot: "core",
	filters: { domain: ["engineering"] },
	fragments: [
		"this dependency graph is a mess",
		"the type system is fighting me",
		"who wrote this migration",
		"the API contract changed again",
		"memory usage is climbing",
		"the CI pipeline is red again",
		"this needs a proper abstraction",
		"the race condition is back",
		"async/await saved my sanity",
		"the refactor is going well actually",
		"the lint rules are stricter than I remembered",
		"this import is circular — impossible, yet here we are",
		"the bundle size needs attention",
		"the cache invalidation logic is subtle",
		"I found a use-after-free and it was mine",
		"the config file is getting out of hand",
		"three libraries do this; none of them are documented",
		"the test runner is flipping between pass and fail",
		"the environment variable is missing in prod",
		"this only breaks in release builds",
		"the schema migration rolled back halfway",
		"the socket timeout is too aggressive",
		"I need to write a custom serializer",
		"the mock is leaking state between tests",
		"the hot-reload broke mid-session",
		"the performance regression crept in three commits ago",
		"the version lock is holding us back",
		"I just introduced a breaking change — intentionally",
		"the stack trace points to a compiled file",
		"this abstraction is fighting the language",
		"the integration test is order-dependent",
	],
};

// ── Cores — design ───────────────────────────────────────────────────

export const DESIGN_CORES: FragmentPool = {
	id: "design-cores",
	slot: "core",
	filters: { domain: ["design"] },
	fragments: [
		"the spacing is off by 2px",
		"this color palette needs work",
		"the user flow has too many steps",
		"accessibility audit found things",
		"the component library is inconsistent",
		"this animation timing is wrong",
		"white space is doing heavy lifting here",
		"the responsive breakpoints are a mess",
		"the design system needs an update",
		"font weights are all over the place",
		"the hover state is invisible",
		"nobody tested this on a small screen",
		"the icon set is sending mixed signals",
		"copy and design are in conflict here",
		"the button hierarchy is confusing",
		"the modal needs a better dismissal pattern",
		"the loading state is doing too much",
		"the dark mode version was forgotten",
		"the prototype doesn't match the spec",
		"the card layout breaks at 768px",
		"the tab order is chaotic",
		"contrast ratio won't pass WCAG",
		"the error state has no illustration",
		"the onboarding flow skips a key step",
		"the empty state copy is too apologetic",
		"the grid is 11 columns for some reason",
		"the border radius is inconsistent across cards",
	],
};

// ── Cores — product ──────────────────────────────────────────────────

export const PRODUCT_CORES: FragmentPool = {
	id: "product-cores",
	slot: "core",
	filters: { domain: ["product"] },
	fragments: [
		"the metrics tell an interesting story",
		"user feedback is mixed",
		"the roadmap needs revisiting",
		"stakeholders changed their minds again",
		"the A/B test results are in",
		"retention is trending up",
		"the feature request list is growing",
		"sprint scope is already creeping",
		"the competitor just shipped something",
		"user interviews were eye-opening",
		"the definition of done keeps shifting",
		"the KPIs contradict each other",
		"the launch date has strong opinions",
		"the beta cohort has strong opinions",
		"north star alignment is slipping",
		"the persona assumptions may be wrong",
		"the discovery phase revealed surprises",
		"the MVP is getting feature-full",
		"the usage data doesn't match the hypothesis",
		"the churn reason survey is illuminating",
		"the pricing model is under review again",
		"the onboarding funnel has a big drop-off",
		"the support tickets are clustering around one feature",
		"the executive review is next week",
		"the OKR check-in is overdue",
		"the quarterly planning is eating the calendar",
		"the product council has concerns",
	],
};

// ── Cores — quality ──────────────────────────────────────────────────

export const QUALITY_CORES: FragmentPool = {
	id: "quality-cores",
	slot: "core",
	filters: { domain: ["quality"] },
	fragments: [
		"the test coverage dropped below threshold",
		"the flaky test struck again",
		"the regression suite takes too long",
		"manual testing caught something automation missed",
		"the acceptance criteria were ambiguous",
		"the bug report has no steps to reproduce",
		"the edge case wasn't in the spec",
		"the staging environment drifted from prod",
		"the rollback plan is untested",
		"the test data is stale",
		"the severity rating is being debated",
		"the QA environment is down",
		"the smoke test is greener than expected",
		"a blocker is blocking the blocker",
		"the defect backlog needs triage",
		"the performance benchmark slipped",
		"the security scan flagged a dependency",
		"the integration test skips an entire service",
		"the test plan was written after the code",
		"the hotfix introduced a new bug",
		"the release checklist has forty-three items",
		"the canary deployment looks healthy so far",
		"the error rate spiked for twelve minutes",
		"the alert fired but nothing was wrong",
		"the post-mortem actions are still open",
		"the load test revealed the bottleneck",
	],
};

// ── Cores — operations ───────────────────────────────────────────────

export const OPERATIONS_CORES: FragmentPool = {
	id: "operations-cores",
	slot: "core",
	filters: { domain: ["operations"] },
	fragments: [
		"the deployment window is tonight",
		"the infrastructure costs jumped",
		"the on-call rotation is thin this week",
		"the service mesh is acting up",
		"the database needs a maintenance window",
		"the autoscaling kicked in earlier than expected",
		"the certificate expires in four days",
		"the backup job failed silently",
		"the incident report is due by EOD",
		"the runbook is outdated",
		"the terraform plan has surprises",
		"the cluster is running hot",
		"the log volume is spiking",
		"the queue depth is growing",
		"the CDN cache needs purging",
		"the canary is getting more traffic than planned",
		"the replica lag is creeping up",
		"the firewall rule is blocking the wrong thing",
		"the health check endpoint lied",
		"the secret rotation is overdue",
		"the network partition test failed gracefully",
		"the service dependency map is wrong",
		"the feature flag is stuck in one state",
		"the dashboard shows contradictory signals",
		"the scheduled job ran twice",
		"the capacity plan needs updating",
	],
};

// ── Cores — management ───────────────────────────────────────────────

export const MANAGEMENT_CORES: FragmentPool = {
	id: "management-cores",
	slot: "core",
	filters: { domain: ["management"] },
	fragments: [
		"the team velocity is down this sprint",
		"the standup went longer than fifteen minutes",
		"the retrospective action items went nowhere",
		"someone needs unblocking",
		"the 1-on-1 surfaced something important",
		"the team mood is lower than it should be",
		"the hiring pipeline has gaps",
		"the tech lead is spread too thin",
		"the project is three days from a slip",
		"the cross-team dependency is a risk",
		"the scope needs a conversation with the stakeholder",
		"the team norms document is overdue",
		"the onboarding process lost someone",
		"the recognition cadence has lapsed",
		"the estimation session took three hours",
		"the priority list changed overnight",
		"the project charter needs revisiting",
		"the working agreement was never agreed upon",
		"the escalation path is unclear",
		"the team needs a process cleanup",
		"the skills gap analysis is overdue",
		"the feedback cycle is too long",
		"the team is bigger than the work",
		"the communication overhead is real",
		"the roadmap alignment call got postponed again",
		"the decision log is missing three recent decisions",
	],
};
