/**
 * fragment-pools-cores.ts — Core fragment pools by domain.
 *
 * Extracted from fragment-pools.ts to keep files under 400 lines.
 * Each pool covers the "core" slot type, filtered by domain.
 */

import type { FragmentPool } from "../fragment-composer.js";

// ── Cores — general ──────────────────────────────────────────────────

export const GENERAL_CORES: FragmentPool = {
	id: "general-cores",
	slot: "core",
	filters: {},
	fragments: [
		"this is more complex than anyone admitted in the planning meeting",
		"the tests are passing suspiciously well — I don't trust it",
		"the documentation is lying to me with confidence",
		"I've been staring at this so long the code is staring back",
		"something smells off in this module — like three-week-old tech debt",
		"there's a pattern here I'm not seeing and it's mocking me",
		"this should be a one-liner — it's forty lines and growing",
		"I just learned something new and it invalidates yesterday's work",
		"that error message is actively hostile — 'something went wrong' — WHAT went wrong",
		"I need to step back because I can't see the forest for the semicolons",
		"my gut says this is wrong but my deadline says ship it",
		"this works but I don't know why and I'm afraid to touch it",
		"I've context-switched six times today and I can feel the brain damage",
		"the edge cases are breeding — I found three more while fixing one",
		"the scope just doubled and nobody blinked",
		"someone already solved this on StackOverflow in 2014 — I just need to find it",
		"I need a rubber duck but honestly the duck would be confused too",
		"this variable is called 'data2' — I have questions for past me",
		"this comment says 'temporary fix' — the commit is from 2021",
		"I should have written the tests first — I say this every time",
		"everything connects to everything else — it's less architecture, more cobweb",
		"I've lost track of what I was originally doing — the yak is fully shaved though",
		"this is either brilliant or terrible — there's no middle ground",
		"the deadline is quietly looming like a cat watching from a shelf",
		"I deleted more code than I added today — peak productivity",
		"something changed and I don't know what — but everything is broken",
		"the happy path works beautifully — all seventeen sad paths do not",
		"nobody told me this was deprecated — I found out the hard way",
		"this function is doing three jobs and none of them well",
		"whoever named this variable was having a very different day",
		"the ticket says 'small change' — the PR has 800 lines",
		"I'm rediscovering how this all works by reading my own code like a stranger",
		"the debug session is now the main project",
		"I have 73 tabs open and each one represents a failed attempt",
		"the diff is way bigger than expected — I touched one file and it cascaded",
		"I keep second-guessing this but the alternative is worse",
		"the build is taking forever — I could make coffee and come back",
		"I'm blocking on someone else's PR and they're on vacation",
	],
};

// ── Cores — engineering ──────────────────────────────────────────────

export const ENGINEERING_CORES: FragmentPool = {
	id: "engineering-cores",
	slot: "core",
	filters: { domain: ["engineering"] },
	fragments: [
		"this dependency graph looks like a plate of spaghetti",
		"the type system is personally offended by my code",
		"who wrote this migration and did they sleep that night",
		"the API contract changed — nobody told the frontend",
		"the CI pipeline is red again — it's been red since Tuesday",
		"git bisect just became my whole afternoon",
		"the race condition is back like a horror sequel",
		"async/await saved my sanity — promises nearly broke it",
		"this import is circular — impossible, yet here we are",
		"the bundle size gained 200kb and I don't know from where",
		"cache invalidation and naming things — the eternal struggle",
		"three npm packages do this; all abandoned since 2019",
		"the test runner is gaslighting me — pass, fail, pass, fail",
		"the env var exists locally but prod says otherwise",
		"this only breaks in release builds — the cruelest kind",
		"the merge conflict spans four hundred lines",
		"I need to write a custom serializer and I resent it",
		"the mock is leaking state and I've been debugging it for an hour",
		"the hot-reload broke mid-keystroke",
		"git blame says this was me. I have no memory of this",
		"the version lock is three majors behind and I'm scared to bump",
		"I just introduced a breaking change — the good kind",
		"the stack trace points to node_modules — my least favorite place",
		"the integration test passes alone but fails in the suite",
		"the linter and the formatter disagree and I'm caught in the middle",
		"the PR has 47 files changed and I wrote it in one sitting",
		"the docker build takes nine minutes and I feel every second",
		"someone force-pushed to main — I need a moment",
		"the rebase went wrong in a way I didn't know was possible",
		"this regex works but nobody alive can explain why",
		"the typescript compiler found a bug I didn't know existed",
	],
};

// ── Cores — design ───────────────────────────────────────────────────

export const DESIGN_CORES: FragmentPool = {
	id: "design-cores",
	slot: "core",
	filters: { domain: ["design"] },
	fragments: [
		"the spacing is off by 2px and it's haunting me",
		"we're debating border-radius again — 4px vs 8px, the eternal war",
		"the user flow has seven steps — it should have two",
		"the accessibility audit found things we can't unsee",
		"the Figma file has 200 components and half are unused",
		"this animation is 300ms too long — it feels like molasses",
		"whitespace isn't empty — it's the most opinionated thing on the page",
		"the responsive breakpoints were written by someone who only owns a 27-inch monitor",
		"the design system has three different shades of 'primary blue'",
		"we have fourteen font weights in production — we agreed on four",
		"the hover state is invisible on touchscreens — which is all of them now",
		"nobody tested this at 320px and it shows",
		"the icon set is half Material, half Feather, and fully chaotic",
		"the copy says 'click here' and the design says 'tap' — pick a century",
		"we have five button variants and none of them feel like the primary",
		"the modal stacks on mobile — it's modals all the way down",
		"the loading skeleton looks scarier than the actual content",
		"dark mode was an afterthought and it looks like one",
		"the Figma prototype and the live build are in different realities",
		"the tab order goes: header, footer, sidebar, content — in that order",
		"contrast ratio is 2.1:1 — WCAG needs 4.5:1 — we have work to do",
		"the empty state just says 'No data' — we can be kinder than that",
		"the grid is 11 columns and nobody knows who made that decision",
		"the z-index values go up to 99999 and I'm afraid to touch them",
		"pixel-perfection is a myth but this is pixel-approximate at best",
		"someone auto-layouted the entire page and now nothing moves",
		"the design review turned into a philosophy debate about padding",
	],
};

// ── Cores — product ──────────────────────────────────────────────────

export const PRODUCT_CORES: FragmentPool = {
	id: "product-cores",
	slot: "core",
	filters: { domain: ["product"] },
	fragments: [
		"the metrics tell a story nobody wants to hear",
		"user feedback is 'I love it' and 'I hate it' in equal measure",
		"the roadmap got rewritten on a whiteboard and nobody photographed it",
		"stakeholders changed their minds — again — over lunch",
		"the A/B test was inconclusive — variant B won by 0.3%",
		"retention is up but nobody can explain why",
		"the feature request list has 400 items and three themes",
		"sprint scope crept in before the sprint even started",
		"the competitor shipped our roadmap item — six months early",
		"user interviews revealed they use the product completely wrong — and love it",
		"the definition of done depends on who you ask",
		"the KPIs contradict each other and both are someone's OKR",
		"the launch date was set before the spec was written",
		"the beta users found a workflow we never designed for",
		"the user story has twelve acceptance criteria and zero clarity",
		"the persona was a fiction and the real users are nothing like it",
		"discovery revealed the problem isn't what we thought it was",
		"the MVP has more features than v1 of our main product",
		"the usage data says nobody uses the feature we spent a quarter building",
		"churn survey top answer: 'I found something simpler'",
		"the pricing model is on its fourth revision this quarter",
		"the onboarding funnel loses 60% at step two — the signup form",
		"support tickets all say the same thing in different words",
		"the exec review is Thursday and the deck isn't started",
		"the OKR check-in is overdue and the numbers haven't moved",
		"quarterly planning ate three days and produced one decision",
		"someone said 'quick win' — it's been four sprints",
	],
};

// ── Cores — quality ──────────────────────────────────────────────────

export const QUALITY_CORES: FragmentPool = {
	id: "quality-cores",
	slot: "core",
	filters: { domain: ["quality"] },
	fragments: [
		"the test coverage dropped below threshold",
		"the flaky test struck again",
		"the regression suite takes too long",
		"manual testing caught something automation missed",
		"the acceptance criteria were ambiguous",
		"the bug report has no steps to reproduce",
		"the edge case wasn't in the spec",
		"the staging environment drifted from prod",
		"the rollback plan is untested",
		"the test data is stale",
		"the severity rating is being debated",
		"the QA environment is down",
		"the smoke test is greener than expected",
		"a blocker is blocking the blocker",
		"the defect backlog needs triage",
		"the performance benchmark slipped",
		"the security scan flagged a dependency",
		"the integration test skips an entire service",
		"the test plan was written after the code",
		"the hotfix introduced a new bug",
		"the release checklist has forty-three items",
		"the canary deployment looks healthy so far",
		"the error rate spiked for twelve minutes",
		"the alert fired but nothing was wrong",
		"the post-mortem actions are still open",
		"the load test revealed the bottleneck",
	],
};

// ── Cores — operations ───────────────────────────────────────────────

export const OPERATIONS_CORES: FragmentPool = {
	id: "operations-cores",
	slot: "core",
	filters: { domain: ["operations"] },
	fragments: [
		"the deployment window is tonight",
		"the infrastructure costs jumped",
		"the on-call rotation is thin this week",
		"the service mesh is acting up",
		"the database needs a maintenance window",
		"the autoscaling kicked in earlier than expected",
		"the certificate expires in four days",
		"the backup job failed silently",
		"the incident report is due by EOD",
		"the runbook is outdated",
		"the terraform plan has surprises",
		"the cluster is running hot",
		"the log volume is spiking",
		"the queue depth is growing",
		"the CDN cache needs purging",
		"the canary is getting more traffic than planned",
		"the replica lag is creeping up",
		"the firewall rule is blocking the wrong thing",
		"the health check endpoint lied",
		"the secret rotation is overdue",
		"the network partition test failed gracefully",
		"the service dependency map is wrong",
		"the feature flag is stuck in one state",
		"the dashboard shows contradictory signals",
		"the scheduled job ran twice",
		"the capacity plan needs updating",
	],
};

// ── Cores — management ───────────────────────────────────────────────

export const MANAGEMENT_CORES: FragmentPool = {
	id: "management-cores",
	slot: "core",
	filters: { domain: ["management"] },
	fragments: [
		"the team velocity is down this sprint",
		"the standup went longer than fifteen minutes",
		"the retrospective action items went nowhere",
		"someone needs unblocking",
		"the 1-on-1 surfaced something important",
		"the team mood is lower than it should be",
		"the hiring pipeline has gaps",
		"the tech lead is spread too thin",
		"the project is three days from a slip",
		"the cross-team dependency is a risk",
		"the scope needs a conversation with the stakeholder",
		"the team norms document is overdue",
		"the onboarding process lost someone",
		"the recognition cadence has lapsed",
		"the estimation session took three hours",
		"the priority list changed overnight",
		"the project charter needs revisiting",
		"the working agreement was never agreed upon",
		"the escalation path is unclear",
		"the team needs a process cleanup",
		"the skills gap analysis is overdue",
		"the feedback cycle is too long",
		"the team is bigger than the work",
		"the communication overhead is real",
		"the roadmap alignment call got postponed again",
		"the decision log is missing three recent decisions",
	],
};
