/**
 * fragment-pools.ts — 500+ composable fragments across 17 pools.
 *
 * These are the building blocks for the FragmentComposer. Each pool covers
 * a single slot type and is optionally filtered by mood or domain so the
 * composer can assemble contextually appropriate phrases.
 *
 * Slot types:  opener | core | closer | qualifier | interjection
 * Filter keys: mood, domain (others available in FragmentPool but unused here)
 */

import type { FragmentPool } from "../fragment-composer.js";

// ── Openers ───────────────────────────────────────────────────────────

const NEUTRAL_OPENERS: FragmentPool = {
	id: "neutral-openers",
	slot: "opener",
	filters: {},
	fragments: [
		"Hmm,",
		"So,",
		"Well,",
		"Okay so,",
		"Right,",
		"Anyway,",
		"Thing is,",
		"Look,",
		"Honestly,",
		"Listen,",
		"Here's the thing,",
		"Y'know,",
		"I mean,",
		"Fun fact:",
		"No but seriously,",
		"Hear me out,",
		"Not gonna lie,",
		"The thing about this is,",
		"Real talk,",
		"Between us,",
		"For the record,",
		"Worth mentioning —",
		"Heads up,",
		"Quick note:",
		"Side observation:",
	],
};

const EXCITED_OPENERS: FragmentPool = {
	id: "excited-openers",
	slot: "opener",
	filters: { mood: ["excited"] },
	fragments: [
		"YES!",
		"Oh wow!",
		"This is great—",
		"I'm pumped—",
		"Get this—",
		"Wait till you hear—",
		"Best news—",
		"Okay I'm excited—",
		"You're gonna love this—",
		"Guess what—",
		"FINALLY!",
		"This is it—",
		"I can't believe—",
		"Hold on—",
		"This changes everything—",
		"Oh my gosh,",
		"You have to hear this—",
		"I'm not even joking—",
	],
};

const TIRED_OPENERS: FragmentPool = {
	id: "tired-openers",
	slot: "opener",
	filters: { mood: ["tired"] },
	fragments: [
		"Ugh,",
		"So tired...",
		"I can't even...",
		"Brain fog...",
		"Why am I still here...",
		"Just...",
		"I have no words.",
		"Send coffee.",
		"My eyes...",
		"Is it Friday yet?",
		"Everything hurts.",
		"I'm running on fumes.",
		"Zero energy left.",
		"One more hour...",
		"Can't think straight.",
		"Barely functional,",
		"On autopilot,",
	],
};

const FRUSTRATED_OPENERS: FragmentPool = {
	id: "frustrated-openers",
	slot: "opener",
	filters: { mood: ["frustrated"] },
	fragments: [
		"Are you kidding me?",
		"Again?!",
		"Seriously?",
		"This is—",
		"I can't—",
		"WHY.",
		"No. Just no.",
		"That's it.",
		"I'm done.",
		"How hard can it be?",
		"Of course.",
		"Classic.",
		"Unbelievable.",
		"For the THIRD time—",
		"You know what—",
		"I give up trying to understand this.",
		"Not this again.",
	],
};

// ── Cores — general ──────────────────────────────────────────────────

const GENERAL_CORES: FragmentPool = {
	id: "general-cores",
	slot: "core",
	filters: {},
	fragments: [
		"this is more complex than I thought",
		"the tests are passing suspiciously well",
		"the documentation is lying to me",
		"I've been looking at this too long",
		"something smells off in this module",
		"there's a pattern here I'm not seeing",
		"this should be simpler",
		"the build is taking forever",
		"I just learned something new",
		"that error message is actively unhelpful",
		"I need to step back and think",
		"my gut says this is wrong",
		"this works but I don't know why",
		"I've context-switched too many times today",
		"the edge cases are multiplying",
		"I keep second-guessing this decision",
		"the scope just doubled",
		"someone already solved this problem somewhere",
		"I need a rubber duck",
		"the naming here is deeply confusing",
		"this comment hasn't aged well",
		"I should have written the tests first",
		"everything connects to everything else",
		"I've lost track of what I was originally doing",
		"this is either brilliant or terrible",
		"the deadline is quietly looming",
		"I deleted more code than I added today — good",
		"we keep having the same conversation",
		"something changed and I don't know what",
		"this broke in a way I didn't expect",
		"the happy path works; the sad paths do not",
		"nobody told me this was deprecated",
		"I'm blocking on someone else's PR",
		"the requirements are ambiguous again",
		"this function is doing three jobs",
		"whoever named this variable was brave",
		"the ticket says nothing useful",
		"I'm rediscovering how this all works",
		"the debug session is becoming the main event",
		"I have too many tabs open",
		"the diff is way bigger than expected",
	],
};

// ── Cores — engineering ──────────────────────────────────────────────

const ENGINEERING_CORES: FragmentPool = {
	id: "engineering-cores",
	slot: "core",
	filters: { domain: ["engineering"] },
	fragments: [
		"this dependency graph is a mess",
		"the type system is fighting me",
		"who wrote this migration",
		"the API contract changed again",
		"memory usage is climbing",
		"the CI pipeline is red again",
		"this needs a proper abstraction",
		"the race condition is back",
		"async/await saved my sanity",
		"the refactor is going well actually",
		"the lint rules are stricter than I remembered",
		"this import is circular — impossible, yet here we are",
		"the bundle size needs attention",
		"the cache invalidation logic is subtle",
		"I found a use-after-free and it was mine",
		"the config file is getting out of hand",
		"three libraries do this; none of them are documented",
		"the test runner is flipping between pass and fail",
		"the environment variable is missing in prod",
		"this only breaks in release builds",
		"the schema migration rolled back halfway",
		"the socket timeout is too aggressive",
		"I need to write a custom serializer",
		"the mock is leaking state between tests",
		"the hot-reload broke mid-session",
		"the performance regression crept in three commits ago",
		"the version lock is holding us back",
		"I just introduced a breaking change — intentionally",
		"the stack trace points to a compiled file",
		"this abstraction is fighting the language",
		"the integration test is order-dependent",
	],
};

// ── Cores — design ───────────────────────────────────────────────────

const DESIGN_CORES: FragmentPool = {
	id: "design-cores",
	slot: "core",
	filters: { domain: ["design"] },
	fragments: [
		"the spacing is off by 2px",
		"this color palette needs work",
		"the user flow has too many steps",
		"accessibility audit found things",
		"the component library is inconsistent",
		"this animation timing is wrong",
		"white space is doing heavy lifting here",
		"the responsive breakpoints are a mess",
		"the design system needs an update",
		"font weights are all over the place",
		"the hover state is invisible",
		"nobody tested this on a small screen",
		"the icon set is sending mixed signals",
		"copy and design are in conflict here",
		"the button hierarchy is confusing",
		"the modal needs a better dismissal pattern",
		"the loading state is doing too much",
		"the dark mode version was forgotten",
		"the prototype doesn't match the spec",
		"the card layout breaks at 768px",
		"the tab order is chaotic",
		"contrast ratio won't pass WCAG",
		"the error state has no illustration",
		"the onboarding flow skips a key step",
		"the empty state copy is too apologetic",
		"the grid is 11 columns for some reason",
		"the border radius is inconsistent across cards",
	],
};

// ── Cores — product ──────────────────────────────────────────────────

const PRODUCT_CORES: FragmentPool = {
	id: "product-cores",
	slot: "core",
	filters: { domain: ["product"] },
	fragments: [
		"the metrics tell an interesting story",
		"user feedback is mixed",
		"the roadmap needs revisiting",
		"stakeholders changed their minds again",
		"the A/B test results are in",
		"retention is trending up",
		"the feature request list is growing",
		"sprint scope is already creeping",
		"the competitor just shipped something",
		"user interviews were eye-opening",
		"the definition of done keeps shifting",
		"the KPIs contradict each other",
		"the launch date has strong opinions",
		"the beta cohort has strong opinions",
		"north star alignment is slipping",
		"the persona assumptions may be wrong",
		"the discovery phase revealed surprises",
		"the MVP is getting feature-full",
		"the usage data doesn't match the hypothesis",
		"the churn reason survey is illuminating",
		"the pricing model is under review again",
		"the onboarding funnel has a big drop-off",
		"the support tickets are clustering around one feature",
		"the executive review is next week",
		"the OKR check-in is overdue",
		"the quarterly planning is eating the calendar",
		"the product council has concerns",
	],
};

// ── Cores — quality ──────────────────────────────────────────────────

const QUALITY_CORES: FragmentPool = {
	id: "quality-cores",
	slot: "core",
	filters: { domain: ["quality"] },
	fragments: [
		"the test coverage dropped below threshold",
		"the flaky test struck again",
		"the regression suite takes too long",
		"manual testing caught something automation missed",
		"the acceptance criteria were ambiguous",
		"the bug report has no steps to reproduce",
		"the edge case wasn't in the spec",
		"the staging environment drifted from prod",
		"the rollback plan is untested",
		"the test data is stale",
		"the severity rating is being debated",
		"the QA environment is down",
		"the smoke test is greener than expected",
		"a blocker is blocking the blocker",
		"the defect backlog needs triage",
		"the performance benchmark slipped",
		"the security scan flagged a dependency",
		"the integration test skips an entire service",
		"the test plan was written after the code",
		"the hotfix introduced a new bug",
		"the release checklist has forty-three items",
		"the canary deployment looks healthy so far",
		"the error rate spiked for twelve minutes",
		"the alert fired but nothing was wrong",
		"the post-mortem actions are still open",
		"the load test revealed the bottleneck",
	],
};

// ── Cores — operations ───────────────────────────────────────────────

const OPERATIONS_CORES: FragmentPool = {
	id: "operations-cores",
	slot: "core",
	filters: { domain: ["operations"] },
	fragments: [
		"the deployment window is tonight",
		"the infrastructure costs jumped",
		"the on-call rotation is thin this week",
		"the service mesh is acting up",
		"the database needs a maintenance window",
		"the autoscaling kicked in earlier than expected",
		"the certificate expires in four days",
		"the backup job failed silently",
		"the incident report is due by EOD",
		"the runbook is outdated",
		"the terraform plan has surprises",
		"the cluster is running hot",
		"the log volume is spiking",
		"the queue depth is growing",
		"the CDN cache needs purging",
		"the canary is getting more traffic than planned",
		"the replica lag is creeping up",
		"the firewall rule is blocking the wrong thing",
		"the health check endpoint lied",
		"the secret rotation is overdue",
		"the network partition test failed gracefully",
		"the service dependency map is wrong",
		"the feature flag is stuck in one state",
		"the dashboard shows contradictory signals",
		"the scheduled job ran twice",
		"the capacity plan needs updating",
	],
};

// ── Cores — management ───────────────────────────────────────────────

const MANAGEMENT_CORES: FragmentPool = {
	id: "management-cores",
	slot: "core",
	filters: { domain: ["management"] },
	fragments: [
		"the team velocity is down this sprint",
		"the standup went longer than fifteen minutes",
		"the retrospective action items went nowhere",
		"someone needs unblocking",
		"the 1-on-1 surfaced something important",
		"the team mood is lower than it should be",
		"the hiring pipeline has gaps",
		"the tech lead is spread too thin",
		"the project is three days from a slip",
		"the cross-team dependency is a risk",
		"the scope needs a conversation with the stakeholder",
		"the team norms document is overdue",
		"the onboarding process lost someone",
		"the recognition cadence has lapsed",
		"the estimation session took three hours",
		"the priority list changed overnight",
		"the project charter needs revisiting",
		"the working agreement was never agreed upon",
		"the escalation path is unclear",
		"the team needs a process cleanup",
		"the skills gap analysis is overdue",
		"the feedback cycle is too long",
		"the team is bigger than the work",
		"the communication overhead is real",
		"the roadmap alignment call got postponed again",
		"the decision log is missing three recent decisions",
	],
};

// ── Closers — general ────────────────────────────────────────────────

const GENERAL_CLOSERS: FragmentPool = {
	id: "general-closers",
	slot: "closer",
	filters: {},
	fragments: [
		"...probably fine",
		"...I think",
		"...maybe",
		"...we'll see",
		"...let's not talk about it",
		"...noted",
		"...right?",
		"...or not",
		"...whatever works",
		"...that's a tomorrow problem",
		"...hopefully",
		"...fingers crossed",
		"...in theory",
		"...famous last words",
		"...what could go wrong",
		"...on second thought",
		"...I'll figure it out",
		"...eventually",
		"...it is what it is",
		"...but don't quote me",
		"...allegedly",
		"...somehow",
		"...not my finest moment",
		"...could be worse",
		"...I've been wrong before",
		"...unclear, will update",
		"...asking for a friend",
		"...results may vary",
		"...terms and conditions apply",
		"...moving on",
		"...this is fine",
		"...we do what we can",
		"...that tracks",
		"...more details to follow",
		"...good enough for now",
		"...not ideal",
		"...ship it",
		"...TBD",
		"...per my last message",
		"...live and learn",
		"...at least it compiles",
	],
};

// ── Closers — frustrated ─────────────────────────────────────────────

const FRUSTRATED_CLOSERS: FragmentPool = {
	id: "frustrated-closers",
	slot: "closer",
	filters: { mood: ["frustrated"] },
	fragments: [
		"...I give up",
		"...send help",
		"...everything is on fire",
		"...I need a break",
		"...why do I do this",
		"...not okay",
		"...this is beyond me",
		"...I'll deal with it later",
		"...just WHY",
		"...cool cool cool",
		"...totally fine",
		"...no big deal",
		"...definitely not screaming inside",
		"...perfect, this is perfect",
		"...it's someone else's problem now",
		"...I need to walk away",
		"...I won't say what I'm thinking",
		"...deep breaths",
		"...clock is ticking",
		"...this has cost me years",
		"...thanks for nothing, documentation",
	],
};

// ── Closers — tired ──────────────────────────────────────────────────

const TIRED_CLOSERS: FragmentPool = {
	id: "tired-closers",
	slot: "closer",
	filters: { mood: ["tired"] },
	fragments: [
		"...need sleep",
		"...coffee isn't working",
		"...eyes closing",
		"...five more minutes",
		"...where was I",
		"...tomorrow brain will understand this",
		"...can't focus",
		"...too tired to care",
		"...just one more thing",
		"...done for today",
		"...shutdown initiated",
		"...if I could just nap for twelve minutes",
		"...not retaining anything I read",
		"...writing comments for future-me to understand",
		"...my notes from earlier make no sense",
		"...going through motions",
		"...at least it's quiet",
		"...almost human again after coffee",
		"...shouldn't be coding this tired",
		"...committed and logging off",
	],
};

// ── Qualifiers — general ─────────────────────────────────────────────

const GENERAL_QUALIFIERS: FragmentPool = {
	id: "general-qualifiers",
	slot: "qualifier",
	filters: {},
	fragments: [
		"...but what do I know",
		"...in theory",
		"...at least in my experience",
		"...or so I'm told",
		"...not that it matters",
		"...but I could be wrong",
		"...take that with a grain of salt",
		"...for what it's worth",
		"...just my two cents",
		"...allegedly",
		"...technically speaking",
		"...from where I'm standing",
		"...if I had to guess",
		"...by my estimation",
		"...without all the context",
		"...ignoring the obvious caveats",
		"...this is a preliminary view",
		"...I haven't tested this exhaustively",
		"...your mileage may vary",
		"...that's the charitable interpretation",
		"...the data suggests",
		"...loosely",
		"...for some definition of 'works'",
		"...barring any surprises",
		"...assuming the docs are accurate",
		"...pending a closer look",
		"...on the surface at least",
		"...by most reasonable measures",
		"...based on incomplete information",
		"...I reserve the right to be wrong",
		"...in a best-case scenario",
	],
};

// ── Qualifiers — confident (excited mood) ────────────────────────────

const CONFIDENT_QUALIFIERS: FragmentPool = {
	id: "confident-qualifiers",
	slot: "qualifier",
	filters: { mood: ["excited"] },
	fragments: [
		"...and I'm right about this",
		"...trust me on this",
		"...I know what I'm talking about",
		"...I checked twice",
		"...this is solid",
		"...no caveats needed",
		"...the data backs this up",
		"...I'd stake my reputation on it",
		"...this is the move",
		"...I've never been more certain",
		"...this is the way",
		"...verified and confirmed",
		"...no doubts here",
		"...100% on this one",
		"...absolutely certain",
		"...I've thought this through",
	],
};

// ── Interjections — general ──────────────────────────────────────────

const GENERAL_INTERJECTIONS: FragmentPool = {
	id: "general-interjections",
	slot: "interjection",
	filters: {},
	fragments: [
		"Wait—",
		"Oh—",
		"Huh.",
		"Actually—",
		"Hold on—",
		"Oh no—",
		"Interesting—",
		"Okay so—",
		"Ha—",
		"Whoa—",
		"Hmm—",
		"Oh boy—",
		"Yikes—",
		"Right—",
		"No way—",
		"Oh wow—",
		"Okay wait—",
		"Huh, okay—",
		"Oh that's—",
		"Wait wait wait—",
		"Oh interesting—",
		"Uh—",
		"So—",
		"Actually, hold on—",
		"Nope—",
	],
};

// ── Interjections — surprised (excited mood) ─────────────────────────

const SURPRISED_INTERJECTIONS: FragmentPool = {
	id: "surprised-interjections",
	slot: "interjection",
	filters: { mood: ["excited"] },
	fragments: [
		"OH WAIT—",
		"NO WAY—",
		"WHAT—",
		"OH MY—",
		"Are you SERIOUS—",
		"I can't believe—",
		"THIS IS—",
		"Okay WOW—",
		"Stop EVERYTHING—",
		"Hold up HOLD UP—",
		"I was NOT expecting—",
		"FINALLY—",
		"OH WOW—",
		"You won't believe—",
		"THE BEST THING JUST—",
		"I need everyone to see—",
	],
};

// ── Export ────────────────────────────────────────────────────────────

export const ALL_FRAGMENT_POOLS: readonly FragmentPool[] = [
	// Openers
	NEUTRAL_OPENERS,
	EXCITED_OPENERS,
	TIRED_OPENERS,
	FRUSTRATED_OPENERS,
	// Cores
	GENERAL_CORES,
	ENGINEERING_CORES,
	DESIGN_CORES,
	PRODUCT_CORES,
	QUALITY_CORES,
	OPERATIONS_CORES,
	MANAGEMENT_CORES,
	// Closers
	GENERAL_CLOSERS,
	FRUSTRATED_CLOSERS,
	TIRED_CLOSERS,
	// Qualifiers
	GENERAL_QUALIFIERS,
	CONFIDENT_QUALIFIERS,
	// Interjections
	GENERAL_INTERJECTIONS,
	SURPRISED_INTERJECTIONS,
];
