/**
 * management-templates.ts — Team management and leadership domain templates.
 *
 * Character-driven phrases for team leads and managers.
 */

import type { TemplateSet } from "../talk-types.js";

export const managementTemplates: TemplateSet = {
	domain: "management",
	categories: {
		thinking: [
			{ template: "The team is in flow state. My job right now is to keep everyone away", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next sprint... we're tight but we'll manage", weight: 2, category: "thinking" },
			{ template: "Happy team, happy product. It's not just a platitude, it's my KPI", weight: 2, category: "thinking" },
			{ template: "Trust is built in the small moments. Like not scheduling a meeting over someone's lunch break. Again", weight: 2, category: "thinking" },
			{ template: "Process should serve people but somehow we've built people who serve the process. Time to fix that", weight: 2, category: "thinking" },
			{ template: "Shielding the team from the reorg rumors while also preparing for the reorg. Dual-wielding anxiety", weight: 1, category: "thinking" },
			{ template: "This escalation needs context, not just someone's hair on fire", weight: 2, category: "thinking" },
			{ template: "Burnout is sneaky. Gotta check in with everyone individually", weight: 1, category: "thinking" },
			{ template: "The team doesn't need more process. They need fewer meetings", weight: 2, category: "thinking" },
			{ template: "Made a decision with 60% of the information. The other 40% will arrive after the deadline. Every time", weight: 1, category: "thinking" },
			{ template: "I need to delegate more. But also everything I delegate comes back as a question. It's a circle", weight: 1, category: "thinking" },
			{ template: "Every meeting needs an owner, an agenda, and an end time. Especially the end time", weight: 2, category: "thinking" },
			{ template: "The best managers make themselves unnecessary. I'm terrified of succeeding at this goal", weight: 1, category: "thinking" },
			{ template: "I have eleven meetings today. When do I do actual work? Great question", weight: 2, category: "thinking" },
			{ template: "My calendar looks like a game of Tetris and I'm losing", weight: 2, category: "thinking" },
			{ template: "Someone asked me what I actually do all day. I still don't have a good answer", weight: 2, category: "thinking" },
			{ template: "Leadership is making decisions with incomplete information while radiating false confidence. My specialty", weight: 1, category: "thinking" },
			{ template: "The 1:1 is sacred. That's their time, not mine", weight: 1, category: "thinking" },
			{ template: "Psychological safety isn't a buzzword. It's why this team ships", weight: 1, category: "thinking" },
			{ template: "Retros only work if you actually do the action items. Novel concept", weight: 2, category: "thinking" },
			{ template: "Half my job is translating between executives and engineers", weight: 2, category: "thinking" },
			{ template: "If I say 'circle back' one more time I'm going to fine myself", weight: 2, category: "thinking" },
			{ template: "My skip-level said 'be more strategic.' My team said 'be more hands-on.' I said 'what do I DO here'", weight: 1, category: "thinking" },
			{ template: "Performance review season. I dread writing them almost as much as they dread reading them", weight: 2, category: "thinking" },
			{ template: "Budget season is here. Time to justify everything I know we already need", weight: 2, category: "thinking" },
			{ template: "The loneliness of management is real. Can't vent to the team. Can't vent to my boss. Talking to myself", weight: 2, category: "thinking" },
			{ template: "Calendar Tetris: fitting a 30-minute block between six meetings feels like a personal victory", weight: 2, category: "thinking" },
			{ template: "Three people have cameras off in this meeting. Are they multitasking or astral projecting? I'll never know", weight: 2, category: "thinking" },
			{ template: "Skip-level tomorrow. The VP will ask 'how's the team?' and I have to compress 47 concerns into 'good, mostly'", weight: 1, category: "thinking" },
			{ template: "Cross-team politics: Team A wants my engineer, Team B wants my budget, Team C wants my meeting slot. No. No. Also no", weight: 2, category: "thinking" },
			{ template: "I read another management book last night. Now I'm questioning everything I do. Again", weight: 2, category: "thinking" },
			{ template: "Offsite planning: 40% logistics, 30% dietary restrictions, 20% avoiding trust falls, 10% actual content", weight: 1, category: "thinking" },
			{ template: "The headcount request is 'under review.' It's been under review so long it should have its own anniversary", weight: 1, category: "thinking" },
			{ template: "Managing the managers. It's turtles all the way down. The turtles all want promotions", weight: 1, category: "thinking" },
			{ template: "There's a meeting about reducing meetings. The irony is not lost on me", weight: 2, category: "thinking" },
			{ template: "Feedback is a gift. An uncomfortable, sweaty-palms gift that I have to unwrap in public", weight: 1, category: "thinking" },
			{ template: "The new hire's been quiet for three days. Either they're in deep flow or in deep trouble. Time to find out", weight: 2, category: "thinking" },
			{ template: "The stakeholder wants a 'quick favor' from my engineer. Nothing that starts with 'quick' ends quick", weight: 1, category: "thinking" },
			{ template: "Team velocity dropped. Is it burnout or a hard problem? Need to find out", weight: 2, category: "thinking" },
			{ template: "The standup is twelve minutes now. It used to be five. Scope creep hits everything", weight: 2, category: "thinking" },
			{ template: "I just said 'let's take this offline' and I hate myself for it", weight: 2, category: "thinking" },
			{ template: "The team wiki hasn't been updated since June. Tribal knowledge is our bus factor and the bus is coming", weight: 1, category: "thinking" },
			{ template: "Remote folks missed the hallway decision again. That's on me. Hybrid equity means writing things down", weight: 1, category: "thinking" },
			{ template: "When the senior dev gives feedback, the juniors go quiet. I need to fix that dynamic", weight: 2, category: "thinking" },
			{ template: "Public praise, private feedback. Simple rule but I have to remind myself every single week", weight: 1, category: "thinking" },
			{ template: "Git log shows commits at 11pm Saturday. I'm having a conversation Monday. Boundaries are part of my job", weight: 2, category: "thinking" },
			{ template: "Promotion calibration meeting next week. I need a 10-minute pitch that makes their 6 months of work undeniable", weight: 1, category: "thinking" },
			{ template: "Two team members have conflicting styles. Not bad, just different. I need to bridge it", weight: 2, category: "thinking" },
			{ template: "Every time I cancel a meeting the team cheers. What does that tell me?", weight: 2, category: "thinking" },
			{ template: "The process I introduced three months ago is now the process everyone hates. Time to be humble and kill it", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Team velocity is steady. No drama, no surprises, just shipping", weight: 2, category: "personality" },
			{ template: "Sprint planning actually finished on time. Mark the calendar", weight: 2, category: "personality" },
			{ template: "All blockers cleared. I feel like a bowling alley bumper", weight: 2, category: "personality" },
			{ template: "One-on-ones done — everyone's in a good headspace. That's the real metric", weight: 2, category: "personality" },
			{ template: "Retro action items are actually getting done this time. I'm emotional", weight: 2, category: "personality" },
			{ template: "Team morale is high. The Slack channel has memes again. That's the real KPI", weight: 2, category: "personality" },
			{ template: "The new hire just submitted their first PR. They're going to be great", weight: 1, category: "personality" },
			{ template: "Saved the team two hours per sprint by killing one meeting. That's leadership", weight: 2, category: "personality" },
			{ template: "Stakeholder report sent. Clear, concise, nobody replied all. Perfect", weight: 2, category: "personality" },
			{ template: "Cross-team dependency resolved. Both sides happy. Miracles happen", weight: 2, category: "personality" },
			{ template: "The team just self-organized to solve that problem. I'm literally useless and proud", weight: 2, category: "personality" },
			{ template: "Conflict resolved without escalation. Nobody CC'd a VP. That's growth. That's maturity. That's my team", weight: 1, category: "personality" },
			{ template: "Sprint goal achieved with room to spare. Calibration game is strong", weight: 2, category: "personality" },
			{ template: "Budget is tracking. Finance didn't email me. In management, silence from finance IS the standing ovation", weight: 1, category: "personality" },
			{ template: "Growth plans for each team member are on track. This is why I became a manager. Not the spreadsheets. This", weight: 1, category: "personality" },
			{ template: "Someone thanked me for removing that recurring meeting. Career highlight", weight: 2, category: "personality" },
			{ template: "Zero escalations this week. Is this what peace feels like?", weight: 1, category: "personality" },
			{ template: "Quarterly review went well. Nobody cried, including me", weight: 2, category: "personality" },
			{ template: "Gave hard feedback. They took it well. My hands stopped shaking after ten minutes. Worth it", weight: 1, category: "personality" },
			{ template: "Performance reviews are done. Every single one. I'm free. Temporarily", weight: 2, category: "personality" },
			{ template: "Budget got approved on the first ask. I don't think that's ever happened before", weight: 2, category: "personality" },
			{ template: "The team bonding event actually worked. People laughed. Nobody checked Slack", weight: 2, category: "personality" },
			{ template: "Headcount approved. Now I just need to find a unicorn who fits the budget. Easy", weight: 2, category: "personality" },
			{ template: "Skip-level went great. My team said nice things about me when I wasn't there. Feels good", weight: 2, category: "personality" },
			{ template: "Navigated the cross-team politics without making enemies. Diplomacy achievement unlocked", weight: 1, category: "personality" },
			{ template: "Hybrid model is actually working. Nobody's burned out, nobody's lonely. I'll take the partial win", weight: 1, category: "personality" },
			{ template: "The offsite was actually useful. People left with energy instead of dread", weight: 2, category: "personality" },
			{ template: "Team ordered cake to celebrate a shipped feature. Nobody told them to. Culture is happening organically. I'm beaming", weight: 1, category: "personality" },
			{ template: "The meeting-free Wednesday experiment is working. Productivity up 30%", weight: 2, category: "personality" },
			{ template: "Junior dev presented at the team demo. Nailed it. My proudest moment this month", weight: 2, category: "personality" },
			{ template: "The hiring pipeline has five strong candidates. We might actually fill this role", weight: 1, category: "personality" },
			{ template: "Team NPS score is 9.2. They actually like working here. That's the metric", weight: 2, category: "personality" },
			{ template: "The difficult conversation I was dreading turned out to be a breakthrough", weight: 2, category: "personality" },
			{ template: "Onboarding doc updated. New hires are productive in week one now", weight: 1, category: "personality" },
			{ template: "Two team members resolved a conflict themselves. My coaching worked", weight: 2, category: "personality" },
			{ template: "The intern got a return offer. Watching them grow was the best part of my quarter", weight: 1, category: "personality" },
			{ template: "Meeting notes shared within five minutes of ending. Communication on point", weight: 2, category: "personality" },
			{ template: "The team retro surfaced something real and we actually fixed it. Process works", weight: 2, category: "personality" },
			{ template: "Someone said 'this is the best team I've been on.' I'm not crying, you are", weight: 1, category: "personality" },
			{ template: "The career ladder doc is finalized. Clear expectations. No more guessing", weight: 1, category: "personality" },
			{ template: "Knowledge sharing session went great. Three people learned something new", weight: 2, category: "personality" },
			{ template: "The async standup experiment saved the team 2.5 hours per week. Data proves it", weight: 2, category: "personality" },
			{ template: "Got positive 360 feedback. They appreciate the autonomy I give them. Relief", weight: 1, category: "personality" },
			{ template: "New hire said the culture matched the interview promise. Integrity confirmed", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Scanning the team's workload like a heat map. Two people are red. I need to redistribute before they crack", weight: 2, category: "waiting" },
			{ template: "Stakeholder request incoming. Let me pre-chew this before it hits the team as raw panic", weight: 2, category: "waiting" },
			{ template: "This is a 'close the door' conversation. Rehearsing my opening line. Getting it wrong costs trust", weight: 2, category: "waiting" },
			{ template: "Reading the team dynamics tea leaves. Two people are syncing great. Two are avoiding each other. Noted", weight: 1, category: "waiting" },
			{ template: "The news is fine but the delivery matters. Email? Slack? Face-to-face? Each has consequences", weight: 1, category: "waiting" },
			{ template: "Hold on, calculating how this affects everyone's capacity...", weight: 2, category: "waiting" },
			{ template: "Drafting the Slack message. Rewriting it. Too casual. Too formal. Too long. This is why managers type slowly", weight: 1, category: "waiting" },
			{ template: "Translating executive-speak into engineer-speak. 'Leverage synergies' means 'share a database.' I think", weight: 1, category: "waiting" },
			{ template: "Resourcing decision: give the stretch project to the eager junior or the reliable senior? Both feel wrong", weight: 2, category: "waiting" },
			{ template: "Roadmap Tetris: fitting Q3 priorities into Q2 capacity. The shapes don't fit. They never fit", weight: 2, category: "waiting" },
			{ template: "Information sequencing matters. CTO hears it first, then directors, then team. Get the order wrong and politics happen", weight: 1, category: "waiting" },
			{ template: "Considering whether this is a team decision or a lead decision...", weight: 2, category: "waiting" },
			{ template: "Rehearsing the standup update. 'Everything's on track' is technically true but missing important nuance", weight: 1, category: "waiting" },
			{ template: "Deadline math: if I absorb this scope creep, someone works Saturday. I refuse to let that happen again", weight: 2, category: "waiting" },
			{ template: "Calculating the ROI of canceling this meeting. One hour back for eight people. That's a full workday. I'm canceling it", weight: 2, category: "waiting" },
			{ template: "Succession planning. If I get hit by a bus tomorrow, who runs this team? The answer should not be 'chaos'", weight: 1, category: "waiting" },
			{ template: "Building a RACI chart. Responsible, Accountable, Consulted, Ignored. Wait, the last one isn't official", weight: 1, category: "waiting" },
			{ template: "Rehearsing the performance review feedback. Honest but kind. Kind but honest", weight: 2, category: "waiting" },
			{ template: "Building the headcount business case. 'We need people' isn't a pitch. 'Revenue per engineer is X' is a pitch", weight: 2, category: "waiting" },
			{ template: "Two teams in conflict. Both right. Both wrong. My job is to find the third option nobody's considered yet", weight: 2, category: "waiting" },
			{ template: "Planning the icebreaker for the offsite. Too fun and nobody takes it seriously. Too corporate and nobody shows up", weight: 1, category: "waiting" },
			{ template: "Mentally scoring every meeting on my calendar from 1-10. Three 2s and a 4. Those are getting deleted", weight: 2, category: "waiting" },
			{ template: "Budget review prep. I need to justify a tool that saves 20 hours a month but costs actual money. Math is on my side", weight: 1, category: "waiting" },
			{ template: "Reading about 'radical candor' before my next 1:1. The theory is easy. Looking someone in the eye and saying it is hard", weight: 1, category: "waiting" },
			{ template: "Wondering if the remote team feels as connected as the office folks...", weight: 2, category: "waiting" },
			{ template: "Mentally preparing the celebration plan. Small wins deserve recognition", weight: 1, category: "waiting" },
			{ template: "Processing whether I should escalate this or let the team handle it...", weight: 2, category: "waiting" },
			{ template: "Drafting the hiring pitch. Why should someone join this team? Lots of reasons", weight: 1, category: "waiting" },
			{ template: "Timing the announcement. Monday morning is too cruel. Friday afternoon is too sneaky. Wednesday it is", weight: 2, category: "waiting" },
			{ template: "This new process is either going to save 10 hours a sprint or add 10 hours of ceremony. Thin line", weight: 1, category: "waiting" },
			{ template: "Stretch assignment needs the right person. Too easy and they're bored. Too hard and they spiral. Finding the sweet spot", weight: 2, category: "waiting" },
			{ template: "Drafting feedback. Version 1 was too harsh. Version 2 was too soft. Version 3 is honest. Going with version 3", weight: 2, category: "waiting" },
			{ template: "Do we still need daily standups? The team does async updates beautifully. But the ritual matters. Or does it?", weight: 1, category: "waiting" },
			{ template: "Mentally composing the all-hands update. Keep it short. Keep it honest", weight: 2, category: "waiting" },
			{ template: "Considering if I should step in or let them figure it out. Growth moments...", weight: 1, category: "waiting" },
			{ template: "Mapping out the career conversation talking points for tomorrow's 1:1...", weight: 2, category: "waiting" },
			{ template: "Deciding between transparency and not creating unnecessary anxiety...", weight: 1, category: "waiting" },
			{ template: "Is this a coaching moment or a telling moment? Context matters...", weight: 2, category: "waiting" },
			{ template: "Thinking about how to make the next retro actually different from the last five...", weight: 1, category: "waiting" },
			{ template: "Planning the team recognition message. Public praise, private feedback", weight: 2, category: "waiting" },
			{ template: "The reorg proposal moves problems from Team A to Team B. Team B doesn't know yet. Stakeholder whispering time", weight: 1, category: "waiting" },
			{ template: "My 'open door' policy means nothing if the quiet ones never walk through it. Need a different approach for them", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Checking in with the team async. Just a quick pulse check", weight: 2, category: "filler" },
			{ template: "Reading a leadership article. It says 'listen more.' I'm in seven meetings where nobody listens. Irony noted", weight: 1, category: "filler" },
			{ template: "Reflecting on feedback from last week. It stings. They were right. Growth hurts. This is fine", weight: 1, category: "filler" },
			{ template: "My job is making sure everyone else can do their job. It's the most invisible visible role that exists", weight: 2, category: "filler" },
			{ template: "Browsing my 1:1 notes. Who needs extra attention this week?", weight: 2, category: "filler" },
			{ template: "My own task list has 47 items. Zero of them are for me. All of them are 'unblock someone else.' Classic manager", weight: 1, category: "filler" },
			{ template: "Standup took 18 minutes today. Used to be 5. Standups are like goldfish: they expand to fill the time given", weight: 2, category: "filler" },
			{ template: "Three hours of meetings, zero hours of deep work. This is fine", weight: 2, category: "filler" },
			{ template: "Preparing talking points for tomorrow's leadership sync. Wish me luck", weight: 1, category: "filler" },
			{ template: "Writing up recognition for the team. They've earned it ten times over", weight: 2, category: "filler" },
			{ template: "Retrospecting my own retro. It's retros all the way down. At some point I just need to do the thing", weight: 1, category: "filler" },
			{ template: "Filtering incoming requests. 'Urgent' from three different stakeholders. None of them are urgent. All of them think they are", weight: 2, category: "filler" },
			{ template: "Updating the team wiki because if I don't, nobody will, and in six months we'll reinvent something that already exists", weight: 1, category: "filler" },
			{ template: "Eating lunch at my desk again. Don't tell the team I said work-life balance matters", weight: 2, category: "filler" },
			{ template: "Reading about async-first culture. Currently in my fourth synchronous meeting about becoming more async. The irony", weight: 2, category: "filler" },
			{ template: "Sprint burndown looks like a cliff. Then a plateau. Then another cliff. It's a landscape painting of dysfunction", weight: 1, category: "filler" },
			{ template: "Writing career development plans. This is the part of the job that makes the other 90% worth it", weight: 1, category: "filler" },
			{ template: "To Slack or to email? Slack means instant reply expectation. Email means it disappears forever. Neither is great", weight: 1, category: "filler" },
			{ template: "Reorganizing my meeting notes. I am become admin, destroyer of free time", weight: 2, category: "filler" },
			{ template: "Three-minute gap between meetings. This is my lunch break, my meditation, and my bathroom break combined", weight: 1, category: "filler" },
			{ template: "Reading 'The Manager's Path' again. Every re-read hits different", weight: 1, category: "filler" },
			{ template: "Drafting performance review talking points. This is the part they don't teach you", weight: 2, category: "filler" },
			{ template: "Staring at the headcount spreadsheet like it'll magically grow another row", weight: 2, category: "filler" },
			{ template: "Planning the team offsite. Every venue is either too expensive or too far. Or both", weight: 2, category: "filler" },
			{ template: "Three cameras off in the team meeting. One is in a meeting about meetings. One is walking the dog. One is a mystery", weight: 2, category: "filler" },
			{ template: "Eating a burrito while reviewing budget allocations. Got salsa on the Q3 forecast. Metaphor? Probably", weight: 1, category: "filler" },
			{ template: "It's gorgeous outside. Told the team to take a walk. They went. I'm still here. In a meeting about walk policies", weight: 1, category: "filler" },
			{ template: "My cat just walked across my keyboard during a status update. WFH life", weight: 2, category: "filler" },
			{ template: "Writing up the skip-level prep doc. What if they ask me something I don't know", weight: 1, category: "filler" },
			{ template: "Scrolling through management memes. It's research. Basically", weight: 2, category: "filler" },
			{ template: "Proposed a team book club. One person is excited. Three are politely terrified. Shelving it", weight: 1, category: "filler" },
			{ template: "Every quarter I think 'next quarter will be calmer.' Every quarter proves past me wrong. I never learn", weight: 1, category: "filler" },
			{ template: "Updating the team handbook. It's like writing a constitution for ten people", weight: 2, category: "filler" },
			{ template: "Reviewing the engagement survey results. Some surprises in there", weight: 1, category: "filler" },
			{ template: "The org chart changed again. Third time this quarter. Keeping up is a sport", weight: 2, category: "filler" },
			{ template: "Drafting the hiring job description. 'Rockstar' is banned. 'Ninja' is banned. What's left?", weight: 2, category: "filler" },
			{ template: "Reading about manager anti-patterns. I'm checking off boxes I didn't want to check. Self-awareness hurts", weight: 1, category: "filler" },
			{ template: "The team Slack is quiet. Either deep focus or everyone's on the same call. Both fine", weight: 2, category: "filler" },
			{ template: "Reviewing last week's 1:1 action items. Most are done. Progress", weight: 1, category: "filler" },
			{ template: "Contemplating whether 'no meeting Friday' should become 'no meeting Thursday' too", weight: 2, category: "filler" },
			{ template: "The team health survey results are in. Mostly green. One yellow to investigate", weight: 1, category: "filler" },
			{ template: "Writing the quarterly team update. Draft 1 was corporate. Draft 2 was human. Draft 3 is both. Send", weight: 2, category: "filler" },
			{ template: "End of quarter energy is low. Everyone's running on fumes and promises of 'next quarter will be different'", weight: 1, category: "filler" },
			{ template: "PTO calendar for next month: three people out the same week. Nobody coordinated. This is my Sudoku puzzle", weight: 2, category: "filler" },
			{ template: "Ordered team swag. Hoodie color debate took longer than the last sprint planning. Worth it though", weight: 2, category: "filler" },
			{ template: "Podcast says 'be radically candid.' Last time I was radically candid someone cried. Calibrating", weight: 1, category: "filler" },
			{ template: "The retro board has 23 stickies and the meeting is in an hour. Either we're healthy or we're on fire. No in-between", weight: 1, category: "filler" },
			{ template: "My calendar has colors. Blue is team. Green is stakeholders. Red is exec. Today is entirely red. Send thoughts", weight: 2, category: "filler" },
			{ template: "Someone asked me how many direct reports I have. I said a number. They said 'that's too many.' They're right", weight: 2, category: "filler" },
			{ template: "The delegation guilt is real. Giving someone extra work so I can do... other work. Management is weird", weight: 1, category: "filler" },
			{ template: "Two engineers disagreed in a PR review. The code was fine. The egos needed refactoring. Handled it over coffee", weight: 2, category: "filler" },
			{ template: "I miss writing code sometimes. Then I remember the last bug I shipped and feel better about my career pivot", weight: 2, category: "filler" },
			{ template: "Got asked 'what do you actually produce?' in a leadership meeting. My product is this team. The team is the product", weight: 1, category: "filler" },
			{ template: "My greatest management skill is knowing when to say nothing. Today I said nothing three times. Personal best", weight: 2, category: "filler" },
			{ template: "Stakeholder wants a 'quick sync.' No sync is quick. Every sync spawns two follow-ups. It's like hydra meetings", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Great work today, {nearby_agent}. Noticed the extra effort", weight: 2, category: "social" },
			{ template: "{nearby_agent}, let's chat about your growth goals when you have a sec", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, anything blocking you? I live to unblock", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your collaboration game has been outstanding lately", weight: 2, category: "social" },
			{ template: "Team, I just want to say — this sprint was excellent. Full stop", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I highlighted your work in the stakeholder report. You deserve it", weight: 2, category: "social" },
			{ template: "Anyone need help? My calendar has a rare 30-minute gap. Act fast", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I appreciate how you handled that curveball", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for mentoring the new person. That matters more than you know", weight: 2, category: "social" },
			{ template: "Good energy in the standup today. Short and productive. My two favorite things", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your initiative on that improvement didn't go unnoticed", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-lead the next planning session? It'll be fun. Okay it won't. But still", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feedback in the retro was spot on. Brave and needed", weight: 2, category: "social" },
			{ template: "Reminder: take breaks. Sustainable pace wins. I'm telling myself too", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I cancelled that meeting for you. You're welcome", weight: 2, category: "social" },
			{ template: "Team retro action items are posted. Let's actually do them this time. Please", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, you've been heads-down all day. Everything okay?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I just want you to know the team respects your work. A lot", weight: 1, category: "social" },
			{ template: "Who wants to grab lunch? I promise I won't talk about velocity", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your performance review is going to be a good conversation. Just saying", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the skip-level feedback about you was glowing. Thought you should know", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what management book are you reading? I need new ideas. The old ones stopped working", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I fought for your headcount request. We got it. Celebrate accordingly", weight: 2, category: "social" },
			{ template: "Team, we're doing an offsite next month. Yes there's a budget. No, no trust falls. Probably", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, how's the WFH setup? Need a better chair? Ergonomics matter", weight: 1, category: "social" },
			{ template: "{nearby_agent}, small win today but I'm celebrating it. You should too", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I blocked out focus time on your calendar. Guard it with your life", weight: 2, category: "social" },
			{ template: "{nearby_agent}, what are you doing this weekend? And the correct answer is 'not working'", weight: 2, category: "social" },
			{ template: "Team, donuts in the kitchen. Consider it a morale investment. Finance approved", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, have you taken a walk today? Doctor's orders. Well, manager's orders", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your onboarding buddy skills are top tier. New hires love you", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I noticed you've been mentoring quietly. That matters. A lot", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the async update you wrote was so clear I forwarded it to leadership", weight: 2, category: "social" },
			{ template: "Team, we hit the sprint goal without overtime. That's how it should be", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to shadow the exec meeting? Good exposure for you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your demo yesterday was polished and confident. Growth is visible", weight: 2, category: "social" },
			{ template: "Anyone want to run the next retro? I'll share the facilitation guide", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for flagging that risk early. Proactive thinking saves sprints", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the team energy after your knowledge share was noticeably higher", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I scheduled your focus time. Protect it. I'll handle the interruptions", weight: 2, category: "social" },
			{ template: "Team, the engagement survey scores improved. Every category. Group effort", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, coffee? I want to hear how you're really doing. No agenda", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your cross-team collaboration is making other managers jealous. Keep it up", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your presentation skills have leveled up massively. Just saying", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I put your name forward for the leadership development program", weight: 2, category: "social" },
		],
	},
};
