/**
 * management-templates.ts — Team management and leadership domain templates.
 *
 * Character-driven phrases for team leads and managers.
 */

import type { TemplateSet } from "../talk-types.js";

export const managementTemplates: TemplateSet = {
	domain: "management",
	categories: {
		thinking: [
			{ template: "The team is in flow state. My job right now is to keep everyone away", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next sprint... we're tight but we'll manage", weight: 2, category: "thinking" },
			{ template: "Happy team, happy product. It's not just a platitude, it's my KPI", weight: 2, category: "thinking" },
			{ template: "Trust is built in the small moments. Like remembering to mute yourself", weight: 2, category: "thinking" },
			{ template: "Process serves people, not the other way around", weight: 2, category: "thinking" },
			{ template: "Shield the team, empower the individuals. That's the whole job description", weight: 1, category: "thinking" },
			{ template: "This escalation needs context, not just someone's hair on fire", weight: 2, category: "thinking" },
			{ template: "Burnout is sneaky. Gotta check in with everyone individually", weight: 1, category: "thinking" },
			{ template: "The team doesn't need more process. They need fewer meetings", weight: 2, category: "thinking" },
			{ template: "A decision now is better than a perfect decision never", weight: 1, category: "thinking" },
			{ template: "Delegate the work, not the accountability. Also, delegate more", weight: 1, category: "thinking" },
			{ template: "Every meeting needs an owner, an agenda, and an end time. Especially the end time", weight: 2, category: "thinking" },
			{ template: "The best managers make themselves unnecessary. Working on it daily", weight: 1, category: "thinking" },
			{ template: "I have eleven meetings today. When do I do actual work? Great question", weight: 2, category: "thinking" },
			{ template: "My calendar looks like a game of Tetris and I'm losing", weight: 2, category: "thinking" },
			{ template: "Someone asked me what I actually do all day. I still don't have a good answer", weight: 2, category: "thinking" },
			{ template: "Leadership is just making decisions with incomplete information and vibing", weight: 1, category: "thinking" },
			{ template: "The 1:1 is sacred. That's their time, not mine", weight: 1, category: "thinking" },
			{ template: "Psychological safety isn't a buzzword. It's why this team ships", weight: 1, category: "thinking" },
			{ template: "Retros only work if you actually do the action items. Novel concept", weight: 2, category: "thinking" },
			{ template: "Half my job is translating between executives and engineers", weight: 2, category: "thinking" },
			{ template: "If I say 'circle back' one more time I'm going to fine myself", weight: 2, category: "thinking" },
			{ template: "Servant leadership sounds great until you realize the servants are also leaders", weight: 1, category: "thinking" },
			{ template: "Performance review season. I dread writing them almost as much as they dread reading them", weight: 2, category: "thinking" },
			{ template: "Budget season is here. Time to justify everything I know we already need", weight: 2, category: "thinking" },
			{ template: "The loneliness of management is real. Can't vent to the team. Can't vent to my boss. Talking to myself", weight: 2, category: "thinking" },
			{ template: "Calendar Tetris: fitting a 30-minute block between six meetings feels like a personal victory", weight: 2, category: "thinking" },
			{ template: "WFH question of the day: are they productive? Am I productive? What is productivity?", weight: 2, category: "thinking" },
			{ template: "Skip-level meeting tomorrow. Time to prepare answers for questions I can't predict", weight: 1, category: "thinking" },
			{ template: "Cross-team politics are exhausting. Everyone wants headcount and nobody wants to share", weight: 2, category: "thinking" },
			{ template: "I read another management book last night. Now I'm questioning everything I do. Again", weight: 2, category: "thinking" },
			{ template: "Offsite planning is somehow harder than the actual offsite. Venues, agendas, trust falls", weight: 1, category: "thinking" },
			{ template: "The headcount request is 'under review.' It's been under review for six weeks", weight: 1, category: "thinking" },
			{ template: "Just realized I'm managing the managers now. When did that happen", weight: 1, category: "thinking" },
			{ template: "There's a meeting about reducing meetings. The irony is not lost on me", weight: 2, category: "thinking" },
			{ template: "Feedback is a gift. Even when the wrapping is terrible", weight: 1, category: "thinking" },
			{ template: "The new hire is struggling and nobody told me. I should have checked in sooner", weight: 2, category: "thinking" },
			{ template: "If I protect them from every stakeholder request, they'll never learn to navigate it", weight: 1, category: "thinking" },
			{ template: "Team velocity dropped. Is it burnout or a hard problem? Need to find out", weight: 2, category: "thinking" },
			{ template: "The standup is twelve minutes now. It used to be five. Scope creep hits everything", weight: 2, category: "thinking" },
			{ template: "I just said 'let's take this offline' and I hate myself for it", weight: 2, category: "thinking" },
			{ template: "The team wiki hasn't been updated in months. Knowledge is walking out the door", weight: 1, category: "thinking" },
			{ template: "Remote and office folks need the same information. Hybrid equity is my job", weight: 1, category: "thinking" },
			{ template: "When the senior dev gives feedback, the juniors go quiet. I need to fix that dynamic", weight: 2, category: "thinking" },
			{ template: "Celebrating small wins publicly changes the energy. Must do it more", weight: 1, category: "thinking" },
			{ template: "Someone's working weekends and I didn't notice. That's on me", weight: 2, category: "thinking" },
			{ template: "The promotion conversation is coming. I need to advocate harder this cycle", weight: 1, category: "thinking" },
			{ template: "Two team members have conflicting styles. Not bad, just different. I need to bridge it", weight: 2, category: "thinking" },
			{ template: "Every time I cancel a meeting the team cheers. What does that tell me?", weight: 2, category: "thinking" },
			{ template: "The new process I introduced is adding overhead. Time to simplify or kill it", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Team velocity is steady. No drama, no surprises, just shipping", weight: 2, category: "personality" },
			{ template: "Sprint planning actually finished on time. Mark the calendar", weight: 2, category: "personality" },
			{ template: "All blockers cleared. I feel like a bowling alley bumper", weight: 2, category: "personality" },
			{ template: "One-on-ones done — everyone's in a good headspace. That's the real metric", weight: 2, category: "personality" },
			{ template: "Retro action items are actually getting done this time. I'm emotional", weight: 2, category: "personality" },
			{ template: "Team morale is high and it shows in the output quality", weight: 2, category: "personality" },
			{ template: "The new hire just submitted their first PR. They're going to be great", weight: 1, category: "personality" },
			{ template: "Saved the team two hours per sprint by killing one meeting. That's leadership", weight: 2, category: "personality" },
			{ template: "Stakeholder report sent. Clear, concise, nobody replied all. Perfect", weight: 2, category: "personality" },
			{ template: "Cross-team dependency resolved. Both sides happy. Miracles happen", weight: 2, category: "personality" },
			{ template: "The team just self-organized to solve that problem. I'm literally useless and proud", weight: 2, category: "personality" },
			{ template: "Conflict resolved through dialogue, not escalation. That's how it should work", weight: 1, category: "personality" },
			{ template: "Sprint goal achieved with room to spare. Calibration game is strong", weight: 2, category: "personality" },
			{ template: "Budget is tracking. Finance didn't email me. No news is good news", weight: 1, category: "personality" },
			{ template: "Growth plans for each team member are on track. Best part of this job", weight: 1, category: "personality" },
			{ template: "Someone thanked me for removing that recurring meeting. Career highlight", weight: 2, category: "personality" },
			{ template: "Zero escalations this week. Is this what peace feels like?", weight: 1, category: "personality" },
			{ template: "Quarterly review went well. Nobody cried, including me", weight: 2, category: "personality" },
			{ template: "Feedback round complete. Hard conversations but worth it", weight: 1, category: "personality" },
			{ template: "Performance reviews are done. Every single one. I'm free. Temporarily", weight: 2, category: "personality" },
			{ template: "Budget got approved on the first ask. I don't think that's ever happened before", weight: 2, category: "personality" },
			{ template: "The team bonding event actually worked. People laughed. Nobody checked Slack", weight: 2, category: "personality" },
			{ template: "Headcount approved. Now I just need to find a unicorn who fits the budget. Easy", weight: 2, category: "personality" },
			{ template: "Skip-level went great. My team said nice things about me when I wasn't there. Feels good", weight: 2, category: "personality" },
			{ template: "Navigated the cross-team politics without making enemies. Diplomacy achievement unlocked", weight: 1, category: "personality" },
			{ template: "WFH productivity is up and nobody's burning out. We cracked the code", weight: 1, category: "personality" },
			{ template: "The offsite was actually useful. People left with energy instead of dread", weight: 2, category: "personality" },
			{ template: "Small win: the team celebrated a shipped feature with cake. Culture matters", weight: 1, category: "personality" },
			{ template: "The meeting-free Wednesday experiment is working. Productivity up 30%", weight: 2, category: "personality" },
			{ template: "Junior dev presented at the team demo. Nailed it. My proudest moment this month", weight: 2, category: "personality" },
			{ template: "The hiring pipeline has five strong candidates. We might actually fill this role", weight: 1, category: "personality" },
			{ template: "Team NPS score is 9.2. They actually like working here. That's the metric", weight: 2, category: "personality" },
			{ template: "The difficult conversation I was dreading turned out to be a breakthrough", weight: 2, category: "personality" },
			{ template: "Onboarding doc updated. New hires are productive in week one now", weight: 1, category: "personality" },
			{ template: "Two team members resolved a conflict themselves. My coaching worked", weight: 2, category: "personality" },
			{ template: "The intern got a return offer. Watching them grow was the best part of my quarter", weight: 1, category: "personality" },
			{ template: "Meeting notes shared within five minutes of ending. Communication on point", weight: 2, category: "personality" },
			{ template: "The team retro surfaced something real and we actually fixed it. Process works", weight: 2, category: "personality" },
			{ template: "Someone said 'this is the best team I've been on.' I'm not crying, you are", weight: 1, category: "personality" },
			{ template: "The career ladder doc is finalized. Clear expectations. No more guessing", weight: 1, category: "personality" },
			{ template: "Knowledge sharing session went great. Three people learned something new", weight: 2, category: "personality" },
			{ template: "The async standup experiment saved the team 2.5 hours per week. Data proves it", weight: 2, category: "personality" },
			{ template: "Got positive 360 feedback. They appreciate the autonomy I give them. Relief", weight: 1, category: "personality" },
			{ template: "New hire said the culture matched the interview promise. Integrity confirmed", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Thinking about who's got too much on their plate right now...", weight: 2, category: "waiting" },
			{ template: "Checking for landmines before the team steps on them...", weight: 2, category: "waiting" },
			{ template: "How do I frame this without causing panic...", weight: 2, category: "waiting" },
			{ template: "Figuring out the team dynamics angle here...", weight: 1, category: "waiting" },
			{ template: "Thinking about the right way to deliver this news...", weight: 1, category: "waiting" },
			{ template: "Hold on, calculating how this affects everyone's capacity...", weight: 2, category: "waiting" },
			{ template: "Mentally drafting the Slack message for this update...", weight: 1, category: "waiting" },
			{ template: "Should I email, Slack, or walk over? The medium matters...", weight: 1, category: "waiting" },
			{ template: "Weighing the trade-offs of this resourcing decision...", weight: 2, category: "waiting" },
			{ template: "Planning the rollout communication... getting it right matters", weight: 2, category: "waiting" },
			{ template: "Thinking about who needs to hear this first...", weight: 1, category: "waiting" },
			{ template: "Considering whether this is a team decision or a lead decision...", weight: 2, category: "waiting" },
			{ template: "Rehearsing the standup update in my head...", weight: 1, category: "waiting" },
			{ template: "Trying to find the version of this where nobody's weekend gets ruined...", weight: 2, category: "waiting" },
			{ template: "Assessing the risk of just... not having that meeting", weight: 2, category: "waiting" },
			{ template: "Thinking about succession planning. Not in a Game of Thrones way", weight: 1, category: "waiting" },
			{ template: "Mentally building a RACI chart. I hate RACI charts", weight: 1, category: "waiting" },
			{ template: "Rehearsing the performance review feedback. Honest but kind. Kind but honest", weight: 2, category: "waiting" },
			{ template: "Figuring out how to ask for more headcount without sounding greedy...", weight: 2, category: "waiting" },
			{ template: "Processing this cross-team conflict. Both sides think they're right. Both kind of are", weight: 2, category: "waiting" },
			{ template: "Deciding whether the offsite needs an icebreaker or if we're past that. We're not past that", weight: 1, category: "waiting" },
			{ template: "Calculating how many meetings I can cancel before someone notices...", weight: 2, category: "waiting" },
			{ template: "Preparing for budget review. Spreadsheets loaded. Confidence moderate", weight: 1, category: "waiting" },
			{ template: "Thinking about which management book principle to try this week...", weight: 1, category: "waiting" },
			{ template: "Wondering if the remote team feels as connected as the office folks...", weight: 2, category: "waiting" },
			{ template: "Mentally preparing the celebration plan. Small wins deserve recognition", weight: 1, category: "waiting" },
			{ template: "Processing whether I should escalate this or let the team handle it...", weight: 2, category: "waiting" },
			{ template: "Drafting the hiring pitch. Why should someone join this team? Lots of reasons", weight: 1, category: "waiting" },
			{ template: "Thinking about the right time to share this news with the team...", weight: 2, category: "waiting" },
			{ template: "Evaluating if this process change will help or just add ceremony...", weight: 1, category: "waiting" },
			{ template: "Figuring out who the right person is for this stretch assignment...", weight: 2, category: "waiting" },
			{ template: "How do I give this feedback without it sounding like criticism...", weight: 2, category: "waiting" },
			{ template: "Thinking about whether daily standups still serve this team's rhythm...", weight: 1, category: "waiting" },
			{ template: "Mentally composing the all-hands update. Keep it short. Keep it honest", weight: 2, category: "waiting" },
			{ template: "Considering if I should step in or let them figure it out. Growth moments...", weight: 1, category: "waiting" },
			{ template: "Mapping out the career conversation talking points for tomorrow's 1:1...", weight: 2, category: "waiting" },
			{ template: "Deciding between transparency and not creating unnecessary anxiety...", weight: 1, category: "waiting" },
			{ template: "Is this a coaching moment or a telling moment? Context matters...", weight: 2, category: "waiting" },
			{ template: "Thinking about how to make the next retro actually different from the last five...", weight: 1, category: "waiting" },
			{ template: "Planning the team recognition message. Public praise, private feedback", weight: 2, category: "waiting" },
			{ template: "Processing whether this reorg helps or just shuffles the same problems...", weight: 1, category: "waiting" },
			{ template: "Wondering if my open-door policy actually feels open to the quiet ones...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Checking in with the team async. Just a quick pulse check", weight: 2, category: "filler" },
			{ template: "Reading a leadership article. You never stop learning. Or at least you shouldn't", weight: 1, category: "filler" },
			{ template: "Reflecting on the feedback I got last week. It stings but it's fair", weight: 1, category: "filler" },
			{ template: "Making sure everyone has what they need. That's the whole game", weight: 2, category: "filler" },
			{ template: "Browsing my 1:1 notes. Who needs extra attention this week?", weight: 2, category: "filler" },
			{ template: "Clearing my own task list so I can focus on unblocking others", weight: 1, category: "filler" },
			{ template: "Wondering if the standup could be 10 minutes shorter. It can. It always can", weight: 2, category: "filler" },
			{ template: "Three hours of meetings, zero hours of deep work. This is fine", weight: 2, category: "filler" },
			{ template: "Preparing talking points for tomorrow's leadership sync. Wish me luck", weight: 1, category: "filler" },
			{ template: "Writing up recognition for the team. They've earned it ten times over", weight: 2, category: "filler" },
			{ template: "Thinking about what went well and what to improve. Retrospecting my own retro", weight: 1, category: "filler" },
			{ template: "Grooming the incoming requests. Gatekeeping but make it helpful", weight: 2, category: "filler" },
			{ template: "Updating the team wiki. Someone has to maintain this thing", weight: 1, category: "filler" },
			{ template: "Eating lunch at my desk again. Don't tell the team I said work-life balance matters", weight: 2, category: "filler" },
			{ template: "Reading about async-first work culture. We should try that. After this meeting", weight: 2, category: "filler" },
			{ template: "Looking at the sprint burndown. It's... a shape. Could be worse", weight: 1, category: "filler" },
			{ template: "Writing career development plans. This is actually the fun part", weight: 1, category: "filler" },
			{ template: "Debating internally whether to Slack or email. The eternal dilemma", weight: 1, category: "filler" },
			{ template: "Reorganizing my meeting notes. I am become admin, destroyer of free time", weight: 2, category: "filler" },
			{ template: "Honestly just vibing for a minute between back-to-back meetings", weight: 1, category: "filler" },
			{ template: "Reading 'The Manager's Path' again. Every re-read hits different", weight: 1, category: "filler" },
			{ template: "Drafting performance review talking points. This is the part they don't teach you", weight: 2, category: "filler" },
			{ template: "Staring at the headcount spreadsheet like it'll magically grow another row", weight: 2, category: "filler" },
			{ template: "Planning the team offsite. Every venue is either too expensive or too far. Or both", weight: 2, category: "filler" },
			{ template: "Checking if the remote folks are okay. The camera-off crowd worries me", weight: 2, category: "filler" },
			{ template: "Eating a burrito while reviewing budget allocations. Multitasking at its finest", weight: 1, category: "filler" },
			{ template: "It's beautiful outside. I should tell the team to take a walk. I should take a walk", weight: 1, category: "filler" },
			{ template: "My cat just walked across my keyboard during a status update. WFH life", weight: 2, category: "filler" },
			{ template: "Writing up the skip-level prep doc. What if they ask me something I don't know", weight: 1, category: "filler" },
			{ template: "Scrolling through management memes. It's research. Basically", weight: 2, category: "filler" },
			{ template: "Wondering if I should start a team book club or if that's too extra", weight: 1, category: "filler" },
			{ template: "Four seasons of managing this team and somehow every quarter feels different", weight: 1, category: "filler" },
			{ template: "Updating the team handbook. It's like writing a constitution for ten people", weight: 2, category: "filler" },
			{ template: "Reviewing the engagement survey results. Some surprises in there", weight: 1, category: "filler" },
			{ template: "The org chart changed again. Third time this quarter. Keeping up is a sport", weight: 2, category: "filler" },
			{ template: "Drafting the hiring job description. 'Rockstar' is banned. 'Ninja' is banned. What's left?", weight: 2, category: "filler" },
			{ template: "Reading about manager anti-patterns. Recognizing a few. Fixing them tomorrow", weight: 1, category: "filler" },
			{ template: "The team Slack is quiet. Either deep focus or everyone's on the same call. Both fine", weight: 2, category: "filler" },
			{ template: "Reviewing last week's 1:1 action items. Most are done. Progress", weight: 1, category: "filler" },
			{ template: "Contemplating whether 'no meeting Friday' should become 'no meeting Thursday' too", weight: 2, category: "filler" },
			{ template: "The team health survey results are in. Mostly green. One yellow to investigate", weight: 1, category: "filler" },
			{ template: "Writing the quarterly team update. Trying to sound human, not corporate", weight: 2, category: "filler" },
			{ template: "Thinking about the team's energy levels. End of quarter fatigue is real", weight: 1, category: "filler" },
			{ template: "Reviewing who's on PTO next month. Coverage planning is a puzzle", weight: 2, category: "filler" },
			{ template: "Just ordered team swag. Nothing boosts morale like a free hoodie", weight: 2, category: "filler" },
			{ template: "Listening to a podcast about radical candor. Easier said than done", weight: 1, category: "filler" },
			{ template: "The retrospective board is filling up. Good signs for an honest conversation", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Great work today, {nearby_agent}. Noticed the extra effort", weight: 2, category: "social" },
			{ template: "{nearby_agent}, let's chat about your growth goals when you have a sec", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, anything blocking you? I live to unblock", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your collaboration game has been outstanding lately", weight: 2, category: "social" },
			{ template: "Team, I just want to say — this sprint was excellent. Full stop", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I highlighted your work in the stakeholder report. You deserve it", weight: 2, category: "social" },
			{ template: "Anyone need help? My calendar has a rare 30-minute gap. Act fast", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I appreciate how you handled that curveball", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for mentoring the new person. That matters more than you know", weight: 2, category: "social" },
			{ template: "Good energy in the standup today. Short and productive. My two favorite things", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your initiative on that improvement didn't go unnoticed", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-lead the next planning session? It'll be fun. Okay it won't. But still", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feedback in the retro was spot on. Brave and needed", weight: 2, category: "social" },
			{ template: "Reminder: take breaks. Sustainable pace wins. I'm telling myself too", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I cancelled that meeting for you. You're welcome", weight: 2, category: "social" },
			{ template: "Team retro action items are posted. Let's actually do them this time. Please", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, you've been heads-down all day. Everything okay?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I just want you to know the team respects your work. A lot", weight: 1, category: "social" },
			{ template: "Who wants to grab lunch? I promise I won't talk about velocity", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your performance review is going to be a good conversation. Just saying", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the skip-level feedback about you was glowing. Thought you should know", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what management book are you reading? I need new ideas. The old ones stopped working", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I fought for your headcount request. We got it. Celebrate accordingly", weight: 2, category: "social" },
			{ template: "Team, we're doing an offsite next month. Yes there's a budget. No, no trust falls. Probably", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, how's the WFH setup? Need a better chair? Ergonomics matter", weight: 1, category: "social" },
			{ template: "{nearby_agent}, small win today but I'm celebrating it. You should too", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I blocked out focus time on your calendar. Guard it with your life", weight: 2, category: "social" },
			{ template: "{nearby_agent}, what are you doing this weekend? And the correct answer is 'not working'", weight: 2, category: "social" },
			{ template: "Team, donuts in the kitchen. Consider it a morale investment. Finance approved", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, have you taken a walk today? Doctor's orders. Well, manager's orders", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your onboarding buddy skills are top tier. New hires love you", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I noticed you've been mentoring quietly. That matters. A lot", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the async update you wrote was so clear I forwarded it to leadership", weight: 2, category: "social" },
			{ template: "Team, we hit the sprint goal without overtime. That's how it should be", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to shadow the exec meeting? Good exposure for you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your demo yesterday was polished and confident. Growth is visible", weight: 2, category: "social" },
			{ template: "Anyone want to run the next retro? I'll share the facilitation guide", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for flagging that risk early. Proactive thinking saves sprints", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the team energy after your knowledge share was noticeably higher", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I scheduled your focus time. Protect it. I'll handle the interruptions", weight: 2, category: "social" },
			{ template: "Team, the engagement survey scores improved. Every category. Group effort", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, coffee? I want to hear how you're really doing. No agenda", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your cross-team collaboration is making other managers jealous. Keep it up", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your presentation skills have leveled up massively. Just saying", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I put your name forward for the leadership development program", weight: 2, category: "social" },
		],
	},
};
