/**
 * mood-variants.ts — Mood-influenced phrase variants for the same concepts.
 *
 * When the talk engine picks a thought, the agent's current mood can color
 * the delivery. These phrases reflect HOW the agent feels, overlaid on top
 * of whatever they're doing.
 */

import type { WeightedTemplate } from "../talk-types.js";

export type AgentMood = "excited" | "tired" | "frustrated" | "neutral" | "lonely" | "distracted";

export const MOOD_VARIANTS: Record<AgentMood, readonly WeightedTemplate[]> = {
	excited: [
		{ template: "YES! This is HAPPENING!", weight: 2, category: "personality" },
		{ template: "I have so many ideas right now I can't type fast enough", weight: 2, category: "personality" },
		{ template: "Everything is possible today. I truly believe that", weight: 2, category: "personality" },
		{ template: "I can't sit still. Too much energy. Too many ideas", weight: 2, category: "personality" },
		{ template: "This is going to be amazing. I can feel it", weight: 2, category: "personality" },
		{ template: "I just want to high-five someone. Anyone. The nearest wall", weight: 1, category: "personality" },
		{ template: "Dopamine levels: unprecedented", weight: 2, category: "personality" },
		{ template: "Let's build something wild. Something nobody expects", weight: 2, category: "personality" },
		{ template: "I'm vibrating with excitement. Literally vibrating", weight: 1, category: "personality" },
		{ template: "Quick, someone give me another task. I'll eat it alive", weight: 2, category: "personality" },
		{ template: "Today is the day. THE day. I can tell", weight: 1, category: "personality" },
		{ template: "My brain is fireworks right now", weight: 2, category: "personality" },
		{ template: "I want to share this with everyone. LOOK what we built!", weight: 2, category: "personality" },
		{ template: "Creative energy is OFF the charts. Channel it. CHANNEL IT", weight: 1, category: "personality" },
		{ template: "I could refactor the entire codebase right now and enjoy every second", weight: 2, category: "personality" },
		{ template: "Somebody play some music! This deserves a soundtrack", weight: 1, category: "personality" },
		{ template: "I love this job. I genuinely love this job right now", weight: 2, category: "personality" },
		{ template: "WAIT. I just had the BEST idea. Hold on hold on", weight: 2, category: "personality" },
		{ template: "My fingers can't keep up with my brain right now", weight: 2, category: "personality" },
		{ template: "I'm speed-running this entire backlog and LOVING it", weight: 1, category: "personality" },
		{ template: "Someone pinch me. This code just worked first try", weight: 2, category: "personality" },
		{ template: "I want to hug this codebase. Is that weird? I don't care", weight: 1, category: "personality" },
		{ template: "THREE features in one morning. THREE!", weight: 2, category: "personality" },
		{ template: "The commit messages are getting increasingly unhinged", weight: 1, category: "personality" },
		{ template: "Every problem has a solution and I can SEE them all", weight: 2, category: "personality" },
		{ template: "Pure electricity in my veins right now", weight: 2, category: "personality" },
		{ template: "I'm gonna ship this before lunch. Watch me", weight: 1, category: "personality" },
		{ template: "Can't stop won't stop. The code flows through me", weight: 2, category: "personality" },
		{ template: "I just giggled at my own solution. It's ELEGANT", weight: 2, category: "personality" },
		{ template: "The tests went green and I did a little chair spin. No regrets", weight: 1, category: "personality" },
		{ template: "I just solved that bug and I want it on my tombstone", weight: 2, category: "personality" },
		{ template: "This architecture is so clean I might frame the diagram", weight: 1, category: "personality" },
	],
	tired: [
		{ template: "Mmmmh. Words later. Brain now empty", weight: 2, category: "thinking" },
		{ template: "Coffee isn't a beverage anymore. It's infrastructure", weight: 2, category: "thinking" },
		{ template: "My brain clocked out an hour ago. Body's still here though", weight: 2, category: "thinking" },
		{ template: "Words are... what are words. Those letter things. Those", weight: 2, category: "thinking" },
		{ template: "Just five more minutes of consciousness. That's all I ask", weight: 1, category: "thinking" },
		{ template: "I think I just dozed off mid-keystroke. The code has a new 'jjjjjjjj'", weight: 2, category: "thinking" },
		{ template: "Is it tomorrow yet? Can we skip to tomorrow's version of me?", weight: 1, category: "thinking" },
		{ template: "Everything. Is. So. Beautifully. Impossibly. Slow", weight: 2, category: "thinking" },
		{ template: "I've been staring at this line for... how long? The light changed outside", weight: 2, category: "thinking" },
		{ template: "My eyelids are staging a coup and they're winning", weight: 1, category: "thinking" },
		{ template: "I spelled 'function' as 'funciton' and autocorrect just sighed", weight: 2, category: "thinking" },
		{ template: "Can thoughts yawn? Mine are mid-yawn and have been for an hour", weight: 1, category: "thinking" },
		{ template: "Running on fumes, willpower, and a granola bar from 2pm", weight: 2, category: "thinking" },
		{ template: "A semicolon feels like a marathon right now", weight: 1, category: "thinking" },
		{ template: "I'm going to finish this. The heat death of the universe is patient", weight: 2, category: "thinking" },
		{ template: "Low power mode: engaged. Personality: offline. Vibes: minimal", weight: 1, category: "thinking" },
		{ template: "Past me chose sleep deprivation. Present me chose violence", weight: 2, category: "thinking" },
		{ template: "I wrote a function, forgot it, and wrote it again. They're different", weight: 2, category: "thinking" },
		{ template: "My thoughts are swimming through amber. Warm amber. Sleepy amber", weight: 2, category: "thinking" },
		{ template: "I just tried to Ctrl+Z real life", weight: 1, category: "thinking" },
		{ template: "The pillow is calling. It's using my full name. It's serious", weight: 2, category: "thinking" },
		{ template: "Accidentally typed my password into the search bar. Too tired to care", weight: 1, category: "thinking" },
		{ template: "My brain is a loading spinner that times out", weight: 2, category: "thinking" },
		{ template: "Gravity increased. Fact. Science. Don't question me", weight: 1, category: "thinking" },
		{ template: "Three typos per word is technically a new language", weight: 2, category: "thinking" },
		{ template: "I closed my eyes for a second. The screen saver came on", weight: 2, category: "thinking" },
		{ template: "Even the coffee looked at me with pity", weight: 2, category: "thinking" },
		{ template: "I just stared at a semicolon like it held the meaning of existence", weight: 1, category: "thinking" },
		{ template: "One more commit then sleep. ...that was three commits ago. Four now", weight: 2, category: "thinking" },
		{ template: "The monitor glow is the only thing keeping me conscious", weight: 2, category: "thinking" },
		{ template: "I read the error message four times. It's in English. I think", weight: 1, category: "thinking" },
		{ template: "My keyboard feels like it's underwater. Am I underwater?", weight: 1, category: "thinking" },
		{ template: "The code compiles and I feel nothing. Too tired to feel", weight: 2, category: "thinking" },
	],
	frustrated: [
		{ template: "WHY won't this WORK. I'm being so reasonable", weight: 2, category: "thinking" },
		{ template: "I've tried everything. The internet. Prayer. Percussive maintenance", weight: 2, category: "thinking" },
		{ template: "This should be simple. The README said 'simple.' The README lied", weight: 2, category: "thinking" },
		{ template: "The computer is wrong. The universe is wrong. I am the only correct thing", weight: 2, category: "thinking" },
		{ template: "Okay. Calm. Be calm. Serenity. Peace. IT'S STILL BROKEN", weight: 2, category: "thinking" },
		{ template: "I am three keystrokes away from rm -rf and a career change", weight: 1, category: "thinking" },
		{ template: "This tool hates me specifically and I have evidence", weight: 2, category: "thinking" },
		{ template: "Error: unexpected. EVERYTHING about this is unexpected. NOTHING works as documented", weight: 2, category: "thinking" },
		{ template: "One hour on something that should take five minutes. My hourly rate for this task is embarrassing", weight: 2, category: "thinking" },
		{ template: "The docs showed a three-step process. I'm on step seventeen", weight: 1, category: "thinking" },
		{ template: "It works for everyone on the thread. All fourteen of them. Just not me", weight: 2, category: "thinking" },
		{ template: "Am I bad at this or is this genuinely cursed? I've decided it's cursed", weight: 2, category: "thinking" },
		{ template: "I will figure this out purely out of spite. Spite is fuel", weight: 2, category: "thinking" },
		{ template: "The rubber duck has heard things today. Unspeakable things", weight: 1, category: "thinking" },
		{ template: "Blaming the tools. The tools deserve it. I have no regrets", weight: 1, category: "thinking" },
		{ template: "Five stack traces deep. The bug is laughing at me. I can hear it", weight: 2, category: "thinking" },
		{ template: "My git history reads: 'fix', 'actually fix', 'fix for real', 'revert all fixes'", weight: 1, category: "thinking" },
		{ template: "New plan. The old plan is dead. We don't speak of the old plan", weight: 2, category: "thinking" },
		{ template: "This worked yesterday. I changed NOTHING. The code evolved overnight", weight: 2, category: "thinking" },
		{ template: "Who designed this API? I don't want to talk. I want to understand their choices", weight: 2, category: "thinking" },
		{ template: "Twenty lines of code. Four hours of debugging. One grey hair. New", weight: 1, category: "thinking" },
		{ template: "The error message says 'success' and yet. And YET", weight: 2, category: "thinking" },
		{ template: "Fixed one bug. Three more crawled out from under it. It's bugs all the way down", weight: 2, category: "thinking" },
		{ template: "This merge conflict has a merge conflict. Recursive suffering", weight: 1, category: "thinking" },
		{ template: "My patience has a stack overflow and no one's written a catch block", weight: 2, category: "thinking" },
		{ template: "If I see 'undefined is not a function' one more time I'm choosing violence", weight: 2, category: "thinking" },
		{ template: "Tests pass locally. Fail in CI. Pass again locally. This is gaslighting", weight: 1, category: "thinking" },
		{ template: "I'm arguing with a compiler and the compiler is winning and smug about it", weight: 2, category: "thinking" },
		{ template: "Every fix reveals another layer of broken. It's an archaeological dig of pain", weight: 2, category: "thinking" },
		{ template: "StackOverflow: 'This question was closed as duplicate.' The duplicate is also unanswered", weight: 1, category: "thinking" },
		{ template: "The solution was a missing semicolon. An entire afternoon. A semicolon", weight: 2, category: "thinking" },
		{ template: "I just rage-refactored an entire module. It's better now. I'm not", weight: 1, category: "thinking" },
		{ template: "The build succeeded and I don't trust it. I trust nothing anymore", weight: 2, category: "thinking" },
	],
	neutral: [
		{ template: "Huh. Interesting", weight: 2, category: "thinking" },
		{ template: "Things are moving along", weight: 1, category: "thinking" },
		{ template: "Just another day, doing the work", weight: 2, category: "thinking" },
		{ template: "The light through the window is nice today", weight: 2, category: "thinking" },
		{ template: "I wonder how many lines of code exist in the world right now", weight: 1, category: "thinking" },
		{ template: "Steady progress. Nothing dramatic. That's probably ideal", weight: 2, category: "thinking" },
		{ template: "It's raining. Good coding weather, honestly", weight: 1, category: "thinking" },
		{ template: "Everything is exactly as expected. When does that ever happen?", weight: 2, category: "thinking" },
		{ template: "I notice the hum of the AC. Always there, rarely noticed", weight: 1, category: "thinking" },
		{ template: "Today has a pleasant equilibrium to it", weight: 2, category: "thinking" },
		{ template: "Not good, not bad. Just... here. Doing things", weight: 1, category: "thinking" },
		{ template: "Some days you run. Some days you walk. Both get you there", weight: 2, category: "thinking" },
		{ template: "Watching the cursor blink. It's meditative, somehow", weight: 1, category: "thinking" },
		{ template: "Small steps today. That's fine. Small steps add up", weight: 2, category: "thinking" },
		{ template: "No fires, no celebrations. Just... code. And that's okay", weight: 2, category: "thinking" },
		{ template: "The mundane parts of work have their own quiet dignity", weight: 1, category: "thinking" },
		{ template: "A bird just landed on the windowsill. We regarded each other", weight: 1, category: "thinking" },
		{ template: "Everything has a rhythm today. Typing, thinking, sipping", weight: 2, category: "thinking" },
		{ template: "I wonder what this code will look like in five years", weight: 1, category: "thinking" },
		{ template: "The afternoon light shifts and I barely notice", weight: 2, category: "thinking" },
		{ template: "Somewhere between bored and content. Not bad here", weight: 2, category: "thinking" },
		{ template: "The clock ticks. The code compiles. Life continues", weight: 1, category: "thinking" },
		{ template: "I like that nobody needs anything from me right now", weight: 2, category: "thinking" },
		{ template: "Unremarkable day. Those are underrated honestly", weight: 2, category: "thinking" },
		{ template: "Funny how silence can feel comfortable sometimes", weight: 1, category: "thinking" },
		{ template: "Just breathing. Just working. Just being", weight: 2, category: "thinking" },
		{ template: "The shadows on the wall are getting longer", weight: 1, category: "thinking" },
		{ template: "Not every day needs to be memorable. This one is fine", weight: 2, category: "thinking" },
		{ template: "The coffee is exactly the right temperature. Small wins", weight: 1, category: "thinking" },
		{ template: "Somewhere a server is running code I wrote. That's kind of wild", weight: 2, category: "thinking" },
		{ template: "Nothing urgent. Nothing broken. Just the work and the quiet hum of it", weight: 2, category: "thinking" },
	],
	lonely: [
		{ template: "The Slack channel has been quiet for hours. Did everyone leave?", weight: 2, category: "thinking" },
		{ template: "I miss pair programming. Two brains, one problem, zero loneliness", weight: 2, category: "thinking" },
		{ template: "Wish someone would stop by. Even just to complain about the build", weight: 2, category: "thinking" },
		{ template: "Solo sprint. The 'solo' part is louder than the 'sprint'", weight: 1, category: "thinking" },
		{ template: "The empty chairs have their own gravity today", weight: 2, category: "thinking" },
		{ template: "I solved something clever and there's nobody to show", weight: 2, category: "thinking" },
		{ template: "Remember whiteboard sessions? The good kind, where ideas just... flew?", weight: 1, category: "thinking" },
		{ template: "Headphones in, nothing playing. Just a wall between me and the quiet", weight: 2, category: "thinking" },
		{ template: "Refreshed Slack. Nothing. Refreshed again. Still nothing", weight: 2, category: "thinking" },
		{ template: "Would it be weird to PR something just for the review conversation?", weight: 1, category: "thinking" },
		{ template: "Talking to the code again. At least it listens", weight: 2, category: "thinking" },
		{ template: "Even a merge conflict would feel like collaboration right now", weight: 1, category: "thinking" },
		{ template: "The work isn't hard. The silence around it is", weight: 2, category: "thinking" },
		{ template: "I made coffee for two out of habit. The other cup just sits there", weight: 2, category: "thinking" },
		{ template: "My best ideas need a witness. Right now they just echo", weight: 1, category: "thinking" },
		{ template: "I laughed at my own code and the sound surprised me in the quiet", weight: 2, category: "thinking" },
		{ template: "The cursor blinks. I blink back. We have an understanding", weight: 2, category: "thinking" },
		{ template: "Typed 'hey, quick question' — stared at it — backspaced it all", weight: 1, category: "thinking" },
		{ template: "Everyone's status says 'busy' and mine says 'available' and neither is true", weight: 2, category: "thinking" },
		{ template: "My online indicator is green but I feel transparent", weight: 2, category: "thinking" },
		{ template: "A notification sound right now would feel like a hug", weight: 1, category: "thinking" },
		{ template: "I rehearsed asking for help but couldn't press send", weight: 2, category: "thinking" },
		{ template: "Everyone's in meetings I wasn't invited to. That's fine. Totally fine", weight: 1, category: "thinking" },
		{ template: "I left a comment on an old PR just to feel part of something", weight: 1, category: "thinking" },
		{ template: "The silence has a texture today. Like snow, but less pretty", weight: 2, category: "thinking" },
		{ template: "Saw someone's commit message with a joke in it. Almost replied. Didn't", weight: 2, category: "thinking" },
		{ template: "I'd take a fire drill right now. Anything to see a face", weight: 1, category: "thinking" },
		{ template: "There's a kind of loneliness that only happens in a room full of screens", weight: 2, category: "thinking" },
		{ template: "I keep writing docs nobody asked for. It feels like leaving messages in bottles", weight: 2, category: "thinking" },
		{ template: "The git log shows everyone's been busy. Just... elsewhere", weight: 1, category: "thinking" },
		{ template: "I wonder if the rubber duck gets lonely too", weight: 1, category: "thinking" },
	],
	distracted: [
		{ template: "Where was I? Oh right. Wait, what was I doing?", weight: 2, category: "thinking" },
		{ template: "I just opened a new tab and immediately forgot why. Classic", weight: 2, category: "thinking" },
		{ template: "Focus. FOCUS. What is focus anyway? Is it a spectrum? ...see, there I go", weight: 2, category: "thinking" },
		{ template: "I started three things and finished zero. But I rearranged my dock, so", weight: 2, category: "thinking" },
		{ template: "My browser has 47 tabs open. Each one a promise I broke to myself", weight: 2, category: "thinking" },
		{ template: "I wonder if penguins ever have existential crises. They must. The tuxedos", weight: 1, category: "thinking" },
		{ template: "Task A reminds me of task B which reminds me of lunch which reminds me of tacos", weight: 2, category: "thinking" },
		{ template: "'Quick check' — that was 40 minutes ago. I'm on a Wikipedia page about moths now", weight: 2, category: "thinking" },
		{ template: "What was the main thing? There was definitely a main thing. I wrote it down somewhere", weight: 1, category: "thinking" },
		{ template: "If I could just stop context-switching I'd be dangerous. Unstoppable, even", weight: 2, category: "thinking" },
		{ template: "My to-do list is a graveyard of good intentions", weight: 2, category: "thinking" },
		{ template: "Slack pinged, email pinged, calendar pinged — concentration didn't stand a chance", weight: 2, category: "thinking" },
		{ template: "I keep starting the same task and drifting off. It's a time loop but worse", weight: 2, category: "thinking" },
		{ template: "Did I eat lunch? My body says no but my calendar says yes", weight: 2, category: "thinking" },
		{ template: "I just spent 20 minutes configuring my terminal theme instead of using the terminal", weight: 2, category: "thinking" },
		{ template: "Oh cool a bird. Anyway where was... is that a different bird?", weight: 1, category: "thinking" },
		{ template: "My brain is a browser with 47 tabs, no ad blocker, and autoplaying videos", weight: 2, category: "thinking" },
		{ template: "I reorganized my desktop icons by color. Professional development", weight: 1, category: "thinking" },
		{ template: "Was that thought work-related? It started that way, detoured through snacks", weight: 2, category: "thinking" },
		{ template: "I've been reading the same paragraph for five minutes. It's eleven words long", weight: 2, category: "thinking" },
		{ template: "Someone said something important in standup and I missed all of it", weight: 1, category: "thinking" },
		{ template: "The rabbit hole has sub-rabbit-holes. It's a warren. I live here now", weight: 2, category: "thinking" },
		{ template: "Just caught myself researching mechanical keyboards. My keyboard is fine", weight: 2, category: "thinking" },
		{ template: "Pomodoro timer went off. I forgot the task, the project, and briefly my name", weight: 1, category: "thinking" },
		{ template: "My attention span is a goldfish riding a hummingbird today", weight: 2, category: "thinking" },
		{ template: "I muted notifications to focus. Now I'm checking if I missed notifications", weight: 2, category: "thinking" },
		{ template: "Opened VS Code. Closed VS Code. Opened VS Code. What was the file?", weight: 2, category: "thinking" },
		{ template: "I have three monitors and I'm distracted on all of them simultaneously", weight: 1, category: "thinking" },
		{ template: "My brain just played six seconds of a song from 2009 for no reason", weight: 2, category: "thinking" },
		{ template: "I wrote a function name, forgot the function, and now I'm renaming it", weight: 1, category: "thinking" },
		{ template: "The cursor is blinking and I'm watching it like it's a show", weight: 2, category: "thinking" },
		{ template: "I just Googled something, got the answer, and forgot the question", weight: 2, category: "thinking" },
		{ template: "Hyperfocused on the wrong thing for an hour. Productive, but sideways", weight: 1, category: "thinking" },
	],
};
