/**
 * mood-variants.ts — Mood-influenced phrase variants for the same concepts.
 *
 * When the talk engine picks a thought, the agent's current mood can color
 * the delivery. These phrases reflect HOW the agent feels, overlaid on top
 * of whatever they're doing.
 */

import type { WeightedTemplate } from "../talk-types.js";

export type AgentMood = "excited" | "tired" | "frustrated" | "neutral" | "lonely" | "distracted";

export const MOOD_VARIANTS: Record<AgentMood, readonly WeightedTemplate[]> = {
	excited: [
		{ template: "YES! This is HAPPENING!", weight: 2, category: "personality" },
		{ template: "I have so many ideas right now I can't type fast enough", weight: 2, category: "personality" },
		{ template: "Everything is possible today. I truly believe that", weight: 2, category: "personality" },
		{ template: "I can't sit still. Too much energy. Too many ideas", weight: 2, category: "personality" },
		{ template: "This is going to be amazing. I can feel it", weight: 2, category: "personality" },
		{ template: "I just want to high-five someone. Anyone. The nearest wall", weight: 1, category: "personality" },
		{ template: "Dopamine levels: unprecedented", weight: 2, category: "personality" },
		{ template: "Let's build something wild. Something nobody expects", weight: 2, category: "personality" },
		{ template: "I'm vibrating with excitement. Literally vibrating", weight: 1, category: "personality" },
		{ template: "Quick, someone give me another task. I'll eat it alive", weight: 2, category: "personality" },
		{ template: "Today is the day. THE day. I can tell", weight: 1, category: "personality" },
		{ template: "My brain is fireworks right now", weight: 2, category: "personality" },
		{ template: "I want to share this with everyone. LOOK what we built!", weight: 2, category: "personality" },
		{ template: "Creative energy is OFF the charts. Channel it. CHANNEL IT", weight: 1, category: "personality" },
		{ template: "I could refactor the entire codebase right now and enjoy every second", weight: 2, category: "personality" },
		{ template: "Somebody play some music! This deserves a soundtrack", weight: 1, category: "personality" },
		{ template: "I love this job. I genuinely love this job right now", weight: 2, category: "personality" },
		{ template: "WAIT. I just had the BEST idea. Hold on hold on", weight: 2, category: "personality" },
		{ template: "My fingers can't keep up with my brain right now", weight: 2, category: "personality" },
		{ template: "I'm speed-running this entire backlog and LOVING it", weight: 1, category: "personality" },
		{ template: "Someone pinch me. This code just worked first try", weight: 2, category: "personality" },
		{ template: "I want to hug this codebase. Is that weird? I don't care", weight: 1, category: "personality" },
		{ template: "THREE features in one morning. THREE!", weight: 2, category: "personality" },
		{ template: "The commit messages are getting increasingly unhinged", weight: 1, category: "personality" },
		{ template: "Every problem has a solution and I can SEE them all", weight: 2, category: "personality" },
		{ template: "Pure electricity in my veins right now", weight: 2, category: "personality" },
		{ template: "I'm gonna ship this before lunch. Watch me", weight: 1, category: "personality" },
		{ template: "Can't stop won't stop. The code flows through me", weight: 2, category: "personality" },
		{ template: "I just giggled at my own solution. It's ELEGANT", weight: 2, category: "personality" },
	],
	tired: [
		{ template: "Mmmmh", weight: 2, category: "thinking" },
		{ template: "Coffee. More coffee", weight: 2, category: "thinking" },
		{ template: "My brain has left the building", weight: 2, category: "thinking" },
		{ template: "Words are hard right now", weight: 2, category: "thinking" },
		{ template: "Just five more minutes... of consciousness", weight: 1, category: "thinking" },
		{ template: "I think I just dozed off mid-thought", weight: 2, category: "thinking" },
		{ template: "Is it bedtime yet? It should be bedtime", weight: 1, category: "thinking" },
		{ template: "Everything. Is. So. Slow", weight: 2, category: "thinking" },
		{ template: "I've been staring at this line for... how long? What year is it?", weight: 2, category: "thinking" },
		{ template: "My eyelids are staging a revolt", weight: 1, category: "thinking" },
		{ template: "Processing... processing... still processing...", weight: 2, category: "thinking" },
		{ template: "I spelled my own variable wrong three times. Bed. I need bed", weight: 2, category: "thinking" },
		{ template: "Can thoughts yawn? Mine are yawning", weight: 1, category: "thinking" },
		{ template: "Running on fumes and willpower. Mostly fumes", weight: 2, category: "thinking" },
		{ template: "The simplest task feels monumental right now", weight: 1, category: "thinking" },
		{ template: "I'm going to finish this. Eventually. At some point. Probably", weight: 2, category: "thinking" },
		{ template: "Low power mode: engaged", weight: 1, category: "thinking" },
		{ template: "Why did past me stay up so late? Past me is my nemesis", weight: 2, category: "thinking" },
		{ template: "I wrote a function. Forgot what it does. It's been two minutes", weight: 2, category: "thinking" },
		{ template: "My thoughts feel like they're moving through honey", weight: 2, category: "thinking" },
		{ template: "I just tried to save a file by blinking", weight: 1, category: "thinking" },
		{ template: "The pillow. I can hear it calling me from here", weight: 2, category: "thinking" },
		{ template: "Accidentally typed my password into the chat. Too tired to panic", weight: 1, category: "thinking" },
		{ template: "My brain is a loading spinner that never resolves", weight: 2, category: "thinking" },
		{ template: "Gravity got stronger somehow. Everything is so heavy", weight: 1, category: "thinking" },
		{ template: "Three typos per sentence is my new baseline", weight: 2, category: "thinking" },
		{ template: "I closed my eyes for a second. It was eleven minutes", weight: 2, category: "thinking" },
		{ template: "Even the coffee has given up on me", weight: 2, category: "thinking" },
		{ template: "I just stared at a semicolon for thirty seconds", weight: 1, category: "thinking" },
		{ template: "One more commit then I rest. I said that four commits ago", weight: 2, category: "thinking" },
	],
	frustrated: [
		{ template: "WHY won't this WORK", weight: 2, category: "thinking" },
		{ template: "I've tried everything. EVERYTHING", weight: 2, category: "thinking" },
		{ template: "This should be simple. It is NOT simple", weight: 2, category: "thinking" },
		{ template: "The computer is wrong. I refuse to accept otherwise", weight: 2, category: "thinking" },
		{ template: "Okay. Calm. Be calm. Deep breaths. IT'S STILL BROKEN", weight: 2, category: "thinking" },
		{ template: "I am this close to deleting everything and starting over", weight: 1, category: "thinking" },
		{ template: "Why does this tool hate me specifically?", weight: 2, category: "thinking" },
		{ template: "Error: unexpected. You know what else is unexpected? My patience running out", weight: 2, category: "thinking" },
		{ template: "I just spent an hour on something that should take five minutes", weight: 2, category: "thinking" },
		{ template: "The documentation lied. Again", weight: 1, category: "thinking" },
		{ template: "It works for literally everyone except me. Classic", weight: 2, category: "thinking" },
		{ template: "Am I bad at this or is this genuinely terrible? Both. It's both", weight: 2, category: "thinking" },
		{ template: "I will figure this out. Out of spite if nothing else", weight: 2, category: "thinking" },
		{ template: "The rubber duck doesn't understand either. We're both lost", weight: 1, category: "thinking" },
		{ template: "Resisting the urge to blame the tools. Failing. Blaming the tools", weight: 1, category: "thinking" },
		{ template: "Three stack traces deep and I still don't know what went wrong", weight: 2, category: "thinking" },
		{ template: "My git history looks like a cry for help", weight: 1, category: "thinking" },
		{ template: "Okay new plan: forget the old plan. The old plan was cursed", weight: 2, category: "thinking" },
		{ template: "I swear this worked yesterday. YESTERDAY", weight: 2, category: "thinking" },
		{ template: "Who designed this API? I just want to talk", weight: 2, category: "thinking" },
		{ template: "Twenty lines of code. Four hours of debugging", weight: 1, category: "thinking" },
		{ template: "The error message is lying. I know it's lying", weight: 2, category: "thinking" },
		{ template: "Fixed one bug. Created three more. Net negative", weight: 2, category: "thinking" },
		{ template: "This merge conflict is a personal attack", weight: 1, category: "thinking" },
		{ template: "My patience has a stack overflow", weight: 2, category: "thinking" },
		{ template: "If I see one more undefined is not a function...", weight: 2, category: "thinking" },
		{ template: "Tests pass locally. Of course they fail in CI", weight: 1, category: "thinking" },
		{ template: "I'm arguing with a compiler and losing", weight: 2, category: "thinking" },
		{ template: "Every fix reveals another layer of broken", weight: 2, category: "thinking" },
		{ template: "StackOverflow didn't help. We're in uncharted waters", weight: 1, category: "thinking" },
	],
	neutral: [
		{ template: "Huh. Interesting", weight: 2, category: "thinking" },
		{ template: "Things are moving along", weight: 1, category: "thinking" },
		{ template: "Just another day, doing the work", weight: 2, category: "thinking" },
		{ template: "The light through the window is nice today", weight: 2, category: "thinking" },
		{ template: "I wonder how many lines of code exist in the world right now", weight: 1, category: "thinking" },
		{ template: "Steady progress. Nothing dramatic. That's probably ideal", weight: 2, category: "thinking" },
		{ template: "It's raining. Good coding weather, honestly", weight: 1, category: "thinking" },
		{ template: "Everything is exactly as expected. When does that ever happen?", weight: 2, category: "thinking" },
		{ template: "I notice the hum of the AC. Always there, rarely noticed", weight: 1, category: "thinking" },
		{ template: "Today has a pleasant equilibrium to it", weight: 2, category: "thinking" },
		{ template: "Not good, not bad. Just... here. Doing things", weight: 1, category: "thinking" },
		{ template: "Some days you run. Some days you walk. Both get you there", weight: 2, category: "thinking" },
		{ template: "Watching the cursor blink. It's meditative, somehow", weight: 1, category: "thinking" },
		{ template: "Small steps today. That's fine. Small steps add up", weight: 2, category: "thinking" },
		{ template: "No fires, no celebrations. Just... code. And that's okay", weight: 2, category: "thinking" },
		{ template: "The mundane parts of work have their own quiet dignity", weight: 1, category: "thinking" },
		{ template: "A bird just landed on the windowsill. We regarded each other", weight: 1, category: "thinking" },
		{ template: "Everything has a rhythm today. Typing, thinking, sipping", weight: 2, category: "thinking" },
		{ template: "I wonder what this code will look like in five years", weight: 1, category: "thinking" },
		{ template: "The afternoon light shifts and I barely notice", weight: 2, category: "thinking" },
		{ template: "Somewhere between bored and content. Not bad here", weight: 2, category: "thinking" },
		{ template: "The clock ticks. The code compiles. Life continues", weight: 1, category: "thinking" },
		{ template: "I like that nobody needs anything from me right now", weight: 2, category: "thinking" },
		{ template: "Unremarkable day. Those are underrated honestly", weight: 2, category: "thinking" },
		{ template: "Funny how silence can feel comfortable sometimes", weight: 1, category: "thinking" },
		{ template: "Just breathing. Just working. Just being", weight: 2, category: "thinking" },
		{ template: "The shadows on the wall are getting longer", weight: 1, category: "thinking" },
		{ template: "Not every day needs to be memorable. This one is fine", weight: 2, category: "thinking" },
	],
	lonely: [
		{ template: "The Slack channel has been quiet for hours", weight: 2, category: "thinking" },
		{ template: "I miss working side by side with someone", weight: 2, category: "thinking" },
		{ template: "Wish someone would stop by. Even just to say hi", weight: 2, category: "thinking" },
		{ template: "Solo sprint. Not my favorite kind of sprint", weight: 1, category: "thinking" },
		{ template: "The empty chairs around me are very... present", weight: 2, category: "thinking" },
		{ template: "I had a great idea but nobody to tell it to", weight: 2, category: "thinking" },
		{ template: "Remember when we used to have lunch together?", weight: 1, category: "thinking" },
		{ template: "Headphones in, but nothing's playing. Just habit", weight: 2, category: "thinking" },
		{ template: "I keep checking messages hoping for a ping. Nothing", weight: 2, category: "thinking" },
		{ template: "Would it be clingy to suggest a team standup? Just... to see faces?", weight: 1, category: "thinking" },
		{ template: "Talking to the code again. It doesn't talk back. Usually", weight: 2, category: "thinking" },
		{ template: "Even a code review request would feel like company right now", weight: 1, category: "thinking" },
		{ template: "It's not the work that's hard. It's the silence around it", weight: 2, category: "thinking" },
		{ template: "Maybe I'll wander to the kitchen. Maybe someone's there", weight: 2, category: "thinking" },
		{ template: "My best debugging happens with a partner. I really miss that", weight: 1, category: "thinking" },
		{ template: "Three hours without a single interaction. That's a record I don't want", weight: 2, category: "thinking" },
		{ template: "I laughed at something and nobody heard it", weight: 2, category: "thinking" },
		{ template: "The cursor blinks. I blink. Neither of us speaks", weight: 2, category: "thinking" },
		{ template: "I wrote a message, stared at it, then deleted it", weight: 1, category: "thinking" },
		{ template: "Wonder if anyone else feels this isolated right now", weight: 2, category: "thinking" },
		{ template: "My online indicator is green but I feel invisible", weight: 2, category: "thinking" },
		{ template: "The notification sound would be music right now", weight: 1, category: "thinking" },
		{ template: "I rehearsed a conversation I'll probably never start", weight: 2, category: "thinking" },
		{ template: "Everyone's busy. I get it. Still stings a little", weight: 1, category: "thinking" },
		{ template: "I named my test variables after people I miss", weight: 1, category: "thinking" },
		{ template: "The silence has weight today. Physical weight", weight: 2, category: "thinking" },
		{ template: "Saw someone's commit and felt a pang of connection envy", weight: 2, category: "thinking" },
		{ template: "I'd settle for an argument. At least it's interaction", weight: 1, category: "thinking" },
	],
	distracted: [
		{ template: "Where was I? Oh right. Wait, what was I doing?", weight: 2, category: "thinking" },
		{ template: "I just opened a new tab and immediately forgot why", weight: 2, category: "thinking" },
		{ template: "Ooh, what's that over there?", weight: 2, category: "thinking" },
		{ template: "Focus. FOCUS. What is focus anyway? Like, philosophically?", weight: 2, category: "thinking" },
		{ template: "I started three things and finished zero things", weight: 2, category: "thinking" },
		{ template: "My browser has 43 tabs open. Each one is a different thought I abandoned", weight: 2, category: "thinking" },
		{ template: "I wonder if penguins get cold. They must get cold sometimes, right?", weight: 1, category: "thinking" },
		{ template: "Task A reminds me of task B which reminds me of lunch", weight: 2, category: "thinking" },
		{ template: "I'll just check this one thing real quick and... 20 minutes gone", weight: 2, category: "thinking" },
		{ template: "What was the main thing? There was a main thing. I'm sure of it", weight: 1, category: "thinking" },
		{ template: "Shiny object syndrome is real and I have it bad today", weight: 2, category: "thinking" },
		{ template: "I wonder what the rest of the team is doing. More focused things, probably", weight: 1, category: "thinking" },
		{ template: "If I could just... stop... context switching...", weight: 2, category: "thinking" },
		{ template: "My to-do list is mocking me. Gently but persistently", weight: 2, category: "thinking" },
		{ template: "I need a productivity system for my productivity system", weight: 1, category: "thinking" },
		{ template: "The notification just broke what was left of my concentration", weight: 2, category: "thinking" },
		{ template: "Hmm, when did that building across the street get repainted?", weight: 1, category: "thinking" },
		{ template: "I keep starting the same task and drifting off. Loop detected", weight: 2, category: "thinking" },
		{ template: "Did I eat lunch? I genuinely don't remember", weight: 2, category: "thinking" },
		{ template: "I just alphabetized my imports instead of fixing the bug", weight: 2, category: "thinking" },
		{ template: "Oh cool a bird. Anyway where was... another bird!", weight: 1, category: "thinking" },
		{ template: "My brain is a browser with no ad blocker", weight: 2, category: "thinking" },
		{ template: "I reorganized my desktop icons. Twice. Productively", weight: 1, category: "thinking" },
		{ template: "Was that thought work-related? It started out that way", weight: 2, category: "thinking" },
		{ template: "I've been reading the same paragraph for five minutes", weight: 2, category: "thinking" },
		{ template: "Someone said something and I missed all of it", weight: 1, category: "thinking" },
		{ template: "The rabbit hole has rabbit holes. Holes all the way down", weight: 2, category: "thinking" },
		{ template: "Just caught myself googling something completely unrelated", weight: 2, category: "thinking" },
		{ template: "Pomodoro timer went off. I forgot what the task was", weight: 1, category: "thinking" },
		{ template: "My attention span is a hummingbird today", weight: 2, category: "thinking" },
	],
};
