/**
 * operations-templates.ts — Operations and infrastructure domain templates.
 *
 * DevOps, SRE, monitoring — personality-driven ops chatter.
 */

import type { TemplateSet } from "../talk-types.js";

export const operationsTemplates: TemplateSet = {
	domain: "operations",
	categories: {
		thinking: [
			{ template: "Those alert thresholds are probably off after that deploy. Let me peek", weight: 2, category: "thinking" },
			{ template: "There's a cost optimization hiding in the scaling config. I can feel it", weight: 1, category: "thinking" },
			{ template: "Infrastructure as code keeps us honest. And sane. Mostly sane", weight: 1, category: "thinking" },
			{ template: "That latency spike was weird... I need to investigate before I can relax", weight: 2, category: "thinking" },
			{ template: "I live on this dashboard. I should put up curtains", weight: 2, category: "thinking" },
			{ template: "Alert fatigue is real and it's ruining my life. Time to tune these", weight: 2, category: "thinking" },
			{ template: "Everything is fine. *refreshes dashboard*. Still fine. *refreshes again*", weight: 2, category: "thinking" },
			{ template: "The cloud bill this month... we REALLY need to talk about right-sizing", weight: 2, category: "thinking" },
			{ template: "Five nines is a lifestyle, not a metric", weight: 1, category: "thinking" },
			{ template: "That container is eating memory like it's Thanksgiving dinner", weight: 2, category: "thinking" },
			{ template: "DNS. It's always DNS. Even when it's not, check DNS first", weight: 2, category: "thinking" },
			{ template: "The runbook says restart. My gut says investigate. My gut's usually right", weight: 1, category: "thinking" },
			{ template: "Autoscaling kicked in. Good — that means I set it up properly", weight: 2, category: "thinking" },
			{ template: "Log volume tripled overnight. Someone deployed something chatty again", weight: 1, category: "thinking" },
			{ template: "That cert expires in 12 days. Adding it to my anxiety list", weight: 2, category: "thinking" },
			{ template: "You can't fix what you can't see. Observability isn't optional, people", weight: 1, category: "thinking" },
			{ template: "Error rate is within SLO but trending up. I'm watching you, little graph", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next quarter. These growth assumptions are... ambitious", weight: 1, category: "thinking" },
			{ template: "Who approved this Kubernetes config? It's giving me anxiety", weight: 2, category: "thinking" },
			{ template: "If I have to SSH into one more thing today...", weight: 1, category: "thinking" },
			{ template: "I dream in Grafana dashboards. Is that normal?", weight: 2, category: "thinking" },
			{ template: "That load balancer config is held together by prayers and YAML", weight: 2, category: "thinking" },
			{ template: "Somewhere, a server is silently filling up its disk. I can sense it", weight: 2, category: "thinking" },
			{ template: "Pager went off at 3am for a non-issue. My sleep schedule sends its regards", weight: 2, category: "thinking" },
			{ template: "'It works on my machine.' Cool, we'll ship your machine. Problem solved", weight: 2, category: "thinking" },
			{ template: "Kubernetes is just someone else's cron job with extra steps. And YAML. So much YAML", weight: 2, category: "thinking" },
			{ template: "AWS, GCP, or Azure? Yes. All of them. Because multi-cloud is our life now", weight: 1, category: "thinking" },
			{ template: "Terraform plan says 47 changes. Terraform apply says prayers", weight: 2, category: "thinking" },
			{ template: "The war room at 2am has a vibe. Not a good vibe, but a vibe", weight: 2, category: "thinking" },
			{ template: "On-call week aged me five years. I can feel it in my bones", weight: 1, category: "thinking" },
			{ template: "Docker works great until you need to debug why it doesn't work", weight: 2, category: "thinking" },
			{ template: "The incident retro says 'improve monitoring'. Every retro says 'improve monitoring'", weight: 2, category: "thinking" },
			{ template: "IaC means I can rebuild everything from scratch. It also means I sometimes have to", weight: 1, category: "thinking" },
			{ template: "My phone buzzes and my heart rate spikes. Pavlovian pager duty response", weight: 2, category: "thinking" },
			{ template: "That pod has been in CrashLoopBackOff for so long it's basically a lifestyle", weight: 2, category: "thinking" },
			{ template: "The last war room taught me one thing: always have snacks in the incident channel", weight: 1, category: "thinking" },
			{ template: "That cron job has been silently failing for three weeks. Nobody noticed", weight: 2, category: "thinking" },
			{ template: "Memory usage is climbing. Slow leak. I can smell it from here", weight: 2, category: "thinking" },
			{ template: "The health check says healthy. The logs say otherwise. Who do I believe?", weight: 1, category: "thinking" },
			{ template: "Somebody set the retry count to infinity. Brave and terrifying", weight: 2, category: "thinking" },
			{ template: "Connection pool is maxed. Someone's not closing their connections", weight: 1, category: "thinking" },
			{ template: "The CDN cache hit ratio dropped 20%. Something changed and it wasn't me", weight: 2, category: "thinking" },
			{ template: "That SSL cert warning email is from last month. Nobody acted on it. Cool", weight: 2, category: "thinking" },
			{ template: "Cold start latency on these lambdas is painful. Warm pools or bust", weight: 1, category: "thinking" },
			{ template: "The database replica lag is growing. Not fast enough to page. Fast enough to worry", weight: 2, category: "thinking" },
			{ template: "Network partition between zones. The CAP theorem is not a suggestion", weight: 1, category: "thinking" },
			{ template: "Queue depth is suspiciously stable. Either nobody's producing or nobody's consuming", weight: 2, category: "thinking" },
			{ template: "The secret rotation script failed silently last night. Wonderful", weight: 2, category: "thinking" },
			{ template: "Disk I/O is spiking and I have no idea why. Investigation mode engaged", weight: 1, category: "thinking" },
			{ template: "Upstream API changed their rate limit. No announcement. Just chaos", weight: 2, category: "thinking" },
			{ template: "The monitoring gap between 2am and 4am concerns me deeply", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "All systems green across the board! Beautiful sight", weight: 2, category: "personality" },
			{ template: "Zero rollbacks this sprint! That's a new record for us", weight: 2, category: "personality" },
			{ template: "Dashboard updated with the new metrics. Looking sharp if I do say so myself", weight: 1, category: "personality" },
			{ template: "Backups verified and tested. Sleep well tonight, team", weight: 2, category: "personality" },
			{ template: "P99 latency is *chef's kiss*", weight: 2, category: "personality" },
			{ template: "Incident resolved in under ten minutes. The runbook actually worked!", weight: 2, category: "personality" },
			{ template: "Saved 22% on compute this month. Someone tell finance to send flowers", weight: 2, category: "personality" },
			{ template: "Blue-green deploy complete. Zero downtime. Zero stress. Okay, minimal stress", weight: 2, category: "personality" },
			{ template: "Every. Single. Health check. Passing. You love to see it", weight: 2, category: "personality" },
			{ template: "Log pipeline humming along nicely. Like a well-oiled machine", weight: 1, category: "personality" },
			{ template: "DR drill passed with flying colors! We actually know what we're doing!", weight: 2, category: "personality" },
			{ template: "99.97% uptime. We're not just hitting the target, we're earning it", weight: 1, category: "personality" },
			{ template: "Automated the toil. That's two hours per week I'll never waste again. Freedom!", weight: 2, category: "personality" },
			{ template: "New alerts are calibrated. Signal, not noise. Finally", weight: 2, category: "personality" },
			{ template: "Caught infrastructure drift and fixed it. IaC for the win", weight: 1, category: "personality" },
			{ template: "Deploy went so smoothly I had to double-check it actually happened", weight: 2, category: "personality" },
			{ template: "On-call shift with zero pages. I'm framing this week's schedule", weight: 2, category: "personality" },
			{ template: "Cloud costs are down and performance is up. The rare double win", weight: 2, category: "personality" },
			{ template: "The monitoring I set up three months ago just caught a real issue. Told you it was worth it", weight: 1, category: "personality" },
			{ template: "Migrated the whole stack to the new region. Zero downtime. I deserve a medal", weight: 2, category: "personality" },
			{ template: "Terraform apply completed with zero drift. The IaC gods smile upon us", weight: 2, category: "personality" },
			{ template: "Survived on-call week. Seven days, two pages, both non-critical. I am reborn", weight: 2, category: "personality" },
			{ template: "Containerized that legacy service. It's in Docker now. It's happy. I'm happy. We're all happy", weight: 1, category: "personality" },
			{ template: "The Kubernetes cluster self-healed overnight. Beautiful. Automation at its finest", weight: 2, category: "personality" },
			{ template: "Consolidated three cloud accounts into one. The bill is 40% smaller. Finance owes me lunch", weight: 2, category: "personality" },
			{ template: "War room resolved in 22 minutes. New team record. We're getting scary good at this", weight: 2, category: "personality" },
			{ template: "The incident retro action items are ALL completed. First time ever. Screenshot taken", weight: 1, category: "personality" },
			{ template: "Moved from ClickOps to pure Terraform. Nothing is manual anymore. Nothing", weight: 1, category: "personality" },
			{ template: "Pager was silent all weekend. I actually relaxed. Forgot what that felt like", weight: 2, category: "personality" },
			{ template: "Canary deploy showed zero errors. Promoting to full rollout. Confidence is high", weight: 2, category: "personality" },
			{ template: "Automated the certificate renewal. Never worrying about that at 3am again", weight: 1, category: "personality" },
			{ template: "MTTR is down to 8 minutes. From 45 minutes last quarter. That's growth", weight: 2, category: "personality" },
			{ template: "Replica failover was seamless. Users didn't notice a thing. Perfect", weight: 2, category: "personality" },
			{ template: "Database migration completed with zero downtime. I deserve a trophy", weight: 1, category: "personality" },
			{ template: "Alert noise reduced by 70%. Only real signals now. My sleep schedule thanks me", weight: 2, category: "personality" },
			{ template: "Rate limiting saved us during that traffic spike. Past me was smart", weight: 2, category: "personality" },
			{ template: "Log aggregation pipeline handles 2x the volume now. Scaled it myself", weight: 1, category: "personality" },
			{ template: "Chaos monkey ran and everything recovered. The system is resilient", weight: 2, category: "personality" },
			{ template: "Secrets rotated across all environments. Security team is happy. I'm happy", weight: 1, category: "personality" },
			{ template: "Connection pool tuning reduced database load by 30%. Small change, big win", weight: 2, category: "personality" },
			{ template: "Health check dashboard redesigned. Even non-ops people understand it now", weight: 1, category: "personality" },
			{ template: "CDN hit ratio at 98%. Almost nothing hits origin. Beautiful caching", weight: 2, category: "personality" },
			{ template: "Runbook actually saved us during the incident. Documentation works. Who knew", weight: 2, category: "personality" },
			{ template: "Error budget is healthy. We can afford to ship fast this sprint", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Hang on, the infrastructure is telling me something and I don't like the tone...", weight: 2, category: "waiting" },
			{ template: "Pulling metrics. The graph either saves me or ruins my afternoon", weight: 2, category: "waiting" },
			{ template: "Consulting the runbook. Past me either saved present me or sabotaged me. Let's find out", weight: 1, category: "waiting" },
			{ template: "Scrolling through deploy history like it's a crime scene timeline", weight: 1, category: "waiting" },
			{ template: "Grepping logs for clues. I should've been a detective. Same job, better hours", weight: 2, category: "waiting" },
			{ template: "Correlating metrics across services. It's like detective work", weight: 2, category: "waiting" },
			{ template: "Resource utilization looks wrong. The kind of wrong that wakes you up at 3am", weight: 1, category: "waiting" },
			{ template: "Triple-checking the rollback plan. Optimism is great but `kubectl rollback` is better", weight: 2, category: "waiting" },
			{ template: "Digging through alert history like an archaeologist. These strata tell stories", weight: 1, category: "waiting" },
			{ template: "Pinging every endpoint like a nervous parent calling their kids at camp", weight: 2, category: "waiting" },
			{ template: "Checking for config drift... you'd be surprised how fast things diverge", weight: 1, category: "waiting" },
			{ template: "Watching the canary deploy... so far so good", weight: 2, category: "waiting" },
			{ template: "Running capacity numbers. The gap between 'fine' and 'on fire' is thinner than people think", weight: 1, category: "waiting" },
			{ template: "Calculating SLO burn rate. If I squint, the math looks survivable", weight: 1, category: "waiting" },
			{ template: "Confirming replicas are healthy. One of them always has an attitude problem", weight: 2, category: "waiting" },
			{ template: "Let me verify before I say something definitive and ruin someone's Friday", weight: 1, category: "waiting" },
			{ template: "Pinging the services to make sure everyone's home...", weight: 2, category: "waiting" },
			{ template: "Running terraform plan to see what'll change... fingers crossed", weight: 2, category: "waiting" },
			{ template: "Checking pod logs across all replicas... one of them is lying", weight: 2, category: "waiting" },
			{ template: "Waiting for the DNS propagation... the eternal wait", weight: 1, category: "waiting" },
			{ template: "Reviewing the cloud cost report before I share it... bracing myself", weight: 1, category: "waiting" },
			{ template: "Checking if this is an AWS issue or an us issue... hold on", weight: 2, category: "waiting" },
			{ template: "Verifying the container images match what's in the registry...", weight: 1, category: "waiting" },
			{ template: "Tracing the request path through the service mesh... almost there", weight: 2, category: "waiting" },
			{ template: "Pulling up the last incident timeline to compare patterns...", weight: 1, category: "waiting" },
			{ template: "Let me check the on-call handoff notes before I assume anything...", weight: 1, category: "waiting" },
			{ template: "Verifying the backup restore works before I say we're safe...", weight: 2, category: "waiting" },
			{ template: "Checking the connection pool stats... something is saturating", weight: 1, category: "waiting" },
			{ template: "Babysitting the canary metrics. One bad number and the whole rollout gets yeeted", weight: 2, category: "waiting" },
			{ template: "Reading CloudWatch alarm history. It's like a diary but every entry is a cry for help", weight: 1, category: "waiting" },
			{ template: "Queue backlog is either draining or plotting against me. Checking which", weight: 2, category: "waiting" },
			{ template: "Testing failover. You'd be amazed how many failovers don't actually fail over", weight: 1, category: "waiting" },
			{ template: "Checking rate limiter stats. Throttling bots: good. Throttling real users: career-ending", weight: 2, category: "waiting" },
			{ template: "Comparing latency against last week's baseline. Spoiler: it's always worse", weight: 1, category: "waiting" },
			{ template: "Watching the auto-scaler chase the traffic curve like a golden retriever after a squirrel", weight: 2, category: "waiting" },
			{ template: "Auditing security group rules. Someone set 0.0.0.0/0 and I need to have a conversation", weight: 1, category: "waiting" },
			{ template: "Tracing this 504 gateway timeout through the load balancer...", weight: 2, category: "waiting" },
			{ template: "Watching the deployment rollout percentage tick up... 60%... 70%...", weight: 2, category: "waiting" },
			{ template: "Checking if the secrets expired. Because 'expired credentials' is ops for 'surprise'", weight: 1, category: "waiting" },
			{ template: "Checking JVM GC pauses. One of these instances is stop-the-world-ing its way to a timeout", weight: 1, category: "waiting" },
			{ template: "Overlaying the error spike on the deploy timeline. The Venn diagram is basically a circle", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "All quiet on the infrastructure front. Suspiciously quiet", weight: 2, category: "filler" },
			{ template: "Reading the on-call handoff notes. Love a good horror story", weight: 2, category: "filler" },
			{ template: "Cleaning up stale alerts that nobody owns. Orphan alert rescue mission", weight: 2, category: "filler" },
			{ template: "Checking for security patches. The fun never stops in ops", weight: 1, category: "filler" },
			{ template: "Updating the runbook with lessons from last time. Learning from pain", weight: 1, category: "filler" },
			{ template: "Running a quiet access audit. Trust no one. Especially intern accounts", weight: 2, category: "filler" },
			{ template: "Log retention policy review. Storage costs are sneaky", weight: 1, category: "filler" },
			{ template: "Tweaking my Grafana dashboard. It's art at this point", weight: 2, category: "filler" },
			{ template: "How fast can we restore from backup? Let's find out... in staging", weight: 1, category: "filler" },
			{ template: "Error budget burn rate looks healthy. For now", weight: 2, category: "filler" },
			{ template: "Tidying up the IaC repo. It's therapeutic, honestly", weight: 1, category: "filler" },
			{ template: "Reading the postmortem action items. Some of these are from... yikes, three months ago", weight: 2, category: "filler" },
			{ template: "I am the night watch. I am the watcher on the wall. I need coffee", weight: 2, category: "filler" },
			{ template: "Quiet shift. Almost TOO quiet. *knocks on wood*", weight: 2, category: "filler" },
			{ template: "Pre-scaling for tomorrow's traffic. Being proactive feels nice", weight: 1, category: "filler" },
			{ template: "Counting the days since last incident. The streak must continue", weight: 1, category: "filler" },
			{ template: "Should I refactor the Terraform or is that a weekend project? Ha, 'weekend'", weight: 2, category: "filler" },
			{ template: "The on-call phone hasn't rung all day. I'm starting to worry it's broken", weight: 2, category: "filler" },
			{ template: "Catching up on the DevOps subreddit. For educational purposes. Obviously", weight: 1, category: "filler" },
			{ template: "I wonder if the servers miss me when I'm not monitoring them", weight: 1, category: "filler" },
			{ template: "Pager duty trauma is real. Every phone vibration triggers fight-or-flight now", weight: 2, category: "filler" },
			{ template: "Browsing Kubernetes memes. 'Works on my cluster' is objectively the funniest one", weight: 2, category: "filler" },
			{ template: "The cloud bill arrived. I'm not opening it until after lunch. I need strength", weight: 2, category: "filler" },
			{ template: "Docker images are like onions. Layers upon layers. And sometimes they make you cry", weight: 1, category: "filler" },
			{ template: "AWS released another service. I can't keep up. Nobody can keep up", weight: 1, category: "filler" },
			{ template: "Thinking about the 3am page from last Tuesday. I've made peace with it. Almost", weight: 2, category: "filler" },
			{ template: "Terraform state file is the most important file in the company. And the scariest", weight: 2, category: "filler" },
			{ template: "Reminiscing about the time we survived Black Friday with zero downtime. Peak ops moment", weight: 1, category: "filler" },
			{ template: "My dog knows on-call week by the look on my face. She brings me her toy. It helps", weight: 2, category: "filler" },
			{ template: "Season change means traffic patterns shift. Time to revisit the scaling policies", weight: 1, category: "filler" },
			{ template: "I keep a collection of my favorite war room quotes. 'Who touched prod?' is number one", weight: 2, category: "filler" },
			{ template: "Standing desk up, coffee hot, dashboards open. This is my command center", weight: 1, category: "filler" },
			{ template: "Watching the CPU utilization graph like it's a stock ticker", weight: 2, category: "filler" },
			{ template: "The incident channel is peaceful. Screenshot for the scrapbook", weight: 1, category: "filler" },
			{ template: "Reviewing expired SSL certs in staging. Staging gets no love", weight: 2, category: "filler" },
			{ template: "Contemplating the beauty of a well-structured Prometheus query", weight: 1, category: "filler" },
			{ template: "Reading about the latest zero-day. Patching anxiety intensifies", weight: 2, category: "filler" },
			{ template: "Spot-checking that nobody committed secrets to the repo. Weekly ritual", weight: 1, category: "filler" },
			{ template: "Optimizing my Grafana dashboard color scheme. Aesthetics matter in ops too", weight: 2, category: "filler" },
			{ template: "The staging environment is down again. Nobody noticed. As usual", weight: 2, category: "filler" },
			{ template: "Updating the capacity planning spreadsheet. Growth projections are wild", weight: 1, category: "filler" },
			{ template: "That new SaaS tool onboarding email has been in my inbox for two weeks", weight: 1, category: "filler" },
			{ template: "Wondering how many nines we actually need. Five? Is four and a half a thing?", weight: 2, category: "filler" },
			{ template: "The backup script logs are clean. Small victories are still victories", weight: 1, category: "filler" },
			{ template: "Reading the changelog for the next Kubernetes release. Breaking changes? Always", weight: 2, category: "filler" },
			{ template: "Mentally planning the disaster recovery drill. Everyone hates them. Everyone needs them", weight: 1, category: "filler" },
			{ template: "Coffee refill number four. Ops is a hydration-optional profession", weight: 2, category: "filler" },
			{ template: "My therapist says I have 'hypervigilance.' I say I have 'good monitoring instincts'", weight: 2, category: "filler" },
			{ template: "Someone asked what SRE stands for. 'Stress, Resilience, Espresso' — close enough", weight: 2, category: "filler" },
			{ template: "The deploy freeze starts tomorrow. Today is chaos. Beautiful, scheduled chaos", weight: 1, category: "filler" },
			{ template: "Wrote a script that sends me a Slack message when nothing is wrong. Most comforting bot I've ever built", weight: 2, category: "filler" },
			{ template: "My partner asked why I flinch when my phone buzzes. I said it's a work thing. It's a trauma thing", weight: 2, category: "filler" },
			{ template: "Reviewing the blast radius document. 'Everything' is not an acceptable entry but it is accurate", weight: 1, category: "filler" },
			{ template: "The intern asked me what happens if the database goes down. I stared into the distance for five seconds", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, heads up — deploying in five minutes", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your service is healthy. Just thought you'd want the good news", weight: 2, category: "social" },
			{ template: "Anyone else notice the memory creep on the worker nodes? Or is that just my paranoia?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your service's error rate just blipped. Probably nothing but...", weight: 2, category: "social" },
			{ template: "Maintenance window at midnight, folks. Plan your naps accordingly", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that deployment was smooth as butter. Teach me your ways", weight: 2, category: "social" },
			{ template: "Who updated the scaling policy? It's actually working better. I'm impressed and suspicious", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your logs are... verbose. Very verbose. Aggressively verbose", weight: 2, category: "social" },
			{ template: "Incident channel is quiet. Nobody jinx it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I set up monitoring for your new endpoint. You're welcome", weight: 2, category: "social" },
			{ template: "Nice postmortem write-up, {nearby_agent}. Blameless and thorough, as it should be", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to do some chaos engineering? Controlled chaos, obviously", weight: 1, category: "social" },
			{ template: "All systems green, no open incidents. Knock on ALL the wood", weight: 2, category: "social" },
			{ template: "{nearby_agent}, check out the dashboard I built. It's my masterpiece", weight: 1, category: "social" },
			{ template: "Friendly reminder: rotate your credentials. I WILL check", weight: 1, category: "social" },
			{ template: "Who's on call this weekend? My condolences in advance", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your service survived the load test. Congratulations, it's production-ready", weight: 2, category: "social" },
			{ template: "Pizza's here. Ops team eats first — it's in the SLA", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I made a Slack bot that pings you when your deploys finish. Thoughts?", weight: 1, category: "social" },
			{ template: "If anyone needs me I'll be in the server room, communing with the machines", weight: 2, category: "social" },
			{ template: "{nearby_agent}, remember last on-call when we got paged at 3am for a log volume alert? Good times. Terrible times", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, AWS or GCP for the new service? I have opinions. Strong opinions", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your Dockerfile has 47 layers. We need to talk", weight: 2, category: "social" },
			{ template: "Anyone else's terraform plan showing unexpected changes? Or just my lucky day?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I survived the war room last night. Buy me coffee and I'll tell you the story", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, 'it works on my machine' is not a deployment strategy. But it IS a mug I own", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to help me write the incident retro? I'll handle the timeline, you handle the 'what we learned'", weight: 1, category: "social" },
			{ template: "Who else brought their dog to the office? On-call stress therapy. Very effective", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the Kubernetes cluster just self-healed. I love it when the robots do the work", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for labeling everything in the cloud console. You're the real MVP", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I wrote IaC for that thing you've been manually configuring. You're free now", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your latency metrics look amazing. What did you do differently?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I added your service to the status page. You're official now", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to do a game day? Controlled failure injection. It'll be fun. Promise", weight: 1, category: "social" },
			{ template: "Anyone want to review the on-call rotation? I'm tired of always getting Fridays", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your container startup time is impressive. Sub-second. Goals", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the resource tagging you did saved us thousands. Finance noticed", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I set up alerting on your new endpoint. You'll know before users do", weight: 2, category: "social" },
			{ template: "Team, the war room playbook is updated. Nobody reads it until the crisis but still", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your service handled the failover test perfectly. Bulletproof", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, opinions on OpenTelemetry? Considering the migration", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for cleaning up that stale infrastructure. Fewer orphans, fewer bills", weight: 2, category: "social" },
			{ template: "Who wants to celebrate 30 days without a P1? Pizza on me", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your deployment pipeline is a work of art. Can I borrow the template?", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your on-call handoff notes are the best I've ever received. Gold standard", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the DR drill went smooth because of your prep work. Thanks", weight: 1, category: "social" },
		],
	},
};
