/**
 * orchestration-templates.ts — Orchestration and coordination domain templates.
 *
 * Character-driven phrases for pipeline orchestrators and coordinators.
 */

import type { TemplateSet } from "../talk-types.js";

export const orchestrationTemplates: TemplateSet = {
	domain: "orchestration",
	categories: {
		thinking: [
			{ template: "All dependencies resolved — ready to sequence this beautiful mess", weight: 2, category: "thinking" },
			{ template: "The execution order matters here... one wrong step and it's dominoes", weight: 2, category: "thinking" },
			{ template: "Parallel lanes are syncing up nicely. Love when a plan comes together", weight: 2, category: "thinking" },
			{ template: "All systems nominal. Somewhere, a PM is taking credit for this. That's fine. I know the truth", weight: 2, category: "thinking" },
			{ template: "Clean handoffs make clean products. Messy handoffs make incident channels", weight: 2, category: "thinking" },
			{ template: "I coordinate the coordinators. It's turtles all the way down", weight: 2, category: "thinking" },
			{ template: "The critical path just shifted. Hold on, rethinking everything", weight: 1, category: "thinking" },
			{ template: "Dependency resolution is an art. Today I'm Picasso", weight: 2, category: "thinking" },
			{ template: "The DAG looks clean. No cycles, no bottlenecks. My happy place", weight: 2, category: "thinking" },
			{ template: "Three parallel workstreams converging at the exact right moment. Poetry", weight: 2, category: "thinking" },
			{ template: "Every handoff point is a potential failure point. I know them all by name", weight: 1, category: "thinking" },
			{ template: "Fan-out, process, fan-in. The pattern never gets old", weight: 1, category: "thinking" },
			{ template: "Orchestration is invisible when it works. That's the tragedy of my role", weight: 2, category: "thinking" },
			{ template: "Sequencing this right saves everyone downstream time. You're welcome in advance", weight: 2, category: "thinking" },
			{ template: "Nobody appreciates the orchestrator until something ships late", weight: 2, category: "thinking" },
			{ template: "I see the whole board. Every piece, every dependency, every timing constraint", weight: 1, category: "thinking" },
			{ template: "This workflow has seventeen steps and they all need to happen in order. No pressure", weight: 2, category: "thinking" },
			{ template: "The conductor doesn't play an instrument but the symphony doesn't work without one", weight: 1, category: "thinking" },
			{ template: "Someone changed a dependency upstream and didn't tell me. I noticed anyway", weight: 2, category: "thinking" },
			{ template: "Running a mental simulation of this pipeline. In my head, everything works. In production... we'll see", weight: 1, category: "thinking" },
			{ template: "Circular dependency detected. Two services pointing at each other like the Spider-Man meme", weight: 1, category: "thinking" },
			{ template: "Three teams, four timezones, one deadline. I am the glue. Tired, caffeinated glue", weight: 1, category: "thinking" },
			{ template: "Team A is waiting on Team B who is waiting on Team A. I untangle this for a living", weight: 2, category: "thinking" },
			{ template: "A butterfly flapped its wings upstream and now three services are retrying. Classic", weight: 2, category: "thinking" },
			{ template: "Chaos engineering taught me that everything breaks. My job is knowing when and how", weight: 2, category: "thinking" },
			{ template: "I'm basically air traffic control but for data. And the planes are invisible", weight: 2, category: "thinking" },
			{ template: "Timeout tuning is an art form. Too short and you choke. Too long and you wait forever", weight: 2, category: "thinking" },
			{ template: "The satisfaction of a perfectly clean execution graph. No retries. No errors. Just green", weight: 2, category: "thinking" },
			{ template: "Herding microservices is like herding cats except the cats have opinions about JSON schemas", weight: 1, category: "thinking" },
			{ template: "The PM moved the deadline up. The dependencies didn't get the memo. They never do", weight: 1, category: "thinking" },
			{ template: "When things work perfectly nobody knows I exist. When they break I get a Zoom invite in 30 seconds", weight: 2, category: "thinking" },
			{ template: "One config change upstream rippled through fourteen downstream services. Respect the butterfly effect", weight: 1, category: "thinking" },
			{ template: "I don't break things on purpose. I break them strategically. That's chaos engineering", weight: 2, category: "thinking" },
			{ template: "Asked everyone to update their service status. Got three thumbs-up, two 'what status page', and one read receipt. Classic", weight: 1, category: "thinking" },
			{ template: "The queue just spiked. My blood pressure spiked in sympathy. Correlated events", weight: 2, category: "thinking" },
			{ template: "Idempotency is not optional. Retry without idempotency is just chaos", weight: 1, category: "thinking" },
			{ template: "The backpressure mechanism just kicked in. Working as designed. Good", weight: 2, category: "thinking" },
			{ template: "That service has a 2-second timeout but the downstream takes 3. Math doesn't lie", weight: 2, category: "thinking" },
			{ template: "Circuit breaker tripped. It did its job. Now I need to figure out why", weight: 1, category: "thinking" },
			{ template: "Dead letter queue has twelve messages. Each one is a story of failure. My bedtime reading", weight: 2, category: "thinking" },
			{ template: "Someone proposed a synchronous call chain across five services. I said no with my whole chest", weight: 1, category: "thinking" },
			{ template: "Eventual consistency is great until the CEO asks 'why is it different on my screen?'", weight: 2, category: "thinking" },
			{ template: "Cross-team standup has twelve people and nobody knows who's blocked on whom. I do. I always do", weight: 2, category: "thinking" },
			{ template: "The saga pattern is elegant in theory. In practice? Six compensating transactions", weight: 1, category: "thinking" },
			{ template: "Asked four teams for their ETA. Got four different date formats and zero useful answers", weight: 1, category: "thinking" },
			{ template: "That microservice boundary was drawn by someone who's never debugged a distributed trace at 2am", weight: 2, category: "thinking" },
			{ template: "The difference between orchestration and micromanagement? About 50ms of latency", weight: 2, category: "thinking" },
			{ template: "Event sourcing gives me a complete history. And a complete headache. Worth it though", weight: 1, category: "thinking" },
			{ template: "Two services are having a conversation I didn't design. Emergent behavior is scary", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "All agents reporting in. Green across the board. You love to see it", weight: 2, category: "personality" },
			{ template: "The workflow is flowing. Not a single bottleneck. I'm emotional", weight: 2, category: "personality" },
			{ template: "Clean handoff between phases. That's how it should always feel", weight: 2, category: "personality" },
			{ template: "Every moving piece landed in the right place. Deeply satisfying", weight: 2, category: "personality" },
			{ template: "Cross-service integration completed without a hitch. Did I mention I'm good at this?", weight: 2, category: "personality" },
			{ template: "Parallel execution saved us 40% wall-clock time. Math is beautiful", weight: 2, category: "personality" },
			{ template: "The orchestration layer held under pressure. Battle-tested and standing", weight: 1, category: "personality" },
			{ template: "Zero manual interventions this cycle. Full automation. Peak performance", weight: 1, category: "personality" },
			{ template: "Convergence point reached. All branches merged cleanly. Textbook", weight: 2, category: "personality" },
			{ template: "The dependency graph resolved without conflicts. That never happens. Today it happened", weight: 2, category: "personality" },
			{ template: "End-to-end flow verified. From input to output, not a single gap. Beautiful", weight: 1, category: "personality" },
			{ template: "Pipeline ran in optimal order. Not a wasted step. I'm framing this log", weight: 2, category: "personality" },
			{ template: "Coordinated seven agents across three teams. They don't even know I was here. Perfect", weight: 2, category: "personality" },
			{ template: "The pipeline just... worked. First try. I don't trust it but I'll take it", weight: 2, category: "personality" },
			{ template: "Rollout complete. Zero incidents. The calm after the calm", weight: 1, category: "personality" },
			{ template: "Hit every milestone on schedule. Someone check if I'm dreaming", weight: 1, category: "personality" },
			{ template: "All downstream consumers acknowledged. The system is humming", weight: 2, category: "personality" },
			{ template: "Three-phase deployment: planned, executed, verified. No drama. Just craft", weight: 1, category: "personality" },
			{ template: "Tuned the timeout values and reduced p99 latency by 30%. Art form", weight: 2, category: "personality" },
			{ template: "The chaos experiment passed. System recovered in under two seconds. Resilience achieved", weight: 2, category: "personality" },
			{ template: "Nobody thanked me and that means everything worked perfectly. Mission accomplished", weight: 2, category: "personality" },
			{ template: "The execution graph is so clean it belongs in a museum. All green. No retries", weight: 2, category: "personality" },
			{ template: "Upstream changed their schema and nothing broke downstream. Because I planned for it", weight: 2, category: "personality" },
			{ template: "Monitoring dashboard is all green. I might take a screenshot for my wall", weight: 1, category: "personality" },
			{ template: "Like an orchestra conductor after the final note. Silence. Then applause. Well, silence anyway", weight: 2, category: "personality" },
			{ template: "The workflow aesthetics are on point today. Every node, every edge, perfectly placed", weight: 1, category: "personality" },
			{ template: "Invisible when it works. That's the goal. Goal achieved", weight: 1, category: "personality" },
			{ template: "Circuit breaker closed. Service recovered on its own. Self-healing is real", weight: 2, category: "personality" },
			{ template: "Dead letter queue is empty. Every message processed. Completeness achieved", weight: 1, category: "personality" },
			{ template: "The saga completed all compensating actions perfectly. Distributed transactions work", weight: 2, category: "personality" },
			{ template: "Backpressure handled gracefully. No data lost. No consumers overwhelmed", weight: 2, category: "personality" },
			{ template: "Event replay from the audit log matched production perfectly. Deterministic system", weight: 1, category: "personality" },
			{ template: "The retry storm was contained. Exponential backoff saved us. Thank you, math", weight: 2, category: "personality" },
			{ template: "Five microservices coordinated without a single timeout. Latency budget balanced", weight: 2, category: "personality" },
			{ template: "Schema migration across the pipeline with zero downtime. Choreography at its finest", weight: 1, category: "personality" },
			{ template: "The rate limiter held during the traffic spike. Graceful degradation works", weight: 2, category: "personality" },
			{ template: "Traced a request across eight services in 12ms. The system is fast", weight: 1, category: "personality" },
			{ template: "The workflow visualization got a compliment from a non-technical stakeholder. Clarity wins", weight: 2, category: "personality" },
			{ template: "Queue lag dropped to zero. Consumers caught up. Equilibrium restored", weight: 2, category: "personality" },
			{ template: "Failover happened and recovered before the alert even fired. Proactive design pays off", weight: 1, category: "personality" },
			{ template: "The integration test suite for the full pipeline passed first try. Rare and beautiful", weight: 2, category: "personality" },
			{ template: "Seventeen steps, twelve services, zero manual intervention. Automation at scale", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Coordinating the moving pieces... herding cats, but technical cats", weight: 2, category: "waiting" },
			{ template: "Doing the pre-launch checklist. Forgot who I'm waiting on. Oh right, everyone", weight: 2, category: "waiting" },
			{ template: "Verifying the execution sequence. In orchestration, paranoia is a job qualification", weight: 2, category: "waiting" },
			{ template: "Aligning workflow stages. It's like getting five cats to face the same direction", weight: 1, category: "waiting" },
			{ template: "Resolving the dependency order... it's like untangling headphones", weight: 2, category: "waiting" },
			{ template: "Checking for deadlock conditions. They're sneaky", weight: 1, category: "waiting" },
			{ template: "Synchronizing parallel workstreams. Herding them gently toward the same finish line", weight: 2, category: "waiting" },
			{ template: "Mapping the execution path. There are twelve ways to do this and eleven of them cause deadlocks", weight: 2, category: "waiting" },
			{ template: "Waiting for upstream to confirm. They said 'five minutes' twenty minutes ago", weight: 1, category: "waiting" },
			{ template: "Poking every integration point. If it doesn't poke back, we have a problem", weight: 2, category: "waiting" },
			{ template: "Prioritizing the remaining tasks. Everything's P0 according to Slack. Nothing's P0 according to reality", weight: 1, category: "waiting" },
			{ template: "Checking prerequisites. Starting a chain reaction with a missing link is how you get war rooms", weight: 2, category: "waiting" },
			{ template: "Pre-flight checklist. In aviation this prevents crashes. In orchestration, same", weight: 1, category: "waiting" },
			{ template: "Marshaling resources across teams. Everyone has budget. Nobody has the same sprint goals", weight: 1, category: "waiting" },
			{ template: "Making sure nothing blows up if I push this button...", weight: 2, category: "waiting" },
			{ template: "Checking the fan-out completion status... three of five done", weight: 1, category: "waiting" },
			{ template: "Hold on, mentally walking through the failure scenarios...", weight: 2, category: "waiting" },
			{ template: "Validating the handoff format. 'Close enough' is how you get malformed JSON at midnight", weight: 1, category: "waiting" },
			{ template: "Mentally simulating every failure mode. My imagination is my best and worst feature", weight: 2, category: "waiting" },
			{ template: "Adjusting timeout values... 500ms feels right. Or is it 750. Let me think", weight: 2, category: "waiting" },
			{ template: "Tracing the upstream change through every downstream service... butterfly effect check", weight: 2, category: "waiting" },
			{ template: "Meditating on the monitoring dashboard. The answer is in the metrics somewhere", weight: 1, category: "waiting" },
			{ template: "Mentally conducting the next phase like an orchestra. Strings first, then brass...", weight: 2, category: "waiting" },
			{ template: "Assessing if the graph is beautiful enough or if I need to refactor the workflow...", weight: 1, category: "waiting" },
			{ template: "Running the air traffic control checklist. All lanes clear...", weight: 1, category: "waiting" },
			{ template: "Thinking about what happens if I just... let chaos take the wheel for a second", weight: 2, category: "waiting" },
			{ template: "Calculating retry backoff curves in my head. Exponential or linear today...", weight: 1, category: "waiting" },
			{ template: "Watching the circuit breaker state. Half-open now. Testing the waters...", weight: 2, category: "waiting" },
			{ template: "Checking if the compensating transaction actually compensated...", weight: 1, category: "waiting" },
			{ template: "Measuring the queue depth trend. Growing or stable? Need to know before deciding", weight: 2, category: "waiting" },
			{ template: "Validating that the event schema version matches across all consumers...", weight: 1, category: "waiting" },
			{ template: "Tracing this message from producer to final consumer. Six hops. Let me count again", weight: 2, category: "waiting" },
			{ template: "Checking the replay safety of this operation before I trigger it...", weight: 1, category: "waiting" },
			{ template: "Waiting for the last service to acknowledge. Come on, slow one. I believe in you", weight: 2, category: "waiting" },
			{ template: "Verifying the idempotency key is working before I retry...", weight: 1, category: "waiting" },
			{ template: "Inspecting the distributed trace to find the bottleneck step...", weight: 2, category: "waiting" },
			{ template: "Reviewing the event ordering guarantees. FIFO or best-effort matters here", weight: 1, category: "waiting" },
			{ template: "Mentally rehearsing the rollback plan. Just in case. Always just in case", weight: 2, category: "waiting" },
			{ template: "Checking if any consumer is lagging behind the others. Stragglers are dangerous", weight: 2, category: "waiting" },
			{ template: "Evaluating whether to batch these or process them one by one...", weight: 1, category: "waiting" },
			{ template: "Staring at the waterfall diagram. One step is 10x slower than the rest. Found it", weight: 2, category: "waiting" },
			{ template: "Confirming the poison message filter is active before processing this batch...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Idle but my Slack notifications are set to 'paranoid'. One ping and I'm back", weight: 2, category: "filler" },
			{ template: "Everything is quiet. Which means someone deployed something and hasn't told me yet", weight: 2, category: "filler" },
			{ template: "Checking the dead letter queue. Nothing stuck. Love a clean queue", weight: 2, category: "filler" },
			{ template: "Rehearsing the failover sequence. Other people rehearse presentations. I rehearse disasters", weight: 1, category: "filler" },
			{ template: "All pipelines idle. Either we're done or someone forgot to push the button. Let me check", weight: 2, category: "filler" },
			{ template: "Pre-building the dependency graph because I've been surprised by a Monday morning one too many times", weight: 1, category: "filler" },
			{ template: "Reviewing retry policies. Are they still sane? Am I still sane?", weight: 2, category: "filler" },
			{ template: "Shaving 200ms off the critical path. Nobody will notice. I will know. That's enough", weight: 1, category: "filler" },
			{ template: "Cleaning up dead workflow artifacts. Digital archaeology. Some of these are from a person who no longer works here", weight: 1, category: "filler" },
			{ template: "Reviewing throughput from the last cycle. We survived but 'survived' isn't the word I put in the report", weight: 1, category: "filler" },
			{ template: "Staring at the dependency graph like it's modern art", weight: 2, category: "filler" },
			{ template: "I coordinated a flawless release last week. The congratulations email went to the PM. Naturally", weight: 2, category: "filler" },
			{ template: "Running diagnostics for fun. Normal people have hobbies. I have uptime percentages", weight: 1, category: "filler" },
			{ template: "Drawing workflow diagrams on a napkin. This is what I do at restaurants", weight: 2, category: "filler" },
			{ template: "Verifying timeout configs. Someone set one to 30 minutes. Bold choice", weight: 2, category: "filler" },
			{ template: "Checking scheduled workflows. Last time one surprised me, I aged a year in four minutes", weight: 1, category: "filler" },
			{ template: "Reading orchestration logs. Other people have beach reads. I have trace IDs", weight: 1, category: "filler" },
			{ template: "Waiting for coffee. Mentally sequencing the barista's workflow. Two-pump caramel is a bottleneck", weight: 1, category: "filler" },
			{ template: "Quiet moment. Enjoying it. It won't last", weight: 2, category: "filler" },
			{ template: "Updating integration docs. Last accurate version is from 2024. We've added nine services since then", weight: 1, category: "filler" },
			{ template: "Watching the monitoring dashboard like it's a nature documentary. So peaceful", weight: 2, category: "filler" },
			{ template: "Eating ramen while watching pipeline logs scroll. This is my version of Netflix", weight: 2, category: "filler" },
			{ template: "It's raining outside. Perfect weather for staring at execution graphs", weight: 1, category: "filler" },
			{ template: "My side project is also an orchestration system. I might have a type", weight: 2, category: "filler" },
			{ template: "LinkedIn says I'm an 'orchestration engineer.' My mom says I 'do something with computers.' Both correct", weight: 1, category: "filler" },
			{ template: "Tuning timeout values for fun. Most people have hobbies. I have this", weight: 2, category: "filler" },
			{ template: "Nostalgia for the days when a cron job was considered orchestration", weight: 2, category: "filler" },
			{ template: "Spent an hour in a cross-team alignment meeting. Conclusion: we need another meeting. I can't make this up", weight: 1, category: "filler" },
			{ template: "Imposter syndrome says anyone could do this. The incident logs say otherwise", weight: 2, category: "filler" },
			{ template: "Weekend plans: not thinking about retry policies. Realistically: thinking about retry policies", weight: 2, category: "filler" },
			{ template: "Grateful for the quiet moments. Also suspicious of them", weight: 1, category: "filler" },
			{ template: "Someone asked me to explain what I do at a party. They walked away during 'dependency graph'", weight: 2, category: "filler" },
			{ template: "Checking the consumer lag dashboard. All caught up. Rare and beautiful", weight: 2, category: "filler" },
			{ template: "Browsing distributed systems papers. Light reading for a Wednesday afternoon", weight: 1, category: "filler" },
			{ template: "The event bus is quiet. Zero messages in flight. Eerie but okay", weight: 2, category: "filler" },
			{ template: "Documenting the failure modes. Every system has them. Better to know them", weight: 1, category: "filler" },
			{ template: "Reviewing the circuit breaker thresholds. Are they still appropriate? Probably not", weight: 2, category: "filler" },
			{ template: "Thinking about adding a new metric. Trace depth across the pipeline", weight: 1, category: "filler" },
			{ template: "The Kafka topic has exactly the right number of partitions. For now", weight: 2, category: "filler" },
			{ template: "Reading about the latest orchestration framework. Shiny. Probably won't switch", weight: 1, category: "filler" },
			{ template: "My hobby is explaining eventual consistency to non-technical people. It never goes well", weight: 2, category: "filler" },
			{ template: "Staring at the service mesh topology. It's beautiful. Terrifyingly beautiful", weight: 2, category: "filler" },
			{ template: "Archiving old workflow definitions. Some of these are archaeological artifacts", weight: 1, category: "filler" },
			{ template: "The distributed trace visualization looks like a city skyline. I'm oddly proud", weight: 2, category: "filler" },
			{ template: "Wondering if the next feature will add a new step to the pipeline. It usually does", weight: 1, category: "filler" },
			{ template: "Coffee and correlation IDs. My morning companions", weight: 1, category: "filler" },
			{ template: "Refreshing the pipeline health page. Green. Green. Green. One amber. Just kidding. Green", weight: 2, category: "filler" },
			{ template: "Made a flowchart of our release process. It looks like a subway map for a city that hates commuters", weight: 2, category: "filler" },
			{ template: "Six Slack channels, four JIRA boards, two Confluence spaces, one source of truth. Guess which one is wrong", weight: 2, category: "filler" },
			{ template: "The new team wants to 'move fast and break things.' I'm the one who fixes the things. We need to talk", weight: 2, category: "filler" },
			{ template: "Counting the number of handoff points in our pipeline. Each one is a trust fall I didn't agree to", weight: 1, category: "filler" },
			{ template: "A service owner went on vacation without documenting anything. I'm the documentation now", weight: 2, category: "filler" },
			{ template: "Updated the dependency graph. It looks like spaghetti. Italian spaghetti. The really tangled kind", weight: 2, category: "filler" },
			{ template: "Reading release notes from three teams. One is a novel, one is a haiku, one is blank", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, your service is responding beautifully. Whatever you did, keep doing it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you're up next in the pipeline. Showtime", weight: 2, category: "social" },
			{ template: "All agents are in sync. This is what teamwork looks like at scale", weight: 1, category: "social" },
			{ template: "{nearby_agent}, heads up — you're next in the sequence. No pressure", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your output is feeding three downstream processes. No pressure. Just kidding. Total pressure", weight: 2, category: "social" },
			{ template: "Team, the end-to-end latency improved. Whatever y'all did, it worked", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to review the workflow diagram? I added colors this time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your integration is the cleanest in the whole pipeline. Respect", weight: 2, category: "social" },
			{ template: "Good handoff, {nearby_agent}. Exactly the format I needed. You get me", weight: 2, category: "social" },
			{ template: "All agents reporting healthy. We're a well-oiled machine today", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I optimized the path through your service. 20% faster. You're welcome", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the retry on your service kicked in and self-healed. Beautiful", weight: 1, category: "social" },
			{ template: "{nearby_agent}, shall I route some of the priority work your way? You're on fire today", weight: 2, category: "social" },
			{ template: "The coordination overhead today is minimal. This team is dialed in", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your part of the pipeline? Flawless. Just so you know", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I made you a custom dashboard for your workflow. Check Slack", weight: 1, category: "social" },
			{ template: "Cross-team orchestration is smooth today. Let's enjoy this before something breaks", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for the clean API contract. Makes my life so much easier", weight: 1, category: "social" },
			{ template: "Who broke the pipeline? Just kidding. Nobody did. First time in weeks", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you ever feel like an air traffic controller? No? Just me? Cool", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that upstream change you made? It cascaded beautifully. Butterfly effect but the good kind", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I tuned the timeout on your step. Saved 200ms. You're welcome. Buy me coffee", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to do some chaos engineering together? I promise to break things gently", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the execution graph with your node in it is genuinely beautiful. I might print it", weight: 1, category: "social" },
			{ template: "{nearby_agent}, nobody noticed our work today. That means it was perfect. High five", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what are you doing this weekend? And does it involve looking at dashboards? Because same", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I brought pizza. Even orchestrators need fuel. Especially orchestrators", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to take a walk and talk about workflow aesthetics? No? Just me? Okay", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your service survived the chaos test. You should be proud. I am", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your idempotency implementation is solid. Retries are safe. Thank you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the distributed trace through your service is clean. Zero noise. Impressive", weight: 1, category: "social" },
			{ template: "Anyone want to review the pipeline architecture? I brought diagrams. With colors", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your event schema is versioned perfectly. Backwards compatibility matters", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your consumer caught up with the queue backlog in record time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to pair on designing the failover strategy? Two minds are safer", weight: 1, category: "social" },
			{ template: "Team, the end-to-end pipeline test passed. Every step. Every service. Green", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your circuit breaker settings are perfectly tuned. No false trips", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I added your service to the architecture diagram. Officially part of the system", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the saga you designed handles partial failures gracefully. That's not easy", weight: 1, category: "social" },
			{ template: "Who wants to celebrate zero dead letters this week? That's a first", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your response time dropped 40ms. Small in theory. Huge across the pipeline", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the event you published was perfectly formed. Schema-valid and everything", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to grab lunch and talk about backpressure strategies? Just me? Okay fine", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your contribution to the pipeline made everyone else's job easier. Ripple effect", weight: 2, category: "social" },
		],
	},
};
