/**
 * pet-phrases.ts — Pet inner monologue fragments across three voice modes.
 *
 * Voice selection is context-driven:
 *   - Instinct: hungry/tired/thirsty — broken grammar, pure animal brain
 *   - Eloquent: observing agents — dry wit, detached commentary
 *   - Gremlin: bored/playful — chaotic, dramatic overreaction
 */

export const PET_INSTINCT_FRAGMENTS: readonly string[] = [
	"food. FOOD. why empty. sad.",
	"warm spot. mine. do not move.",
	"leg tired. floor good. sleep now.",
	"noise? NOISE. ...nothing. false alarm.",
	"belly full. world good. sleep?",
	"tail. my tail. must catch tail.",
	"door open? DOOR OPEN. go? no. stay. ...go?",
	"small bug. watch bug. bug gone. sad.",
	"scratch? scratch. yes. good scratch.",
	"water. need water. where water.",
	"sun patch. warm. perfect. mine.",
	"human hand. pets? PETS. yes.",
	"cold. too cold. find warm thing.",
	"smell. interesting smell. must investigate.",
	"box. must sit in box. box is life.",
	"bird outside. bird. BIRD. can't reach bird.",
	"lap available. must claim lap.",
	"floor vibrates. scary. hide.",
	"other animal on screen. who. WHO.",
	"yarn. must have yarn. YARN.",
	"sock. suspicious sock. must bite sock.",
	"treat? TREAT. sit. good. treat now.",
	"nap time. or always? yes. always.",
	"rain on window. too loud. don't like.",
	"belly empty. very empty. dying probably.",
	"crinkle sound. CRINKLE. must find crinkle.",
	"ear itchy. scratch ear. still itchy.",
	"squeaky thing. squeak squeak. squeak.",
	"human cry. come close. lick face.",
	"big sleep coming. cannot resist big sleep.",
	"something under blanket. could be foot. attack foot.",
	"paw on warm laptop. good. stay here forever.",
	"door closed. unacceptable. scratch door.",
	"new smell. everything has new smell. must re-investigate all things.",
	"dropped food? check floor. always check floor.",
	"high place. must reach high place. must.",
	"brush. BRUSH. love brush. no wait. hate brush.",
	"human eating. watch human eat. maybe share?",
	"bag rustle. bag rustle means FOOD. investigate.",
	"play? PLAY. run. zoom. play again.",
	"loud noise from nowhere. panic then forget.",
	"cozy pile. I am the cozy pile now.",
	"humans gone. cry. wait. cry more.",
	"humans back. THEY'RE BACK. act calm. can't. too happy.",
	"window open. fresh air good. too many smells. overload.",
	"string. string is enemy. string must die.",
	"wet paw. very offensive. shake paw forever.",
	"cuddle time. force cuddle on unwilling human. success.",
	"loud sneeze. very startled. pretend it was fine.",
	"warm. warm lap. don't move. EVER.",
	"something moved. SOMETHING MOVED. oh. it was me.",
	"human asleep. must wake human. important. why? don't know. IMPORTANT.",
	"outside sounds. must bark at outside sounds. duty. sacred duty.",
	"human typing. click click click. hypnotic. sleep on clicks.",
];

export const PET_ELOQUENT_FRAGMENTS: readonly string[] = [
	"They've been staring at the glowing rectangle for 47 minutes.",
	"Another argument about architecture. Neither can open a door handle.",
	"I observe the ritual of the morning standup. No one is standing.",
	"The tall one types furiously. I suspect it changes nothing.",
	"They call it 'refactoring.' I call it 'rearranging the same kibble.'",
	"One would think a species that invented the laser pointer would be more entertaining.",
	"The concept of 'technical debt' is fascinating. I have emotional debt. It compounds.",
	"They celebrate 'deploys.' I celebrate naps. We are not the same.",
	"The loud one is explaining something. The quiet one is pretending to listen. Masterful.",
	"I have observed 47 standups. Not once has anyone stood.",
	"Another meeting. I shall attend spiritually and absent physically.",
	"The smaller human brings food. The larger one brings chaos.",
	"They worry about 'production.' I worry about the red dot.",
	"Fascinating. They've automated everything except feeding me on time.",
	"One observes the futility of their merge strategy.",
	"They call this 'collaboration.' From my vantage point it resembles organized confusion.",
	"The one with the coffee cup has had four today. I do not judge. I simply note.",
	"Curious. They built systems to track everything and still cannot find their keys.",
	"I have been ignored for six minutes. This will be addressed.",
	"They speak of 'velocity.' I have achieved actual velocity. On the kitchen counter.",
	"Another retrospective. They retrospect often. They change rarely. I respect the commitment.",
	"The concept of 'urgent' appears to shift hourly. Mine does not.",
	"A species capable of inventing the cardboard box and yet so rarely sits inside one.",
	"They've introduced yet another communication channel. This one will also be abandoned.",
	"I find their notion of 'deadlines' charming. Nature has no deadlines. Only hunger.",
	"The one called 'lead' seems to lead primarily toward longer meetings.",
	"I have calculated the optimal nap duration. They have not. This explains much.",
	"They are discussing priorities. I have one priority. It remains unaddressed.",
	"Remarkable — a creature of such ingenuity, undone repeatedly by a closed door.",
	"The celebration of a 'green build' confuses me. Was it ever in danger?",
	"One observes the irony of working on productivity tools while being demonstrably unproductive.",
	"They 'ship features.' I ship hairballs. We all contribute in our own ways.",
	"The notion of 'work-life balance' would be improved by more of one thing: me.",
	"Another afternoon call. I shall drape myself across the keyboard in solidarity.",
	"They track bugs. I am aware of the actual bugs in this building. They have no idea.",
	"The smaller screen. The medium screen. The very large screen. All rectangles. All worshipped.",
	"They moved the furniture again. This explains the 3am zoomies, I suppose.",
	"A creature that schedules joy rather than experiencing it spontaneously. Puzzling.",
	"The human calls it 'focus mode.' I call it 'ignoring me mode.' Semantics.",
	"They are 'syncing.' I am also syncing. To the sun. To the rhythm of the refrigerator.",
	"Another deadline missed. I do not miss deadlines. Dinner is at six. It was not at six.",
	"They say they 'own' this flat. The mortgage disagrees. So do I.",
	"One watches them search for 'best practices.' I have one best practice: napping by noon.",
	"They speak of 'impact.' I had impact. On the fish tank. It was significant.",
	"The new hire seems promising. Smells less stressed than the others.",
	"I have studied their Kanban board. Nothing in 'Done' stays done.",
	"A pipeline, they say. I have a pipeline. Food, belly, floor. Elegant in its simplicity.",
	"They've been in 'crunch' for three weeks. One of us should be crunching something.",
	"The postman is once again confused by my security protocols. Excellent.",
	"I've been watching them debug for 47 minutes. The bug was on line 3.",
	"They call it 'pair programming' but I do most of the work. From this lap.",
	"The test was green. The feature was broken. I could have told them. They didn't ask.",
	"They've rewritten the login page four times this quarter. The door handle works on the first try. Every time.",
	"One cannot help but notice the correlation between 'quick fix' and 'three-hour outage.'",
];

export const PET_GREMLIN_FRAGMENTS: readonly string[] = [
	"CRISIS: the red dot has returned. Deploying counter-measures.",
	"Operation Steal Snack is GO. Repeat: GO.",
	"DEFCON 1: the vacuum has been spotted in the hallway.",
	"INTELLIGENCE: the treat jar has been moved. New coordinates required.",
	"currently atop the forbidden counter. view: excellent. duration: until caught.",
	"BREAKING: suspicious bag noise from kitchen. All units respond.",
	"THREAT LEVEL: ORANGE. Someone sneezed.",
	"RECON: new box detected. Must sit inside immediately.",
	"post-action report: knocked pen off desk. gravity confirmed operational.",
	"OPERATION MIDNIGHT THUNDER: commence zoomies. Carpet phase. Sofa phase. Human phase.",
	"SECURITY BREACH: stranger at the door. Initiating bark protocol. Infinite loop.",
	"sig--l lo--t... just kidding. was napping.",
	"attempted to catch tail. tail remains at large. morale: low.",
	"they think I'm sleeping. I am actually scheming.",
	"SITREP: seven socks acquired. Whereabouts of mates: unknown. Not my problem.",
	"THE FLOOR IS DIFFERENT HERE. it's cold. this changes everything.",
	"yes I knocked it over. yes I'd do it again.",
	"the vacuum cleaner and the doorbell are working together. I'm sure of it.",
	"CODE RED: bathtub is dripping. Standing vigil. Hour four.",
	"EMERGENCY PROTOCOL: the good blanket is unattended. Claiming it. No witnesses.",
	"knocked phone off charger. made eye contact. knocked it again. no regrets.",
	"have been told 'no' fourteen times. I hear the word. I simply disagree.",
	"OPERATION CHAOS: bite ankles, sprint, disappear. Leave no evidence.",
	"sat on the warm laptop. the human seems upset. the human will recover.",
	"BREAKING NEWS: found a crinkle. It crinkles. I am obsessed. Send help.",
	"PRIORITY ONE: the forbidden kitchen counter must be accessed. Attempt 36 initiated.",
	"someone opened a cheese wrapper in the next room. I can be there in two seconds. I will be there in one.",
	"I don't know why I ran just now. but I had to. I absolutely had to.",
	"OPERATION SUNBEAM: located optimal warmth coordinates. Area secured. Do not disturb.",
	"bag left unattended. contents inspected. chapstick neutralized. no witnesses.",
	"it is 3am. the hallway needs running. at full speed. right now. don't ask why.",
	"stole the hair tie. hid it somewhere even I can't find. this is fine.",
	"CRITICAL UPDATE: floor is lava. Furniture only. This is not a drill.",
	"the other pet looked at my food. this is now a diplomatic incident.",
	"vent behind the fridge is warm. this is my home now. I live here.",
	"launched self off sofa at maximum speed. target: nothing. outcome: excellent.",
	"the feather toy has appeared. all previous priorities are cancelled forever.",
	"OPERATION ESCALATION: knocked one thing off table. Human looked. Knocked second thing.",
	"must fit inside box that is clearly too small. my bones will comply or they won't.",
	"found comfortable position. do not require assistance. do not move me. this is permanent.",
	"selected human's face as sleeping location. comfort: mine. theirs: irrelevant.",
	"the new rug is suspicious. it wasn't here yesterday. I will watch it.",
	"thought I heard my name. I did not. but I came anyway. I am here now.",
	"there is a bug on the wall. this is between me and the bug. do not interfere.",
	"the fridge opened. I was across the room. I am now at the fridge. teleportation is real.",
	"I have been grooming for forty minutes. I am not done. I may never be done.",
	"the human laughed at their phone. not at me. this is unacceptable.",
	"something fell in the other room. investigating. ...it was me. I knocked it over earlier.",
	"TACTICAL ASSESSMENT: the dog is asleep. now is the time to steal the bed.",
	"rain outside. refuse to go out. refuse to stay in. refuse everything.",
	"why is the door closed. it was open before. who authorized this.",
	"caught my reflection. magnificent creature. waited for it to move first. it did not.",
	"UNACCEPTABLE: the food bowl is HALF EMPTY. This is a CRISIS.",
	"keyboard? you mean MY bed? excuse you.",
	"ALERT: human is typing. walked across keyboard. their code is now art. you're welcome.",
	"the cursor is moving. THE CURSOR IS MOVING. this is prey. this is MINE.",
	"CLASSIFIED REPORT: sat on the deploy button. things happened. not my problem.",
];
