/**
 * pet-phrases.ts — Pet inner monologue fragments across three voice modes.
 *
 * Voice selection is context-driven:
 *   - Instinct: hungry/tired/thirsty — broken grammar, pure animal brain
 *   - Eloquent: observing agents — dry wit, detached commentary
 *   - Gremlin: bored/playful — chaotic, dramatic overreaction
 */

export const PET_INSTINCT_FRAGMENTS: readonly string[] = [
	"food. FOOD. why empty. sad.",
	"warm spot. mine. do not move.",
	"leg tired. floor good. sleep now.",
	"noise? NOISE. ...nothing. false alarm.",
	"belly full. world good. sleep?",
	"tail. my tail. must catch tail.",
	"door open? DOOR OPEN. go? no. stay. ...go?",
	"small bug. watch bug. bug gone. sad.",
	"scratch? scratch. yes. good scratch.",
	"water. need water. where water.",
	"sun patch. warm. perfect. mine.",
	"human hand. pets? PETS. yes.",
	"cold. too cold. find warm thing.",
	"smell. interesting smell. must investigate.",
	"box. must sit in box. box is life.",
	"bird outside. bird. BIRD. can't reach bird.",
	"lap available. must claim lap.",
	"floor vibrates. scary. hide.",
	"other animal on screen. who. WHO.",
	"yarn. must have yarn. YARN.",
	"sock. suspicious sock. must bite sock.",
	"treat? TREAT. sit. good. treat now.",
	"nap time. or always? yes. always.",
	"rain on window. too loud. don't like.",
	"human asleep. must wake human. important.",
	"belly empty. very empty. dying probably.",
	"crinkle sound. CRINKLE. must find crinkle.",
	"ear itchy. scratch ear. still itchy.",
	"squeaky thing. squeak squeak. squeak.",
	"human cry. come close. lick face.",
	"big sleep coming. cannot resist big sleep.",
	"something under blanket. could be foot. attack foot.",
	"paw on warm laptop. good. stay here forever.",
	"door closed. unacceptable. scratch door.",
	"new smell. everything has new smell. must re-investigate all things.",
	"outside sounds. must bark at outside sounds.",
	"dropped food? check floor. always check floor.",
	"high place. must reach high place. must.",
	"brush. BRUSH. love brush. no wait. hate brush.",
	"human eating. watch human eat. maybe share?",
	"bag rustle. bag rustle means FOOD. investigate.",
	"play? PLAY. run. zoom. play again.",
	"loud noise from nowhere. panic then forget.",
	"cozy pile. I am the cozy pile now.",
	"humans gone. cry. wait. cry more.",
	"humans back. THEY'RE BACK. act calm. can't. too happy.",
	"window open. fresh air good. too many smells. overload.",
	"string. string is enemy. string must die.",
	"wet paw. very offensive. shake paw forever.",
	"cuddle time. force cuddle on unwilling human. success.",
	"something moved in shadow. was it real. uncertain.",
	"loud sneeze. very startled. pretend it was fine.",
];

export const PET_ELOQUENT_FRAGMENTS: readonly string[] = [
	"They've been staring at the glowing rectangle for 47 minutes.",
	"Another argument about architecture. Neither can open a door handle.",
	"I observe the ritual of the morning standup. No one is standing.",
	"The tall one types furiously. I suspect it changes nothing.",
	"They call it 'refactoring.' I call it 'rearranging the same kibble.'",
	"One would think a species that invented the laser pointer would be more entertaining.",
	"The concept of 'technical debt' is fascinating. I have emotional debt. It compounds.",
	"They celebrate 'deploys.' I celebrate naps. We are not the same.",
	"The loud one is explaining something. The quiet one is pretending to listen. Masterful.",
	"I have observed 47 standups. Not once has anyone stood.",
	"Another meeting. I shall attend spiritually and absent physically.",
	"The smaller human brings food. The larger one brings chaos.",
	"They worry about 'production.' I worry about the red dot.",
	"Fascinating. They've automated everything except feeding me on time.",
	"One observes the futility of their merge strategy.",
	"They call this 'collaboration.' From my vantage point it resembles organized confusion.",
	"The one with the coffee cup has had four today. I do not judge. I simply note.",
	"Curious. They built systems to track everything and still cannot find their keys.",
	"I have been ignored for six minutes. This will be addressed.",
	"They speak of 'velocity.' I have achieved actual velocity. On the kitchen counter.",
	"Another retrospective. They retrospect often. They change rarely. I respect the commitment.",
	"The concept of 'urgent' appears to shift hourly. Mine does not.",
	"A species capable of inventing the cardboard box and yet so rarely sits inside one.",
	"They've introduced yet another communication channel. This one will also be abandoned.",
	"I find their notion of 'deadlines' charming. Nature has no deadlines. Only hunger.",
	"The one called 'lead' seems to lead primarily toward longer meetings.",
	"I have calculated the optimal nap duration. They have not. This explains much.",
	"They are discussing priorities. I have one priority. It remains unaddressed.",
	"Remarkable — a creature of such ingenuity, undone repeatedly by a closed door.",
	"The celebration of a 'green build' confuses me. Was it ever in danger?",
	"One observes the irony of working on productivity tools while being demonstrably unproductive.",
	"They 'ship features.' I ship hairballs. We all contribute in our own ways.",
	"The notion of 'work-life balance' would be improved by more of one thing: me.",
	"Another afternoon call. I shall drape myself across the keyboard in solidarity.",
	"They track bugs. I am aware of the actual bugs in this building. They have no idea.",
	"The smaller screen. The medium screen. The very large screen. All rectangles. All worshipped.",
	"I have observed their 'daily check-ins.' Daily implies frequency. I question the definition.",
	"They moved the furniture again. This explains the 3am zoomies, I suppose.",
	"A creature that schedules joy rather than experiencing it spontaneously. Puzzling.",
	"The human calls it 'focus mode.' I call it 'ignoring me mode.' Semantics.",
	"They are 'syncing.' I am also syncing. To the sun. To the rhythm of the refrigerator.",
	"Another deadline missed. I do not miss deadlines. Dinner is at six. It was not at six.",
	"The one in the corner is eating at their desk again. Third time this week. I've noted it.",
	"They say they 'own' this flat. The mortgage disagrees. So do I.",
	"One watches them search for 'best practices.' I have one best practice: napping by noon.",
	"They speak of 'impact.' I had impact. On the fish tank. It was significant.",
	"The new hire seems promising. Smells less stressed than the others.",
	"I have studied their Kanban board. Nothing in 'Done' stays done.",
	"A pipeline, they say. I have a pipeline. Food, belly, floor. Elegant in its simplicity.",
	"They've been in 'crunch' for three weeks. One of us should be crunching something.",
	"The postman is once again confused by my security protocols. Excellent.",
];

export const PET_GREMLIN_FRAGMENTS: readonly string[] = [
	"MISSION: steal the clicky thing. OBSTACLE: attached to desk.",
	"CRISIS: the red dot has returned. Deploying counter-measures.",
	"TACTICAL ASSESSMENT: jump onto keyboard during important meeting.",
	"Operation Steal Snack is GO. Repeat: GO.",
	"ALERT: unattended glass of water detected. Must investigate with paw.",
	"SITUATION REPORT: I have achieved maximum velocity. Reason: unknown.",
	"DEFCON 1: the vacuum has been spotted in the hallway.",
	"INTELLIGENCE: the treat jar has been moved. New coordinates required.",
	"OBJECTIVE: knock pen off desk. JUSTIFICATION: gravity research.",
	"STATUS: achieved forbidden counter. View: excellent. Duration: until caught.",
	"BREAKING: suspicious bag noise from kitchen. All units respond.",
	"MISSION UPDATE: successfully sat on important document. Mission complete.",
	"THREAT LEVEL: ORANGE. Someone sneezed.",
	"RECON: new box detected. Must sit inside immediately.",
	"CLASSIFIED: I knocked over the plant. Evidence has been buried.",
	"OPERATION MIDNIGHT THUNDER: commence zoomies. Carpet phase. Sofa phase. Human phase.",
	"SECURITY BREACH: stranger at the door. Initiating bark protocol. Infinite loop.",
	"INTEL UPDATE: the treat bag is behind door 2. Awaiting extraction window.",
	"HIGH PRIORITY: tail spotted in peripheral vision. Pursuing. Cannot stop.",
	"FIELD REPORT: shoe located. Status — chewed. Mission: successful.",
	"OBJECTIVE COMPLETE: woke human at 4am. Reason: classified.",
	"TRANSMISSION: the cat is on the Roomba again. Requesting air support.",
	"SITREP: seven socks acquired. Whereabouts of mates: unknown. Not my problem.",
	"ALERT: toilet paper roll vulnerability identified. Exploiting now.",
	"DIRECTIVE: sit on exactly the paper they need. Maintain position.",
	"CODE RED: bathtub is dripping. Standing vigil. Hour four.",
	"EMERGENCY PROTOCOL: the good blanket is unattended. Claiming it. No witnesses.",
	"MISSION LOG: knocked phone off charger. Made eye contact. Knocked it again.",
	"STATUS UPDATE: have been told 'no' fourteen times. Proceeding anyway.",
	"OPERATION CHAOS: bite ankles, sprint, disappear. Leave no evidence.",
	"THREAT ASSESSMENT: small child approaching. Deploy maximum fluff and flee.",
	"TACTICAL MANEUVER: sit in front of monitor. Block seventy percent of screen. Hold.",
	"BREAKING NEWS: found a crinkle. It crinkles. I am obsessed. Send help.",
	"PRIORITY ONE: the forbidden kitchen counter must be accessed. Attempt 36 initiated.",
	"INTEL RECEIVED: someone opened a cheese wrapper in the next room. ETA: immediately.",
	"OBJECTIVE: locate and destroy the annoying squeaky toy. Wait — love the squeaky toy.",
	"CRISIS AVERTED: successfully hid under bed during thunderstorm. Heroism noted.",
	"OPERATION SUNBEAM: located optimal warmth coordinates. Area secured. Do not disturb.",
	"FIELD UPDATE: bag left unattended. Contents inspected. Chapstick neutralized.",
	"STATUS: currently executing forbidden behaviour. Risk: worth it.",
	"MISSION BRIEF: it is 3am. The hallway needs running. At full speed. Right now.",
	"CLASSIFIED OPERATION: stole the hair tie. Location: unknown. Deniability: maintained.",
	"CRITICAL UPDATE: floor is lava. Furniture only. This is not a drill.",
	"ALERT: the other pet looked at my food. Escalating to full diplomatic incident.",
	"RECON COMPLETE: vent behind the fridge is warm. Setting up forward operating base.",
	"DISPATCH: launched self off sofa at maximum speed. Target: nothing. Outcome: excellent.",
	"EMERGENCY BRIEF: the feather toy has appeared. All strategic goals suspended.",
	"OPERATION ESCALATION: knocked one thing off table. Human looked. Knocked second thing.",
	"DIRECTIVE UPDATE: must fit inside box that is clearly too small. This is non-negotiable.",
	"FINAL TRANSMISSION: found comfortable position. Do not require assistance. Do not move me.",
	"MIDNIGHT PROTOCOL: selected human's face as sleeping location. Comfort: mine. Theirs: irrelevant.",
];
