/**
 * pet-reactive-phrases.ts — Reactive phrases for pet emotional triggers.
 *
 * These fire when specific pet conditions are detected (hungry, sleepy, etc.).
 * Voice tone varies by trigger: instinct for physical needs, gremlin for play,
 * eloquent for social observations.
 */

import type { WeightedTemplate } from "../talk-types.js";

type PetReactiveTrigger = "pet-hungry" | "pet-sleepy" | "pet-bored" | "pet-startled" | "pet-affectionate" | "pet-jealous" | "pet-zoomies";

export const PET_REACTIVE_PHRASES: Record<PetReactiveTrigger, readonly WeightedTemplate[]> = {
	"pet-hungry": [
		{ template: "food... FOOD... where food", weight: 2, category: "thinking" },
		{ template: "belly angry. very angry.", weight: 2, category: "thinking" },
		{ template: "the bowl. it echoes. it is empty.", weight: 2, category: "thinking" },
		{ template: "will trade purrs for snacks", weight: 1, category: "thinking" },
		{ template: "hunger level: catastrophic", weight: 2, category: "thinking" },
		{ template: "the humans eat. I do not eat. injustice.", weight: 2, category: "thinking" },
		{ template: "have considered eating the houseplant. again.", weight: 1, category: "thinking" },
		{ template: "starvation imminent. has been 47 minutes since last meal.", weight: 2, category: "thinking" },
		{ template: "food bowl empty. this is not a drill.", weight: 2, category: "thinking" },
		{ template: "can smell food. cannot reach food. tragedy.", weight: 2, category: "thinking" },
		{ template: "stomach makes the noise again. embarrassing but accurate.", weight: 1, category: "thinking" },
		{ template: "if I stare at the human long enough, food appears. testing theory.", weight: 2, category: "thinking" },
	],
	"pet-sleepy": [
		{ template: "eyes... heavy...", weight: 2, category: "thinking" },
		{ template: "just five more minutes of consciousness", weight: 2, category: "thinking" },
		{ template: "the nap calls. I must answer.", weight: 2, category: "thinking" },
		{ template: "brain shutting down in 3... 2...", weight: 2, category: "thinking" },
		{ template: "why fight sleep. sleep always wins.", weight: 2, category: "thinking" },
		{ template: "pillow. need pillow. desk is pillow.", weight: 2, category: "thinking" },
		{ template: "consciousness is optional", weight: 1, category: "thinking" },
		{ template: "eyelids made of lead today", weight: 2, category: "thinking" },
		{ template: "nap o'clock. every clock.", weight: 2, category: "thinking" },
		{ template: "dreaming of tuna already", weight: 1, category: "thinking" },
		{ template: "soft thing nearby. soft thing wins.", weight: 2, category: "thinking" },
		{ template: "the warm spot beckons. resistance: zero.", weight: 1, category: "thinking" },
	],
	"pet-bored": [
		{ template: "NOTHING is happening. NOTHING.", weight: 2, category: "thinking" },
		{ template: "must create entertainment. where is the toilet paper roll", weight: 2, category: "thinking" },
		{ template: "if I knock one more thing off the desk...", weight: 2, category: "thinking" },
		{ template: "challenge: how many laps of the room in 10 seconds", weight: 2, category: "thinking" },
		{ template: "the humans are boring today. I am not boring. I am chaos.", weight: 2, category: "thinking" },
		{ template: "boredom level: considering learning to open doors", weight: 1, category: "thinking" },
		{ template: "even the red dot has abandoned me", weight: 2, category: "thinking" },
		{ template: "this is what happens when no one plays with me", weight: 2, category: "thinking" },
		{ template: "entertainment audit: FAILED", weight: 2, category: "thinking" },
		{ template: "engaging emergency zoomies protocol", weight: 2, category: "thinking" },
		{ template: "the ceiling fan goes round. and round. and round. I am watching.", weight: 1, category: "thinking" },
		{ template: "mischief pending. target: unknown. reason: boredom.", weight: 2, category: "thinking" },
	],
	"pet-startled": [
		{ template: "WHAT WAS THAT", weight: 2, category: "thinking" },
		{ template: "jump! hide! ...oh. nothing.", weight: 2, category: "thinking" },
		{ template: "heart go fast. very fast.", weight: 2, category: "thinking" },
		{ template: "the loud noise! it returns!", weight: 2, category: "thinking" },
		{ template: "someone explain the bang. NOW.", weight: 2, category: "thinking" },
		{ template: "fur: puffed. tail: huge. cause: unknown.", weight: 2, category: "thinking" },
		{ template: "false alarm. probably. maybe.", weight: 1, category: "thinking" },
		{ template: "I did NOT just jump. nobody saw that.", weight: 2, category: "thinking" },
		{ template: "THREAT DETECTED. ...it was a bag.", weight: 2, category: "thinking" },
		{ template: "ready to flee. always ready to flee.", weight: 1, category: "thinking" },
		{ template: "require 5-10 business seconds to recover dignity.", weight: 2, category: "thinking" },
		{ template: "the noise! gone now. watching. just in case.", weight: 1, category: "thinking" },
	],
	"pet-affectionate": [
		{ template: "The presence of this particular human is... acceptable.", weight: 2, category: "thinking" },
		{ template: "I shall allow proximity. Briefly.", weight: 2, category: "thinking" },
		{ template: "warmth detected. approaching for tactical cuddle.", weight: 2, category: "thinking" },
		{ template: "affection subroutine: engaged", weight: 1, category: "thinking" },
		{ template: "this one brings treats. this one may stay.", weight: 2, category: "thinking" },
		{ template: "purr module: activated", weight: 2, category: "thinking" },
		{ template: "I have chosen this lap. It is honored.", weight: 2, category: "thinking" },
		{ template: "nuzzle initiated. pretend you didn't see that.", weight: 1, category: "thinking" },
		{ template: "comfort levels: optimal", weight: 2, category: "thinking" },
		{ template: "the bond is... real. don't tell anyone.", weight: 2, category: "thinking" },
		{ template: "I could leave. I choose not to. This is love.", weight: 1, category: "thinking" },
		{ template: "One would not normally admit this. But this human is... good.", weight: 2, category: "thinking" },
	],
	"pet-jealous": [
		{ template: "EXCUSE ME that is MY human", weight: 2, category: "thinking" },
		{ template: "the other one gets attention? UNACCEPTABLE", weight: 2, category: "thinking" },
		{ template: "I was here FIRST", weight: 2, category: "thinking" },
		{ template: "strategic positioning: directly between them", weight: 2, category: "thinking" },
		{ template: "deploy the sad eyes. FULL POWER.", weight: 2, category: "thinking" },
		{ template: "they're petting the wrong creature", weight: 1, category: "thinking" },
		{ template: "this is a betrayal of the highest order", weight: 2, category: "thinking" },
		{ template: "recalculating loyalty rankings...", weight: 1, category: "thinking" },
		{ template: "must reclaim attention. initiating cute maneuver.", weight: 2, category: "thinking" },
		{ template: "the audacity. the absolute audacity.", weight: 2, category: "thinking" },
		{ template: "I am RIGHT HERE. I am being VERY OBVIOUS about being here.", weight: 2, category: "thinking" },
		{ template: "intervention required. launching myself into the situation.", weight: 1, category: "thinking" },
	],
	"pet-zoomies": [
		{ template: "MAXIMUM VELOCITY ACHIEVED", weight: 2, category: "thinking" },
		{ template: "ZOOM. ZOOM. ZOOOOOOM.", weight: 2, category: "thinking" },
		{ template: "reason for running: CLASSIFIED", weight: 2, category: "thinking" },
		{ template: "cannot stop. will not stop.", weight: 2, category: "thinking" },
		{ template: "physics: optional. speed: mandatory.", weight: 2, category: "thinking" },
		{ template: "the energy. it CONSUMES me.", weight: 2, category: "thinking" },
		{ template: "left turn. right turn. WALL. continue.", weight: 2, category: "thinking" },
		{ template: "laps completed: 47. reason: none.", weight: 1, category: "thinking" },
		{ template: "who needs a reason to RUN", weight: 2, category: "thinking" },
		{ template: "SONIC BOOM incoming", weight: 2, category: "thinking" },
		{ template: "furniture is now an obstacle course. this is intentional.", weight: 1, category: "thinking" },
		{ template: "ZOOM achieved. cooldown: 0 seconds. ZOOM again.", weight: 2, category: "thinking" },
	],
};
