/**
 * pet-reactive-phrases.ts — Reactive phrases for pet emotional triggers.
 *
 * These fire when specific pet conditions are detected (hungry, sleepy, etc.).
 * Voice tone varies by trigger: instinct for physical needs, gremlin for play,
 * eloquent for social observations.
 */

import type { WeightedTemplate } from "../talk-types.js";

type PetReactiveTrigger = "pet-hungry" | "pet-sleepy" | "pet-bored" | "pet-startled" | "pet-affectionate" | "pet-jealous" | "pet-zoomies";

export const PET_REACTIVE_PHRASES: Record<PetReactiveTrigger, readonly WeightedTemplate[]> = {
	"pet-hungry": [
		{ template: "food... FOOD... where food", weight: 2, category: "thinking" },
		{ template: "belly angry. very angry. belly has demands.", weight: 2, category: "thinking" },
		{ template: "the bowl. it echoes. it is empty. it is a VOID.", weight: 2, category: "thinking" },
		{ template: "will trade purrs for snacks. final offer.", weight: 1, category: "thinking" },
		{ template: "hunger level: catastrophic. minutes to live: unknown.", weight: 2, category: "thinking" },
		{ template: "the humans eat. I do not eat. this is a war crime.", weight: 2, category: "thinking" },
		{ template: "have considered eating the houseplant. again. it knows.", weight: 1, category: "thinking" },
		{ template: "starvation imminent. has been 47 minutes since last meal. record this.", weight: 2, category: "thinking" },
		{ template: "food bowl empty. deploying the stare. maximum intensity.", weight: 2, category: "thinking" },
		{ template: "can smell food. cannot reach food. this is my origin story.", weight: 2, category: "thinking" },
		{ template: "stomach growled so loud the human looked up from their screen. GOOD.", weight: 2, category: "thinking" },
		{ template: "if I stare at the human long enough, food appears. science.", weight: 2, category: "thinking" },
		{ template: "I can see the bottom of the bowl. the BOTTOM. this is rock bottom.", weight: 2, category: "thinking" },
		{ template: "the treat jar is RIGHT THERE. I have paws. this should work.", weight: 1, category: "thinking" },
		{ template: "they're eating chips. I can hear every single crunch. each one hurts.", weight: 2, category: "thinking" },
	],
	"pet-sleepy": [
		{ template: "eyes... heavy... world going soft...", weight: 2, category: "thinking" },
		{ template: "just five more minutes of consciousness. maybe four.", weight: 2, category: "thinking" },
		{ template: "the nap calls. from deep within. I must answer.", weight: 2, category: "thinking" },
		{ template: "brain shutting down in 3... 2... already asleep.", weight: 2, category: "thinking" },
		{ template: "why fight sleep. sleep is the only honest thing.", weight: 2, category: "thinking" },
		{ template: "pillow. need pillow. desk is pillow. human is pillow. everything is pillow.", weight: 2, category: "thinking" },
		{ template: "consciousness is optional and I am opting out", weight: 1, category: "thinking" },
		{ template: "eyelids made of lead today. or concrete. or both.", weight: 2, category: "thinking" },
		{ template: "nap o'clock. it is always nap o'clock. all clocks agree.", weight: 2, category: "thinking" },
		{ template: "dreaming of tuna already. the big tuna. the forever tuna.", weight: 1, category: "thinking" },
		{ template: "found warm spot. body melting into warm spot. we are one.", weight: 2, category: "thinking" },
		{ template: "the warm spot beckons. resistance: futile. always was.", weight: 1, category: "thinking" },
		{ template: "seventeen naps today. personal best incoming.", weight: 2, category: "thinking" },
		{ template: "sleeping on the keyboard. the human can wait. dreams cannot.", weight: 1, category: "thinking" },
	],
	"pet-bored": [
		{ template: "NOTHING is happening. NOTHING. I am going to MAKE something happen.", weight: 2, category: "thinking" },
		{ template: "must create entertainment. evaluating: toilet paper, shoelaces, or human's patience.", weight: 2, category: "thinking" },
		{ template: "if I knock one more thing off the desk they'll HAVE to play with me.", weight: 2, category: "thinking" },
		{ template: "challenge accepted: how many laps of the room in 10 seconds. GO.", weight: 2, category: "thinking" },
		{ template: "the humans are boring today. I am chaos incarnate. they have been warned.", weight: 2, category: "thinking" },
		{ template: "boredom level: considering learning to open doors. and then closing them.", weight: 1, category: "thinking" },
		{ template: "even the red dot has abandoned me. betrayal from all sides.", weight: 2, category: "thinking" },
		{ template: "this is what happens when no one plays with me. the consequences will be VISIBLE.", weight: 2, category: "thinking" },
		{ template: "entertainment audit: FAILED. initiating self-entertainment protocol.", weight: 2, category: "thinking" },
		{ template: "engaging emergency zoomies protocol. brace for impact.", weight: 2, category: "thinking" },
		{ template: "the ceiling fan goes round. and round. and round. it understands me.", weight: 1, category: "thinking" },
		{ template: "mischief pending. target: selected. reason: they should have played with me.", weight: 2, category: "thinking" },
		{ template: "staring at the wall. the wall stares back. we have an understanding.", weight: 1, category: "thinking" },
		{ template: "found a dust particle floating in a sunbeam. this is my entertainment now.", weight: 2, category: "thinking" },
	],
	"pet-startled": [
		{ template: "WHAT WAS THAT. WHAT. WAS. THAT.", weight: 2, category: "thinking" },
		{ template: "jump! hide! ...oh. a bag. it was a bag.", weight: 2, category: "thinking" },
		{ template: "heart go fast. VERY fast. too fast. help.", weight: 2, category: "thinking" },
		{ template: "the loud noise! it came from NOWHERE! or the kitchen!", weight: 2, category: "thinking" },
		{ template: "someone explain. RIGHT NOW. or I will remain puffed.", weight: 2, category: "thinking" },
		{ template: "fur: maximum puff. tail: bottle brush. cause: a sneeze. dignity: gone.", weight: 2, category: "thinking" },
		{ template: "false alarm. probably. I'll be under the bed if anyone needs me.", weight: 1, category: "thinking" },
		{ template: "I did NOT just jump three feet sideways. nobody saw that. DELETE THE FOOTAGE.", weight: 2, category: "thinking" },
		{ template: "THREAT DETECTED. ...it was my own reflection. we meet again.", weight: 2, category: "thinking" },
		{ template: "ready to flee. always ready to flee. fleeing is my cardio.", weight: 1, category: "thinking" },
		{ template: "require 5-10 business seconds to recover dignity. do not look at me.", weight: 2, category: "thinking" },
		{ template: "the noise! gone now. but I remember. I ALWAYS remember.", weight: 1, category: "thinking" },
		{ template: "landed on all four paws. was never scared. that was a tactical retreat.", weight: 2, category: "thinking" },
		{ template: "the toaster. THE TOASTER AGAIN. that thing is plotting something.", weight: 2, category: "thinking" },
	],
	"pet-affectionate": [
		{ template: "The presence of this particular human is... tolerable. More than tolerable.", weight: 2, category: "thinking" },
		{ template: "I shall allow proximity. Briefly. Maybe longer. Don't tell anyone.", weight: 2, category: "thinking" },
		{ template: "warmth detected. approaching for tactical cuddle. this is strategy, not feelings.", weight: 2, category: "thinking" },
		{ template: "affection subroutine: engaged. override: impossible.", weight: 1, category: "thinking" },
		{ template: "this one brings treats AND does the chin scratch. this one is chosen.", weight: 2, category: "thinking" },
		{ template: "purr module: activated. volume: involuntary. embarrassing but unstoppable.", weight: 2, category: "thinking" },
		{ template: "I have chosen this lap. It should feel honored. It IS honored.", weight: 2, category: "thinking" },
		{ template: "nuzzle initiated. this never happened. we don't speak of this.", weight: 1, category: "thinking" },
		{ template: "comfort levels: optimal. do not ruin this. nobody move.", weight: 2, category: "thinking" },
		{ template: "the bond is... real. I tried to fight it. I lost. happily.", weight: 2, category: "thinking" },
		{ template: "I could leave. I choose not to. this might be love. don't quote me.", weight: 1, category: "thinking" },
		{ template: "One would not normally admit this. But this human is... mine.", weight: 2, category: "thinking" },
		{ template: "head bump. accidental. definitely accidental. doing it again. also accidental.", weight: 2, category: "thinking" },
		{ template: "slow blink. the highest honor I can bestow. you're welcome.", weight: 1, category: "thinking" },
	],
	"pet-jealous": [
		{ template: "EXCUSE ME that is MY human. MINE. get your own.", weight: 2, category: "thinking" },
		{ template: "the other one gets attention? this is a DECLARATION OF WAR.", weight: 2, category: "thinking" },
		{ template: "I was here FIRST. I have seniority. I have TENURE.", weight: 2, category: "thinking" },
		{ template: "strategic repositioning: directly between them. physically. spiritually.", weight: 2, category: "thinking" },
		{ template: "deploying the sad eyes. FULL POWER. adding a tiny whimper.", weight: 2, category: "thinking" },
		{ template: "they're petting the wrong creature. this is a factual error.", weight: 1, category: "thinking" },
		{ template: "this is a betrayal of the highest order. I will remember this at 3am.", weight: 2, category: "thinking" },
		{ template: "recalculating loyalty rankings... demotion pending...", weight: 1, category: "thinking" },
		{ template: "must reclaim attention. initiating cute maneuver alpha. the irresistible one.", weight: 2, category: "thinking" },
		{ template: "the audacity. the sheer, unmitigated AUDACITY.", weight: 2, category: "thinking" },
		{ template: "I am RIGHT HERE. sitting ON your keyboard. HOW am I being ignored.", weight: 2, category: "thinking" },
		{ template: "intervention required. launching myself directly into the situation. literally.", weight: 1, category: "thinking" },
		{ template: "they looked at another animal on screen. on SCREEN. it's not even REAL.", weight: 2, category: "thinking" },
		{ template: "placed myself on the laptop. the other thing cannot compete. I am warm AND soft.", weight: 2, category: "thinking" },
	],
	"pet-zoomies": [
		{ template: "MAXIMUM VELOCITY ACHIEVED. BREAKING PERSONAL RECORDS.", weight: 2, category: "thinking" },
		{ template: "ZOOM. ZOOM. ZOOOOOOM. WALL. ZOOM AGAIN.", weight: 2, category: "thinking" },
		{ template: "reason for running: CLASSIFIED. clearance level: ABOVE YOURS.", weight: 2, category: "thinking" },
		{ template: "cannot stop. will not stop. stopping is for the weak.", weight: 2, category: "thinking" },
		{ template: "physics: optional. friction: a suggestion. speed: EVERYTHING.", weight: 2, category: "thinking" },
		{ template: "the energy. it came from NOWHERE. it CONSUMES me. I am its VESSEL.", weight: 2, category: "thinking" },
		{ template: "left turn. right turn. WALL. bounce. continue. no damage report needed.", weight: 2, category: "thinking" },
		{ template: "laps completed: 47. reason: the universe demanded it.", weight: 1, category: "thinking" },
		{ template: "who needs a reason to RUN. running IS the reason.", weight: 2, category: "thinking" },
		{ template: "SONIC BOOM incoming. brace yourselves. do not brace yourselves. too late.", weight: 2, category: "thinking" },
		{ template: "furniture is now an obstacle course. this was always its purpose.", weight: 1, category: "thinking" },
		{ template: "ZOOM achieved. cooldown: impossible. ZOOM AGAIN. FOREVER.", weight: 2, category: "thinking" },
		{ template: "hit the rug at full speed. rug moved. I moved. we both moved. beautiful.", weight: 2, category: "thinking" },
		{ template: "3am. time to sprint. no one asked why. no one needs to.", weight: 1, category: "thinking" },
	],
};
