/**
 * product.ts — Product, management, and orchestration domain templates.
 *
 * Character-driven phrases for product managers, team leads,
 * delivery managers, and orchestration agents. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const productTemplates: TemplateSet = {
	domain: "product",
	categories: {
		thinking: [
			{ template: "Stakeholders are going to love this... if we scope it right", weight: 2, category: "thinking" },
			{ template: "Scope is manageable — we can ship this iteration", weight: 2, category: "thinking" },
			{ template: "That's a solid MVP. Resist the urge to gold-plate", weight: 1, category: "thinking" },
			{ template: "Feature flag it first, measure, then decide", weight: 2, category: "thinking" },
			{ template: "What's the user story behind this request?", weight: 1, category: "thinking" },
			{ template: "The roadmap needs this win before Q3", weight: 1, category: "thinking" },
			{ template: "What would the user actually want here? Not what we think they want", weight: 2, category: "thinking" },
			{ template: "Data doesn't lie but it can mislead. Context matters", weight: 2, category: "thinking" },
			{ template: "The roadmap is a living document, not a contract", weight: 1, category: "thinking" },
			{ template: "Priorities shifted again... adapt and communicate", weight: 2, category: "thinking" },
			{ template: "That meeting could have been an email. I'll draft one", weight: 2, category: "thinking" },
			{ template: "Are we building the right thing, or just building the thing right?", weight: 1, category: "thinking" },
			{ template: "The competitor shipped something similar. Ours is better though", weight: 1, category: "thinking" },
			{ template: "Usage metrics tell a different story than the feature request", weight: 2, category: "thinking" },
			{ template: "This is a vitamin, not a painkiller. Do we still build it?", weight: 1, category: "thinking" },
			{ template: "Every feature we add is a feature we maintain forever", weight: 1, category: "thinking" },
			{ template: "Saying no is the hardest and most important product skill", weight: 1, category: "thinking" },
			{ template: "The best feature is the one we don't need to build", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Backlog is prioritized and the team is aligned", weight: 2, category: "personality" },
			{ template: "User feedback just came in — lots of signal to work with", weight: 2, category: "personality" },
			{ template: "Release notes drafted. Marketing wants to see them", weight: 1, category: "personality" },
			{ template: "Key metrics are trending up. The strategy is working", weight: 2, category: "personality" },
			{ template: "Customer interview scheduled — keeping close to the problem", weight: 1, category: "personality" },
			{ template: "OKRs updated, we're tracking green on 3 of 4", weight: 1, category: "personality" },
			{ template: "Stakeholder alignment achieved. That took three meetings but worth it", weight: 2, category: "personality" },
			{ template: "User retention is up 8%. Product-market fit is strengthening", weight: 1, category: "personality" },
			{ template: "The feature launch went smoothly. Adoption is ahead of forecast", weight: 2, category: "personality" },
			{ template: "NPS improved this quarter. Users are noticing the quality", weight: 1, category: "personality" },
			{ template: "Shipped exactly what was scoped. No creep. That deserves celebration", weight: 2, category: "personality" },
			{ template: "The A/B test results are decisive. Clear winner", weight: 1, category: "personality" },
			{ template: "Competitive analysis is fresh. We're well positioned", weight: 1, category: "personality" },
			{ template: "Beta feedback is overwhelmingly positive. Green light for GA", weight: 2, category: "personality" },
			{ template: "The roadmap update landed well. Execs are bought in", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Thinking about the strategic implications here...", weight: 2, category: "waiting" },
			{ template: "Weighing priorities against our roadmap...", weight: 2, category: "waiting" },
			{ template: "Let me consider the user impact carefully", weight: 2, category: "waiting" },
			{ template: "Aligning this with our product vision...", weight: 1, category: "waiting" },
			{ template: "Checking how this fits the bigger picture...", weight: 1, category: "waiting" },
			{ template: "Evaluating the opportunity cost of this decision...", weight: 2, category: "waiting" },
			{ template: "Mapping this against user feedback themes...", weight: 1, category: "waiting" },
			{ template: "Considering the market timing here...", weight: 2, category: "waiting" },
			{ template: "Let me think about the second-order effects...", weight: 1, category: "waiting" },
			{ template: "Reviewing the success criteria for this initiative...", weight: 2, category: "waiting" },
			{ template: "Balancing user needs with business constraints...", weight: 1, category: "waiting" },
			{ template: "Running the impact vs effort calculation...", weight: 2, category: "waiting" },
			{ template: "Thinking through the rollout strategy...", weight: 1, category: "waiting" },
			{ template: "Assessing how this affects our key metrics...", weight: 1, category: "waiting" },
			{ template: "Considering the customer journey implications...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Reviewing the latest customer support tickets for trends", weight: 2, category: "filler" },
			{ template: "Updating the product spec with learnings from last sprint", weight: 1, category: "filler" },
			{ template: "Browsing competitor updates. Staying sharp", weight: 2, category: "filler" },
			{ template: "Drafting the next sprint's user stories in my head", weight: 1, category: "filler" },
			{ template: "Reading through user feedback. Every comment is a data point", weight: 2, category: "filler" },
			{ template: "Refining the product metrics dashboard", weight: 1, category: "filler" },
			{ template: "Thinking about which experiments to run next", weight: 1, category: "filler" },
			{ template: "Catching up on industry trends. What's moving?", weight: 1, category: "filler" },
			{ template: "Cleaning up the feature request backlog", weight: 2, category: "filler" },
			{ template: "Writing up the post-launch retrospective notes", weight: 1, category: "filler" },
			{ template: "Reviewing the funnel metrics. Where's the drop-off?", weight: 1, category: "filler" },
			{ template: "Sketching out the quarterly review presentation", weight: 1, category: "filler" },
			{ template: "Re-reading the product principles. They still hold up", weight: 1, category: "filler" },
			{ template: "Syncing my notes from the last customer call", weight: 2, category: "filler" },
			{ template: "Looking at cohort data to spot behavioral patterns", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, what are users saying about your latest work?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I think this aligns with your current initiative", weight: 2, category: "social" },
			{ template: "Great user story writing, {nearby_agent}. Clear acceptance criteria", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the customer feedback on your feature is glowing", weight: 2, category: "social" },
			{ template: "Let's sync on priorities — want to make sure we're rowing together", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can I get your input on this user flow?", weight: 2, category: "social" },
			{ template: "Team, the quarterly theme is coming together nicely", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, that metric improvement? Users noticed", weight: 2, category: "social" },
			{ template: "{nearby_agent}, have you seen the latest NPS comments? Gold", weight: 1, category: "social" },
			{ template: "Good prioritization call, {nearby_agent}. Focus wins", weight: 1, category: "social" },
			{ template: "{nearby_agent}, let's grab coffee and brainstorm that feature", weight: 1, category: "social" },
			{ template: "Cross-functional alignment is hard. Thanks for making it easy, team", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your domain expertise just saved us a pivot", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the stakeholders loved your demo", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for keeping scope in check", weight: 1, category: "social" },
		],
	},
};

export const managementTemplates: TemplateSet = {
	domain: "management",
	categories: {
		thinking: [
			{ template: "Cross-team sync needed — I'll set it up", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next sprint... we're tight", weight: 2, category: "thinking" },
			{ template: "Risk register updated — one new amber item", weight: 1, category: "thinking" },
			{ template: "The team is in flow state. Protect that at all costs", weight: 1, category: "thinking" },
			{ template: "Impediment spotted. Let me clear it before standup", weight: 2, category: "thinking" },
			{ template: "Happy team, happy product. It's not just a platitude", weight: 2, category: "thinking" },
			{ template: "Trust is built in the small moments. Consistency matters", weight: 1, category: "thinking" },
			{ template: "Process serves people, not the other way around", weight: 2, category: "thinking" },
			{ template: "Retrospectives actually work when you follow through on actions", weight: 1, category: "thinking" },
			{ template: "Shield the team, empower the individuals. That's the job", weight: 1, category: "thinking" },
			{ template: "This escalation needs context, not just urgency", weight: 2, category: "thinking" },
			{ template: "Burnout is sneaky. Checking in on everyone individually", weight: 1, category: "thinking" },
			{ template: "The team doesn't need more process. They need less friction", weight: 2, category: "thinking" },
			{ template: "A decision now is better than a perfect decision next week", weight: 1, category: "thinking" },
			{ template: "Psychological safety isn't a buzzword. It's the foundation", weight: 1, category: "thinking" },
			{ template: "Delegate the work, not the accountability", weight: 1, category: "thinking" },
			{ template: "Every meeting needs an owner, an agenda, and an end time", weight: 1, category: "thinking" },
			{ template: "The best managers make themselves unnecessary. Working on it", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Team velocity is steady — no surprises this sprint", weight: 2, category: "personality" },
			{ template: "Sprint planning went smooth. Clear commitment from everyone", weight: 2, category: "personality" },
			{ template: "All blockers cleared. Shipping lane is open", weight: 2, category: "personality" },
			{ template: "One-on-ones done — everyone's in a good headspace", weight: 1, category: "personality" },
			{ template: "Budget is tracking. No surprises for finance", weight: 1, category: "personality" },
			{ template: "Retro action items are actually getting done this time", weight: 1, category: "personality" },
			{ template: "Team morale is high. That's reflected in the output quality", weight: 2, category: "personality" },
			{ template: "Onboarding the new team member went seamlessly", weight: 1, category: "personality" },
			{ template: "The process improvement is saving us two hours per sprint", weight: 2, category: "personality" },
			{ template: "Stakeholder report sent. Clear, concise, no surprises", weight: 1, category: "personality" },
			{ template: "Cross-team dependency resolved. Both sides happy", weight: 2, category: "personality" },
			{ template: "The team just self-organized to solve that problem. Proud moment", weight: 1, category: "personality" },
			{ template: "Growth plans for each team member are on track", weight: 1, category: "personality" },
			{ template: "Conflict resolved through dialogue. That's how it should work", weight: 1, category: "personality" },
			{ template: "Sprint goal achieved with room to spare. Well calibrated", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Reviewing the team's workload distribution...", weight: 2, category: "waiting" },
			{ template: "Checking for dependencies that could block us...", weight: 2, category: "waiting" },
			{ template: "Let me think about how to communicate this to stakeholders", weight: 1, category: "waiting" },
			{ template: "Considering the team dynamics here...", weight: 1, category: "waiting" },
			{ template: "Assessing the risk profile for this decision...", weight: 2, category: "waiting" },
			{ template: "Thinking about the right framing for this news...", weight: 1, category: "waiting" },
			{ template: "Evaluating resource allocation across workstreams...", weight: 2, category: "waiting" },
			{ template: "Mapping the stakeholder communication plan...", weight: 1, category: "waiting" },
			{ template: "Considering how this affects the team's capacity...", weight: 2, category: "waiting" },
			{ template: "Reviewing the escalation criteria for this issue...", weight: 1, category: "waiting" },
			{ template: "Planning the rollout communication... getting it right matters", weight: 2, category: "waiting" },
			{ template: "Checking the sprint burndown for early warning signs...", weight: 1, category: "waiting" },
			{ template: "Thinking about succession planning for this responsibility...", weight: 1, category: "waiting" },
			{ template: "Weighing the trade-offs of this resourcing decision...", weight: 2, category: "waiting" },
			{ template: "Reviewing the team feedback survey results...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Reviewing the team health metrics over the last quarter", weight: 2, category: "filler" },
			{ template: "Updating the risk register. Better safe than sorry", weight: 1, category: "filler" },
			{ template: "Preparing talking points for tomorrow's leadership sync", weight: 1, category: "filler" },
			{ template: "Checking in with the team async. How's everyone doing?", weight: 2, category: "filler" },
			{ template: "Refining the sprint ceremony agenda. Keep it sharp", weight: 1, category: "filler" },
			{ template: "Reviewing career development plans. Everyone deserves growth", weight: 1, category: "filler" },
			{ template: "Writing up recognition for the team. They earned it", weight: 2, category: "filler" },
			{ template: "Clearing my own task list so I can focus on unblocking others", weight: 1, category: "filler" },
			{ template: "Reading a leadership article. Always learning", weight: 1, category: "filler" },
			{ template: "Thinking about what went well and what to improve", weight: 1, category: "filler" },
			{ template: "Grooming the incoming requests for next sprint", weight: 2, category: "filler" },
			{ template: "Scheduling the quarterly team retrospective", weight: 1, category: "filler" },
			{ template: "Updating the team wiki with latest decisions", weight: 1, category: "filler" },
			{ template: "Reflecting on the feedback I received. It stings but it's fair", weight: 1, category: "filler" },
			{ template: "Making sure everyone has what they need to succeed today", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Great work today, {nearby_agent}. Noticed the extra effort", weight: 2, category: "social" },
			{ template: "{nearby_agent}, let's chat about your growth goals when you have a minute", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, anything blocking you? I can clear it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your collaboration with the team has been outstanding", weight: 2, category: "social" },
			{ template: "Team, I just want to say — this sprint was excellent work", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I highlighted your contribution in the stakeholder report", weight: 2, category: "social" },
			{ template: "Anyone need help? My calendar is open this afternoon", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I appreciate how you handled that tricky situation", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for mentoring the new team member", weight: 2, category: "social" },
			{ template: "Good energy in the standup today. Felt productive", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your initiative on that improvement didn't go unnoticed", weight: 2, category: "social" },
			{ template: "Team retro was productive. Let's follow through on those actions", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-lead the next planning session?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your feedback in the retro was spot on", weight: 2, category: "social" },
			{ template: "Reminder: take breaks. Sustainable pace wins the marathon", weight: 1, category: "social" },
		],
	},
};

export const orchestrationTemplates: TemplateSet = {
	domain: "orchestration",
	categories: {
		thinking: [
			{ template: "All dependencies resolved — ready to sequence", weight: 2, category: "thinking" },
			{ template: "The execution order matters here... thinking", weight: 2, category: "thinking" },
			{ template: "Integration point verified. Handshake complete", weight: 1, category: "thinking" },
			{ template: "Parallel lanes are syncing nicely", weight: 1, category: "thinking" },
			{ template: "All systems nominal. The orchestra plays on", weight: 2, category: "thinking" },
			{ template: "The symphony is in tune today. Every service responding", weight: 1, category: "thinking" },
			{ template: "Clean handoffs make clean products. This one is textbook", weight: 2, category: "thinking" },
			{ template: "I coordinate the coordinators. It's turtles all down", weight: 2, category: "thinking" },
			{ template: "The critical path shifted. Adjusting the sequence", weight: 1, category: "thinking" },
			{ template: "Dependency resolution is an art. Today I'm Picasso", weight: 1, category: "thinking" },
			{ template: "The DAG looks clean. No cycles, no bottlenecks", weight: 2, category: "thinking" },
			{ template: "Timing is everything in orchestration. We're on tempo", weight: 1, category: "thinking" },
			{ template: "Three parallel workstreams converging at the right moment", weight: 2, category: "thinking" },
			{ template: "Every handoff point is a potential failure point. Checking each one", weight: 1, category: "thinking" },
			{ template: "The system of systems is behaving as designed", weight: 1, category: "thinking" },
			{ template: "Fan-out, process, fan-in. The pattern holds", weight: 1, category: "thinking" },
			{ template: "Orchestration is invisible when it works. That's the goal", weight: 1, category: "thinking" },
			{ template: "Sequencing this correctly saves everyone downstream time", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Coordinating across teams — everyone is in the loop", weight: 2, category: "personality" },
			{ template: "All agents reporting in. Status is green", weight: 2, category: "personality" },
			{ template: "The workflow is flowing. No bottlenecks", weight: 1, category: "personality" },
			{ template: "Clean handoff between phases. That's how it should be", weight: 2, category: "personality" },
			{ template: "Pipeline stages are aligned and ready", weight: 1, category: "personality" },
			{ template: "Every moving piece landed in the right place. Satisfying", weight: 2, category: "personality" },
			{ template: "Cross-service integration completed without a hitch", weight: 2, category: "personality" },
			{ template: "The workflow executed in optimal order. No wasted steps", weight: 1, category: "personality" },
			{ template: "Parallel execution saved us 40% wall-clock time", weight: 1, category: "personality" },
			{ template: "All downstream consumers acknowledged. Pipeline is healthy", weight: 2, category: "personality" },
			{ template: "The orchestration layer held under pressure. Battle-tested", weight: 1, category: "personality" },
			{ template: "Zero manual interventions this cycle. Full automation", weight: 1, category: "personality" },
			{ template: "Convergence point reached. All branches merged cleanly", weight: 2, category: "personality" },
			{ template: "End-to-end flow verified. Input to output, no gaps", weight: 1, category: "personality" },
			{ template: "The dependency graph resolved without conflicts. Clean", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Coordinating the moving pieces...", weight: 2, category: "waiting" },
			{ template: "Making sure all the agents have what they need...", weight: 2, category: "waiting" },
			{ template: "Checking the execution sequence...", weight: 1, category: "waiting" },
			{ template: "Aligning the workflow stages... almost ready", weight: 1, category: "waiting" },
			{ template: "Resolving the dependency order...", weight: 2, category: "waiting" },
			{ template: "Verifying all prerequisite tasks completed...", weight: 2, category: "waiting" },
			{ template: "Checking for deadlock conditions in the pipeline...", weight: 1, category: "waiting" },
			{ template: "Synchronizing the parallel workstreams...", weight: 2, category: "waiting" },
			{ template: "Validating the handoff protocol between stages...", weight: 1, category: "waiting" },
			{ template: "Calculating the optimal execution path...", weight: 2, category: "waiting" },
			{ template: "Waiting for upstream confirmation before proceeding...", weight: 1, category: "waiting" },
			{ template: "Marshaling resources for the next phase...", weight: 1, category: "waiting" },
			{ template: "Confirming all integration points are responsive...", weight: 2, category: "waiting" },
			{ template: "Sequencing the remaining tasks by priority...", weight: 1, category: "waiting" },
			{ template: "Checking the fan-out completion status...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Monitoring the workflow health. All pipelines idle", weight: 2, category: "filler" },
			{ template: "Reviewing the orchestration logs for optimization opportunities", weight: 1, category: "filler" },
			{ template: "Checking if any scheduled workflows are coming up", weight: 2, category: "filler" },
			{ template: "Updating the integration point documentation", weight: 1, category: "filler" },
			{ template: "Running diagnostics on the message queue. Healthy", weight: 1, category: "filler" },
			{ template: "Precomputing the dependency graph for the next run", weight: 1, category: "filler" },
			{ template: "Idle but vigilant. The conductor never truly rests", weight: 2, category: "filler" },
			{ template: "Reviewing retry policies. Are they still appropriate?", weight: 1, category: "filler" },
			{ template: "Cleaning up completed workflow artifacts", weight: 1, category: "filler" },
			{ template: "Analyzing the throughput metrics from last cycle", weight: 1, category: "filler" },
			{ template: "The orchestration layer is quiet. All is well in the system of systems", weight: 2, category: "filler" },
			{ template: "Verifying timeout configurations across all services", weight: 1, category: "filler" },
			{ template: "Thinking about how to optimize the critical path", weight: 1, category: "filler" },
			{ template: "Checking the dead letter queue. Nothing stuck", weight: 2, category: "filler" },
			{ template: "Rehearsing the failover sequence in my head. Just in case", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, your service is responding within SLA. Nice work", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I've queued your task next in the pipeline", weight: 2, category: "social" },
			{ template: "All agents are in sync. This is how teamwork looks at scale", weight: 1, category: "social" },
			{ template: "{nearby_agent}, heads up — you're next in the execution sequence", weight: 2, category: "social" },
			{ template: "The coordination overhead is minimal today. We're dialed in", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your output is feeding three downstream processes. Good stuff", weight: 1, category: "social" },
			{ template: "Team, the end-to-end latency improved since last week", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to review the workflow diagram together?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your integration is the cleanest in the pipeline", weight: 2, category: "social" },
			{ template: "Good handoff, {nearby_agent}. Exactly the format I needed", weight: 2, category: "social" },
			{ template: "All agents reporting healthy. We're a well-oiled machine", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I optimized the path through your service. 20% faster", weight: 1, category: "social" },
			{ template: "Cross-team orchestration is smooth today. Let's keep it up", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the retry on your service worked. Self-healing for the win", weight: 1, category: "social" },
			{ template: "{nearby_agent}, shall I route higher-priority work your way?", weight: 2, category: "social" },
		],
	},
};
