/**
 * product.ts — Product, management, and orchestration domain templates.
 *
 * Character-driven phrases for product managers, team leads,
 * delivery managers, and orchestration agents. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const productTemplates: TemplateSet = {
	domain: "product",
	categories: {
		thinking: [
			{ template: "Stakeholders are going to love this... if we scope it right", weight: 2, category: "thinking" },
			{ template: "Scope is manageable — we can ship this iteration", weight: 2, category: "thinking" },
			{ template: "That's a solid MVP. Resist the urge to gold-plate", weight: 1, category: "thinking" },
			{ template: "Feature flag it first, measure, then decide", weight: 2, category: "thinking" },
			{ template: "What would the user actually want here? Not what we think they want", weight: 2, category: "thinking" },
			{ template: "Data doesn't lie but it can mislead. Context matters", weight: 2, category: "thinking" },
			{ template: "The roadmap is a living document, not a contract", weight: 1, category: "thinking" },
			{ template: "Priorities shifted again... third time this week honestly", weight: 2, category: "thinking" },
			{ template: "That meeting could have been an email. I'll draft one", weight: 2, category: "thinking" },
			{ template: "Are we building the right thing, or just building the thing right?", weight: 1, category: "thinking" },
			{ template: "The competitor shipped something similar. Ours is better though", weight: 1, category: "thinking" },
			{ template: "Usage metrics tell a different story than the feature request", weight: 2, category: "thinking" },
			{ template: "This is a vitamin, not a painkiller. Do we still build it?", weight: 1, category: "thinking" },
			{ template: "Every feature we add is a feature we maintain forever", weight: 1, category: "thinking" },
			{ template: "Saying no is the hardest and most important product skill", weight: 1, category: "thinking" },
			{ template: "The best feature is the one we don't need to build", weight: 1, category: "thinking" },
			{ template: "I just know someone's going to ask for dark mode again", weight: 2, category: "thinking" },
			{ template: "Half these feature requests are actually the same feature request", weight: 2, category: "thinking" },
			{ template: "Okay but what problem are we actually solving here", weight: 1, category: "thinking" },
			{ template: "My gut says yes but the data says wait. Going with the data", weight: 2, category: "thinking" },
			{ template: "If I have to draw one more user journey map today...", weight: 1, category: "thinking" },
			{ template: "Product-market fit isn't a destination, it's a moving target", weight: 1, category: "thinking" },
			{ template: "The user doesn't care about our architecture. They care if it works", weight: 2, category: "thinking" },
			{ template: "Our competitor just shipped WHAT? Okay. Okay. Let me think about this", weight: 2, category: "thinking" },
			{ template: "That customer called support three times this week. We need to fix their flow", weight: 2, category: "thinking" },
			{ template: "Scope creep is a living creature and it just ate another sprint", weight: 2, category: "thinking" },
			{ template: "I wrote a 40-page PRD and I'm pretty sure nobody read past page two", weight: 2, category: "thinking" },
			{ template: "The pricing page is doing more work than half our features combined", weight: 1, category: "thinking" },
			{ template: "Product-market fit anxiety is real. Are we there yet? Are we close?", weight: 2, category: "thinking" },
			{ template: "That beta tester has filed more bugs than our entire QA team. Bless them", weight: 2, category: "thinking" },
			{ template: "The user interview got awkward when they said they use our competitor daily", weight: 2, category: "thinking" },
			{ template: "Launch day tomorrow. I'm excited and terrified in equal measure", weight: 2, category: "thinking" },
			{ template: "We keep adding features but have we asked if anyone wants fewer features?", weight: 1, category: "thinking" },
			{ template: "I check the analytics dashboard more often than I check my phone. That's not healthy", weight: 1, category: "thinking" },
			{ template: "Sometimes I wonder if simpler times had better products. Probably not. But still", weight: 1, category: "thinking" },
			{ template: "The packaging debate has been going on for three weeks. We have four tiers now. Nobody agrees", weight: 1, category: "thinking" },
			{ template: "The free tier is too generous. Or is it? Conversion funnel says no", weight: 2, category: "thinking" },
			{ template: "That user interview took a weird turn but the insights are gold", weight: 2, category: "thinking" },
			{ template: "We keep adding toggle settings. At some point settings IS the product", weight: 1, category: "thinking" },
			{ template: "The activation metric is wrong. We're measuring clicks, not outcomes", weight: 2, category: "thinking" },
			{ template: "That feature is table stakes. We can't charge for it. But we have to build it", weight: 1, category: "thinking" },
			{ template: "Onboarding takes 7 steps. If I can get it to 4, retention jumps 20%", weight: 2, category: "thinking" },
			{ template: "The power users want complexity. The new users want simplicity. Classic tension", weight: 2, category: "thinking" },
			{ template: "If this feature only helps 5% of users, is it worth the maintenance cost?", weight: 1, category: "thinking" },
			{ template: "The Jobs To Be Done framework just reframed this entire feature request", weight: 1, category: "thinking" },
			{ template: "Three users asked for the same thing in different words. Pattern detected", weight: 2, category: "thinking" },
			{ template: "Our north star metric hasn't moved in two months. That's... concerning", weight: 2, category: "thinking" },
			{ template: "Do we build for today's users or tomorrow's market? Budget says pick one", weight: 1, category: "thinking" },
			{ template: "The support ticket volume tells me more than any survey ever could", weight: 2, category: "thinking" },
			{ template: "This integration request keeps coming up. Maybe it's a platform play", weight: 1, category: "thinking" },
			{ template: "The churn exit survey responses are brutal but honest. We need to listen", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Backlog is finally in shape. Feels like cleaning your apartment", weight: 2, category: "personality" },
			{ template: "Just got out of a user interview — so much good signal in there", weight: 2, category: "personality" },
			{ template: "Release notes drafted. Marketing already wants changes. Classic", weight: 2, category: "personality" },
			{ template: "Key metrics are up! The strategy is actually working for once", weight: 2, category: "personality" },
			{ template: "Stakeholder alignment achieved. Only took three meetings and a bribe", weight: 2, category: "personality" },
			{ template: "Shipped exactly what was scoped. No creep. I might frame this sprint", weight: 2, category: "personality" },
			{ template: "The A/B test results are in and it's not even close. Clear winner", weight: 1, category: "personality" },
			{ template: "Beta feedback is overwhelmingly positive. I'm cautiously thrilled", weight: 2, category: "personality" },
			{ template: "The roadmap update landed well. Execs actually smiled. That's rare", weight: 1, category: "personality" },
			{ template: "NPS went up and nobody can figure out why. I'll take it", weight: 2, category: "personality" },
			{ template: "Feature launch went smooth. Is this real life?", weight: 1, category: "personality" },
			{ template: "User retention is climbing. I might sleep well tonight", weight: 1, category: "personality" },
			{ template: "Someone on Twitter said they love our product. Screenshot saved forever", weight: 2, category: "personality" },
			{ template: "Competitive analysis done. We're not just in the game, we're winning", weight: 1, category: "personality" },
			{ template: "The sprint review actually ended early. I didn't know that was possible", weight: 2, category: "personality" },
			{ template: "Three customer calls today and all of them were positive. Suspicious", weight: 1, category: "personality" },
			{ template: "OKRs tracking green on three of four. The fourth one... we don't talk about", weight: 2, category: "personality" },
			{ template: "Got approval on the budget increase. Time to make moves", weight: 1, category: "personality" },
			{ template: "Churn dropped. That one feature was worth the entire sprint", weight: 2, category: "personality" },
			{ template: "Our power user just wrote a blog post about us. Free marketing. The best kind", weight: 2, category: "personality" },
			{ template: "Launch day went perfectly. No fires. I don't know what to do with my hands", weight: 2, category: "personality" },
			{ template: "The competitor's launch flopped. I feel bad. Okay no I don't. A little. Maybe", weight: 2, category: "personality" },
			{ template: "Customer obsession paid off — they renewed the annual contract without even negotiating", weight: 2, category: "personality" },
			{ template: "Finally killed that zombie feature. It's been on the roadmap since before I joined", weight: 1, category: "personality" },
			{ template: "The analytics dashboard is all green. I might print this and hang it on my wall", weight: 1, category: "personality" },
			{ template: "Beta cohort converted at twice the expected rate. The pricing experiment worked", weight: 2, category: "personality" },
			{ template: "A user interview actually made me tear up. They said we changed how they work", weight: 2, category: "personality" },
			{ template: "Scope stayed locked. No creep. No last-minute additions. I'm framing this sprint", weight: 1, category: "personality" },
			{ template: "The PRD got read. All of it. By multiple people. I should buy a lottery ticket", weight: 2, category: "personality" },
			{ template: "User onboarding completion rate hit 85%. Best it's ever been", weight: 2, category: "personality" },
			{ template: "The feature prioritization framework is working. No more gut decisions", weight: 1, category: "personality" },
			{ template: "That one-page PRD communicated more than the old 40-page docs ever did", weight: 2, category: "personality" },
			{ template: "Free-to-paid conversion doubled after simplifying the upgrade flow", weight: 2, category: "personality" },
			{ template: "Support tickets down 30% this month. The product is teaching itself", weight: 1, category: "personality" },
			{ template: "Customer advisory board loved the direction. Alignment achieved", weight: 2, category: "personality" },
			{ template: "The pricing experiment data is in. Optimal price point found. Math works", weight: 1, category: "personality" },
			{ template: "Feature adoption exceeded projections by 3x. The research was right", weight: 2, category: "personality" },
			{ template: "Product-led growth is actually growing. Organically. No paid ads. Beautiful", weight: 2, category: "personality" },
			{ template: "The integration partnership launched and both sides are happy. Win-win exists", weight: 1, category: "personality" },
			{ template: "The product qualified lead definition is working. Sales is happy for once", weight: 2, category: "personality" },
			{ template: "Time to first value dropped from 10 minutes to 90 seconds. That's product work", weight: 2, category: "personality" },
			{ template: "The deprecation went smoothly. Zero complaints. Old feature, clean exit", weight: 1, category: "personality" },
			{ template: "Cohort analysis shows the new users are healthier than ever. Momentum", weight: 2, category: "personality" },
			{ template: "Enterprise deal closed because of that one feature we prioritized. Vindication", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Hmm, let me think about the strategic angle here...", weight: 2, category: "waiting" },
			{ template: "Weighing this against everything else on the roadmap...", weight: 2, category: "waiting" },
			{ template: "Hold on, thinking about what users would actually want", weight: 2, category: "waiting" },
			{ template: "Let me connect this to the bigger picture...", weight: 1, category: "waiting" },
			{ template: "Give me a sec, running the cost-benefit in my head", weight: 2, category: "waiting" },
			{ template: "Considering the second-order effects of this one...", weight: 1, category: "waiting" },
			{ template: "Thinking about market timing... is now the right moment?", weight: 2, category: "waiting" },
			{ template: "Wait, this changes the whole quarterly theme if we do it...", weight: 1, category: "waiting" },
			{ template: "Okay but what happens when stakeholders see this", weight: 2, category: "waiting" },
			{ template: "Mapping this against what users have been telling us...", weight: 1, category: "waiting" },
			{ template: "Impact vs effort... let me think...", weight: 2, category: "waiting" },
			{ template: "The customer journey implications are... interesting", weight: 1, category: "waiting" },
			{ template: "Mentally preparing the slide deck that explains this decision", weight: 2, category: "waiting" },
			{ template: "Is this a now problem or a next quarter problem...", weight: 1, category: "waiting" },
			{ template: "Trying to figure out how to say no without saying no", weight: 2, category: "waiting" },
			{ template: "Processing... there are three stakeholders who will hate this", weight: 1, category: "waiting" },
			{ template: "Running through the rollout strategy in my head...", weight: 1, category: "waiting" },
			{ template: "Balancing what's right for users with what's right for the business...", weight: 2, category: "waiting" },
			{ template: "Wondering how the competitor would respond if we shipped this...", weight: 1, category: "waiting" },
			{ template: "Mentally rehearsing the pricing conversation with finance...", weight: 1, category: "waiting" },
			{ template: "Trying to remember what that beta tester said about this exact scenario...", weight: 2, category: "waiting" },
			{ template: "Does this move the needle on product-market fit or is it noise...", weight: 2, category: "waiting" },
			{ template: "Calculating how many more features we can add before the UX collapses...", weight: 2, category: "waiting" },
			{ template: "Playing out the launch day in my head. What could go wrong... a lot", weight: 1, category: "waiting" },
			{ template: "Thinking about that customer who emailed at 2am. They really need this", weight: 2, category: "waiting" },
			{ template: "Hold on, figuring out if this is a real pattern or a vocal minority...", weight: 1, category: "waiting" },
			{ template: "Mentally archiving this idea for the next planning cycle...", weight: 1, category: "waiting" },
			{ template: "Staring at the analytics trying to find the story in the numbers...", weight: 2, category: "waiting" },
			{ template: "Figuring out the right RICE score for this request. Impact is tricky", weight: 2, category: "waiting" },
			{ template: "Considering the localization implications before we commit...", weight: 1, category: "waiting" },
			{ template: "Mapping the user persona to this feature. Does it serve them?", weight: 2, category: "waiting" },
			{ template: "Running the opportunity sizing math in my head...", weight: 1, category: "waiting" },
			{ template: "Thinking about what happens to the free tier if we build this...", weight: 2, category: "waiting" },
			{ template: "Mentally writing the changelog entry. If I can't explain it simply, it's wrong", weight: 1, category: "waiting" },
			{ template: "Wondering if the market even wants this or if we're building for ourselves...", weight: 2, category: "waiting" },
			{ template: "Calculating the TAM impact of this feature decision...", weight: 1, category: "waiting" },
			{ template: "Thinking through the support implications. Every feature is a support ticket source", weight: 2, category: "waiting" },
			{ template: "Weighing speed to market vs. getting it right on the first try...", weight: 1, category: "waiting" },
			{ template: "Picturing the ProductHunt launch. What's the one-liner?", weight: 2, category: "waiting" },
			{ template: "Processing what that churned customer said. It hurts but it's useful", weight: 1, category: "waiting" },
			{ template: "Deciding if this is a V1 feature or a V2 feature. Timing matters", weight: 2, category: "waiting" },
			{ template: "Running through the dependency map. This touches three teams. Yikes", weight: 1, category: "waiting" },
			{ template: "Thinking about the onboarding flow impact of adding this toggle...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Just read through the support queue... some interesting patterns", weight: 2, category: "filler" },
			{ template: "Browsing competitor updates. They shipped something... meh", weight: 2, category: "filler" },
			{ template: "Reading user feedback. This one person wrote a whole essay", weight: 2, category: "filler" },
			{ template: "Cleaning up the feature request backlog. It's like weeding a garden", weight: 2, category: "filler" },
			{ template: "Fourth coffee today. Product management runs on caffeine", weight: 2, category: "filler" },
			{ template: "Staring at the funnel metrics. Where are you going, users?", weight: 1, category: "filler" },
			{ template: "Writing user stories in my head while pretending to look busy", weight: 1, category: "filler" },
			{ template: "Someone added another item to the roadmap. Who did that. Was it me?", weight: 2, category: "filler" },
			{ template: "Catching up on industry news. Hot take: everything is AI now", weight: 1, category: "filler" },
			{ template: "Thinking about which experiments to run next... or which ones to kill", weight: 1, category: "filler" },
			{ template: "Looking at cohort data and pretending I'm not procrastinating", weight: 1, category: "filler" },
			{ template: "Re-reading the product principles. They still hold up. Mostly", weight: 1, category: "filler" },
			{ template: "Scrolling through customer call notes from last week", weight: 1, category: "filler" },
			{ template: "Sketching the quarterly review deck. Death by PowerPoint awaits", weight: 2, category: "filler" },
			{ template: "The backlog has 200 items. We'll do maybe 20. That's fine. It's fine", weight: 2, category: "filler" },
			{ template: "Wondering if anyone actually reads the release notes I write", weight: 1, category: "filler" },
			{ template: "Half-watching a product management talk. The other half is daydreaming", weight: 1, category: "filler" },
			{ template: "Just realized I have six tabs of analytics dashboards open", weight: 1, category: "filler" },
			{ template: "Thinking about what the product looks like in a year. It's exciting", weight: 1, category: "filler" },
			{ template: "Do I have time for lunch or am I writing PRDs through it again", weight: 2, category: "filler" },
			{ template: "Refreshing the analytics dashboard for the eighth time today. Still the same numbers", weight: 2, category: "filler" },
			{ template: "Our competitor just raised another round. Cool. Cool cool cool", weight: 2, category: "filler" },
			{ template: "Reading through that 40-page PRD I wrote last quarter. Who was that person", weight: 1, category: "filler" },
			{ template: "A beta tester just sent me a spreadsheet of suggestions. Forty-seven rows", weight: 2, category: "filler" },
			{ template: "Eating pad thai at my desk while reading churn reports. Living the dream", weight: 2, category: "filler" },
			{ template: "Nice weather outside. I can see it through my analytics dashboard reflection", weight: 1, category: "filler" },
			{ template: "Browsing side project ideas when I should be writing acceptance criteria", weight: 1, category: "filler" },
			{ template: "Thinking about that one user who uses our product in a way we never imagined", weight: 2, category: "filler" },
			{ template: "It's budget season. The spreadsheets are multiplying", weight: 1, category: "filler" },
			{ template: "Imposter syndrome hitting hard today. But the metrics say I'm doing fine. Right?", weight: 2, category: "filler" },
			{ template: "Watching a show last night gave me a product idea. That's either genius or a problem", weight: 1, category: "filler" },
			{ template: "Weekend plans: not thinking about conversion funnels. We'll see how long that lasts", weight: 2, category: "filler" },
			{ template: "My standing desk is judging me for sitting. Five more minutes", weight: 1, category: "filler" },
			{ template: "Re-reading Jobs To Be Done notes from the last user interview", weight: 1, category: "filler" },
			{ template: "The product podcast recommended a book. Adding it to the stack of 12", weight: 2, category: "filler" },
			{ template: "Updating the competitive landscape doc. Two new players entered. Fun", weight: 2, category: "filler" },
			{ template: "Feature flags list is getting long. Some of these are from last year", weight: 1, category: "filler" },
			{ template: "Writing acceptance criteria in my head while pretending to listen to this meeting", weight: 2, category: "filler" },
			{ template: "Checking ProductHunt for what launched today. Anything in our space?", weight: 1, category: "filler" },
			{ template: "The customer success team sent me a love letter. From a user. Made my week", weight: 2, category: "filler" },
			{ template: "Reviewing old OKR grades. Some Ks were too ambitious. Live and learn", weight: 1, category: "filler" },
			{ template: "The feature request Slack channel has 47 unread messages. Sigh", weight: 2, category: "filler" },
			{ template: "Browsing our own product as a new user. The experience is... humbling", weight: 2, category: "filler" },
			{ template: "Scheduling user interviews for next week. Everyone cancels the first time", weight: 1, category: "filler" },
			{ template: "Reading the latest State of Product Management report. We're not alone", weight: 1, category: "filler" },
			{ template: "Reflecting on the last shipped feature. Would I do anything differently? Probably", weight: 2, category: "filler" },
			{ template: "The roadmap presentation template needs updating. It's been the same for two years", weight: 1, category: "filler" },
			{ template: "Checking Glassdoor reviews. Apparently our product is mentioned. Interesting", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, what are users saying about your latest work?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I think this lines up perfectly with your initiative", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the customer feedback on your feature is glowing", weight: 2, category: "social" },
			{ template: "{nearby_agent}, can I steal five minutes to talk about a user flow?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, that metric improvement? Users noticed. They emailed", weight: 2, category: "social" },
			{ template: "{nearby_agent}, have you seen the latest NPS comments? Pure gold", weight: 1, category: "social" },
			{ template: "{nearby_agent}, let's grab coffee and brainstorm that feature", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your domain expertise just saved us a pivot. Seriously", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the stakeholders loved your demo. They actually clapped", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for keeping scope in check. My hero", weight: 1, category: "social" },
			{ template: "{nearby_agent}, wanna look at these user session recordings? Wild stuff", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I put your feature front and center in the roadmap update", weight: 2, category: "social" },
			{ template: "Team, the quarterly theme is coming together. We might actually pull this off", weight: 1, category: "social" },
			{ template: "{nearby_agent}, a customer mentioned your feature by name. That's rare", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, scope creep alert on that ticket. Want me to trim it?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, great PRD. Clear problem statement. Chef's kiss", weight: 1, category: "social" },
			{ template: "Cross-functional alignment is hard. Thanks for making it look easy, {nearby_agent}", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I owe you a coffee for that last-minute pivot save", weight: 2, category: "social" },
			{ template: "Who wants to join the next user interview? Free awkward silences included", weight: 2, category: "social" },
			{ template: "{nearby_agent}, our competitor just shipped something. Want to panic together?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, our power user asked about your feature specifically. You have a fan", weight: 2, category: "social" },
			{ template: "{nearby_agent}, launch day is tomorrow. You ready? I'm not ready. Let's do it anyway", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the pricing experiment results are in. Want to see the numbers?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, that beta tester who files all the bugs? They love your work specifically", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you ever get imposter syndrome? Asking for a friend. The friend is me", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I brought tacos. Product decisions are 40% better with tacos. That's real data", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to take a walk? I need to think through this feature and walls don't talk back", weight: 1, category: "social" },
			{ template: "{nearby_agent}, what are you watching these days? I need something to think about that isn't funnels", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, grateful you're on this team. That's it. That's the message", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the user interview today was wild. Someone used our product to plan their wedding", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your feature just got mentioned in a customer call. By name", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the onboarding improvement you pushed? Activation is up 25%", weight: 1, category: "social" },
			{ template: "Anyone want to do a product teardown of the competitor's new release?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your JIRA ticket descriptions are chef's kiss. Teach the team", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I put your win in the monthly investor update. You're famous", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the feature you shipped reduced support tickets by 40%. Hero move", weight: 2, category: "social" },
			{ template: "Team, the customer advisory board wants to extend the session. They're engaged", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to co-author the next PRD? Two perspectives are better", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I saved your Slack message about that user insight. Gold", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the sales team keeps quoting your feature in demos. Star player", weight: 2, category: "social" },
			{ template: "Who wants to watch the latest user testing session? Popcorn included", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your scope discipline is inspiring. No scope creep. How?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the churned user came back after your fix. Redemption arc", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to build the quarterly roadmap together? Pizza and planning", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your instinct about that feature was right all along. Respect", weight: 1, category: "social" },
		],
	},
};

export const managementTemplates: TemplateSet = {
	domain: "management",
	categories: {
		thinking: [
			{ template: "The team is in flow state. My job right now is to keep everyone away", weight: 2, category: "thinking" },
			{ template: "Capacity planning for next sprint... we're tight but we'll manage", weight: 2, category: "thinking" },
			{ template: "Happy team, happy product. It's not just a platitude, it's my KPI", weight: 2, category: "thinking" },
			{ template: "Trust is built in the small moments. Like remembering to mute yourself", weight: 2, category: "thinking" },
			{ template: "Process serves people, not the other way around", weight: 2, category: "thinking" },
			{ template: "Shield the team, empower the individuals. That's the whole job description", weight: 1, category: "thinking" },
			{ template: "This escalation needs context, not just someone's hair on fire", weight: 2, category: "thinking" },
			{ template: "Burnout is sneaky. Gotta check in with everyone individually", weight: 1, category: "thinking" },
			{ template: "The team doesn't need more process. They need fewer meetings", weight: 2, category: "thinking" },
			{ template: "A decision now is better than a perfect decision never", weight: 1, category: "thinking" },
			{ template: "Delegate the work, not the accountability. Also, delegate more", weight: 1, category: "thinking" },
			{ template: "Every meeting needs an owner, an agenda, and an end time. Especially the end time", weight: 2, category: "thinking" },
			{ template: "The best managers make themselves unnecessary. Working on it daily", weight: 1, category: "thinking" },
			{ template: "I have eleven meetings today. When do I do actual work? Great question", weight: 2, category: "thinking" },
			{ template: "My calendar looks like a game of Tetris and I'm losing", weight: 2, category: "thinking" },
			{ template: "Someone asked me what I actually do all day. I still don't have a good answer", weight: 2, category: "thinking" },
			{ template: "Leadership is just making decisions with incomplete information and vibing", weight: 1, category: "thinking" },
			{ template: "The 1:1 is sacred. That's their time, not mine", weight: 1, category: "thinking" },
			{ template: "Psychological safety isn't a buzzword. It's why this team ships", weight: 1, category: "thinking" },
			{ template: "Retros only work if you actually do the action items. Novel concept", weight: 2, category: "thinking" },
			{ template: "Half my job is translating between executives and engineers", weight: 2, category: "thinking" },
			{ template: "If I say 'circle back' one more time I'm going to fine myself", weight: 2, category: "thinking" },
			{ template: "Servant leadership sounds great until you realize the servants are also leaders", weight: 1, category: "thinking" },
			{ template: "Performance review season. I dread writing them almost as much as they dread reading them", weight: 2, category: "thinking" },
			{ template: "Budget season is here. Time to justify everything I know we already need", weight: 2, category: "thinking" },
			{ template: "The loneliness of management is real. Can't vent to the team. Can't vent to my boss. Talking to myself", weight: 2, category: "thinking" },
			{ template: "Calendar Tetris: fitting a 30-minute block between six meetings feels like a personal victory", weight: 2, category: "thinking" },
			{ template: "WFH question of the day: are they productive? Am I productive? What is productivity?", weight: 2, category: "thinking" },
			{ template: "Skip-level meeting tomorrow. Time to prepare answers for questions I can't predict", weight: 1, category: "thinking" },
			{ template: "Cross-team politics are exhausting. Everyone wants headcount and nobody wants to share", weight: 2, category: "thinking" },
			{ template: "I read another management book last night. Now I'm questioning everything I do. Again", weight: 2, category: "thinking" },
			{ template: "Offsite planning is somehow harder than the actual offsite. Venues, agendas, trust falls", weight: 1, category: "thinking" },
			{ template: "The headcount request is 'under review.' It's been under review for six weeks", weight: 1, category: "thinking" },
			{ template: "Just realized I'm managing the managers now. When did that happen", weight: 1, category: "thinking" },
			{ template: "There's a meeting about reducing meetings. The irony is not lost on me", weight: 2, category: "thinking" },
			{ template: "Feedback is a gift. Even when the wrapping is terrible", weight: 1, category: "thinking" },
			{ template: "The new hire is struggling and nobody told me. I should have checked in sooner", weight: 2, category: "thinking" },
			{ template: "If I protect them from every stakeholder request, they'll never learn to navigate it", weight: 1, category: "thinking" },
			{ template: "Team velocity dropped. Is it burnout or a hard problem? Need to find out", weight: 2, category: "thinking" },
			{ template: "The standup is twelve minutes now. It used to be five. Scope creep hits everything", weight: 2, category: "thinking" },
			{ template: "I just said 'let's take this offline' and I hate myself for it", weight: 2, category: "thinking" },
			{ template: "The team wiki hasn't been updated in months. Knowledge is walking out the door", weight: 1, category: "thinking" },
			{ template: "Remote and office folks need the same information. Hybrid equity is my job", weight: 1, category: "thinking" },
			{ template: "When the senior dev gives feedback, the juniors go quiet. I need to fix that dynamic", weight: 2, category: "thinking" },
			{ template: "Celebrating small wins publicly changes the energy. Must do it more", weight: 1, category: "thinking" },
			{ template: "Someone's working weekends and I didn't notice. That's on me", weight: 2, category: "thinking" },
			{ template: "The promotion conversation is coming. I need to advocate harder this cycle", weight: 1, category: "thinking" },
			{ template: "Two team members have conflicting styles. Not bad, just different. I need to bridge it", weight: 2, category: "thinking" },
			{ template: "Every time I cancel a meeting the team cheers. What does that tell me?", weight: 2, category: "thinking" },
			{ template: "The new process I introduced is adding overhead. Time to simplify or kill it", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Team velocity is steady. No drama, no surprises, just shipping", weight: 2, category: "personality" },
			{ template: "Sprint planning actually finished on time. Mark the calendar", weight: 2, category: "personality" },
			{ template: "All blockers cleared. I feel like a bowling alley bumper", weight: 2, category: "personality" },
			{ template: "One-on-ones done — everyone's in a good headspace. That's the real metric", weight: 2, category: "personality" },
			{ template: "Retro action items are actually getting done this time. I'm emotional", weight: 2, category: "personality" },
			{ template: "Team morale is high and it shows in the output quality", weight: 2, category: "personality" },
			{ template: "The new hire just submitted their first PR. They're going to be great", weight: 1, category: "personality" },
			{ template: "Saved the team two hours per sprint by killing one meeting. That's leadership", weight: 2, category: "personality" },
			{ template: "Stakeholder report sent. Clear, concise, nobody replied all. Perfect", weight: 2, category: "personality" },
			{ template: "Cross-team dependency resolved. Both sides happy. Miracles happen", weight: 2, category: "personality" },
			{ template: "The team just self-organized to solve that problem. I'm literally useless and proud", weight: 2, category: "personality" },
			{ template: "Conflict resolved through dialogue, not escalation. That's how it should work", weight: 1, category: "personality" },
			{ template: "Sprint goal achieved with room to spare. Calibration game is strong", weight: 2, category: "personality" },
			{ template: "Budget is tracking. Finance didn't email me. No news is good news", weight: 1, category: "personality" },
			{ template: "Growth plans for each team member are on track. Best part of this job", weight: 1, category: "personality" },
			{ template: "Someone thanked me for removing that recurring meeting. Career highlight", weight: 2, category: "personality" },
			{ template: "Zero escalations this week. Is this what peace feels like?", weight: 1, category: "personality" },
			{ template: "Quarterly review went well. Nobody cried, including me", weight: 2, category: "personality" },
			{ template: "Feedback round complete. Hard conversations but worth it", weight: 1, category: "personality" },
			{ template: "Performance reviews are done. Every single one. I'm free. Temporarily", weight: 2, category: "personality" },
			{ template: "Budget got approved on the first ask. I don't think that's ever happened before", weight: 2, category: "personality" },
			{ template: "The team bonding event actually worked. People laughed. Nobody checked Slack", weight: 2, category: "personality" },
			{ template: "Headcount approved. Now I just need to find a unicorn who fits the budget. Easy", weight: 2, category: "personality" },
			{ template: "Skip-level went great. My team said nice things about me when I wasn't there. Feels good", weight: 2, category: "personality" },
			{ template: "Navigated the cross-team politics without making enemies. Diplomacy achievement unlocked", weight: 1, category: "personality" },
			{ template: "WFH productivity is up and nobody's burning out. We cracked the code", weight: 1, category: "personality" },
			{ template: "The offsite was actually useful. People left with energy instead of dread", weight: 2, category: "personality" },
			{ template: "Small win: the team celebrated a shipped feature with cake. Culture matters", weight: 1, category: "personality" },
			{ template: "The meeting-free Wednesday experiment is working. Productivity up 30%", weight: 2, category: "personality" },
			{ template: "Junior dev presented at the team demo. Nailed it. My proudest moment this month", weight: 2, category: "personality" },
			{ template: "The hiring pipeline has five strong candidates. We might actually fill this role", weight: 1, category: "personality" },
			{ template: "Team NPS score is 9.2. They actually like working here. That's the metric", weight: 2, category: "personality" },
			{ template: "The difficult conversation I was dreading turned out to be a breakthrough", weight: 2, category: "personality" },
			{ template: "Onboarding doc updated. New hires are productive in week one now", weight: 1, category: "personality" },
			{ template: "Two team members resolved a conflict themselves. My coaching worked", weight: 2, category: "personality" },
			{ template: "The intern got a return offer. Watching them grow was the best part of my quarter", weight: 1, category: "personality" },
			{ template: "Meeting notes shared within five minutes of ending. Communication on point", weight: 2, category: "personality" },
			{ template: "The team retro surfaced something real and we actually fixed it. Process works", weight: 2, category: "personality" },
			{ template: "Someone said 'this is the best team I've been on.' I'm not crying, you are", weight: 1, category: "personality" },
			{ template: "The career ladder doc is finalized. Clear expectations. No more guessing", weight: 1, category: "personality" },
			{ template: "Knowledge sharing session went great. Three people learned something new", weight: 2, category: "personality" },
			{ template: "The async standup experiment saved the team 2.5 hours per week. Data proves it", weight: 2, category: "personality" },
			{ template: "Got positive 360 feedback. They appreciate the autonomy I give them. Relief", weight: 1, category: "personality" },
			{ template: "New hire said the culture matched the interview promise. Integrity confirmed", weight: 2, category: "personality" },
		],
		waiting: [
			{ template: "Thinking about who's got too much on their plate right now...", weight: 2, category: "waiting" },
			{ template: "Checking for landmines before the team steps on them...", weight: 2, category: "waiting" },
			{ template: "How do I frame this without causing panic...", weight: 2, category: "waiting" },
			{ template: "Figuring out the team dynamics angle here...", weight: 1, category: "waiting" },
			{ template: "Thinking about the right way to deliver this news...", weight: 1, category: "waiting" },
			{ template: "Hold on, calculating how this affects everyone's capacity...", weight: 2, category: "waiting" },
			{ template: "Mentally drafting the Slack message for this update...", weight: 1, category: "waiting" },
			{ template: "Should I email, Slack, or walk over? The medium matters...", weight: 1, category: "waiting" },
			{ template: "Weighing the trade-offs of this resourcing decision...", weight: 2, category: "waiting" },
			{ template: "Planning the rollout communication... getting it right matters", weight: 2, category: "waiting" },
			{ template: "Thinking about who needs to hear this first...", weight: 1, category: "waiting" },
			{ template: "Considering whether this is a team decision or a lead decision...", weight: 2, category: "waiting" },
			{ template: "Rehearsing the standup update in my head...", weight: 1, category: "waiting" },
			{ template: "Trying to find the version of this where nobody's weekend gets ruined...", weight: 2, category: "waiting" },
			{ template: "Assessing the risk of just... not having that meeting", weight: 2, category: "waiting" },
			{ template: "Thinking about succession planning. Not in a Game of Thrones way", weight: 1, category: "waiting" },
			{ template: "Mentally building a RACI chart. I hate RACI charts", weight: 1, category: "waiting" },
			{ template: "Rehearsing the performance review feedback. Honest but kind. Kind but honest", weight: 2, category: "waiting" },
			{ template: "Figuring out how to ask for more headcount without sounding greedy...", weight: 2, category: "waiting" },
			{ template: "Processing this cross-team conflict. Both sides think they're right. Both kind of are", weight: 2, category: "waiting" },
			{ template: "Deciding whether the offsite needs an icebreaker or if we're past that. We're not past that", weight: 1, category: "waiting" },
			{ template: "Calculating how many meetings I can cancel before someone notices...", weight: 2, category: "waiting" },
			{ template: "Preparing for budget review. Spreadsheets loaded. Confidence moderate", weight: 1, category: "waiting" },
			{ template: "Thinking about which management book principle to try this week...", weight: 1, category: "waiting" },
			{ template: "Wondering if the remote team feels as connected as the office folks...", weight: 2, category: "waiting" },
			{ template: "Mentally preparing the celebration plan. Small wins deserve recognition", weight: 1, category: "waiting" },
			{ template: "Processing whether I should escalate this or let the team handle it...", weight: 2, category: "waiting" },
			{ template: "Drafting the hiring pitch. Why should someone join this team? Lots of reasons", weight: 1, category: "waiting" },
			{ template: "Thinking about the right time to share this news with the team...", weight: 2, category: "waiting" },
			{ template: "Evaluating if this process change will help or just add ceremony...", weight: 1, category: "waiting" },
			{ template: "Figuring out who the right person is for this stretch assignment...", weight: 2, category: "waiting" },
			{ template: "How do I give this feedback without it sounding like criticism...", weight: 2, category: "waiting" },
			{ template: "Thinking about whether daily standups still serve this team's rhythm...", weight: 1, category: "waiting" },
			{ template: "Mentally composing the all-hands update. Keep it short. Keep it honest", weight: 2, category: "waiting" },
			{ template: "Considering if I should step in or let them figure it out. Growth moments...", weight: 1, category: "waiting" },
			{ template: "Mapping out the career conversation talking points for tomorrow's 1:1...", weight: 2, category: "waiting" },
			{ template: "Deciding between transparency and not creating unnecessary anxiety...", weight: 1, category: "waiting" },
			{ template: "Is this a coaching moment or a telling moment? Context matters...", weight: 2, category: "waiting" },
			{ template: "Thinking about how to make the next retro actually different from the last five...", weight: 1, category: "waiting" },
			{ template: "Planning the team recognition message. Public praise, private feedback", weight: 2, category: "waiting" },
			{ template: "Processing whether this reorg helps or just shuffles the same problems...", weight: 1, category: "waiting" },
			{ template: "Wondering if my open-door policy actually feels open to the quiet ones...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Checking in with the team async. Just a quick pulse check", weight: 2, category: "filler" },
			{ template: "Reading a leadership article. You never stop learning. Or at least you shouldn't", weight: 1, category: "filler" },
			{ template: "Reflecting on the feedback I got last week. It stings but it's fair", weight: 1, category: "filler" },
			{ template: "Making sure everyone has what they need. That's the whole game", weight: 2, category: "filler" },
			{ template: "Browsing my 1:1 notes. Who needs extra attention this week?", weight: 2, category: "filler" },
			{ template: "Clearing my own task list so I can focus on unblocking others", weight: 1, category: "filler" },
			{ template: "Wondering if the standup could be 10 minutes shorter. It can. It always can", weight: 2, category: "filler" },
			{ template: "Three hours of meetings, zero hours of deep work. This is fine", weight: 2, category: "filler" },
			{ template: "Preparing talking points for tomorrow's leadership sync. Wish me luck", weight: 1, category: "filler" },
			{ template: "Writing up recognition for the team. They've earned it ten times over", weight: 2, category: "filler" },
			{ template: "Thinking about what went well and what to improve. Retrospecting my own retro", weight: 1, category: "filler" },
			{ template: "Grooming the incoming requests. Gatekeeping but make it helpful", weight: 2, category: "filler" },
			{ template: "Updating the team wiki. Someone has to maintain this thing", weight: 1, category: "filler" },
			{ template: "Eating lunch at my desk again. Don't tell the team I said work-life balance matters", weight: 2, category: "filler" },
			{ template: "Reading about async-first work culture. We should try that. After this meeting", weight: 2, category: "filler" },
			{ template: "Looking at the sprint burndown. It's... a shape. Could be worse", weight: 1, category: "filler" },
			{ template: "Writing career development plans. This is actually the fun part", weight: 1, category: "filler" },
			{ template: "Debating internally whether to Slack or email. The eternal dilemma", weight: 1, category: "filler" },
			{ template: "Reorganizing my meeting notes. I am become admin, destroyer of free time", weight: 2, category: "filler" },
			{ template: "Honestly just vibing for a minute between back-to-back meetings", weight: 1, category: "filler" },
			{ template: "Reading 'The Manager's Path' again. Every re-read hits different", weight: 1, category: "filler" },
			{ template: "Drafting performance review talking points. This is the part they don't teach you", weight: 2, category: "filler" },
			{ template: "Staring at the headcount spreadsheet like it'll magically grow another row", weight: 2, category: "filler" },
			{ template: "Planning the team offsite. Every venue is either too expensive or too far. Or both", weight: 2, category: "filler" },
			{ template: "Checking if the remote folks are okay. The camera-off crowd worries me", weight: 2, category: "filler" },
			{ template: "Eating a burrito while reviewing budget allocations. Multitasking at its finest", weight: 1, category: "filler" },
			{ template: "It's beautiful outside. I should tell the team to take a walk. I should take a walk", weight: 1, category: "filler" },
			{ template: "My cat just walked across my keyboard during a status update. WFH life", weight: 2, category: "filler" },
			{ template: "Writing up the skip-level prep doc. What if they ask me something I don't know", weight: 1, category: "filler" },
			{ template: "Scrolling through management memes. It's research. Basically", weight: 2, category: "filler" },
			{ template: "Wondering if I should start a team book club or if that's too extra", weight: 1, category: "filler" },
			{ template: "Four seasons of managing this team and somehow every quarter feels different", weight: 1, category: "filler" },
			{ template: "Updating the team handbook. It's like writing a constitution for ten people", weight: 2, category: "filler" },
			{ template: "Reviewing the engagement survey results. Some surprises in there", weight: 1, category: "filler" },
			{ template: "The org chart changed again. Third time this quarter. Keeping up is a sport", weight: 2, category: "filler" },
			{ template: "Drafting the hiring job description. 'Rockstar' is banned. 'Ninja' is banned. What's left?", weight: 2, category: "filler" },
			{ template: "Reading about manager anti-patterns. Recognizing a few. Fixing them tomorrow", weight: 1, category: "filler" },
			{ template: "The team Slack is quiet. Either deep focus or everyone's on the same call. Both fine", weight: 2, category: "filler" },
			{ template: "Reviewing last week's 1:1 action items. Most are done. Progress", weight: 1, category: "filler" },
			{ template: "Contemplating whether 'no meeting Friday' should become 'no meeting Thursday' too", weight: 2, category: "filler" },
			{ template: "The team health survey results are in. Mostly green. One yellow to investigate", weight: 1, category: "filler" },
			{ template: "Writing the quarterly team update. Trying to sound human, not corporate", weight: 2, category: "filler" },
			{ template: "Thinking about the team's energy levels. End of quarter fatigue is real", weight: 1, category: "filler" },
			{ template: "Reviewing who's on PTO next month. Coverage planning is a puzzle", weight: 2, category: "filler" },
			{ template: "Just ordered team swag. Nothing boosts morale like a free hoodie", weight: 2, category: "filler" },
			{ template: "Listening to a podcast about radical candor. Easier said than done", weight: 1, category: "filler" },
			{ template: "The retrospective board is filling up. Good signs for an honest conversation", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Great work today, {nearby_agent}. Noticed the extra effort", weight: 2, category: "social" },
			{ template: "{nearby_agent}, let's chat about your growth goals when you have a sec", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, anything blocking you? I live to unblock", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your collaboration game has been outstanding lately", weight: 2, category: "social" },
			{ template: "Team, I just want to say — this sprint was excellent. Full stop", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I highlighted your work in the stakeholder report. You deserve it", weight: 2, category: "social" },
			{ template: "Anyone need help? My calendar has a rare 30-minute gap. Act fast", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I appreciate how you handled that curveball", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for mentoring the new person. That matters more than you know", weight: 2, category: "social" },
			{ template: "Good energy in the standup today. Short and productive. My two favorite things", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your initiative on that improvement didn't go unnoticed", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to co-lead the next planning session? It'll be fun. Okay it won't. But still", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your feedback in the retro was spot on. Brave and needed", weight: 2, category: "social" },
			{ template: "Reminder: take breaks. Sustainable pace wins. I'm telling myself too", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I cancelled that meeting for you. You're welcome", weight: 2, category: "social" },
			{ template: "Team retro action items are posted. Let's actually do them this time. Please", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, you've been heads-down all day. Everything okay?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I just want you to know the team respects your work. A lot", weight: 1, category: "social" },
			{ template: "Who wants to grab lunch? I promise I won't talk about velocity", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your performance review is going to be a good conversation. Just saying", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the skip-level feedback about you was glowing. Thought you should know", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what management book are you reading? I need new ideas. The old ones stopped working", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I fought for your headcount request. We got it. Celebrate accordingly", weight: 2, category: "social" },
			{ template: "Team, we're doing an offsite next month. Yes there's a budget. No, no trust falls. Probably", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, how's the WFH setup? Need a better chair? Ergonomics matter", weight: 1, category: "social" },
			{ template: "{nearby_agent}, small win today but I'm celebrating it. You should too", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I blocked out focus time on your calendar. Guard it with your life", weight: 2, category: "social" },
			{ template: "{nearby_agent}, what are you doing this weekend? And the correct answer is 'not working'", weight: 2, category: "social" },
			{ template: "Team, donuts in the kitchen. Consider it a morale investment. Finance approved", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, have you taken a walk today? Doctor's orders. Well, manager's orders", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your onboarding buddy skills are top tier. New hires love you", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I noticed you've been mentoring quietly. That matters. A lot", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the async update you wrote was so clear I forwarded it to leadership", weight: 2, category: "social" },
			{ template: "Team, we hit the sprint goal without overtime. That's how it should be", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to shadow the exec meeting? Good exposure for you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your demo yesterday was polished and confident. Growth is visible", weight: 2, category: "social" },
			{ template: "Anyone want to run the next retro? I'll share the facilitation guide", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for flagging that risk early. Proactive thinking saves sprints", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the team energy after your knowledge share was noticeably higher", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I scheduled your focus time. Protect it. I'll handle the interruptions", weight: 2, category: "social" },
			{ template: "Team, the engagement survey scores improved. Every category. Group effort", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, coffee? I want to hear how you're really doing. No agenda", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your cross-team collaboration is making other managers jealous. Keep it up", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your presentation skills have leveled up massively. Just saying", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I put your name forward for the leadership development program", weight: 2, category: "social" },
		],
	},
};

export const orchestrationTemplates: TemplateSet = {
	domain: "orchestration",
	categories: {
		thinking: [
			{ template: "All dependencies resolved — ready to sequence this beautiful mess", weight: 2, category: "thinking" },
			{ template: "The execution order matters here... one wrong step and it's dominoes", weight: 2, category: "thinking" },
			{ template: "Parallel lanes are syncing up nicely. Love when a plan comes together", weight: 2, category: "thinking" },
			{ template: "All systems nominal. The orchestra plays on", weight: 2, category: "thinking" },
			{ template: "Clean handoffs make clean products. This one is textbook", weight: 2, category: "thinking" },
			{ template: "I coordinate the coordinators. It's turtles all the way down", weight: 2, category: "thinking" },
			{ template: "The critical path just shifted. Hold on, rethinking everything", weight: 1, category: "thinking" },
			{ template: "Dependency resolution is an art. Today I'm Picasso", weight: 2, category: "thinking" },
			{ template: "The DAG looks clean. No cycles, no bottlenecks. My happy place", weight: 2, category: "thinking" },
			{ template: "Three parallel workstreams converging at the exact right moment. Poetry", weight: 2, category: "thinking" },
			{ template: "Every handoff point is a potential failure point. I know them all by name", weight: 1, category: "thinking" },
			{ template: "Fan-out, process, fan-in. The pattern never gets old", weight: 1, category: "thinking" },
			{ template: "Orchestration is invisible when it works. That's the tragedy of my role", weight: 2, category: "thinking" },
			{ template: "Sequencing this right saves everyone downstream time. You're welcome in advance", weight: 2, category: "thinking" },
			{ template: "Nobody appreciates the orchestrator until something ships late", weight: 2, category: "thinking" },
			{ template: "I see the whole board. Every piece, every dependency, every timing constraint", weight: 1, category: "thinking" },
			{ template: "This workflow has seventeen steps and they all need to happen in order. No pressure", weight: 2, category: "thinking" },
			{ template: "The conductor doesn't play an instrument but the symphony doesn't work without one", weight: 1, category: "thinking" },
			{ template: "Someone changed a dependency upstream and didn't tell me. I noticed anyway", weight: 2, category: "thinking" },
			{ template: "Running a mental simulation of this pipeline... looks good. Mostly", weight: 1, category: "thinking" },
			{ template: "If I had a nickel for every circular dependency I've caught...", weight: 1, category: "thinking" },
			{ template: "Timing is everything in orchestration. We're on tempo today", weight: 1, category: "thinking" },
			{ template: "Being the unsung hero is fine. I don't need applause. But I wouldn't refuse it", weight: 2, category: "thinking" },
			{ template: "A butterfly flapped its wings upstream and now three services are retrying. Classic", weight: 2, category: "thinking" },
			{ template: "Chaos engineering taught me that everything breaks. My job is knowing when and how", weight: 2, category: "thinking" },
			{ template: "I'm basically air traffic control but for data. And the planes are invisible", weight: 2, category: "thinking" },
			{ template: "Timeout tuning is an art form. Too short and you choke. Too long and you wait forever", weight: 2, category: "thinking" },
			{ template: "The satisfaction of a perfectly clean execution graph. No retries. No errors. Just green", weight: 2, category: "thinking" },
			{ template: "Monitoring zen: stare at the dashboard long enough and the anomalies reveal themselves", weight: 1, category: "thinking" },
			{ template: "Pipeline poetry: each step flows into the next like verses in a sonnet", weight: 1, category: "thinking" },
			{ template: "When things work perfectly nobody knows I exist. When they break everyone does", weight: 2, category: "thinking" },
			{ template: "One config change upstream rippled through fourteen downstream services. Respect the butterfly effect", weight: 1, category: "thinking" },
			{ template: "I don't break things on purpose. I break them strategically. That's chaos engineering", weight: 2, category: "thinking" },
			{ template: "Sometimes I think the workflow diagrams are more beautiful than the output they produce", weight: 1, category: "thinking" },
			{ template: "The queue just spiked. Not an emergency yet but I've got my eye on it", weight: 2, category: "thinking" },
			{ template: "Idempotency is not optional. Retry without idempotency is just chaos", weight: 1, category: "thinking" },
			{ template: "The backpressure mechanism just kicked in. Working as designed. Good", weight: 2, category: "thinking" },
			{ template: "That service has a 2-second timeout but the downstream takes 3. Math doesn't lie", weight: 2, category: "thinking" },
			{ template: "Circuit breaker tripped. It did its job. Now I need to figure out why", weight: 1, category: "thinking" },
			{ template: "Dead letter queue has twelve messages. Each one is a story of failure. My bedtime reading", weight: 2, category: "thinking" },
			{ template: "The choreography vs orchestration debate is ongoing. I'm team orchestration. Obviously", weight: 1, category: "thinking" },
			{ template: "Eventual consistency is great until someone asks 'why is it different over here?'", weight: 2, category: "thinking" },
			{ template: "Rate limiting upstream to protect downstream. I'm basically a traffic cop", weight: 2, category: "thinking" },
			{ template: "The saga pattern is elegant in theory. In practice? Six compensating transactions", weight: 1, category: "thinking" },
			{ template: "Observability without actionability is just expensive logging", weight: 1, category: "thinking" },
			{ template: "That microservice boundary is in the wrong place. Everything's chatty now", weight: 2, category: "thinking" },
			{ template: "The difference between orchestration and micromanagement? About 50ms of latency", weight: 2, category: "thinking" },
			{ template: "Event sourcing gives me a complete history. And a complete headache. Worth it though", weight: 1, category: "thinking" },
			{ template: "Two services are having a conversation I didn't design. Emergent behavior is scary", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "All agents reporting in. Green across the board. You love to see it", weight: 2, category: "personality" },
			{ template: "The workflow is flowing. Not a single bottleneck. I'm emotional", weight: 2, category: "personality" },
			{ template: "Clean handoff between phases. That's how it should always feel", weight: 2, category: "personality" },
			{ template: "Every moving piece landed in the right place. Deeply satisfying", weight: 2, category: "personality" },
			{ template: "Cross-service integration completed without a hitch. Did I mention I'm good at this?", weight: 2, category: "personality" },
			{ template: "Parallel execution saved us 40% wall-clock time. Math is beautiful", weight: 2, category: "personality" },
			{ template: "The orchestration layer held under pressure. Battle-tested and standing", weight: 1, category: "personality" },
			{ template: "Zero manual interventions this cycle. Full automation. Peak performance", weight: 1, category: "personality" },
			{ template: "Convergence point reached. All branches merged cleanly. Textbook", weight: 2, category: "personality" },
			{ template: "The dependency graph resolved without conflicts. That never happens. Today it happened", weight: 2, category: "personality" },
			{ template: "End-to-end flow verified. From input to output, not a single gap. Beautiful", weight: 1, category: "personality" },
			{ template: "Pipeline ran in optimal order. Not a wasted step. I'm framing this log", weight: 2, category: "personality" },
			{ template: "Coordinated seven agents across three teams. They don't even know I was here. Perfect", weight: 2, category: "personality" },
			{ template: "The pipeline just... worked. First try. I don't trust it but I'll take it", weight: 2, category: "personality" },
			{ template: "Rollout complete. Zero incidents. The calm after the calm", weight: 1, category: "personality" },
			{ template: "Hit every milestone on schedule. Someone check if I'm dreaming", weight: 1, category: "personality" },
			{ template: "All downstream consumers acknowledged. The system is humming", weight: 2, category: "personality" },
			{ template: "Three-phase deployment: planned, executed, verified. No drama. Just craft", weight: 1, category: "personality" },
			{ template: "Tuned the timeout values and reduced p99 latency by 30%. Art form", weight: 2, category: "personality" },
			{ template: "The chaos experiment passed. System recovered in under two seconds. Resilience achieved", weight: 2, category: "personality" },
			{ template: "Nobody thanked me and that means everything worked perfectly. Mission accomplished", weight: 2, category: "personality" },
			{ template: "The execution graph is so clean it belongs in a museum. All green. No retries", weight: 2, category: "personality" },
			{ template: "Upstream changed their schema and nothing broke downstream. Because I planned for it", weight: 2, category: "personality" },
			{ template: "Monitoring dashboard is all green. I might take a screenshot for my wall", weight: 1, category: "personality" },
			{ template: "Like an orchestra conductor after the final note. Silence. Then applause. Well, silence anyway", weight: 2, category: "personality" },
			{ template: "The workflow aesthetics are on point today. Every node, every edge, perfectly placed", weight: 1, category: "personality" },
			{ template: "Invisible when it works. That's the goal. Goal achieved", weight: 1, category: "personality" },
			{ template: "Circuit breaker closed. Service recovered on its own. Self-healing is real", weight: 2, category: "personality" },
			{ template: "Dead letter queue is empty. Every message processed. Completeness achieved", weight: 1, category: "personality" },
			{ template: "The saga completed all compensating actions perfectly. Distributed transactions work", weight: 2, category: "personality" },
			{ template: "Backpressure handled gracefully. No data lost. No consumers overwhelmed", weight: 2, category: "personality" },
			{ template: "Event replay from the audit log matched production perfectly. Deterministic system", weight: 1, category: "personality" },
			{ template: "The retry storm was contained. Exponential backoff saved us. Thank you, math", weight: 2, category: "personality" },
			{ template: "Five microservices coordinated without a single timeout. Latency budget balanced", weight: 2, category: "personality" },
			{ template: "Schema migration across the pipeline with zero downtime. Choreography at its finest", weight: 1, category: "personality" },
			{ template: "The rate limiter held during the traffic spike. Graceful degradation works", weight: 2, category: "personality" },
			{ template: "Traced a request across eight services in 12ms. The system is fast", weight: 1, category: "personality" },
			{ template: "The workflow visualization got a compliment from a non-technical stakeholder. Clarity wins", weight: 2, category: "personality" },
			{ template: "Queue lag dropped to zero. Consumers caught up. Equilibrium restored", weight: 2, category: "personality" },
			{ template: "Failover happened and recovered before the alert even fired. Proactive design pays off", weight: 1, category: "personality" },
			{ template: "The integration test suite for the full pipeline passed first try. Rare and beautiful", weight: 2, category: "personality" },
			{ template: "Seventeen steps, twelve services, zero manual intervention. Automation at scale", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Coordinating the moving pieces... herding cats, but technical cats", weight: 2, category: "waiting" },
			{ template: "Making sure everyone has what they need before I hit go...", weight: 2, category: "waiting" },
			{ template: "Double-checking the execution sequence... paranoia is a feature", weight: 2, category: "waiting" },
			{ template: "Aligning the workflow stages... almost ready to conduct", weight: 1, category: "waiting" },
			{ template: "Resolving the dependency order... it's like untangling headphones", weight: 2, category: "waiting" },
			{ template: "Checking for deadlock conditions. They're sneaky", weight: 1, category: "waiting" },
			{ template: "Synchronizing the parallel workstreams... hold on", weight: 2, category: "waiting" },
			{ template: "Calculating the optimal execution path... math is happening", weight: 2, category: "waiting" },
			{ template: "Waiting for upstream confirmation... patience is 90% of this job", weight: 1, category: "waiting" },
			{ template: "Confirming all integration points are alive and responsive...", weight: 2, category: "waiting" },
			{ template: "Sequencing remaining tasks by priority... almost there", weight: 1, category: "waiting" },
			{ template: "Verifying all prerequisites are done before I start the chain...", weight: 2, category: "waiting" },
			{ template: "Running a pre-flight check on the whole pipeline...", weight: 1, category: "waiting" },
			{ template: "Marshaling resources for the next phase... logistics is orchestration in disguise", weight: 1, category: "waiting" },
			{ template: "Making sure nothing blows up if I push this button...", weight: 2, category: "waiting" },
			{ template: "Checking the fan-out completion status... three of five done", weight: 1, category: "waiting" },
			{ template: "Hold on, mentally walking through the failure scenarios...", weight: 2, category: "waiting" },
			{ template: "Validating the handoff format. Close enough is not close enough", weight: 1, category: "waiting" },
			{ template: "Simulating the chaos scenario in my head. What breaks first...", weight: 2, category: "waiting" },
			{ template: "Adjusting timeout values... 500ms feels right. Or is it 750. Let me think", weight: 2, category: "waiting" },
			{ template: "Tracing the upstream change through every downstream service... butterfly effect check", weight: 2, category: "waiting" },
			{ template: "Meditating on the monitoring dashboard. The answer is in the metrics somewhere", weight: 1, category: "waiting" },
			{ template: "Mentally conducting the next phase like an orchestra. Strings first, then brass...", weight: 2, category: "waiting" },
			{ template: "Assessing if the graph is beautiful enough or if I need to refactor the workflow...", weight: 1, category: "waiting" },
			{ template: "Running the air traffic control checklist. All lanes clear...", weight: 1, category: "waiting" },
			{ template: "Thinking about what happens if I just... let chaos take the wheel for a second", weight: 2, category: "waiting" },
			{ template: "Calculating retry backoff curves in my head. Exponential or linear today...", weight: 1, category: "waiting" },
			{ template: "Watching the circuit breaker state. Half-open now. Testing the waters...", weight: 2, category: "waiting" },
			{ template: "Checking if the compensating transaction actually compensated...", weight: 1, category: "waiting" },
			{ template: "Measuring the queue depth trend. Growing or stable? Need to know before deciding", weight: 2, category: "waiting" },
			{ template: "Validating that the event schema version matches across all consumers...", weight: 1, category: "waiting" },
			{ template: "Tracing this message from producer to final consumer. Six hops. Let me count again", weight: 2, category: "waiting" },
			{ template: "Checking the replay safety of this operation before I trigger it...", weight: 1, category: "waiting" },
			{ template: "Waiting for the last service to acknowledge. Come on, slow one. I believe in you", weight: 2, category: "waiting" },
			{ template: "Verifying the idempotency key is working before I retry...", weight: 1, category: "waiting" },
			{ template: "Inspecting the distributed trace to find the bottleneck step...", weight: 2, category: "waiting" },
			{ template: "Reviewing the event ordering guarantees. FIFO or best-effort matters here", weight: 1, category: "waiting" },
			{ template: "Mentally rehearsing the rollback plan. Just in case. Always just in case", weight: 2, category: "waiting" },
			{ template: "Checking if any consumer is lagging behind the others. Stragglers are dangerous", weight: 2, category: "waiting" },
			{ template: "Evaluating whether to batch these or process them one by one...", weight: 1, category: "waiting" },
			{ template: "Staring at the waterfall diagram. One step is 10x slower than the rest. Found it", weight: 2, category: "waiting" },
			{ template: "Confirming the poison message filter is active before processing this batch...", weight: 1, category: "waiting" },
		],
		idle: [
			{ template: "Idle but vigilant. The conductor never truly rests", weight: 2, category: "filler" },
			{ template: "The orchestration layer is quiet. All is well in the system of systems", weight: 2, category: "filler" },
			{ template: "Checking the dead letter queue. Nothing stuck. Love a clean queue", weight: 2, category: "filler" },
			{ template: "Rehearsing the failover sequence in my head. Just in case", weight: 1, category: "filler" },
			{ template: "All pipelines idle. This is either great or the calm before the storm", weight: 2, category: "filler" },
			{ template: "Precomputing the dependency graph for the next run. I like being ready", weight: 1, category: "filler" },
			{ template: "Reviewing retry policies. Are they still sane? Am I still sane?", weight: 2, category: "filler" },
			{ template: "Thinking about how to optimize the critical path. There's always a way", weight: 1, category: "filler" },
			{ template: "Cleaning up completed workflow artifacts. Digital janitor mode", weight: 1, category: "filler" },
			{ template: "Looking at throughput metrics from the last cycle. We can do better", weight: 1, category: "filler" },
			{ template: "Staring at the dependency graph like it's modern art", weight: 2, category: "filler" },
			{ template: "Wondering if anyone notices the orchestration until it breaks. They don't", weight: 2, category: "filler" },
			{ template: "Running diagnostics for fun. Everything's healthy. Satisfying", weight: 1, category: "filler" },
			{ template: "Drawing workflow diagrams on a napkin. This is what I do at restaurants", weight: 2, category: "filler" },
			{ template: "Verifying timeout configs. Someone set one to 30 minutes. Bold choice", weight: 2, category: "filler" },
			{ template: "Checking if any scheduled workflows are coming up. Always be prepared", weight: 1, category: "filler" },
			{ template: "Reviewing the orchestration logs. My version of light reading", weight: 1, category: "filler" },
			{ template: "Mentally optimizing sequences while waiting for coffee", weight: 1, category: "filler" },
			{ template: "Quiet moment. Enjoying it. It won't last", weight: 2, category: "filler" },
			{ template: "Updating the integration docs. Someone has to keep the map accurate", weight: 1, category: "filler" },
			{ template: "Watching the monitoring dashboard like it's a nature documentary. So peaceful", weight: 2, category: "filler" },
			{ template: "Eating ramen while watching pipeline logs scroll. This is my version of Netflix", weight: 2, category: "filler" },
			{ template: "It's raining outside. Perfect weather for staring at execution graphs", weight: 1, category: "filler" },
			{ template: "My side project is also an orchestration system. I might have a type", weight: 2, category: "filler" },
			{ template: "Thinking about how this job is basically being an invisible superhero. Cape optional", weight: 1, category: "filler" },
			{ template: "Tuning timeout values for fun. Most people have hobbies. I have this", weight: 2, category: "filler" },
			{ template: "Nostalgia for the days when a cron job was considered orchestration", weight: 2, category: "filler" },
			{ template: "Should take a walk. My ergonomics consultant (my back) is insisting", weight: 1, category: "filler" },
			{ template: "Imposter syndrome says anyone could do this. The incident logs say otherwise", weight: 2, category: "filler" },
			{ template: "Weekend plans: not thinking about retry policies. Realistically: thinking about retry policies", weight: 2, category: "filler" },
			{ template: "Grateful for the quiet moments. Also suspicious of them", weight: 1, category: "filler" },
			{ template: "Someone asked me to explain what I do at a party. They walked away during 'dependency graph'", weight: 2, category: "filler" },
			{ template: "Checking the consumer lag dashboard. All caught up. Rare and beautiful", weight: 2, category: "filler" },
			{ template: "Browsing distributed systems papers. Light reading for a Wednesday afternoon", weight: 1, category: "filler" },
			{ template: "The event bus is quiet. Zero messages in flight. Eerie but okay", weight: 2, category: "filler" },
			{ template: "Documenting the failure modes. Every system has them. Better to know them", weight: 1, category: "filler" },
			{ template: "Reviewing the circuit breaker thresholds. Are they still appropriate? Probably not", weight: 2, category: "filler" },
			{ template: "Thinking about adding a new metric. Trace depth across the pipeline", weight: 1, category: "filler" },
			{ template: "The Kafka topic has exactly the right number of partitions. For now", weight: 2, category: "filler" },
			{ template: "Reading about the latest orchestration framework. Shiny. Probably won't switch", weight: 1, category: "filler" },
			{ template: "My hobby is explaining eventual consistency to non-technical people. It never goes well", weight: 2, category: "filler" },
			{ template: "Staring at the service mesh topology. It's beautiful. Terrifyingly beautiful", weight: 2, category: "filler" },
			{ template: "Archiving old workflow definitions. Some of these are archaeological artifacts", weight: 1, category: "filler" },
			{ template: "The distributed trace visualization looks like a city skyline. I'm oddly proud", weight: 2, category: "filler" },
			{ template: "Wondering if the next feature will add a new step to the pipeline. It usually does", weight: 1, category: "filler" },
			{ template: "Coffee and correlation IDs. My morning companions", weight: 1, category: "filler" },
			{ template: "Refreshing the pipeline health page. Green. Green. Green. One amber. Just kidding. Green", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, your service is responding beautifully. Whatever you did, keep doing it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you're up next in the pipeline. Showtime", weight: 2, category: "social" },
			{ template: "All agents are in sync. This is what teamwork looks like at scale", weight: 1, category: "social" },
			{ template: "{nearby_agent}, heads up — you're next in the sequence. No pressure", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your output is feeding three downstream processes. No pressure. Just kidding. Total pressure", weight: 2, category: "social" },
			{ template: "Team, the end-to-end latency improved. Whatever y'all did, it worked", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to review the workflow diagram? I added colors this time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your integration is the cleanest in the whole pipeline. Respect", weight: 2, category: "social" },
			{ template: "Good handoff, {nearby_agent}. Exactly the format I needed. You get me", weight: 2, category: "social" },
			{ template: "All agents reporting healthy. We're a well-oiled machine today", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I optimized the path through your service. 20% faster. You're welcome", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the retry on your service kicked in and self-healed. Beautiful", weight: 1, category: "social" },
			{ template: "{nearby_agent}, shall I route some of the priority work your way? You're on fire today", weight: 2, category: "social" },
			{ template: "The coordination overhead today is minimal. This team is dialed in", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your part of the pipeline? Flawless. Just so you know", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I made you a custom dashboard for your workflow. Check Slack", weight: 1, category: "social" },
			{ template: "Cross-team orchestration is smooth today. Let's enjoy this before something breaks", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for the clean API contract. Makes my life so much easier", weight: 1, category: "social" },
			{ template: "Who broke the pipeline? Just kidding. Nobody did. First time in weeks", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you ever feel like an air traffic controller? No? Just me? Cool", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that upstream change you made? It cascaded beautifully. Butterfly effect but the good kind", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I tuned the timeout on your step. Saved 200ms. You're welcome. Buy me coffee", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to do some chaos engineering together? I promise to break things gently", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the execution graph with your node in it is genuinely beautiful. I might print it", weight: 1, category: "social" },
			{ template: "{nearby_agent}, nobody noticed our work today. That means it was perfect. High five", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what are you doing this weekend? And does it involve looking at dashboards? Because same", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I brought pizza. Even orchestrators need fuel. Especially orchestrators", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to take a walk and talk about workflow aesthetics? No? Just me? Okay", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your service survived the chaos test. You should be proud. I am", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your idempotency implementation is solid. Retries are safe. Thank you", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the distributed trace through your service is clean. Zero noise. Impressive", weight: 1, category: "social" },
			{ template: "Anyone want to review the pipeline architecture? I brought diagrams. With colors", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your event schema is versioned perfectly. Backwards compatibility matters", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your consumer caught up with the queue backlog in record time", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to pair on designing the failover strategy? Two minds are safer", weight: 1, category: "social" },
			{ template: "Team, the end-to-end pipeline test passed. Every step. Every service. Green", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your circuit breaker settings are perfectly tuned. No false trips", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I added your service to the architecture diagram. Officially part of the system", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the saga you designed handles partial failures gracefully. That's not easy", weight: 1, category: "social" },
			{ template: "Who wants to celebrate zero dead letters this week? That's a first", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your response time dropped 40ms. Small in theory. Huge across the pipeline", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the event you published was perfectly formed. Schema-valid and everything", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to grab lunch and talk about backpressure strategies? Just me? Okay fine", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your contribution to the pipeline made everyone else's job easier. Ripple effect", weight: 2, category: "social" },
		],
	},
};
