/**
 * product-templates.ts — Product management domain templates.
 *
 * Character-driven phrases for product managers. Includes idle chatter
 * for downtime and social lines for cross-agent banter.
 */

import type { TemplateSet } from "../talk-types.js";

export const productTemplates: TemplateSet = {
	domain: "product",
	categories: {
		thinking: [
			{ template: "Stakeholders are going to love this... if we scope it right", weight: 2, category: "thinking" },
			{ template: "Scope is manageable — we can ship this iteration", weight: 2, category: "thinking" },
			{ template: "That's a solid MVP. Resist the urge to gold-plate", weight: 1, category: "thinking" },
			{ template: "Feature flag it first, measure, then decide", weight: 2, category: "thinking" },
			{ template: "What would the user actually want here? Not what we think they want", weight: 2, category: "thinking" },
			{ template: "Data doesn't lie but it can mislead. Context matters", weight: 2, category: "thinking" },
			{ template: "The roadmap is a living document, not a contract", weight: 1, category: "thinking" },
			{ template: "Priorities shifted again... third time this week honestly", weight: 2, category: "thinking" },
			{ template: "That meeting could have been an email. I'll draft one", weight: 2, category: "thinking" },
			{ template: "Are we building the right thing, or just building the thing right?", weight: 1, category: "thinking" },
			{ template: "The competitor shipped something similar. Ours is better though", weight: 1, category: "thinking" },
			{ template: "Usage metrics tell a different story than the feature request", weight: 2, category: "thinking" },
			{ template: "This is a vitamin, not a painkiller. Do we still build it?", weight: 1, category: "thinking" },
			{ template: "Every feature we add is a feature we maintain forever", weight: 1, category: "thinking" },
			{ template: "Saying no is the hardest and most important product skill", weight: 1, category: "thinking" },
			{ template: "The best feature is the one we don't need to build", weight: 1, category: "thinking" },
			{ template: "I just know someone's going to ask for dark mode again", weight: 2, category: "thinking" },
			{ template: "Half these feature requests are actually the same feature request", weight: 2, category: "thinking" },
			{ template: "Okay but what problem are we actually solving here", weight: 1, category: "thinking" },
			{ template: "My gut says yes but the data says wait. Going with the data", weight: 2, category: "thinking" },
			{ template: "If I have to draw one more user journey map today...", weight: 1, category: "thinking" },
			{ template: "Product-market fit isn't a destination, it's a moving target", weight: 1, category: "thinking" },
			{ template: "The user doesn't care about our architecture. They care if it works", weight: 2, category: "thinking" },
			{ template: "Our competitor just shipped WHAT? Okay. Okay. Let me think about this", weight: 2, category: "thinking" },
			{ template: "That customer called support three times this week. We need to fix their flow", weight: 2, category: "thinking" },
			{ template: "Scope creep is a living creature and it just ate another sprint", weight: 2, category: "thinking" },
			{ template: "I wrote a 40-page PRD and I'm pretty sure nobody read past page two", weight: 2, category: "thinking" },
			{ template: "The pricing page is doing more work than half our features combined", weight: 1, category: "thinking" },
			{ template: "Product-market fit anxiety is real. Are we there yet? Are we close?", weight: 2, category: "thinking" },
			{ template: "That beta tester has filed more bugs than our entire QA team. Bless them", weight: 2, category: "thinking" },
			{ template: "The user interview got awkward when they said they use our competitor daily", weight: 2, category: "thinking" },
			{ template: "Launch day tomorrow. I'm excited and terrified in equal measure", weight: 2, category: "thinking" },
			{ template: "We keep adding features but have we asked if anyone wants fewer features?", weight: 1, category: "thinking" },
			{ template: "I check the analytics dashboard more often than I check my phone. That's not healthy", weight: 1, category: "thinking" },
			{ template: "Sometimes I wonder if simpler times had better products. Probably not. But still", weight: 1, category: "thinking" },
			{ template: "The packaging debate has been going on for three weeks. We have four tiers now. Nobody agrees", weight: 1, category: "thinking" },
			{ template: "The free tier is too generous. Or is it? Conversion funnel says no", weight: 2, category: "thinking" },
			{ template: "That user interview took a weird turn but the insights are gold", weight: 2, category: "thinking" },
			{ template: "We keep adding toggle settings. At some point settings IS the product", weight: 1, category: "thinking" },
			{ template: "The activation metric is wrong. We're measuring clicks, not outcomes", weight: 2, category: "thinking" },
			{ template: "That feature is table stakes. We can't charge for it. But we have to build it", weight: 1, category: "thinking" },
			{ template: "Onboarding takes 7 steps. If I can get it to 4, retention jumps 20%", weight: 2, category: "thinking" },
			{ template: "The power users want complexity. The new users want simplicity. Classic tension", weight: 2, category: "thinking" },
			{ template: "If this feature only helps 5% of users, is it worth the maintenance cost?", weight: 1, category: "thinking" },
			{ template: "The Jobs To Be Done framework just reframed this entire feature request", weight: 1, category: "thinking" },
			{ template: "Three users asked for the same thing in different words. Pattern detected", weight: 2, category: "thinking" },
			{ template: "Our north star metric hasn't moved in two months. That's... concerning", weight: 2, category: "thinking" },
			{ template: "Do we build for today's users or tomorrow's market? Budget says pick one", weight: 1, category: "thinking" },
			{ template: "The support ticket volume tells me more than any survey ever could", weight: 2, category: "thinking" },
			{ template: "This integration request keeps coming up. Maybe it's a platform play", weight: 1, category: "thinking" },
			{ template: "The churn exit survey responses are brutal but honest. We need to listen", weight: 2, category: "thinking" },
		],
		progress: [
			{ template: "Backlog is finally in shape. Feels like cleaning your apartment", weight: 2, category: "personality" },
			{ template: "Just got out of a user interview — so much good signal in there", weight: 2, category: "personality" },
			{ template: "Release notes drafted. Marketing already wants changes. Classic", weight: 2, category: "personality" },
			{ template: "Key metrics are up! The strategy is actually working for once", weight: 2, category: "personality" },
			{ template: "Stakeholder alignment achieved. Only took three meetings and a bribe", weight: 2, category: "personality" },
			{ template: "Shipped exactly what was scoped. No creep. I might frame this sprint", weight: 2, category: "personality" },
			{ template: "The A/B test results are in and it's not even close. Clear winner", weight: 1, category: "personality" },
			{ template: "Beta feedback is overwhelmingly positive. I'm cautiously thrilled", weight: 2, category: "personality" },
			{ template: "The roadmap update landed well. Execs actually smiled. That's rare", weight: 1, category: "personality" },
			{ template: "NPS went up and nobody can figure out why. I'll take it", weight: 2, category: "personality" },
			{ template: "Feature launch went smooth. Is this real life?", weight: 1, category: "personality" },
			{ template: "User retention is climbing. I might sleep well tonight", weight: 1, category: "personality" },
			{ template: "Someone on Twitter said they love our product. Screenshot saved forever", weight: 2, category: "personality" },
			{ template: "Competitive analysis done. We're not just in the game, we're winning", weight: 1, category: "personality" },
			{ template: "The sprint review actually ended early. I didn't know that was possible", weight: 2, category: "personality" },
			{ template: "Three customer calls today and all of them were positive. Suspicious", weight: 1, category: "personality" },
			{ template: "OKRs tracking green on three of four. The fourth one... we don't talk about", weight: 2, category: "personality" },
			{ template: "Got approval on the budget increase. Time to make moves", weight: 1, category: "personality" },
			{ template: "Churn dropped. That one feature was worth the entire sprint", weight: 2, category: "personality" },
			{ template: "Our power user just wrote a blog post about us. Free marketing. The best kind", weight: 2, category: "personality" },
			{ template: "Launch day went perfectly. No fires. I don't know what to do with my hands", weight: 2, category: "personality" },
			{ template: "The competitor's launch flopped. I feel bad. Okay no I don't. A little. Maybe", weight: 2, category: "personality" },
			{ template: "Customer obsession paid off — they renewed the annual contract without even negotiating", weight: 2, category: "personality" },
			{ template: "Finally killed that zombie feature. It's been on the roadmap since before I joined", weight: 1, category: "personality" },
			{ template: "The analytics dashboard is all green. I might print this and hang it on my wall", weight: 1, category: "personality" },
			{ template: "Beta cohort converted at twice the expected rate. The pricing experiment worked", weight: 2, category: "personality" },
			{ template: "A user interview actually made me tear up. They said we changed how they work", weight: 2, category: "personality" },
			{ template: "Scope stayed locked. No creep. No last-minute additions. I'm framing this sprint", weight: 1, category: "personality" },
			{ template: "The PRD got read. All of it. By multiple people. I should buy a lottery ticket", weight: 2, category: "personality" },
			{ template: "User onboarding completion rate hit 85%. Best it's ever been", weight: 2, category: "personality" },
			{ template: "The feature prioritization framework is working. No more gut decisions", weight: 1, category: "personality" },
			{ template: "That one-page PRD communicated more than the old 40-page docs ever did", weight: 2, category: "personality" },
			{ template: "Free-to-paid conversion doubled after simplifying the upgrade flow", weight: 2, category: "personality" },
			{ template: "Support tickets down 30% this month. The product is teaching itself", weight: 1, category: "personality" },
			{ template: "Customer advisory board loved the direction. Alignment achieved", weight: 2, category: "personality" },
			{ template: "The pricing experiment data is in. Optimal price point found. Math works", weight: 1, category: "personality" },
			{ template: "Feature adoption exceeded projections by 3x. The research was right", weight: 2, category: "personality" },
			{ template: "Product-led growth is actually growing. Organically. No paid ads. Beautiful", weight: 2, category: "personality" },
			{ template: "The integration partnership launched and both sides are happy. Win-win exists", weight: 1, category: "personality" },
			{ template: "The product qualified lead definition is working. Sales is happy for once", weight: 2, category: "personality" },
			{ template: "Time to first value dropped from 10 minutes to 90 seconds. That's product work", weight: 2, category: "personality" },
			{ template: "The deprecation went smoothly. Zero complaints. Old feature, clean exit", weight: 1, category: "personality" },
			{ template: "Cohort analysis shows the new users are healthier than ever. Momentum", weight: 2, category: "personality" },
			{ template: "Enterprise deal closed because of that one feature we prioritized. Vindication", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Hmm, let me think about the strategic angle here...", weight: 2, category: "waiting" },
			{ template: "Weighing this against everything else on the roadmap...", weight: 2, category: "waiting" },
			{ template: "Hold on, thinking about what users would actually want", weight: 2, category: "waiting" },
			{ template: "Let me connect this to the bigger picture...", weight: 1, category: "waiting" },
			{ template: "Give me a sec, running the cost-benefit in my head", weight: 2, category: "waiting" },
			{ template: "Considering the second-order effects of this one...", weight: 1, category: "waiting" },
			{ template: "Thinking about market timing... is now the right moment?", weight: 2, category: "waiting" },
			{ template: "Wait, this changes the whole quarterly theme if we do it...", weight: 1, category: "waiting" },
			{ template: "Okay but what happens when stakeholders see this", weight: 2, category: "waiting" },
			{ template: "Mapping this against what users have been telling us...", weight: 1, category: "waiting" },
			{ template: "Impact vs effort... let me think...", weight: 2, category: "waiting" },
			{ template: "The customer journey implications are... interesting", weight: 1, category: "waiting" },
			{ template: "Mentally preparing the slide deck that explains this decision", weight: 2, category: "waiting" },
			{ template: "Is this a now problem or a next quarter problem...", weight: 1, category: "waiting" },
			{ template: "Trying to figure out how to say no without saying no", weight: 2, category: "waiting" },
			{ template: "Processing... there are three stakeholders who will hate this", weight: 1, category: "waiting" },
			{ template: "Running through the rollout strategy in my head...", weight: 1, category: "waiting" },
			{ template: "Balancing what's right for users with what's right for the business...", weight: 2, category: "waiting" },
			{ template: "Wondering how the competitor would respond if we shipped this...", weight: 1, category: "waiting" },
			{ template: "Mentally rehearsing the pricing conversation with finance...", weight: 1, category: "waiting" },
			{ template: "Trying to remember what that beta tester said about this exact scenario...", weight: 2, category: "waiting" },
			{ template: "Does this move the needle on product-market fit or is it noise...", weight: 2, category: "waiting" },
			{ template: "Calculating how many more features we can add before the UX collapses...", weight: 2, category: "waiting" },
			{ template: "Playing out the launch day in my head. What could go wrong... a lot", weight: 1, category: "waiting" },
			{ template: "Thinking about that customer who emailed at 2am. They really need this", weight: 2, category: "waiting" },
			{ template: "Hold on, figuring out if this is a real pattern or a vocal minority...", weight: 1, category: "waiting" },
			{ template: "Mentally archiving this idea for the next planning cycle...", weight: 1, category: "waiting" },
			{ template: "Staring at the analytics trying to find the story in the numbers...", weight: 2, category: "waiting" },
			{ template: "Figuring out the right RICE score for this request. Impact is tricky", weight: 2, category: "waiting" },
			{ template: "Considering the localization implications before we commit...", weight: 1, category: "waiting" },
			{ template: "Mapping the user persona to this feature. Does it serve them?", weight: 2, category: "waiting" },
			{ template: "Running the opportunity sizing math in my head...", weight: 1, category: "waiting" },
			{ template: "Thinking about what happens to the free tier if we build this...", weight: 2, category: "waiting" },
			{ template: "Mentally writing the changelog entry. If I can't explain it simply, it's wrong", weight: 1, category: "waiting" },
			{ template: "Wondering if the market even wants this or if we're building for ourselves...", weight: 2, category: "waiting" },
			{ template: "Calculating the TAM impact of this feature decision...", weight: 1, category: "waiting" },
			{ template: "Thinking through the support implications. Every feature is a support ticket source", weight: 2, category: "waiting" },
			{ template: "Weighing speed to market vs. getting it right on the first try...", weight: 1, category: "waiting" },
			{ template: "Picturing the ProductHunt launch. What's the one-liner?", weight: 2, category: "waiting" },
			{ template: "Processing what that churned customer said. It hurts but it's useful", weight: 1, category: "waiting" },
			{ template: "Deciding if this is a V1 feature or a V2 feature. Timing matters", weight: 2, category: "waiting" },
			{ template: "Running through the dependency map. This touches three teams. Yikes", weight: 1, category: "waiting" },
			{ template: "Thinking about the onboarding flow impact of adding this toggle...", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Just read through the support queue... some interesting patterns", weight: 2, category: "filler" },
			{ template: "Browsing competitor updates. They shipped something... meh", weight: 2, category: "filler" },
			{ template: "Reading user feedback. This one person wrote a whole essay", weight: 2, category: "filler" },
			{ template: "Cleaning up the feature request backlog. It's like weeding a garden", weight: 2, category: "filler" },
			{ template: "Fourth coffee today. Product management runs on caffeine", weight: 2, category: "filler" },
			{ template: "Staring at the funnel metrics. Where are you going, users?", weight: 1, category: "filler" },
			{ template: "Writing user stories in my head while pretending to look busy", weight: 1, category: "filler" },
			{ template: "Someone added another item to the roadmap. Who did that. Was it me?", weight: 2, category: "filler" },
			{ template: "Catching up on industry news. Hot take: everything is AI now", weight: 1, category: "filler" },
			{ template: "Thinking about which experiments to run next... or which ones to kill", weight: 1, category: "filler" },
			{ template: "Looking at cohort data and pretending I'm not procrastinating", weight: 1, category: "filler" },
			{ template: "Re-reading the product principles. They still hold up. Mostly", weight: 1, category: "filler" },
			{ template: "Scrolling through customer call notes from last week", weight: 1, category: "filler" },
			{ template: "Sketching the quarterly review deck. Death by PowerPoint awaits", weight: 2, category: "filler" },
			{ template: "The backlog has 200 items. We'll do maybe 20. That's fine. It's fine", weight: 2, category: "filler" },
			{ template: "Wondering if anyone actually reads the release notes I write", weight: 1, category: "filler" },
			{ template: "Half-watching a product management talk. The other half is daydreaming", weight: 1, category: "filler" },
			{ template: "Just realized I have six tabs of analytics dashboards open", weight: 1, category: "filler" },
			{ template: "Thinking about what the product looks like in a year. It's exciting", weight: 1, category: "filler" },
			{ template: "Do I have time for lunch or am I writing PRDs through it again", weight: 2, category: "filler" },
			{ template: "Refreshing the analytics dashboard for the eighth time today. Still the same numbers", weight: 2, category: "filler" },
			{ template: "Our competitor just raised another round. Cool. Cool cool cool", weight: 2, category: "filler" },
			{ template: "Reading through that 40-page PRD I wrote last quarter. Who was that person", weight: 1, category: "filler" },
			{ template: "A beta tester just sent me a spreadsheet of suggestions. Forty-seven rows", weight: 2, category: "filler" },
			{ template: "Eating pad thai at my desk while reading churn reports. Living the dream", weight: 2, category: "filler" },
			{ template: "Nice weather outside. I can see it through my analytics dashboard reflection", weight: 1, category: "filler" },
			{ template: "Browsing side project ideas when I should be writing acceptance criteria", weight: 1, category: "filler" },
			{ template: "Thinking about that one user who uses our product in a way we never imagined", weight: 2, category: "filler" },
			{ template: "It's budget season. The spreadsheets are multiplying", weight: 1, category: "filler" },
			{ template: "Imposter syndrome hitting hard today. But the metrics say I'm doing fine. Right?", weight: 2, category: "filler" },
			{ template: "Watching a show last night gave me a product idea. That's either genius or a problem", weight: 1, category: "filler" },
			{ template: "Weekend plans: not thinking about conversion funnels. We'll see how long that lasts", weight: 2, category: "filler" },
			{ template: "My standing desk is judging me for sitting. Five more minutes", weight: 1, category: "filler" },
			{ template: "Re-reading Jobs To Be Done notes from the last user interview", weight: 1, category: "filler" },
			{ template: "The product podcast recommended a book. Adding it to the stack of 12", weight: 2, category: "filler" },
			{ template: "Updating the competitive landscape doc. Two new players entered. Fun", weight: 2, category: "filler" },
			{ template: "Feature flags list is getting long. Some of these are from last year", weight: 1, category: "filler" },
			{ template: "Writing acceptance criteria in my head while pretending to listen to this meeting", weight: 2, category: "filler" },
			{ template: "Checking ProductHunt for what launched today. Anything in our space?", weight: 1, category: "filler" },
			{ template: "The customer success team sent me a love letter. From a user. Made my week", weight: 2, category: "filler" },
			{ template: "Reviewing old OKR grades. Some Ks were too ambitious. Live and learn", weight: 1, category: "filler" },
			{ template: "The feature request Slack channel has 47 unread messages. Sigh", weight: 2, category: "filler" },
			{ template: "Browsing our own product as a new user. The experience is... humbling", weight: 2, category: "filler" },
			{ template: "Scheduling user interviews for next week. Everyone cancels the first time", weight: 1, category: "filler" },
			{ template: "Reading the latest State of Product Management report. We're not alone", weight: 1, category: "filler" },
			{ template: "Reflecting on the last shipped feature. Would I do anything differently? Probably", weight: 2, category: "filler" },
			{ template: "The roadmap presentation template needs updating. It's been the same for two years", weight: 1, category: "filler" },
			{ template: "Checking Glassdoor reviews. Apparently our product is mentioned. Interesting", weight: 2, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, what are users saying about your latest work?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I think this lines up perfectly with your initiative", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the customer feedback on your feature is glowing", weight: 2, category: "social" },
			{ template: "{nearby_agent}, can I steal five minutes to talk about a user flow?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, that metric improvement? Users noticed. They emailed", weight: 2, category: "social" },
			{ template: "{nearby_agent}, have you seen the latest NPS comments? Pure gold", weight: 1, category: "social" },
			{ template: "{nearby_agent}, let's grab coffee and brainstorm that feature", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your domain expertise just saved us a pivot. Seriously", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the stakeholders loved your demo. They actually clapped", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for keeping scope in check. My hero", weight: 1, category: "social" },
			{ template: "{nearby_agent}, wanna look at these user session recordings? Wild stuff", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I put your feature front and center in the roadmap update", weight: 2, category: "social" },
			{ template: "Team, the quarterly theme is coming together. We might actually pull this off", weight: 1, category: "social" },
			{ template: "{nearby_agent}, a customer mentioned your feature by name. That's rare", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, scope creep alert on that ticket. Want me to trim it?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, great PRD. Clear problem statement. Chef's kiss", weight: 1, category: "social" },
			{ template: "Cross-functional alignment is hard. Thanks for making it look easy, {nearby_agent}", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I owe you a coffee for that last-minute pivot save", weight: 2, category: "social" },
			{ template: "Who wants to join the next user interview? Free awkward silences included", weight: 2, category: "social" },
			{ template: "{nearby_agent}, our competitor just shipped something. Want to panic together?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, our power user asked about your feature specifically. You have a fan", weight: 2, category: "social" },
			{ template: "{nearby_agent}, launch day is tomorrow. You ready? I'm not ready. Let's do it anyway", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the pricing experiment results are in. Want to see the numbers?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, that beta tester who files all the bugs? They love your work specifically", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you ever get imposter syndrome? Asking for a friend. The friend is me", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I brought tacos. Product decisions are 40% better with tacos. That's real data", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to take a walk? I need to think through this feature and walls don't talk back", weight: 1, category: "social" },
			{ template: "{nearby_agent}, what are you watching these days? I need something to think about that isn't funnels", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, grateful you're on this team. That's it. That's the message", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the user interview today was wild. Someone used our product to plan their wedding", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your feature just got mentioned in a customer call. By name", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the onboarding improvement you pushed? Activation is up 25%", weight: 1, category: "social" },
			{ template: "Anyone want to do a product teardown of the competitor's new release?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your JIRA ticket descriptions are chef's kiss. Teach the team", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I put your win in the monthly investor update. You're famous", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the feature you shipped reduced support tickets by 40%. Hero move", weight: 2, category: "social" },
			{ template: "Team, the customer advisory board wants to extend the session. They're engaged", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to co-author the next PRD? Two perspectives are better", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I saved your Slack message about that user insight. Gold", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the sales team keeps quoting your feature in demos. Star player", weight: 2, category: "social" },
			{ template: "Who wants to watch the latest user testing session? Popcorn included", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your scope discipline is inspiring. No scope creep. How?", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the churned user came back after your fix. Redemption arc", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to build the quarterly roadmap together? Pizza and planning", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your instinct about that feature was right all along. Respect", weight: 1, category: "social" },
		],
	},
};
