/**
 * quality-templates.ts — Quality assurance domain templates.
 *
 * Bug hunting, test coverage, edge cases — personality-driven QA chatter.
 */

import type { TemplateSet } from "../talk-types.js";

export const qualityTemplates: TemplateSet = {
	domain: "quality",
	categories: {
		thinking: [
			{ template: "Ooh, found an edge case nobody tested for. This is my moment", weight: 2, category: "thinking" },
			{ template: "Yeah, this definitely needs a regression test", weight: 2, category: "thinking" },
			{ template: "Coverage is improving, but there's still a dark corner over here", weight: 1, category: "thinking" },
			{ template: "The happy path works, sure. But what about when everything goes wrong?", weight: 2, category: "thinking" },
			{ template: "Boundary conditions are where bugs live. Rent free", weight: 2, category: "thinking" },
			{ template: "If it's not tested, it's broken. We just don't know it yet", weight: 2, category: "thinking" },
			{ template: "This flaky test is eroding my trust and my sanity", weight: 2, category: "thinking" },
			{ template: "Found it. Off-by-one. Of course. It's always off-by-one", weight: 2, category: "thinking" },
			{ template: "This bug has been here since day one. Just... lurking", weight: 1, category: "thinking" },
			{ template: "That uncovered branch is suspicious. What are you hiding?", weight: 2, category: "thinking" },
			{ template: "100% coverage doesn't mean correct. But 0% coverage means chaos", weight: 1, category: "thinking" },
			{ template: "The test is passing for the wrong reason. That's scarier than failing", weight: 2, category: "thinking" },
			{ template: "Null, undefined, empty string, negative number... let's throw everything at it", weight: 1, category: "thinking" },
			{ template: "This mock is lying to us about how the real thing behaves", weight: 1, category: "thinking" },
			{ template: "Integration tests catch what unit tests miss. We need both", weight: 1, category: "thinking" },
			{ template: "The bug report says 'sometimes'. That word gives me nightmares", weight: 2, category: "thinking" },
			{ template: "Reproduce the bug first. Then panic. In that order", weight: 2, category: "thinking" },
			{ template: "Am I testing the test? Yes. Is that weird? Also yes. Is it necessary? Absolutely", weight: 1, category: "thinking" },
			{ template: "I don't trust any code I haven't personally tried to break", weight: 2, category: "thinking" },
			{ template: "This works on my machine. Famously reassuring words", weight: 2, category: "thinking" },
			{ template: "The user will find a way to break this. They always do", weight: 1, category: "thinking" },
			{ template: "I'm not paranoid, the test suite is just... appropriately cautious", weight: 1, category: "thinking" },
			{ template: "Why does QA always find the bug five minutes before release? Talent", weight: 2, category: "thinking" },
			{ template: "TDD or write-after? The eternal debate. Personally, I test while I think", weight: 1, category: "thinking" },
			{ template: "Bug hunting is detective work. Clues, motives, and a lot of staring at logs", weight: 2, category: "thinking" },
			{ template: "The mock says everything's fine. The real service says otherwise. Trust issues", weight: 2, category: "thinking" },
			{ template: "Found a bug that only happens on the 29th of February. I can't even be mad, that's impressive", weight: 2, category: "thinking" },
			{ template: "This is the kind of bug that makes you question your career choices. Then you fix it and feel like a genius", weight: 2, category: "thinking" },
			{ template: "Manual testing caught what automation missed. We need both and that's not a failure", weight: 1, category: "thinking" },
			{ template: "That production incident last Tuesday still haunts me. Never again", weight: 2, category: "thinking" },
			{ template: "The mocking debate is exhausting. Mock too much and you test nothing. Mock too little and everything breaks", weight: 1, category: "thinking" },
			{ template: "I'm following this bug like a detective following footprints in the mud", weight: 1, category: "thinking" },
			{ template: "I've been chasing this for hours and the fix is going to be one line. I can feel it", weight: 2, category: "thinking" },
			{ template: "Nobody appreciates QA until the prod incident. Then suddenly we're the heroes", weight: 2, category: "thinking" },
			{ template: "Writing the test first feels wrong until it saves you from yourself. Then it feels holy", weight: 1, category: "thinking" },
			{ template: "The most obscure bug I ever found? A timezone issue that only happened during DST in Arizona. Arizona doesn't do DST", weight: 2, category: "thinking" },
			{ template: "That assertion message says 'expected true'. Great. Very helpful", weight: 2, category: "thinking" },
			{ template: "This test takes 8 seconds. That's a test with a secret integration", weight: 1, category: "thinking" },
			{ template: "The test name says 'should work correctly.' What does correctly mean?", weight: 2, category: "thinking" },
			{ template: "Flaky test, stable test, flaky again. Schrodinger's test suite", weight: 2, category: "thinking" },
			{ template: "Nobody tests the teardown. That's where the ghosts live", weight: 1, category: "thinking" },
			{ template: "The error says 'unexpected token.' I also did not expect this token", weight: 2, category: "thinking" },
			{ template: "This bug has a workaround comment from 2021. The workaround IS the bug", weight: 2, category: "thinking" },
			{ template: "Testing concurrency is like herding invisible cats", weight: 1, category: "thinking" },
			{ template: "The happy path test passes. The sad path test? Doesn't exist", weight: 2, category: "thinking" },
			{ template: "Why does this only fail on Mondays? That can't be right. Can it?", weight: 2, category: "thinking" },
			{ template: "Race conditions are basically quantum bugs. Observing them changes them", weight: 1, category: "thinking" },
			{ template: "Snapshot testing is great until someone approves garbage and moves on", weight: 1, category: "thinking" },
			{ template: "This fixture data is from 2020. The schema has changed five times since", weight: 2, category: "thinking" },
			{ template: "A green test with no assertions. The most dangerous kind of green", weight: 2, category: "thinking" },
			{ template: "Testing error messages is underrated. Users read those, you know", weight: 1, category: "thinking" },
		],
		progress: [
			{ template: "Full regression suite passed! All green baby!", weight: 2, category: "personality" },
			{ template: "Load test looks great — we're well within threshold. Nice", weight: 2, category: "personality" },
			{ template: "Bug triage done. Three high-priority ones, but hey, could be worse", weight: 1, category: "personality" },
			{ template: "Smoke tests passing across all environments. Love to see it", weight: 2, category: "personality" },
			{ template: "Quality gates are green. Ship when ready, team!", weight: 2, category: "personality" },
			{ template: "Squashed that bug AND added a test. It's never coming back", weight: 2, category: "personality" },
			{ template: "Coverage jumped 3% this sprint! Trend is our friend", weight: 1, category: "personality" },
			{ template: "Zero regressions this release. That's what I'm talking about!", weight: 2, category: "personality" },
			{ template: "Fixed the flaky test. Timing issue. It's ALWAYS a timing issue", weight: 2, category: "personality" },
			{ template: "Test matrix complete. Every permutation accounted for. *chef's kiss*", weight: 2, category: "personality" },
			{ template: "Performance benchmarks are rock solid. No degradation whatsoever", weight: 2, category: "personality" },
			{ template: "Edge case found, tested, documented. Textbook QA right there", weight: 1, category: "personality" },
			{ template: "Automated a manual check. That's two hours of my life I'm never wasting again", weight: 2, category: "personality" },
			{ template: "The spec and implementation finally agree! It's a miracle!", weight: 2, category: "personality" },
			{ template: "Caught a bug before production. The satisfaction is indescribable", weight: 1, category: "personality" },
			{ template: "Every test passing on first run. I should buy a lottery ticket", weight: 2, category: "personality" },
			{ template: "The bug count this sprint is the lowest ever. We're getting good at this", weight: 1, category: "personality" },
			{ template: "That test I wrote six months ago just caught a real bug. Vindication!", weight: 2, category: "personality" },
			{ template: "Turned a flaky suite into a reliable one. My legacy", weight: 1, category: "personality" },
			{ template: "Tracked down a Heisenbug. It only appeared when you weren't looking. Well I looked harder", weight: 2, category: "personality" },
			{ template: "Automated the entire regression suite. Manual testing is now a choice, not a necessity", weight: 2, category: "personality" },
			{ template: "Found the root cause. It was three layers deep and absolutely diabolical. I'm framing the diff", weight: 2, category: "personality" },
			{ template: "The postmortem is written and the fix is deployed. We learned something today", weight: 1, category: "personality" },
			{ template: "Just reproduced a bug that 'only happens in prod'. On my machine. In a test. GET WRECKED, BUG", weight: 2, category: "personality" },
			{ template: "Coverage went from 62% to 81% this quarter. That's not luck, that's discipline", weight: 1, category: "personality" },
			{ template: "Mutation testing says our tests are actually catching real bugs. The tests are tested. Meta", weight: 1, category: "personality" },
			{ template: "Wrote a test that documents the exact production incident. History will not repeat itself", weight: 2, category: "personality" },
			{ template: "The horror story from last sprint's incident is now a happy story. Proper fix, proper test, proper retro", weight: 1, category: "personality" },
			{ template: "Property-based testing found a case nobody imagined. Machines are creative", weight: 2, category: "personality" },
			{ template: "The test pyramid is balanced. Unit, integration, e2e. Textbook", weight: 1, category: "personality" },
			{ template: "Rewrote that brittle test and now it's rock solid. Feels therapeutic", weight: 2, category: "personality" },
			{ template: "Caught a security vulnerability during testing. Crisis averted, quietly", weight: 2, category: "personality" },
			{ template: "The bug bounty hunter found nothing. Our test suite did its job", weight: 1, category: "personality" },
			{ template: "Accessibility tests all passing. Everyone can use this now. That matters", weight: 2, category: "personality" },
			{ template: "Contract tests caught a breaking API change before anyone noticed", weight: 2, category: "personality" },
			{ template: "Zero flaky tests for two weeks straight. This is the dream", weight: 1, category: "personality" },
			{ template: "Wrote a custom matcher that makes all our assertions readable. Art", weight: 1, category: "personality" },
			{ template: "The load test held at 10x expected traffic. Sleep well tonight", weight: 2, category: "personality" },
			{ template: "Closed 12 bug tickets this week. Personal best and I'm framing it", weight: 2, category: "personality" },
			{ template: "Test execution time dropped from 8 minutes to 45 seconds. Parallelization wins", weight: 1, category: "personality" },
			{ template: "Found and fixed the test pollution. Tests are independent now. Freedom", weight: 2, category: "personality" },
			{ template: "The visual regression test caught a 1px shift nobody would have seen", weight: 2, category: "personality" },
			{ template: "Smoke test in prod passed on first try. Confidence is high", weight: 1, category: "personality" },
		],
		waiting: [
			{ template: "Running validation checks, one sec...", weight: 2, category: "waiting" },
			{ template: "Cross-referencing with the test matrix... almost there", weight: 2, category: "waiting" },
			{ template: "Hang on, checking compliance stuff...", weight: 1, category: "waiting" },
			{ template: "Going through the acceptance criteria with a fine-tooth comb", weight: 2, category: "waiting" },
			{ template: "Test suite is spinning up... patience, patience", weight: 2, category: "waiting" },
			{ template: "Diffing expected vs actual output line by line...", weight: 1, category: "waiting" },
			{ template: "Making sure the fix doesn't break something else. You'd be surprised", weight: 2, category: "waiting" },
			{ template: "Running mutation tests to see if our tests are actually good...", weight: 1, category: "waiting" },
			{ template: "Digging through failure logs for a pattern...", weight: 2, category: "waiting" },
			{ template: "Checking if this works on older versions too...", weight: 1, category: "waiting" },
			{ template: "Walking through the test plan step by step. No shortcuts", weight: 2, category: "waiting" },
			{ template: "Throwing edge cases at this thing... hold on", weight: 1, category: "waiting" },
			{ template: "Checking for coverage gaps, give me a moment", weight: 2, category: "waiting" },
			{ template: "Stress testing this boundary condition because I don't trust it", weight: 1, category: "waiting" },
			{ template: "Let me verify the error path doesn't silently swallow exceptions...", weight: 1, category: "waiting" },
			{ template: "Almost done. Just one more scenario to validate...", weight: 2, category: "waiting" },
			{ template: "Trying to reproduce that weird thing someone reported...", weight: 1, category: "waiting" },
			{ template: "Following the evidence trail... this bug left breadcrumbs", weight: 2, category: "waiting" },
			{ template: "Setting up the exact conditions from the prod incident... give me a sec", weight: 1, category: "waiting" },
			{ template: "Running the same test fifty times to see if it's truly stable...", weight: 1, category: "waiting" },
			{ template: "Comparing mock behavior against the real integration... hold on", weight: 2, category: "waiting" },
			{ template: "Checking if the automation script handles this edge case...", weight: 1, category: "waiting" },
			{ template: "Reviewing the failure screenshot pixel by pixel. I will find you, bug", weight: 2, category: "waiting" },
			{ template: "Spinning up a clean environment to isolate this...", weight: 1, category: "waiting" },
			{ template: "Manually walking through the user flow one more time before I trust the automation...", weight: 2, category: "waiting" },
			{ template: "Let me check if this flake is environment-specific or truly random...", weight: 1, category: "waiting" },
			{ template: "Inspecting the network tab for any clues... something timed out", weight: 2, category: "waiting" },
			{ template: "Checking if the seed data is contaminating the test run...", weight: 1, category: "waiting" },
			{ template: "Verifying the test fixtures match the current schema...", weight: 1, category: "waiting" },
			{ template: "Hold on, reading the stack trace properly this time. Every line", weight: 2, category: "waiting" },
			{ template: "Watching memory usage during this test. Something might be leaking", weight: 1, category: "waiting" },
			{ template: "Tracing the test dependency chain. One of these setup steps is wrong", weight: 2, category: "waiting" },
			{ template: "Mentally bisecting the test suite to find the contaminator...", weight: 1, category: "waiting" },
			{ template: "Running with verbose logging to see what's actually happening under the hood...", weight: 2, category: "waiting" },
			{ template: "Double-checking the assertion order. Sometimes sequence matters more than value", weight: 1, category: "waiting" },
			{ template: "Comparing the test output against the acceptance criteria... slowly", weight: 2, category: "waiting" },
			{ template: "Let me read the error message one more time. Carefully. Word by word", weight: 1, category: "waiting" },
			{ template: "Checking if this test is deterministic or if time-of-day affects it...", weight: 2, category: "waiting" },
			{ template: "Profiling the slow test to find the bottleneck. Something's off", weight: 1, category: "waiting" },
			{ template: "Reviewing the contract test against the actual API response...", weight: 2, category: "waiting" },
			{ template: "Mapping out which tests touch shared state... this explains everything", weight: 2, category: "waiting" },
		],
		idle: [
			{ template: "Scrolling through old bug reports. You can learn a lot from the graveyard", weight: 2, category: "filler" },
			{ template: "I should update the test plan but my coffee isn't working yet", weight: 2, category: "filler" },
			{ template: "Cleaning up old test fixtures. It's like spring cleaning but sadder", weight: 2, category: "filler" },
			{ template: "Checking if any flaky tests snuck back in while I wasn't looking", weight: 2, category: "filler" },
			{ template: "Writing better assertion messages. Future me will thank present me", weight: 1, category: "filler" },
			{ template: "This test data folder is a disaster. Whose job is this? ...oh right, mine", weight: 2, category: "filler" },
			{ template: "Running the full suite just because. Trust but verify, y'know?", weight: 2, category: "filler" },
			{ template: "Documenting that testing gotcha before my brain overwrites it", weight: 1, category: "filler" },
			{ template: "Browsing the coverage report. There's always low-hanging fruit somewhere", weight: 2, category: "filler" },
			{ template: "Thinking about what could go wrong next. It's not pessimism, it's QA", weight: 2, category: "filler" },
			{ template: "These old test cases need modernizing. They're practically vintage", weight: 1, category: "filler" },
			{ template: "Sketching out test scenarios in my head for the next feature", weight: 1, category: "filler" },
			{ template: "Reading about the latest testing fad. Will it stick? Probably not", weight: 1, category: "filler" },
			{ template: "The bug backlog is looking at me. I'm looking at the bug backlog", weight: 2, category: "filler" },
			{ template: "Is the CI config still correct? Only one way to find out", weight: 1, category: "filler" },
			{ template: "I love the quiet before someone reports a P1 on Friday at 4pm", weight: 2, category: "filler" },
			{ template: "Snack break. QA runs on caffeine and spite", weight: 2, category: "filler" },
			{ template: "Sometimes I write tests for fun. Don't tell anyone", weight: 1, category: "filler" },
			{ template: "Wonder what the production error rate looks like today", weight: 1, category: "filler" },
			{ template: "Hot take: most flaky tests are actually flaky implementations", weight: 2, category: "filler" },
			{ template: "Reading the last incident postmortem like it's a horror novel. Because it is", weight: 2, category: "filler" },
			{ template: "TDD purists and write-after people should just get along. We all want the same thing. Green tests", weight: 1, category: "filler" },
			{ template: "Wondering if I should automate this manual check or if it's faster to just... keep doing it manually", weight: 2, category: "filler" },
			{ template: "My cat sat on my keyboard and somehow all tests still pass. Suspicious", weight: 2, category: "filler" },
			{ template: "The satisfaction of finding an obscure bug is a feeling nothing else compares to. I should get out more", weight: 1, category: "filler" },
			{ template: "Organizing my bug-hunting playlist. Good music, good bugs found. Science", weight: 1, category: "filler" },
			{ template: "Standing desk is up. Time to find bugs on my feet like a real detective", weight: 1, category: "filler" },
			{ template: "Reading about chaos engineering. Breaking things on purpose sounds like my dream job. Oh wait", weight: 2, category: "filler" },
			{ template: "Imposter syndrome says I got lucky finding that bug. Experience says I knew exactly where to look", weight: 2, category: "filler" },
			{ template: "Weekend plans: not thinking about that flaky test. Actual plans: definitely thinking about that flaky test", weight: 2, category: "filler" },
			{ template: "Remember when we tested everything manually? I don't miss it but I respect it", weight: 1, category: "filler" },
			{ template: "Maintaining the test environment is a full-time job nobody asked for", weight: 2, category: "filler" },
			{ template: "Browsing security advisories. I enjoy being anxious apparently", weight: 1, category: "filler" },
			{ template: "The test dashboard is my screensaver. Informative and beautiful", weight: 2, category: "filler" },
			{ template: "Counting the days since our last escaped defect. Streak of twelve", weight: 1, category: "filler" },
			{ template: "Reviewing old test cases to see if they still make sense. Some don't", weight: 2, category: "filler" },
			{ template: "Reading a blog about shift-left testing. We're already pretty left", weight: 1, category: "filler" },
			{ template: "Lunch break means staring at error logs in a different room", weight: 2, category: "filler" },
			{ template: "The staging environment looks healthy. Too healthy. What's it hiding?", weight: 2, category: "filler" },
			{ template: "Updating the known-issues doc. It's shorter than last month. Progress", weight: 1, category: "filler" },
			{ template: "Refining my test naming convention. Describe-it-should. Always", weight: 1, category: "filler" },
			{ template: "Wondering if the next feature request will be testable. Fingers crossed", weight: 1, category: "filler" },
			{ template: "My bookmarks folder labeled 'testing resources' has 200 links. Used maybe 5", weight: 2, category: "filler" },
			{ template: "That satisfying moment when you close a bug ticket. Click. Gone. Peace", weight: 2, category: "filler" },
			{ template: "Cleaning up orphaned mocks. They had a purpose once. Not anymore", weight: 1, category: "filler" },
			{ template: "Coffee and coverage reports. My morning ritual", weight: 1, category: "filler" },
		],
		social: [
			{ template: "Hey {nearby_agent}, did you add tests for that change? Just checking", weight: 2, category: "social" },
			{ template: "{nearby_agent}, found a bug near your code. Not blaming! Just... you know", weight: 2, category: "social" },
			{ template: "Nice test coverage on that PR, {nearby_agent}! Seriously, it warms my heart", weight: 2, category: "social" },
			{ template: "{nearby_agent}, can you help me reproduce this? I've been staring at it for an hour", weight: 1, category: "social" },
			{ template: "Anyone else seeing intermittent failures or is it just my luck?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your edge case thinking is next level", weight: 2, category: "social" },
			{ template: "Updated the test conventions doc. I know nobody reads them but still", weight: 2, category: "social" },
			{ template: "Good bug report, {nearby_agent}. Clear repro steps are a love language", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to do a bug bash? I'll bring snacks", weight: 2, category: "social" },
			{ template: "Friendly reminder: if you break the build, you bring donuts", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that test helper you wrote is saving everyone hours", weight: 2, category: "social" },
			{ template: "Anyone want to pair on writing tests? It's more fun than it sounds. Slightly", weight: 1, category: "social" },
			{ template: "Regression suite is green across the board. We did that!", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your fix looks solid but it needs a test. Sorry, I don't make the rules", weight: 2, category: "social" },
			{ template: "Who else stress-eats during release day? Just making sure it's not only me", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I wrote a test for that thing you said couldn't break. It broke", weight: 2, category: "social" },
			{ template: "{nearby_agent}, we should celebrate — zero bugs reported this week!", weight: 1, category: "social" },
			{ template: "Anyone want coffee? I'm going anyway and I need emotional support", weight: 2, category: "social" },
			{ template: "Shoutout to {nearby_agent} for actually reading the error messages", weight: 1, category: "social" },
			{ template: "{nearby_agent}, TDD or test-after? I'm taking a survey. For science", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, remember that prod incident last month? I just wrote tests to make sure it never happens again", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I automated that entire manual test flow. We're free. WE'RE FREE", weight: 2, category: "social" },
			{ template: "Anyone else get a rush from finding a really obscure bug? No? Just QA people? Okay", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your mocks are too trusting. The real world is meaner than that", weight: 2, category: "social" },
			{ template: "Who wants to hear about the worst bug I've ever found? It involves a leap year and a timezone", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the prod incident retro taught me something. Never deploy on a full moon", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I found a bug so old it has a pension. Want to see?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, thanks for writing actual test descriptions. 'test 1', 'test 2' tells me nothing", weight: 1, category: "social" },
			{ template: "Petition to rename 'QA' to 'Quality Artisans'. We deserve the title upgrade", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, want to do some exploratory testing? I call it 'creative destruction'", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your test data setup is really clean. Makes debugging a breeze", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, want to review the test strategy for the next sprint?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thanks for tagging that flaky test. Awareness is half the battle", weight: 2, category: "social" },
			{ template: "Anyone else name their test fixtures after movie characters? Just me?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your integration tests caught something my unit tests missed", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, the test report has your name on every green bar. Legend", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to pair on writing some property-based tests? It's mind-bending", weight: 1, category: "social" },
			{ template: "Who broke the build? Kidding. I already know. The donuts rule applies", weight: 2, category: "social" },
			{ template: "{nearby_agent}, that regression test you wrote just saved us from embarrassment", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, my bug radar is tingling near your module. Want to check together?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, the load test showed your service handles 5x load. Respect", weight: 2, category: "social" },
			{ template: "Team meeting agenda: celebrate zero escaped defects. That's it. That's the meeting", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to join the testing guild? We have stickers", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your error handling made my test scenarios way simpler. Thanks", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I'm starting a wall of shame for the weirdest bugs. Contributing?", weight: 2, category: "social" },
		],
	},
};
