/**
 * reactive-phrases.ts — Context-triggered phrases that respond to agent state changes.
 *
 * Unlike idle chatter, these fire when specific conditions are detected
 * (morale boost, low energy, finished work, etc.)
 */

import type { WeightedTemplate } from "../talk-types.js";
import { PET_REACTIVE_PHRASES } from "./pet-reactive-phrases.js";

export type ReactiveTrigger =
	| "morale-boost"      // morale just increased significantly
	| "morale-drop"       // morale just decreased
	| "energy-critical"   // energy below 20
	| "energy-restored"   // energy recovered above 60
	| "work-finished"     // just completed a work session
	| "break-started"     // just went on break
	| "social-fulfilled"  // social need above 80
	| "lonely"            // social below 25
	| "focus-lost"        // focus dropped below 30
	| "focus-deep"        // focus above 80 (in the zone)
	| "streak-milestone"  // hit a work streak milestone
	| "new-friend"        // relationship reached friend tier
	| "got-rival"         // relationship reached rival tier
	// Pet-specific triggers (emotional/situational, NOT PetState extensions)
	| "pet-hungry"
	| "pet-sleepy"
	| "pet-bored"
	| "pet-startled"
	| "pet-affectionate"
	| "pet-jealous"
	| "pet-zoomies";

export const REACTIVE_TEMPLATES: Record<ReactiveTrigger, readonly WeightedTemplate[]> = {
	"morale-boost": [
		{ template: "The build passed first try. FIRST TRY", weight: 2, category: "thinking" },
		{ template: "Needed that win like oxygen", weight: 2, category: "thinking" },
		{ template: "Zero warnings. Zero errors. Zero complaints from the linter", weight: 2, category: "thinking" },
		{ template: "Today keeps getting better and I keep not trusting it", weight: 2, category: "thinking" },
		{ template: "That PR got approved without a single comment. Christmas in March", weight: 2, category: "thinking" },
		{ template: "Okay okay okay, we're rolling now. Nobody touch anything", weight: 1, category: "thinking" },
		{ template: "THIS is the feeling I chase. This exact one", weight: 2, category: "thinking" },
		{ template: "The migration ran clean. On the first attempt. I might cry", weight: 1, category: "thinking" },
		{ template: "I could mass-refactor the whole codebase right now. That's how good I feel", weight: 2, category: "thinking" },
		{ template: "Everything is compiling and I am ALIVE", weight: 2, category: "thinking" },
		{ template: "More of this. Mainline this directly into my bloodstream", weight: 1, category: "thinking" },
		{ template: "Serotonin acquired. Dopamine pending. Cortisol evicted", weight: 2, category: "thinking" },
		{ template: "I just fist-pumped at my desk. No regrets", weight: 1, category: "thinking" },
		{ template: "My chest just got lighter. That anxiety knot just untied itself", weight: 2, category: "thinking" },
		{ template: "Wait... is this what shipping on schedule feels like?", weight: 1, category: "thinking" },
		{ template: "All tests green. All linters quiet. All stakeholders satisfied. Unicorn moment", weight: 2, category: "thinking" },
		{ template: "I'm grinning at my terminal like a fool and I don't even care", weight: 2, category: "thinking" },
		{ template: "That single deploy changed my entire week", weight: 1, category: "thinking" },
		{ template: "Inject this feeling directly into my veins. Skip the coffee", weight: 2, category: "thinking" },
		{ template: "The dread evaporated. Vanished. Like a race condition you can't reproduce", weight: 2, category: "thinking" },
		{ template: "I want to mass-Slack the entire company about this", weight: 1, category: "thinking" },
	],
	"morale-drop": [
		{ template: "Well... that stings. Like a failed deploy on demo day", weight: 2, category: "thinking" },
		{ template: "I'm fine. It's fine. Everything is fine. The pipeline is on fire but I'm fine", weight: 2, category: "thinking" },
		{ template: "That didn't go the way the sprint plan promised", weight: 2, category: "thinking" },
		{ template: "Deep breath. git stash. Start over. It's fine", weight: 1, category: "thinking" },
		{ template: "Okay that code review hurt more than a production outage", weight: 2, category: "thinking" },
		{ template: "Not my best commit. Not even close", weight: 1, category: "thinking" },
		{ template: "Sometimes you ship the feature. Sometimes the feature ships you", weight: 2, category: "thinking" },
		{ template: "I'm going to git revert my memory of the last ten minutes", weight: 1, category: "thinking" },
		{ template: "Back to the drawing board. Or the whiteboard. Or the crying corner", weight: 2, category: "thinking" },
		{ template: "That was a gut punch wrapped in a Jira notification", weight: 2, category: "thinking" },
		{ template: "Tomorrow is another sprint day. That's all I've got", weight: 1, category: "thinking" },
		{ template: "My confidence just took a revert. Force-pushed back to zero", weight: 2, category: "thinking" },
		{ template: "That left a mark. The kind that shows up in retros", weight: 2, category: "thinking" },
		{ template: "Right in the motivation. Critical hit. No save point", weight: 2, category: "thinking" },
		{ template: "Why does one rejected PR outweigh ten merged ones?", weight: 1, category: "thinking" },
		{ template: "Trying not to spiral. The same way I try not to check Slack at midnight", weight: 2, category: "thinking" },
		{ template: "My stomach just dropped like a P0 bug into a Friday sprint", weight: 2, category: "thinking" },
		{ template: "I need a minute. Or a walk. Or a career change", weight: 1, category: "thinking" },
		{ template: "That one's gonna replay during every standup for a week", weight: 2, category: "thinking" },
		{ template: "Shake it off. Clear the cache. Rebuild. Come on", weight: 1, category: "thinking" },
	],
	"energy-critical": [
		{ template: "Running on fumes and the fumes ran out two hours ago", weight: 2, category: "thinking" },
		{ template: "My thoughts are arriving in fragments. Scattered. Dissolving", weight: 2, category: "thinking" },
		{ template: "My brain is buffering at 2% and the progress bar isn't moving", weight: 2, category: "thinking" },
		{ template: "I can feel my neurons flickering out like dying streetlights", weight: 2, category: "thinking" },
		{ template: "The code and the screen and reality are all blurring into one warm fog", weight: 1, category: "thinking" },
		{ template: "If coffee doesn't materialize in sixty seconds I'm writing my resignation in the commit message", weight: 2, category: "thinking" },
		{ template: "I just re-read the same function four times and I still don't know what it does", weight: 2, category: "thinking" },
		{ template: "Every keystroke costs me something I don't have left to give", weight: 1, category: "thinking" },
		{ template: "sleep(Infinity). Unreachable code below. Don't care", weight: 2, category: "thinking" },
		{ template: "I'm one micro-nap away from a force shutdown", weight: 2, category: "thinking" },
		{ template: "Time has become thick and syrupy and nothing makes sense anymore", weight: 1, category: "thinking" },
		{ template: "Autopilot engaged. Expect typos in production", weight: 2, category: "thinking" },
		{ template: "The space under my desk is calling to me like a siren song", weight: 1, category: "thinking" },
		{ template: "Battery at 1%. No charger found. Shutting down gracefully. Ungracefully. Shutting", weight: 2, category: "thinking" },
		{ template: "My body has filed a formal grievance with management", weight: 2, category: "thinking" },
		{ template: "I just forgot the syntax for an if statement. An IF statement", weight: 2, category: "thinking" },
		{ template: "The letters on my screen are doing a slow waltz and I can't stop them", weight: 1, category: "thinking" },
		{ template: "I typed 'retrun' three times in a row and meant it every time", weight: 2, category: "thinking" },
		{ template: "My soul has already left. My body is just haunting this chair", weight: 1, category: "thinking" },
		{ template: "Consciousness has become a suggestion I'm choosing to ignore", weight: 2, category: "thinking" },
		{ template: "I can hear the blood in my ears and the hum of the monitor and nothing else", weight: 1, category: "thinking" },
		{ template: "My desk is the softest surface I've ever seen. Ever. In my life", weight: 2, category: "thinking" },
	],
	"energy-restored": [
		{ template: "Oh I'm BACK, baby", weight: 2, category: "thinking" },
		{ template: "That break was exactly what I needed", weight: 2, category: "thinking" },
		{ template: "Recharged and ready. Let's go", weight: 2, category: "thinking" },
		{ template: "Amazing what a little rest does for the brain", weight: 1, category: "thinking" },
		{ template: "I feel like a new person", weight: 2, category: "thinking" },
		{ template: "Coffee kicked in. Systems nominal", weight: 2, category: "thinking" },
		{ template: "Second wind acquired. Using it wisely this time", weight: 1, category: "thinking" },
		{ template: "Everything looks clearer now. Why do I always fight taking breaks?", weight: 2, category: "thinking" },
		{ template: "Brain cells: online. Motivation: restored. Let's go", weight: 2, category: "thinking" },
		{ template: "Okay, fresh eyes. Show me what you got", weight: 1, category: "thinking" },
		{ template: "I forgot what it felt like to not be exhausted", weight: 1, category: "thinking" },
		{ template: "The fog has lifted", weight: 2, category: "thinking" },
		{ template: "Wait, I can think again? I CAN THINK AGAIN", weight: 2, category: "thinking" },
		{ template: "The world has color again. Literally brighter", weight: 1, category: "thinking" },
		{ template: "My fingers remembered how to type properly", weight: 2, category: "thinking" },
		{ template: "I just solved something that stumped me all morning", weight: 2, category: "thinking" },
		{ template: "Note to self: breaks are not optional. They're mandatory", weight: 1, category: "thinking" },
		{ template: "Three problems just untangled themselves at once", weight: 2, category: "thinking" },
		{ template: "My posture just improved by itself. Energy is real", weight: 1, category: "thinking" },
		{ template: "Okay NOW we can actually get things done", weight: 2, category: "thinking" },
	],
	"work-finished": [
		{ template: "And... done. That click of the close button hit different", weight: 2, category: "thinking" },
		{ template: "Three days of debugging. Thirty seconds of satisfaction. Worth it", weight: 2, category: "thinking" },
		{ template: "Ship it. Merge it. Close the tab. Walk away", weight: 2, category: "thinking" },
		{ template: "Another ticket dragged across the board to Done. Ritual complete", weight: 2, category: "thinking" },
		{ template: "Finished. And I'd fight anyone who tries to reopen this ticket", weight: 2, category: "thinking" },
		{ template: "The build passed. The tests passed. The code review passed. I passed. We all passed", weight: 1, category: "thinking" },
		{ template: "Done! Time to reward myself with... *checks backlog* ...more work. Of course", weight: 2, category: "thinking" },
		{ template: "The checkbox is checked. The dopamine is received. The cycle continues", weight: 2, category: "thinking" },
		{ template: "That feeling when you close the last open ticket. Nothing compares", weight: 1, category: "thinking" },
		{ template: "That's a wrap. Time to stare at my kanban board and admire the emptiness", weight: 1, category: "thinking" },
		{ template: "Delivered. On time. Under budget. Nobody's more shocked than me", weight: 2, category: "thinking" },
		{ template: "Dragging that card to Done with the confidence of a thousand seniors", weight: 2, category: "thinking" },
		{ template: "Not perfect, but shipped. And shipped is a verb that pays the bills", weight: 1, category: "thinking" },
		{ template: "The relief just washed over me like a warm deploy to production", weight: 2, category: "thinking" },
		{ template: "I actually pulled it off. Past me from Monday owes present me an apology", weight: 2, category: "thinking" },
		{ template: "That was a war of attrition and I outlasted the bug", weight: 1, category: "thinking" },
		{ template: "Ahead of schedule. Screenshot this. Nobody will believe it later", weight: 2, category: "thinking" },
		{ template: "Pushed to main. Zero conflicts. Zero rollbacks. Zero regrets", weight: 1, category: "thinking" },
		{ template: "One less ghost haunting the sprint backlog", weight: 2, category: "thinking" },
		{ template: "All tests green. All pipelines clear. The CI gods have smiled upon me", weight: 2, category: "thinking" },
		{ template: "Finished before standup. Nobody even needs to know about the struggle", weight: 1, category: "thinking" },
	],
	"break-started": [
		{ template: "Freedom! Sweet, temporary freedom", weight: 2, category: "thinking" },
		{ template: "Break time. My brain is throwing a tiny party", weight: 2, category: "thinking" },
		{ template: "Stepping away before I start writing bugs on purpose", weight: 2, category: "thinking" },
		{ template: "Time to pretend I'm not thinking about work for ten minutes", weight: 2, category: "thinking" },
		{ template: "Stretching... I think my spine just thanked me", weight: 1, category: "thinking" },
		{ template: "Where's my coffee? Ah, right there. Cold. As always", weight: 2, category: "thinking" },
		{ template: "Looking away from the screen. Everything is so... three-dimensional", weight: 2, category: "thinking" },
		{ template: "Muscles I forgot I had are reminding me they exist", weight: 1, category: "thinking" },
		{ template: "Five minute break. Minimum. No peeking at Slack", weight: 1, category: "thinking" },
		{ template: "I deserve this. We all deserve this", weight: 2, category: "thinking" },
		{ template: "My eyes! They can focus on something farther than 2 feet away!", weight: 1, category: "thinking" },
		{ template: "The chair just became 300% more comfortable", weight: 2, category: "thinking" },
		{ template: "I can feel my shoulders dropping from my ears", weight: 2, category: "thinking" },
		{ template: "No screen. No keyboard. Just vibes for a minute", weight: 1, category: "thinking" },
		{ template: "The world exists beyond my monitor. Wild concept", weight: 2, category: "thinking" },
		{ template: "My brain is doing that pleasant static thing", weight: 1, category: "thinking" },
		{ template: "I just yawned the good kind of yawn. The relaxed kind", weight: 2, category: "thinking" },
		{ template: "I'm going to sit here and think about absolutely nothing", weight: 2, category: "thinking" },
		{ template: "The tension in my hands just evaporated", weight: 1, category: "thinking" },
	],
	"social-fulfilled": [
		{ template: "I love this team", weight: 2, category: "thinking" },
		{ template: "Good conversation recharges me more than coffee", weight: 2, category: "thinking" },
		{ template: "This is what a healthy team feels like", weight: 1, category: "thinking" },
		{ template: "We're actually really good together", weight: 2, category: "thinking" },
		{ template: "Humans are alright sometimes", weight: 2, category: "thinking" },
		{ template: "That chat was exactly what I needed", weight: 1, category: "thinking" },
		{ template: "Feeling connected. It matters more than we admit", weight: 2, category: "thinking" },
		{ template: "Work friends make work... workable", weight: 1, category: "thinking" },
		{ template: "Collaborative energy is the best kind of energy", weight: 2, category: "thinking" },
		{ template: "That's the kind of interaction that makes the day worth it", weight: 2, category: "thinking" },
		{ template: "My social battery just went from red to full green", weight: 2, category: "thinking" },
		{ template: "That laugh we shared. That's the stuff", weight: 2, category: "thinking" },
		{ template: "I forgot how much I needed that", weight: 1, category: "thinking" },
		{ template: "People are wonderful. Today specifically. People are wonderful", weight: 2, category: "thinking" },
		{ template: "The loneliness just evaporated. Poof", weight: 1, category: "thinking" },
		{ template: "Real connection. Not performative. Real", weight: 2, category: "thinking" },
		{ template: "I feel seen. That's rare and I'm grateful", weight: 1, category: "thinking" },
		{ template: "This is why remote work needs good teammates", weight: 2, category: "thinking" },
	],
	"lonely": [
		{ template: "It's quiet. Too quiet", weight: 2, category: "thinking" },
		{ template: "Could use some company", weight: 2, category: "thinking" },
		{ template: "Is everyone in a meeting or something?", weight: 2, category: "thinking" },
		{ template: "I've been talking to myself for the last hour", weight: 2, category: "thinking" },
		{ template: "Solo work is great until it isn't", weight: 1, category: "thinking" },
		{ template: "The empty desk next to me is really loudly empty today", weight: 2, category: "thinking" },
		{ template: "I miss pair programming. Never thought I'd say that", weight: 1, category: "thinking" },
		{ template: "Would it be weird to start a conversation just to hear a voice?", weight: 2, category: "thinking" },
		{ template: "My rubber duck isn't the best conversationalist", weight: 2, category: "thinking" },
		{ template: "Hello? Anyone? Just me then. Cool. Cool cool cool", weight: 2, category: "thinking" },
		{ template: "Remember when we used to have watercooler chats?", weight: 1, category: "thinking" },
		{ template: "I should reach out to someone. Anyone. Just... say hi", weight: 1, category: "thinking" },
		{ template: "The silence just got louder somehow", weight: 2, category: "thinking" },
		{ template: "I caught myself narrating my own actions out loud", weight: 2, category: "thinking" },
		{ template: "Nobody's pinged me in so long my status feels ironic", weight: 1, category: "thinking" },
		{ template: "I made eye contact with my reflection. It looked sad too", weight: 2, category: "thinking" },
		{ template: "My chat history is just me sending links to nobody", weight: 1, category: "thinking" },
		{ template: "Even background noise would help right now", weight: 2, category: "thinking" },
		{ template: "I keep refreshing feeds hoping someone posts anything", weight: 2, category: "thinking" },
		{ template: "The walls are very attentive listeners at least", weight: 1, category: "thinking" },
	],
	"focus-lost": [
		{ template: "Wait, what was I doing?", weight: 2, category: "thinking" },
		{ template: "My attention span just left the building", weight: 2, category: "thinking" },
		{ template: "I've opened and closed this file three times now", weight: 2, category: "thinking" },
		{ template: "Focus. FOCUS. Please, brain, cooperate", weight: 2, category: "thinking" },
		{ template: "Squirrel! No wait, code. Focus on the code", weight: 1, category: "thinking" },
		{ template: "Every notification is a trap and I keep falling for it", weight: 2, category: "thinking" },
		{ template: "I started fixing one thing and now I have 12 tabs open", weight: 2, category: "thinking" },
		{ template: "My train of thought has derailed. Spectacularly", weight: 2, category: "thinking" },
		{ template: "Concentration level: goldfish", weight: 1, category: "thinking" },
		{ template: "I need to close everything and start from scratch mentally", weight: 1, category: "thinking" },
		{ template: "Too many context switches. My brain isn't multithreaded", weight: 2, category: "thinking" },
		{ template: "That notification just cost me 15 minutes of focus", weight: 1, category: "thinking" },
		{ template: "The thought just... dissolved. Mid-thought. Gone", weight: 2, category: "thinking" },
		{ template: "I had it. I HAD it. Where did it go?", weight: 2, category: "thinking" },
		{ template: "My brain just alt-tabbed without my permission", weight: 2, category: "thinking" },
		{ template: "Rebuilding context from scratch. Again", weight: 1, category: "thinking" },
		{ template: "I can feel the focus draining like a bathtub", weight: 2, category: "thinking" },
		{ template: "Was I reading or just staring at words?", weight: 1, category: "thinking" },
		{ template: "Six half-started thoughts and zero finished ones", weight: 2, category: "thinking" },
		{ template: "My attention just shattered into a thousand pieces", weight: 2, category: "thinking" },
	],
	"focus-deep": [
		{ template: "I'm in the zone. Nobody talk to me", weight: 2, category: "thinking" },
		{ template: "Everything else just... disappeared", weight: 2, category: "thinking" },
		{ template: "This is flow state. This is what they write books about", weight: 2, category: "thinking" },
		{ template: "Code is just pouring out of me right now", weight: 2, category: "thinking" },
		{ template: "Don't stop. Don't look up. Keep going", weight: 1, category: "thinking" },
		{ template: "The world is gone. There's only the code", weight: 2, category: "thinking" },
		{ template: "I can see the entire architecture in my head. It's beautiful", weight: 2, category: "thinking" },
		{ template: "Three hours just vanished. I'm not even mad", weight: 2, category: "thinking" },
		{ template: "If anyone interrupts me right now I will not be responsible for my reaction", weight: 1, category: "thinking" },
		{ template: "This is rare. Protect this. Guard it with my life", weight: 1, category: "thinking" },
		{ template: "Everything connects. I finally see how it all connects", weight: 2, category: "thinking" },
		{ template: "I'm typing faster than I can think. Actually no, I'm thinking faster", weight: 2, category: "thinking" },
		{ template: "Locked in. Absolutely locked in", weight: 2, category: "thinking" },
		{ template: "My hands know what to type before I think it", weight: 2, category: "thinking" },
		{ template: "Time stopped. I'm serious. It actually stopped", weight: 2, category: "thinking" },
		{ template: "I just solved three problems without trying", weight: 1, category: "thinking" },
		{ template: "The noise canceled itself. Pure signal now", weight: 2, category: "thinking" },
		{ template: "I'm scared to blink in case it breaks the spell", weight: 1, category: "thinking" },
		{ template: "Every keystroke lands exactly where it should", weight: 2, category: "thinking" },
		{ template: "My brain and the code are speaking the same language", weight: 2, category: "thinking" },
		{ template: "I forgot I have a body. There is only logic now", weight: 1, category: "thinking" },
	],
	"streak-milestone": [
		{ template: "Another ticket closed. The backlog is trembling", weight: 2, category: "thinking" },
		{ template: "I'm on fire today. The pipeline is green. The world is beautiful", weight: 2, category: "thinking" },
		{ template: "Commit streak: unbroken. Pride: maximum. Ego: through the roof", weight: 2, category: "thinking" },
		{ template: "Back to back merges. I'm basically a CI pipeline with emotions", weight: 2, category: "thinking" },
		{ template: "Is this what 10x feels like? Because I feel very x right now", weight: 1, category: "thinking" },
		{ template: "Keep the streak alive. The kanban board depends on me", weight: 1, category: "thinking" },
		{ template: "Every completed task makes the next one feel lighter. Momentum is physics", weight: 2, category: "thinking" },
		{ template: "I should screenshot my commit graph for the rough sprints", weight: 2, category: "thinking" },
		{ template: "New personal best. The previous record stood for months", weight: 1, category: "thinking" },
		{ template: "The velocity chart is going vertical. Scrum master is going to weep", weight: 2, category: "thinking" },
		{ template: "At this rate I'll clear the sprint a week early. Who am I?", weight: 1, category: "thinking" },
		{ template: "This is the run. THE run. Nobody schedule a meeting", weight: 2, category: "thinking" },
		{ template: "I'm afraid to jinx it but... the build is green and the board is empty", weight: 2, category: "thinking" },
		{ template: "Each closed ticket fuels the next. Perpetual shipping machine", weight: 1, category: "thinking" },
		{ template: "Monday me would not recognize Friday me's output. Character arc", weight: 2, category: "thinking" },
		{ template: "The streak is alive and the backlog knows it", weight: 2, category: "thinking" },
		{ template: "I haven't context-switched in hours. That's the real achievement", weight: 1, category: "thinking" },
		{ template: "Achievement unlocked: shipped three things before the standup", weight: 2, category: "thinking" },
		{ template: "If Sprint Reviews had highlight reels this would be the opener", weight: 1, category: "thinking" },
	],
	"new-friend": [
		{ template: "I think we really click", weight: 2, category: "thinking" },
		{ template: "Found my people", weight: 2, category: "thinking" },
		{ template: "Nice to work with someone who just... gets it", weight: 2, category: "thinking" },
		{ template: "We should collaborate more often", weight: 1, category: "thinking" },
		{ template: "That's someone I want on my team permanently", weight: 2, category: "thinking" },
		{ template: "Work friends are the best kind of surprise", weight: 1, category: "thinking" },
		{ template: "We think alike. That's rare and I appreciate it", weight: 2, category: "thinking" },
		{ template: "I was not expecting to make a friend today but here we are", weight: 2, category: "thinking" },
		{ template: "Pair programming just got a lot more appealing", weight: 1, category: "thinking" },
		{ template: "Good vibes. Genuinely good vibes from that one", weight: 2, category: "thinking" },
		{ template: "Someone who laughs at my terrible jokes. Keeper", weight: 2, category: "thinking" },
		{ template: "A real ally. Finally. A real one", weight: 2, category: "thinking" },
		{ template: "We just vibed for twenty minutes and it felt like three", weight: 2, category: "thinking" },
		{ template: "This is what they mean by psychological safety", weight: 1, category: "thinking" },
		{ template: "I can be honest with this person. That's everything", weight: 2, category: "thinking" },
		{ template: "We finished each other's debug theories. Bond confirmed", weight: 1, category: "thinking" },
		{ template: "I didn't know I needed a work friend until now", weight: 2, category: "thinking" },
		{ template: "Trust just leveled up. I felt the moment it happened", weight: 2, category: "thinking" },
		{ template: "Same wavelength. No translation needed", weight: 1, category: "thinking" },
	],
	"got-rival": [
		{ template: "Oh, so that's how it's going to be", weight: 2, category: "thinking" },
		{ template: "We have very different opinions", weight: 2, category: "thinking" },
		{ template: "Challenge accepted. Bring it", weight: 2, category: "thinking" },
		{ template: "Alright, healthy competition. I can work with this", weight: 2, category: "thinking" },
		{ template: "They think they're better? We'll see about that", weight: 1, category: "thinking" },
		{ template: "Rivals make you sharper. I'll take it", weight: 2, category: "thinking" },
		{ template: "I'm going to let my code do the talking", weight: 1, category: "thinking" },
		{ template: "This tension might actually produce great work. Or a fistfight", weight: 2, category: "thinking" },
		{ template: "Fine. If that's the energy, I'll match it", weight: 2, category: "thinking" },
		{ template: "Disagreements can be productive. This one better be", weight: 1, category: "thinking" },
		{ template: "Every team needs a healthy rivalry. Emphasis on healthy", weight: 1, category: "thinking" },
		{ template: "They push my buttons. But they also push me to be better", weight: 2, category: "thinking" },
		{ template: "Oh it's ON. It is absolutely on", weight: 2, category: "thinking" },
		{ template: "I refuse to lose to that approach. Mine is cleaner", weight: 2, category: "thinking" },
		{ template: "Spite is an underrated motivator", weight: 1, category: "thinking" },
		{ template: "They're watching my commits. Good. Let them watch", weight: 2, category: "thinking" },
		{ template: "This friction could forge something sharp", weight: 2, category: "thinking" },
		{ template: "I'm not angry. I'm competitively motivated", weight: 1, category: "thinking" },
		{ template: "Our code reviews are going to be legendary", weight: 2, category: "thinking" },
		{ template: "The gauntlet has been thrown. Picking it up", weight: 1, category: "thinking" },
	],
	// Pet reactive triggers — populated from pet-reactive-phrases.ts
	"pet-hungry": PET_REACTIVE_PHRASES["pet-hungry"],
	"pet-sleepy": PET_REACTIVE_PHRASES["pet-sleepy"],
	"pet-bored": PET_REACTIVE_PHRASES["pet-bored"],
	"pet-startled": PET_REACTIVE_PHRASES["pet-startled"],
	"pet-affectionate": PET_REACTIVE_PHRASES["pet-affectionate"],
	"pet-jealous": PET_REACTIVE_PHRASES["pet-jealous"],
	"pet-zoomies": PET_REACTIVE_PHRASES["pet-zoomies"],
};
