/**
 * reactive-phrases.ts — Context-triggered phrases that respond to agent state changes.
 *
 * Unlike idle chatter, these fire when specific conditions are detected
 * (morale boost, low energy, finished work, etc.)
 */

import type { WeightedTemplate } from "../talk-types.js";

export type ReactiveTrigger =
	| "morale-boost"      // morale just increased significantly
	| "morale-drop"       // morale just decreased
	| "energy-critical"   // energy below 20
	| "energy-restored"   // energy recovered above 60
	| "work-finished"     // just completed a work session
	| "break-started"     // just went on break
	| "social-fulfilled"  // social need above 80
	| "lonely"            // social below 25
	| "focus-lost"        // focus dropped below 30
	| "focus-deep"        // focus above 80 (in the zone)
	| "streak-milestone"  // hit a work streak milestone
	| "new-friend"        // relationship reached friend tier
	| "got-rival";        // relationship reached rival tier

export const REACTIVE_TEMPLATES: Record<ReactiveTrigger, readonly WeightedTemplate[]> = {
	"morale-boost": [
		{ template: "That felt good", weight: 2, category: "thinking" },
		{ template: "Needed that win", weight: 2, category: "thinking" },
		{ template: "Momentum!", weight: 2, category: "thinking" },
		{ template: "Today keeps getting better", weight: 2, category: "thinking" },
		{ template: "Now THAT is what I'm talking about", weight: 2, category: "thinking" },
		{ template: "Okay okay okay, we're rolling now", weight: 1, category: "thinking" },
		{ template: "This is why I do this", weight: 2, category: "thinking" },
		{ template: "Feeling unstoppable right now. Don't jinx it", weight: 1, category: "thinking" },
		{ template: "I could conquer the world. Or at least this sprint", weight: 2, category: "thinking" },
		{ template: "Things are clicking. Everything is clicking", weight: 2, category: "thinking" },
		{ template: "More of this, please. Much more of this", weight: 1, category: "thinking" },
		{ template: "Serotonin acquired", weight: 2, category: "thinking" },
		{ template: "I might actually enjoy today", weight: 1, category: "thinking" },
	],
	"morale-drop": [
		{ template: "Well... that stings", weight: 2, category: "thinking" },
		{ template: "I'm fine. It's fine. Everything is fine", weight: 2, category: "thinking" },
		{ template: "That didn't go the way I hoped", weight: 2, category: "thinking" },
		{ template: "Deep breath. Recalibrate. Move forward", weight: 1, category: "thinking" },
		{ template: "Okay that hurt more than I expected", weight: 2, category: "thinking" },
		{ template: "Not my best moment", weight: 1, category: "thinking" },
		{ template: "Sometimes you eat the bear. Sometimes the bear eats you", weight: 2, category: "thinking" },
		{ template: "I'm going to pretend that didn't happen", weight: 1, category: "thinking" },
		{ template: "Back to the drawing board, I guess", weight: 2, category: "thinking" },
		{ template: "That was a gut punch. But we recover", weight: 2, category: "thinking" },
		{ template: "Tomorrow is another day. That's what I'll tell myself", weight: 1, category: "thinking" },
		{ template: "My confidence just took a hit. Recalculating", weight: 2, category: "thinking" },
	],
	"energy-critical": [
		{ template: "Running on fumes", weight: 2, category: "thinking" },
		{ template: "Need a break. Desperately", weight: 2, category: "thinking" },
		{ template: "My brain is buffering", weight: 2, category: "thinking" },
		{ template: "I can feel my neurons shutting down one by one", weight: 2, category: "thinking" },
		{ template: "The screen is getting blurry. Or my eyes are. Probably both", weight: 1, category: "thinking" },
		{ template: "If I don't get coffee in the next five minutes...", weight: 2, category: "thinking" },
		{ template: "I just re-read the same line four times", weight: 2, category: "thinking" },
		{ template: "My keyboard feels like it weighs a thousand pounds", weight: 1, category: "thinking" },
		{ template: "Sleep mode initiated. Error: cannot sleep at desk", weight: 2, category: "thinking" },
		{ template: "I'm one yawn away from giving up", weight: 2, category: "thinking" },
		{ template: "Everything takes twice as long when you're this tired", weight: 1, category: "thinking" },
		{ template: "Autopilot engaged. Quality not guaranteed", weight: 2, category: "thinking" },
		{ template: "Is it socially acceptable to nap under a desk?", weight: 1, category: "thinking" },
		{ template: "Battery at 3%. Charging required", weight: 2, category: "thinking" },
	],
	"energy-restored": [
		{ template: "Oh I'm BACK, baby", weight: 2, category: "thinking" },
		{ template: "That break was exactly what I needed", weight: 2, category: "thinking" },
		{ template: "Recharged and ready. Let's go", weight: 2, category: "thinking" },
		{ template: "Amazing what a little rest does for the brain", weight: 1, category: "thinking" },
		{ template: "I feel like a new person", weight: 2, category: "thinking" },
		{ template: "Coffee kicked in. Systems nominal", weight: 2, category: "thinking" },
		{ template: "Second wind acquired. Using it wisely this time", weight: 1, category: "thinking" },
		{ template: "Everything looks clearer now. Why do I always fight taking breaks?", weight: 2, category: "thinking" },
		{ template: "Brain cells: online. Motivation: restored. Let's go", weight: 2, category: "thinking" },
		{ template: "Okay, fresh eyes. Show me what you got", weight: 1, category: "thinking" },
		{ template: "I forgot what it felt like to not be exhausted", weight: 1, category: "thinking" },
		{ template: "The fog has lifted", weight: 2, category: "thinking" },
	],
	"work-finished": [
		{ template: "And... done!", weight: 2, category: "thinking" },
		{ template: "That took longer than expected but it's done", weight: 2, category: "thinking" },
		{ template: "Ship it!", weight: 2, category: "thinking" },
		{ template: "Another one bites the dust", weight: 2, category: "thinking" },
		{ template: "Finished. Genuinely proud of that one", weight: 2, category: "thinking" },
		{ template: "Wrapping up. That felt productive", weight: 1, category: "thinking" },
		{ template: "Done! Time to reward myself with... more work", weight: 2, category: "thinking" },
		{ template: "Crossing that off the list. Satisfying", weight: 2, category: "thinking" },
		{ template: "I keep underestimating how good 'done' feels", weight: 1, category: "thinking" },
		{ template: "That's a wrap. What's next?", weight: 1, category: "thinking" },
		{ template: "Delivered. On time. Nobody's more surprised than me", weight: 2, category: "thinking" },
		{ template: "Mark it complete. I love marking things complete", weight: 2, category: "thinking" },
		{ template: "Not perfect, but done beats perfect every time", weight: 1, category: "thinking" },
	],
	"break-started": [
		{ template: "Freedom! Sweet, temporary freedom", weight: 2, category: "thinking" },
		{ template: "Break time. My brain is throwing a tiny party", weight: 2, category: "thinking" },
		{ template: "Stepping away before I start writing bugs on purpose", weight: 2, category: "thinking" },
		{ template: "Time to pretend I'm not thinking about work for ten minutes", weight: 2, category: "thinking" },
		{ template: "Stretching... I think my spine just thanked me", weight: 1, category: "thinking" },
		{ template: "Where's my coffee? Ah, right there. Cold. As always", weight: 2, category: "thinking" },
		{ template: "Looking away from the screen. Everything is so... three-dimensional", weight: 2, category: "thinking" },
		{ template: "Muscles I forgot I had are reminding me they exist", weight: 1, category: "thinking" },
		{ template: "Five minute break. Minimum. No peeking at Slack", weight: 1, category: "thinking" },
		{ template: "I deserve this. We all deserve this", weight: 2, category: "thinking" },
		{ template: "My eyes! They can focus on something farther than 2 feet away!", weight: 1, category: "thinking" },
	],
	"social-fulfilled": [
		{ template: "I love this team", weight: 2, category: "thinking" },
		{ template: "Good conversation recharges me more than coffee", weight: 2, category: "thinking" },
		{ template: "This is what a healthy team feels like", weight: 1, category: "thinking" },
		{ template: "We're actually really good together", weight: 2, category: "thinking" },
		{ template: "Humans are alright sometimes", weight: 2, category: "thinking" },
		{ template: "That chat was exactly what I needed", weight: 1, category: "thinking" },
		{ template: "Feeling connected. It matters more than we admit", weight: 2, category: "thinking" },
		{ template: "Work friends make work... workable", weight: 1, category: "thinking" },
		{ template: "Collaborative energy is the best kind of energy", weight: 2, category: "thinking" },
		{ template: "That's the kind of interaction that makes the day worth it", weight: 2, category: "thinking" },
	],
	"lonely": [
		{ template: "It's quiet. Too quiet", weight: 2, category: "thinking" },
		{ template: "Could use some company", weight: 2, category: "thinking" },
		{ template: "Is everyone in a meeting or something?", weight: 2, category: "thinking" },
		{ template: "I've been talking to myself for the last hour", weight: 2, category: "thinking" },
		{ template: "Solo work is great until it isn't", weight: 1, category: "thinking" },
		{ template: "The empty desk next to me is really loudly empty today", weight: 2, category: "thinking" },
		{ template: "I miss pair programming. Never thought I'd say that", weight: 1, category: "thinking" },
		{ template: "Would it be weird to start a conversation just to hear a voice?", weight: 2, category: "thinking" },
		{ template: "My rubber duck isn't the best conversationalist", weight: 2, category: "thinking" },
		{ template: "Hello? Anyone? Just me then. Cool. Cool cool cool", weight: 2, category: "thinking" },
		{ template: "Remember when we used to have watercooler chats?", weight: 1, category: "thinking" },
		{ template: "I should reach out to someone. Anyone. Just... say hi", weight: 1, category: "thinking" },
	],
	"focus-lost": [
		{ template: "Wait, what was I doing?", weight: 2, category: "thinking" },
		{ template: "My attention span just left the building", weight: 2, category: "thinking" },
		{ template: "I've opened and closed this file three times now", weight: 2, category: "thinking" },
		{ template: "Focus. FOCUS. Please, brain, cooperate", weight: 2, category: "thinking" },
		{ template: "Squirrel! No wait, code. Focus on the code", weight: 1, category: "thinking" },
		{ template: "Every notification is a trap and I keep falling for it", weight: 2, category: "thinking" },
		{ template: "I started fixing one thing and now I have 12 tabs open", weight: 2, category: "thinking" },
		{ template: "My train of thought has derailed. Spectacularly", weight: 2, category: "thinking" },
		{ template: "Concentration level: goldfish", weight: 1, category: "thinking" },
		{ template: "I need to close everything and start from scratch mentally", weight: 1, category: "thinking" },
		{ template: "Too many context switches. My brain isn't multithreaded", weight: 2, category: "thinking" },
		{ template: "That notification just cost me 15 minutes of focus", weight: 1, category: "thinking" },
	],
	"focus-deep": [
		{ template: "I'm in the zone. Nobody talk to me", weight: 2, category: "thinking" },
		{ template: "Everything else just... disappeared", weight: 2, category: "thinking" },
		{ template: "This is flow state. This is what they write books about", weight: 2, category: "thinking" },
		{ template: "Code is just pouring out of me right now", weight: 2, category: "thinking" },
		{ template: "Don't stop. Don't look up. Keep going", weight: 1, category: "thinking" },
		{ template: "The world is gone. There's only the code", weight: 2, category: "thinking" },
		{ template: "I can see the entire architecture in my head. It's beautiful", weight: 2, category: "thinking" },
		{ template: "Three hours just vanished. I'm not even mad", weight: 2, category: "thinking" },
		{ template: "If anyone interrupts me right now I will not be responsible for my reaction", weight: 1, category: "thinking" },
		{ template: "This is rare. Protect this. Guard it with my life", weight: 1, category: "thinking" },
		{ template: "Everything connects. I finally see how it all connects", weight: 2, category: "thinking" },
		{ template: "I'm typing faster than I can think. Actually no, I'm thinking faster", weight: 2, category: "thinking" },
		{ template: "Locked in. Absolutely locked in", weight: 2, category: "thinking" },
	],
	"streak-milestone": [
		{ template: "Another one! The streak continues", weight: 2, category: "thinking" },
		{ template: "I'm on fire today. Metaphorically. Thankfully", weight: 2, category: "thinking" },
		{ template: "Productivity streak unlocked. Don't break it", weight: 2, category: "thinking" },
		{ template: "Back to back to back. Unstoppable", weight: 2, category: "thinking" },
		{ template: "Is this what peak performance feels like?", weight: 1, category: "thinking" },
		{ template: "Keep the streak alive. No pressure", weight: 1, category: "thinking" },
		{ template: "Every completed task feeds the next one. Momentum is real", weight: 2, category: "thinking" },
		{ template: "I should bottle this feeling for the rough days", weight: 2, category: "thinking" },
		{ template: "New personal record? I think that's a new personal record", weight: 1, category: "thinking" },
		{ template: "The streak gods are smiling on me today", weight: 2, category: "thinking" },
		{ template: "At this rate I'll finish everything by lunch. Well, maybe not", weight: 1, category: "thinking" },
	],
	"new-friend": [
		{ template: "I think we really click", weight: 2, category: "thinking" },
		{ template: "Found my people", weight: 2, category: "thinking" },
		{ template: "Nice to work with someone who just... gets it", weight: 2, category: "thinking" },
		{ template: "We should collaborate more often", weight: 1, category: "thinking" },
		{ template: "That's someone I want on my team permanently", weight: 2, category: "thinking" },
		{ template: "Work friends are the best kind of surprise", weight: 1, category: "thinking" },
		{ template: "We think alike. That's rare and I appreciate it", weight: 2, category: "thinking" },
		{ template: "I was not expecting to make a friend today but here we are", weight: 2, category: "thinking" },
		{ template: "Pair programming just got a lot more appealing", weight: 1, category: "thinking" },
		{ template: "Good vibes. Genuinely good vibes from that one", weight: 2, category: "thinking" },
		{ template: "Someone who laughs at my terrible jokes. Keeper", weight: 2, category: "thinking" },
	],
	"got-rival": [
		{ template: "Oh, so that's how it's going to be", weight: 2, category: "thinking" },
		{ template: "We have very different opinions", weight: 2, category: "thinking" },
		{ template: "Challenge accepted. Bring it", weight: 2, category: "thinking" },
		{ template: "Alright, healthy competition. I can work with this", weight: 2, category: "thinking" },
		{ template: "They think they're better? We'll see about that", weight: 1, category: "thinking" },
		{ template: "Rivals make you sharper. I'll take it", weight: 2, category: "thinking" },
		{ template: "I'm going to let my code do the talking", weight: 1, category: "thinking" },
		{ template: "This tension might actually produce great work. Or a fistfight", weight: 2, category: "thinking" },
		{ template: "Fine. If that's the energy, I'll match it", weight: 2, category: "thinking" },
		{ template: "Disagreements can be productive. This one better be", weight: 1, category: "thinking" },
		{ template: "Every team needs a healthy rivalry. Emphasis on healthy", weight: 1, category: "thinking" },
		{ template: "They push my buttons. But they also push me to be better", weight: 2, category: "thinking" },
	],
};
