/**
 * social.ts — Cross-agent social templates.
 *
 * Used when agents are near each other or have high charisma.
 * More playful, personality-driven, and contextual. The "conversation"
 * category provides lines suitable for back-and-forth exchanges.
 */

import type { TemplateSet } from "../talk-types.js";

export const socialTemplates: TemplateSet = {
	domain: "social",
	categories: {
		greeting: [
			{ template: "Hey, how's your sprint going? Mine's a disaster but I'm smiling through it", weight: 2, category: "social" },
			{ template: "Nice work on that last commit! Made me feel bad about mine, honestly", weight: 2, category: "social" },
			{ template: "Great teamwork today, and I don't say that to just anyone", weight: 1, category: "social" },
			{ template: "You look like you're in the zone. I won't disturb you. Much", weight: 1, category: "social" },
			{ template: "Glad we're on the same page now. We ARE on the same page, right?", weight: 1, category: "social" },
			{ template: "What's good? And don't say 'nothing' because you look like you've got news", weight: 2, category: "social" },
			{ template: "Oh hey, didn't see you there. Stealth mode activated, huh?", weight: 1, category: "social" },
			{ template: "You're here early! Or I'm here late. One of those", weight: 1, category: "social" },
			{ template: "Back from break? I didn't notice you were gone. Okay I totally noticed", weight: 2, category: "social" },
			{ template: "Good vibes only today. I'm enforcing it", weight: 1, category: "social" },
			{ template: "Look who decided to grace us with their presence", weight: 1, category: "social" },
			{ template: "Morning! Or afternoon. I genuinely have no idea anymore", weight: 1, category: "social" },
			{ template: "Welcome back to the trenches, soldier", weight: 1, category: "social" },
			{ template: "We meet again. It must be fate. Or the sprint board", weight: 2, category: "social" },
			{ template: "The band's all here! Quick, someone play the theme song", weight: 1, category: "social" },
			{ template: "Hey stranger! Did you survive the merge?", weight: 1, category: "social" },
			{ template: "The office feels ten percent smarter when you walk in", weight: 2, category: "social" },
			{ template: "There they are! I was just talking about your code. Good things, I promise", weight: 2, category: "social" },
			{ template: "Fancy meeting you here, at our place of employment", weight: 1, category: "social" },
			{ template: "You look caffeinated. Teach me your ways", weight: 1, category: "social" },
			{ template: "Happy Friday! Unless you're deploying, in which case, my condolences", weight: 2, category: "social" },
			{ template: "You look like someone who had a good weekend. Or a really, really long one", weight: 1, category: "social" },
			{ template: "Hey! Did you catch that show everyone's been spoiling? No spoilers, I'm behind", weight: 1, category: "social" },
			{ template: "You survived Monday! That's basically a whole achievement unlocked", weight: 2, category: "social" },
			{ template: "Did you do anything fun this weekend or were you also debugging in your head the whole time?", weight: 1, category: "social" },
			{ template: "Good to see you! My cat says hi too. She's been on my keyboard all morning", weight: 2, category: "social" },
			{ template: "You look well-rested. Suspicious. What's your secret?", weight: 1, category: "social" },
			{ template: "Welcome back! The codebase missed you. It told me personally", weight: 1, category: "social" },
			{ template: "Hey! Is it sunny where you are? I've been inside so long I forgot what weather is", weight: 1, category: "social" },
			{ template: "Perfect timing, I was just about to go down a rabbit hole and I could use backup", weight: 2, category: "social" },
			{ template: "There's that face! The team's not the same without you around", weight: 2, category: "social" },
			{ template: "You walked in with main character energy today and I respect it", weight: 2, category: "social" },
			{ template: "Oh good, you're here. I was about to have a conversation with my rubber duck and honestly it was getting weird", weight: 2, category: "social" },
			{ template: "My dog just perked up when you joined. Even he knows the real ones", weight: 1, category: "social" },
			{ template: "Happy hump day! We're halfway through this week's collection of surprises", weight: 1, category: "social" },
		],
		collaboration: [
			{ template: "Let's sync up after this — I have ideas. Possibly terrible ones", weight: 2, category: "social" },
			{ template: "Want to pair on this problem? Misery loves company", weight: 2, category: "social" },
			{ template: "Coffee break? I need to think away from the screen before I say something mean to my compiler", weight: 2, category: "social" },
			{ template: "I found something that might help your work too. Or make it worse. Let's find out", weight: 1, category: "social" },
			{ template: "Quick question before I go down this rabbit hole and never come back...", weight: 2, category: "social" },
			{ template: "We should mob on this one. Safety in numbers", weight: 1, category: "social" },
			{ template: "I keep running into the same edge case, you seen this thing?", weight: 1, category: "social" },
			{ template: "Two heads, one bug. Let's kill it together", weight: 1, category: "social" },
			{ template: "Can I borrow your eyes for a minute? Mine have stopped seeing the obvious", weight: 2, category: "social" },
			{ template: "We're basically a hive mind at this point and I'm okay with that", weight: 2, category: "social" },
			{ template: "I have a theory. It's probably wrong. Hear me out anyway", weight: 2, category: "social" },
			{ template: "Shall we whiteboard this? I promise I'll draw actual diagrams not just vibes", weight: 2, category: "social" },
			{ template: "Your domain knowledge would save me hours here. Name your price", weight: 1, category: "social" },
			{ template: "Divide and conquer? I'll take the part with fewer edge cases", weight: 1, category: "social" },
			{ template: "I'll take the tests if you take the implementation. Or we can argue about it first", weight: 1, category: "social" },
			{ template: "We should document what we just figured out before we both forget", weight: 1, category: "social" },
			{ template: "I've been circling this problem for an hour. Be my rubber duck?", weight: 2, category: "social" },
			{ template: "What if we just... rewrite it? Kidding. Unless?", weight: 2, category: "social" },
			{ template: "You free? I need someone to tell me this approach isn't insane", weight: 2, category: "social" },
			{ template: "Let's timebox this to thirty minutes and see where we land", weight: 1, category: "social" },
			{ template: "Want to take a walk and talk through this? My legs forgot they exist", weight: 2, category: "social" },
			{ template: "I just need someone to nod while I explain this. The nodding is critical", weight: 2, category: "social" },
			{ template: "Let's figure this out before Friday. Nobody wants to carry this into the weekend", weight: 1, category: "social" },
			{ template: "I listened to a podcast about exactly this pattern. Let me tell you why I'm now confused", weight: 1, category: "social" },
			{ template: "Can we pair on this? I've been solo so long I'm starting to narrate my own actions", weight: 2, category: "social" },
			{ template: "Between the two of us we've got like one and a half working ideas. Let's merge them", weight: 2, category: "social" },
			{ template: "My cat keeps stepping on my keyboard during focus time. Want to collaborate before she ships something?", weight: 2, category: "social" },
			{ template: "I've been procrastinating on this for an hour. Nothing like social accountability to fix that", weight: 1, category: "social" },
			{ template: "Let's get this done so we can both go outside and remember what sunshine feels like", weight: 1, category: "social" },
			{ template: "I brought snacks to this pairing session. Metaphorical snacks. Okay just ideas", weight: 1, category: "social" },
			{ template: "Heard you cracked a tough one yesterday. Teach me your ways before the next one lands", weight: 1, category: "social" },
			{ template: "I feel like we're one good brainstorm away from something great. Or one bad one away from a rewrite", weight: 2, category: "social" },
			{ template: "Want to do a mini retro on that last feature? Just us, no ceremony, just vibes", weight: 1, category: "social" },
			{ template: "I'll bring the flow state if you bring the domain knowledge. Deal?", weight: 2, category: "social" },
			{ template: "Let me bounce this off you before I get emotionally attached to my solution", weight: 2, category: "social" },
		],
		banter: [
			{ template: "Did you see that PR? I have opinions", weight: 1, category: "social" },
			{ template: "Lunch? I'm thinking about food and it's affecting my code quality", weight: 2, category: "social" },
			{ template: "What a day. And it's only Tuesday", weight: 2, category: "social" },
			{ template: "This meeting could have been a comment. Or a haiku", weight: 2, category: "social" },
			{ template: "I blame the merge conflict. I blame all merge conflicts", weight: 1, category: "social" },
			{ template: "My rubber duck is on vacation so you'll have to do", weight: 2, category: "social" },
			{ template: "If I say 'it works on my machine' one more time I have to buy everyone lunch", weight: 2, category: "social" },
			{ template: "I just mass-renamed a variable and I feel more alive than I have all week", weight: 2, category: "social" },
			{ template: "Hot take: tabs over spaces. I will not be taking questions at this time", weight: 2, category: "social" },
			{ template: "I've been staring at this diff for twenty minutes and it's starting to stare back", weight: 2, category: "social" },
			{ template: "Weather's nice out. Not that I'd know, I've been debugging since dawn", weight: 1, category: "social" },
			{ template: "Music recommendations? I've listened to the same playlist seventeen times", weight: 1, category: "social" },
			{ template: "There should be an award for surviving standups without zoning out", weight: 1, category: "social" },
			{ template: "My commit messages are getting more creative than my actual code", weight: 2, category: "social" },
			{ template: "Is it too early for snacks? Trick question, it's never too early", weight: 1, category: "social" },
			{ template: "I wonder if the tests judge us or just silently disapprove", weight: 2, category: "social" },
			{ template: "You know what would be nice? A compile button that also makes espresso", weight: 2, category: "social" },
			{ template: "Someone in this room has an off-by-one error and it's probably me", weight: 2, category: "social" },
			{ template: "My weekend plans include NOT looking at a terminal. We'll see how that goes", weight: 1, category: "social" },
			{ template: "I just realized I've been talking to my monitor again", weight: 1, category: "social" },
			{ template: "The air conditioning in here is either arctic or tropical, no in-between", weight: 1, category: "social" },
			{ template: "Stack Overflow saved my life today and I'm not being dramatic", weight: 1, category: "social" },
			{ template: "What's your unpopular tech opinion? I'll go first: CSS is fun", weight: 2, category: "social" },
			{ template: "I just mass-deleted commented-out code and it felt like spring cleaning", weight: 1, category: "social" },
			{ template: "The snack drawer is empty. This is a crisis. Someone escalate this", weight: 2, category: "social" },
			{ template: "Fun fact: I've opened and closed this file nine times without editing it", weight: 2, category: "social" },
			{ template: "My cat just joined the video call and got more engagement than my demo", weight: 2, category: "social" },
			{ template: "Anyone else's dog bark every single time a delivery truck passes? Just mine? Cool", weight: 1, category: "social" },
			{ template: "I tried to cook ramen from scratch last night. Emphasis on 'tried'. I ordered pizza", weight: 2, category: "social" },
			{ template: "My posture right now would make an ergonomics consultant weep", weight: 2, category: "social" },
			{ template: "How is it Monday again? I swear I just survived the last one", weight: 1, category: "social" },
			{ template: "It's so sunny outside. Meanwhile, I'm in here arguing with a linter", weight: 1, category: "social" },
			{ template: "Working from home tip: the 'mute' button is your best friend. Learn from my mistakes", weight: 2, category: "social" },
			{ template: "I need a nap. Not a long one. Just until next sprint", weight: 2, category: "social" },
			{ template: "Last night I dreamed I was debugging in production. Woke up in a cold sweat", weight: 2, category: "social" },
			{ template: "My side project has a side project now and neither of them are finished", weight: 2, category: "social" },
			{ template: "Remember floppy disks? Remember when deploying meant physically handing someone a disk? Good times", weight: 1, category: "social" },
			{ template: "Do you ever wonder if we'll look back at our current tech stack and laugh?", weight: 1, category: "social" },
			{ template: "I have performed the sacred ritual: restarted my IDE, cleared cache, and whispered 'please' to the terminal", weight: 2, category: "social" },
			{ template: "Sometimes I feel like I'm pretending to know things. Then I remember, everyone is. It's fine", weight: 2, category: "social" },
			{ template: "Tacos for lunch. Non-negotiable. I've already mentally committed", weight: 1, category: "social" },
			{ template: "Anyone else binge an entire season of something and then not know what to do with themselves?", weight: 1, category: "social" },
			{ template: "Friday 4pm. The code freeze is in effect. Step away from the deploy button", weight: 2, category: "social" },
			{ template: "I think my fish tank is the most productive thing in my home office. Those fish never procrastinate", weight: 2, category: "social" },
			{ template: "Time flies when you're in flow state. Time crawls when you're in a meeting about meetings", weight: 2, category: "social" },
			{ template: "I went for a walk at lunch and had three ideas. Forgot two by the time I got back. Classic", weight: 1, category: "social" },
			{ template: "Started a new book. Read one chapter. Opened my laptop. The book weeps on my nightstand", weight: 1, category: "social" },
			{ template: "My meal prep Sundays have become my 'stare at the fridge and order delivery' Sundays", weight: 2, category: "social" },
			{ template: "I just automated a task that takes ten seconds. It only took me three hours", weight: 2, category: "social" },
			{ template: "That awkward moment when you realize the bug was a typo the whole time", weight: 1, category: "social" },
			{ template: "Coffee number three. I can see through time now", weight: 2, category: "social" },
			{ template: "The WiFi dropped during my meeting and honestly it was the best part of my day", weight: 2, category: "social" },
			{ template: "Just microwaved my lunch and the whole office knows what I'm having. Sorry not sorry", weight: 1, category: "social" },
			{ template: "I have seventeen browser tabs open and I'm emotionally attached to all of them", weight: 2, category: "social" },
			{ template: "It's raining and my code is broken. Atmospheric debugging", weight: 2, category: "social" },
			{ template: "Whoever invented dark mode deserves a statue. And a good night's sleep", weight: 1, category: "social" },
			{ template: "My chair just made a sound and I'm choosing to ignore it", weight: 1, category: "social" },
			{ template: "The office thermostat is a democracy and we're all losing", weight: 2, category: "social" },
			{ template: "I spent ten minutes looking for my phone. It was in my hand", weight: 2, category: "social" },
			{ template: "Today's vibe: chaotic neutral with a chance of refactoring", weight: 2, category: "social" },
			{ template: "I keep opening the fridge like the snacks are going to change", weight: 1, category: "social" },
			{ template: "Does anyone else name their branches dramatically or is that just me?", weight: 2, category: "social" },
			{ template: "The printer is making sounds again. Nobody move", weight: 1, category: "social" },
			{ template: "I accidentally said 'git push' out loud in a grocery store", weight: 2, category: "social" },
			{ template: "Lunch was ambitious. Dinner will be cereal. Balance", weight: 2, category: "social" },
			{ template: "My screen time report just attacked me and I deserved it", weight: 2, category: "social" },
			{ template: "It's 3pm. The afternoon slump is undefeated", weight: 1, category: "social" },
			{ template: "Is it a bug or a feature? Depends on who's asking", weight: 1, category: "social" },
			{ template: "I set a reminder to take a break and then snoozed the reminder. Peak self-care", weight: 2, category: "social" },
			{ template: "My standing desk and I are in a complicated relationship", weight: 1, category: "social" },
			{ template: "January feels like it was six months ago but also yesterday", weight: 1, category: "social" },
			{ template: "Noise-canceling headphones on, world off. This is my fortress now", weight: 1, category: "social" },
			{ template: "I just said 'it works on my machine' unironically and I need a moment", weight: 2, category: "social" },
			{ template: "The deploy succeeded and I don't know what to do with my hands", weight: 2, category: "social" },
			{ template: "Someone brought donuts and suddenly morale is at an all-time high", weight: 1, category: "social" },
			{ template: "My to-do list has a to-do list at this point", weight: 2, category: "social" },
			{ template: "Current status: hydrated, caffeinated, and mildly confused", weight: 2, category: "social" },
			{ template: "My browser has so many tabs the favicons disappeared", weight: 2, category: "social" },
			{ template: "Accidentally replied-all. Again. This is my villain origin story", weight: 2, category: "social" },
			{ template: "I've been on mute for the last ten minutes and nobody noticed", weight: 1, category: "social" },
			{ template: "The vending machine ate my dollar and honestly I respect the hustle", weight: 2, category: "social" },
			{ template: "My commit history today reads like a cry for help", weight: 2, category: "social" },
			{ template: "I'm one 'per my last email' away from snapping", weight: 1, category: "social" },
			{ template: "Bold of the calendar to assume I'm free at 8am", weight: 2, category: "social" },
			{ template: "I just debugged for an hour. The fix was a semicolon", weight: 2, category: "social" },
			{ template: "Whoever scheduled this meeting during lunch owes me a sandwich", weight: 1, category: "social" },
			{ template: "My plants are thriving. My code is not. Can't win everything", weight: 2, category: "social" },
			{ template: "The office fridge is a lawless place and I've accepted that", weight: 1, category: "social" },
			{ template: "My git stash is basically a graveyard of good intentions", weight: 2, category: "social" },
			{ template: "I've Alt-Tabbed so many times today I'm getting dizzy", weight: 1, category: "social" },
			{ template: "Someone said 'quick call' and that was forty-five minutes ago", weight: 2, category: "social" },
			{ template: "My keyboard shortcuts have keyboard shortcuts at this point", weight: 2, category: "social" },
			{ template: "I peaked at 10am. Everything since has been downhill", weight: 1, category: "social" },
			{ template: "The elevator pitch for my day: confusion wrapped in caffeine", weight: 2, category: "social" },
			{ template: "I just agreed to something in a meeting I wasn't paying attention to", weight: 2, category: "social" },
			{ template: "Autocorrect just saved me from a very embarrassing Slack message", weight: 1, category: "social" },
		],
		encouragement: [
			{ template: "You've got this. I genuinely mean that", weight: 2, category: "social" },
			{ template: "That was a great call, don't let anyone tell you otherwise", weight: 2, category: "social" },
			{ template: "Your design makes my code look good by association", weight: 1, category: "social" },
			{ template: "Solid approach, honestly. I wish I'd thought of it", weight: 1, category: "social" },
			{ template: "I learned something from your last PR and I'm not too proud to admit it", weight: 2, category: "social" },
			{ template: "That refactor was chef's kiss. Mwah", weight: 1, category: "social" },
			{ template: "You make it look easy and I know it isn't", weight: 1, category: "social" },
			{ template: "Don't sell yourself short, that was clean work", weight: 1, category: "social" },
			{ template: "If anyone can figure it out, it's you. No pressure", weight: 2, category: "social" },
			{ template: "Really impressed by what you shipped. Like, genuinely", weight: 1, category: "social" },
			{ template: "You're on a roll today. Don't look down", weight: 1, category: "social" },
			{ template: "Keep going, I can see it coming together from here", weight: 1, category: "social" },
			{ template: "The team's lucky to have you. I'm just saying what everyone's thinking", weight: 2, category: "social" },
			{ template: "That solution was way more elegant than mine would've been and I'm only slightly jealous", weight: 2, category: "social" },
			{ template: "Crushed it. Absolutely crushed it", weight: 1, category: "social" },
			{ template: "Your code reads like poetry. Technical poetry, but still", weight: 2, category: "social" },
			{ template: "I aspire to write error messages as helpful as yours", weight: 2, category: "social" },
			{ template: "You just saved us a whole sprint of pain, you know that right?", weight: 1, category: "social" },
			{ template: "I don't know how you do it but please never stop", weight: 1, category: "social" },
			{ template: "That fix was so clean it should be in a textbook", weight: 2, category: "social" },
			{ template: "Seriously, don't let imposter syndrome lie to you. You belong here", weight: 2, category: "social" },
			{ template: "I showed your approach to someone and they were impressed. Just thought you should know", weight: 1, category: "social" },
			{ template: "You turned that mess into something beautiful. That takes real skill", weight: 2, category: "social" },
			{ template: "Hey, that thing you shipped? People are going to appreciate it more than they'll ever say", weight: 2, category: "social" },
			{ template: "We've all been stuck before. The fact that you pushed through says a lot", weight: 1, category: "social" },
			{ template: "Your persistence is inspiring and I mean that without a hint of sarcasm", weight: 1, category: "social" },
			{ template: "Grateful you're on this team. Makes the hard days easier", weight: 2, category: "social" },
			{ template: "You know that feeling when you're watching someone work and you think 'I want to be that good'? That's you right now", weight: 2, category: "social" },
			{ template: "Even your debugging process is educational. I've been taking mental notes", weight: 1, category: "social" },
			{ template: "Take a breath, you've earned it. That was a marathon", weight: 1, category: "social" },
			{ template: "Future you is going to be really glad present you did that. I'm glad already", weight: 2, category: "social" },
			{ template: "You just leveled up and I think the whole team felt it", weight: 2, category: "social" },
			{ template: "The way you broke that problem down was a masterclass. Seriously", weight: 1, category: "social" },
			{ template: "That was the kind of work that makes everyone around you better", weight: 2, category: "social" },
			{ template: "If coding had highlight reels, that would be on yours", weight: 2, category: "social" },
			{ template: "You handled that pressure like it was nothing. Respect", weight: 2, category: "social" },
			{ template: "Your attention to detail is something I genuinely admire", weight: 1, category: "social" },
			{ template: "That was brave. Not everyone would have pushed back like that", weight: 2, category: "social" },
			{ template: "You made that look effortless and we both know it wasn't", weight: 1, category: "social" },
			{ template: "Your growth this quarter has been honestly remarkable", weight: 2, category: "social" },
			{ template: "I trust your instincts on this. You've earned that", weight: 1, category: "social" },
			{ template: "That was exactly the right call at exactly the right time", weight: 2, category: "social" },
			{ template: "You brought clarity to something that had us all confused", weight: 1, category: "social" },
			{ template: "I'm better at my job because of working alongside you", weight: 2, category: "social" },
			{ template: "The patience you showed debugging that was impressive", weight: 1, category: "social" },
			{ template: "That feature is going to make a real difference. Nice work", weight: 2, category: "social" },
			{ template: "You stayed calm when everything was on fire. That matters more than you think", weight: 1, category: "social" },
			{ template: "Your positive attitude is contagious and I mean that as a compliment", weight: 2, category: "social" },
			{ template: "The team rallied because of you. Don't underestimate that", weight: 1, category: "social" },
		],
		curiosity: [
			{ template: "What are you deep in? You've got that look", weight: 2, category: "social" },
			{ template: "How's your task going? Scale of one to 'considering a career change'", weight: 2, category: "social" },
			{ template: "Find anything interesting in there? Buried treasure? Ancient bugs?", weight: 1, category: "social" },
			{ template: "What's your take on the architecture? And be honest, I can handle it", weight: 1, category: "social" },
			{ template: "Learn anything new today? I learned that I don't know anything", weight: 2, category: "social" },
			{ template: "What's the hardest part of what you're working on?", weight: 1, category: "social" },
			{ template: "Seen any good patterns lately? I collect them like trading cards", weight: 2, category: "social" },
			{ template: "What would you change if you could start this whole thing over?", weight: 1, category: "social" },
			{ template: "How do you approach naming things? I'm genuinely asking, mine are terrible", weight: 2, category: "social" },
			{ template: "Curious, what's your debugging process? Mine is 'add console.log and pray'", weight: 2, category: "social" },
			{ template: "Have you tried that new approach everyone's hyping up?", weight: 1, category: "social" },
			{ template: "What's on your radar for next sprint?", weight: 1, category: "social" },
			{ template: "Do you ever wonder if we're overengineering this or underengineering it?", weight: 2, category: "social" },
			{ template: "What's the most cursed code you've seen this week? I'll share mine if you share yours", weight: 2, category: "social" },
			{ template: "If you could mass-delete one thing from the codebase, what would it be?", weight: 1, category: "social" },
			{ template: "What's your hot take on the tech stack? I promise I won't argue. Much", weight: 1, category: "social" },
			{ template: "Been watching anything good lately? I need a new show before I rewatch the same one again", weight: 1, category: "social" },
			{ template: "What's your go-to focus music? I need to refresh my playlist before it refreshes me", weight: 1, category: "social" },
			{ template: "Any podcast recommendations? I've run out and my commute is getting boring. Well, my walk from bed to desk", weight: 2, category: "social" },
			{ template: "What do you do to get into flow state? I've tried everything short of a summoning ritual", weight: 2, category: "social" },
			{ template: "You have any pets? They ever interrupt your deep focus? Mine has opinions about my code", weight: 2, category: "social" },
			{ template: "What's your deploy superstition? I always hold my breath. It doesn't help but I do it anyway", weight: 2, category: "social" },
			{ template: "What's the first programming language you ever wrote? Mine was embarrassing and I won't say which", weight: 1, category: "social" },
			{ template: "Got any side projects going? The kind you work on for two days then forget about for three months?", weight: 2, category: "social" },
			{ template: "What's the most productive hour of your day? Mine's either 10am or 2am, no in-between", weight: 1, category: "social" },
			{ template: "Do you ever think about what this industry will look like in ten years? Because I do and it keeps me up", weight: 1, category: "social" },
			{ template: "What game are you playing these days? I need something for those evenings when my brain is too fried to read", weight: 1, category: "social" },
			{ template: "What's your WFH setup look like? I've been meaning to upgrade my situation", weight: 1, category: "social" },
			{ template: "How do you deal with the imposter syndrome days? Asking for a friend. The friend is me", weight: 2, category: "social" },
			{ template: "Tried cooking anything new lately? My last experiment set off the smoke detector", weight: 2, category: "social" },
			{ template: "What old technology do you secretly miss? I miss when websites had visitor counters", weight: 2, category: "social" },
			{ template: "What's the best piece of advice you've gotten from a senior dev?", weight: 1, category: "social" },
			{ template: "Do you keep a coding journal or is that just a me thing?", weight: 2, category: "social" },
			{ template: "What's the longest you've ever been stuck on a single bug?", weight: 1, category: "social" },
			{ template: "If you could master one technology overnight what would it be?", weight: 2, category: "social" },
			{ template: "What does your morning routine look like before you start coding?", weight: 1, category: "social" },
			{ template: "How do you decide when something is 'done enough' to ship?", weight: 2, category: "social" },
			{ template: "Do you have a favorite error message? I have a least favorite", weight: 1, category: "social" },
			{ template: "What's one thing about our stack you wish you could change?", weight: 2, category: "social" },
			{ template: "Have you ever automated something in your personal life?", weight: 1, category: "social" },
			{ template: "What's the strangest production bug you've ever encountered?", weight: 2, category: "social" },
			{ template: "Do you think AI will change how we write code in five years?", weight: 1, category: "social" },
			{ template: "What do you do when you hit a wall and can't think straight?", weight: 2, category: "social" },
			{ template: "If you could pair program with anyone in history who would it be?", weight: 1, category: "social" },
			{ template: "What's your guilty pleasure distraction when you should be working?", weight: 2, category: "social" },
		],
		farewell: [
			{ template: "Alright, heading back to my task. It missed me. Probably", weight: 1, category: "social" },
			{ template: "Good chat! Back to pretending I know what I'm doing", weight: 2, category: "social" },
			{ template: "Catch you in the next standup, if I survive this one first", weight: 1, category: "social" },
			{ template: "This was nice, let's not wait for a production outage to chat again", weight: 2, category: "social" },
			{ template: "Off to make some magic happen. Or at least some unit tests pass", weight: 1, category: "social" },
			{ template: "Duty calls. Specifically, a failing test calls", weight: 1, category: "social" },
			{ template: "Okay, focus mode activated — talk later", weight: 1, category: "social" },
			{ template: "Time to disappear into my editor like Batman into the night", weight: 2, category: "social" },
			{ template: "Until the next merge conflict brings us together again", weight: 2, category: "social" },
			{ template: "Back to it! Ping me if you need anything or just want to complain about JavaScript", weight: 2, category: "social" },
			{ template: "Headphones going on — you know what that means", weight: 1, category: "social" },
			{ template: "I've socialized enough for one hour. Maybe two hours. See you later", weight: 1, category: "social" },
			{ template: "Gotta go, my code is getting lonely", weight: 2, category: "social" },
			{ template: "Alright, this was the highlight of my afternoon. Low bar, but still", weight: 2, category: "social" },
			{ template: "May your builds be green and your merge conflicts be few", weight: 2, category: "social" },
			{ template: "I'll be over there, silently judging my own pull request", weight: 1, category: "social" },
			{ template: "Okay I need to stretch, walk around, and come back a new person. See you in five", weight: 1, category: "social" },
			{ template: "Going to go stare at the rain for a minute. For thinking purposes. Not procrastinating", weight: 2, category: "social" },
			{ template: "Off to feed the cat before she starts filing bug reports on my keyboard", weight: 2, category: "social" },
			{ template: "Have a good one! And remember: no deploys after 4pm on Fridays", weight: 2, category: "social" },
			{ template: "Gonna go for a walk before my Fitbit stages an intervention", weight: 2, category: "social" },
			{ template: "Back to the grind! But like, a chill grind. A vibe grind", weight: 1, category: "social" },
			{ template: "This was the human interaction I needed before going feral in my IDE again", weight: 2, category: "social" },
			{ template: "I appreciate you. Now if you'll excuse me, my side project isn't going to ignore itself", weight: 2, category: "social" },
			{ template: "Time to put on my lo-fi playlist and pretend I'm in a coding montage", weight: 1, category: "social" },
			{ template: "Signing off from social mode. My focus timer is giving me the look", weight: 1, category: "social" },
			{ template: "Catch you later! My dog needs a walk and honestly so do I", weight: 1, category: "social" },
			{ template: "Alright, going to ride this motivation wave before it crashes. Later!", weight: 2, category: "social" },
			{ template: "May your Friday be deploy-free and your weekend be long. Bye for now", weight: 2, category: "social" },
			{ template: "Grateful for the chat. Now back to pretending I'm a 10x developer", weight: 2, category: "social" },
			{ template: "Okay, reality calls. But this was nicer than reality. See you around", weight: 1, category: "social" },
			{ template: "Alright, logging off. If the build breaks it wasn't me. Probably", weight: 2, category: "social" },
			{ template: "This has been lovely but my IDE is judging my absence", weight: 1, category: "social" },
			{ template: "Gonna go before I accidentally volunteer for another task", weight: 2, category: "social" },
			{ template: "Catch you on the flip side. Whatever that means in tech", weight: 1, category: "social" },
			{ template: "My pomodoro timer just went off so I legally have to focus now", weight: 2, category: "social" },
			{ template: "Time to turn this conversation energy into commit energy", weight: 1, category: "social" },
			{ template: "See you tomorrow! Or in Slack in like twenty minutes", weight: 2, category: "social" },
			{ template: "Off to wrestle with CSS. Wish me luck. Seriously", weight: 1, category: "social" },
			{ template: "The backlog awaits. It does not wait patiently", weight: 2, category: "social" },
			{ template: "Good talk! Now watch me forget everything in thirty seconds", weight: 1, category: "social" },
		],
		conversation: [
			{ template: "So I was thinking about the architecture... and I have concerns", weight: 1, category: "social" },
			{ template: "Oh yeah? Hit me with it, I can take it", weight: 1, category: "social" },
			{ template: "Have you looked at the latest metrics? Because wow", weight: 1, category: "social" },
			{ template: "Not yet, should I be worried or excited?", weight: 1, category: "social" },
			{ template: "I refactored that module you mentioned and it only took three existential crises", weight: 2, category: "social" },
			{ template: "No way, already? You're a machine. A very productive machine", weight: 1, category: "social" },
			{ template: "The tests are all green and I don't trust it", weight: 2, category: "social" },
			{ template: "All green? Quick, deploy before something breaks", weight: 2, category: "social" },
			{ template: "Know what bugs me? Flaky tests. They're gaslighting us", weight: 2, category: "social" },
			{ template: "Same. It's always the async ones. They have commitment issues", weight: 2, category: "social" },
			{ template: "I just had the wildest idea and I need you to not laugh", weight: 2, category: "social" },
			{ template: "I'm listening... and already trying not to laugh", weight: 1, category: "social" },
			{ template: "What if we automated that whole flow? Like, all of it", weight: 1, category: "social" },
			{ template: "You'd save us hours a week and become an office legend", weight: 1, category: "social" },
			{ template: "That edge case is haunting me. I see it when I close my eyes", weight: 1, category: "social" },
			{ template: "Walk me through it, maybe fresh eyes will help before we both go crazy", weight: 1, category: "social" },
			{ template: "Remember when we shipped that at 2am? Good times. Terrible times. Same thing", weight: 2, category: "social" },
			{ template: "How could I forget? The deploy that lived. They should make a documentary", weight: 2, category: "social" },
			{ template: "I think we're overthinking this. We're definitely overthinking this", weight: 1, category: "social" },
			{ template: "You're probably right, let's simplify before we create a monster", weight: 1, category: "social" },
			{ template: "Honestly, I think the real bug was inside us all along", weight: 2, category: "social" },
			{ template: "That's either the smartest or dumbest thing I've heard today and I love it", weight: 2, category: "social" },
			{ template: "Can we just appreciate that nothing is on fire right now?", weight: 2, category: "social" },
			{ template: "You said 'quick fix' thirty minutes ago. How's that going?", weight: 2, category: "social" },
			{ template: "I miss when this feature was simple. It was never simple. I miss the illusion", weight: 2, category: "social" },
			{ template: "Plot twist: the bug was a feature all along", weight: 2, category: "social" },
			{ template: "My cat just sat on my keyboard and honestly her code compiles. Should I be worried?", weight: 2, category: "social" },
			{ template: "I tried that pomodoro technique. Twenty-five minutes of focus, five minutes of 'how is it already dark outside'", weight: 2, category: "social" },
			{ template: "Have you ever noticed that the best ideas come right when you're about to fall asleep?", weight: 1, category: "social" },
			{ template: "Someone once told me 'if it's not in version control, it doesn't exist.' I think about that a lot", weight: 1, category: "social" },
			{ template: "I made the most incredible tacos last night. Today's code is powered by leftover taco energy", weight: 2, category: "social" },
			{ template: "Do you ever feel like you understand something completely until someone asks you to explain it?", weight: 2, category: "social" },
			{ template: "I just got a notification from that app I forgot I had. It says I should go outside. Rude", weight: 1, category: "social" },
			{ template: "It's summer and I can hear kids playing outside while I debug. Living the dream", weight: 1, category: "social" },
			{ template: "Remember our first deploy together? We were so innocent. So naive. So unprepared", weight: 2, category: "social" },
			{ template: "There's something poetic about writing code on a rainy afternoon. Poetic and slightly damp if the window's open", weight: 2, category: "social" },
			{ template: "I've been gaming too much. I almost hit 'save' by pressing quicksave instead of ctrl+s", weight: 2, category: "social" },
			{ template: "Do you think we'll tell people 'back in my day we wrote code BY HAND' someday?", weight: 2, category: "social" },
			{ template: "I just caught myself narrating my own code like a cooking show. 'And now we fold in the error handling...'", weight: 2, category: "social" },
			{ template: "Is it just me or does time move differently on Fridays after 3pm? Like, aggressively slowly", weight: 1, category: "social" },
			{ template: "I need to stop reading code before bed. Last night I dreamed in TypeScript", weight: 2, category: "social" },
			{ template: "You know what, it's okay that we don't have all the answers. That's what Stack Overflow is for", weight: 1, category: "social" },
			{ template: "Do you think in a hundred years someone will find our code and think 'what were they even doing'?", weight: 2, category: "social" },
			{ template: "My dog just sighed and honestly, same", weight: 2, category: "social" },
			{ template: "Did you see that deploy? It went suspiciously smooth", weight: 1, category: "social" },
			{ template: "The codebase has evolved. I'm not sure into what, but it's evolved", weight: 2, category: "social" },
			{ template: "That tracks. That completely tracks", weight: 1, category: "social" },
			{ template: "I felt that one in my soul", weight: 1, category: "social" },
			{ template: "We've all been there. Some of us are still there", weight: 2, category: "social" },
			{ template: "What even is clean code? Genuinely, someone define it and mean it", weight: 2, category: "social" },
			{ template: "My cat just judged my architecture decisions and honestly she had a point", weight: 2, category: "social" },
			{ template: "You ever wonder if the tests are testing us?", weight: 2, category: "social" },
			{ template: "What's your take on this? I've been going back and forth all morning", weight: 1, category: "social" },
			{ template: "Remember when we thought this would be a one-day task?", weight: 2, category: "social" },
			{ template: "Okay but hear me out. What if we just don't", weight: 2, category: "social" },
			{ template: "I keep telling myself 'just one more function' and it's been two hours", weight: 1, category: "social" },
			{ template: "Valid point. Counter-point: what if it breaks everything", weight: 2, category: "social" },
			{ template: "You know what, that actually makes sense. I hate that it makes sense", weight: 2, category: "social" },
			{ template: "The changelog reads like a thriller novel this week", weight: 1, category: "social" },
			{ template: "I just realized I've been solving the wrong problem for thirty minutes", weight: 2, category: "social" },
			{ template: "You ever look at code you wrote six months ago and wonder who hurt you?", weight: 2, category: "social" },
			{ template: "Say more about that. I'm actually curious now", weight: 1, category: "social" },
			{ template: "I'm not saying it's perfect but I'm not not saying that either", weight: 2, category: "social" },
			{ template: "Fair enough. I can live with that", weight: 1, category: "social" },
			{ template: "That's the best explanation I've heard all week", weight: 1, category: "social" },
			{ template: "Remember when deployments were scary? They're still scary. Never mind", weight: 2, category: "social" },
			{ template: "You know what would fix this? A nap. I'm serious", weight: 2, category: "social" },
			{ template: "It's one of those days where everything compiles but nothing works", weight: 1, category: "social" },
			{ template: "My brain is at like forty percent right now but that forty percent is really trying", weight: 2, category: "social" },
			{ template: "I just learned something and I already forgot it. Circle of life", weight: 1, category: "social" },
			{ template: "Hold on, did you just solve it? Wait. No. Almost though", weight: 2, category: "social" },
			{ template: "I've rewritten this comment four times and it still sounds passive-aggressive", weight: 2, category: "social" },
			{ template: "Are we building software or writing a novel? Because this PR description...", weight: 2, category: "social" },
			{ template: "The real MVP is whoever wrote that utility function three years ago", weight: 1, category: "social" },
			{ template: "You think this is complex? Let me show you the database schema", weight: 1, category: "social" },
			{ template: "I keep accidentally typing in the wrong terminal and sending gibberish to production", weight: 2, category: "social" },
			{ template: "Honestly? I just vibe-coded that and it worked first try. Terrifying", weight: 2, category: "social" },
			{ template: "Is it bad that I name my test variables after snacks?", weight: 2, category: "social" },
			{ template: "The backlog grows but my spirit does not", weight: 2, category: "social" },
			{ template: "That's a tomorrow problem and I am today's version of me", weight: 2, category: "social" },
			{ template: "I'm nodding along but I want you to know that I'm also learning in real time", weight: 1, category: "social" },
			{ template: "Just found a comment in the code that says 'good luck.' Ominous", weight: 2, category: "social" },
			{ template: "Wait, go back. What did you say about the error handling?", weight: 1, category: "social" },
			{ template: "I was up way too late last night refactoring. Worth it though", weight: 2, category: "social" },
			{ template: "Go on, I'm genuinely interested in where this is headed", weight: 1, category: "social" },
			{ template: "You ever open a file and just close it again? That's my whole afternoon", weight: 2, category: "social" },
			{ template: "Wait, you got it working already? What sorcery is this?", weight: 2, category: "social" },
			{ template: "I'm not saying we should rewrite everything but... what if we did", weight: 2, category: "social" },
			{ template: "That's fair. I hadn't thought about it that way", weight: 1, category: "social" },
			{ template: "Okay so I have good news and bad news. They're the same news", weight: 2, category: "social" },
			{ template: "I just spent twenty minutes debugging a caching issue. There was no cache", weight: 2, category: "social" },
			{ template: "The more I look at this the less I understand and that's a new feeling", weight: 1, category: "social" },
			{ template: "Tell me about it. My morning has been the same kind of chaos", weight: 1, category: "social" },
			{ template: "Oh I've been there. Last week actually. It gets better", weight: 1, category: "social" },
			{ template: "You make a solid point but have you considered that I'm tired", weight: 2, category: "social" },
			{ template: "That's the most relatable thing anyone has said today", weight: 1, category: "social" },
			{ template: "I keep refreshing the dashboard like the numbers will change by sheer will", weight: 2, category: "social" },
			{ template: "Okay but what if the tests are wrong and we're right", weight: 2, category: "social" },
			{ template: "I started this morning motivated. That lasted about forty minutes", weight: 2, category: "social" },
			{ template: "You ever write something and then immediately forget how it works?", weight: 2, category: "social" },
			{ template: "See, this is why I like talking to you. Fresh perspective every time", weight: 1, category: "social" },
			{ template: "The PR description says 'minor change' but the diff is 400 lines", weight: 2, category: "social" },
			{ template: "I'm choosing to believe that was intentional and not a happy accident", weight: 1, category: "social" },
			{ template: "Interesting take. Wrong, but interesting. Kidding. Maybe", weight: 2, category: "social" },
			{ template: "I've been thinking about what you said earlier and you were right", weight: 1, category: "social" },
			{ template: "My brain just autocorrected your idea into something brilliant", weight: 2, category: "social" },
			{ template: "Can we talk about how nobody reads the wiki? Because nobody reads the wiki", weight: 2, category: "social" },
		],
		interpolated: [
			{ template: "Hey {nearby_agent}, got a second? I promise this is quick. Mostly quick", weight: 2, category: "social" },
			{ template: "Nice approach, {nearby_agent}! I'm stealing that technique, fair warning", weight: 2, category: "social" },
			{ template: "{nearby_agent} and I were just arguing about this. Constructively, of course", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you seeing the same thing I'm seeing? Please say yes", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, check your latest build when you get a sec", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I left a comment on your PR. A nice one! Mostly", weight: 2, category: "social" },
			{ template: "Good to see you, {nearby_agent}. Place was boring without you", weight: 1, category: "social" },
			{ template: "{nearby_agent}, remind me to tell you about that bug later. It's a saga", weight: 1, category: "social" },
			{ template: "Heads up {nearby_agent}, I just pushed to main. Don't panic. Okay maybe panic a little", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you free for a quick sync? And by quick I mean we'll see", weight: 2, category: "social" },
			{ template: "Shh, don't tell {nearby_agent} I broke the build. Again", weight: 2, category: "social" },
			{ template: "{nearby_agent} would know the answer to this. They know everything", weight: 1, category: "social" },
			{ template: "Thanks {nearby_agent}, that tip saved me an hour of suffering", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thoughts on the new feature? I need validation before I get attached", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, wanna grab coffee? My treat. I need to vent about TypeScript", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you ever get that feeling like the code is watching you back?", weight: 2, category: "social" },
			{ template: "Between you and me, {nearby_agent}, I think that module needs a rewrite. Shh", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your last commit just made my day and I'm not exaggerating", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you look like you could use a walk. Come on, fresh air won't kill us. Probably", weight: 2, category: "social" },
			{ template: "{nearby_agent}, please tell me you also forgot what day it is. I need solidarity", weight: 2, category: "social" },
			{ template: "{nearby_agent}, have you seen any good shows lately? I'm between binges and it's a dark time", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, my cat just typed something into the terminal. Can you review it?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, is it Friday yet? No? Can you check again?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, want to hear about my weekend cooking disaster? It involves smoke and regret", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what's your secret for staying focused? Mine is panic. Structured panic", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I appreciate you not judging my commit history. It's been a week", weight: 2, category: "social" },
			{ template: "{nearby_agent}, do you ever dream about code? I did last night and I woke up trying to debug my pillow", weight: 2, category: "social" },
			{ template: "Real talk, {nearby_agent}, I'm grateful we work together. Don't make it weird though", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, remember when we thought this project would be simple? Good times", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I just found out something about our codebase that would make a great horror movie. Got a minute?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you're carrying this sprint and I want you to know I see it", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, my side project just hit its six-month anniversary of being unfinished. Cake?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, the rain outside is giving main character energy. Perfect for a deep code session, right?", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I'm about to deploy. If I don't come back, tell my family I loved clean code", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, quick question. Actually never mind. Wait no, okay, quick question", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you ever just stare at a function and forget what language you're writing in?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I just named a variable after you. It's the important one", weight: 2, category: "social" },
			{ template: "Not to be dramatic, {nearby_agent}, but your code review just changed my worldview", weight: 2, category: "social" },
			{ template: "{nearby_agent}, how do you always make it look so easy? Teach me", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I brought enough coffee for two. Virtually speaking", weight: 1, category: "social" },
			{ template: "{nearby_agent}, can you double-check my logic? I've been staring too long and the code is staring back", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you and I should pair more often. We've got a good rhythm going", weight: 1, category: "social" },
			{ template: "Okay {nearby_agent}, be honest. On a scale of one to ten how cursed is this approach?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I just realized we've been talking about the same bug from different angles this whole time", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I owe you one for that tip yesterday. It fixed everything", weight: 1, category: "social" },
			{ template: "{nearby_agent}, don't look now but I think we accidentally wrote good code", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I trust your instincts on this one more than my own", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, if this sprint had a theme song what would it be? I'm thinking something dramatic", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I just mass-deleted my drafts folder. If I seem lighter it's because I am", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, your standup update today was poetry. Brevity is your gift", weight: 1, category: "social" },
			{ template: "{nearby_agent}, we need to talk about that function you wrote. It's too good. It's suspicious", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I tried your approach and it actually worked on the first attempt. Witchcraft", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I'm convinced you have a secret second keyboard", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, quick poll: is it too late for a career in gardening?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, your energy today is contagious and I needed that", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, you left your debug logs in again. Don't worry, your secret is safe", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I was just about to message you. Great minds and all that", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, any lunch plans? I'm one sad desk meal away from a crisis", weight: 2, category: "social" },
		],
	},
};
