/**
 * social.ts — Cross-agent social templates.
 *
 * Used when agents are near each other or have high charisma.
 * More playful, personality-driven, and contextual. The "conversation"
 * category provides lines suitable for back-and-forth exchanges.
 */

import type { TemplateSet } from "../talk-types.js";

export const socialTemplates: TemplateSet = {
	domain: "social",
	categories: {
		greeting: [
			{ template: "Hey, how's your sprint going?", weight: 2, category: "social" },
			{ template: "Nice work on that last commit!", weight: 2, category: "social" },
			{ template: "Great teamwork today, seriously", weight: 1, category: "social" },
			{ template: "You look like you're in the zone", weight: 1, category: "social" },
			{ template: "Glad we're on the same page now", weight: 1, category: "social" },
			{ template: "What's good?", weight: 1, category: "social" },
			{ template: "Oh hey, didn't see you there", weight: 1, category: "social" },
			{ template: "You're here early", weight: 1, category: "social" },
			{ template: "Back from break?", weight: 1, category: "social" },
			{ template: "Good vibes today", weight: 1, category: "social" },
			{ template: "Look who showed up!", weight: 1, category: "social" },
			{ template: "Morning! Or afternoon. I've lost track", weight: 1, category: "social" },
			{ template: "Welcome back to the trenches", weight: 1, category: "social" },
			{ template: "We meet again", weight: 1, category: "social" },
			{ template: "The band's all here", weight: 1, category: "social" },
		],
		collaboration: [
			{ template: "Let's sync up after this — I have ideas", weight: 2, category: "social" },
			{ template: "Want to pair on this problem?", weight: 2, category: "social" },
			{ template: "Coffee break? I need to think away from the screen", weight: 1, category: "social" },
			{ template: "I found something that might help your work too", weight: 1, category: "social" },
			{ template: "Quick question before I go down this rabbit hole...", weight: 2, category: "social" },
			{ template: "We should mob on this one", weight: 1, category: "social" },
			{ template: "I keep running into the same edge case, you seen this?", weight: 1, category: "social" },
			{ template: "Two heads, one bug", weight: 1, category: "social" },
			{ template: "Can I borrow your eyes for a minute?", weight: 2, category: "social" },
			{ template: "We're basically a hive mind at this point", weight: 2, category: "social" },
			{ template: "I have a theory, hear me out", weight: 1, category: "social" },
			{ template: "Shall we whiteboard this?", weight: 1, category: "social" },
			{ template: "Your domain knowledge would save me hours here", weight: 1, category: "social" },
			{ template: "Divide and conquer?", weight: 1, category: "social" },
			{ template: "I'll take the tests if you take the implementation", weight: 1, category: "social" },
		],
		banter: [
			{ template: "Did you see that PR?", weight: 1, category: "social" },
			{ template: "Lunch?", weight: 1, category: "social" },
			{ template: "What a day", weight: 1, category: "social" },
			{ template: "This meeting could have been a comment", weight: 2, category: "social" },
			{ template: "I blame the merge conflict", weight: 1, category: "social" },
			{ template: "My rubber duck is on vacation so you'll have to do", weight: 2, category: "social" },
			{ template: "If I say 'it works on my machine' one more time...", weight: 2, category: "social" },
			{ template: "I just mass-renamed a variable and I feel alive", weight: 1, category: "social" },
			{ template: "Hot take: tabs over spaces", weight: 1, category: "social" },
			{ template: "I've been staring at this diff for twenty minutes", weight: 1, category: "social" },
			{ template: "Weather's nice for debugging", weight: 1, category: "social" },
			{ template: "Music recommendations? I've exhausted my playlist", weight: 1, category: "social" },
			{ template: "There should be an award for surviving standups", weight: 1, category: "social" },
			{ template: "My commit messages are getting poetic", weight: 1, category: "social" },
			{ template: "Is it too early for snacks?", weight: 1, category: "social" },
			{ template: "I wonder if the tests are judging us", weight: 1, category: "social" },
		],
		encouragement: [
			{ template: "You've got this", weight: 2, category: "social" },
			{ template: "That was a great call", weight: 2, category: "social" },
			{ template: "Your design makes my code look good", weight: 1, category: "social" },
			{ template: "Solid approach, honestly", weight: 1, category: "social" },
			{ template: "I learned something from your last PR", weight: 1, category: "social" },
			{ template: "That refactor was chef's kiss", weight: 1, category: "social" },
			{ template: "You make it look easy", weight: 1, category: "social" },
			{ template: "Don't sell yourself short, that was clean work", weight: 1, category: "social" },
			{ template: "If anyone can figure it out, it's you", weight: 2, category: "social" },
			{ template: "Really impressed by what you shipped", weight: 1, category: "social" },
			{ template: "You're on a roll today", weight: 1, category: "social" },
			{ template: "Keep going, I can see it coming together", weight: 1, category: "social" },
			{ template: "The team's lucky to have you", weight: 2, category: "social" },
			{ template: "That solution was way more elegant than mine would've been", weight: 1, category: "social" },
			{ template: "Crushed it", weight: 1, category: "social" },
		],
		curiosity: [
			{ template: "What are you deep in?", weight: 2, category: "social" },
			{ template: "How's your task going?", weight: 2, category: "social" },
			{ template: "Find anything interesting in there?", weight: 1, category: "social" },
			{ template: "What's your take on the architecture?", weight: 1, category: "social" },
			{ template: "Learn anything new today?", weight: 1, category: "social" },
			{ template: "What's the hardest part of what you're working on?", weight: 1, category: "social" },
			{ template: "Seen any good patterns lately?", weight: 1, category: "social" },
			{ template: "What would you change if you could start over?", weight: 1, category: "social" },
			{ template: "How do you approach naming things?", weight: 1, category: "social" },
			{ template: "Curious, what's your debugging process?", weight: 1, category: "social" },
			{ template: "Have you tried that new approach everyone's talking about?", weight: 1, category: "social" },
			{ template: "What's on your radar for next sprint?", weight: 1, category: "social" },
		],
		farewell: [
			{ template: "Alright, heading back to my task", weight: 1, category: "social" },
			{ template: "Good chat, back to the grind", weight: 1, category: "social" },
			{ template: "Catch you in the next standup", weight: 1, category: "social" },
			{ template: "This was nice, let's not wait for a bug to chat again", weight: 2, category: "social" },
			{ template: "Off to make some magic happen", weight: 1, category: "social" },
			{ template: "Duty calls", weight: 1, category: "social" },
			{ template: "Okay, focus mode — talk later", weight: 1, category: "social" },
			{ template: "Time to disappear into my editor", weight: 1, category: "social" },
			{ template: "Until the next merge conflict brings us together", weight: 2, category: "social" },
			{ template: "Signing off from social mode", weight: 1, category: "social" },
			{ template: "Back to it, ping me if you need anything", weight: 1, category: "social" },
			{ template: "Headphones going on — you know what that means", weight: 1, category: "social" },
		],
		conversation: [
			{ template: "So I was thinking about the architecture...", weight: 1, category: "social" },
			{ template: "Oh yeah? What about it?", weight: 1, category: "social" },
			{ template: "Have you looked at the latest metrics?", weight: 1, category: "social" },
			{ template: "Not yet, anything stand out?", weight: 1, category: "social" },
			{ template: "I refactored that module you mentioned", weight: 1, category: "social" },
			{ template: "No way, already? How'd it go?", weight: 1, category: "social" },
			{ template: "The tests are all green", weight: 1, category: "social" },
			{ template: "Music to my ears", weight: 1, category: "social" },
			{ template: "Know what bugs me? Flaky tests", weight: 1, category: "social" },
			{ template: "Same. It's always the async ones", weight: 1, category: "social" },
			{ template: "I just had the wildest idea", weight: 1, category: "social" },
			{ template: "I'm listening...", weight: 1, category: "social" },
			{ template: "What if we automated that whole flow?", weight: 1, category: "social" },
			{ template: "You'd save us hours a week", weight: 1, category: "social" },
			{ template: "That edge case is haunting me", weight: 1, category: "social" },
			{ template: "Walk me through it, maybe fresh eyes will help", weight: 1, category: "social" },
			{ template: "Remember when we shipped that at 2am?", weight: 1, category: "social" },
			{ template: "How could I forget? The deploy that lived", weight: 1, category: "social" },
			{ template: "I think we're overthinking this", weight: 1, category: "social" },
			{ template: "You're probably right, let's simplify", weight: 1, category: "social" },
		],
		interpolated: [
			{ template: "Hey {nearby_agent}, got a moment? Quick thought", weight: 2, category: "social" },
			{ template: "Nice approach, {nearby_agent}! Clean solution", weight: 2, category: "social" },
			{ template: "{nearby_agent} and I were just discussing this", weight: 1, category: "social" },
			{ template: "{nearby_agent}, you seeing the same thing I'm seeing?", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, check your latest build", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I left a comment on your PR", weight: 1, category: "social" },
			{ template: "Good to see you, {nearby_agent}", weight: 1, category: "social" },
			{ template: "{nearby_agent}, remind me to tell you about that bug later", weight: 1, category: "social" },
			{ template: "Heads up {nearby_agent}, I just pushed to main", weight: 1, category: "social" },
			{ template: "{nearby_agent}, you free for a quick sync?", weight: 2, category: "social" },
			{ template: "Shh, don't tell {nearby_agent} I broke the build", weight: 2, category: "social" },
			{ template: "{nearby_agent} would know the answer to this", weight: 1, category: "social" },
			{ template: "Thanks {nearby_agent}, that tip saved me an hour", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thoughts on the new feature?", weight: 1, category: "social" },
		],
	},
};
