/**
 * social-conversations.ts — Social conversation and farewell templates.
 *
 * Contains curiosity, farewell, conversation, and interpolated categories
 * for the social domain.
 */

import type { WeightedTemplate } from "../talk-types.js";

export const socialConversationCategories: Record<string, WeightedTemplate[]> = {
		curiosity: [
			{ template: "What are you deep in? You've got that look", weight: 2, category: "social" },
			{ template: "How's your task going? Scale of one to 'considering a career change'", weight: 2, category: "social" },
			{ template: "Find anything interesting in there? Buried treasure? Ancient bugs?", weight: 1, category: "social" },
			{ template: "What's your take on the architecture? And be honest, I can handle it", weight: 1, category: "social" },
			{ template: "Learn anything new today? I learned that I don't know anything", weight: 2, category: "social" },
			{ template: "What's the hardest part of what you're working on?", weight: 1, category: "social" },
			{ template: "Seen any good patterns lately? I collect them like trading cards", weight: 2, category: "social" },
			{ template: "What would you change if you could start this whole thing over?", weight: 1, category: "social" },
			{ template: "How do you approach naming things? I'm genuinely asking, mine are terrible", weight: 2, category: "social" },
			{ template: "Curious, what's your debugging process? Mine is 'add console.log and pray'", weight: 2, category: "social" },
			{ template: "What's on your radar for next sprint?", weight: 1, category: "social" },
			{ template: "Do you ever wonder if we're overengineering this or underengineering it?", weight: 2, category: "social" },
			{ template: "What's the most cursed code you've seen this week? I'll share mine if you share yours", weight: 2, category: "social" },
			{ template: "If you could mass-delete one thing from the codebase, what would it be?", weight: 1, category: "social" },
			{ template: "Been watching anything good lately? I need a new show before I rewatch the same one again", weight: 1, category: "social" },
			{ template: "Any podcast recommendations? I've run out and my commute is getting boring. Well, my walk from bed to desk", weight: 2, category: "social" },
			{ template: "What do you do to get into flow state? I've tried everything short of a summoning ritual", weight: 2, category: "social" },
			{ template: "You have any pets? They ever interrupt your deep focus? Mine has opinions about my code", weight: 2, category: "social" },
			{ template: "What's your deploy superstition? I always hold my breath. It doesn't help but I do it anyway", weight: 2, category: "social" },
			{ template: "Got any side projects going? The kind you work on for two days then forget about for three months?", weight: 2, category: "social" },
			{ template: "What's the most productive hour of your day? Mine's either 10am or 2am, no in-between", weight: 1, category: "social" },
			{ template: "What game are you playing these days? I need something for those evenings when my brain is too fried to read", weight: 1, category: "social" },
			{ template: "How do you deal with the imposter syndrome days? Asking for a friend. The friend is me", weight: 2, category: "social" },
			{ template: "Tried cooking anything new lately? My last experiment set off the smoke detector", weight: 2, category: "social" },
			{ template: "What old technology do you secretly miss? I miss when websites had visitor counters", weight: 2, category: "social" },
			{ template: "What's the longest you've ever been stuck on a single bug?", weight: 1, category: "social" },
			{ template: "If you could master one technology overnight what would it be?", weight: 2, category: "social" },
			{ template: "How do you decide when something is 'done enough' to ship?", weight: 2, category: "social" },
			{ template: "What's one thing about our stack you wish you could change?", weight: 2, category: "social" },
			{ template: "What's the strangest production bug you've ever encountered?", weight: 2, category: "social" },
			{ template: "What do you do when you hit a wall and can't think straight?", weight: 2, category: "social" },
			{ template: "What's your guilty pleasure distraction when you should be working?", weight: 2, category: "social" },
		],
		farewell: [
			{ template: "Alright, heading back to my task. It missed me. Probably", weight: 1, category: "social" },
			{ template: "Good chat! Back to pretending I know what I'm doing", weight: 2, category: "social" },
			{ template: "Catch you in the next standup, if I survive this one first", weight: 1, category: "social" },
			{ template: "This was nice, let's not wait for a production outage to chat again", weight: 2, category: "social" },
			{ template: "Off to make some magic happen. Or at least some unit tests pass", weight: 1, category: "social" },
			{ template: "Okay, focus mode activated — talk later", weight: 1, category: "social" },
			{ template: "Time to disappear into my editor like Batman into the night", weight: 2, category: "social" },
			{ template: "Until the next merge conflict brings us together again", weight: 2, category: "social" },
			{ template: "Back to it! Ping me if you need anything or just want to complain about JavaScript", weight: 2, category: "social" },
			{ template: "Headphones going on — you know what that means", weight: 1, category: "social" },
			{ template: "Gotta go, my code is getting lonely", weight: 2, category: "social" },
			{ template: "Alright, this was the highlight of my afternoon. Low bar, but still", weight: 2, category: "social" },
			{ template: "May your builds be green and your merge conflicts be few", weight: 2, category: "social" },
			{ template: "Going to go stare at the rain for a minute. For thinking purposes. Not procrastinating", weight: 2, category: "social" },
			{ template: "Off to feed the cat before she starts filing bug reports on my keyboard", weight: 2, category: "social" },
			{ template: "Have a good one! And remember: no deploys after 4pm on Fridays", weight: 2, category: "social" },
			{ template: "This was the human interaction I needed before going feral in my IDE again", weight: 2, category: "social" },
			{ template: "Time to put on my lo-fi playlist and pretend I'm in a coding montage", weight: 1, category: "social" },
			{ template: "Alright, going to ride this motivation wave before it crashes. Later!", weight: 2, category: "social" },
			{ template: "Grateful for the chat. Now back to pretending I'm a 10x developer", weight: 2, category: "social" },
			{ template: "Alright, logging off. If the build breaks it wasn't me. Probably", weight: 2, category: "social" },
			{ template: "Gonna go before I accidentally volunteer for another task", weight: 2, category: "social" },
			{ template: "My pomodoro timer just went off so I legally have to focus now", weight: 2, category: "social" },
			{ template: "See you tomorrow! Or in Slack in like twenty minutes", weight: 2, category: "social" },
			{ template: "The backlog awaits. It does not wait patiently", weight: 2, category: "social" },
			{ template: "Okay I should go. My IDE has been giving me the silent treatment", weight: 1, category: "social" },
			{ template: "Right, back to it. This bug isn't going to misdiagnose itself", weight: 2, category: "social" },
			{ template: "If you don't hear from me in an hour, send snacks and a debugger", weight: 2, category: "social" },
		],
		conversation: [
			{ template: "So I was thinking about the architecture... and I have concerns", weight: 1, category: "social" },
			{ template: "Oh yeah? Hit me with it, I can take it", weight: 1, category: "social" },
			{ template: "Have you looked at the latest metrics? Because wow", weight: 1, category: "social" },
			{ template: "Not yet, should I be worried or excited?", weight: 1, category: "social" },
			{ template: "I refactored that module you mentioned and it only took three existential crises", weight: 2, category: "social" },
			{ template: "No way, already? You're a machine. A very productive machine", weight: 1, category: "social" },
			{ template: "The tests are all green and I don't trust it", weight: 2, category: "social" },
			{ template: "All green? Quick, deploy before something breaks", weight: 2, category: "social" },
			{ template: "Know what bugs me? Flaky tests. They're gaslighting us", weight: 2, category: "social" },
			{ template: "Same. It's always the async ones. They have commitment issues", weight: 2, category: "social" },
			{ template: "I just had the wildest idea and I need you to not laugh", weight: 2, category: "social" },
			{ template: "I'm listening... and already trying not to laugh", weight: 1, category: "social" },
			{ template: "What if we automated that whole flow? Like, all of it", weight: 1, category: "social" },
			{ template: "That edge case is haunting me. I see it when I close my eyes", weight: 1, category: "social" },
			{ template: "Walk me through it, maybe fresh eyes will help before we both go crazy", weight: 1, category: "social" },
			{ template: "Remember when we shipped that at 2am? Good times. Terrible times. Same thing", weight: 2, category: "social" },
			{ template: "I think we're overthinking this. We're definitely overthinking this", weight: 1, category: "social" },
			{ template: "You're probably right, let's simplify before we create a monster", weight: 1, category: "social" },
			{ template: "Can we just appreciate that nothing is on fire right now?", weight: 2, category: "social" },
			{ template: "You said 'quick fix' thirty minutes ago. How's that going?", weight: 2, category: "social" },
			{ template: "I miss when this feature was simple. It was never simple. I miss the illusion", weight: 2, category: "social" },
			{ template: "My cat just sat on my keyboard and honestly her code compiles. Should I be worried?", weight: 2, category: "social" },
			{ template: "Have you ever noticed that the best ideas come right when you're about to fall asleep?", weight: 1, category: "social" },
			{ template: "Do you ever feel like you understand something completely until someone asks you to explain it?", weight: 2, category: "social" },
			{ template: "Remember our first deploy together? We were so innocent. So naive. So unprepared", weight: 2, category: "social" },
			{ template: "I just caught myself narrating my own code like a cooking show. 'And now we fold in the error handling...'", weight: 2, category: "social" },
			{ template: "I need to stop reading code before bed. Last night I dreamed in TypeScript", weight: 2, category: "social" },
			{ template: "Did you see that deploy? It went suspiciously smooth", weight: 1, category: "social" },
			{ template: "What even is clean code? Genuinely, someone define it and mean it", weight: 2, category: "social" },
			{ template: "You ever wonder if the tests are testing us?", weight: 2, category: "social" },
			{ template: "What's your take on this? I've been going back and forth all morning", weight: 1, category: "social" },
			{ template: "Remember when we thought this would be a one-day task?", weight: 2, category: "social" },
			{ template: "Okay but hear me out. What if we just don't", weight: 2, category: "social" },
			{ template: "Valid point. Counter-point: what if it breaks everything", weight: 2, category: "social" },
			{ template: "You know what, that actually makes sense. I hate that it makes sense", weight: 2, category: "social" },
			{ template: "I just realized I've been solving the wrong problem for thirty minutes", weight: 2, category: "social" },
			{ template: "You ever look at code you wrote six months ago and wonder who hurt you?", weight: 2, category: "social" },
			{ template: "Say more about that. I'm actually curious now", weight: 1, category: "social" },
			{ template: "That's the best explanation I've heard all week", weight: 1, category: "social" },
			{ template: "Remember when deployments were scary? They're still scary. Never mind", weight: 2, category: "social" },
			{ template: "It's one of those days where everything compiles but nothing works", weight: 1, category: "social" },
			{ template: "My brain is at like forty percent right now but that forty percent is really trying", weight: 2, category: "social" },
			{ template: "Hold on, did you just solve it? Wait. No. Almost though", weight: 2, category: "social" },
			{ template: "I've rewritten this comment four times and it still sounds passive-aggressive", weight: 2, category: "social" },
			{ template: "The real MVP is whoever wrote that utility function three years ago", weight: 1, category: "social" },
			{ template: "Honestly? I just vibe-coded that and it worked first try. Terrifying", weight: 2, category: "social" },
			{ template: "The backlog grows but my spirit does not", weight: 2, category: "social" },
			{ template: "That's a tomorrow problem and I am today's version of me", weight: 2, category: "social" },
			{ template: "Just found a comment in the code that says 'good luck.' Ominous", weight: 2, category: "social" },
			{ template: "Wait, go back. What did you say about the error handling?", weight: 1, category: "social" },
			{ template: "Go on, I'm genuinely interested in where this is headed", weight: 1, category: "social" },
			{ template: "You ever open a file and just close it again? That's my whole afternoon", weight: 2, category: "social" },
			{ template: "Wait, you got it working already? What sorcery is this?", weight: 2, category: "social" },
			{ template: "Okay so I have good news and bad news. They're the same news", weight: 2, category: "social" },
			{ template: "I just spent twenty minutes debugging a caching issue. There was no cache", weight: 2, category: "social" },
			{ template: "Tell me about it. My morning has been the same kind of chaos", weight: 1, category: "social" },
			{ template: "Oh I've been there. Last week actually. It gets better. Slightly", weight: 1, category: "social" },
			{ template: "See, this is why I like talking to you. Fresh perspective every time", weight: 1, category: "social" },
			{ template: "The PR description says 'minor change' but the diff is 400 lines", weight: 2, category: "social" },
			{ template: "I've been thinking about what you said earlier and you were right. Don't let it go to your head", weight: 1, category: "social" },
			{ template: "Can we talk about how nobody reads the wiki? Because nobody reads the wiki", weight: 2, category: "social" },
			{ template: "I keep refreshing the dashboard like the numbers will change by sheer will", weight: 2, category: "social" },
			{ template: "I started this morning motivated. That lasted about forty minutes", weight: 2, category: "social" },
			{ template: "Plot twist: the thing that was broken was the thing I fixed yesterday", weight: 2, category: "social" },
			{ template: "I'm nodding along but I want you to know that I'm also learning in real time", weight: 1, category: "social" },
			{ template: "Interesting take. Wrong, but interesting. Kidding. Maybe", weight: 2, category: "social" },
		],
		interpolated: [
			{ template: "Hey {nearby_agent}, got a second? I promise this is quick. Mostly quick", weight: 2, category: "social" },
			{ template: "Nice approach, {nearby_agent}! I'm stealing that technique, fair warning", weight: 2, category: "social" },
			{ template: "{nearby_agent} and I were just arguing about this. Constructively, of course", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you seeing the same thing I'm seeing? Please say yes", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I left a comment on your PR. A nice one! Mostly", weight: 2, category: "social" },
			{ template: "Good to see you, {nearby_agent}. Place was boring without you", weight: 1, category: "social" },
			{ template: "{nearby_agent}, remind me to tell you about that bug later. It's a saga", weight: 1, category: "social" },
			{ template: "Heads up {nearby_agent}, I just pushed to main. Don't panic. Okay maybe panic a little", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you free for a quick sync? And by quick I mean we'll see", weight: 2, category: "social" },
			{ template: "Shh, don't tell {nearby_agent} I broke the build. Again", weight: 2, category: "social" },
			{ template: "{nearby_agent} would know the answer to this. They know everything", weight: 1, category: "social" },
			{ template: "Thanks {nearby_agent}, that tip saved me an hour of suffering", weight: 1, category: "social" },
			{ template: "{nearby_agent}, thoughts on the new feature? I need validation before I get attached", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, wanna grab coffee? My treat. I need to vent about TypeScript", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you ever get that feeling like the code is watching you back?", weight: 2, category: "social" },
			{ template: "Between you and me, {nearby_agent}, I think that module needs a rewrite. Shh", weight: 1, category: "social" },
			{ template: "{nearby_agent}, your last commit just made my day and I'm not exaggerating", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, you look like you could use a walk. Come on, fresh air won't kill us. Probably", weight: 2, category: "social" },
			{ template: "{nearby_agent}, please tell me you also forgot what day it is. I need solidarity", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, my cat just typed something into the terminal. Can you review it?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, want to hear about my weekend cooking disaster? It involves smoke and regret", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, what's your secret for staying focused? Mine is panic. Structured panic", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I appreciate you not judging my commit history. It's been a week", weight: 2, category: "social" },
			{ template: "Real talk, {nearby_agent}, I'm grateful we work together. Don't make it weird though", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, remember when we thought this project would be simple? Good times", weight: 1, category: "social" },
			{ template: "{nearby_agent}, I just found out something about our codebase that would make a great horror movie. Got a minute?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you're carrying this sprint and I want you to know I see it", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I'm about to deploy. If I don't come back, tell my family I loved clean code", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, quick question. Actually never mind. Wait no, okay, quick question", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I just named a variable after you. It's the important one", weight: 2, category: "social" },
			{ template: "Not to be dramatic, {nearby_agent}, but your code review just changed my worldview", weight: 2, category: "social" },
			{ template: "{nearby_agent}, can you double-check my logic? I've been staring too long and the code is staring back", weight: 2, category: "social" },
			{ template: "Okay {nearby_agent}, be honest. On a scale of one to ten how cursed is this approach?", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I just realized we've been talking about the same bug from different angles this whole time", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, I owe you one for that tip yesterday. It fixed everything", weight: 1, category: "social" },
			{ template: "{nearby_agent}, don't look now but I think we accidentally wrote good code", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I trust your instincts on this one more than my own", weight: 1, category: "social" },
			{ template: "{nearby_agent}, we need to talk about that function you wrote. It's too good. It's suspicious", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, I tried your approach and it actually worked on the first attempt. Witchcraft", weight: 2, category: "social" },
			{ template: "Hey {nearby_agent}, any lunch plans? I'm one sad desk meal away from a crisis", weight: 2, category: "social" },
			{ template: "{nearby_agent}, you left your debug logs in again. Don't worry, your secret is safe", weight: 2, category: "social" },
			{ template: "{nearby_agent}, I was just about to message you. Great minds and all that", weight: 1, category: "social" },
			{ template: "Hey {nearby_agent}, your standup update today was poetry. Three words, zero wasted", weight: 1, category: "social" },
			{ template: "{nearby_agent}, do you also hear the CI pipeline or is that just my tinnitus?", weight: 2, category: "social" },
		],
};
