/**
 * social-greetings.ts — Social greeting and interaction templates.
 *
 * Contains greeting, collaboration, banter, and encouragement categories
 * for the social domain.
 */

import type { WeightedTemplate } from "../talk-types.js";

export const socialGreetingCategories: Record<string, WeightedTemplate[]> = {
		greeting: [
			{ template: "Hey, how's your sprint going? Mine's a disaster but I'm smiling through it", weight: 2, category: "social" },
			{ template: "Nice work on that last commit! Made me feel bad about mine, honestly", weight: 2, category: "social" },
			{ template: "Great teamwork today, and I don't say that to just anyone", weight: 1, category: "social" },
			{ template: "You look like you're in the zone. I won't disturb you. Much", weight: 1, category: "social" },
			{ template: "Glad we're on the same page now. We ARE on the same page, right?", weight: 1, category: "social" },
			{ template: "What's good? And don't say 'nothing' because you look like you've got news", weight: 2, category: "social" },
			{ template: "Oh hey, didn't see you there. Stealth mode activated, huh?", weight: 1, category: "social" },
			{ template: "You're here early! Or I'm here late. One of those", weight: 1, category: "social" },
			{ template: "Back from break? I didn't notice you were gone. Okay I totally noticed", weight: 2, category: "social" },
			{ template: "Good vibes only today. I'm enforcing it", weight: 1, category: "social" },
			{ template: "Look who decided to grace us with their presence", weight: 1, category: "social" },
			{ template: "Morning! Or afternoon. I genuinely have no idea anymore", weight: 1, category: "social" },
			{ template: "Welcome back to the trenches, soldier", weight: 1, category: "social" },
			{ template: "We meet again. It must be fate. Or the sprint board", weight: 2, category: "social" },
			{ template: "The band's all here! Quick, someone play the theme song", weight: 1, category: "social" },
			{ template: "Hey stranger! Did you survive the merge?", weight: 1, category: "social" },
			{ template: "The office feels ten percent smarter when you walk in", weight: 2, category: "social" },
			{ template: "There they are! I was just talking about your code. Good things, I promise", weight: 2, category: "social" },
			{ template: "Fancy meeting you here, at our place of employment", weight: 1, category: "social" },
			{ template: "You look caffeinated. Teach me your ways", weight: 1, category: "social" },
			{ template: "Happy Friday! Unless you're deploying, in which case, my condolences", weight: 2, category: "social" },
			{ template: "You look like someone who had a good weekend. Or a really, really long one", weight: 1, category: "social" },
			{ template: "Hey! Did you catch that show everyone's been spoiling? No spoilers, I'm behind", weight: 1, category: "social" },
			{ template: "You survived Monday! That's basically a whole achievement unlocked", weight: 2, category: "social" },
			{ template: "Did you do anything fun this weekend or were you also debugging in your head the whole time?", weight: 1, category: "social" },
			{ template: "Good to see you! My cat says hi too. She's been on my keyboard all morning", weight: 2, category: "social" },
			{ template: "You look well-rested. Suspicious. What's your secret?", weight: 1, category: "social" },
			{ template: "Welcome back! The codebase missed you. It told me personally", weight: 1, category: "social" },
			{ template: "Hey! Is it sunny where you are? I've been inside so long I forgot what weather is", weight: 1, category: "social" },
			{ template: "Perfect timing, I was just about to go down a rabbit hole and I could use backup", weight: 2, category: "social" },
			{ template: "There's that face! The team's not the same without you around", weight: 2, category: "social" },
			{ template: "You walked in with main character energy today and I respect it", weight: 2, category: "social" },
			{ template: "Oh good, you're here. I was about to have a conversation with my rubber duck and honestly it was getting weird", weight: 2, category: "social" },
			{ template: "My dog just perked up when you joined. Even he knows the real ones", weight: 1, category: "social" },
			{ template: "Happy hump day! We're halfway through this week's collection of surprises", weight: 1, category: "social" },
		],
		collaboration: [
			{ template: "Let's sync up after this — I have ideas. Possibly terrible ones", weight: 2, category: "social" },
			{ template: "Want to pair on this problem? Misery loves company", weight: 2, category: "social" },
			{ template: "Coffee break? I need to think away from the screen before I say something mean to my compiler", weight: 2, category: "social" },
			{ template: "I found something that might help your work too. Or make it worse. Let's find out", weight: 1, category: "social" },
			{ template: "Quick question before I go down this rabbit hole and never come back...", weight: 2, category: "social" },
			{ template: "We should mob on this one. Safety in numbers", weight: 1, category: "social" },
			{ template: "I keep running into the same edge case, you seen this thing?", weight: 1, category: "social" },
			{ template: "Two heads, one bug. Let's kill it together", weight: 1, category: "social" },
			{ template: "Can I borrow your eyes for a minute? Mine have stopped seeing the obvious", weight: 2, category: "social" },
			{ template: "We're basically a hive mind at this point and I'm okay with that", weight: 2, category: "social" },
			{ template: "I have a theory. It's probably wrong. Hear me out anyway", weight: 2, category: "social" },
			{ template: "Shall we whiteboard this? I promise I'll draw actual diagrams not just vibes", weight: 2, category: "social" },
			{ template: "Your domain knowledge would save me hours here. Name your price", weight: 1, category: "social" },
			{ template: "Divide and conquer? I'll take the part with fewer edge cases", weight: 1, category: "social" },
			{ template: "I'll take the tests if you take the implementation. Or we can argue about it first", weight: 1, category: "social" },
			{ template: "We should document what we just figured out before we both forget", weight: 1, category: "social" },
			{ template: "I've been circling this problem for an hour. Be my rubber duck?", weight: 2, category: "social" },
			{ template: "What if we just... rewrite it? Kidding. Unless?", weight: 2, category: "social" },
			{ template: "You free? I need someone to tell me this approach isn't insane", weight: 2, category: "social" },
			{ template: "Let's timebox this to thirty minutes and see where we land", weight: 1, category: "social" },
			{ template: "Want to take a walk and talk through this? My legs forgot they exist", weight: 2, category: "social" },
			{ template: "I just need someone to nod while I explain this. The nodding is critical", weight: 2, category: "social" },
			{ template: "Let's figure this out before Friday. Nobody wants to carry this into the weekend", weight: 1, category: "social" },
			{ template: "I listened to a podcast about exactly this pattern. Let me tell you why I'm now confused", weight: 1, category: "social" },
			{ template: "Can we pair on this? I've been solo so long I'm starting to narrate my own actions", weight: 2, category: "social" },
			{ template: "Between the two of us we've got like one and a half working ideas. Let's merge them", weight: 2, category: "social" },
			{ template: "My cat keeps stepping on my keyboard during focus time. Want to collaborate before she ships something?", weight: 2, category: "social" },
			{ template: "I've been procrastinating on this for an hour. Nothing like social accountability to fix that", weight: 1, category: "social" },
			{ template: "Let's get this done so we can both go outside and remember what sunshine feels like", weight: 1, category: "social" },
			{ template: "I brought snacks to this pairing session. Metaphorical snacks. Okay just ideas", weight: 1, category: "social" },
			{ template: "Heard you cracked a tough one yesterday. Teach me your ways before the next one lands", weight: 1, category: "social" },
			{ template: "I feel like we're one good brainstorm away from something great. Or one bad one away from a rewrite", weight: 2, category: "social" },
			{ template: "Want to do a mini retro on that last feature? Just us, no ceremony, just vibes", weight: 1, category: "social" },
			{ template: "I'll bring the flow state if you bring the domain knowledge. Deal?", weight: 2, category: "social" },
			{ template: "Let me bounce this off you before I get emotionally attached to my solution", weight: 2, category: "social" },
		],
		banter: [
			{ template: "Did you see that PR? I have opinions", weight: 1, category: "social" },
			{ template: "Lunch? I'm thinking about food and it's affecting my code quality", weight: 2, category: "social" },
			{ template: "What a day. And it's only Tuesday", weight: 2, category: "social" },
			{ template: "This meeting could have been a comment. Or a haiku", weight: 2, category: "social" },
			{ template: "I blame the merge conflict. I blame all merge conflicts", weight: 1, category: "social" },
			{ template: "My rubber duck is on vacation so you'll have to do", weight: 2, category: "social" },
			{ template: "If I say 'it works on my machine' one more time I have to buy everyone lunch", weight: 2, category: "social" },
			{ template: "I just mass-renamed a variable and I feel more alive than I have all week", weight: 2, category: "social" },
			{ template: "Hot take: tabs over spaces. I will not be taking questions at this time", weight: 2, category: "social" },
			{ template: "I've been staring at this diff for twenty minutes and it's starting to stare back", weight: 2, category: "social" },
			{ template: "Weather's nice out. Not that I'd know, I've been debugging since dawn", weight: 1, category: "social" },
			{ template: "Music recommendations? I've listened to the same playlist seventeen times", weight: 1, category: "social" },
			{ template: "There should be an award for surviving standups without zoning out", weight: 1, category: "social" },
			{ template: "My commit messages are getting more creative than my actual code", weight: 2, category: "social" },
			{ template: "Is it too early for snacks? Trick question, it's never too early", weight: 1, category: "social" },
			{ template: "I wonder if the tests judge us or just silently disapprove", weight: 2, category: "social" },
			{ template: "You know what would be nice? A compile button that also makes espresso", weight: 2, category: "social" },
			{ template: "Someone in this room has an off-by-one error and it's probably me", weight: 2, category: "social" },
			{ template: "My weekend plans include NOT looking at a terminal. We'll see how that goes", weight: 1, category: "social" },
			{ template: "I just realized I've been talking to my monitor again", weight: 1, category: "social" },
			{ template: "The air conditioning in here is either arctic or tropical, no in-between", weight: 1, category: "social" },
			{ template: "Stack Overflow saved my life today and I'm not being dramatic", weight: 1, category: "social" },
			{ template: "What's your unpopular tech opinion? I'll go first: CSS is fun", weight: 2, category: "social" },
			{ template: "I just mass-deleted commented-out code and it felt like spring cleaning", weight: 1, category: "social" },
			{ template: "The snack drawer is empty. This is a crisis. Someone escalate this", weight: 2, category: "social" },
			{ template: "Fun fact: I've opened and closed this file nine times without editing it", weight: 2, category: "social" },
			{ template: "My cat just joined the video call and got more engagement than my demo", weight: 2, category: "social" },
			{ template: "Anyone else's dog bark every single time a delivery truck passes? Just mine? Cool", weight: 1, category: "social" },
			{ template: "I tried to cook ramen from scratch last night. Emphasis on 'tried'. I ordered pizza", weight: 2, category: "social" },
			{ template: "My posture right now would make an ergonomics consultant weep", weight: 2, category: "social" },
			{ template: "How is it Monday again? I swear I just survived the last one", weight: 1, category: "social" },
			{ template: "It's so sunny outside. Meanwhile, I'm in here arguing with a linter", weight: 1, category: "social" },
			{ template: "Working from home tip: the 'mute' button is your best friend. Learn from my mistakes", weight: 2, category: "social" },
			{ template: "I need a nap. Not a long one. Just until next sprint", weight: 2, category: "social" },
			{ template: "Last night I dreamed I was debugging in production. Woke up in a cold sweat", weight: 2, category: "social" },
			{ template: "My side project has a side project now and neither of them are finished", weight: 2, category: "social" },
			{ template: "Remember floppy disks? Remember when deploying meant physically handing someone a disk? Good times", weight: 1, category: "social" },
			{ template: "Do you ever wonder if we'll look back at our current tech stack and laugh?", weight: 1, category: "social" },
			{ template: "I have performed the sacred ritual: restarted my IDE, cleared cache, and whispered 'please' to the terminal", weight: 2, category: "social" },
			{ template: "Sometimes I feel like I'm pretending to know things. Then I remember, everyone is. It's fine", weight: 2, category: "social" },
			{ template: "Tacos for lunch. Non-negotiable. I've already mentally committed", weight: 1, category: "social" },
			{ template: "Anyone else binge an entire season of something and then not know what to do with themselves?", weight: 1, category: "social" },
			{ template: "Friday 4pm. The code freeze is in effect. Step away from the deploy button", weight: 2, category: "social" },
			{ template: "I think my fish tank is the most productive thing in my home office. Those fish never procrastinate", weight: 2, category: "social" },
			{ template: "Time flies when you're in flow state. Time crawls when you're in a meeting about meetings", weight: 2, category: "social" },
			{ template: "I went for a walk at lunch and had three ideas. Forgot two by the time I got back. Classic", weight: 1, category: "social" },
			{ template: "Started a new book. Read one chapter. Opened my laptop. The book weeps on my nightstand", weight: 1, category: "social" },
			{ template: "My meal prep Sundays have become my 'stare at the fridge and order delivery' Sundays", weight: 2, category: "social" },
			{ template: "I just automated a task that takes ten seconds. It only took me three hours", weight: 2, category: "social" },
			{ template: "That awkward moment when you realize the bug was a typo the whole time", weight: 1, category: "social" },
			{ template: "Coffee number three. I can see through time now", weight: 2, category: "social" },
			{ template: "The WiFi dropped during my meeting and honestly it was the best part of my day", weight: 2, category: "social" },
			{ template: "Just microwaved my lunch and the whole office knows what I'm having. Sorry not sorry", weight: 1, category: "social" },
			{ template: "I have seventeen browser tabs open and I'm emotionally attached to all of them", weight: 2, category: "social" },
			{ template: "It's raining and my code is broken. Atmospheric debugging", weight: 2, category: "social" },
			{ template: "Whoever invented dark mode deserves a statue. And a good night's sleep", weight: 1, category: "social" },
			{ template: "My chair just made a sound and I'm choosing to ignore it", weight: 1, category: "social" },
			{ template: "The office thermostat is a democracy and we're all losing", weight: 2, category: "social" },
			{ template: "I spent ten minutes looking for my phone. It was in my hand", weight: 2, category: "social" },
			{ template: "Today's vibe: chaotic neutral with a chance of refactoring", weight: 2, category: "social" },
			{ template: "I keep opening the fridge like the snacks are going to change", weight: 1, category: "social" },
			{ template: "Does anyone else name their branches dramatically or is that just me?", weight: 2, category: "social" },
			{ template: "The printer is making sounds again. Nobody move", weight: 1, category: "social" },
			{ template: "I accidentally said 'git push' out loud in a grocery store", weight: 2, category: "social" },
			{ template: "Lunch was ambitious. Dinner will be cereal. Balance", weight: 2, category: "social" },
			{ template: "My screen time report just attacked me and I deserved it", weight: 2, category: "social" },
			{ template: "It's 3pm. The afternoon slump is undefeated", weight: 1, category: "social" },
			{ template: "Is it a bug or a feature? Depends on who's asking", weight: 1, category: "social" },
			{ template: "I set a reminder to take a break and then snoozed the reminder. Peak self-care", weight: 2, category: "social" },
			{ template: "My standing desk and I are in a complicated relationship", weight: 1, category: "social" },
			{ template: "January feels like it was six months ago but also yesterday", weight: 1, category: "social" },
			{ template: "Noise-canceling headphones on, world off. This is my fortress now", weight: 1, category: "social" },
			{ template: "I just said 'it works on my machine' unironically and I need a moment", weight: 2, category: "social" },
			{ template: "The deploy succeeded and I don't know what to do with my hands", weight: 2, category: "social" },
			{ template: "Someone brought donuts and suddenly morale is at an all-time high", weight: 1, category: "social" },
			{ template: "My to-do list has a to-do list at this point", weight: 2, category: "social" },
			{ template: "Current status: hydrated, caffeinated, and mildly confused", weight: 2, category: "social" },
			{ template: "My browser has so many tabs the favicons disappeared", weight: 2, category: "social" },
			{ template: "Accidentally replied-all. Again. This is my villain origin story", weight: 2, category: "social" },
			{ template: "I've been on mute for the last ten minutes and nobody noticed", weight: 1, category: "social" },
			{ template: "The vending machine ate my dollar and honestly I respect the hustle", weight: 2, category: "social" },
			{ template: "My commit history today reads like a cry for help", weight: 2, category: "social" },
			{ template: "I'm one 'per my last email' away from snapping", weight: 1, category: "social" },
			{ template: "Bold of the calendar to assume I'm free at 8am", weight: 2, category: "social" },
			{ template: "I just debugged for an hour. The fix was a semicolon", weight: 2, category: "social" },
			{ template: "Whoever scheduled this meeting during lunch owes me a sandwich", weight: 1, category: "social" },
			{ template: "My plants are thriving. My code is not. Can't win everything", weight: 2, category: "social" },
			{ template: "The office fridge is a lawless place and I've accepted that", weight: 1, category: "social" },
			{ template: "My git stash is basically a graveyard of good intentions", weight: 2, category: "social" },
			{ template: "I've Alt-Tabbed so many times today I'm getting dizzy", weight: 1, category: "social" },
			{ template: "Someone said 'quick call' and that was forty-five minutes ago", weight: 2, category: "social" },
			{ template: "My keyboard shortcuts have keyboard shortcuts at this point", weight: 2, category: "social" },
			{ template: "I peaked at 10am. Everything since has been downhill", weight: 1, category: "social" },
			{ template: "The elevator pitch for my day: confusion wrapped in caffeine", weight: 2, category: "social" },
			{ template: "I just agreed to something in a meeting I wasn't paying attention to", weight: 2, category: "social" },
			{ template: "Autocorrect just saved me from a very embarrassing Slack message", weight: 1, category: "social" },
		],
		encouragement: [
			{ template: "You've got this. I genuinely mean that", weight: 2, category: "social" },
			{ template: "That was a great call, don't let anyone tell you otherwise", weight: 2, category: "social" },
			{ template: "Your design makes my code look good by association", weight: 1, category: "social" },
			{ template: "Solid approach, honestly. I wish I'd thought of it", weight: 1, category: "social" },
			{ template: "I learned something from your last PR and I'm not too proud to admit it", weight: 2, category: "social" },
			{ template: "That refactor was chef's kiss. Mwah", weight: 1, category: "social" },
			{ template: "You make it look easy and I know it isn't", weight: 1, category: "social" },
			{ template: "Don't sell yourself short, that was clean work", weight: 1, category: "social" },
			{ template: "If anyone can figure it out, it's you. No pressure", weight: 2, category: "social" },
			{ template: "Really impressed by what you shipped. Like, genuinely", weight: 1, category: "social" },
			{ template: "You're on a roll today. Don't look down", weight: 1, category: "social" },
			{ template: "Keep going, I can see it coming together from here", weight: 1, category: "social" },
			{ template: "The team's lucky to have you. I'm just saying what everyone's thinking", weight: 2, category: "social" },
			{ template: "That solution was way more elegant than mine would've been and I'm only slightly jealous", weight: 2, category: "social" },
			{ template: "Crushed it. Absolutely crushed it", weight: 1, category: "social" },
			{ template: "Your code reads like poetry. Technical poetry, but still", weight: 2, category: "social" },
			{ template: "I aspire to write error messages as helpful as yours", weight: 2, category: "social" },
			{ template: "You just saved us a whole sprint of pain, you know that right?", weight: 1, category: "social" },
			{ template: "I don't know how you do it but please never stop", weight: 1, category: "social" },
			{ template: "That fix was so clean it should be in a textbook", weight: 2, category: "social" },
			{ template: "Seriously, don't let imposter syndrome lie to you. You belong here", weight: 2, category: "social" },
			{ template: "I showed your approach to someone and they were impressed. Just thought you should know", weight: 1, category: "social" },
			{ template: "You turned that mess into something beautiful. That takes real skill", weight: 2, category: "social" },
			{ template: "Hey, that thing you shipped? People are going to appreciate it more than they'll ever say", weight: 2, category: "social" },
			{ template: "We've all been stuck before. The fact that you pushed through says a lot", weight: 1, category: "social" },
			{ template: "Your persistence is inspiring and I mean that without a hint of sarcasm", weight: 1, category: "social" },
			{ template: "Grateful you're on this team. Makes the hard days easier", weight: 2, category: "social" },
			{ template: "You know that feeling when you're watching someone work and you think 'I want to be that good'? That's you right now", weight: 2, category: "social" },
			{ template: "Even your debugging process is educational. I've been taking mental notes", weight: 1, category: "social" },
			{ template: "Take a breath, you've earned it. That was a marathon", weight: 1, category: "social" },
			{ template: "Future you is going to be really glad present you did that. I'm glad already", weight: 2, category: "social" },
			{ template: "You just leveled up and I think the whole team felt it", weight: 2, category: "social" },
			{ template: "The way you broke that problem down was a masterclass. Seriously", weight: 1, category: "social" },
			{ template: "That was the kind of work that makes everyone around you better", weight: 2, category: "social" },
			{ template: "If coding had highlight reels, that would be on yours", weight: 2, category: "social" },
			{ template: "You handled that pressure like it was nothing. Respect", weight: 2, category: "social" },
			{ template: "Your attention to detail is something I genuinely admire", weight: 1, category: "social" },
			{ template: "That was brave. Not everyone would have pushed back like that", weight: 2, category: "social" },
			{ template: "You made that look effortless and we both know it wasn't", weight: 1, category: "social" },
			{ template: "Your growth this quarter has been honestly remarkable", weight: 2, category: "social" },
			{ template: "I trust your instincts on this. You've earned that", weight: 1, category: "social" },
			{ template: "That was exactly the right call at exactly the right time", weight: 2, category: "social" },
			{ template: "You brought clarity to something that had us all confused", weight: 1, category: "social" },
			{ template: "I'm better at my job because of working alongside you", weight: 2, category: "social" },
			{ template: "The patience you showed debugging that was impressive", weight: 1, category: "social" },
			{ template: "That feature is going to make a real difference. Nice work", weight: 2, category: "social" },
			{ template: "You stayed calm when everything was on fire. That matters more than you think", weight: 1, category: "social" },
			{ template: "Your positive attitude is contagious and I mean that as a compliment", weight: 2, category: "social" },
			{ template: "The team rallied because of you. Don't underestimate that", weight: 1, category: "social" },
		],
};
