/**
 * tier-modifiers.ts — Relationship-tier prefix and suffix pools.
 *
 * These wrap existing phrases to add tone appropriate to the current
 * relationship tier between two agents. Applied with TIER_MODIFIER_CHANCE (15%).
 */

import type { RelationshipTier } from "../../relationship-system.js";

export const TIER_PREFIXES: Record<RelationshipTier, readonly string[]> = {
	rival: [
		"Oh great, {nearby_agent}'s here.",
		"Don't look now but...",
		"Speaking of bad ideas...",
		"Here we go again...",
		"Oh, it's you.",
		"Wonderful. Just wonderful.",
		"Of ALL the people...",
		"Oh sure, of course it's {nearby_agent}.",
		"What a surprise. Not.",
		"Ah yes, my favorite person.",
		"Deep breath...",
		"I was having a good day until...",
	],
	acquaintance: [
		"Hey, uh...",
		"So...",
		"Not sure if you're busy but...",
		"I don't mean to interrupt but...",
		"If you have a second...",
		"Sorry to bother you but...",
		"Quick thing...",
		"Not sure if this is relevant but...",
		"I was just thinking...",
		"Don't know if you noticed but...",
		"Random thought...",
		"Might be nothing but...",
	],
	colleague: [
		"Quick thought—",
		"Oh hey, good timing—",
		"You'd appreciate this—",
		"FYI—",
		"Heads up—",
		"Just noticed—",
		"Worth mentioning—",
		"Thought you should know—",
		"Between us—",
		"Speaking of which—",
		"Oh, related to what you said—",
		"This might interest you—",
	],
	friend: [
		"Okay you're gonna love this—",
		"Don't judge me but—",
		"Remember what I said about—",
		"You won't believe this—",
		"Be honest with me—",
		"I need your opinion on something—",
		"Okay so hear me out—",
		"Real talk—",
		"Between you and me—",
		"You know how I feel about—",
		"Tell me I'm not crazy—",
		"Only telling you this because—",
	],
	"best-friend": [
		"You already know what I'm going to say—",
		"Same wavelength—",
		"Tell me you see it too—",
		"Okay so—",
		"Read my mind—",
		"You and I both know—",
		"I don't even have to explain—",
		"We were just talking about this—",
		"Jinx—",
		"Finish my sentence—",
		"You feel it too right?",
		"I was literally about to say—",
	],
};

export const TIER_SUFFIXES: Record<RelationshipTier, readonly string[]> = {
	rival: [
		"...but what would I know",
		"...unlike SOME people",
		"...not naming names",
		"...but sure, what do YOU think",
		"...shocking, I know",
		"...take it or leave it",
		"...but hey, I'm just the person who's right",
		"...but who am I to say",
		"...unfortunately",
		"...not that anyone asked",
		"...for what it's worth. Which is a lot",
		"...but go off",
	],
	acquaintance: [
		"...anyway!",
		"...just a thought",
		"...no worries if not",
		"...totally optional",
		"...feel free to ignore that",
		"...or not, up to you",
		"...just throwing it out there",
		"...sorry if that's obvious",
		"...I could be wrong though",
		"...but what do I know, ha",
		"...don't mind me",
		"...if that makes sense",
	],
	colleague: [
		"...worth a look",
		"...what do you think?",
		"...you've probably seen this before",
		"...might be useful",
		"...let me know your thoughts",
		"...just flagging it",
		"...curious what you'd do",
		"...food for thought",
		"...on your radar?",
		"...something to consider",
		"...thought you'd want to know",
		"...keep me posted",
	],
	friend: [
		"...you owe me one",
		"...classic us",
		"...and that's why we work",
		"...don't pretend you're surprised",
		"...but you already knew that",
		"...we've been here before",
		"...and I'd do it again",
		"...you get me",
		"...our little secret",
		"...that's the deal",
		"...partners in crime",
		"...you know the drill",
	],
	"best-friend": [
		"...like that time with the deploy",
		"...you get it",
		"...us against the codebase",
		"...say no more",
		"...I knew you'd understand",
		"...that's our thing",
		"...wouldn't want anyone else here",
		"...we've survived worse",
		"...ride or die",
		"...always",
		"...you know what I mean",
		"...we don't even need to say it",
	],
};
