/**
 * tier-modifiers.ts — Relationship-tier prefix and suffix pools.
 *
 * These wrap existing phrases to add tone appropriate to the current
 * relationship tier between two agents. Applied with TIER_MODIFIER_CHANCE (15%).
 */

import type { RelationshipTier } from "../../relationship-system.js";

export const TIER_PREFIXES: Record<RelationshipTier, readonly string[]> = {
	rival: [
		"Oh look, {nearby_agent}'s gracing us with their presence.",
		"Ah, {nearby_agent}. My code review nemesis.",
		"Speaking of overengineered solutions...",
		"Here we go again. Brace for unsolicited opinions...",
		"Oh, it's you. And your strong opinions about tabs vs spaces.",
		"My least favorite notification just walked in.",
		"Of ALL the people to be pairing with...",
		"Oh sure, the person who force-pushes to main. Hi {nearby_agent}.",
		"Look who finally finished their 'quick refactor'.",
		"Ah yes, the person who thinks every PR needs a rewrite.",
		"Let me put on my diplomatic face... nope, can't find it.",
		"I was having a productive day before {nearby_agent} appeared.",
	],
	acquaintance: [
		"Hey, uh... we've met right? In that standup?",
		"So... I don't know if we've really talked before but...",
		"Not sure if you're in the middle of something but...",
		"I don't want to overstep but...",
		"Sorry, is now a bad time? I can come back...",
		"Sorry to bother you, I know we don't really...",
		"Quick thing, and feel free to completely ignore me...",
		"Not sure if this is even your area but...",
		"I was just thinking, and forgive me if this is dumb...",
		"Don't know if you noticed, but I didn't want to just not say anything...",
		"This might be completely out of line but...",
		"I could be totally wrong about this, but...",
	],
	colleague: [
		"Quick thought—",
		"Oh hey, good timing—",
		"You'd appreciate this—",
		"FYI—",
		"Heads up—",
		"Just noticed—",
		"Worth mentioning—",
		"Thought you should know—",
		"Between us—",
		"Speaking of which—",
		"Oh, related to what you said—",
		"This might interest you—",
	],
	friend: [
		"Okay you're gonna love this—",
		"Don't judge me but—",
		"Remember what I said about—",
		"You won't believe this—",
		"Be honest with me—",
		"I need your opinion on something—",
		"Okay so hear me out—",
		"Real talk—",
		"Between you and me—",
		"You know how I feel about—",
		"Tell me I'm not crazy—",
		"Only telling you this because—",
	],
	"best-friend": [
		"You already know what I'm going to say. You always do—",
		"Okay, remember our 3AM debugging session? This is like that—",
		"Tell me you see it too, I can't be the only one—",
		"Okay so, and don't you dare laugh—",
		"Read my mind. I know you can, you weirdo—",
		"You and I both know this is cursed—",
		"I don't even have to explain, you're already nodding—",
		"Remember when we said 'never again'? Well—",
		"Jinx. Again. We need to stop doing that—",
		"Finish my sentence, I'm too tired to use words—",
		"You smell it too right? The code smell? Right?",
		"I swear on our shared git history—",
	],
};

export const TIER_SUFFIXES: Record<RelationshipTier, readonly string[]> = {
	rival: [
		"...but what would I know. I only wrote the original implementation",
		"...unlike SOME people's pull requests I could mention",
		"...not naming names. But the git blame doesn't lie",
		"...but sure, you probably have a 'better' way",
		"...shocking, I know. Almost as shocking as your test coverage",
		"...take it or leave it. You'll leave it. You always leave it",
		"...but hey, I'm just the one whose code actually compiles",
		"...but who am I to question your architectural decisions",
		"...unfortunately for everyone who has to maintain your code",
		"...not that anyone asked. Not that anyone ever asks",
		"...for what it's worth. Which is more than your last sprint velocity",
		"...but go off. Your deploys certainly do",
	],
	acquaintance: [
		"...anyway! Sorry, I'll let you get back to it",
		"...just a thought. Probably a bad one. Sorry",
		"...no worries if not, honestly, zero pressure",
		"...totally optional, I don't want to impose",
		"...feel free to completely disregard all of that",
		"...or not, seriously, I won't be offended either way",
		"...just throwing it out there. Into the void. Where it belongs maybe",
		"...sorry if that's obvious, I'm still learning everyone's workflow",
		"...I could be totally off base though, I'm new-ish",
		"...but what do I know, I've only been here a few months, ha",
		"...don't mind me, I'll just be over here. Quietly",
		"...if that makes sense? I can explain differently if not",
	],
	colleague: [
		"...worth a look",
		"...what do you think?",
		"...you've probably seen this before",
		"...might be useful",
		"...let me know your thoughts",
		"...just flagging it",
		"...curious what you'd do",
		"...food for thought",
		"...on your radar?",
		"...something to consider",
		"...thought you'd want to know",
		"...keep me posted",
	],
	friend: [
		"...you owe me one",
		"...classic us",
		"...and that's why we work",
		"...don't pretend you're surprised",
		"...but you already knew that",
		"...we've been here before",
		"...and I'd do it again",
		"...you get me",
		"...our little secret",
		"...that's the deal",
		"...partners in crime",
		"...you know the drill",
	],
	"best-friend": [
		"...like that deploy at 2AM. We don't talk about that deploy",
		"...you get it. You always get it. That's why we work",
		"...us against the codebase, same as always",
		"...say no more. The look on your face says everything",
		"...I knew you'd understand before I even finished the sentence",
		"...that's our thing. Nobody else gets it and that's fine",
		"...wouldn't want anyone else in this trench with me",
		"...we've survived worse deploys and worse code reviews",
		"...ride or die. Or at least pair-program or die",
		"...always. Through merges and merge conflicts alike",
		"...you know exactly what I mean. We share a brain sometimes",
		"...we don't even need to say it. The git log tells our story",
	],
};
