import type { InteractionTemplate } from "../interaction-types.js";

export const AGENT_AGENT_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "code-review-banter",
		category: "social",
		action: "code-review-banter",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "work-adjacent"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning"],
		priority: 30,
		cooldownMs: 60000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "code-review-banter" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
		chainTemplates: ["code-review-escalation"],
		chainChance: 0.2,
	},
	{
		id: "lunch-invite",
		category: "social",
		action: "lunch-invite",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 3,
		tags: ["social", "meal", "bonding"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["lunch"],
		priority: 35,
		cooldownMs: 120000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "lunch-invite" },
			{ type: "need-change", target: "all", need: "social", amount: 5 },
		],
	},
	{
		id: "morning-greeting",
		category: "social",
		action: "morning-greeting",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 5,
		tags: ["greeting", "routine"],
		tierRange: ["acquaintance", "best-friend"],
		phaseFilter: ["morning-arrival"],
		priority: 25,
		cooldownMs: 300000,
		duration: 4000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "morning-greeting" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "work-complaint",
		category: "social",
		action: "work-complaint",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["venting", "catharsis"],
		tierRange: ["friend", "best-friend"],
		phaseFilter: ["afternoon-slump"],
		priority: 25,
		cooldownMs: 180000,
		duration: 12000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "work-complaint" },
			{ type: "need-change", target: "initiator", need: "morale", amount: 2 },
			{ type: "need-change", target: "all", need: "social", amount: 5 },
		],
	},
	{
		id: "knowledge-share",
		category: "work",
		action: "knowledge-share",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["work", "learning", "mentoring"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning", "afternoon"],
		priority: 40,
		cooldownMs: 120000,
		duration: 15000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "knowledge-share" },
			{ type: "need-change", target: "targets", need: "focus", amount: 5 },
		],
	},
] as const;
