import type { InteractionTemplate } from "../interaction-types.js";

export const AGENT_AGENT_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "code-review-banter",
		category: "social",
		action: "code-review-banter",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "work-adjacent"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning"],
		priority: 30,
		cooldownMs: 60000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "code-review-banter" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
		chainTemplates: ["code-review-escalation"],
		chainChance: 0.2,
	},
	{
		id: "lunch-invite",
		category: "social",
		action: "lunch-invite",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 3,
		tags: ["social", "meal", "bonding"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["lunch"],
		priority: 35,
		cooldownMs: 120000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "lunch-invite" },
			{ type: "need-change", target: "all", need: "social", amount: 5 },
		],
	},
	{
		id: "morning-greeting",
		category: "social",
		action: "morning-greeting",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 5,
		tags: ["greeting", "routine"],
		tierRange: ["acquaintance", "best-friend"],
		phaseFilter: ["morning-arrival"],
		priority: 25,
		cooldownMs: 300000,
		duration: 4000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "morning-greeting" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "work-complaint",
		category: "social",
		action: "work-complaint",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["venting", "catharsis"],
		tierRange: ["friend", "best-friend"],
		phaseFilter: ["afternoon-slump"],
		priority: 25,
		cooldownMs: 180000,
		duration: 12000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "work-complaint" },
			{ type: "need-change", target: "initiator", need: "morale", amount: 2 },
			{ type: "need-change", target: "all", need: "social", amount: 5 },
		],
	},
	{
		id: "knowledge-share",
		category: "work",
		action: "knowledge-share",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["work", "learning", "mentoring"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning", "afternoon"],
		priority: 40,
		cooldownMs: 120000,
		duration: 15000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "knowledge-share" },
			{ type: "need-change", target: "targets", need: "focus", amount: 5 },
		],
	},

	// ── Work (4 new) ───────────────────────────────────────────────────

	{
		id: "pair-debugging",
		category: "work",
		action: "pair-debugging",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["work", "collaboration"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning", "afternoon"],
		priority: 40,
		cooldownMs: 120000,
		duration: 15000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "pair-debugging" },
			{ type: "need-change", target: "all", need: "focus", amount: 5 },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "brainstorm-invite",
		category: "work",
		action: "brainstorm-invite",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["work", "creative"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning"],
		priority: 35,
		cooldownMs: 180000,
		duration: 12000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "brainstorm-invite" },
			{ type: "need-change", target: "all", need: "morale", amount: 3 },
		],
	},
	{
		id: "deadline-stress-vent",
		category: "work",
		action: "deadline-stress-vent",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["work", "stress", "venting"],
		tierRange: ["friend", "best-friend"],
		phaseFilter: ["afternoon-slump"],
		priority: 20,
		cooldownMs: 240000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "deadline-stress-vent" },
			{ type: "need-change", target: "initiator", need: "morale", amount: 3 },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "rubber-ducking",
		category: "work",
		action: "rubber-ducking",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["work", "problem-solving"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning", "afternoon"],
		priority: 30,
		cooldownMs: 150000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "rubber-ducking" },
			{ type: "need-change", target: "initiator", need: "focus", amount: 5 },
		],
	},

	// ── Social (6 new) ─────────────────────────────────────────────────

	{
		id: "departure-wave",
		category: "social",
		action: "departure-wave",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 4,
		tags: ["social", "routine", "farewell"],
		tierRange: ["acquaintance", "best-friend"],
		phaseFilter: ["evening-departure"],
		priority: 25,
		cooldownMs: 300000,
		duration: 3000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "departure-wave" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "domain-crossover-chat",
		category: "social",
		action: "domain-crossover-chat",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "cross-domain"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning", "lunch"],
		priority: 30,
		cooldownMs: 120000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "domain-crossover-chat" },
			{ type: "need-change", target: "all", need: "social", amount: 3 },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "celebrating-milestone",
		category: "social",
		action: "celebrating-milestone",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "celebration", "milestone"],
		tierRange: ["colleague", "best-friend"],
		priority: 45,
		cooldownMs: 300000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "celebrating-milestone" },
			{ type: "need-change", target: "all", need: "morale", amount: 5 },
			{ type: "affinity-change", target: "targets", amount: 2 },
		],
	},
	{
		id: "gossip-about-absent",
		category: "social",
		action: "gossip-about-absent",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "gossip"],
		tierRange: ["friend", "best-friend"],
		phaseFilter: ["lunch", "afternoon-slump"],
		priority: 20,
		cooldownMs: 240000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "gossip-about-absent" },
			{ type: "need-change", target: "all", need: "social", amount: 4 },
		],
	},
	{
		id: "noticed-mood-change",
		category: "social",
		action: "noticed-mood-change",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "observation", "empathy"],
		tierRange: ["colleague", "best-friend"],
		priority: 35,
		cooldownMs: 180000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "noticed-mood-change" },
			{ type: "need-change", target: "targets", need: "morale", amount: 3 },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "suggest-break",
		category: "social",
		action: "suggest-break",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 3,
		tags: ["social", "care", "wellbeing"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["afternoon-slump"],
		priority: 30,
		cooldownMs: 180000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "suggest-break" },
			{ type: "need-change", target: "targets", need: "morale", amount: 4 },
		],
	},

	// ── Reactive (3 new) ───────────────────────────────────────────────

	{
		id: "awkward-silence-break",
		category: "reactive",
		action: "awkward-silence-break",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 3,
		tags: ["reactive", "humor", "social"],
		tierRange: ["acquaintance", "best-friend"],
		priority: 20,
		cooldownMs: 120000,
		duration: 4000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "awkward-silence-break" },
			{ type: "need-change", target: "all", need: "social", amount: 2 },
		],
	},
	{
		id: "overheard-something",
		category: "reactive",
		action: "overheard-something",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "curiosity"],
		tierRange: ["acquaintance", "best-friend"],
		priority: 15,
		cooldownMs: 180000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "overheard-something" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "bumped-into",
		category: "reactive",
		action: "bumped-into",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["reactive", "surprise", "physical"],
		tierRange: ["acquaintance", "best-friend"],
		priority: 20,
		cooldownMs: 60000,
		duration: 3000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "bumped-into" },
			{ type: "need-change", target: "all", need: "social", amount: 1 },
		],
	},

	// ── Playful (2 new) ────────────────────────────────────────────────

	{
		id: "competitive-challenge",
		category: "playful",
		action: "competitive-challenge",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["playful", "competition"],
		tierRange: ["colleague", "best-friend"],
		phaseFilter: ["productive-morning", "afternoon"],
		priority: 25,
		cooldownMs: 240000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "competitive-challenge" },
			{ type: "need-change", target: "all", need: "morale", amount: 3 },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "inside-joke-callback",
		category: "playful",
		action: "inside-joke-callback",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["playful", "humor", "bonding"],
		tierRange: ["friend", "best-friend"],
		priority: 20,
		cooldownMs: 180000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "inside-joke-callback" },
			{ type: "need-change", target: "all", need: "social", amount: 3 },
			{ type: "affinity-change", target: "targets", amount: 2 },
		],
	},
] as const;
