import type { InteractionTemplate } from "../interaction-types.js";

export const AGENT_PET_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "sneak-treat",
		category: "care",
		action: "sneak-treat",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [
			{ type: "proximity", maxDistance: 2 },
		],
		weight: 1,
		tags: ["care", "food"],
		priority: 30,
		cooldownMs: 300000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "sneak-treat" },
			{ type: "need-change", target: "targets", need: "hunger", amount: 15 },
		],
		chainTemplates: ["caught-sneaking-treat"],
		chainChance: 0.3,
	},
	{
		id: "pet-greeting",
		category: "social",
		action: "pet-greeting",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "pet"],
		priority: 25,
		cooldownMs: 120000,
		duration: 4000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "pet-greeting" },
			{ type: "affinity-change", target: "targets", amount: 2 },
		],
	},
	{
		id: "play-with-pet",
		category: "playful",
		action: "play-with-pet",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 1,
		tags: ["playful", "pet"],
		priority: 30,
		cooldownMs: 180000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "play-with-pet" },
			{ type: "need-change", target: "initiator", need: "social", amount: 5 },
		],
	},
	{
		id: "play-fetch",
		category: "playful",
		action: "play-fetch",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 2,
		tags: ["playful", "pet", "exercise"],
		priority: 30,
		cooldownMs: 120000,
		duration: 12000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "play-fetch" },
			{ type: "need-change", target: "initiator", need: "energy", amount: -3 },
			{ type: "affinity-change", target: "targets", amount: 3 },
		],
	},
	{
		id: "teach-trick",
		category: "work",
		action: "teach-trick",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 1,
		tags: ["work", "pet", "training"],
		priority: 25,
		cooldownMs: 300000,
		duration: 15000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "teach-trick" },
			{ type: "affinity-change", target: "targets", amount: 2 },
			{ type: "need-change", target: "initiator", need: "focus", amount: -2 },
		],
	},
	{
		id: "pet-grooming",
		category: "care",
		action: "pet-grooming",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 2,
		tags: ["care", "pet", "grooming"],
		priority: 25,
		cooldownMs: 240000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "pet-grooming" },
			{ type: "affinity-change", target: "targets", amount: 4 },
		],
	},
	{
		id: "give-treat",
		category: "care",
		action: "give-treat",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 3,
		tags: ["care", "pet", "reward"],
		priority: 20,
		cooldownMs: 180000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "give-treat" },
			{ type: "need-change", target: "targets", need: "hunger", amount: 10 },
			{ type: "affinity-change", target: "targets", amount: 2 },
		],
	},
	{
		id: "talk-to-pet",
		category: "social",
		action: "talk-to-pet",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 4,
		tags: ["social", "pet", "ambient"],
		priority: 15,
		cooldownMs: 60000,
		duration: 4000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "talk-to-pet" },
			{ type: "need-change", target: "initiator", need: "social", amount: 3 },
		],
	},
] as const;
