import type { InteractionTemplate } from "../interaction-types.js";

export const CROSS_TYPE_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "caught-sneaking-treat",
		category: "reactive",
		action: "caught-sneaking-treat",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "chain", "humor"],
		priority: 35,
		cooldownMs: 300000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:caught" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "what-did-you-buy",
		category: "social",
		action: "what-did-you-buy",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "chain", "commerce"],
		priority: 25,
		cooldownMs: 120000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:curious" },
			{ type: "need-change", target: "targets", need: "social", amount: 3 },
		],
	},
	{
		id: "chase-sequence",
		category: "playful",
		action: "chase-sequence",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 1,
		tags: ["playful", "chain", "pet"],
		priority: 30,
		cooldownMs: 120000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "reactive:playful" },
			{ type: "need-change", target: "initiator", need: "energy", amount: -5 },
			{ type: "need-change", target: "all", need: "social", amount: 5 },
		],
	},
	{
		id: "post-commerce-gossip",
		category: "social",
		action: "post-commerce-gossip",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "chain", "commerce"],
		priority: 25,
		cooldownMs: 120000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "post-commerce-gossip" },
			{ type: "need-change", target: "all", need: "social", amount: 3 },
		],
	},
	{
		id: "post-care-gratitude",
		category: "social",
		action: "post-care-gratitude",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "chain", "gratitude"],
		priority: 25,
		cooldownMs: 180000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "post-care-gratitude" },
			{ type: "affinity-change", target: "targets", amount: 3 },
		],
	},
	{
		id: "post-play-escalation",
		category: "playful",
		action: "post-play-escalation",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["playful", "chain", "escalation"],
		priority: 30,
		cooldownMs: 120000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "reactive:playful" },
			{ type: "need-change", target: "all", need: "energy", amount: -3 },
			{ type: "need-change", target: "all", need: "social", amount: 4 },
		],
	},
	{
		id: "post-work-debrief",
		category: "social",
		action: "post-work-debrief",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["social", "chain", "work"],
		priority: 20,
		cooldownMs: 180000,
		duration: 7000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "post-work-debrief" },
			{ type: "need-change", target: "all", need: "social", amount: 3 },
			{ type: "need-change", target: "all", need: "focus", amount: 2 },
		],
	},
	{
		id: "pet-stole-seat-reaction",
		category: "reactive",
		action: "pet-stole-seat-reaction",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 2,
		tags: ["reactive", "chain", "humor"],
		priority: 30,
		cooldownMs: 180000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:pet-stole-seat" },
			{ type: "mood-change", target: "initiator", mood: "amused" },
		],
	},
	{
		id: "merchant-recommendation",
		category: "social",
		action: "merchant-recommendation",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "chain", "commerce"],
		priority: 20,
		cooldownMs: 240000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-recommendation" },
			{ type: "need-change", target: "targets", need: "social", amount: 2 },
		],
	},
	{
		id: "room-mood-spread",
		category: "reactive",
		action: "room-mood-spread",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["reactive", "chain", "mood"],
		priority: 25,
		cooldownMs: 120000,
		duration: 0,
		effects: [
			{ type: "mood-change", target: "targets", mood: "sympathetic" },
			{ type: "need-change", target: "targets", need: "social", amount: 2 },
		],
	},
	{
		id: "group-celebration-toast",
		category: "social",
		action: "group-celebration-toast",
		cardinality: "one-to-many",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "chain", "celebration"],
		priority: 30,
		cooldownMs: 300000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "group-celebration-toast" },
			{ type: "need-change", target: "all", need: "morale", amount: 5 },
			{ type: "need-change", target: "all", need: "social", amount: 4 },
		],
	},
	{
		id: "misunderstanding-cleared",
		category: "reactive",
		action: "misunderstanding-cleared",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "chain", "resolution"],
		priority: 30,
		cooldownMs: 300000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:misunderstanding-cleared" },
			{ type: "affinity-change", target: "targets", amount: 4 },
			{ type: "mood-change", target: "all", mood: "relieved" },
		],
	},
	{
		id: "code-review-escalation",
		category: "social",
		action: "code-review-escalation",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "chain", "work-adjacent", "debate"],
		tierRange: ["colleague", "best-friend"],
		priority: 35,
		cooldownMs: 120000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:debate" },
			{ type: "need-change", target: "all", need: "focus", amount: -3 },
			{ type: "affinity-change", target: "targets", amount: -1 },
		],
	},
] as const;
