import type { InteractionTemplate } from "../interaction-types.js";

export const CROSS_TYPE_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "caught-sneaking-treat",
		category: "reactive",
		action: "caught-sneaking-treat",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "chain", "humor"],
		priority: 35,
		cooldownMs: 300000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:caught" },
			{ type: "affinity-change", target: "targets", amount: 1 },
		],
	},
	{
		id: "what-did-you-buy",
		category: "social",
		action: "what-did-you-buy",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "chain", "commerce"],
		priority: 25,
		cooldownMs: 120000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "reactive:curious" },
			{ type: "need-change", target: "targets", need: "social", amount: 3 },
		],
	},
	{
		id: "chase-sequence",
		category: "playful",
		action: "chase-sequence",
		cardinality: "one-to-one",
		initiatorTypes: ["agent"],
		targetTypes: ["pet"],
		prerequisites: [],
		weight: 1,
		tags: ["playful", "chain", "pet"],
		priority: 30,
		cooldownMs: 120000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "reactive:playful" },
			{ type: "need-change", target: "initiator", need: "energy", amount: -5 },
			{ type: "need-change", target: "all", need: "social", amount: 5 },
		],
	},
] as const;
