import type { InteractionTemplate } from "../interaction-types.js";

export const DIRECTOR_COMMAND_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "director-praise",
		category: "directive",
		action: "director-praise",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["directive", "praise"],
		priority: 95,
		cooldownMs: 60000,
		duration: 5000,
		effects: [
			{ type: "need-change", target: "targets", need: "morale", amount: 15 },
			{ type: "memory-record", target: "targets", memory: "Praised by director" },
		],
	},
	{
		id: "director-team-huddle",
		category: "directive",
		action: "director-team-huddle",
		cardinality: "one-to-many",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["directive", "team"],
		priority: 95,
		cooldownMs: 120000,
		duration: 20000,
		effects: [
			{ type: "need-change", target: "targets", need: "social", amount: 10 },
			{ type: "need-change", target: "targets", need: "focus", amount: 5 },
			{ type: "memory-record", target: "targets", memory: "Attended team huddle" },
		],
	},
	{
		id: "director-assign-task",
		category: "directive",
		action: "director-assign-task",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["directive", "task"],
		priority: 95,
		cooldownMs: 30000,
		duration: 3000,
		effects: [
			{ type: "state-change", target: "targets", key: "assigned", value: true },
		],
	},
	{
		id: "director-redirect-focus",
		category: "directive",
		action: "director-redirect-focus",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["directive", "focus"],
		priority: 92,
		cooldownMs: 60000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "director-redirect-focus" },
			{ type: "need-change", target: "targets", need: "focus", amount: 10 },
			{ type: "memory-record", target: "targets", memory: "Redirected by director" },
		],
	},
	{
		id: "director-one-on-one",
		category: "directive",
		action: "director-one-on-one",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["directive", "feedback"],
		priority: 90,
		cooldownMs: 300000,
		duration: 15000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "director-one-on-one" },
			{ type: "need-change", target: "targets", need: "morale", amount: 8 },
			{ type: "need-change", target: "targets", need: "social", amount: 5 },
			{ type: "memory-record", target: "targets", memory: "Had one-on-one with director" },
		],
	},
	{
		id: "director-delegate-task",
		category: "directive",
		action: "director-delegate-task",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["directive", "delegation"],
		priority: 88,
		cooldownMs: 60000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "director-delegate-task" },
			{ type: "state-change", target: "targets", key: "delegated", value: true },
			{ type: "memory-record", target: "targets", memory: "Received delegated task from director" },
		],
	},
	{
		id: "director-announce-milestone",
		category: "directive",
		action: "director-announce-milestone",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["directive", "celebration"],
		priority: 85,
		cooldownMs: 600000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "director-announce-milestone" },
			{ type: "need-change", target: "targets", need: "morale", amount: 12 },
			{ type: "particle", target: "targets", particleType: "confetti" },
		],
	},
	{
		id: "director-encourage",
		category: "directive",
		action: "director-encourage",
		cardinality: "one-to-one",
		initiatorTypes: ["director"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 3,
		tags: ["directive", "morale"],
		priority: 85,
		cooldownMs: 120000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "director-encourage" },
			{ type: "need-change", target: "targets", need: "morale", amount: 7 },
			{ type: "mood-change", target: "targets", mood: "motivated" },
		],
	},
] as const;
