import type { InteractionTemplate } from "../interaction-types.js";

export const ENVIRONMENT_EVENT_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "build-break-reaction",
		category: "reactive",
		action: "build-break-reaction",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "build"],
		priority: 80,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "thought", phrasePool: "reactive:focus-lost" },
			{ type: "need-change", target: "targets", need: "focus", amount: -5 },
			{ type: "mood-change", target: "targets", mood: "concerned" },
		],
	},
	{
		id: "deploy-celebration",
		category: "reactive",
		action: "deploy-celebration",
		cardinality: "many-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "celebration"],
		priority: 75,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "all", bubbleKind: "emote", phrasePool: "reactive:morale-boost" },
			{ type: "need-change", target: "all", need: "morale", amount: 10 },
			{ type: "particle", target: "all", particleType: "confetti" },
		],
	},
	{
		id: "birthday-party",
		category: "social",
		action: "birthday-party",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "environment", "celebration"],
		priority: 50,
		cooldownMs: 86400000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "speech", phrasePool: "reactive:morale-boost" },
			{ type: "need-change", target: "targets", need: "morale", amount: 15 },
			{ type: "need-change", target: "all", need: "social", amount: 10 },
		],
	},
	{
		id: "weather-mood-shift",
		category: "environmental",
		action: "weather-mood-shift",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["environmental", "weather"],
		priority: 20,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "mood-change", target: "targets", mood: "weather-affected" },
			{ type: "need-change", target: "targets", need: "energy", amount: -2 },
		],
	},
	{
		id: "seasonal-decorations",
		category: "social",
		action: "seasonal-decorations",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "seasonal", "celebration"],
		priority: 25,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "thought", phrasePool: "seasonal-decorations" },
			{ type: "need-change", target: "targets", need: "morale", amount: 5 },
		],
	},
	{
		id: "power-flicker",
		category: "reactive",
		action: "power-flicker",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "surprise"],
		priority: 40,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "emote", phrasePool: "reactive:surprise" },
			{ type: "need-change", target: "targets", need: "focus", amount: -4 },
			{ type: "mood-change", target: "targets", mood: "startled" },
		],
	},
	{
		id: "new-tool-announcement",
		category: "reactive",
		action: "new-tool-announcement",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "work"],
		priority: 35,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "thought", phrasePool: "new-tool-announcement" },
			{ type: "mood-change", target: "targets", mood: "curious" },
		],
	},
	{
		id: "fire-drill",
		category: "reactive",
		action: "fire-drill",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "urgent"],
		priority: 80,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "emote", phrasePool: "reactive:fire-drill" },
			{ type: "need-change", target: "targets", need: "focus", amount: -8 },
			{ type: "mood-change", target: "targets", mood: "alert" },
			{ type: "room-mood-shift", mood: "disrupted", amount: -3 },
		],
	},
	{
		id: "spontaneous-music",
		category: "playful",
		action: "spontaneous-music",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["playful", "environment", "ambient"],
		priority: 15,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "emote", phrasePool: "spontaneous-music" },
			{ type: "need-change", target: "targets", need: "morale", amount: 3 },
			{ type: "mood-change", target: "targets", mood: "upbeat" },
		],
	},
	{
		id: "coffee-machine-broken",
		category: "reactive",
		action: "coffee-machine-broken",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["reactive", "environment", "humor"],
		priority: 30,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "speech", phrasePool: "coffee-machine-broken" },
			{ type: "need-change", target: "targets", need: "energy", amount: -3 },
			{ type: "mood-change", target: "targets", mood: "dismayed" },
		],
	},
] as const;
