import type { InteractionTemplate } from "../interaction-types.js";

export const ENVIRONMENT_EVENT_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "build-break-reaction",
		category: "reactive",
		action: "build-break-reaction",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "build"],
		priority: 80,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "thought", phrasePool: "reactive:focus-lost" },
			{ type: "need-change", target: "targets", need: "focus", amount: -5 },
			{ type: "mood-change", target: "targets", mood: "concerned" },
		],
	},
	{
		id: "deploy-celebration",
		category: "reactive",
		action: "deploy-celebration",
		cardinality: "many-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "environment", "celebration"],
		priority: 75,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "all", bubbleKind: "emote", phrasePool: "reactive:morale-boost" },
			{ type: "need-change", target: "all", need: "morale", amount: 10 },
			{ type: "particle", target: "all", particleType: "confetti" },
		],
	},
	{
		id: "birthday-party",
		category: "social",
		action: "birthday-party",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "environment", "celebration"],
		priority: 50,
		cooldownMs: 86400000,
		duration: 0,
		effects: [
			{ type: "bubble", target: "targets", bubbleKind: "speech", phrasePool: "reactive:morale-boost" },
			{ type: "need-change", target: "targets", need: "morale", amount: 15 },
			{ type: "need-change", target: "all", need: "social", amount: 10 },
		],
	},
] as const;
