import type { InteractionTemplate } from "../interaction-types.js";

export const NPC_INTERACTION_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "merchant-pitch",
		category: "commerce",
		action: "merchant-pitch",
		cardinality: "one-to-one",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "proximity", maxDistance: 3 },
		],
		weight: 1,
		tags: ["commerce", "merchant"],
		priority: 55,
		cooldownMs: 60000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-pitch" },
		],
	},
	{
		id: "merchant-idle-grumble",
		category: "reactive",
		action: "merchant-idle-grumble",
		cardinality: "entity-to-environment",
		initiatorTypes: ["npc"],
		targetTypes: ["room"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "idle", "merchant"],
		priority: 10,
		cooldownMs: 45000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "thought", phrasePool: "merchant-idle-grumble" },
		],
	},
	{
		id: "merchant-comment-on-pair",
		category: "social",
		action: "merchant-comment-on-pair",
		cardinality: "one-to-many",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "proximity", maxDistance: 4 },
		],
		weight: 1,
		tags: ["social", "merchant", "observation"],
		priority: 15,
		cooldownMs: 90000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-comment-on-pair" },
		],
	},
	{
		id: "merchant-special-offer",
		category: "commerce",
		action: "merchant-special-offer",
		cardinality: "one-to-one",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["commerce", "merchant", "rare"],
		priority: 50,
		cooldownMs: 600000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-special-offer" },
			{ type: "mood-change", target: "targets", mood: "intrigued" },
		],
	},
	{
		id: "merchant-haggle",
		category: "commerce",
		action: "merchant-haggle",
		cardinality: "one-to-one",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["commerce", "merchant", "negotiation"],
		priority: 45,
		cooldownMs: 120000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-haggle" },
			{ type: "need-change", target: "targets", need: "social", amount: 3 },
		],
	},
	{
		id: "merchant-show-new-stock",
		category: "commerce",
		action: "merchant-show-new-stock",
		cardinality: "one-to-one",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["commerce", "merchant", "discovery"],
		priority: 40,
		cooldownMs: 180000,
		duration: 7000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-show-new-stock" },
			{ type: "mood-change", target: "targets", mood: "curious" },
		],
	},
	{
		id: "merchant-loyalty-thanks",
		category: "social",
		action: "merchant-loyalty-thanks",
		cardinality: "one-to-one",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "merchant", "gratitude"],
		priority: 30,
		cooldownMs: 300000,
		duration: 5000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-loyalty-thanks" },
			{ type: "affinity-change", target: "targets", amount: 3 },
		],
	},
	{
		id: "merchant-warn-of-danger",
		category: "reactive",
		action: "merchant-warn-of-danger",
		cardinality: "one-to-one",
		initiatorTypes: ["npc"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "merchant", "narrative"],
		priority: 60,
		cooldownMs: 600000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "speech", phrasePool: "merchant-warn-of-danger" },
			{ type: "mood-change", target: "targets", mood: "alert" },
		],
	},
] as const;
