import type { InteractionTemplate } from "../interaction-types.js";

export const PET_SOCIAL_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "zoomies-disruption",
		category: "playful",
		action: "zoomies-disruption",
		cardinality: "one-to-many",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "need-threshold", need: "energy", op: ">", value: 80 },
		],
		weight: 2,
		tags: ["playful", "pet", "disruption"],
		priority: 30,
		cooldownMs: 120000,
		duration: 6000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "thought", phrasePool: "reactive:zoomies" },
			{ type: "need-change", target: "targets", need: "social", amount: 5 },
		],
		chainTemplates: ["chase-sequence"],
		chainChance: 0.15,
	},
	{
		id: "sit-between",
		category: "social",
		action: "sit-between",
		cardinality: "one-to-many",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "proximity", maxDistance: 4 },
		],
		weight: 1,
		tags: ["social", "pet", "comfort"],
		priority: 40,
		cooldownMs: 180000,
		duration: 8000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "reactive:comfort" },
			{ type: "need-change", target: "targets", need: "morale", amount: 3 },
		],
	},
	{
		id: "comfort-sad-agent",
		category: "care",
		action: "comfort-sad-agent",
		cardinality: "one-to-one",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "need-threshold", need: "morale", op: "<", value: 20 },
		],
		weight: 3,
		tags: ["care", "pet", "empathy"],
		priority: 50,
		cooldownMs: 60000,
		duration: 10000,
		effects: [
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "reactive:comfort" },
			{ type: "need-change", target: "targets", need: "morale", amount: 8 },
			{ type: "affinity-change", target: "targets", amount: 3 },
		],
	},
	{
		id: "pet-proximity-comfort",
		category: "care",
		action: "pet-proximity-comfort",
		cardinality: "one-to-one",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 4,
		tags: ["care", "pet", "proximity", "ambient"],
		priority: 20,
		cooldownMs: 30000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "morale", amount: 3 },
			{ type: "bubble", target: "initiator", bubbleKind: "emote", phrasePool: "reactive:comfort" },
			{ type: "particle", target: "all", particleType: "hearts" },
		],
	},
	{
		id: "pet-catalyst-social",
		category: "social",
		action: "pet-catalyst-social",
		cardinality: "one-to-many",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["social", "pet", "catalyst"],
		priority: 25,
		cooldownMs: 120000,
		duration: 0,
		effects: [
			{ type: "affinity-change", target: "targets", amount: 2 },
			{ type: "need-change", target: "targets", need: "social", amount: 3 },
		],
	},
	{
		id: "pet-share-food",
		category: "care",
		action: "pet-share-food",
		cardinality: "one-to-one",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["care", "pet", "sharing", "food"],
		priority: 20,
		cooldownMs: 30000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "all", need: "hunger", amount: 10 },
			{ type: "need-change", target: "targets", need: "social", amount: 3 },
			{ type: "particle", target: "all", particleType: "hearts" },
		],
	},
	{
		id: "pet-share-drink",
		category: "care",
		action: "pet-share-drink",
		cardinality: "one-to-one",
		initiatorTypes: ["pet"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["care", "pet", "sharing", "drink"],
		priority: 20,
		cooldownMs: 30000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "all", need: "thirst", amount: 10 },
			{ type: "need-change", target: "targets", need: "social", amount: 3 },
			{ type: "particle", target: "all", particleType: "hearts" },
		],
	},
] as const;
