import type { InteractionTemplate } from "../interaction-types.js";

export const ROOM_REACTION_TEMPLATES: readonly InteractionTemplate[] = [
	{
		id: "crunch-time-pressure",
		category: "environmental",
		action: "crunch-time-pressure",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["afternoon-slump"] },
		],
		weight: 1,
		tags: ["environmental", "stress"],
		priority: 60,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "focus", amount: -3 },
			{ type: "room-mood-shift", mood: "tense", amount: -2 },
		],
	},
	{
		id: "celebration-vibe",
		category: "reactive",
		action: "celebration-vibe",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 1,
		tags: ["reactive", "celebration"],
		priority: 50,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "morale", amount: 5 },
			{ type: "room-mood-shift", mood: "festive", amount: 3 },
		],
	},
	{
		id: "quiet-focus",
		category: "environmental",
		action: "quiet-focus",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["productive-morning"] },
		],
		weight: 1,
		tags: ["environmental", "focus"],
		priority: 15,
		cooldownMs: 240000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "focus", amount: 3 },
		],
	},
	{
		id: "morning-energy-boost",
		category: "environmental",
		action: "morning-energy-boost",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["morning-arrival"] },
		],
		weight: 3,
		tags: ["environmental", "morning"],
		priority: 20,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "energy", amount: 5 },
			{ type: "mood-change", target: "targets", mood: "refreshed" },
		],
	},
	{
		id: "lunch-rush-chatter",
		category: "environmental",
		action: "lunch-rush-chatter",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["lunch"] },
		],
		weight: 3,
		tags: ["environmental", "lunch", "social"],
		priority: 25,
		cooldownMs: 240000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "social", amount: 4 },
			{ type: "need-change", target: "targets", need: "focus", amount: -2 },
		],
	},
	{
		id: "afternoon-slump-yawns",
		category: "environmental",
		action: "afternoon-slump-yawns",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["afternoon-slump"] },
		],
		weight: 4,
		tags: ["environmental", "fatigue"],
		priority: 20,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "energy", amount: -3 },
			{ type: "mood-change", target: "targets", mood: "drowsy" },
		],
	},
	{
		id: "end-of-day-wind-down",
		category: "environmental",
		action: "end-of-day-wind-down",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["evening-departure"] },
		],
		weight: 3,
		tags: ["environmental", "farewell"],
		priority: 20,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "energy", amount: -2 },
			{ type: "mood-change", target: "targets", mood: "winding-down" },
		],
	},
	{
		id: "late-night-solidarity",
		category: "environmental",
		action: "late-night-solidarity",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [
			{ type: "phase", phases: ["night-owl"] },
		],
		weight: 1,
		tags: ["environmental", "bonding", "rare"],
		priority: 25,
		cooldownMs: 600000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "social", amount: 5 },
			{ type: "affinity-change", target: "targets", amount: 2 },
		],
	},
	{
		id: "crowded-room-tension",
		category: "reactive",
		action: "crowded-room-tension",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["reactive", "environmental", "stress"],
		priority: 30,
		cooldownMs: 300000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "focus", amount: -2 },
			{ type: "room-mood-shift", mood: "cramped", amount: -1 },
		],
	},
	{
		id: "empty-room-peace",
		category: "environmental",
		action: "empty-room-peace",
		cardinality: "one-to-many",
		initiatorTypes: ["room"],
		targetTypes: ["agent"],
		prerequisites: [],
		weight: 2,
		tags: ["environmental", "quiet", "focus"],
		priority: 15,
		cooldownMs: 240000,
		duration: 0,
		effects: [
			{ type: "need-change", target: "targets", need: "focus", amount: 4 },
			{ type: "mood-change", target: "targets", mood: "peaceful" },
		],
	},
] as const;
