/**
 * template-engine.ts — LLM fallback content generation.
 *
 * Produces useful analysis for each goal type without requiring LLM.
 * Domain-layer pure. No I/O.
 */

import type { GoalType } from "../bt-types.js";

export interface TemplateContext {
	readonly goalType: GoalType;
	readonly fileName: string;
	readonly fileContent: string;
	readonly agentName: string;
	readonly persona: string | undefined;
	readonly mood: string;
	readonly timestamp: string;
}

function extractFrontmatter(content: string): Record<string, string> {
	const match = content.match(/^---\n([\s\S]*?)\n---/);
	if (!match) return {};
	const fields: Record<string, string> = {};
	for (const line of match[1].split("\n")) {
		const sep = line.indexOf(":");
		if (sep > 0) fields[line.slice(0, sep).trim()] = line.slice(sep + 1).trim();
	}
	return fields;
}

function extractHeadings(content: string): string[] {
	return content.split("\n").filter((l) => l.startsWith("#")).map((l) => l.replace(/^#+\s*/, ""));
}

function wordCount(content: string): number {
	return content.split(/\s+/).filter(Boolean).length;
}

function header(ctx: TemplateContext, title: string): string {
	const who = ctx.persona ?? ctx.agentName;
	return `# ${title}: ${ctx.fileName}\n\n*Generated by ${who} on ${ctx.timestamp}*\n*Mood: ${ctx.mood}*\n\n`;
}

function reviewTemplate(ctx: TemplateContext): string {
	const fm = extractFrontmatter(ctx.fileContent);
	const headings = extractHeadings(ctx.fileContent);
	const words = wordCount(ctx.fileContent);
	const status = fm.status ?? "unknown";

	let out = header(ctx, "Review");
	out += `## Summary\n\n`;
	out += `- **Status:** ${status}\n`;
	out += `- **${headings.length} sections** | ${words} words\n`;
	out += `- **Sections:** ${headings.join(", ") || "none"}\n\n`;

	const todos = (ctx.fileContent.match(/TODO|FIXME|HACK/gi) ?? []).length;
	if (todos > 0) out += `> **Warning:** ${todos} TODO/FIXME markers found.\n\n`;

	out += `## Assessment by ${ctx.persona ?? ctx.agentName}\n\n`;
	out += `Document is ${status}. Contains ${headings.length} sections spanning ${words} words.`;
	if (todos > 0) out += ` Flagged ${todos} open items that need attention.`;
	out += `\n`;
	return out;
}

function summarizeTemplate(ctx: TemplateContext): string {
	const headings = extractHeadings(ctx.fileContent);
	const words = wordCount(ctx.fileContent);
	const firstParagraph = ctx.fileContent.replace(/^---[\s\S]*?---\n*/, "").split("\n\n").find((p) => p.trim() && !p.startsWith("#")) ?? "";

	let out = header(ctx, "Summary");
	if (firstParagraph) out += `${firstParagraph.trim()}\n\n`;
	out += `## Sections\n\n`;
	for (const h of headings) out += `- ${h}\n`;
	out += `\n${words} words total.\n`;
	return out;
}

function planTemplate(ctx: TemplateContext): string {
	const headings = extractHeadings(ctx.fileContent);
	let out = header(ctx, "Plan");
	out += `## Action Items\n\n`;
	if (headings.length > 0) {
		headings.forEach((h, i) => { out += `${i + 1}. Review and address: ${h}\n`; });
	} else {
		out += `1. Analyze the contents of ${ctx.fileName}\n`;
		out += `2. Identify key action items\n`;
		out += `3. Prioritize and schedule work\n`;
	}
	out += `\n## Next Steps\n\nProceed through items in priority order.\n`;
	return out;
}

function implementTemplate(ctx: TemplateContext): string {
	let out = header(ctx, "Implementation Notes");
	out += `## Scope\n\nTarget file: \`${ctx.fileName}\`\n\n`;
	out += `## Approach\n\n`;
	out += `1. Read and understand current contents\n`;
	out += `2. Identify areas for modification\n`;
	out += `3. Apply changes incrementally\n`;
	out += `4. Verify changes against goals\n\n`;
	out += `## Notes\n\nGenerated without LLM assistance — manual review recommended.\n`;
	return out;
}

function monitorTemplate(ctx: TemplateContext): string {
	const fm = extractFrontmatter(ctx.fileContent);
	const words = wordCount(ctx.fileContent);
	const status = fm.status ?? "unknown";

	let out = header(ctx, "Status Check");
	out += `## Current State\n\n`;
	out += `- **File:** ${ctx.fileName}\n`;
	out += `- **Status:** ${status}\n`;
	out += `- **Size:** ${words} words\n`;
	out += `- **Checked at:** ${ctx.timestamp}\n\n`;
	out += `No anomalies detected in automated check.\n`;
	return out;
}

function reportTemplate(ctx: TemplateContext): string {
	const fm = extractFrontmatter(ctx.fileContent);
	const headings = extractHeadings(ctx.fileContent);
	const words = wordCount(ctx.fileContent);

	let out = header(ctx, "Report");
	out += `## File Metadata\n\n`;
	out += `| Property | Value |\n|----------|-------|\n`;
	out += `| File | ${ctx.fileName} |\n`;
	out += `| Words | ${words} |\n`;
	out += `| Sections | ${headings.length} |\n`;
	for (const [k, v] of Object.entries(fm)) out += `| ${k} | ${v} |\n`;
	out += `\n## Content Overview\n\n`;
	for (const h of headings) out += `- ${h}\n`;
	out += `\n`;
	return out;
}

const GENERATORS: Record<GoalType, (ctx: TemplateContext) => string> = {
	review: reviewTemplate,
	summarize: summarizeTemplate,
	plan: planTemplate,
	implement: implementTemplate,
	monitor: monitorTemplate,
	report: reportTemplate,
};

export function generateFromTemplate(ctx: TemplateContext): string {
	return GENERATORS[ctx.goalType](ctx);
}
